# -*- coding: utf-8 -*-
"""L4-IF.72 — ingest-from/extensions/.../wmi-extensions/wmi-schema-reference.md"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/extensions/develop-your-extensions/data-sources/wmi-extensions"

TRANS = {
    "* Reference": "* Справочник",
    "* 10-min read": "* Чтение: 10 мин",
    "* Updated on Nov 10, 2025": "* Обновлено 10 ноября 2025 г.",
    # intro
    "This is a general description of WMI data source-based extension YAML file and ways to declare metrics and dimensions you would like to collect using your extension.": "Это общее описание YAML-файла расширения на основе источника данных WMI и способов объявления метрик и измерений для сбора с помощью расширения.",
    'You can also try our WMI data source tutorial for a step-by-step guide on creating a WMI extension. For more information, see [WMI data source tutorial](/managed/ingest-from/extensions/develop-your-extensions/data-sources/wmi-extensions/wmi-tutorial "Learn about WMI extensions in the Extensions framework.").': 'Пошаговое руководство по созданию расширения WMI также доступно в разделе [Учебное руководство по источнику данных WMI](/managed/ingest-from/extensions/develop-your-extensions/data-sources/wmi-extensions/wmi-tutorial "Learn about WMI extensions in the Extensions framework.").',
    # Data scope
    "## Data scope": "## Область данных",
    "Create the inventory of the devices you'd like to reference in your extension, as well [WMI properties](#wql-queries) you'll use as the source for your metric and dimension values.": "Создайте перечень устройств, на которые ссылается расширение, а также [свойства WMI](#wql-queries), которые будут источником значений метрик и измерений.",
    "In our example, we create a simple extension collecting disk and network details data from your WMI monitored devices.": "В этом примере создаётся простое расширение, собирающее данные о дисках и сетевых параметрах с устройств под мониторингом WMI.",
    'Your WMI monitoring scope definition starts with the `wmi` YAML node. All the settings under the node pertain to the declared [data source type](/managed/ingest-from/extensions/concepts#data-source-type "Learn more about the concept of Dynatrace Extensions.") (in this case, WMI).': 'Определение области мониторинга WMI начинается с узла YAML `wmi`. Все параметры этого узла относятся к объявленному [типу источника данных](/managed/ingest-from/extensions/concepts#data-source-type "Подробнее о концепции Dynatrace Extensions.") (в данном случае WMI).',
    # WQL queries
    "## WQL queries": "## WQL-запросы",
    "WMI extensions rely on WMI namespaces and their classes. Your WMI extension extracts the dimension and metric values from WMI class properties using the [WQL queries](https://docs.microsoft.com/en-us/windows/win32/wmisdk/querying-with-wql).": "Расширения WMI используют пространства имён WMI и их классы. Расширение WMI извлекает значения измерений и метрик из свойств классов WMI с помощью [WQL-запросов](https://docs.microsoft.com/en-us/windows/win32/wmisdk/querying-with-wql).",
    "Most extension-related classes and properties reside in the `root\\civm2` namespace. To learn more about WMI namespaces and classes, see [Windows Management Instrumentation](https://docs.microsoft.com/en-us/windows/win32/wmisdk/wmi-start-page) in the Microsoft documentation.": "Большинство классов и свойств, связанных с расширениями, находятся в пространстве имён `root\\civm2`. Дополнительные сведения о пространствах имён и классах WMI см. в документации Microsoft: [Windows Management Instrumentation](https://docs.microsoft.com/en-us/windows/win32/wmisdk/wmi-start-page).",
    "In this example, we query the disk-related properties from the [`Win32_LogicalDisk`](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-logicaldisk) class (`DeviceID`, `FreeSpace`, and `Size`) in the `root\\cimv2` namespace (`wmiNamespace` defined at the group level) and we filter the results to drive C with some `FreeSpace` left. Filtering is achieved with a variable; see [monitoring configuration](#monitoring-configuration) below. The values queried from WMI are then assigned to dimension and metric values and ingested into Dynatrace.": "В этом примере из класса [`Win32_LogicalDisk`](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-logicaldisk) в пространстве имён `root\\cimv2` (`wmiNamespace` определён на уровне группы) запрашиваются свойства диска (`DeviceID`, `FreeSpace` и `Size`), а результаты фильтруются по диску C с ненулевым `FreeSpace`. Фильтрация реализована через переменную; см. [конфигурацию мониторинга](#monitoring-configuration) ниже. Значения, полученные из WMI, назначаются измерениям и метрикам и передаются в Dynatrace.",
    "### Example monitoring configuration for your WQL query": "### Пример конфигурации мониторинга для WQL-запроса",
    "This example shows how to pass the `deviceFilter` variable declared earlier in the `extension.yaml`.": "В этом примере показано, как передать переменную `deviceFilter`, объявленную ранее в `extension.yaml`.",
    # Dimensions
    "## Dimensions": "## Измерения",
    "For each level (extension, group, subgroup), you can define up to 25 dimensions.": "На каждом уровне (расширение, группа, подгруппа) можно определить до 25 измерений.",
    "### Dimension key": "### Ключ измерения",
    'The dimension key string must conform to the [metrics ingestion protocol](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#dimension-optional "Learn how the data ingestion protocol for Dynatrace Metrics API works.").': 'Строка ключа измерения должна соответствовать [протоколу приёма метрик](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#dimension-optional "Learn how the data ingestion protocol for Dynatrace Metrics API works.").',
    "### Dimension value": "### Значение измерения",
    "Apart from simply instructing the extension to extract a dimension value from a property, you can also use the following methods:": "Помимо простого извлечения значения измерения из свойства, можно использовать следующие методы:",
    "* WQL query extracted value. Prefix with `column:`.": "* Значение, извлечённое WQL-запросом. Используйте префикс `column:`.",
    "Note that you must first query the `DeviceID` property in a related group or subgroup to use it as the dimension value.": "Свойство `DeviceID` необходимо предварительно запросить в связанной группе или подгруппе, чтобы использовать его как значение измерения.",
    "* Plain text. Prefix with `const:`.": "* Простой текст. Используйте префикс `const:`.",
    "* Monitoring configuration defined variable. Prefix with `var:`.": "* Переменная, определённая в конфигурации мониторинга. Используйте префикс `var:`.",
    "* Monitoring configuration–defined device details, such as device IP address or port. Use `this:device.host`.": "* Сведения об устройстве, определённые в конфигурации мониторинга, такие как IP-адрес или порт устройства. Используйте `this:device.host`.",
    "### Use variables with dimensions": "### Использование переменных с измерениями",
    "If you want to make your extension dimension customizable with the data from the monitoring configuration, you can use variables that will be replaced by values passed from the monitoring configuration. To use variables, you must first declare them in your extension YAML file:": "Чтобы сделать измерение расширения настраиваемым с помощью данных из конфигурации мониторинга, используйте переменные, которые заменяются значениями из конфигурации мониторинга. Для работы с переменными необходимо сначала объявить их в YAML-файле расширения:",
    "Then you can reference them in the dimension definition. Prefix the variable name with `var`.": "После этого можно ссылаться на них в определении измерения. Добавьте к имени переменной префикс `var`.",
    "### Filter extracted dimensions": "### Фильтрация извлечённых измерений",
    "When extracting the dimension value, you can add filtering logic using [WQL queries](#wql-queries) that will result in reporting only the dimensions that match the filtering criteria.": "При извлечении значения измерения можно добавить логику фильтрации с помощью [WQL-запросов](#wql-queries), в результате чего будут передаваться только измерения, соответствующие критериям фильтрации.",
    "Define the filter as a query in the monitoring configuration and pass it to the extension as a [variable](#variables):": "Определите фильтр как запрос в конфигурации мониторинга и передайте его расширению в виде [переменной](#variables):",
    # Metrics
    "## Metrics": "## Метрики",
    "For each level (extension, group, subgroup), you can define up to 100 metrics.": "На каждом уровне (расширение, группа, подгруппа) можно определить до 100 метрик.",
    "For example:": "Например:",
    "### Metric key": "### Ключ метрики",
    'The metric key string must conform to the [metrics ingestion protocol](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#metric-key-required "Learn how the data ingestion protocol for Dynatrace Metrics API works.").': 'Строка ключа метрики должна соответствовать [протоколу приёма метрик](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#metric-key-required "Learn how the data ingestion protocol for Dynatrace Metrics API works.").',
    "For Dynatrace versions 1.215 and 1.217, a metric node requires the `id` parameter in place of 'key'. Starting with Dynatrace version 1.219, it is recommended to use the `key` parameter, as `id` will be considered as deprecated.": "В Dynatrace версий 1.215 и 1.217 узел метрики требует параметр `id` вместо `key`. Начиная с Dynatrace версии 1.219, рекомендуется использовать параметр `key`, так как `id` будет считаться устаревшим.",
    "#### Best practices for metric keys": "#### Рекомендации по ключам метрик",
    "The metrics you ingest into Dynatrace using your extension are just some of the thousands of metrics, built-in and custom, processed by Dynatrace. To make your metrics keys unique and easy to identify in Dynatrace, the best practice is to prefix the metric name with the extension name. This guarantees that the metric key is unique and you can easily appoint a metric to a particular extension in your environment.": "Метрики, передаваемые в Dynatrace с помощью расширения, являются частью тысяч встроенных и пользовательских метрик, обрабатываемых Dynatrace. Для уникальности и удобства идентификации ключей метрик рекомендуется добавлять к имени метрики префикс с именем расширения. Это гарантирует уникальность ключа метрики и позволяет легко отнести метрику к конкретному расширению в среде.",
    "### Metric value": "### Значение метрики",
    "The WMI property from which you want to extract the metric value.": "Свойство WMI, из которого извлекается значение метрики.",
    "### Type": "### Тип",
    'The Dynatrace Extensions framework supports metric payloads in the gauge (`gauge`) or count value (`count`) formats. For details, see [Metric payload](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#payload-required "Learn how the data ingestion protocol for Dynatrace Metrics API works."). To indicate the metric type, use the `type` attribute.': 'Платформа Dynatrace Extensions поддерживает нагрузку метрик в форматах gauge (`gauge`) или count (`count`). Дополнительные сведения см. в разделе [Нагрузка метрики](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#payload-required "Learn how the data ingestion protocol for Dynatrace Metrics API works."). Для указания типа метрики используйте атрибут `type`.',
    # Metric metadata
    "## Metric metadata": "## Метаданные метрик",
    'An Extension can define metadata for each metric available in Dynatrace. For example, you might want to add the metric display name and the unit, both of which can be used for filtering in the [Metrics browser](/managed/analyze-explore-automate/dashboards-classic/metrics-browser "Browse metrics with the Dynatrace metrics browser.").': 'Расширение может определять метаданные для каждой метрики, доступной в Dynatrace. Например, можно добавить отображаемое имя метрики и единицу измерения, которые используются для фильтрации в [браузере метрик](/managed/analyze-explore-automate/dashboards-classic/metrics-browser "Browse metrics with the Dynatrace metrics browser.").',
    "Define all metric metadata in the `metrics` section of the extension's YAML file to ensure it's correctly associated with the metric configuration.": "Определяйте все метаданные метрик в разделе `metrics` YAML-файла расширения, чтобы они корректно сопоставлялись с конфигурацией метрики.",
    # Feature set
    "## Feature set": "## Набор функций",
    "Feature sets are categories into which you organize the data collected by the extension. In this example, we create a WMI extension monitoring your devices and collecting metrics related to the transport protocol statistics and device disks. This is reflected by metrics organization into related feature sets `tcp` and `physicalDisks`.": "Наборы функций: категории, по которым организуются данные, собираемые расширением. В этом примере создаётся расширение WMI, выполняющее мониторинг устройств и собирающее метрики статистики транспортного протокола и дисков устройств. Это отражено в организации метрик по связанным наборам функций `tcp` и `physicalDisks`.",
    "When activating your extension using [monitoring configuration](#monitoring-configuration), you can limit monitoring to one of the feature sets. To work properly, the extension has to collect at least one metric after the activation.": "При активации расширения с помощью [конфигурации мониторинга](#monitoring-configuration) можно ограничить мониторинг одним из наборов функций. Для корректной работы расширение должно собирать хотя бы одну метрику после активации.",
    "In highly segmented networks, feature sets can reflect the segments of your environment. Then, when you create a monitoring configuration, you can select a feature set and a corresponding ActiveGate group that can connect to this particular segment.": "В сильно сегментированных сетях наборы функций могут отражать сегменты среды. При создании конфигурации мониторинга можно выбрать набор функций и соответствующую группу ActiveGate, которая может подключаться к этому сегменту.",
    "All metrics that aren't categorized into any feature set are considered to be the default and are always reported.": "Все метрики, не отнесённые ни к одному набору функций, считаются метриками по умолчанию и передаются всегда.",
    "A metric inherits the feature set of a subgroup, which in turn inherits the feature set of a group. Also, the feature set defined on the metric level overrides the feature set defined on the subgroup level, which in turn overrides the feature set defined on the group level.": "Метрика наследует набор функций подгруппы, которая, в свою очередь, наследует набор функций группы. При этом набор функций, определённый на уровне метрики, имеет приоритет над набором функций подгруппы, а набор функций подгруппы имеет приоритет над набором функций группы.",
    # Interval
    "## Interval": "## Интервал",
    "The interval at which the data measurement will be taken. You can define intervals at the group, subgroup, or individual metric level. You can define intervals with the granularity of one minute. The maximum interval is 2880 minutes (2 days, 48 hours).": "Интервал, с которым выполняются измерения данных. Интервалы можно определять на уровне группы, подгруппы или отдельной метрики с детализацией в одну минуту. Максимальный интервал составляет 2880 минут (2 дня, 48 часов).",
    "Setting the interval is not possible for JMX data sources.": "Для источников данных JMX установка интервала недоступна.",
    "The above format is supported starting with schema version 1.217. For earlier schema versions, use the following format (supported up to schema version 1.251):": "Приведённый формат поддерживается начиная со схемы версии 1.217. Для более ранних версий схемы используйте следующий формат (поддерживается до схемы версии 1.251):",
    # WMI monitoring configuration
    "## WMI monitoring configuration": "## Конфигурация мониторинга WMI",
    "After you define the scope of your configuration, you need to identify the network devices you'd like to collect data from and identify the ActiveGates that will execute the extension and connect to your devices.": "После определения области конфигурации необходимо указать сетевые устройства, с которых будут собираться данные, и ActiveGate, которые будут выполнять расширение и подключаться к устройствам.",
    'Make sure that all the ActiveGates from the ActiveGate group you\'ll define as the scope can connect to a respective data source. You can assign an ActiveGate to a group during or after installation. For more information, see [ActiveGate group](/managed/ingest-from/dynatrace-activegate/activegate-group "Understand the basic concepts of ActiveGate groups.").': 'Убедитесь, что все ActiveGate из группы ActiveGate, определённой как область, могут подключаться к соответствующему источнику данных. ActiveGate можно назначить в группу во время установки или после неё. Дополнительные сведения см. в разделе [Группа ActiveGate](/managed/ingest-from/dynatrace-activegate/activegate-group "Изучите основные концепции групп ActiveGate.").',
    'The monitoring configuration is a JSON payload defining the connection details, credentials, and feature sets that you want to monitor. For details, see [Start monitoring](/managed/upgrade/unavailable-in-managed "Your selection is unavailable in Dynatrace Managed.").': 'Конфигурация мониторинга: JSON-нагрузка, определяющая сведения о подключении, учётные данные и наборы функций для мониторинга. Дополнительные сведения см. в разделе [Начало мониторинга](/managed/upgrade/unavailable-in-managed "Your selection is unavailable in Dynatrace Managed.").',
    "Example payload to activate a WMI extension:": "Пример нагрузки для активации расширения WMI:",
    'When you have your initial extension YAML ready, package it, sign it, and upload it to your Dynatrace environment. For details, see [Manage extension lifecyle](/managed/upgrade/unavailable-in-managed "Your selection is unavailable in Dynatrace Managed.").': 'Когда первоначальный YAML расширения готов, упакуйте его, подпишите и загрузите в среду Dynatrace. Дополнительные сведения см. в разделе [Управление жизненным циклом расширения](/managed/upgrade/unavailable-in-managed "Your selection is unavailable in Dynatrace Managed.").',
    "The Dynatrace Hub-based extension activation wizard contains a dynamically updated JSON payload with your monitoring configuration": "Мастер активации расширений на базе Dynatrace Hub содержит динамически обновляемую JSON-нагрузку с конфигурацией мониторинга.",
    "Then you can use the Dynatrace API to download the schema for your extension that will help you create the JSON payload for your monitoring configuration.": "Затем можно использовать Dynatrace API для загрузки схемы расширения, которая поможет создать JSON-нагрузку для конфигурации мониторинга.",
    'Use the [GET an extension schema](/managed/dynatrace-api/environment-api/extensions-20/extensions/get-schema "View the schema of an extension the Dynatrace Extensions 2.0 API.") endpoint.': 'Используйте эндпоинт [GET схемы расширения](/managed/dynatrace-api/environment-api/extensions-20/extensions/get-schema "View the schema of an extension the Dynatrace Extensions 2.0 API.").',
    "Issue the following request:": "Выполните следующий запрос:",
    "Make sure to replace `{extension-name}` and `{extension-version}` with values from your extension YAML file. A successful call returns the JSON schema.": "Замените `{extension-name}` и `{extension-version}` значениями из YAML-файла расширения. При успешном вызове возвращается JSON-схема.",
    "### Scope": "### Область",
    'Note that each OneAgent or ActiveGate host running your extension needs the root certificate to verify the authenticity of your extension. For more information, see [Sign extension](/managed/ingest-from/extensions/develop-your-extensions/sign-extensions "Learn how to sign an extension, upload certificates and custom extensions, and configure certificate permissions using the Dynatrace Extensions Framework.").': 'Каждый хост OneAgent или ActiveGate, на котором выполняется расширение, требует наличия корневого сертификата для проверки подлинности расширения. Дополнительные сведения см. в разделе [Подписание расширения](/managed/ingest-from/extensions/develop-your-extensions/sign-extensions "Узнайте, как подписать расширение, загрузить сертификаты и пользовательские расширения и настроить разрешения сертификатов с помощью платформы Dynatrace Extensions Framework.").',
    "#### Remote extension": "#### Удалённое расширение",
    'For a remote extension, the scope is an ActiveGate group that will execute the extension. Only one ActiveGate from the group will run this monitoring configuration. If you plan to use a single ActiveGate, assign it to a dedicated group. You can assign an ActiveGate to a group during or after installation. For more information, see [ActiveGate group](/managed/ingest-from/dynatrace-activegate/activegate-group "Understand the basic concepts of ActiveGate groups.").': 'Для удалённого расширения областью является группа ActiveGate, которая будет выполнять расширение. Только один ActiveGate из группы будет запускать эту конфигурацию мониторинга. Если планируется использовать один ActiveGate, назначьте его в выделенную группу. ActiveGate можно назначить в группу во время установки или после неё. Дополнительные сведения см. в разделе [Группа ActiveGate](/managed/ingest-from/dynatrace-activegate/activegate-group "Изучите основные концепции групп ActiveGate.").',
    "Use the following format when defining the ActiveGate group:": "При определении группы ActiveGate используйте следующий формат:",
    "Replace `<ActiveGate-group-name>` with the actual name.": "Замените `<ActiveGate-group-name>` фактическим именем.",
    "#### Local extension": "#### Локальное расширение",
    "For a local extension, the scope is a host, host group, management zone, or environment for which you will execute the extension.": "Для локального расширения областью является хост, группа хостов, зона управления или среда, в которой будет выполняться расширение.",
    "* When defining a host as the scope, use this format:": "* При определении хоста как области используйте следующий формат:",
    "Replace `<HOST_ID>` with the entity ID of the host as in this example:": "Замените `<HOST_ID>` идентификатором сущности хоста, как в этом примере:",
    "* When defining a host group as the scope, use this format:": "* При определении группы хостов как области используйте следующий формат:",
    "Replace `<HOST_GROUP_ID>` with the entity ID of the host group as in this example:": "Замените `<HOST_GROUP_ID>` идентификатором сущности группы хостов, как в этом примере:",
    'You can find the host group ID in the [host group settings page](/managed/observe/infrastructure-observability/hosts/configuration/organize-your-environment-using-host-groups "Find out how Dynatrace enables you to organize your hosts, processes, and services using host groups.") URL. For example:': 'Идентификатор группы хостов можно найти в URL страницы [настроек группы хостов](/managed/observe/infrastructure-observability/hosts/configuration/organize-your-environment-using-host-groups "Find out how Dynatrace enables you to organize your hosts, processes, and services using host groups."). Например:',
    "* When defining a management zone as the scope, use this format:": "* При определении зоны управления как области используйте следующий формат:",
    "Replace `<MANAGEMENT-ZONE>` with the management zone name as in this example:": "Замените `<MANAGEMENT-ZONE>` именем зоны управления, как в этом примере:",
    'You can find the management zone in the [management zones page](/managed/manage/identity-access-management/permission-management/management-zones/apply-and-use-management-zones "Apply management zones to organize your Dynatrace environment and control user access to specific data.").': 'Зону управления можно найти на [странице зон управления](/managed/manage/identity-access-management/permission-management/management-zones/apply-and-use-management-zones "Apply management zones to organize your Dynatrace environment and control user access to specific data.").',
    "* When defining an environment as the scope, use this format:": "* При определении среды как области используйте следующий формат:",
    "You can also add tags to filter the hosts that this configuration will run on:": "Также можно добавить теги для фильтрации хостов, на которых будет применяться эта конфигурация:",
    "### Version": "### Версия",
    "Version of this monitoring configuration. Note that a single extension can run multiple monitoring configurations.": "Версия данной конфигурации мониторинга. Одно расширение может выполняться с несколькими конфигурациями мониторинга.",
    "### Description": "### Описание",
    "Human-readable description of the specifics of this monitoring configuration.": "Описание конфигурации мониторинга в удобочитаемом виде.",
    "### Enabled": "### Включено",
    "If set to `true`, the configuration is active and Dynatrace starts monitoring immediately.": "Если установлено значение `true`, конфигурация активна и Dynatrace немедленно начинает мониторинг.",
    "### Activation context": "### Контекст активации",
    "Set `activationContext` to `REMOTE` for remote extensions and to `LOCAL` for local extensions.": "Установите для `activationContext` значение `REMOTE` для удалённых расширений и `LOCAL` для локальных расширений.",
    "### Devices": "### Устройства",
    "Remote extensions only.": "Только для удалённых расширений.",
    "You can define up to 100 devices in a single monitoring configuration in the `wmiRemote` section. To define a device, add the following details:": "В одной конфигурации мониторинга в разделе `wmiRemote` можно определить до 100 устройств. Для определения устройства укажите следующие сведения:",
    "* Host": "* Хост",
    "* Authentication credentials": "* Учётные данные аутентификации",
    "### Authentication": "### Аутентификация",
    "Authentication details passed to Dynatrace API when activating monitoring configuration are obfuscated and it's impossible to retrieve them.": "Сведения об аутентификации, передаваемые в Dynatrace API при активации конфигурации мониторинга, скрываются и не могут быть получены обратно.",
    "When authenticating your extension into a Windows host, the general Windows user management concepts apply. If an ActiveGate running the extension is in the same domain, you only need to provide a user name and password. You can also provide a domain, but remember to escape the backward slash (`\\`).": "При аутентификации расширения на хосте Windows применяются стандартные концепции управления пользователями Windows. Если ActiveGate, выполняющий расширение, находится в том же домене, достаточно указать имя пользователя и пароль. Можно также указать домен, не забыв экранировать обратную косую черту (`\\`).",
    "For example:": "Например:",
    "We recommend that you create a dedicated local user group or a user account on the target computer specifically for remote connections.": "Рекомендуется создать выделенную локальную группу пользователей или учётную запись на целевом компьютере специально для удалённых подключений.",
    "### Feature sets": "### Наборы функций",
    "Add a list of feature sets you want to monitor. To report all feature sets, add `all`.": "Добавьте список наборов функций для мониторинга. Чтобы передавать все наборы функций, укажите `all`.",
    "### Variables": "### Переменные",
    "If your extension declares variables, you can define values that will be passed as filters or plain strings to your extension. For more information, see [Use variables with dimensions](#declare-variables).": "Если расширение объявляет переменные, можно определить значения, которые передаются в расширение как фильтры или обычные строки. Дополнительные сведения см. в разделе [Использование переменных с измерениями](#declare-variables).",
}

PASS = {
    "title: WMI data source reference",
    "# WMI data source reference",
}

if __name__ == "__main__":
    build_one(REL, "wmi-schema-reference.md", TRANS, PASS)
    qa_one(REL, "wmi-schema-reference.md")
