# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/google-cloud-platform/gcp-integrations/gcp-functions"

TRANS = {
    "title: Set up OpenTelemetry monitoring for Google Cloud Functions": "title: Настройка мониторинга OpenTelemetry для Google Cloud Functions",
    "# Set up OpenTelemetry monitoring for Google Cloud Functions": "# Настройка мониторинга OpenTelemetry для Google Cloud Functions",
    "* How-to guide": "* Практическое руководство",
    "* 2-min read": "* Чтение: 2 мин",
    "* Updated on Mar 31, 2025": "* Обновлено 31 марта 2025 г.",
    "Dynatrace uses [OpenTelemetry](https://dt-url.net/y903u4j) to monitor Google Cloud Functions invocations.": "Dynatrace использует [OpenTelemetry](https://dt-url.net/y903u4j) для мониторинга вызовов Google Cloud Functions.",
    "For that purpose, Dynatrace provides language-specific packages—such as [`@dynatrace/opentelemetry-gcf` for Node.js](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-nodejs \"Monitor Google Cloud Functions with OpenTelemetry for Node.js and Dynatrace.\"), [`dynatrace-opentelemetry-gcf` for Python](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-python \"Monitor Google Cloud Functions with OpenTelemetry for Python and Dynatrace.\"), and [`Dynatrace.OpenTelemetry.Instrumentation.GoogleCloudFunctions` for .NET](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-dotnet \"Monitor Google Cloud Functions with OpenTelemetry for .NET and Dynatrace.\")—that can be used in combination with default OpenTelemetry SDKs and APIs.": "Для этого Dynatrace предоставляет пакеты для конкретных языков: [`@dynatrace/opentelemetry-gcf` для Node.js](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-nodejs \"Мониторинг Google Cloud Functions с OpenTelemetry для Node.js и Dynatrace.\"), [`dynatrace-opentelemetry-gcf` для Python](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-python \"Мониторинг Google Cloud Functions с OpenTelemetry для Python и Dynatrace.\") и [`Dynatrace.OpenTelemetry.Instrumentation.GoogleCloudFunctions` для .NET](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-dotnet \"Мониторинг Google Cloud Functions с OpenTelemetry для .NET и Dynatrace.\"), которые можно использовать совместно со стандартными OpenTelemetry SDK и API.",
    "## Prerequisites": "## Предварительные требования",
    "* Dynatrace version 1.240+": "* Dynatrace версии 1.240+",
    "* OneAgent version 1.193+ for all OneAgents participating in a trace": "* OneAgent версии 1.193+ для всех OneAgent, участвующих в трассировке",
    "* Go to **Settings** > **Preferences** > **OneAgent features** and activate the **Forward Tag 4 trace context extension** OneAgent feature.": "* Перейдите в **Settings** > **Preferences** > **OneAgent features** и активируйте функцию OneAgent **Forward Tag 4 trace context extension**.",
    "## Installation": "## Установка",
    "[![Step 1](https://dt-cdn.net/images/step-1-086e22066c.svg \"Step 1\")": "[![Шаг 1](https://dt-cdn.net/images/step-1-086e22066c.svg \"Шаг 1\")",
    "**Select a configuration method**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf#choose-config-method \"Monitor Google Cloud Functions with OpenTelemetry and Dynatrace.\")[![Step 2 optional](https://dt-cdn.net/images/dotted-step-2-8ae6982454.svg \"Step 2 optional\")": "**Выберите метод конфигурации**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf#choose-config-method \"Мониторинг Google Cloud Functions с OpenTelemetry и Dynatrace.\")[![Шаг 2 необязательный](https://dt-cdn.net/images/dotted-step-2-8ae6982454.svg \"Шаг 2 необязательный\")",
    "**Specify a Dynatrace API endpoint**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf#specify-endpoint \"Monitor Google Cloud Functions with OpenTelemetry and Dynatrace.\")[![Step 3](https://dt-cdn.net/images/step-3-350cf6c19a.svg \"Step 3\")": "**Укажите эндпоинт API Dynatrace**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf#specify-endpoint \"Мониторинг Google Cloud Functions с OpenTelemetry и Dynatrace.\")[![Шаг 3](https://dt-cdn.net/images/step-3-350cf6c19a.svg \"Шаг 3\")",
    "**Apply the configuration to your Google Cloud function**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf#apply-config \"Monitor Google Cloud Functions with OpenTelemetry and Dynatrace.\")[![Step 4](https://dt-cdn.net/images/step-4-3f89d67d41.svg \"Step 4\")": "**Примените конфигурацию к функции Google Cloud**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf#apply-config \"Мониторинг Google Cloud Functions с OpenTelemetry и Dynatrace.\")[![Шаг 4](https://dt-cdn.net/images/step-4-3f89d67d41.svg \"Шаг 4\")",
    "**Instrument the function code**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf#instrument-code \"Monitor Google Cloud Functions with OpenTelemetry and Dynatrace.\")": "**Инструментируйте код функции**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf#instrument-code \"Мониторинг Google Cloud Functions с OpenTelemetry и Dynatrace.\")",
    "## Step 1 Select a configuration method": "## Шаг 1 Выбор метода конфигурации",
    "1. In Dynatrace,  **Search** for **Deploy OneAgent** app and select it.": "1. В Dynatrace выполните поиск приложения **Deploy OneAgent** и выберите его.",
    "2. Under **Download Dynatrace OneAgent**, select **Set up** > **Google Cloud Functions**.": "2. В разделе **Download Dynatrace OneAgent** выберите **Set up** > **Google Cloud Functions**.",
    "3. On the **Enable Monitoring for Google Cloud Functions** page, under **How will you configure your Google Cloud Functions?**, select your preferred method from the dropdown menu. Make sure you set all properties for the selected method before copying the generated configuration snippets.": "3. На странице **Enable Monitoring for Google Cloud Functions**, в разделе **How will you configure your Google Cloud Functions?**, выберите нужный метод из выпадающего меню. Перед копированием сгенерированных фрагментов конфигурации убедитесь, что заданы все свойства для выбранного метода.",
    "## Step 2 optional Specify a Dynatrace API endpoint Optional": "## Шаг 2 (необязательно) Укажите эндпоинт API Dynatrace",
    "If you don't want to use the default public Dynatrace endpoint, specify a custom Dynatrace API endpoint where you want to receive monitoring data.": "Если использовать стандартный публичный эндпоинт Dynatrace не нужно, укажите пользовательский эндпоинт API Dynatrace для получения данных мониторинга.",
    "To reduce network latency, you typically deploy a Dynatrace ActiveGate close to (in the same region as) the Google Cloud function that you want to monitor.": "Для снижения сетевой задержки рекомендуется развёртывать Dynatrace ActiveGate рядом с отслеживаемой функцией Google Cloud (в том же регионе).",
    "### Step 3 Apply the configuration to your Google Cloud function": "### Шаг 3 Применение конфигурации к функции Google Cloud",
    "Configure with JSON file": "Конфигурация с помощью JSON-файла",
    "Copy the JSON snippet into a file named `dtconfig.json` located in the root folder of your Google Cloud Functions deployment.": "Скопируйте фрагмент JSON в файл `dtconfig.json`, расположенный в корневой папке развёртывания Google Cloud Functions.",
    "Configure with environment variables": "Конфигурация с помощью переменных окружения",
    "On **Enable Monitoring for Google Cloud Functions**, under **Use the following values to configure your monitored Google Cloud Functions**, there's a snippet with all required environment variables. Be sure to add these environment variables and their values to your Google Cloud function configuration. For details, see [Using environment variables](https://cloud.google.com/functions/docs/configuring/env-var).": "На странице **Enable Monitoring for Google Cloud Functions**, в разделе **Use the following values to configure your monitored Google Cloud Functions**, содержится фрагмент со всеми необходимыми переменными окружения. Обязательно добавьте эти переменные и их значения в конфигурацию функции Google Cloud. Подробнее см. [Using environment variables](https://cloud.google.com/functions/docs/configuring/env-var).",
    "## Step 4 Instrument the function code": "## Шаг 4 Инструментирование кода функции",
    "Adding the required API calls to monitor function invocations via OpenTelemetry is specific to languages and their respective OpenTelemetry distribution:": "Добавление необходимых API-вызовов для мониторинга вызовов функции через OpenTelemetry зависит от языка и соответствующего дистрибутива OpenTelemetry:",
    "* **Node.js:** [Integrate on Google Cloud Functions Node.js](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-nodejs \"Monitor Google Cloud Functions with OpenTelemetry for Node.js and Dynatrace.\")": "* **Node.js:** [Интеграция на Google Cloud Functions Node.js](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-nodejs \"Мониторинг Google Cloud Functions с OpenTelemetry для Node.js и Dynatrace.\")",
    "* **Python:** [Integrate on Google Cloud Functions Python](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-python \"Monitor Google Cloud Functions with OpenTelemetry for Python and Dynatrace.\")": "* **Python:** [Интеграция на Google Cloud Functions Python](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-python \"Мониторинг Google Cloud Functions с OpenTelemetry для Python и Dynatrace.\")",
    "* **Go:** [Integrate on Google Cloud Functions GoLang](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-go \"Monitor Google Cloud Functions with OpenTelemetry for Go and Dynatrace.\")": "* **Go:** [Интеграция на Google Cloud Functions GoLang](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-go \"Мониторинг Google Cloud Functions с OpenTelemetry для Go и Dynatrace.\")",
    "* **.NET:** [Integrate on Google Cloud Functions .NET](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-dotnet \"Monitor Google Cloud Functions with OpenTelemetry for .NET and Dynatrace.\")": "* **.NET:** [Интеграция на Google Cloud Functions .NET](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-dotnet \"Мониторинг Google Cloud Functions с OpenTelemetry для .NET и Dynatrace.\")",
    "## Known limitations": "## Известные ограничения",
    "The Dynatrace Google Cloud Functions integration doesn't capture the IP addresses of outgoing HTTP requests. If the called service isn't monitored with Dynatrace OneAgent, this results in **unmonitored hosts**.": "Интеграция Dynatrace для Google Cloud Functions не фиксирует IP-адреса исходящих HTTP-запросов. Если вызываемый сервис не отслеживается Dynatrace OneAgent, это приводит к появлению **немониторируемых хостов**.",
    "## Related topics": "## Связанные темы",
    "* [Set up Dynatrace on Google Cloud](/managed/ingest-from/google-cloud-platform \"Monitor Google Cloud with Dynatrace.\")": "* [Настройка Dynatrace в Google Cloud](/managed/ingest-from/google-cloud-platform \"Мониторинг Google Cloud с Dynatrace.\")",
    "* [OneAgent platform and capability support matrix](/managed/ingest-from/technology-support/oneagent-platform-and-capability-support-matrix \"Learn which capabilities are supported by OneAgent on different operating systems and platforms.\")": "* [Матрица поддержки платформ и возможностей OneAgent](/managed/ingest-from/technology-support/oneagent-platform-and-capability-support-matrix \"Узнайте, какие возможности поддерживает OneAgent на различных операционных системах и платформах.\")",
    "* [Google Cloud monitoring](https://www.dynatrace.com/technologies/google-cloud-monitoring/)": "* [Google Cloud monitoring](https://www.dynatrace.com/technologies/google-cloud-monitoring/)",
}

PASS = set()

build_one(REL, "opentelemetry-on-gcf.md", TRANS, PASS)
qa_one(REL, "opentelemetry-on-gcf.md")
