# -*- coding: utf-8 -*-
"""L4-IF.73 — ingest-from/microsoft-azure-services/azure-integrations/azure-appservice/integrate-oneagent-on-web-app-for-containers.md"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/microsoft-azure-services/azure-integrations/azure-appservice"

TT_AZURE = "Настройка и конфигурирование мониторинга для Microsoft Azure."
TT_CONTAINERS = "Узнайте, как установить, настроить, обновить и удалить OneAgent в контейнеризированных приложениях на Linux."
TT_MONITOR_ENV = "Познакомьтесь с окружениями мониторинга и научитесь с ними работать."
TT_ACTIVEGATE = "Ознакомьтесь с основными концепциями, связанными с ActiveGate."
TT_ONEAGENT_API = "Загрузите последнюю версию установщика OneAgent через Dynatrace API."
TT_NETZONES = "Узнайте, как работают сетевые зоны в Dynatrace."
TT_APPONLY = "Установите, обновите и удалите OneAgent в контейнерах для мониторинга только на уровне приложения."
TT_SVC_DET = "Узнайте, как Dynatrace Service Detection v1 обнаруживает и именует различные типы сервисов."
TT_TAGS = "Узнайте, как Dynatrace позволяет определять теги на основе переменных среды."
TT_METADATA = "Настройте собственные метаданные, связанные с процессами, исходя из уникальных потребностей вашей организации или среды."
TT_PG_DETECT = "Способы настройки обнаружения группы процессов"
TT_ONEAGENT_UPDATE = "Узнайте о различных способах обновления OneAgent на Linux."
TT_ONEAGENT_MATRIX = "Узнайте, какие возможности поддерживаются OneAgent в различных операционных системах и на разных платформах."
TT_AUTH = "Узнайте, как пройти аутентификацию для использования Dynatrace API."
TT_STARTUP = "Узнайте, как установить, настроить, обновить и удалить OneAgent в контейнеризированных приложениях на Linux."

TRANS = {
    "title: Integrate OneAgent on Azure App Service for Linux and containers": "title: Интеграция OneAgent в Azure App Service для Linux и контейнеров",
    "# Integrate OneAgent on Azure App Service for Linux and containers": "# Интеграция OneAgent в Azure App Service для Linux и контейнеров",
    "* How-to guide": "* Практическое руководство",
    "* 11-min read": "* Чтение: 11 мин",
    "* Updated on Apr 22, 2026": "* Обновлено 22 апреля 2026 г.",
    "Linux only": "Только Linux",
    "App Service on Linux supports two scenarios.": "App Service на Linux поддерживает два сценария.",
    "* **Bring your own code**": "* **Принесите собственный код**",
    "In the code scenario, App Service provides a base container that is maintained by the platform.": "В сценарии с кодом App Service предоставляет базовый контейнер, обслуживаемый платформой.",
    "This container targets:": "Этот контейнер ориентирован на:",
    "+ A development framework, such as .NET Core, PHP, or Node.js.": "+ фреймворк разработки, например .NET Core, PHP или Node.js;",
    "+ A version of that framework, such as .NET Core 3.0 or .NET Core 3.1.": "+ версию этого фреймворка, например .NET Core 3.0 или .NET Core 3.1.",
    "Follow the procedure on the **Built-in image** tab.": "Следуйте инструкциям на вкладке **Built-in image**.",
    "* **Bring your own container**": "* **Принесите собственный контейнер**",
    "In the container scenario, App Service provides a host where a custom container provided by the customer can execute.": "В сценарии с контейнером App Service предоставляет хост, на котором может выполняться пользовательский контейнер клиента.",
    f"For details on the differences between the two scenarios, see [Things you should know: Web Apps on Linux](https://dt-url.net/jm039gu).": f"Подробности о различиях между двумя сценариями см. в разделе [Что нужно знать: Web Apps на Linux](https://dt-url.net/jm039gu).",
    "To monitor App Services on Linux, you need to integrate OneAgent within your containerized application.": "Для мониторинга App Services на Linux необходимо интегрировать OneAgent в контейнеризированное приложение.",
    "Follow the procedure on the **Custom image** tab.": "Следуйте инструкциям на вкладке **Custom image**.",
    "Built-in image": "Встроенный образ",
    "Custom image": "Пользовательский образ",
    "## Integrate Dynatrace on built-in image": "## Интеграция Dynatrace в встроенный образ",
    f"Azure App Service for Linux allows you to customize its base container at runtime using a [startup script or script command](https://dt-url.net/z2234qa) that must be executed in a bash shell or [Azure Cloud Shell](https://dt-url.net/at034yy). The script can be configured in multiple ways.": f"Azure App Service для Linux позволяет настраивать базовый контейнер во время выполнения с помощью [скрипта запуска или команды](https://dt-url.net/z2234qa), которые должны выполняться в bash-оболочке или [Azure Cloud Shell](https://dt-url.net/at034yy). Скрипт можно настроить несколькими способами.",
    "### Set startup script command/file at creation time using Azure CLI": "### Настройка команды/файла скрипта запуска при создании с помощью Azure CLI",
    "### Set script command/file at creation time for an existing App Service": "### Настройка команды/файла скрипта для существующего App Service",
    "### Set script command/file using ARM template": "### Настройка команды/файла скрипта с помощью ARM-шаблона",
    f"Use the [appCommandLine](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-web?pivots=deployment-language-arm-template#siteconfig-1) property of your ARM template to set the startup script/command.": f"Используйте свойство [appCommandLine](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-web?pivots=deployment-language-arm-template#siteconfig-1) ARM-шаблона для задания скрипта/команды запуска.",
    "### Set startup script command/file in the Azure portal": "### Настройка команды/файла скрипта запуска на портале Azure",
    "![AppService Linux Portal Startup](https://dt-cdn.net/images/screenshot-2022-12-13-at-13-42-44-1109-8955530cdd.png)": "![AppService Linux Portal Startup](https://dt-cdn.net/images/screenshot-2022-12-13-at-13-42-44-1109-8955530cdd.png)",
    "AppService Linux Portal Startup": "Запуск AppService Linux Portal",
    "### Script or command?": "### Скрипт или команда?",
    "A startup script is the same as a startup command: it's a command that executes the script (remember to use the path of the script). However, this requires that you package the script along with your application. If you don't want to have this dependency, use startup commands.": "Скрипт запуска, это то же самое, что и команда запуска: это команда, выполняющая скрипт (не забудьте указать путь к скрипту). Однако для этого требуется упаковать скрипт вместе с приложением. Чтобы избежать этой зависимости, используйте команды запуска.",
    "The script/command is executed within the container init script, which is implemented differently on each technology stack.": "Скрипт/команда выполняется в рамках скрипта инициализации контейнера, который реализован по-разному для каждого технологического стека.",
    f"For details on startup commands, see the Azure App Service for Linux documentation on [What are the expected values for the Startup File section when I configure the runtime stack?](https://docs.microsoft.com/en-us/troubleshoot/azure/app-service/faqs-app-service-linux#what-are-the-expected-values-for-the-startup-file-section-when-i-configure-the-runtime-stack-)": f"Подробности о командах запуска см. в документации Azure App Service для Linux: [Какие значения ожидаются в разделе Startup File при настройке стека выполнения?](https://docs.microsoft.com/en-us/troubleshoot/azure/app-service/faqs-app-service-linux#what-are-the-expected-values-for-the-startup-file-section-when-i-configure-the-runtime-stack-)",
    "### Integrate Dynatrace using a startup script/command": "### Интеграция Dynatrace с помощью скрипта/команды запуска",
    "To integrate Dynatrace, the startup script/command needs to have access to a few variables.": "Для интеграции Dynatrace скрипту/команде запуска необходим доступ к нескольким переменным.",
    "| Parameter | Description |": "| Параметр | Описание |",
    "| --- | --- |": "| --- | --- |",
    f'| `$DT_ENDPOINT` | Your Dynatrace API server endpoint—use either your environment [cluster endpoint](/managed/discover-dynatrace/get-started/monitoring-environment "Understand and learn how to work with monitoring environments.") or an [ActiveGate address](/managed/ingest-from/dynatrace-activegate "Understand the basic concepts related to ActiveGate."). |': f'| `$DT_ENDPOINT` | Эндпоинт API-сервера Dynatrace: используйте [эндпоинт кластера](/managed/discover-dynatrace/get-started/monitoring-environment "{TT_MONITOR_ENV}") окружения или [адрес ActiveGate](/managed/ingest-from/dynatrace-activegate "{TT_ACTIVEGATE}"). |',
    f'| `$DT_API_TOKEN` | API Token to access the Dynatrace REST API—[create an API Token](/managed/dynatrace-api/basics/dynatrace-api-authentication "Find out how to get authenticated to use the Dynatrace API.") with the **InstallerDownload** scope. |': f'| `$DT_API_TOKEN` | API-токен для доступа к Dynatrace REST API. [Создайте API-токен](/managed/dynatrace-api/basics/dynatrace-api-authentication "{TT_AUTH}") с областью видимости **InstallerDownload**. |',
    f'| `$DT_INCLUDE` | Configure required code modules, depending on the used technology stack.  * `all` includes all available OneAgent code modules (`java`, `apache`, `nginx`, `nodejs`, `dotnet`, `php`, `go`, `sdk`), but it increases download package size. * Alternatively, choose identifiers appropriate to your application stack, such as `java`, `dotnet`, `nodejs`, or `php`.  For details, see [API documentation](/managed/dynatrace-api/environment-api/deployment/oneagent/download-oneagent-latest "Download the latest OneAgent installer via Dynatrace API."). |': f'| `$DT_INCLUDE` | Настройте необходимые модули кода в зависимости от используемого технологического стека.  * `all` включает все доступные модули кода OneAgent (`java`, `apache`, `nginx`, `nodejs`, `dotnet`, `php`, `go`, `sdk`), но увеличивает размер пакета загрузки. * Alternatively, choose identifiers appropriate to your application stack, such as `java`, `dotnet`, `nodejs`, or `php`.  Подробности см. в [документации API](/managed/dynatrace-api/environment-api/deployment/oneagent/download-oneagent-latest "{TT_ONEAGENT_API}"). |',
    f"| `$START_APP_CMD` | The command to start your application  [What are the expected values for the Startup File section when I configure the runtime stack?](https://docs.microsoft.com/en-us/troubleshoot/azure/app-service/faqs-app-service-linux#what-are-the-expected-values-for-the-startup-file-section-when-i-configure-the-runtime-stack-) |": f"| `$START_APP_CMD` | Команда для запуска приложения.  [Какие значения ожидаются в разделе Startup File при настройке стека выполнения?](https://docs.microsoft.com/en-us/troubleshoot/azure/app-service/faqs-app-service-linux#what-are-the-expected-values-for-the-startup-file-section-when-i-configure-the-runtime-stack-) |",
    "If you use a shell other than bash, make sure to adapt the script appropriately to the shell's character escape requirements.": "При использовании оболочки, отличной от bash, адаптируйте скрипт с учётом требований экранирования символов этой оболочки.",
    "You can do this in two ways.": "Это можно сделать двумя способами.",
    "* App service settings Recommended": "* Настройки App Service (рекомендуется)",
    "* Setting the values inline": "* Установка значений непосредственно в команде",
    "#### Monitoring PHP on NGINX": "#### Мониторинг PHP на NGINX",
    "To monitor both PHP-FPM and NGINX": "Для мониторинга PHP-FPM и NGINX одновременно",
    "1. Set `DT_INCLUDE` to `all`.": "1. Установите `DT_INCLUDE` в `all`.",
    "2. Use the startup script with two additional commands at the end.": "2. Используйте скрипт запуска с двумя дополнительными командами в конце.",
    "#### App service settings": "#### Настройки App Service",
    f"Set the values of the above parameters using [App Settings](https://dt-url.net/da239ts)—this is equivalent to setting environment variables—and then run this command.": f"Задайте значения указанных выше параметров через [App Settings](https://dt-url.net/da239ts): это эквивалентно установке переменных среды. Затем выполните следующую команду.",
    "Java Runtime stack": "Стек выполнения Java",
    "For apps running on the Java Runtime stack in Azure App Service, this installation method may not work as expected in some cases. For example, customers have reported issues with Alpine-based images, where the above command was interpreted as a single string rather than executed as a shell command. This caused the `&&` operator to be treated as part of the `wget` input instead of chaining commands.": "Для приложений, работающих в стеке Java Runtime на Azure App Service, этот метод установки может работать не так, как ожидается, в некоторых случаях. Например, поступали сообщения о проблемах с образами на основе Alpine, где приведённая команда интерпретировалась как единая строка, а не выполнялась как команда оболочки. Это приводило к тому, что оператор `&&` воспринимался как часть входных данных `wget`, а не как разделитель команд.",
    f'If you encounter this behavior, consider using an alternative approach to execute the script (such as a custom startup script or modifying a [custom image](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-appservice/integrate-oneagent-on-web-app-for-containers#install--custom-image "Learn how to install, configure, update, and uninstall OneAgent in containerized applications on Linux.")).': f'При возникновении такого поведения рассмотрите альтернативный способ выполнения скрипта (например, пользовательский скрипт запуска или изменение [пользовательского образа](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-appservice/integrate-oneagent-on-web-app-for-containers#install--custom-image "{TT_STARTUP}")).',
    "Alternatively, you can use the calling-only script below, which works for all Linux images.": "Также можно использовать приведённый ниже скрипт-вызыватель, который работает для всех образов Linux.",
    "#### Setting the values inline": "#### Установка значений непосредственно в команде",
    "You can set the needed variables only for the command that runs the OneAgent installer.": "Нужные переменные можно задать только для команды, запускающей установщик OneAgent.",
    "To do this, you need to set the values before the command as shown below.": "Для этого задайте значения перед командой, как показано ниже.",
    "Alternatively, you can use the startup file as shown below.": "Также можно использовать файл запуска, как показано ниже.",
    "### Example: Integrate into a node.js application using Azure CLI within a bash shell": "### Пример: интеграция в приложение Node.js с помощью Azure CLI в bash-оболочке",
    f'[![Step 1](https://dt-cdn.net/images/step-1-086e22066c.svg "Step 1")': f'[![Step 1](https://dt-cdn.net/images/step-1-086e22066c.svg "Шаг 1")',
    f'**Configure the startup command**](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-appservice/integrate-oneagent-on-web-app-for-containers#step-1 "Learn how to install, configure, update, and uninstall OneAgent in containerized applications on Linux.")[![Step 2](https://dt-cdn.net/images/step-2-1a1384627e.svg "Step 2")': f'**Настройте команду запуска**](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-appservice/integrate-oneagent-on-web-app-for-containers#step-1 "{TT_STARTUP}")[![Step 2](https://dt-cdn.net/images/step-2-1a1384627e.svg "Шаг 2")',
    f'**Restart the web application twice**](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-appservice/integrate-oneagent-on-web-app-for-containers#step-2 "Learn how to install, configure, update, and uninstall OneAgent in containerized applications on Linux.")': f'**Перезапустите веб-приложение дважды**](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-appservice/integrate-oneagent-on-web-app-for-containers#step-2 "{TT_STARTUP}")',
    "#### Step 1 Configure the startup command": "#### Шаг 1. Настройка команды запуска",
    "#### Step 2 Restart the web application twice": "#### Шаг 2. Двойной перезапуск веб-приложения",
    "After you configure the startup command, restart the web application **twice**.": "После настройки команды запуска перезапустите веб-приложение **дважды**.",
    "* Restart once to initialize OneAgent installation.": "* Перезапустите один раз для инициализации установки OneAgent.",
    "* Restart again to start OneAgent instrumenting your application.": "* Перезапустите повторно, чтобы OneAgent начал инструментирование приложения.",
    "## Integrate Dynatrace on custom image": "## Интеграция Dynatrace в пользовательский образ",
    "To integrate OneAgent with the application image, you have two options:": "Для интеграции OneAgent с образом приложения доступны два варианта:",
    "* [Integrate the OneAgent image layer provided by Dynatrace](#layer)": "* [Интеграция слоя образа OneAgent, предоставляемого Dynatrace](#layer)",
    "* [Download OneAgent artifacts at image build-time from Dynatrace REST API](#api)": "* [Загрузка артефактов OneAgent во время сборки образа из Dynatrace REST API](#api)",
    "### Option 1: Integrate using Dynatrace offered OneAgent image layer": "### Вариант 1: интеграция с использованием слоя образа OneAgent от Dynatrace",
    "This option requires that you have Docker v17.05+ installed on your computer.": "Для этого варианта необходимо установить Docker v17.05+ на компьютере.",
    "1. Sign in to Docker with your Dynatrace environment ID as the username and your PaaS token as the password.": "1. Войдите в Docker, используя идентификатор окружения Dynatrace в качестве имени пользователя и PaaS-токен в качестве пароля.",
    "2. Add the following lines to your application image Dockerfile, after the last `FROM` command.": "2. Добавьте следующие строки в Dockerfile образа приложения после последней команды `FROM`.",
    "Replace the following placeholders in the template.": "Замените следующие заполнители в шаблоне.",
    f'| `<ADDRESS>` | Your Dynatrace registry endpoint—use either your environment [cluster endpoint](/managed/discover-dynatrace/get-started/monitoring-environment "Understand and learn how to work with monitoring environments.") or an [ActiveGate address](/managed/ingest-from/dynatrace-activegate "Understand the basic concepts related to ActiveGate."). |': f'| `<ADDRESS>` | Эндпоинт реестра Dynatrace: используйте [эндпоинт кластера](/managed/discover-dynatrace/get-started/monitoring-environment "{TT_MONITOR_ENV}") окружения или [адрес ActiveGate](/managed/ingest-from/dynatrace-activegate "{TT_ACTIVEGATE}"). |',
    f'| `<TECHNOLOGY>` | Configure required code modules, depending on the used technology stack.  * `all` includes all available OneAgent code modules (`java`, `apache`, `nginx`, `nodejs`, `dotnet`, `php`, `go`, `sdk`), but it increases download package size. * Alternatively, choose identifiers appropriate to your application stack, such as `java`, `dotnet`, `nodejs`, or `php`.  For details, see the [API documentation](/managed/dynatrace-api/environment-api/deployment/oneagent/download-oneagent-latest "Download the latest OneAgent installer via Dynatrace API."). |': f'| `<TECHNOLOGY>` | Настройте необходимые модули кода в зависимости от используемого технологического стека.  * `all` включает все доступные модули кода OneAgent (`java`, `apache`, `nginx`, `nodejs`, `dotnet`, `php`, `go`, `sdk`), но увеличивает размер пакета загрузки. * Alternatively, choose identifiers appropriate to your application stack, such as `java`, `dotnet`, `nodejs`, or `php`.  Подробности см. в [документации API](/managed/dynatrace-api/environment-api/deployment/oneagent/download-oneagent-latest "{TT_ONEAGENT_API}"). |',
    "**What if my Docker image is based on Alpine Linux?**": "**Что делать, если образ Docker основан на Alpine Linux?**",
    "Dynatrace OneAgent supports Alpine Linux–based environments. To use an Alpine Linux compatible OneAgent, use image name `oneagent-codemodules-musl` (as shown in the adapted template below) instead of `oneagent-codemodules`.": "Dynatrace OneAgent поддерживает среды на основе Alpine Linux. Для использования совместимого с Alpine Linux OneAgent используйте имя образа `oneagent-codemodules-musl` (как показано в адаптированном шаблоне ниже) вместо `oneagent-codemodules`.",
    "3. Build your application image.": "3. Соберите образ приложения.",
    "Build the Docker image from your Dockerfile to use it in your Kubernetes environment.": "Соберите образ Docker из Dockerfile для использования в среде Kubernetes.",
    "4. Restart the web application **twice**.": "4. Перезапустите веб-приложение **дважды**.",
    "* Restart once to initialize the OneAgent install script.": "* Перезапустите один раз для инициализации скрипта установки OneAgent.",
    "* Restart again to start OneAgent on the host.": "* Перезапустите повторно для запуска OneAgent на хосте.",
    "### Option 2: Integrate using installer script from Dynatrace REST API": "### Вариант 2: интеграция с использованием скрипта установщика из Dynatrace REST API",
    "1. Add the following two lines to your Dockerfile.": "1. Добавьте следующие две строки в Dockerfile.",
    "Replace the following parameters in the template above.": "Замените следующие параметры в приведённом выше шаблоне.",
    f'| `<DT_ENDPOINT>` | Your Dynatrace API endpoint—use either your environment [cluster endpoint](/managed/discover-dynatrace/get-started/monitoring-environment "Understand and learn how to work with monitoring environments.") or an [ActiveGate address](/managed/ingest-from/dynatrace-activegate "Understand the basic concepts related to ActiveGate."). |': f'| `<DT_ENDPOINT>` | Эндпоинт Dynatrace API: используйте [эндпоинт кластера](/managed/discover-dynatrace/get-started/monitoring-environment "{TT_MONITOR_ENV}") окружения или [адрес ActiveGate](/managed/ingest-from/dynatrace-activegate "{TT_ACTIVEGATE}"). |',
    f'| `<DT_API_TOKEN>` | API Token to access the Dynatrace REST API—[create an API Token](/managed/dynatrace-api/basics/dynatrace-api-authentication "Find out how to get authenticated to use the Dynatrace API.") with the **InstallerDownload** scope. |': f'| `<DT_API_TOKEN>` | API-токен для доступа к Dynatrace REST API. [Создайте API-токен](/managed/dynatrace-api/basics/dynatrace-api-authentication "{TT_AUTH}") с областью видимости **InstallerDownload**. |',
    "| `<DT_FLAVOR>` | Configure the required architecture.  * `default` for standard, glibc-based Linux images * `musl` for Alpine Linux–based images |": "| `<DT_FLAVOR>` | Настройте необходимую архитектуру.  * `default` для стандартных образов Linux на основе glibc * `musl` для образов на основе Alpine Linux |",
    f'| `<DT_INCLUDE>` | Configure required code modules, depending on the used technology stack.  * `all` includes all available OneAgent code modules (`java`, `apache`, `nginx`, `nodejs`, `dotnet`, `php`, `go`, `sdk`), but it increases download package size. * Alternatively, choose identifiers appropriate to your application stack, such as `java`, `dotnet`, `nodejs`, or `php`.  For details, see the [API documentation](/managed/dynatrace-api/environment-api/deployment/oneagent/download-oneagent-latest "Download the latest OneAgent installer via Dynatrace API."). |': f'| `<DT_INCLUDE>` | Настройте необходимые модули кода в зависимости от используемого технологического стека.  * `all` включает все доступные модули кода OneAgent (`java`, `apache`, `nginx`, `nodejs`, `dotnet`, `php`, `go`, `sdk`), но увеличивает размер пакета загрузки. * Alternatively, choose identifiers appropriate to your application stack, such as `java`, `dotnet`, `nodejs`, or `php`.  Подробности см. в [документации API](/managed/dynatrace-api/environment-api/deployment/oneagent/download-oneagent-latest "{TT_ONEAGENT_API}"). |',
    "2. Build your application image.": "2. Соберите образ приложения.",
    "3. Restart the web application **twice**.": "3. Перезапустите веб-приложение **дважды**.",
    "## Additional configuration": "## Дополнительная настройка",
    "Use additional environment variables to configure OneAgent for troubleshooting or advanced networking. You can either set them via your App Service Application settings or, when using a custom container image, configure them within your application image Dockerfile.": "Используйте дополнительные переменные среды для настройки OneAgent при устранении неполадок или для расширенных сетевых конфигураций. Их можно задать через настройки приложения App Service или, при использовании пользовательского образа контейнера, в Dockerfile образа приложения.",
    "### Networking variables Optional": "### Сетевые переменные (необязательно)",
    f'| `DT_NETWORK_ZONE` | Specifies to use a network zone. For more information, see [network zones](/managed/manage/network-zones "Find out how network zones work in Dynatrace."). |': f'| `DT_NETWORK_ZONE` | Указывает используемую сетевую зону. Подробнее см. в разделе [Сетевые зоны](/managed/manage/network-zones "{TT_NETZONES}"). |',
    f'| `DT_PROXY` | When using a proxy, use this environment variable to pass proxy credentials. For more information, see [Set up OneAgent on containers for application-only monitoring](/managed/ingest-from/setup-on-container-platforms/docker/set-up-oneagent-on-containers-for-application-only-monitoring "Install, update, and uninstall OneAgent on containers for application-only monitoring."). |': f'| `DT_PROXY` | При использовании прокси-сервера используйте эту переменную среды для передачи учётных данных прокси. Подробнее см. в разделе [Настройка OneAgent в контейнерах для мониторинга только на уровне приложения](/managed/ingest-from/setup-on-container-platforms/docker/set-up-oneagent-on-containers-for-application-only-monitoring "{TT_APPONLY}"). |',
    "### Additional metadata for process grouping and service detection Optional": "### Дополнительные метаданные для группировки процессов и обнаружения сервисов (необязательно)",
    'When listing multiple tags, you need to put them in double quotes, for example: DT\\_TAGS="Tag1=Value1 Tag2=Value2".': 'При перечислении нескольких тегов заключайте их в двойные кавычки, например: DT\\_TAGS="Tag1=Value1 Tag2=Value2".',
    f'| `DT_LOCALTOVIRTUALHOSTNAME` | Multiple containers are sometimes detected as a single instance (localhost), leading to various problems in, for example, service detection or availability alerts. Use this environment variable to define a unique name for your container instance. For details, see [Service Detection v1](/managed/observe/application-observability/services/service-detection/service-detection-v1#adjusting-service-detection "Find out how Dynatrace Service Detection v1 detects and names different types of services.") |': f'| `DT_LOCALTOVIRTUALHOSTNAME` | Несколько контейнеров иногда определяются как один экземпляр (localhost), что приводит к различным проблемам, например при обнаружении сервисов или оповещениях о доступности. Используйте эту переменную среды для определения уникального имени экземпляра контейнера. Подробности см. в разделе [Обнаружение сервисов v1](/managed/observe/application-observability/services/service-detection/service-detection-v1#adjusting-service-detection "{TT_SVC_DET}") |',
    f'| `DT_APPLICATIONID` | Some technologies don\'t provide unique application names. In such cases, use this environment variable to provide a unique name. For more information, see [Web server naming issues](/managed/observe/application-observability/services/service-detection/service-detection-v1#web-server-naming-issues "Find out how Dynatrace Service Detection v1 detects and names different types of services."). |': f'| `DT_APPLICATIONID` | Некоторые технологии не предоставляют уникальных имён приложений. В таких случаях используйте эту переменную среды для задания уникального имени. Подробнее см. в разделе [Проблемы именования веб-сервера](/managed/observe/application-observability/services/service-detection/service-detection-v1#web-server-naming-issues "{TT_SVC_DET}"). |',
    f'| `DT_TAGS` | Applies [custom tags](/managed/manage/tags-and-metadata/setup/define-tags-based-on-environment-variables "Find out how Dynatrace enables you to define tags based on environment variables.") to your process group. |': f'| `DT_TAGS` | Применяет [пользовательские теги](/managed/manage/tags-and-metadata/setup/define-tags-based-on-environment-variables "{TT_TAGS}") к группе процессов. |',
    f'| `DT_CUSTOM_PROP` | Applies [custom metadata](/managed/observe/infrastructure-observability/process-groups/configuration/define-your-own-process-group-metadata "Configure your own process-related metadata based on the unique needs of your organization or environment.") to your process group. |': f'| `DT_CUSTOM_PROP` | Применяет [пользовательские метаданные](/managed/observe/infrastructure-observability/process-groups/configuration/define-your-own-process-group-metadata "{TT_METADATA}") к группе процессов. |',
    f'| `DT_CLUSTER_ID` | If the [process group detection rules](/managed/observe/infrastructure-observability/process-groups/configuration/pg-detection "Ways to customize process-group detection") won\'t work for your use case, use this environment variable to **group all processes with the same value**. |': f'| `DT_CLUSTER_ID` | Если [правила обнаружения групп процессов](/managed/observe/infrastructure-observability/process-groups/configuration/pg-detection "{TT_PG_DETECT}") не подходят для вашего случая, используйте эту переменную среды, чтобы **сгруппировать все процессы с одинаковым значением**. |',
    f'| `DT_NODE_ID` | If the [process group detection rules](/managed/observe/infrastructure-observability/process-groups/configuration/pg-detection "Ways to customize process-group detection") won\'t work for your use case, use this environment variable to **separate process group instances**. |': f'| `DT_NODE_ID` | Если [правила обнаружения групп процессов](/managed/observe/infrastructure-observability/process-groups/configuration/pg-detection "{TT_PG_DETECT}") не подходят для вашего случая, используйте эту переменную среды, чтобы **разделить экземпляры группы процессов**. |',
    "### Validating variables Optional": "### Проверочные переменные (необязательно)",
    "| `DT_LOGSTREAM` | Set this variable with `stdout` to configure the OneAgent to log errors to the console. To see additional OneAgent logs, set the log level with `DT_LOGLEVELCON` as follows. |": "| `DT_LOGSTREAM` | Установите значение `stdout`, чтобы настроить OneAgent на запись ошибок в консоль. Для просмотра дополнительных журналов OneAgent задайте уровень журналирования с помощью `DT_LOGLEVELCON`, как описано ниже. |",
    "| `DT_LOGLEVELCON` | Use this environment variable to define the console log level. Valid options are: `NONE`, `SEVERE`, and `INFO`. |": "| `DT_LOGLEVELCON` | Используйте эту переменную среды для определения уровня журналирования консоли. Допустимые значения: `NONE`, `SEVERE` и `INFO`. |",
    "### .NET-specific variables": "### Переменные для .NET",
    "This section contains variables only relevant for **.NET environments**.": "Этот раздел содержит переменные, относящиеся только к **средам .NET**.",
    "| `DT_AGENTACTIVE` | .NET-specific variable to configure OneAgent monitoring of .NET Framework and .NET Core applications. OneAgent .NET monitoring is active by default (`true`). To deactivate it, set `DT_AGENTACTIVE` to `false`. If you configure .NET monitoring using the .NET profiler environment variables, you need to set `DT_AGENTACTIVE` to `true` to activate it. |": "| `DT_AGENTACTIVE` | Переменная для .NET для настройки мониторинга приложений .NET Framework и .NET Core с помощью OneAgent. Мониторинг OneAgent для .NET активен по умолчанию (`true`). Для его отключения установите `DT_AGENTACTIVE` в `false`. Если мониторинг .NET настроен с помощью переменных среды профилировщика .NET, установите `DT_AGENTACTIVE` в `true` для его активации. |",
    "## Update OneAgent": "## Обновление OneAgent",
    "When an update is available, restart your application to update OneAgent.": "При появлении обновления перезапустите приложение для обновления OneAgent.",
    "Each time you want to leverage a new version of Dynatrace OneAgent, you need to rebuild your local OneAgent code modules and application image. Any newly started pods from this application image will be monitored with the latest version of OneAgent.": "Каждый раз при необходимости использовать новую версию Dynatrace OneAgent требуется пересобрать локальные модули кода OneAgent и образ приложения. Все вновь запущенные поды из этого образа приложения будут мониториться с последней версией OneAgent.",
    f'If you\'ve specified a default OneAgent installation version for new hosts and applications using [OneAgent update settings](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/update-oneagent-on-linux "Learn about the different ways to update OneAgent on Linux."), your web apps will be automatically monitored by the defined default version of OneAgent.': f'Если для новых хостов и приложений задана версия OneAgent по умолчанию с помощью [настроек обновления OneAgent](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/update-oneagent-on-linux "{TT_ONEAGENT_UPDATE}"), веб-приложения будут автоматически мониториться заданной версией OneAgent по умолчанию.',
    "## Uninstall OneAgent": "## Удаление OneAgent",
    "To uninstall OneAgent": "Порядок удаления OneAgent",
    "1. In Azure portal, go to your web application > **Configuration** > **General settings**.": "1. На портале Azure откройте веб-приложение и перейдите в **Configuration** > **General settings**.",
    "2. Remove your startup command (leave **Startup Command** empty).": "2. Удалите команду запуска (оставьте поле **Startup Command** пустым).",
    "3. Select **Save**.": "3. Нажмите **Save**.",
    "To uninstall OneAgent, remove references from above described Dynatrace integration from your application image and redeploy the application.": "Для удаления OneAgent уберите ссылки на описанную выше интеграцию Dynatrace из образа приложения и повторно разверните приложение.",
    "## Potential conflict with Application Insights": "## Возможный конфликт с Application Insights",
    "OneAgent may conflict with Azure Application Insights agents already instrumenting the application. If you don't see any monitoring data coming in, check if you have turned on Application Insights and re-try with Application Insights turned off.": "OneAgent может конфликтовать с агентами Azure Application Insights, уже инструментирующими приложение. Если данные мониторинга не поступают, проверьте, включён ли Application Insights, и повторите попытку с отключённым Application Insights.",
    "## Related topics": "## Связанные темы",
    f'* [Set up Dynatrace on Microsoft Azure](/managed/ingest-from/microsoft-azure-services "Set up and configure monitoring for Microsoft Azure.")': f'* [Настройка Dynatrace в Microsoft Azure](/managed/ingest-from/microsoft-azure-services "{TT_AZURE}")',
    f'* [OneAgent platform and capability support matrix](/managed/ingest-from/technology-support/oneagent-platform-and-capability-support-matrix "Learn which capabilities are supported by OneAgent on different operating systems and platforms.")': f'* [Матрица поддержки платформ и возможностей OneAgent](/managed/ingest-from/technology-support/oneagent-platform-and-capability-support-matrix "{TT_ONEAGENT_MATRIX}")',
}

PASS = {
    "| --- | --- |",
}

if __name__ == "__main__":
    build_one(REL, "integrate-oneagent-on-web-app-for-containers.md", TRANS, PASS)
    qa_one(REL, "integrate-oneagent-on-web-app-for-containers.md")
