# -*- coding: utf-8 -*-
"""L4-IF.72 — sql/sql-reference.md (UNIQUE big Reference page; no SHARED)."""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/extensions/develop-your-extensions/data-sources/sql"

TRANS = {
    # --- frontmatter / title / H1 ---
    "title: SQL data source reference": "title: Справочник по источнику данных SQL",
    "# SQL data source reference": "# Справочник по источнику данных SQL",
    # --- meta ---
    "* Reference": "* Справочник",
    "* 9-min read": "* Чтение: 9 мин",
    "* Updated on Mar 18, 2026": "* Обновлено 18 марта 2026 г.",
    # --- intro ---
    "This is a general description of the SQL data source based extension YAML file and ways to declare metrics and dimensions that you would like to collect using your extension.": "Это общее описание YAML-файла расширения на основе источника данных SQL и способов объявления метрик и измерений, которые нужно собирать с помощью расширения.",
    # --- ## Extension security ---
    "## Extension security": "## Безопасность расширений",
    "While the Extensions framework is secure, the security of your extensions also depends on how you develop them and manage them in your Dynatrace environment.": "Несмотря на то что платформа Extensions является безопасной, безопасность расширений также зависит от того, как вы их разрабатываете и управляете ими в среде Dynatrace.",
    "We recommend the following when developing custom SQL extensions:": "При разработке пользовательских SQL-расширений рекомендуется следующее:",
    "* Use a dedicated database user with read-only permissions in your monitoring configuration to prevent any unintentional changes to your database. Admin or system privileges must not be granted to the user.": "* Используйте выделенного пользователя базы данных с разрешениями только на чтение в конфигурации мониторинга, чтобы предотвратить непреднамеренные изменения в базе данных. Пользователю не должны предоставляться права администратора или системные права.",
    "### Security controls": "### Меры безопасности",
    "* Only `SELECT` queries are available": "* Доступны только запросы `SELECT`",
    "+ MySQL queries can also begin with `SHOW GLOBAL STATUS`": "+ Запросы MySQL также могут начинаться с `SHOW GLOBAL STATUS`",
    "* Only one query can be executed at a time": "* Одновременно может выполняться только один запрос",
    "* Queries containing comments are rejected": "* Запросы, содержащие комментарии, отклоняются",
    "* To prevent data integrity violations (manipulating, changing, or deleting data), the SQL data source executes the queries in rolled-back transactions. For this reason, databases that don't support transactions are not supported as a SQL data source.": "* Чтобы предотвратить нарушения целостности данных (манипулирование, изменение или удаление данных), источник данных SQL выполняет запросы в транзакциях с откатом. По этой причине базы данных, не поддерживающие транзакции, не поддерживаются в качестве источника данных SQL.",
    '* Make sure that the connection string used in the JDBC monitoring configuration doesn\'t expose any sensitive data. For more information, see [JDBC monitoring configuration](/managed/ingest-from/extensions/develop-your-extensions/data-sources/sql/jdbc-monitoring "JDBC extensions in the Extensions framework.").': '* Убедитесь, что строка подключения в конфигурации мониторинга JDBC не раскрывает конфиденциальные данные. Дополнительные сведения см. в разделе [Конфигурация мониторинга JDBC](/managed/ingest-from/extensions/develop-your-extensions/data-sources/sql/jdbc-monitoring "JDBC extensions in the Extensions framework.").',
    # --- ## Data scope ---
    "## Data scope": "## Область данных",
    "Create an inventory of the data you want to query from your database as the source for your metric and dimension values.": "Составьте перечень данных, которые нужно запрашивать из базы данных в качестве источника значений метрик и измерений.",
    "In our example, we create a simple extension collecting basic CPU performance details from an Oracle Database.": "В этом примере создаётся простое расширение, собирающее основные сведения о производительности ЦП из Oracle Database.",
    'Depending on the provider, your SQL monitoring scope definition starts with a dedicated YAML node. For Oracle Database, it\'s `sqloracle`. All the settings under the node pertain to the declared [data source type](/managed/ingest-from/extensions/concepts#data-source-type "Learn more about the concept of Dynatrace Extensions.") (in this case, SQL).': 'В зависимости от провайдера определение области мониторинга SQL начинается с выделенного YAML-узла. Для Oracle Database это `sqloracle`. Все параметры под этим узлом относятся к объявленному [типу источника данных](/managed/ingest-from/extensions/concepts#data-source-type "Подробнее о концепции Dynatrace Extensions.") (в данном случае SQL).',
    # --- ## JDBC connector ---
    "## JDBC connector": "## Коннектор JDBC",
    "Dynatrace Extensions SQL data source enables you to query any database allowing connections using the JDBC driver on top of all the database vendors supported by default. For such databases, some additional steps are required.": "Источник данных SQL платформы Dynatrace Extensions позволяет запрашивать любую базу данных, поддерживающую подключения через драйвер JDBC, в дополнение ко всем поставщикам баз данных, поддерживаемым по умолчанию. Для таких баз данных требуются дополнительные шаги.",
    "### Declare the JDBC connection in the extension YAML file": "### Объявление подключения JDBC в YAML-файле расширения",
    "1. Start the extension definition with the `jdbc` node.": "1. Начните определение расширения с узла `jdbc`.",
    "2. Declare the driver class name. For example `org.mariadb.jdbc.Driver`.": "2. Объявите имя класса драйвера. Например, `org.mariadb.jdbc.Driver`.",
    "3. Provide the pattern for the connection string and the validation message. They'll be used to validate the connection string provided by a user in the monitoring configuration.": "3. Укажите шаблон строки подключения и сообщение проверки. Они будут использоваться для проверки строки подключения, указанной пользователем в конфигурации мониторинга.",
    "4. Provide the most basic query that the extension will execute to validate the connectivity.": "4. Укажите самый простой запрос, который расширение будет выполнять для проверки подключения.",
    'Users running your extension will also need to upload a related JDBC driver to an ActiveGate belonging to the group designated to run your extension. For more information, see [JDBC monitoring configuration](/managed/ingest-from/extensions/develop-your-extensions/data-sources/sql/jdbc-monitoring#upload "JDBC extensions in the Extensions framework.").': 'Пользователям, запускающим расширение, также потребуется загрузить соответствующий драйвер JDBC на ActiveGate, входящий в группу, предназначенную для запуска расширения. Дополнительные сведения см. в разделе [Конфигурация мониторинга JDBC](/managed/ingest-from/extensions/develop-your-extensions/data-sources/sql/jdbc-monitoring#upload "JDBC extensions in the Extensions framework.").',
    # --- ## SQL queries ---
    "## SQL queries": "## SQL-запросы",
    "SQL extensions rely on SQL queries. The queries declared in your extension retrieve the values for your metrics and dimensions. To map query results to a metric, the column type must be numeric. If it's not numeric, you must cast it to a numeric type.": "SQL-расширения основаны на SQL-запросах. Запросы, объявленные в расширении, извлекают значения для метрик и измерений. Чтобы сопоставить результаты запроса с метрикой, тип столбца должен быть числовым. Если он не числовой, необходимо привести его к числовому типу.",
    "For example, the following SQL query returns the number of CPU cores.": "Например, следующий SQL-запрос возвращает количество ядер ЦП.",
    "You can use it in your extension and report the value returned by a query as the `com.dynatrace.extension.sql-oracle.cpu.cores` metric in Dynatrace.": "Его можно использовать в расширении и передавать значение, возвращаемое запросом, как метрику `com.dynatrace.extension.sql-oracle.cpu.cores` в Dynatrace.",
    "For security reasons the data source supports only a subset of the SQL language. See [Security controls](#security-controls) for more details.": "По соображениям безопасности источник данных поддерживает только подмножество языка SQL. Подробные сведения см. в разделе [Меры безопасности](#security-controls).",
    # --- ## Versioned SQL queries ---
    "## Versioned SQL queries": "## SQL-запросы с версионированием",
    "ActiveGate version 1.335+": "ActiveGate версии 1.335+",
    "Some SQL queries are valid only for specific database versions. To ensure your extension is compatible with different database versions, you can declare version-specific queries.": "Некоторые SQL-запросы допустимы только для определённых версий баз данных. Чтобы расширение было совместимо с различными версиями баз данных, можно объявить запросы для конкретных версий.",
    "Versioned queries are declared under the `queriesVersioned` node. For each versioned query, you can define a `query` and the `minDBVersion` it requires. If a database version matches more than one version-specific query, the query with the highest `minDBVersion` that is lower than (or equal to) the database version will be executed.": "Версионированные запросы объявляются в узле `queriesVersioned`. Для каждого версионированного запроса можно определить `query` и требуемый `minDBVersion`. Если версия базы данных соответствует нескольким запросам для конкретной версии, будет выполнен запрос с наибольшим значением `minDBVersion`, которое не превышает версию базы данных (или равно ей).",
    "If no versioned query matches the database version, or if versioned queries are not declared, the regular `query` defined for the group runs for all database versions.": "Если ни один версионированный запрос не соответствует версии базы данных или версионированные запросы не объявлены, для всех версий баз данных выполняется обычный `query`, определённый для группы.",
    # --- ## Query frequency ---
    "## Query frequency": "## Частота запросов",
    "You can set the frequency at which database provider is queried. If you don't set, the database provider is queried every minute by default.": "Можно задать частоту, с которой выполняется опрос поставщика базы данных. Если частота не задана, поставщик базы данных опрашивается каждую минуту по умолчанию.",
    "You can use one of the two exclusive properties to control when the database provider is queried, `interval` or `schedule`. You can define it at the group or subgroup level.": "Для управления временем опроса поставщика базы данных можно использовать одно из двух взаимоисключающих свойств: `interval` или `schedule`. Их можно определить на уровне группы или подгруппы.",
    "### Interval": "### Interval",
    "ActiveGate version 1.253+": "ActiveGate версии 1.253+",
    "The interval value accepts an integer value expressing minutes. For example, to query the database provider every 10 minutes, add the following entry:": "Значение интервала принимает целое число, выражающее минуты. Например, чтобы опрашивать поставщик базы данных каждые 10 минут, добавьте следующую запись:",
    "### Schedule": "### Schedule",
    "ActiveGate version 1.301+": "ActiveGate версии 1.301+",
    "You can use a cron expression to query your database provider using a schedule of your choice.": "Для опроса поставщика базы данных по выбранному расписанию можно использовать выражение cron.",
    "The expression must follow the Unix cron format:": "Выражение должно соответствовать формату cron Unix:",
    "The values also support lists (`1,2,3,4`), steps (`0-23/2`), and ranges (`2-5`).": "Значения также поддерживают списки (`1,2,3,4`), шаги (`0-23/2`) и диапазоны (`2-5`).",
    "The format doesn\x27t support specifying both a day-of-week and a day-of-month value. You must use the ‘?’ character in one of these fields.": "Формат не поддерживает одновременное указание дня недели и дня месяца. В одном из этих полей необходимо использовать символ «?».",
    "For example, to run a query at 12:00 on every week day (Monday-Friday), use the following entry:": "Например, чтобы выполнять запрос в 12:00 каждый рабочий день (с понедельника по пятницу), используйте следующую запись:",
    "### Let extension users control frequency": "### Предоставление пользователям расширения управления частотой",
    "ActiveGate version 1.303+": "ActiveGate версии 1.303+",
    "If you want to let your extension users control the frequency at which a database provider is queried, you can use variables instead of fixed values. Users will be able to define the variable value when activating the extensions.": "Если нужно разрешить пользователям расширения управлять частотой опроса поставщика базы данных, можно использовать переменные вместо фиксированных значений. Пользователи смогут задать значение переменной при активации расширений.",
    "Make sure you describe your variable context in detail, so that users understand how to set the variable value properly. You can also set the pattern to help users validate their entries.": "Подробно опишите контекст переменной, чтобы пользователи понимали, как правильно задать её значение. Также можно задать шаблон для проверки введённых пользователями значений.",
    "For example, to let user control the interval:": "Например, чтобы предоставить пользователю управление интервалом:",
    "1. First, declare the variable in your extension YAML file": "1. Сначала объявите переменную в YAML-файле расширения:",
    "2. Then, reference the variable instead of a fixed value in your extension YAML file": "2. Затем укажите ссылку на переменную вместо фиксированного значения в YAML-файле расширения:",
    'For more information on using variables, see [Extension YAML file](/managed/ingest-from/extensions/develop-your-extensions/extension-yaml#variables "Learn how to create an extension YAML file using the Extensions framework.")': 'Дополнительные сведения об использовании переменных см. в разделе [YAML-файл расширения](/managed/ingest-from/extensions/develop-your-extensions/extension-yaml#variables "Learn how to create an extension YAML file using the Extensions framework.")',
    # --- ## Timeouts ---
    "## Timeouts": "## Тайм-ауты",
    "When developing an extension, a timeout value can be specified for a given query at both group and subgroup levels. Timeouts are specified in seconds; the default value is `10`. The provided value must be a string, for example: `20`, `60`, `120`, and so on.": "При разработке расширения для заданного запроса можно указать значение тайм-аута как на уровне группы, так и на уровне подгруппы. Тайм-ауты указываются в секундах; значение по умолчанию: `10`. Указанное значение должно быть строкой, например: `20`, `60`, `120` и т. д.",
    'You can also use a reference to a variable to specify the timeout. For more information on using variables, see [Extension YAML file](/managed/ingest-from/extensions/develop-your-extensions/extension-yaml#variables "Learn how to create an extension YAML file using the Extensions framework.").': 'Также для указания тайм-аута можно использовать ссылку на переменную. Дополнительные сведения об использовании переменных см. в разделе [YAML-файл расширения](/managed/ingest-from/extensions/develop-your-extensions/extension-yaml#variables "Learn how to create an extension YAML file using the Extensions framework.").',
    "Important considerations when setting timeouts": "Важные аспекты при настройке тайм-аутов",
    "Specifying a custom timeout for a query changes how the data source executes it. All queries are executed in sequence by default, so the data source only needs to utilize a single database connection. With a custom timeout defined, the query will be executed in parallel, opening an additional connection to the database. This means that care must be taken when adding custom timeouts so that the extension does not open too many connections.": "Указание пользовательского тайм-аута для запроса изменяет способ его выполнения источником данных. По умолчанию все запросы выполняются последовательно, поэтому источнику данных требуется только одно подключение к базе данных. При определённом пользовательском тайм-ауте запрос будет выполняться параллельно, открывая дополнительное подключение к базе данных. Это означает, что при добавлении пользовательских тайм-аутов необходимо следить за тем, чтобы расширение не открывало слишком много подключений.",
    # --- ## Dimensions ---
    "## Dimensions": "## Измерения",
    "For each level (extension, group, subgroup), you can define up to 25 dimensions.": "Для каждого уровня (расширение, группа, подгруппа) можно определить до 25 измерений.",
    "A subgroup inherits the dimensions of its parent group. To ensure data propagation, when the parent group has a defined query, the subgroup will execute its query after the parent group finishes the first query execution.": "Подгруппа наследует измерения родительской группы. Чтобы обеспечить распространение данных, при наличии определённого запроса в родительской группе подгруппа выполнит свой запрос после завершения первого выполнения запроса родительской группы.",
    "### Dimension key": "### Ключ измерения",
    'The dimension key string must conform to the [metrics ingestion protocol](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#dimension-optional "Learn how the data ingestion protocol for Dynatrace Metrics API works.").': 'Строка ключа измерения должна соответствовать [протоколу приёма метрик](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#dimension-optional "Learn how the data ingestion protocol for Dynatrace Metrics API works.").',
    "### Dimension value": "### Значение измерения",
    "You use an SQL query to retrieve a value for your dimension (prefix with `col:`) or use a fixed string (prefix with `const:`). For example:": "Для получения значения измерения используется SQL-запрос (с префиксом `col:`) или фиксированная строка (с префиксом `const:`). Например:",
    "### Filter extracted metric lines": "### Фильтрация извлечённых строк метрик",
    "ActiveGate version 1.311+": "ActiveGate версии 1.311+",
    "You can add filtering logic at the dimension level. This will result in reporting only the metric whose dimension's value matches the filtering criteria.": "На уровне измерения можно добавить логику фильтрации. В результате будет передаваться только та метрика, значение измерения которой соответствует критериям фильтрации.",
    "If filters are set on more than one dimension, all filters have to match for a metric line to be created. Filtering logic does not modify the executed query.": "Если фильтры установлены для нескольких измерений, для создания строки метрики все фильтры должны совпасть. Логика фильтрации не изменяет выполняемый запрос.",
    'Filters can be set as a constant value or as a [variable](/managed/ingest-from/extensions/develop-your-extensions/extension-yaml#variables "Learn how to create an extension YAML file using the Extensions framework.").': 'Фильтры можно задать как константное значение или как [переменную](/managed/ingest-from/extensions/develop-your-extensions/extension-yaml#variables "Learn how to create an extension YAML file using the Extensions framework.").',
    "Define the filter based on a condition as follows:": "Определите фильтр на основе условия следующим образом:",
    "* **Starts with** – use a `const:$prefix` qualifier. Example:": "* **Starts with**: используйте квалификатор `const:$prefix`. Пример:",
    "* **Ends with** – use a `const:$suffix` qualifier. Example:": "* **Ends with**: используйте квалификатор `const:$suffix`. Пример:",
    "* **Contains** – use a `const:$contains` qualifier. Example:": "* **Contains**: используйте квалификатор `const:$contains`. Пример:",
    "* **Equals** – use a `const:$eq` qualifier. Example:": "* **Equals**: используйте квалификатор `const:$eq`. Пример:",
    "For the expressions mentioned above, you can also use qualifiers:": "Для перечисленных выше выражений также можно использовать следующие квалификаторы:",
    "+ `const:$and` – to chain two or more expressions with AND operator. Example:": "+ `const:$and`: объединение двух или более выражений с помощью оператора AND. Пример:",
    "+ a `const:$or` – to chain two or more expressions with OR operator. Example:": "+ `const:$or`: объединение двух или более выражений с помощью оператора OR. Пример:",
    "+ a `const:$not` – to negate an expression. Example:": "+ `const:$not`: отрицание выражения. Пример:",
    # --- ## Metrics ---
    "## Metrics": "## Метрики",
    "For each level (extension, group, subgroup), you can define up to 100 metrics.": "Для каждого уровня (расширение, группа, подгруппа) можно определить до 100 метрик.",
    "For example:": "Например:",
    "### Metric key": "### Ключ метрики",
    'The metric key string must conform to the [metrics ingestion protocol](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#metric-key-required "Learn how the data ingestion protocol for Dynatrace Metrics API works.").': 'Строка ключа метрики должна соответствовать [протоколу приёма метрик](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#metric-key-required "Learn how the data ingestion protocol for Dynatrace Metrics API works.").',
    "For Dynatrace versions 1.215 and 1.217, a metric node requires the `id` parameter in place of `key`. Starting with Dynatrace version 1.219, you should use the `key` parameter, as `id` will be considered deprecated.": "Для Dynatrace версий 1.215 и 1.217 узел метрики требует параметра `id` вместо `key`. Начиная с Dynatrace версии 1.219 следует использовать параметр `key`, поскольку `id` считается устаревшим.",
    "#### Best practices for metric keys": "#### Рекомендации по ключам метрик",
    "The metrics you ingest into Dynatrace using your extension are just some of the thousands of metrics, built-in and custom, processed by Dynatrace. To make your metrics keys unique and easy to identify in Dynatrace, the best practice is to prefix the metric name with the extension name. This guarantees that the metric key is unique and you can easily appoint a metric to a particular extension in your environment.": "Метрики, принимаемые в Dynatrace с помощью расширения, являются лишь частью тысяч встроенных и пользовательских метрик, обрабатываемых Dynatrace. Чтобы ключи метрик были уникальными и легко идентифицировались в Dynatrace, рекомендуется добавлять к имени метрики имя расширения в качестве префикса. Это гарантирует уникальность ключа метрики и возможность легко связать метрику с конкретным расширением в среде.",
    "### Metric value": "### Значение метрики",
    "The column value queried from your database.": "Значение столбца, запрошенное из базы данных.",
    "### Type": "### Тип",
    'The Dynatrace Extensions framework supports metric payloads in the gauge (`gauge`) or count value (`count`) formats. For details, see [Metric payload](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#payload-required "Learn how the data ingestion protocol for Dynatrace Metrics API works."). To indicate the metric type, use the `type` attribute.': 'Платформа Dynatrace Extensions поддерживает полезные нагрузки метрик в форматах gauge (`gauge`) или count (`count`). Подробные сведения см. в разделе [Полезная нагрузка метрики](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#payload-required "Learn how the data ingestion protocol for Dynatrace Metrics API works."). Для указания типа метрики используйте атрибут `type`.',
    # --- ## Metric metadata ---
    "## Metric metadata": "## Метаданные метрики",
    'An Extension can define metadata for each metric available in Dynatrace. For example, you might want to add the metric display name and the unit, both of which can be used for filtering in the [Metrics browser](/managed/analyze-explore-automate/dashboards-classic/metrics-browser "Browse metrics with the Dynatrace metrics browser.").': 'Расширение может определять метаданные для каждой метрики, доступной в Dynatrace. Например, можно добавить отображаемое имя метрики и единицу измерения, которые можно использовать для фильтрации в [браузере метрик](/managed/analyze-explore-automate/dashboards-classic/metrics-browser "Browse metrics with the Dynatrace metrics browser.").',
    "Define all metric metadata in the `metrics` section of the extension's YAML file to ensure it's correctly associated with the metric configuration.": "Определите все метаданные метрик в разделе `metrics` YAML-файла расширения, чтобы они были правильно связаны с конфигурацией метрики.",
    # --- ## Feature set ---
    "## Feature set": "## Набор функций",
    "Feature sets are categories into which you organize the data collected by the extension. In this example, we create an Oracle SQL extension collecting metrics related to CPU and Input/Output performance. This is reflected by the metrics organization into related feature sets `cpu` and `io`.": "Наборы функций: это категории, по которым организуются данные, собираемые расширением. В этом примере создаётся расширение Oracle SQL, собирающее метрики, связанные с производительностью ЦП и операций ввода/вывода. Это отражено в организации метрик по соответствующим наборам функций `cpu` и `io`.",
    "When activating your extension using [monitoring configuration](#monitoring-configuration), you can limit monitoring to one of the feature sets. To work properly, the extension has to collect at least one metric after the activation.": "При активации расширения с помощью [конфигурации мониторинга](#monitoring-configuration) мониторинг можно ограничить одним из наборов функций. Для корректной работы расширение должно собирать хотя бы одну метрику после активации.",
    "In highly segmented networks, feature sets can reflect the segments of your environment. Then, when you create a monitoring configuration, you can select a feature set and a corresponding ActiveGate group that can connect to this particular segment.": "В сильно сегментированных сетях наборы функций могут отражать сегменты среды. Затем при создании конфигурации мониторинга можно выбрать набор функций и соответствующую группу ActiveGate, которая может подключиться к этому конкретному сегменту.",
    "All metrics that aren't categorized into any feature set are considered to be the default and are always reported.": "Все метрики, не отнесённые ни к одному набору функций, считаются заданными по умолчанию и всегда передаются.",
    "A metric inherits the feature set of a subgroup, which in turn inherits the feature set of a group. Also, the feature set defined on the metric level overrides the feature set defined on the subgroup level, which in turn overrides the feature set defined on the group level.": "Метрика наследует набор функций подгруппы, которая, в свою очередь, наследует набор функций группы. Кроме того, набор функций, определённый на уровне метрики, переопределяет набор функций, определённый на уровне подгруппы, который, в свою очередь, переопределяет набор функций, определённый на уровне группы.",
    # --- ## Oracle SQL monitoring configuration ---
    "## Oracle SQL monitoring configuration": "## Конфигурация мониторинга Oracle SQL",
    "After you define the scope of your configuration, you need to identify the network devices you'd like to collect data from and identify the ActiveGates that will execute the extension and connect to your devices.": "После определения области конфигурации необходимо указать сетевые устройства, из которых нужно собирать данные, и ActiveGate, которые будут выполнять расширение и подключаться к устройствам.",
    'The monitoring configuration format depends on the database provider. For more information, see [Oracle Database monitoring configuration](/managed/ingest-from/extensions/develop-your-extensions/data-sources/sql/oracle-monitoring "Create and activate a monitoring configuration for an SQL data source based extension for Oracle Database.").': 'Формат конфигурации мониторинга зависит от поставщика базы данных. Дополнительные сведения см. в разделе [Конфигурация мониторинга Oracle Database](/managed/ingest-from/extensions/develop-your-extensions/data-sources/sql/oracle-monitoring "Create and activate a monitoring configuration for an SQL data source based extension for Oracle Database.").',
}

if __name__ == "__main__":
    build_one(REL, "sql-reference.md", TRANS)
    qa_one(REL, "sql-reference.md")
