# -*- coding: utf-8 -*-
"""L4-IF.65 builder: setup-on-k8s/reference/dynakube-parameters.md (single large file).

Deterministic line-parity engine (mirrors _build_meta_l4if58.py):
- line-parity (EN line count == RU line count),
- byte-identical code fences / blank lines / `---` / `source:` / `scraped:`,
- `.spec` field-path headings (`^#{1,4}\\s+\\`\\.spec[^\\`]*\\`$`) copied verbatim (EN anchors),
- table separators `| --- | ... |` copied verbatim,
- URL identity (link/anchor targets copied verbatim inside translated lines),
- LF endings, clean RU (no em-dash, no mojibake/BOM).

The EN file repeats the same `.spec.*` parameter tree ~6x (per DynaKube API version),
so there are only ~254 UNIQUE translatable lines. TRANS is keyed by the stripped EN
line; the engine reuses each translation across all repeats -> guaranteed consistency.
Any non-passthrough, non-spec, untranslated line raises SystemExit before writing.
"""

import os
import re

MOJI_RE = re.compile("[﻿]|ï»¿")
SPEC_HEAD_RE = re.compile(r"^#{1,4}\s+`\.spec[^`]*`$")
SEP_RE = re.compile(r"^\|(?:\s*-{3,}\s*\|)+$")

BASE = os.path.join(os.path.dirname(__file__), "..", "docs")
REL = "ingest-from/setup-on-k8s/reference/dynakube-parameters.md"

# ---------------------------------------------------------------------------
# TRANS: stripped EN line -> stripped RU line. Backticked identifiers, URLs,
# anchors, YAML keys, data-type values, feature.dynatrace.com/* kept EN.
TRANS = {
    # --- page header --------------------------------------------------------
    "title: DynaKube parameters for Dynatrace Operator": "title: Параметры DynaKube для Dynatrace Operator",
    "# DynaKube parameters for Dynatrace Operator": "# Параметры DynaKube для Dynatrace Operator",
    "* 57-min read": "* Чтение: 57 мин",
    "* Updated on Mar 16, 2026": "* Обновлено 16 марта 2026 г.",
    "This page will help you to understand and configure the DynaKube [Kubernetes Custom Resource](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/), enabling you to optimize your Dynatrace Operator setup according to your specific requirements.": "Эта страница поможет понять и настроить DynaKube [Kubernetes Custom Resource](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/), что позволит оптимизировать настройку Dynatrace Operator в соответствии с вашими конкретными требованиями.",
    "The table below specifies the required Dynatrace Operator versions corresponding to each DynaKube API version.": "В таблице ниже указаны необходимые версии Dynatrace Operator, соответствующие каждой версии API DynaKube.",
    "| DynaKube API version | Minimum Dynatrace Operator version | Maximum Dynatrace Operator version [1](#fn-1-1-def) |": "| Версия API DynaKube | Минимальная версия Dynatrace Operator | Максимальная версия Dynatrace Operator [1](#fn-1-1-def) |",
    "| `v1beta6` | 1.8 |  |": "| `v1beta6` | 1.8 |  |",
    "| `v1beta5` | 1.6 |  |": "| `v1beta5` | 1.6 |  |",
    "| `v1beta4` | 1.5 |  |": "| `v1beta4` | 1.5 |  |",
    "| `v1beta3` | 1.4 | 1.7 |": "| `v1beta3` | 1.4 | 1.7 |",
    "| `v1beta2` | 1.2 | 1.6 |": "| `v1beta2` | 1.2 | 1.6 |",
    "| `v1beta1` | All versions | 1.6 |": "| `v1beta1` | Все версии | 1.6 |",
    "The corresponding DynaKube API versions will be removed from the Dynatrace Operator in the subsequent minor or major release.": "Соответствующие версии API DynaKube будут удалены из Dynatrace Operator в следующем минорном или мажорном выпуске.",
    "See the DynaKube YAML samples on [GitHub](https://github.com/Dynatrace/dynatrace-operator/tree/v1.9.0/assets/samples/dynakube).": "См. примеры YAML для DynaKube на [GitHub](https://github.com/Dynatrace/dynatrace-operator/tree/v1.9.0/assets/samples/dynakube).",
    # API-version selector labels (kept EN identifiers)
    "v1beta6": "v1beta6",
    "v1beta5": "v1beta5",
    "v1beta4": "v1beta4",
    "v1beta3": "v1beta3",
    "v1beta2": "v1beta2",
    "v1beta1": "v1beta1",
    # --- version badges (kept EN byte-identical, corpus canon) --------------
    "Dynatrace Operator version 1.8.0+": "Dynatrace Operator version 1.8.0+",
    "Dynatrace Operator version 1.9.0+": "Dynatrace Operator version 1.9.0+",
    "Dynatrace Operator version 1.6.0+": "Dynatrace Operator version 1.6.0+",
    "Dynatrace Operator version 1.5.0+": "Dynatrace Operator version 1.5.0+",
    "Dynatrace Operator version 1.4.0+": "Dynatrace Operator version 1.4.0+",
    "Dynatrace Operator version 1.2.0 - 1.6.0": "Dynatrace Operator version 1.2.0 - 1.6.0",
    "Dynatrace Operator version <=1.6.0": "Dynatrace Operator version <=1.6.0",
    "Available with a future Dynatrace version.": "Доступно в будущей версии Dynatrace.",
    "Available with Dynatrace version 1.306 and OneAgent 1.305": "Доступно с версии Dynatrace 1.306 и OneAgent 1.305",
    # --- requirement / optionality bullets ----------------------------------
    "* `apiUrl` parameter is Required and immutable. Once set, it cannot be modified in an existing DynaKube.": "* Параметр `apiUrl` обязателен и неизменяем. После установки его нельзя изменить в существующем DynaKube.",
    "* `apiUrl` parameter is Required and immutable. Once set, it cannot be modified on an existing DynaKube.": "* Параметр `apiUrl` обязателен и неизменяем. После установки его нельзя изменить в существующем DynaKube.",
    "* `apiUrl` parameter is Required.": "* Параметр `apiUrl` обязателен.",
    "* All other parameters are Optional.": "* Все остальные параметры необязательны.",
    "* All parameters are Optional.": "* Все параметры необязательны.",
    "* All parameters besides `id` are Optional.": "* Все параметры, кроме `id`, необязательны.",
    "* All parameters in `.spec.kspm` are Optional.": "* Все параметры в `.spec.kspm` необязательны.",
    "* All parameters in `.spec.logMonitoring` are Optional.": "* Все параметры в `.spec.logMonitoring` необязательны.",
    "* `capabilities` parameter is Required.": "* Параметр `capabilities` обязателен.",
    "* `resources` and `group` parameters are Recommended.": "* Параметры `resources` и `group` рекомендуются.",
    "* `imageRef` parameter is Required.": "* Параметр `imageRef` обязателен.",
    "Recommended": "Рекомендуется",
    # --- footnotes / notices ------------------------------------------------
    "A custom certificate is required for this capability. See the `tlsSecretName` parameter for details.": "Для этой возможности требуется пользовательский сертификат. Подробнее см. параметр `tlsSecretName`.",
    "Deprecation notice": "Уведомление о прекращении поддержки",
    "DynaKube API version `v1beta2` is no longer available with Dynatrace Operator version 1.7.0+.": "Версия API DynaKube `v1beta2` больше не доступна в Dynatrace Operator версии 1.7.0+.",
    "DynaKube API version `v1beta1` is no longer available with Dynatrace Operator version 1.6.0+.": "Версия API DynaKube `v1beta1` больше не доступна в Dynatrace Operator версии 1.6.0+.",
    "DynaKube API version `v1beta1` is no longer available with Dynatrace Operator version 1.7.0+.": "Версия API DynaKube `v1beta1` больше не доступна в Dynatrace Operator версии 1.7.0+.",
    # --- table header rows --------------------------------------------------
    "| **Parameter** | **Description** | **Default value** | **Data type** |": "| **Параметр** | **Описание** | **Значение по умолчанию** | **Тип данных** |",
    "| Parameter | Description | Default value | Data type |": "| Параметр | Описание | Значение по умолчанию | Тип данных |",
    # --- .spec parameters ---------------------------------------------------
    '| `apiUrl` | Dynatrace `apiUrl`, including the `/api` path at the end.- For SaaS, set `YOUR_ENVIRONMENT_ID` to your environment ID.- For Managed, change the `apiUrl` address.For instructions on how to determine the environment ID and how to configure the apiUrl address, see [Environment ID](/managed/discover-dynatrace/get-started/monitoring-environment "Understand and learn how to work with monitoring environments.") | No default (required) | string |': '| `apiUrl` | `apiUrl` Dynatrace, включая путь `/api` в конце.- Для SaaS задайте `YOUR_ENVIRONMENT_ID` равным вашему ID окружения.- Для Managed измените адрес `apiUrl`.Инструкции по определению ID окружения и настройке адреса apiUrl см. в разделе [ID окружения](/managed/discover-dynatrace/get-started/monitoring-environment "Разберитесь и научитесь работать с окружениями мониторинга.") | Нет значения по умолчанию (обязательно) | string |',
    '| `apiUrl` | Dynatrace `apiUrl`, including the `/api` path at the end.- For SaaS, set `YOUR_ENVIRONMENT_ID` to your environment ID.- For Managed, change the `apiUrl` address.For instructions on how to determine the environment ID and how to configure the apiUrl address, see [Environment ID](/managed/discover-dynatrace/get-started/monitoring-environment "Understand and learn how to work with monitoring environments."). | No default (required) | string |': '| `apiUrl` | `apiUrl` Dynatrace, включая путь `/api` в конце.- Для SaaS задайте `YOUR_ENVIRONMENT_ID` равным вашему ID окружения.- Для Managed измените адрес `apiUrl`.Инструкции по определению ID окружения и настройке адреса apiUrl см. в разделе [ID окружения](/managed/discover-dynatrace/get-started/monitoring-environment "Разберитесь и научитесь работать с окружениями мониторинга."). | Нет значения по умолчанию (обязательно) | string |',
    '| `customPullSecret` | Defines a custom pull secret in case you use a private registry when pulling images from the Dynatrace environment.Note: For the [node image pull feature](/managed/ingest-from/setup-on-k8s/guides/deployment-and-configuration/node-image-pull "Configure node image pull") without the CSI driver, you must manually ensure that pull secrets are available on the injected pod. See [node image pull prerequisites](/managed/ingest-from/setup-on-k8s/guides/deployment-and-configuration/node-image-pull#prerequisites "Configure node image pull") for more details.To define a custom pull secret and learn about the expected behavior, see [Configure `customPullSecret`](/managed/ingest-from/setup-on-k8s/guides/container-registries/use-private-registry#create-pull-secret "Use a private registry"). | No default (optional) | string |': '| `customPullSecret` | Определяет пользовательский pull-секрет на случай использования приватного реестра при загрузке образов из окружения Dynatrace.Примечание: для [функции загрузки образа узла](/managed/ingest-from/setup-on-k8s/guides/deployment-and-configuration/node-image-pull "Настройка загрузки образа узла") без CSI driver необходимо вручную обеспечить наличие pull-секретов во внедрённом поде. Подробнее см. [предварительные требования для загрузки образа узла](/managed/ingest-from/setup-on-k8s/guides/deployment-and-configuration/node-image-pull#prerequisites "Настройка загрузки образа узла").Чтобы определить пользовательский pull-секрет и узнать об ожидаемом поведении, см. [Настройка `customPullSecret`](/managed/ingest-from/setup-on-k8s/guides/container-registries/use-private-registry#create-pull-secret "Использование приватного реестра"). | Нет значения по умолчанию (необязательно) | string |',
    "| `dynatraceApiRequestThreshold` | Minimum minutes between Dynatrace API requests. | 15 | integer |": "| `dynatraceApiRequestThreshold` | Минимальное число минут между запросами к API Dynatrace. | 15 | integer |",
    "| `enableIstio` | When enabled, and if Istio is installed on the Kubernetes environment, Dynatrace Operator will create the corresponding VirtualService and ServiceEntry objects to allow access to the Dynatrace Cluster from the OneAgent or ActiveGate.Disabled by default. | No default (optional) | boolean |": "| `enableIstio` | Когда включено и если Istio установлен в окружении Kubernetes, Dynatrace Operator создаёт соответствующие объекты VirtualService и ServiceEntry, чтобы разрешить доступ к Dynatrace Cluster от OneAgent или ActiveGate.Отключено по умолчанию. | Нет значения по умолчанию (необязательно) | boolean |",
    "| `enableIstio` | When enabled, and if Istio is installed on the Kubernetes environment, Dynatrace Operator will create the corresponding VirtualService and ServiceEntry objects to allow access to the Dynatrace Cluster from the OneAgent or ActiveGate. Disabled by default. | `false` | boolean |": "| `enableIstio` | Когда включено и если Istio установлен в окружении Kubernetes, Dynatrace Operator создаёт соответствующие объекты VirtualService и ServiceEntry, чтобы разрешить доступ к Dynatrace Cluster от OneAgent или ActiveGate. Отключено по умолчанию. | `false` | boolean |",
    "| `networkZone` | Sets a network zone for the OneAgent and ActiveGate Pods. | No default (optional) | string |": "| `networkZone` | Задаёт network zone для подов OneAgent и ActiveGate. | Нет значения по умолчанию (необязательно) | string |",
    "| `proxy` | Set custom proxy settings either directly or from a secret with the field `proxy`.Applies to Dynatrace Operator, ActiveGate, and OneAgents. | No default (optional) | DynaKubeProxy |": "| `proxy` | Задаёт пользовательские настройки proxy напрямую или из секрета с полем `proxy`.Применяется к Dynatrace Operator, ActiveGate и OneAgent. | Нет значения по умолчанию (необязательно) | DynaKubeProxy |",
    "| `proxy` | Set custom proxy settings either directly or from a secret with the field `proxy`.Applies to Dynatrace Operator, ActiveGate, and OneAgents. | No default (optional) | string |": "| `proxy` | Задаёт пользовательские настройки proxy напрямую или из секрета с полем `proxy`.Применяется к Dynatrace Operator, ActiveGate и OneAgent. | Нет значения по умолчанию (необязательно) | string |",
    "| `skipCertCheck` | Disable certificate check for the connection between Dynatrace Operator and the Dynatrace Cluster.Set to `true` if you want to skip certification validation checks. | No default (optional) | boolean |": "| `skipCertCheck` | Отключает проверку сертификата для соединения между Dynatrace Operator и Dynatrace Cluster.Установите `true`, если нужно пропустить проверки валидации сертификата. | Нет значения по умолчанию (необязательно) | boolean |",
    "| `skipCertCheck` | Disable certificate check for the connection between Dynatrace Operator and the Dynatrace Cluster.Set to `true` if you want to skip certification validation checks. | `false` | boolean |": "| `skipCertCheck` | Отключает проверку сертификата для соединения между Dynatrace Operator и Dynatrace Cluster.Установите `true`, если нужно пропустить проверки валидации сертификата. | `false` | boolean |",
    "| `tokens` | Name of the secret holding the tokens used for connecting to Dynatrace. | No default (optional) | string |": "| `tokens` | Имя секрета, содержащего токены для подключения к Dynatrace. | Нет значения по умолчанию (необязательно) | string |",
    "| `tokens` | Name of the secret holding the tokens. | Name of custom resource (`.metadata.name`) if unset | string |": "| `tokens` | Имя секрета, содержащего токены. | Имя пользовательского ресурса (`.metadata.name`), если не задано | string |",
    "| `trustedCAs` | Adds custom RootCAs from a configmap.The key to the data must be `certs`.This applies to Dynatrace Operator, OneAgent, and ActiveGate. | No default (optional) | string |": "| `trustedCAs` | Добавляет пользовательские RootCAs из configmap.Ключом к данным должен быть `certs`.Применяется к Dynatrace Operator, OneAgent и ActiveGate. | Нет значения по умолчанию (необязательно) | string |",
    "| `trustedCAs` | Adds custom RootCAs from a configmap. Put the certificate under `certs` within your configmap.This applies to Dynatrace Operator, OneAgent, and ActiveGate. | No default (optional) | string |": "| `trustedCAs` | Добавляет пользовательские RootCAs из configmap. Поместите сертификат под ключом `certs` в вашем configmap.Применяется к Dynatrace Operator, OneAgent и ActiveGate. | Нет значения по умолчанию (необязательно) | string |",
    # --- .spec.oneAgent -----------------------------------------------------
    "| `hostGroup` | Specify the name of the group to which you want to assign the host. This method is preferred over the now obsolete `--set-host-group` argument. If both settings are used, this field takes precedence over the `--set-host-group` argument. | No default (optional) | string |": "| `hostGroup` | Укажите имя группы, к которой нужно отнести хост. Этот способ предпочтительнее устаревшего аргумента `--set-host-group`. Если используются обе настройки, это поле имеет приоритет над аргументом `--set-host-group`. | Нет значения по умолчанию (необязательно) | string |",
    "| `codeModulesImage` | The OneAgent image that is used to inject into Pods | No default (optional) | string |": "| `codeModulesImage` | Образ OneAgent, используемый для внедрения в поды | Нет значения по умолчанию (необязательно) | string |",
    # --- common OneAgent/section params -------------------------------------
    "| `annotations` | Add custom OneAgent annotations. | No default (optional) | map[string]string |": "| `annotations` | Добавьте пользовательские аннотации OneAgent. | Нет значения по умолчанию (необязательно) | map[string]string |",
    '| `args` | Set additional arguments to the OneAgent installer.For available options, see [Linux custom installation](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/installation/customize-oneagent-installation-on-linux "Learn how to use the Linux installer with command line parameters.").For the list of limitations, see [Limitations](/managed/ingest-from/setup-on-container-platforms/docker/set-up-dynatrace-oneagent-as-docker-container#limitations "Install and update Dynatrace OneAgent as a Docker container."). | No default (optional) | []string |': '| `args` | Задайте дополнительные аргументы для установщика OneAgent.Доступные параметры см. в разделе [Пользовательская установка на Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/installation/customize-oneagent-installation-on-linux "Узнайте, как использовать установщик для Linux с параметрами командной строки.").Список ограничений см. в разделе [Ограничения](/managed/ingest-from/setup-on-container-platforms/docker/set-up-dynatrace-oneagent-as-docker-container#limitations "Установка и обновление Dynatrace OneAgent как контейнера Docker."). | Нет значения по умолчанию (необязательно) | []string |',
    "| `codeModulesImage` | Specifies the OneAgent CodeModules image used for injection into application pods. Updates are applied only when the image reference changes. If a floating tag (for example, `latest`) is used, new images pushed under the same tag are not automatically picked up on existing nodes. It is recommended to use a unique tag for each OneAgent CodeModule image version. |  |  |": "| `codeModulesImage` | Указывает образ OneAgent CodeModules, используемый для внедрения в поды приложений. Обновления применяются только при изменении ссылки на образ. Если используется плавающий тег (например, `latest`), новые образы, опубликованные под тем же тегом, не подхватываются автоматически на существующих узлах. Рекомендуется использовать уникальный тег для каждой версии образа OneAgent CodeModule. |  |  |",
    "| No default (optional) | string |  |  |": "| Нет значения по умолчанию (необязательно) | string |  |  |",
    "| `codeModulesImage` | Specifies the OneAgent CodeModules image used for injection into application pods. Updates are applied only when the image reference changes. If a floating tag (for example, `latest`) is used, new images pushed under the same tag are not automatically picked up on existing nodes. It is recommended to use a unique tag for each OneAgent CodeModule image version. | No default (optional) | string |": "| `codeModulesImage` | Указывает образ OneAgent CodeModules, используемый для внедрения в поды приложений. Обновления применяются только при изменении ссылки на образ. Если используется плавающий тег (например, `latest`), новые образы, опубликованные под тем же тегом, не подхватываются автоматически на существующих узлах. Рекомендуется использовать уникальный тег для каждой версии образа OneAgent CodeModule. | Нет значения по умолчанию (необязательно) | string |",
    "| `codeModulesImagePullPolicy` | Defines the image pull policy for the CodeModules image. When empty, the Kubernetes default applies. | No default (optional) | string |": "| `codeModulesImagePullPolicy` | Определяет политику загрузки образа для образа CodeModules. Если не задано, применяется значение по умолчанию Kubernetes. | Нет значения по умолчанию (необязательно) | string |",
    "| `dnsPolicy` | Set the DNS policy for OneAgent pods.For details, see [Pods DNS Policy](https://dt-url.net/2t2375a). | `ClusterFirstWithHostNet` | string |": "| `dnsPolicy` | Задайте политику DNS для подов OneAgent.Подробнее см. [Pods DNS Policy](https://dt-url.net/2t2375a). | `ClusterFirstWithHostNet` | string |",
    "| `dnsPolicy` | Set the DNS Policy for OneAgent pods.For details, see [Pods DNS Policy](https://dt-url.net/2t2375a). | `ClusterFirstWithHostNet` | string |": "| `dnsPolicy` | Задайте политику DNS для подов OneAgent.Подробнее см. [Pods DNS Policy](https://dt-url.net/2t2375a). | `ClusterFirstWithHostNet` | string |",
    "| `dnsPolicy` | Set the DNS Policy for OneAgent Pods.For details, see [Pods DNS Policy](https://dt-url.net/2t2375a). | `ClusterFirstWithHostNet` | string |": "| `dnsPolicy` | Задайте политику DNS для подов OneAgent.Подробнее см. [Pods DNS Policy](https://dt-url.net/2t2375a). | `ClusterFirstWithHostNet` | string |",
    "| `env` | Set additional environment variables for the OneAgent pods. | No default (optional) | []EnvVar |": "| `env` | Задайте дополнительные переменные окружения для подов OneAgent. | Нет значения по умолчанию (необязательно) | []EnvVar |",
    "| `env` | Set additional environment variables for the OneAgent Pods. | No default (optional) | []EnvVar |": "| `env` | Задайте дополнительные переменные окружения для подов OneAgent. | Нет значения по умолчанию (необязательно) | []EnvVar |",
    "| `image` | Use a custom OneAgent Docker image. | The image from the Dynatrace cluster. | string |": "| `image` | Используйте пользовательский образ Docker для OneAgent. | Образ из кластера Dynatrace. | string |",
    "| `image` | Use a custom OneAgent Docker image. Defaults to the image from the Dynatrace cluster. | Name of the image. | string |": "| `image` | Используйте пользовательский образ Docker для OneAgent. По умолчанию используется образ из кластера Dynatrace. | Имя образа. | string |",
    "| `imagePullPolicy` | Defines the image pull policy. When empty, the Kubernetes default applies. | No default (optional) | string |": "| `imagePullPolicy` | Определяет политику загрузки образа. Если не задано, применяется значение по умолчанию Kubernetes. | Нет значения по умолчанию (необязательно) | string |",
    "| `initResources` | Define resources requests and limits for the initContainer. For details, see [Managing resources for containers](https://dt-url.net/atc371q). | No default (optional) | ResourceRequirements |": "| `initResources` | Определите запросы и лимиты ресурсов для initContainer. Подробнее см. [Managing resources for containers](https://dt-url.net/atc371q). | Нет значения по умолчанию (необязательно) | ResourceRequirements |",
    "| `labels` | Your defined labels for OneAgent pods in order to structure workloads as desired. | No default (optional) | map[string]string |": "| `labels` | Заданные вами метки для подов OneAgent, чтобы структурировать рабочие нагрузки по необходимости. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `labels` | Your defined labels for OneAgent Pods in order to structure workloads as desired. | No default (optional) | map[string]string |": "| `labels` | Заданные вами метки для подов OneAgent, чтобы структурировать рабочие нагрузки по необходимости. | Нет значения по умолчанию (необязательно) | map[string]string |",
    '| `namespaceSelector` | The namespaces where you want Dynatrace Operator to inject.For more information, see [Configure monitoring for namespaces and Pods](/managed/ingest-from/setup-on-k8s/guides/deployment-and-configuration/monitoring-and-instrumentation/annotate "Configure monitoring for namespaces and pods"). | No default (optional) | LabelSelector |': '| `namespaceSelector` | Пространства имён, в которые должен внедряться Dynatrace Operator.Подробнее см. [Настройка мониторинга для пространств имён и подов](/managed/ingest-from/setup-on-k8s/guides/deployment-and-configuration/monitoring-and-instrumentation/annotate "Настройка мониторинга для пространств имён и подов"). | Нет значения по умолчанию (необязательно) | LabelSelector |',
    '| `namespaceSelector` | The namespaces where you want Dynatrace Operator to inject. For more information, see [Configure monitoring for namespaces and Pods](/managed/ingest-from/setup-on-k8s/guides/deployment-and-configuration/monitoring-and-instrumentation/annotate "Configure monitoring for namespaces and pods"). | No default (optional) | LabelSelector |': '| `namespaceSelector` | Пространства имён, в которые должен внедряться Dynatrace Operator. Подробнее см. [Настройка мониторинга для пространств имён и подов](/managed/ingest-from/setup-on-k8s/guides/deployment-and-configuration/monitoring-and-instrumentation/annotate "Настройка мониторинга для пространств имён и подов"). | Нет значения по умолчанию (необязательно) | LabelSelector |',
    '| `namespaceSelector` | Applicable only for `applicationMonitoring` or `cloudNativeFullStack` configuration types. The namespaces where you want Dynatrace Operator to inject. For more information, see [Configure monitoring for namespaces and Pods](/managed/ingest-from/setup-on-k8s/guides/deployment-and-configuration/monitoring-and-instrumentation/annotate "Configure monitoring for namespaces and pods"). | No default (optional) | LabelSelector |': '| `namespaceSelector` | Применимо только для типов конфигурации `applicationMonitoring` или `cloudNativeFullStack`. Пространства имён, в которые должен внедряться Dynatrace Operator. Подробнее см. [Настройка мониторинга для пространств имён и подов](/managed/ingest-from/setup-on-k8s/guides/deployment-and-configuration/monitoring-and-instrumentation/annotate "Настройка мониторинга для пространств имён и подов"). | Нет значения по умолчанию (необязательно) | LabelSelector |',
    '| `namespaceSelector` | The namespaces where OTLP exporter configuration will be injected. For more information, see [Configure monitoring for namespaces and pods](/managed/ingest-from/setup-on-k8s/guides#annotate "Detailed description of installation and configuration options for specific use-cases") | No default (optional) | LabelSelector |': '| `namespaceSelector` | Пространства имён, в которые будет внедряться конфигурация экспортёра OTLP. Подробнее см. [Настройка мониторинга для пространств имён и подов](/managed/ingest-from/setup-on-k8s/guides#annotate "Подробное описание вариантов установки и настройки для конкретных сценариев использования") | Нет значения по умолчанию (необязательно) | LabelSelector |',
    "| `nodeSelector` | Specify the node selector that controls on which nodes OneAgent will be deployed. | No default (optional) | map[string]string |": "| `nodeSelector` | Укажите селектор узлов, который определяет, на каких узлах будет развёрнут OneAgent. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `oneAgentResources` | Resource settings for OneAgent container. Consumption of the OneAgent heavily depends on the workload to monitor. You can use the default settings in the [CR](https://dt-url.net/dynakube-samples).`resource.requests` shows the values needed to run; `resource.limits` shows the maximum limits for the Pod. | No default (optional) | ResourceRequirements |": "| `oneAgentResources` | Настройки ресурсов для контейнера OneAgent. Потребление OneAgent сильно зависит от отслеживаемой рабочей нагрузки. Можно использовать настройки по умолчанию в [CR](https://dt-url.net/dynakube-samples).`resource.requests` показывает значения, необходимые для запуска; `resource.limits` показывает максимальные лимиты для пода. | Нет значения по умолчанию (необязательно) | ResourceRequirements |",
    "| `oneAgentResources` | Resource settings for OneAgent container. Consumption of the OneAgent heavily depends on the workload to monitor. You can use the default settings in the [CR](https://dt-url.net/dynakube-samples).`resource.requests` shows the values needed to run; `resource.limits` shows the maximum limits for the pod. | No default (optional) | ResourceRequirements |": "| `oneAgentResources` | Настройки ресурсов для контейнера OneAgent. Потребление OneAgent сильно зависит от отслеживаемой рабочей нагрузки. Можно использовать настройки по умолчанию в [CR](https://dt-url.net/dynakube-samples).`resource.requests` показывает значения, необходимые для запуска; `resource.limits` показывает максимальные лимиты для пода. | Нет значения по умолчанию (необязательно) | ResourceRequirements |",
    "| `oneAgentResources` | Resource settings for OneAgent container. Consumption of the OneAgent heavily depends on the workload to monitor. You can use the default settings in the [CR](https://github.com/Dynatrace/dynatrace-operator/tree/v1.9.0/assets/samples/dynakube).`resource.requests` shows the values needed to run; `resource.limits` shows the maximum limits for the Pod. | No default (optional) | ResourceRequirements |": "| `oneAgentResources` | Настройки ресурсов для контейнера OneAgent. Потребление OneAgent сильно зависит от отслеживаемой рабочей нагрузки. Можно использовать настройки по умолчанию в [CR](https://github.com/Dynatrace/dynatrace-operator/tree/v1.9.0/assets/samples/dynakube).`resource.requests` показывает значения, необходимые для запуска; `resource.limits` показывает максимальные лимиты для пода. | Нет значения по умолчанию (необязательно) | ResourceRequirements |",
    "| `priorityClassName` | Assign a priority class to the OneAgent pods. By default, no class is set.For details, see [Pod Priority and Preemption](https://dt-url.net/n8437bl). | No default (optional) | string |": "| `priorityClassName` | Назначьте класс приоритета подам OneAgent. По умолчанию класс не задан.Подробнее см. [Pod Priority and Preemption](https://dt-url.net/n8437bl). | Нет значения по умолчанию (необязательно) | string |",
    "| `priorityClassName` | Assign a priority class to the OneAgent Pods. By default, no class is set.For details, see [Pod Priority and Preemption](https://dt-url.net/n8437bl). | No default (optional) | string |": "| `priorityClassName` | Назначьте класс приоритета подам OneAgent. По умолчанию класс не задан.Подробнее см. [Pod Priority and Preemption](https://dt-url.net/n8437bl). | Нет значения по умолчанию (необязательно) | string |",
    "| `rollingUpdate` | Define rollingUpdate settings for UpdateStrategy of the OneAgent DaemonSet.For details, see [DaemonSet specification](https://dt-url.net/v0038c5). | No default (optional) | RollingUpdateDaemonSet |": "| `rollingUpdate` | Определите настройки rollingUpdate для UpdateStrategy OneAgent DaemonSet.Подробнее см. [DaemonSet specification](https://dt-url.net/v0038c5). | Нет значения по умолчанию (необязательно) | RollingUpdateDaemonSet |",
    "| `secCompProfile` | The SecComp Profile that will be configured in order to run in secure computing mode. | No default (optional) | string |": "| `secCompProfile` | Профиль SecComp, который будет настроен для запуска в режиме защищённых вычислений. | Нет значения по умолчанию (необязательно) | string |",
    "| `storageHostPath` | Writable directory on the host filesystem where OneAgent configurations will be stored. | No default (optional) | string |": "| `storageHostPath` | Доступный для записи каталог в файловой системе хоста, где будут храниться конфигурации OneAgent. | Нет значения по умолчанию (необязательно) | string |",
    "| `storageHostPath` | Writeable directory on the host filesystem where OneAgent configurations will be stored. | No default (optional) | string |": "| `storageHostPath` | Доступный для записи каталог в файловой системе хоста, где будут храниться конфигурации OneAgent. | Нет значения по умолчанию (необязательно) | string |",
    "| `tolerations` | Tolerations to include with the OneAgent DaemonSet.For details, see [Taints and Tolerations](https://dt-url.net/od03765). | No default (optional) | []Toleration |": "| `tolerations` | Tolerations, включаемые в OneAgent DaemonSet.Подробнее см. [Taints and Tolerations](https://dt-url.net/od03765). | Нет значения по умолчанию (необязательно) | []Toleration |",
    "| `version` | The OneAgent version to be used for host monitoring OneAgents running in the dedicated pod. This setting doesn't affect the OneAgent version used for application monitoring. | The latest version is used by default. | string |": "| `version` | Версия OneAgent, используемая для OneAgent мониторинга хостов, работающих в выделенном поде. Эта настройка не влияет на версию OneAgent, используемую для мониторинга приложений. | По умолчанию используется последняя версия. | string |",
    "| `version` | The OneAgent version to be used for host monitoring OneAgents running in the dedicated Pod. This setting doesn't affect the OneAgent version used for application monitoring. | The latest version is used by default. | string |": "| `version` | Версия OneAgent, используемая для OneAgent мониторинга хостов, работающих в выделенном поде. Эта настройка не влияет на версию OneAgent, используемую для мониторинга приложений. | По умолчанию используется последняя версия. | string |",
    "| `version` | The OneAgent version to be used. | The latest version is used by default. | string |": "| `version` | Используемая версия OneAgent. | По умолчанию используется последняя версия. | string |",
    '| `autoUpdate` (**deprecated**) | Deprecated field to be removed in a future release. [Pin the OneAgent version on your tenant to configure auto-update](/managed/ingest-from/setup-on-k8s/guides/deployment-and-configuration/updates-and-maintenance/auto-update-components#configure-oneagent-auto-update "Configure auto-updates for components managed by Dynatrace Operator (OneAgent, ActiveGate, and EdgeConnect).").Auto-update is disabled when the `version` or `image` fields are set. | `true` | boolean |': '| `autoUpdate` (**устаревший**) | Устаревшее поле, будет удалено в одном из будущих выпусков. [Закрепите версию OneAgent на вашем тенанте, чтобы настроить автообновление](/managed/ingest-from/setup-on-k8s/guides/deployment-and-configuration/updates-and-maintenance/auto-update-components#configure-oneagent-auto-update "Настройка автообновлений для компонентов, управляемых Dynatrace Operator (OneAgent, ActiveGate и EdgeConnect).").Автообновление отключается, когда заданы поля `version` или `image`. | `true` | boolean |',
    # --- .spec.activeGate ---------------------------------------------------
    "| `annotations` | Add custom ActiveGate annotations. | No default (optional) | map[string]string |": "| `annotations` | Добавьте пользовательские аннотации ActiveGate. | Нет значения по умолчанию (необязательно) | map[string]string |",
    '| `capabilities` | Defines the ActiveGate pod capabilities: what functionality should be enabled.Possible values:- `routing` enables OneAgent routing.- `kubernetes-monitoring` enables Kubernetes API monitoring.- `metrics-ingest`[1](#fn-2-1-def) opens the metrics ingest endpoint on the DynaKube ActiveGate and redirects all pods to it.- `dynatrace-api`[1](#fn-2-1-def) enables calling the Dynatrace API via ActiveGate.- `debugging` enables the [Live Debugging module](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#debugging "Learn which ActiveGate properties you can configure based on your needs and requirements.") in ActiveGate. | No default (required) | string |': '| `capabilities` | Определяет возможности пода ActiveGate: какую функциональность следует включить.Возможные значения:- `routing` включает маршрутизацию OneAgent.- `kubernetes-monitoring` включает мониторинг Kubernetes API.- `metrics-ingest`[1](#fn-2-1-def) открывает конечную точку приёма метрик на ActiveGate DynaKube и перенаправляет на неё все поды.- `dynatrace-api`[1](#fn-2-1-def) включает вызов API Dynatrace через ActiveGate.- `debugging` включает [модуль Live Debugging](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#debugging "Узнайте, какие свойства ActiveGate можно настроить в зависимости от ваших нужд и требований.") в ActiveGate. | Нет значения по умолчанию (обязательно) | string |',
    '| `capabilities` | Defines the ActiveGate pod capabilities: what functionality should be enabled.Possible values:- `routing` enables OneAgent routing.- `kubernetes-monitoring` enables Kubernetes API monitoring.- `metrics-ingest`[1](#fn-3-1-def) opens the metrics ingest endpoint on the DynaKube ActiveGate and redirects all pods to it.- `dynatrace-api`[1](#fn-3-1-def) enables calling the Dynatrace API via ActiveGate.- `debugging` enables the [Live Debugging module](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#debugging "Learn which ActiveGate properties you can configure based on your needs and requirements.") in ActiveGate. | No default (required) | string |': '| `capabilities` | Определяет возможности пода ActiveGate: какую функциональность следует включить.Возможные значения:- `routing` включает маршрутизацию OneAgent.- `kubernetes-monitoring` включает мониторинг Kubernetes API.- `metrics-ingest`[1](#fn-3-1-def) открывает конечную точку приёма метрик на ActiveGate DynaKube и перенаправляет на неё все поды.- `dynatrace-api`[1](#fn-3-1-def) включает вызов API Dynatrace через ActiveGate.- `debugging` включает [модуль Live Debugging](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#debugging "Узнайте, какие свойства ActiveGate можно настроить в зависимости от ваших нужд и требований.") в ActiveGate. | Нет значения по умолчанию (обязательно) | string |',
    '| `capabilities` | Defines the ActiveGate pod capabilities: what functionality should be enabled.Possible values:- `routing` enables OneAgent routing.- `kubernetes-monitoring` enables Kubernetes API monitoring.- `metrics-ingest`[1](#fn-4-1-def) opens the metrics ingest endpoint on the DynaKube ActiveGate and redirects all pods to it.- `dynatrace-api`[1](#fn-4-1-def) enables calling the Dynatrace API via ActiveGate.- `debugging` enables the [Live Debugging module](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#debugging "Learn which ActiveGate properties you can configure based on your needs and requirements.") in ActiveGate. | No default (required) | string |': '| `capabilities` | Определяет возможности пода ActiveGate: какую функциональность следует включить.Возможные значения:- `routing` включает маршрутизацию OneAgent.- `kubernetes-monitoring` включает мониторинг Kubernetes API.- `metrics-ingest`[1](#fn-4-1-def) открывает конечную точку приёма метрик на ActiveGate DynaKube и перенаправляет на неё все поды.- `dynatrace-api`[1](#fn-4-1-def) включает вызов API Dynatrace через ActiveGate.- `debugging` включает [модуль Live Debugging](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#debugging "Узнайте, какие свойства ActiveGate можно настроить в зависимости от ваших нужд и требований.") в ActiveGate. | Нет значения по умолчанию (обязательно) | string |',
    '| `capabilities` | Defines the ActiveGate pod capabilities: what functionality should be enabled.Possible values:- `routing` enables OneAgent routing.- `kubernetes-monitoring` enables Kubernetes API monitoring.- `metrics-ingest`[1](#fn-5-1-def) opens the metrics ingest endpoint on the DynaKube ActiveGate and redirects all pods to it.- `dynatrace-api`[1](#fn-5-1-def) enables calling the Dynatrace API via ActiveGate.- `debugging` enables the [Live Debugging module](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#debugging "Learn which ActiveGate properties you can configure based on your needs and requirements.") in ActiveGate. | No default (required) | string |': '| `capabilities` | Определяет возможности пода ActiveGate: какую функциональность следует включить.Возможные значения:- `routing` включает маршрутизацию OneAgent.- `kubernetes-monitoring` включает мониторинг Kubernetes API.- `metrics-ingest`[1](#fn-5-1-def) открывает конечную точку приёма метрик на ActiveGate DynaKube и перенаправляет на неё все поды.- `dynatrace-api`[1](#fn-5-1-def) включает вызов API Dynatrace через ActiveGate.- `debugging` включает [модуль Live Debugging](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#debugging "Узнайте, какие свойства ActiveGate можно настроить в зависимости от ваших нужд и требований.") в ActiveGate. | Нет значения по умолчанию (обязательно) | string |',
    '| `capabilities` | Defines the ActiveGate pod capabilities: what functionality should be enabled.Possible values:- `routing` enables OneAgent routing.- `kubernetes-monitoring` enables Kubernetes API monitoring.- `metrics-ingest`[1](#fn-6-1-def) opens the metrics ingest endpoint on the DynaKube ActiveGate and redirects all pods to it.- `dynatrace-api`[1](#fn-6-1-def) enables calling the Dynatrace API via ActiveGate.- `debugging` enables the [Live Debugging module](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#debugging "Learn which ActiveGate properties you can configure based on your needs and requirements.") in ActiveGate. | No default (required) | string |': '| `capabilities` | Определяет возможности пода ActiveGate: какую функциональность следует включить.Возможные значения:- `routing` включает маршрутизацию OneAgent.- `kubernetes-monitoring` включает мониторинг Kubernetes API.- `metrics-ingest`[1](#fn-6-1-def) открывает конечную точку приёма метрик на ActiveGate DynaKube и перенаправляет на неё все поды.- `dynatrace-api`[1](#fn-6-1-def) включает вызов API Dynatrace через ActiveGate.- `debugging` включает [модуль Live Debugging](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#debugging "Узнайте, какие свойства ActiveGate можно настроить в зависимости от ваших нужд и требований.") в ActiveGate. | Нет значения по умолчанию (обязательно) | string |',
    '| `capabilities` | Defines the ActiveGate pod capabilities: what functionality should be enabled.Possible values:- `routing` enables OneAgent routing.- `kubernetes-monitoring` enables Kubernetes API monitoring.- `metrics-ingest`[1](#fn-7-1-def) opens the metrics ingest endpoint on the DynaKube ActiveGate and redirects all pods to it.- `dynatrace-api`[1](#fn-7-1-def) enables calling the Dynatrace API via ActiveGate.- `debugging` enables the [Live Debugging module](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#debugging "Learn which ActiveGate properties you can configure based on your needs and requirements.") in ActiveGate. | No default (required) | string |': '| `capabilities` | Определяет возможности пода ActiveGate: какую функциональность следует включить.Возможные значения:- `routing` включает маршрутизацию OneAgent.- `kubernetes-monitoring` включает мониторинг Kubernetes API.- `metrics-ingest`[1](#fn-7-1-def) открывает конечную точку приёма метрик на ActiveGate DynaKube и перенаправляет на неё все поды.- `dynatrace-api`[1](#fn-7-1-def) включает вызов API Dynatrace через ActiveGate.- `debugging` включает [модуль Live Debugging](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#debugging "Узнайте, какие свойства ActiveGate можно настроить в зависимости от ваших нужд и требований.") в ActiveGate. | Нет значения по умолчанию (обязательно) | string |',
    '| `customProperties` | Add a custom properties file by providing it as a value or by referencing it from a secret.When referencing a custom properties file from a secret, make sure that the key is named `customProperties`. See [How to add a custom properties file](/managed/ingest-from/setup-on-k8s/guides/metadata-automation/custom-properties-file "Add a custom properties file") for details. | No default (optional) | string |': '| `customProperties` | Добавьте файл пользовательских свойств, указав его как значение или сославшись на него из секрета.При ссылке на файл пользовательских свойств из секрета убедитесь, что ключ называется `customProperties`. Подробнее см. [Как добавить файл пользовательских свойств](/managed/ingest-from/setup-on-k8s/guides/metadata-automation/custom-properties-file "Добавление файла пользовательских свойств"). | Нет значения по умолчанию (необязательно) | string |',
    "| `dnsPolicy` | Set the DNS policy for ActiveGate pods. | `ClusterFirstWithHostNet` | string |": "| `dnsPolicy` | Задайте политику DNS для подов ActiveGate. | `ClusterFirstWithHostNet` | string |",
    "| `env` | Set additional environment variables for the ActiveGate pods. | No default (optional) | []EnvVar |": "| `env` | Задайте дополнительные переменные окружения для подов ActiveGate. | Нет значения по умолчанию (необязательно) | []EnvVar |",
    '| `group` | Set activation group for ActiveGate. See [Customize ActiveGate properties](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#collect "Learn which ActiveGate properties you can configure based on your needs and requirements.") for details. | No default (recommended) | string |': '| `group` | Задайте группу активации для ActiveGate. Подробнее см. [Настройка свойств ActiveGate](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#collect "Узнайте, какие свойства ActiveGate можно настроить в зависимости от ваших нужд и требований."). | Нет значения по умолчанию (рекомендуется) | string |',
    "| `image` | Use a custom ActiveGate image. Defaults to the latest ActiveGate image from the Dynatrace cluster. | No default (optional) | string |": "| `image` | Используйте пользовательский образ ActiveGate. По умолчанию используется последний образ ActiveGate из кластера Dynatrace. | Нет значения по умолчанию (необязательно) | string |",
    "| `labels` | Your defined labels for ActiveGate pods in order to structure workloads as desired. | No default (optional) | map[string]string |": "| `labels` | Заданные вами метки для подов ActiveGate, чтобы структурировать рабочие нагрузки по необходимости. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `nodeSelector` | Specify the node selector that controls on which nodes ActiveGate will be deployed. | No default (optional) | map[string]string |": "| `nodeSelector` | Укажите селектор узлов, который определяет, на каких узлах будет развёрнут ActiveGate. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `priorityClassName` | Assign a priority class to the ActiveGate pods. By default, no class is set.For details, see [Pod Priority and Preemption](https://dt-url.net/n8437bl). | No default (optional) | string |": "| `priorityClassName` | Назначьте класс приоритета подам ActiveGate. По умолчанию класс не задан.Подробнее см. [Pod Priority and Preemption](https://dt-url.net/n8437bl). | Нет значения по умолчанию (необязательно) | string |",
    "| `replicas` | Number of replicas of ActiveGate pods. | 1 | int |": "| `replicas` | Количество реплик подов ActiveGate. | 1 | int |",
    "| `rollingUpdate` | Define rollingUpdate settings for UpdateStrategy of the ActiveGate StatefulSet. For details, see [StatefulSet Specification](https://dt-url.net/ql238m1).  UpdateStrategy for StatefulSet requires Kubernetes 1.35 and above. The setting is ignored on lower versions, and the Operator warns you about ignored settings if it was specified. | No default (optional) | RollingUpdateStatefulSetStrategy |": "| `rollingUpdate` | Определите настройки rollingUpdate для UpdateStrategy ActiveGate StatefulSet. Подробнее см. [StatefulSet Specification](https://dt-url.net/ql238m1).  UpdateStrategy для StatefulSet требует Kubernetes 1.35 и выше. На более ранних версиях настройка игнорируется, и Operator предупреждает об игнорируемых настройках, если они были указаны. | Нет значения по умолчанию (необязательно) | RollingUpdateStatefulSetStrategy |",
    "| `resources` | Resource settings for ActiveGate container. Consumption of the ActiveGate heavily depends on the workload to monitor; adjust values accordingly. | No default (recommended) | ResourceRequirements |": "| `resources` | Настройки ресурсов для контейнера ActiveGate. Потребление ActiveGate сильно зависит от отслеживаемой рабочей нагрузки; корректируйте значения соответственно. | Нет значения по умолчанию (рекомендуется) | ResourceRequirements |",
    "| `terminationGracePeriodSeconds` | Configures the terminationGracePeriodSeconds parameter of the ActiveGate pod. Kubernetes defaults and rules apply. | No default (optional) | int |": "| `terminationGracePeriodSeconds` | Настраивает параметр terminationGracePeriodSeconds пода ActiveGate. Применяются значения по умолчанию и правила Kubernetes. | Нет значения по умолчанию (необязательно) | int |",
    '| `tlsSecretName` | Name of a secret containing ActiveGate TLS certificate, key, and password. If not set, a self-signed certificate is used. For details, see [How to add a custom certificate for ActiveGate](/managed/ingest-from/setup-on-k8s/guides/networking-security-compliance/network-configurations#tls-certificate "Configure Dynatrace in network-restricted environments, network-related settings and proxy configurations."). | No default (optional) | string |': '| `tlsSecretName` | Имя секрета, содержащего TLS-сертификат, ключ и пароль ActiveGate. Если не задано, используется самоподписанный сертификат. Подробнее см. [Как добавить пользовательский сертификат для ActiveGate](/managed/ingest-from/setup-on-k8s/guides/networking-security-compliance/network-configurations#tls-certificate "Настройка Dynatrace в окружениях с сетевыми ограничениями, сетевых параметров и конфигураций proxy."). | Нет значения по умолчанию (необязательно) | string |',
    "| `tolerations` | Set tolerations for the ActiveGate pods.For details, see [Taints and Tolerations](https://dt-url.net/od03765). | No default (optional) | []Toleration |": "| `tolerations` | Задайте tolerations для подов ActiveGate.Подробнее см. [Taints and Tolerations](https://dt-url.net/od03765). | Нет значения по умолчанию (необязательно) | []Toleration |",
    "| `topologySpreadConstraints` | Adds [topology spread constraints](https://dt-url.net/xc03ysw) to the ActiveGate pods. | No default (optional) | []TopologySpreadConstraint |": "| `topologySpreadConstraints` | Добавляет [topology spread constraints](https://dt-url.net/xc03ysw) к подам ActiveGate. | Нет значения по умолчанию (необязательно) | []TopologySpreadConstraint |",
    "| `useEphemeralVolume` | Indicates whether to use ephemeral volume for storage. | No default (optional) | boolean |": "| `useEphemeralVolume` | Указывает, использовать ли эфемерный том для хранения. | Нет значения по умолчанию (необязательно) | boolean |",
    "| `volumeClaimTemplate` | Describes the common attributes of storage devices and allows a Source for provider-specific attributes. | No default (optional) | PersistentVolumeClaimSpec |": "| `volumeClaimTemplate` | Описывает общие атрибуты устройств хранения и допускает Source для атрибутов, специфичных для провайдера. | Нет значения по умолчанию (необязательно) | PersistentVolumeClaimSpec |",
    # --- .spec.metadataEnrichment ------------------------------------------
    "| `enabled` | Enables MetadataEnrichment, `false` by default. | `false` | boolean |": "| `enabled` | Включает MetadataEnrichment, по умолчанию `false`. | `false` | boolean |",
    "| `enabled` | Enables MetadataEnrichment, `true` by default. | `true` | boolean |": "| `enabled` | Включает MetadataEnrichment, по умолчанию `true`. | `true` | boolean |",
    "### Implicit metadata enrichment": "### Неявное обогащение метаданными",
    "When OneAgent injection is configured for a namespace, metadata enrichment is implicitly enabled for that namespace, even if the `enabled` parameter in `.spec.metadataEnrichment` is set to `false`.": "Когда для пространства имён настроено внедрение OneAgent, обогащение метаданными неявно включается для этого пространства имён, даже если параметр `enabled` в `.spec.metadataEnrichment` установлен в `false`.",
    'See [Configure enrichment directory](/managed/ingest-from/setup-on-k8s/guides/metadata-automation/metadata-enrichment "Metadata enrichment in the Dynatrace Operator adds context to Kubernetes pods by attaching relevant metadata to entities like pods, hosts, and processes for better observability.") for additional information': 'Дополнительные сведения см. в разделе [Настройка каталога обогащения](/managed/ingest-from/setup-on-k8s/guides/metadata-automation/metadata-enrichment "Обогащение метаданными в Dynatrace Operator добавляет контекст к подам Kubernetes, присоединяя релевантные метаданные к таким сущностям, как поды, хосты и процессы, для лучшей наблюдаемости.")',
    # --- .spec.extensions ---------------------------------------------------
    "Adding this section enables extension support in Kubernetes. To use extensions": "Добавление этого раздела включает поддержку расширений в Kubernetes. Чтобы использовать расширения",
    "* `kubernetes-monitoring` is mandatory and has to be added to the [list of ActiveGate capabilities](#active-gate) in `.spec.activeGate.capabilities` and": "* `kubernetes-monitoring` обязателен и должен быть добавлен в [список возможностей ActiveGate](#active-gate) в `.spec.activeGate.capabilities`, а также",
    "* The feature flag `feature.dynatrace.com/automatic-kubernetes-api-monitoring` must not be set to `false`.": "* Флаг функции `feature.dynatrace.com/automatic-kubernetes-api-monitoring` не должен быть установлен в `false`.",
    "| `prometheus` | Enables prometheus extension. | No default (optional) |  |": "| `prometheus` | Включает расширение prometheus. | Нет значения по умолчанию (необязательно) |  |",
    "| `databases` | List of database extensions. | No default (optional) | [[]DatabaseSpec](#extensions-databases) |": "| `databases` | Список расширений баз данных. | Нет значения по умолчанию (необязательно) | [[]DatabaseSpec](#extensions-databases) |",
    # --- .spec.extensions.databases ----------------------------------------
    "| `id` | Unique Kubernetes object name. | No default (required) | string |": "| `id` | Уникальное имя объекта Kubernetes. | Нет значения по умолчанию (обязательно) | string |",
    "| `replicas` | Number of SQL Extension Executor replicas. | 1 | int32 |": "| `replicas` | Количество реплик SQL Extension Executor. | 1 | int32 |",
    "| `volumes` | Volumes for file-based authentication. | No default (optional) | []Volume |": "| `volumes` | Тома для аутентификации на основе файлов. | Нет значения по умолчанию (необязательно) | []Volume |",
    "| `volumeMounts` | Volume mounts for file-based authentication. | No default (optional) | []VolumeMount |": "| `volumeMounts` | Монтирования томов для аутентификации на основе файлов. | Нет значения по умолчанию (необязательно) | []VolumeMount |",
    "| `serviceAccountName` | ServiceAccount for IAM-based authentication. | No default (optional) | string |": "| `serviceAccountName` | ServiceAccount для аутентификации на основе IAM. | Нет значения по умолчанию (необязательно) | string |",
    "| `labels` | SQL Extension Executor labels. | No default (optional) | []Label |": "| `labels` | Метки SQL Extension Executor. | Нет значения по умолчанию (необязательно) | []Label |",
    "| `annotations` | SQL Extension Executor annotations. | No default (optional) | []Annotation |": "| `annotations` | Аннотации SQL Extension Executor. | Нет значения по умолчанию (необязательно) | []Annotation |",
    "| `affinity` | SQL Extension Executor affinities. | No default (optional) | []Affinity |": "| `affinity` | Affinity для SQL Extension Executor. | Нет значения по умолчанию (необязательно) | []Affinity |",
    "| `resources` | SQL Extension Executor resources. | No default (optional) | ResourcesSpec |": "| `resources` | Ресурсы SQL Extension Executor. | Нет значения по умолчанию (необязательно) | ResourcesSpec |",
    "| `nodeSelector` | SQL Extension Executor node selector. | No default (optional) | NodeSelectorSpec |": "| `nodeSelector` | Селектор узлов SQL Extension Executor. | Нет значения по умолчанию (необязательно) | NodeSelectorSpec |",
    "| `topologySpreadConstraints` | SQL Extension Executor topology spread constraints. | No default (optional) | TopologySpreadConstraints |": "| `topologySpreadConstraints` | Topology spread constraints для SQL Extension Executor. | Нет значения по умолчанию (необязательно) | TopologySpreadConstraints |",
    "On OpenShift, using volumes of type `hostPath` is prohibited by default SCC and will cause failures. If `hostPath` is required, create a role with sufficient privileges and bind it to the respective service account. In this example, the created role is bound to a service account named `custom-sql-extension-executor-sa`:": "В OpenShift использование томов типа `hostPath` запрещено политикой SCC по умолчанию и приведёт к сбоям. Если `hostPath` необходим, создайте роль с достаточными привилегиями и привяжите её к соответствующему service account. В этом примере созданная роль привязывается к service account с именем `custom-sql-extension-executor-sa`:",
    # --- .spec.kspm ---------------------------------------------------------
    'Adding this section enables [Kubernetes Security Posture Management (KSPM)](/managed/upgrade/unavailable-in-managed "Your selection is unavailable in Dynatrace Managed."). To use KSPM': 'Добавление этого раздела включает [Kubernetes Security Posture Management (KSPM)](/managed/upgrade/unavailable-in-managed "Ваш выбор недоступен в Dynatrace Managed."). Чтобы использовать KSPM',
    "| `mappedHostPaths` | Specifies the host paths that are mounted to the NCC container. | No default (optional) | [[]string](#kspm-mappedHostPaths) |": "| `mappedHostPaths` | Указывает пути на хосте, которые монтируются в контейнер NCC. | Нет значения по умолчанию (необязательно) | [[]string](#kspm-mappedHostPaths) |",
    # --- .spec.logMonitoring ------------------------------------------------
    "Log Monitoring requires the `kubernetes-monitoring` [ActiveGate capability](#active-gate) to be enabled, but it doesn't have to be configured in the same DynaKube. If `kubernetes-monitoring` is missing or the feature flag `feature.dynatrace.com/automatic-kubernetes-api-monitoring` is set to `false`, the Operator produces a warning but Log Monitoring still deploys.": "Для Log Monitoring требуется включённая [возможность ActiveGate](#active-gate) `kubernetes-monitoring`, но её не обязательно настраивать в том же DynaKube. Если `kubernetes-monitoring` отсутствует или флаг функции `feature.dynatrace.com/automatic-kubernetes-api-monitoring` установлен в `false`, Operator выдаёт предупреждение, но Log Monitoring всё равно разворачивается.",
    "| `ingestRuleMatchers` | Specifies the rules and conditions for matching ingest attributes. | No default (optional) | [[]IngestRuleMatchers](#log-monitoring-ingest-rule-matchers) |": "| `ingestRuleMatchers` | Указывает правила и условия для сопоставления атрибутов приёма. | Нет значения по умолчанию (необязательно) | [[]IngestRuleMatchers](#log-monitoring-ingest-rule-matchers) |",
    "This field is immutable. Once set, it will no longer be updated.": "Это поле неизменяемо. После установки оно больше не обновляется.",
    "| `attribute` | Specifies the attribute name for matching ingest rules. | No default (optional) | string |": "| `attribute` | Указывает имя атрибута для сопоставления правил приёма. | Нет значения по умолчанию (необязательно) | string |",
    "| `values` | Lists the values that the `attribute` must match for an ingest rule to apply. | No default (optional) | []string |": "| `values` | Перечисляет значения, которым должен соответствовать `attribute`, чтобы правило приёма применилось. | Нет значения по умолчанию (необязательно) | []string |",
    "#### Example:": "#### Пример:",
    # --- .spec.telemetryIngest ----------------------------------------------
    'Enable additional [telemetry ingest endpoints](/managed/ingest-from/setup-on-k8s/extend-observability-k8s/telemetry-ingest "Enable Dynatrace telemetry ingest endpoints in Kubernetes for cluster-local data ingest.") in Kubernetes for cluster-local data ingest using 3rd-party protocols. Adding this section deploys the Dynatrace Collector workload to the cluster.': 'Включите дополнительные [конечные точки приёма телеметрии](/managed/ingest-from/setup-on-k8s/extend-observability-k8s/telemetry-ingest "Включите конечные точки приёма телеметрии Dynatrace в Kubernetes для приёма данных локально в кластере.") в Kubernetes для приёма данных локально в кластере с использованием сторонних протоколов. Добавление этого раздела разворачивает рабочую нагрузку Dynatrace Collector в кластере.',
    'Enable Dynatrace [telemetry endpoints](/managed/ingest-from/setup-on-k8s/extend-observability-k8s/telemetry-ingest "Enable Dynatrace telemetry ingest endpoints in Kubernetes for cluster-local data ingest.") in Kubernetes for cluster-local data ingest. Adding this section deploys the Dynatrace Collector by Dynatrace Operator.': 'Включите [конечные точки телеметрии](/managed/ingest-from/setup-on-k8s/extend-observability-k8s/telemetry-ingest "Включите конечные точки приёма телеметрии Dynatrace в Kubernetes для приёма данных локально в кластере.") Dynatrace в Kubernetes для приёма данных локально в кластере. Добавление этого раздела разворачивает Dynatrace Collector силами Dynatrace Operator.',
    '| `protocols` | Specifies the protocols that will be ingested by the Dynatrace Collector. | "otlp, jaeger, statsd, zipkin" | []string |': '| `protocols` | Указывает протоколы, которые будет принимать Dynatrace Collector. | "otlp, jaeger, statsd, zipkin" | []string |',
    '| `serviceName` | Specifies the name of the service to be used. If not specified the serviceName is set to a default. | "*dynakube.name*-telemetry-ingest" | string |': '| `serviceName` | Указывает имя используемого сервиса. Если не указано, serviceName устанавливается в значение по умолчанию. | "*dynakube.name*-telemetry-ingest" | string |',
    "| `tlsRefName` | Secret containing a TLS certificate used by telemetryIngest. | No default (optional) | string |": "| `tlsRefName` | Секрет, содержащий TLS-сертификат, используемый telemetryIngest. | Нет значения по умолчанию (необязательно) | string |",
    # --- .spec.otlpExporterConfiguration ------------------------------------
    'Enable automatic [OTLP exporter configuration](/managed/ingest-from/setup-on-k8s/extend-observability-k8s/otlp-auto-config "Automatically configure the OTLP exporter in applications instrumented with OpenTelemetry SDKs using Dynatrace Operator.") for application pods that are already instrumented with OpenTelemetry SDK.': 'Включите автоматическую [настройку экспортёра OTLP](/managed/ingest-from/setup-on-k8s/extend-observability-k8s/otlp-auto-config "Автоматически настраивайте экспортёр OTLP в приложениях, инструментированных с помощью OpenTelemetry SDK, средствами Dynatrace Operator.") для подов приложений, которые уже инструментированы с помощью OpenTelemetry SDK.',
    "| `signals` | The OpenTelemetry signals that will be automatically ingested into Dynatrace. | No default (optional) | [signalConfiguration](#otlp-exporter-signals) |": "| `signals` | Сигналы OpenTelemetry, которые будут автоматически приниматься в Dynatrace. | Нет значения по умолчанию (необязательно) | [signalConfiguration](#otlp-exporter-signals) |",
    "| `overrideEnvVars` | Enable overriding of existing configuration environment variables of the OTLP exporter. | false | boolean |": "| `overrideEnvVars` | Включает переопределение существующих переменных окружения конфигурации экспортёра OTLP. | false | boolean |",
    "| `logs` | Enables the automatic OTLP exporter configuration for logs. See [endpoint urls for otlphttp](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#endpoint-urls-for-otlphttp). | No default (optional) | object |": "| `logs` | Включает автоматическую настройку экспортёра OTLP для логов. См. [endpoint urls for otlphttp](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#endpoint-urls-for-otlphttp). | Нет значения по умолчанию (необязательно) | object |",
    "| `metrics` | Enables the automatic OTLP exporter configuration for metrics. See [endpoint urls for otlphttp](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#endpoint-urls-for-otlphttp). | No default (optional) | object |": "| `metrics` | Включает автоматическую настройку экспортёра OTLP для метрик. См. [endpoint urls for otlphttp](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#endpoint-urls-for-otlphttp). | Нет значения по умолчанию (необязательно) | object |",
    "| `traces` | Enables the automatic OTLP exporter configuration for traces. See [endpoint urls for otlphttp](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#endpoint-urls-for-otlphttp) | No default (optional) | object |": "| `traces` | Включает автоматическую настройку экспортёра OTLP для трассировок. См. [endpoint urls for otlphttp](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#endpoint-urls-for-otlphttp) | Нет значения по умолчанию (необязательно) | object |",
    # --- .spec.templates.kspmNodeConfigurationCollector ---------------------
    "| `updateStrategy` | Define the Node Configuration Collector daemonSet updateStrategy | No default (optional) | DaemonSetUpdateStrategy |": "| `updateStrategy` | Определите updateStrategy для daemonSet Node Configuration Collector | Нет значения по умолчанию (необязательно) | DaemonSetUpdateStrategy |",
    "| `updateStrategy` | Define the NodeConfigurationCollector daemonSet updateStrategy. | No default (optional) | DaemonSetUpdateStrategy |": "| `updateStrategy` | Определите updateStrategy для daemonSet NodeConfigurationCollector. | Нет значения по умолчанию (необязательно) | DaemonSetUpdateStrategy |",
    "| `labels` | Add custom labels to the Node Configuration Collector pods. | No default (optional) | map[string]string |": "| `labels` | Добавьте пользовательские метки к подам Node Configuration Collector. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `labels` | Add custom labels to the Node Configuration Collector Pods. | No default (optional) | map[string]string |": "| `labels` | Добавьте пользовательские метки к подам Node Configuration Collector. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `annotations` | Add custom annotations to the Node Configuration Collector pods. | No default (optional) | map[string]string |": "| `annotations` | Добавьте пользовательские аннотации к подам Node Configuration Collector. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `annotations` | Add custom annotations to the Node Configuration Collector Pods. | No default (optional) | map[string]string |": "| `annotations` | Добавьте пользовательские аннотации к подам Node Configuration Collector. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `nodeSelector` | Specify the node selector that controls on which nodes the Node Configuration Collector pods will be deployed. | No default (optional) | map[string]string |": "| `nodeSelector` | Укажите селектор узлов, который определяет, на каких узлах будут развёрнуты поды Node Configuration Collector. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `nodeSelector` | Specify the node selector that controls on which nodes the Node Configuration Collector Pods will be deployed. | No default (optional) | map[string]string |": "| `nodeSelector` | Укажите селектор узлов, который определяет, на каких узлах будут развёрнуты поды Node Configuration Collector. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `imageRef` | Overrides the default image. | No default (optional) | [imageRef](#kspm-image-ref) |": "| `imageRef` | Переопределяет образ по умолчанию. | Нет значения по умолчанию (необязательно) | [imageRef](#kspm-image-ref) |",
    "| `priorityClassName` | If specified, indicates the Pod's priority. Name must be defined by creating a PriorityClass object with that name. If not specified the setting will be removed from the DaemonSet. | No default (optional) | string |": "| `priorityClassName` | Если указано, определяет приоритет пода. Имя должно быть задано путём создания объекта PriorityClass с этим именем. Если не указано, настройка будет удалена из DaemonSet. | Нет значения по умолчанию (необязательно) | string |",
    "| `resources` | Define resource requests and limits for Node Configuration Collector Pods. | No default (optional) | ResourceRequirements |": "| `resources` | Определите запросы и лимиты ресурсов для подов Node Configuration Collector. | Нет значения по умолчанию (необязательно) | ResourceRequirements |",
    "| `nodeAffinity` | Define the nodeAffinity for the DaemonSet of the Node Configuration Collector | No default (optional) | NodeAffinity |": "| `nodeAffinity` | Определите nodeAffinity для DaemonSet Node Configuration Collector | Нет значения по умолчанию (необязательно) | NodeAffinity |",
    "| `nodeAffinity` | Define the nodeAffinity for the DaemonSet of the NodeConfigurationCollector | No default (optional) | NodeAffinity |": "| `nodeAffinity` | Определите nodeAffinity для DaemonSet NodeConfigurationCollector | Нет значения по умолчанию (необязательно) | NodeAffinity |",
    "| `tolerations` | Set tolerations for the Node Configuration Collector pods.For details, see [Taints and Tolerations](https://dt-url.net/od03765). | No default (optional) | []Toleration |": "| `tolerations` | Задайте tolerations для подов Node Configuration Collector.Подробнее см. [Taints and Tolerations](https://dt-url.net/od03765). | Нет значения по умолчанию (необязательно) | []Toleration |",
    "| `tolerations` | Set tolerations for the Node Configuration Collector Pods.For details, see [Taints and Tolerations](https://dt-url.net/od03765). | No default (optional) | []Toleration |": "| `tolerations` | Задайте tolerations для подов Node Configuration Collector.Подробнее см. [Taints and Tolerations](https://dt-url.net/od03765). | Нет значения по умолчанию (необязательно) | []Toleration |",
    "| `args` | Set additional arguments for the Node Configuration Collector main container. | No default (optional) | []string |": "| `args` | Задайте дополнительные аргументы для основного контейнера Node Configuration Collector. | Нет значения по умолчанию (необязательно) | []string |",
    "| `env` | Set additional environment variables for the Node Configuration Collector main container. | No default (optional) | []string |": "| `env` | Задайте дополнительные переменные окружения для основного контейнера Node Configuration Collector. | Нет значения по умолчанию (необязательно) | []string |",
    # --- imageRef shared (kspm / extension controller / collector / sql) ----
    "| `pullPolicy` | Defines the image pull policy. When empty, the Kubernetes default applies. | No default (optional) | string |": "| `pullPolicy` | Определяет политику загрузки образа. Если не задано, применяется значение по умолчанию Kubernetes. | Нет значения по умолчанию (необязательно) | string |",
    "| `repository` | URL of Node Configuration Collector image. | No default (optional) | string |": "| `repository` | URL образа Node Configuration Collector. | Нет значения по умолчанию (необязательно) | string |",
    "| repository | URL of Node Configuration Collector image. | No default (optional) | string |": "| repository | URL образа Node Configuration Collector. | Нет значения по умолчанию (необязательно) | string |",
    "| `tag` | Tag for Node Configuration Collector image. | No default (optional) | string |": "| `tag` | Тег образа Node Configuration Collector. | Нет значения по умолчанию (необязательно) | string |",
    "| tag | Tag for Node Configuration Collector image. | No default (optional) | string |": "| tag | Тег образа Node Configuration Collector. | Нет значения по умолчанию (необязательно) | string |",
    # --- .spec.templates.logMonitoring --------------------------------------
    "| `annotations` | Add custom annotations to the LogMonitoring pods. | No default (optional) | map[string]string |": "| `annotations` | Добавьте пользовательские аннотации к подам LogMonitoring. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `annotations` | Add custom annotations to the LogMonitoring Pods. | No default (optional) | map[string]string |": "| `annotations` | Добавьте пользовательские аннотации к подам LogMonitoring. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `labels` | Add custom labels to the LogMonitoring pods. | No default (optional) | map[string]string |": "| `labels` | Добавьте пользовательские метки к подам LogMonitoring. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `labels` | Add custom labels to the LogMonitoring Pods. | No default (optional) | map[string]string |": "| `labels` | Добавьте пользовательские метки к подам LogMonitoring. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `nodeSelector` | Specify the node selector that controls on which nodes the LogMonitoring pods will be deployed. | No default (optional) | map[string]string |": "| `nodeSelector` | Укажите селектор узлов, который определяет, на каких узлах будут развёрнуты поды LogMonitoring. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `nodeSelector` | Specify the node selector that controls on which nodes the LogMonitoring Pods will be deployed. | No default (optional) | map[string]string |": "| `nodeSelector` | Укажите селектор узлов, который определяет, на каких узлах будут развёрнуты поды LogMonitoring. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `imageRef` | Overrides the default image for the LogMonitoring pods. | No default (required) | [imageRef](#log-monitoring-image-ref) |": "| `imageRef` | Переопределяет образ по умолчанию для подов LogMonitoring. | Нет значения по умолчанию (обязательно) | [imageRef](#log-monitoring-image-ref) |",
    "| `imageRef` | Overrides the default image for the LogMonitoring Pods. | No default (required) | [imageRef](#log-monitoring-image-ref) |": "| `imageRef` | Переопределяет образ по умолчанию для подов LogMonitoring. | Нет значения по умолчанию (обязательно) | [imageRef](#log-monitoring-image-ref) |",
    "| `dnsPolicy` | Set the DNS policy for LogMonitoring pods. | `ClusterFirst` | string |": "| `dnsPolicy` | Задайте политику DNS для подов LogMonitoring. | `ClusterFirst` | string |",
    "| `dnsPolicy` | Set the DNS policy for LogMonitoring Pods. | `ClusterFirst` | string |": "| `dnsPolicy` | Задайте политику DNS для подов LogMonitoring. | `ClusterFirst` | string |",
    "| `priorityClassName` | Assign a priority class to the LogMonitoring pods. By default, no class is set. | No default (optional) | string |": "| `priorityClassName` | Назначьте класс приоритета подам LogMonitoring. По умолчанию класс не задан. | Нет значения по умолчанию (необязательно) | string |",
    "| `priorityClassName` | Assign a priority class to the LogMonitoring Pods. By default, no class is set. | No default (optional) | string |": "| `priorityClassName` | Назначьте класс приоритета подам LogMonitoring. По умолчанию класс не задан. | Нет значения по умолчанию (необязательно) | string |",
    "| `secCompProfile` | Configures a SecComp profile to enable secure computing mode for the LogMonitoring pods. | No default (optional) | string |": "| `secCompProfile` | Настраивает профиль SecComp для включения режима защищённых вычислений для подов LogMonitoring. | Нет значения по умолчанию (необязательно) | string |",
    "| `secCompProfile` | Configures a SecComp profile to enable secure computing mode for the LogMonitoring Pods. | No default (optional) | string |": "| `secCompProfile` | Настраивает профиль SecComp для включения режима защищённых вычислений для подов LogMonitoring. | Нет значения по умолчанию (необязательно) | string |",
    "| `resources` | Define resource requests and limits for LogMonitoring's main and init-container. | No default (optional) | ResourceRequirements |": "| `resources` | Определите запросы и лимиты ресурсов для основного и init-контейнера LogMonitoring. | Нет значения по умолчанию (необязательно) | ResourceRequirements |",
    "| `rollingUpdate` | Define rollingUpdate settings for UpdateStrategy of the LogMonitoring DaemonSet.For details, see [DaemonSet specification](https://dt-url.net/v0038c5). | No default (optional) | RollingUpdateDaemonSet |": "| `rollingUpdate` | Определите настройки rollingUpdate для UpdateStrategy LogMonitoring DaemonSet.Подробнее см. [DaemonSet specification](https://dt-url.net/v0038c5). | Нет значения по умолчанию (необязательно) | RollingUpdateDaemonSet |",
    "| `tolerations` | Set tolerations for the LogMonitoring pods.For details, see [Taints and Tolerations](https://dt-url.net/od03765). | No default (optional) | []Toleration |": "| `tolerations` | Задайте tolerations для подов LogMonitoring.Подробнее см. [Taints and Tolerations](https://dt-url.net/od03765). | Нет значения по умолчанию (необязательно) | []Toleration |",
    "| `tolerations` | Set tolerations for the LogMonitoring Pods.For details, see [Taints and Tolerations](https://dt-url.net/od03765). | No default (optional) | []Toleration |": "| `tolerations` | Задайте tolerations для подов LogMonitoring.Подробнее см. [Taints and Tolerations](https://dt-url.net/od03765). | Нет значения по умолчанию (необязательно) | []Toleration |",
    "| `args` | Set additional arguments for the LogMonitoring init container. | No default (optional) | []string |": "| `args` | Задайте дополнительные аргументы для init-контейнера LogMonitoring. | Нет значения по умолчанию (необязательно) | []string |",
    "| `repository` | URL of LogMonitoring image. | No default (optional) | string |": "| `repository` | URL образа LogMonitoring. | Нет значения по умолчанию (необязательно) | string |",
    "| `tag` | Tag for LogMonitoring image. | No default (optional) | string |": "| `tag` | Тег образа LogMonitoring. | Нет значения по умолчанию (необязательно) | string |",
    # --- .spec.templates.extensionExecutionController -----------------------
    "| `imageRef` | Image that is used for Extension Execution Controller. This field is mandatory. | No default (required) | [imageRef](#extension-controller-image-ref) |": "| `imageRef` | Образ, используемый для Extension Execution Controller. Это поле обязательно. | Нет значения по умолчанию (обязательно) | [imageRef](#extension-controller-image-ref) |",
    "| `persistentVolumeClaim` | PVC for the Extension Execution Controller. If not specified, a default PVC is used. | No default (optional) | PersistentVolumeClaim |": "| `persistentVolumeClaim` | PVC для Extension Execution Controller. Если не указано, используется PVC по умолчанию. | Нет значения по умолчанию (необязательно) | PersistentVolumeClaim |",
    "| `persistentVolumeClaim` | PVC for the Extension Execution Controller. If not specified a default PVC is used. | No default (optional) | PersistentVolumeClaim |": "| `persistentVolumeClaim` | PVC для Extension Execution Controller. Если не указано, используется PVC по умолчанию. | Нет значения по умолчанию (необязательно) | PersistentVolumeClaim |",
    "| `labels` | Labels applied to Extension Execution Controller pod. | No default (optional) | map[string]string |": "| `labels` | Метки, применяемые к поду Extension Execution Controller. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `labels` | Lables applied to Extension Execution Controller Pod. | No default (optional) | map[string]string |": "| `labels` | Метки, применяемые к поду Extension Execution Controller. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `annotations` | Annotations applied to Extension Execution Controller pod. | No default (optional) | map[string]string |": "| `annotations` | Аннотации, применяемые к поду Extension Execution Controller. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `annotations` | Annotations applied to Extension Execution Controller Pod. | No default (optional) | map[string]string |": "| `annotations` | Аннотации, применяемые к поду Extension Execution Controller. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `tlsRefName` | Secret containing a TLS certificate for communication between Extension Execution Controller and Dynatrace Collector. | No default (optional) | string |": "| `tlsRefName` | Секрет, содержащий TLS-сертификат для связи между Extension Execution Controller и Dynatrace Collector. | Нет значения по умолчанию (необязательно) | string |",
    "| `customConfig` | ConfigMap holding a custom Extension Execution Controller configuration. | No default (optional) | string |": "| `customConfig` | ConfigMap, содержащий пользовательскую конфигурацию Extension Execution Controller. | Нет значения по умолчанию (необязательно) | string |",
    "| `customExtensionCertificates` | Secret holding certificates that have been used to sign custom extensions. Needed for extensions signature validation by Extension Execution Controller. | No default (optional) | string |": "| `customExtensionCertificates` | Секрет, содержащий сертификаты, использованные для подписи пользовательских расширений. Необходим для проверки подписи расширений в Extension Execution Controller. | Нет значения по умолчанию (необязательно) | string |",
    "| `resources` | Resource settings for Extension Execution Controller pod. | No default (optional) | ResourceRequirements |": "| `resources` | Настройки ресурсов для пода Extension Execution Controller. | Нет значения по умолчанию (необязательно) | ResourceRequirements |",
    "| `resources` | Resource settings for Extension Execution Controller Pod. | No default (optional) | ResourceRequirements |": "| `resources` | Настройки ресурсов для пода Extension Execution Controller. | Нет значения по умолчанию (необязательно) | ResourceRequirements |",
    "| `tolerations` | Tolerations for Extension Execution Controller pod.For details, see [Taints and Tolerations](https://dt-url.net/od03765). | No default (optional) | []Toleration |": "| `tolerations` | Tolerations для пода Extension Execution Controller.Подробнее см. [Taints and Tolerations](https://dt-url.net/od03765). | Нет значения по умолчанию (необязательно) | []Toleration |",
    "| `tolerations` | Tolerations for Extension Execution Controller Pod.For details, see [Taints and Tolerations](https://dt-url.net/od03765). | No default (optional) | []Toleration |": "| `tolerations` | Tolerations для пода Extension Execution Controller.Подробнее см. [Taints and Tolerations](https://dt-url.net/od03765). | Нет значения по умолчанию (необязательно) | []Toleration |",
    "| `topologySpreadConstraints` | Topology spread constraints for Extension Execution Controller pod. | No default (optional) | []TopologySpreadConstraint |": "| `topologySpreadConstraints` | Topology spread constraints для пода Extension Execution Controller. | Нет значения по умолчанию (необязательно) | []TopologySpreadConstraint |",
    "| `topologySpreadConstraints` | Topology spread constraints for Extension Execution Controller Pod. | No default (optional) | []TopologySpreadConstraint |": "| `topologySpreadConstraints` | Topology spread constraints для пода Extension Execution Controller. | Нет значения по умолчанию (необязательно) | []TopologySpreadConstraint |",
    "| `useEphemeralVolume` | Indicates whether to use ephemeral volume for storage. | No default (optional) | boolean |": "| `useEphemeralVolume` | Указывает, использовать ли эфемерный том для хранения. | Нет значения по умолчанию (необязательно) | boolean |",
    "| `repository` | URL of Extension Execution Controller image. | No default (optional) | string |": "| `repository` | URL образа Extension Execution Controller. | Нет значения по умолчанию (необязательно) | string |",
    "| `tag` | Tag for Extension Execution Controller image. | No default (optional) | string |": "| `tag` | Тег образа Extension Execution Controller. | Нет значения по умолчанию (необязательно) | string |",
    # --- .spec.templates.otelCollector --------------------------------------
    "| `imageRef` | Image that is used for Dynatrace Collector. | No default (optional) | [imageRef](#extensions-collector-image-ref) |": "| `imageRef` | Образ, используемый для Dynatrace Collector. | Нет значения по умолчанию (необязательно) | [imageRef](#extensions-collector-image-ref) |",
    "| `replicas` | Number of Dynatrace Collector replicas. | 1 | int32 |": "| `replicas` | Количество реплик Dynatrace Collector. | 1 | int32 |",
    "| `labels` | Labels applied to Dynatrace Collector pod. | No default (optional) | map[string]string |": "| `labels` | Метки, применяемые к поду Dynatrace Collector. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `labels` | Labels applied to Dynatrace Collector Pod. | No default (optional) | map[string]string |": "| `labels` | Метки, применяемые к поду Dynatrace Collector. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `annotations` | Annotations applied to Dynatrace Collector pod. | No default (optional) | map[string]string |": "| `annotations` | Аннотации, применяемые к поду Dynatrace Collector. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `annotations` | Annotations applied to Dynatrace Collector Pod. | No default (optional) | map[string]string |": "| `annotations` | Аннотации, применяемые к поду Dynatrace Collector. | Нет значения по умолчанию (необязательно) | map[string]string |",
    "| `tlsRefName` | Secret containing a TLS certificate used by Dynatrace Collector to verify connections to endpoints of other components. | No default (optional) | string |": "| `tlsRefName` | Секрет, содержащий TLS-сертификат, используемый Dynatrace Collector для проверки соединений с конечными точками других компонентов. | Нет значения по умолчанию (необязательно) | string |",
    "| `resources` | Resource settings for Dynatrace Collector pod. | No default (optional) | ResourceRequirements |": "| `resources` | Настройки ресурсов для пода Dynatrace Collector. | Нет значения по умолчанию (необязательно) | ResourceRequirements |",
    "| `resources` | Resource settings for Dynatrace Collector Pod. | No default (optional) | ResourceRequirements |": "| `resources` | Настройки ресурсов для пода Dynatrace Collector. | Нет значения по умолчанию (необязательно) | ResourceRequirements |",
    "| `tolerations` | Tolerations for Dynatrace Collector pod.For details, see [Taints and Tolerations](https://dt-url.net/od03765). | No default (optional) | []Toleration |": "| `tolerations` | Tolerations для пода Dynatrace Collector.Подробнее см. [Taints and Tolerations](https://dt-url.net/od03765). | Нет значения по умолчанию (необязательно) | []Toleration |",
    "| `tolerations` | Tolerations for Dynatrace Collector Pod.For details, see [Taints and Tolerations](https://dt-url.net/od03765). | No default (optional) | []Toleration |": "| `tolerations` | Tolerations для пода Dynatrace Collector.Подробнее см. [Taints and Tolerations](https://dt-url.net/od03765). | Нет значения по умолчанию (необязательно) | []Toleration |",
    "| `topologySpreadConstraints` | Topology spread constraints for Dynatrace Collector pod. | No default (optional) | []TopologySpreadConstraint |": "| `topologySpreadConstraints` | Topology spread constraints для пода Dynatrace Collector. | Нет значения по умолчанию (необязательно) | []TopologySpreadConstraint |",
    "| `topologySpreadConstraints` | Topology spread constraints for Dynatrace Collector Pod. | No default (optional) | []TopologySpreadConstraint |": "| `topologySpreadConstraints` | Topology spread constraints для пода Dynatrace Collector. | Нет значения по умолчанию (необязательно) | []TopologySpreadConstraint |",
    "Adding this section deploys the Dynatrace Collector by the Operator.": "Добавление этого раздела разворачивает Dynatrace Collector силами Operator.",
    "| `repository` | URL of Dynatrace Collector image. | No default (optional) | string |": "| `repository` | URL образа Dynatrace Collector. | Нет значения по умолчанию (необязательно) | string |",
    "| `repository` | URL of Dynatrace Collector image. | `public.ecr.aws/dynatrace/dynatrace-otel-collector` | string |": "| `repository` | URL образа Dynatrace Collector. | `public.ecr.aws/dynatrace/dynatrace-otel-collector` | string |",
    "| `tag` | Tag for Dynatrace Collector image. | No default (optional) | string |": "| `tag` | Тег образа Dynatrace Collector. | Нет значения по умолчанию (необязательно) | string |",
    "| `tag` | Tag for Dynatrace Collector image. | `latest` | string |": "| `tag` | Тег образа Dynatrace Collector. | `latest` | string |",
    # --- .spec.templates.sqlExtensionExecutor -------------------------------
    "| `imageRef` | Image that is used for SQL Extension Executor. | No default (optional) | [imageRef](#extensions-sql-extension-executor-image-ref) |": "| `imageRef` | Образ, используемый для SQL Extension Executor. | Нет значения по умолчанию (необязательно) | [imageRef](#extensions-sql-extension-executor-image-ref) |",
    "| `tolerations` | Tolerations for SQL Extension Executor pods.For details, see [Taints and Tolerations](https://dt-url.net/od03765). | No default (optional) | []Toleration |": "| `tolerations` | Tolerations для подов SQL Extension Executor.Подробнее см. [Taints and Tolerations](https://dt-url.net/od03765). | Нет значения по умолчанию (необязательно) | []Toleration |",
    "| `repository` | URL of SQL Extension Executor image. | No default (optional) | string |": "| `repository` | URL образа SQL Extension Executor. | Нет значения по умолчанию (необязательно) | string |",
    "| `tag` | Tag for SQL Extension Executor image. | No default (optional) | string |": "| `tag` | Тег образа SQL Extension Executor. | Нет значения по умолчанию (необязательно) | string |",
    "| `persistentVolumeClaim` | Describes the common attributes of storage devices and allows a Source for provider-specific attributes. | No default (optional) | PersistentVolumeClaimSpec |": "| `persistentVolumeClaim` | Описывает общие атрибуты устройств хранения и допускает Source для атрибутов, специфичных для провайдера. | Нет значения по умолчанию (необязательно) | PersistentVolumeClaimSpec |",
    # --- legacy v1beta1/v1beta2 extras --------------------------------------
    "| `useCSIDriver` | Set if you want to use the CSIDriver. Don't enable it if you do not have access to Kubernetes nodes or if you lack privileges. | `false` | boolean |": "| `useCSIDriver` | Установите, если нужно использовать CSIDriver. Не включайте, если у вас нет доступа к узлам Kubernetes или недостаточно привилегий. | `false` | boolean |",
    "| `useCSIDriver` | Set if you want to use the CSI driver. Don't enable it if you do not have access to Kubernetes nodes or if you lack privileges. | `false` | boolean |": "| `useCSIDriver` | Установите, если нужно использовать CSI driver. Не включайте, если у вас нет доступа к узлам Kubernetes или недостаточно привилегий. | `false` | boolean |",
}

# Lines copied verbatim (footnote numbers and other bare identifiers).
PASS = {
    "1",
}


def read_lf(p):
    with open(p, "r", encoding="utf-8", newline="") as f:
        return f.read().replace("\r\n", "\n").replace("\r", "\n")


def build():
    en_path = os.path.join(BASE, "managed", REL)
    ru_path = os.path.join(BASE, "managed-ru", REL)
    en_lines = read_lf(en_path).split("\n")
    tmap = {MOJI_RE.sub("", k): v for k, v in TRANS.items()}
    passset = {MOJI_RE.sub("", k) for k in PASS}
    out = []
    in_fence = False
    for ln in en_lines:
        stripped = MOJI_RE.sub("", ln.strip())
        if stripped.startswith("```"):
            in_fence = not in_fence
            out.append(ln)
            continue
        if in_fence:
            out.append(ln)
            continue
        if stripped == "":
            out.append(ln)
            continue
        if stripped == "---":
            out.append(ln)
            continue
        if stripped.startswith("source:") or stripped.startswith("scraped:"):
            out.append(ln)
            continue
        if SPEC_HEAD_RE.match(stripped):
            out.append(ln)  # .spec field-path heading kept EN (preserves anchors)
            continue
        if SEP_RE.match(stripped):
            out.append(ln)  # table separator
            continue
        if stripped in tmap:
            indent = ln[: len(ln) - len(ln.lstrip())]
            out.append(indent + tmap[stripped])
            continue
        if stripped in passset:
            out.append(ln)
            continue
        raise SystemExit(f"UNTRANSLATED: {ln!r}")

    assert len(out) == len(en_lines), f"parity {len(out)} != {len(en_lines)}"
    os.makedirs(os.path.dirname(ru_path), exist_ok=True)
    with open(ru_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"OK  {len(out)} lines -> {ru_path}")


if __name__ == "__main__":
    build()
