# -*- coding: utf-8 -*-
"""L4-IF.72 — ingest-from/extensions/develop-your-extensions/extension-yaml.md"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/extensions/develop-your-extensions"

TRANS = {
    "* How-to guide": "* Практическое руководство",
    "* 5-min read": "* Чтение: 5 мин",
    "* Updated on Sep 19, 2022": "* Обновлено 19 сентября 2022 г.",
    "Your `extension.yaml` file defines the generic scope of your extension and is the core element of your extension package. It stores your environment configuration and is uploaded to your environment as a part of the extension ZIP package.": "Файл `extension.yaml` определяет общий охват расширения и является основным элементом пакета расширения. В нём хранится конфигурация окружения, и он загружается в окружение как часть пакета расширения ZIP.",
    "This topic describes core elements of the `extension.yaml` file applicable to any kind of extension from the Dynatrace Extensions framework. For elements specific to particular data source types, see:": "В этой статье описаны основные элементы файла `extension.yaml`, применимые к любому типу расширений платформы Dynatrace Extensions. Для элементов, характерных для конкретных типов источников данных, см.:",
    '* [SNMP extension](/managed/ingest-from/extensions/develop-your-extensions/data-sources/snmp-extensions "Learn how to create an SNMP extension using the Extensions framework.")': '* [Расширение SNMP](/managed/ingest-from/extensions/develop-your-extensions/data-sources/snmp-extensions "Узнайте, как создать расширение SNMP с помощью платформы Extensions.")',
    '* [WMI extension](/managed/ingest-from/extensions/develop-your-extensions/data-sources/wmi-extensions "Learn how to create a WMI extension using the Extensions framework.")': '* [Расширение WMI](/managed/ingest-from/extensions/develop-your-extensions/data-sources/wmi-extensions "Узнайте, как создать расширение WMI с помощью платформы Extensions.")',
    '* [Prometheus extension](/managed/ingest-from/extensions/develop-your-extensions/data-sources/prometheus-extensions "Learn how to create a Prometheus extension using the Extensions framework.")': '* [Расширение Prometheus](/managed/ingest-from/extensions/develop-your-extensions/data-sources/prometheus-extensions "Узнайте, как создать расширение Prometheus с помощью платформы Extensions.")',
    '* [JMX extension](/managed/ingest-from/extensions/develop-your-extensions/data-sources/jmx "Learn how to create a JMX extension using the Extensions framework.")': '* [Расширение JMX](/managed/ingest-from/extensions/develop-your-extensions/data-sources/jmx "Узнайте, как создать расширение JMX с помощью платформы Extensions.")',
    '* [SQL extension](/managed/ingest-from/extensions/develop-your-extensions/data-sources/sql "Learn how to create an SQL data source-based extension using the Extensions framework.")': '* [Расширение SQL](/managed/ingest-from/extensions/develop-your-extensions/data-sources/sql "Узнайте, как создать расширение на основе источника данных SQL с помощью платформы Extensions.")',
    "## Schemas": "## Схемы",
    'When you create the `extension.yaml` file, make sure to rely on the schemas provided through the [Extensions API](/managed/dynatrace-api/environment-api/extensions-20 "Learn how to manage extensions with the Dynatrace Extensions 2.0 API."). We recommend that you use an editor supporting schema validation and snippets, which significantly simplifies `extension.yaml` editing.': 'При создании файла `extension.yaml` используйте схемы, предоставляемые через [Extensions API](/managed/dynatrace-api/environment-api/extensions-20 "Узнайте, как управлять расширениями с помощью Dynatrace Extensions 2.0 API."). Рекомендуется использовать редактор с поддержкой проверки схем и сниппетов: это значительно упрощает редактирование `extension.yaml`.',
    "We recommend using the Dynatrace Extensions VS Code add-on provided by Dynatrace. For more information, see [Add-on for VS Code](https://dt-url.net/tx03uks/).": "Рекомендуется использовать дополнение Dynatrace Extensions для VS Code. Дополнительные сведения см. в разделе [Дополнение для VS Code](https://dt-url.net/tx03uks/).",
    "To download Extensions schemas:": "Чтобы загрузить схемы Extensions:",
    '1. Check available schema versions using the [GET all schemas](/managed/dynatrace-api/environment-api/extensions-20/schemas/get-all-schemas "View available extension schema versions via the Dynatrace Extensions 2.0 API.") endpoint. Schema version relate to Dynatrace Cluster versions.': '1. Проверьте доступные версии схем с помощью эндпоинта [GET all schemas](/managed/dynatrace-api/environment-api/extensions-20/schemas/get-all-schemas "Просмотрите доступные версии схем расширений через Dynatrace Extensions 2.0 API."). Версии схем соответствуют версиям Dynatrace Cluster.',
    "Response:": "Ответ:",
    '2. Use the [GET all files](/managed/dynatrace-api/environment-api/extensions-20/schemas/get-all-files "View available schema files in a schema version via the Dynatrace Extensions 2.0 API.") endpoint to list all available schemas for a specific Dynatrace version.': '2. Используйте эндпоинт [GET all files](/managed/dynatrace-api/environment-api/extensions-20/schemas/get-all-files "Просмотрите доступные файлы схем для конкретной версии Dynatrace через Dynatrace Extensions 2.0 API."), чтобы получить список всех доступных схем для конкретной версии Dynatrace.',
    "For example:": "Например:",
    '3. Use the [GET a file](/managed/dynatrace-api/environment-api/extensions-20/schemas/get-file "View an extension schema file via the Dynatrace Extensions 2.0 API.") endpoint to download a specific file in a specific version. For example, to download `extension.schema.json`, version `1.215`:': '3. Используйте эндпоинт [GET a file](/managed/dynatrace-api/environment-api/extensions-20/schemas/get-file "Просмотрите файл схемы расширения через Dynatrace Extensions 2.0 API."), чтобы загрузить конкретный файл нужной версии. Например, чтобы загрузить `extension.schema.json`, версия `1.215`:',
    "Alternatively, you can use the Dynatrace GitHub repository for [Extensions schemas](https://github.com/dynatrace-extensions/extensions-schemas).": "Также можно использовать репозиторий Dynatrace на GitHub для [схем Extensions](https://github.com/dynatrace-extensions/extensions-schemas).",
    "## Start extension YAML file": "## Начало файла YAML расширения",
    'The extension YAML file starts with basic information about the extension. It also contains optional references to [assets](/managed/ingest-from/extensions/concepts#extension-assets "Learn more about the concept of Dynatrace Extensions.") used by the extension.': 'Файл YAML расширения начинается с основной информации о расширении. Он также содержит необязательные ссылки на [ресурсы](/managed/ingest-from/extensions/concepts#extension-assets "Подробнее о концепции Dynatrace Extensions."), используемые расширением.',
    '* `name`—the name of your extension. A custom extension name (an extension not developed by Dynatrace) must start with `custom:`. The string must comply with the metric [ingestion protocol requirements](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#dimension-optional "Learn how the data ingestion protocol for Dynatrace Metrics API works.") for dimensions.': '* `name`: имя расширения. Имя пользовательского расширения (не разработанного Dynatrace) должно начинаться с `custom:`. Строка должна соответствовать [требованиям протокола приёма данных](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#dimension-optional "Узнайте, как работает протокол приёма данных для Dynatrace Metrics API.") для измерений.',
    "* `version`—the version of your extension in `major`.`minor`.`build` format, such as `1.0.0`. Your Dynatrace environment can store 10 extension versions, but only one can be active at the time.": "* `version`: версия расширения в формате `major`.`minor`.`build`, например `1.0.0`. В окружении Dynatrace можно хранить 10 версий расширения, но одновременно активна только одна.",
    '* `minDynatraceVersion`—the earliest Dynatrace version supported by the extension enclosed in quotes (`"`), such as `"1.213"`.': '* `minDynatraceVersion`: наиболее ранняя версия Dynatrace, поддерживаемая расширением, в кавычках (`"`), например `"1.213"`.',
    "* `author`—the extension developer or company.": "* `author`: разработчик или компания, создавшая расширение.",
    "* `dashboards`—the path to the dashboard definitions in the `extension.zip` archive relative to the extension YAML file. You can add up to 10 definitions.": "* `dashboards`: путь к определениям дашборда в архиве `extension.zip` относительно файла YAML расширения. Допускается до 10 определений.",
    "* `alerts`—the path to the custom metric events definitions in the `extension.zip` archive relative to the extension YAML file. You can add up to 10 definitions.": "* `alerts`: путь к определениям пользовательских событий метрик в архиве `extension.zip` относительно файла YAML расширения. Допускается до 10 определений.",
    "## Groups and subgroups": "## Группы и подгруппы",
    'You can organize your metrics into groups and subgroups to assign metrics within a group to specific [dimensions](#dimensions) or [feature sets](/managed/ingest-from/extensions/concepts#feature-sets "Learn more about the concept of Dynatrace Extensions."), or control the [interval](#interval) at which they\'re reported at a group level.': 'Метрики можно организовывать в группы и подгруппы, чтобы назначать метрики внутри группы определённым [измерениям](#dimensions) или [наборам функций](/managed/ingest-from/extensions/concepts#feature-sets "Подробнее о концепции Dynatrace Extensions."), а также управлять [интервалом](#interval) сбора данных на уровне группы.',
    "For each extension, you can define 10 groups, and each group can contain 10 subgroups.": "Для каждого расширения можно определить 10 групп, каждая из которых может содержать 10 подгрупп.",
    "For example:": "Например:",
    "## Interval": "## Интервал",
    "The interval at which the data measurement will be taken. You can define intervals at the group, subgroup, or individual metric level. You can define intervals with the granularity of one minute. The maximum interval is 2880 minutes (2 days, 48 hours).": "Интервал, с которым выполняется измерение данных. Интервалы можно задавать на уровне группы, подгруппы или отдельной метрики. Минимальная гранулярность интервала составляет одну минуту. Максимальный интервал составляет 2880 минут (2 дня, 48 часов).",
    "Setting the interval is not possible for JMX data sources.": "Для источников данных JMX задать интервал невозможно.",
    "The above format is supported starting with schema version 1.217. For earlier schema versions, use the following format (supported up to schema version 1.251):": "Указанный формат поддерживается начиная с версии схемы 1.217. Для более ранних версий схемы используйте следующий формат (поддерживается до версии схемы 1.251 включительно):",
    "## Metrics": "## Метрики",
    "You can define metrics at the extension, group, and subgroup level. The details on how you extract metric values vary depending on the data source type.": "Метрики можно определять на уровне расширения, группы и подгруппы. Способ извлечения значений метрик зависит от типа источника данных.",
    "See:": "См.:",
    '* [SNMP](/managed/ingest-from/extensions/develop-your-extensions/data-sources/snmp-extensions#dimensions "Learn how to create an SNMP extension using the Extensions framework.")': '* [SNMP](/managed/ingest-from/extensions/develop-your-extensions/data-sources/snmp-extensions#dimensions "Узнайте, как создать расширение SNMP с помощью платформы Extensions.")',
    '* [WMI](/managed/ingest-from/extensions/develop-your-extensions/data-sources/wmi-extensions#dimensions "Learn how to create a WMI extension using the Extensions framework.")': '* [WMI](/managed/ingest-from/extensions/develop-your-extensions/data-sources/wmi-extensions#dimensions "Узнайте, как создать расширение WMI с помощью платформы Extensions.")',
    "### Best practices for metric keys": "### Рекомендации по ключам метрик",
    "The metrics you ingest into Dynatrace using your extension are just some of the thousands of metrics, built-in and custom, processed by Dynatrace. To make your metrics keys unique and easy to identify in Dynatrace, the best practice is to prefix the metric name with the extension name. This guarantees that the metric key is unique and you can easily appoint a metric to a particular extension in your environment.": "Метрики, поступающие в Dynatrace через расширение, являются лишь частью тысяч встроенных и пользовательских метрик, обрабатываемых Dynatrace. Чтобы ключи метрик были уникальными и легко идентифицировались в Dynatrace, рекомендуется добавлять к имени метрики префикс с именем расширения. Это гарантирует уникальность ключа метрики и позволяет легко связать метрику с конкретным расширением в окружении.",
    "## Dimensions": "## Измерения",
    "You can define a dimension at the metric, group, and subgroup level. The details on how you extract dimension values vary depending on the data source type.": "Измерение можно определить на уровне метрики, группы и подгруппы. Способ извлечения значений измерения зависит от типа источника данных.",
    '* [Prometheus](/managed/ingest-from/extensions/develop-your-extensions/data-sources/prometheus-extensions#dimensions "Learn how to create a Prometheus extension using the Extensions framework.")': '* [Prometheus](/managed/ingest-from/extensions/develop-your-extensions/data-sources/prometheus-extensions#dimensions "Узнайте, как создать расширение Prometheus с помощью платформы Extensions.")',
    "## Variables": "## Переменные",
    "If you want to make your extension customizable with the monitoring configuration, you can use variables that will be replaced by values passed from the monitoring configuration. You can use variables directly as the dimension value or with [filters](#filters). To use variables, you must first declare them in your extension YAML file:": "Чтобы расширение было настраиваемым через конфигурацию мониторинга, применяйте переменные, которые заменяются значениями из конфигурации мониторинга. Переменные можно использовать напрямую как значение измерения или совместно с [фильтрами](#filters). Перед использованием переменные необходимо объявить в файле YAML расширения:",
    "There are three types of variables that can be used in your variables definition:": "В определении переменных доступны три типа:",
    "* `text`—allows you to provide a plain text value.": "* `text`: позволяет задать значение в виде простого текста.",
    "+ `displayName`—the name visible in Dynatrace Hub.": "+ `displayName`: имя, отображаемое в Dynatrace Hub.",
    "+ `maxLength`—the maximum length of the variable value (up to 10,000).": "+ `maxLength`: максимальная длина значения переменной (до 10 000).",
    "+ `required`—whether providing a value is required for this variable.": "+ `required`: обязательность указания значения для данной переменной.",
    "+ `defaultValue`—the default value if no value is specified in the REST API.": "+ `defaultValue`: значение по умолчанию, если значение не задано в REST API.",
    "+ `pattern`—a regular expression pattern that must be fulfilled by the provided value.": "+ `pattern`: шаблон регулярного выражения, которому должно соответствовать введённое значение.",
    "* `multiline-text`—allows you to provide plain text with the new line symbols. For details on multiline YAML syntax, see [YAML Multiline](https://dt-url.net/1m034c2).": "* `multiline-text`: позволяет задать простой текст с символами новой строки. Подробнее о многострочном синтаксисе YAML см. [YAML Multiline](https://dt-url.net/1m034c2).",
    "+ `maxLength`—the maximum length of a variable value (up to 10,000).": "+ `maxLength`: максимальная длина значения переменной (до 10 000).",
    "* `enum`—allows you to define your own set of possible values.": "* `enum`: позволяет задать собственный набор допустимых значений.",
    "+ Optional `defaultValue`—if defined, sets the default value for the whole set and makes the variable required.": "+ Необязательный `defaultValue`: если задан, устанавливает значение по умолчанию для всего набора и делает переменную обязательной.",
    "Define the possible values in `availableValues` list:": "Определите допустимые значения в списке `availableValues`:",
    "+ `value`—the value passed to the extension.": "+ `value`: значение, передаваемое в расширение.",
    "## Filters": "## Фильтры",
    "After you define the filter as a [variable](#variables), you can add filtering logic that will result in reporting only the dimensions that match the filtering criteria.": "После того как фильтр определён как [переменная](#variables), можно добавить логику фильтрации, чтобы передавались только те измерения, которые соответствуют критериям фильтрации.",
    "Define the filter based on a condition as follows:": "Определите фильтр на основе условия следующим образом:",
    "* **Starts with** – use a `const:$prefix` qualifier. Example:": "* **Starts with**: используйте квалификатор `const:$prefix`. Пример:",
    "* **Ends with** – use a `const:$suffix` qualifier. Example:": "* **Ends with**: используйте квалификатор `const:$suffix`. Пример:",
    "* **Contains** – use a `const:$contains` qualifier. Example:": "* **Contains**: используйте квалификатор `const:$contains`. Пример:",
    "* **Equals** – use a `const:$eq` qualifier. Example:": "* **Equals**: используйте квалификатор `const:$eq`. Пример:",
    "For the expressions mentioned above, you can also use qualifiers:": "Для перечисленных выше выражений также доступны следующие квалификаторы:",
    "+ `const:$and` – to chain two or more expressions with AND operator. Example:": "+ `const:$and`: для объединения двух или более выражений оператором AND. Пример:",
    "+ a `const:$or` – to chain two or more expressions with OR operator. Example:": "+ `const:$or`: для объединения двух или более выражений оператором OR. Пример:",
    "+ a `const:$not` – to negate an expression. Example:": "+ `const:$not`: для отрицания выражения. Пример:",
    'The filtering logic is different for WMI extensions, where you pass the condition as a query. For more information, see [Filter extracted dimensions](/managed/ingest-from/extensions/develop-your-extensions/data-sources/wmi-extensions/wmi-schema-reference#filter-extracted-dimensions "Learn about WMI extensions in the Extensions framework.").': 'Логика фильтрации для расширений WMI отличается: условие передаётся в виде запроса. Дополнительные сведения см. в разделе [Фильтрация извлечённых измерений](/managed/ingest-from/extensions/develop-your-extensions/data-sources/wmi-extensions/wmi-schema-reference#filter-extracted-dimensions "Узнайте о расширениях WMI в платформе Extensions.").',
}

PASS = {
    "title: Extension YAML file",
    "# Extension YAML file",
}

if __name__ == "__main__":
    build_one(REL, "extension-yaml.md", TRANS, PASS)
    qa_one(REL, "extension-yaml.md")
