# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/amazon-web-services/integrate-with-aws"

TRANS = {
    "title: Monitor Amazon Web Services with CloudWatch metrics": "title: Мониторинг Amazon Web Services с помощью метрик CloudWatch",
    "# Monitor Amazon Web Services with CloudWatch metrics": "# Мониторинг Amazon Web Services с помощью метрик CloudWatch",
    "* How-to guide": "* Практическое руководство",
    "* 23-min read": "* Чтение: 23 мин",
    "* Updated on Mar 04, 2026": "* Обновлено 04 марта 2026 г.",
    "Follow this guide to start ingesting data remotely from Amazon CloudWatch.": "Следуйте этому руководству, чтобы начать удалённый приём данных из Amazon CloudWatch.",
    "Its main focus is on infrastructure monitoring of AWS services: Dynatrace monitoring AWS services via CloudWatch.": "Основное внимание уделяется мониторингу инфраструктуры сервисов AWS: Dynatrace отслеживает сервисы AWS через CloudWatch.",
    "See [What's next?](#next) for Full-Stack and Log Monitoring of your AWS services.": "Сведения о мониторинге полного стека и логов AWS-сервисов см. в разделе [Что дальше?](#next).",
    "After you have established the initial monitoring, you can add, remove, or modify service monitoring using the Dynatrace web UI, at scale, or using the Dynatrace API.": "После настройки первоначального мониторинга можно добавлять, удалять или изменять мониторинг сервисов через веб-интерфейс Dynatrace, в масштабе или с помощью Dynatrace API.",
    "Details of collected measurements": "Сведения о собираемых измерениях",
    "To learn the measurements collected for each of the AWS services, see:": "Сведения об измерениях, собираемых для каждого из сервисов AWS, см. в:",
    "* [AWS cloud services enabled by default and metrics](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/default-aws-metrics \"The list of classic (formerly 'built-in') metrics Dynatrace collects by default for AWS monitoring.\")": "* [Облачные сервисы AWS, включённые по умолчанию, и метрики](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/default-aws-metrics \"Список классических (ранее «встроенных») метрик, которые Dynatrace собирает по умолчанию для мониторинга AWS.\")",
    "* [AWS cloud services](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Monitor all AWS cloud services with Dynatrace and view available metrics.\")": "* [Облачные сервисы AWS](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Мониторинг всех облачных сервисов AWS с помощью Dynatrace и просмотр доступных метрик.\")",
    "The Amazon Web Services infrastructure monitoring provides metrics from CloudWatch, infrastructure data available via public AWS API, and specific events. The data is collected in five-minute intervals.": "Мониторинг инфраструктуры Amazon Web Services обеспечивает сбор метрик из CloudWatch, данных инфраструктуры через публичный AWS API и определённых событий. Данные собираются с интервалом в пять минут.",
    "## Cost of monitoring": "## Стоимость мониторинга",
    "* Each service monitored by Dynatrace through CloudWatch, as well as log processing and analysis, consumes [DDUs](/managed/license/monitoring-consumption-classic/davis-data-units \"Understand how Dynatrace monitoring consumption is calculated based on Davis data units (DDU).\").": "* Каждый сервис, отслеживаемый Dynatrace через CloudWatch, а также обработка и анализ логов потребляют [DDU](/managed/license/monitoring-consumption-classic/davis-data-units \"Принципы расчёта потребления мониторинга Dynatrace на основе единиц данных Davis (DDU).\").",
    "* Amazon may charge you extra for CloudWatch metric queries. For details on these additional costs, please consult [Amazon CloudWatch pricing online documentation](https://aws.amazon.com/cloudwatch/pricing/).": "* Amazon может взимать дополнительную плату за запросы метрик CloudWatch. Подробнее о дополнительных расходах см. в [онлайн-документации по ценам Amazon CloudWatch](https://aws.amazon.com/cloudwatch/pricing/).",
    "## Monitoring prerequisites": "## Предварительные требования для мониторинга",
    "There are three prerequisites for the AWS monitoring setup:": "Для настройки мониторинга AWS необходимо выполнить три предварительных условия:",
    "1. Dynatrace admin permissions": "1. Права администратора Dynatrace",
    "To manage AWS monitoring configuration, you need permissions to read and modify the `builtin:cloud.aws` schema.": "Для управления конфигурацией мониторинга AWS необходимы разрешения на чтение и изменение схемы `builtin:cloud.aws`.",
    "* Both `settings:objects:read` and `settings:objects:write` are required.": "* Требуются как `settings:objects:read`, так и `settings:objects:write`.",
    "* They are included in the **Change monitoring settings** permissions.": "* Они включены в разрешения **Change monitoring settings**.",
    "* Read-only access is not supported.": "* Доступ только для чтения не поддерживается.",
    "See [Manage user permissions with roles](/managed/manage/identity-access-management/permission-management/role-based-permissions \"Role-based permissions\") for details on how to manage and set permissions.": "Сведения об управлении разрешениями и их настройке см. в разделе [Управление разрешениями пользователей с помощью ролей](/managed/manage/identity-access-management/permission-management/role-based-permissions \"Разрешения на основе ролей\").",
    "2. Allow ActiveGate to access URLs": "2. Разрешить ActiveGate доступ к URL",
    "To monitor Amazon Web Services, Dynatrace needs to be able to connect to the Amazon CloudWatch API and query it periodically. At least one ActiveGate needs to be able to connect to Amazon CloudWatch to perform the monitoring tasks. Your ActiveGate needs to be deployed on an EC2 instance and be able to connect to the endpoints listed below.": "Для мониторинга Amazon Web Services Dynatrace необходимо периодически подключаться к Amazon CloudWatch API и отправлять запросы. Как минимум один ActiveGate должен иметь возможность подключаться к Amazon CloudWatch для выполнения задач мониторинга. ActiveGate должен быть развёрнут на экземпляре EC2 и иметь доступ к эндпоинтам, перечисленным ниже.",
    "From Dynatrace version 1.267+, only role-based access can be used. Key-based authorization is no longer available for new credentials. For existing key-based credentials, you can keep using keys indefinitely. We recommend switching to role-based authentication using the dedicated button on the configuration page. Dynatrace automatically checks the configuration to ensure the correct configuration of roles.": "Начиная с Dynatrace версии 1.267+, можно использовать только доступ на основе ролей. Авторизация на основе ключей больше недоступна для новых учётных данных. Для существующих учётных данных на основе ключей можно продолжать использовать ключи бессрочно. Рекомендуется перейти на аутентификацию на основе ролей с помощью специальной кнопки на странице конфигурации. Dynatrace автоматически проверяет конфигурацию для обеспечения правильной настройки ролей.",
    "[Key-based authentication](#key-based-authentication) is allowed only for AWS GovCloud and China partitions.": "[Аутентификация на основе ключей](#key-based-authentication) разрешена только для разделов AWS GovCloud и China.",
    "#### Allow ActiveGate to access AWS URLs": "#### Разрешить ActiveGate доступ к URL AWS",
    "The integration accesses the following AWS API endpoints, so they must be accessible from your ActiveGate:": "Интеграция обращается к следующим эндпоинтам AWS API, поэтому они должны быть доступны из вашего ActiveGate:",
    "* AWS Security Token Service (AWS STS)": "* AWS Security Token Service (AWS STS)",
    "Environment ActiveGate version 1.329+": "Environment ActiveGate версии 1.329+",
    "Environment ActiveGate version 1.328 and earlier": "Environment ActiveGate версии 1.328 и ниже",
    "Starting with Dynatrace version 1.329, the AWS STS global endpoint is not supported. Make sure that `sts.<REGION>.amazonaws.com` is accessible for the regions you want to monitor.": "Начиная с Dynatrace версии 1.329 глобальный эндпоинт AWS STS не поддерживается. Убедитесь, что `sts.<REGION>.amazonaws.com` доступен для регионов, которые требуется отслеживать.",
    "The `us-west-2` region is now the default region for ActiveGate. In case of connectivity issues, ensure that the `sts.us-west-2.amazonaws.com` endpoint is enabled.": "Регион `us-west-2` теперь является регионом ActiveGate по умолчанию. При возникновении проблем с подключением убедитесь, что эндпоинт `sts.us-west-2.amazonaws.com` доступен.",
    "See [AWS STS Regionalized endpoints](https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html) for details.": "Подробнее см. в разделе [Регионализованные эндпоинты AWS STS](https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html).",
    "* AWS Resource Groups Tagging": "* AWS Resource Groups Tagging",
    "* Amazon CloudWatch": "* Amazon CloudWatch",
    "* Amazon EC2": "* Amazon EC2",
    "Other endpoints may be required depending on the services you need to monitor.": "В зависимости от отслеживаемых сервисов могут потребоваться другие эндпоинты.",
    "Consult the tables below for endpoints specific to each service you might want to monitor and for AWS Regions supported by Dynatrace AWS Monitoring.": "Обратитесь к таблицам ниже для получения эндпоинтов, специфичных для каждого отслеживаемого сервиса, и AWS-регионов, поддерживаемых Dynatrace AWS Monitoring.",
    "### AWS endpoints that need to be reachable from ActiveGate with corresponding AWS services": "### Эндпоинты AWS, которые должны быть доступны из ActiveGate, с соответствующими сервисами AWS",
    "| Endpoint | Service |": "| Эндпоинт | Сервис |",
    "| --- | --- |": "| --- | --- |",
    "| `autoscaling.<REGION>.amazonaws.com` | Amazon EC2 Auto Scaling (built-in), Amazon EC2 Auto Scaling |": "| `autoscaling.<REGION>.amazonaws.com` | Amazon EC2 Auto Scaling (built-in), Amazon EC2 Auto Scaling |",
    "| `lambda.<REGION>.amazonaws.com` | AWS Lambda (built-in), AWS Lambda |": "| `lambda.<REGION>.amazonaws.com` | AWS Lambda (built-in), AWS Lambda |",
    "| `elasticloadbalancing.<REGION>.amazonaws.com` | Amazon Application and Network Load Balancer (built-in), Amazon Elastic Load Balancer (ELB) (built-in) |": "| `elasticloadbalancing.<REGION>.amazonaws.com` | Amazon Application and Network Load Balancer (built-in), Amazon Elastic Load Balancer (ELB) (built-in) |",
    "| `dynamodb.<REGION>.amazonaws.com` | Amazon DynamoDB (built-in), Amazon DynamoDB |": "| `dynamodb.<REGION>.amazonaws.com` | Amazon DynamoDB (built-in), Amazon DynamoDB |",
    "| `ec2.<REGION>.amazonaws.com` | Amazon EBS (built-in), Amazon EC2 (built-in), Amazon EBS, Amazon EC2 Spot Fleet, Amazon VPC NAT Gateways, AWS Transit Gateway, AWS Site-to-Site VPN |": "| `ec2.<REGION>.amazonaws.com` | Amazon EBS (built-in), Amazon EC2 (built-in), Amazon EBS, Amazon EC2 Spot Fleet, Amazon VPC NAT Gateways, AWS Transit Gateway, AWS Site-to-Site VPN |",
    "| `rds.<REGION>.amazonaws.com` | Amazon RDS (built-in), Amazon Aurora, Amazon DocumentDB, Amazon Neptune, Amazon RDS |": "| `rds.<REGION>.amazonaws.com` | Amazon RDS (built-in), Amazon Aurora, Amazon DocumentDB, Amazon Neptune, Amazon RDS |",
    "| `s3.<REGION>.amazonaws.com` | Amazon S3 (built-in) |": "| `s3.<REGION>.amazonaws.com` | Amazon S3 (built-in) |",
    "| `acm-pca.<REGION>.amazonaws.com` | AWS Certificate Manager Private Certificate Authority |": "| `acm-pca.<REGION>.amazonaws.com` | AWS Certificate Manager Private Certificate Authority |",
    "| `apigateway.<REGION>.amazonaws.com` | Amazon API Gateway |": "| `apigateway.<REGION>.amazonaws.com` | Amazon API Gateway |",
    "| `apprunner.<REGION>.amazonaws.com` | AWS App Runner |": "| `apprunner.<REGION>.amazonaws.com` | AWS App Runner |",
    "| `appstream2.<REGION>.amazonaws.com` | Amazon AppStream |": "| `appstream2.<REGION>.amazonaws.com` | Amazon AppStream |",
    "| `appsync.<REGION>.amazonaws.com` | AWS AppSync |": "| `appsync.<REGION>.amazonaws.com` | AWS AppSync |",
    "| `athena.<REGION>.amazonaws.com` | Amazon Athena |": "| `athena.<REGION>.amazonaws.com` | Amazon Athena |",
    "| `cloudfront.amazonaws.com` | Amazon CloudFront |": "| `cloudfront.amazonaws.com` | Amazon CloudFront |",
    "| `cloudhsmv2.<REGION>.amazonaws.com` | AWS CloudHSM |": "| `cloudhsmv2.<REGION>.amazonaws.com` | AWS CloudHSM |",
    "| `cloudsearch.<REGION>.amazonaws.com` | Amazon CloudSearch |": "| `cloudsearch.<REGION>.amazonaws.com` | Amazon CloudSearch |",
    "| `codebuild.<REGION>.amazonaws.com` | AWS CodeBuild |": "| `codebuild.<REGION>.amazonaws.com` | AWS CodeBuild |",
    "| `datasync.<REGION>.amazonaws.com` | AWS DataSync |": "| `datasync.<REGION>.amazonaws.com` | AWS DataSync |",
    "| `dax.<REGION>.amazonaws.com` | Amazon DynamoDB Accelerator (DAX) |": "| `dax.<REGION>.amazonaws.com` | Amazon DynamoDB Accelerator (DAX) |",
    "| `dms.<REGION>.amazonaws.com` | AWS Database Migration Service (AWS DMS) |": "| `dms.<REGION>.amazonaws.com` | AWS Database Migration Service (AWS DMS) |",
    "| `directconnect.<REGION>.amazonaws.com` | AWS Direct Connect |": "| `directconnect.<REGION>.amazonaws.com` | AWS Direct Connect |",
    "| `ecs.<REGION>.amazonaws.com` | Amazon Elastic Container Service (ECS), Amazon ECS Container Insights |": "| `ecs.<REGION>.amazonaws.com` | Amazon Elastic Container Service (ECS), Amazon ECS Container Insights |",
    "| `elasticfilesystem.<REGION>.amazonaws.com` | Amazon Elastic File System (EFS) |": "| `elasticfilesystem.<REGION>.amazonaws.com` | Amazon Elastic File System (EFS) |",
    "| `eks.<REGION>.amazonaws.com` | Amazon Elastic Kubernetes Service (EKS) |": "| `eks.<REGION>.amazonaws.com` | Amazon Elastic Kubernetes Service (EKS) |",
    "| `elasticache.<REGION>.amazonaws.com` | Amazon ElastiCache (EC) |": "| `elasticache.<REGION>.amazonaws.com` | Amazon ElastiCache (EC) |",
    "| `elasticbeanstalk.<REGION>.amazonaws.com` | AWS Elastic Beanstalk |": "| `elasticbeanstalk.<REGION>.amazonaws.com` | AWS Elastic Beanstalk |",
    "| `elastictranscoder.<REGION>.amazonaws.com` | Amazon Elastic Transcoder |": "| `elastictranscoder.<REGION>.amazonaws.com` | Amazon Elastic Transcoder |",
    "| `es.<REGION>.amazonaws.com` | Amazon Elasticsearch Service (ES) |": "| `es.<REGION>.amazonaws.com` | Amazon Elasticsearch Service (ES) |",
    "| `events.<REGION>.amazonaws.com` | Amazon EventBridge |": "| `events.<REGION>.amazonaws.com` | Amazon EventBridge |",
    "| `fsx.<REGION>.amazonaws.com` | Amazon FSx |": "| `fsx.<REGION>.amazonaws.com` | Amazon FSx |",
    "| `gamelift.<REGION>.amazonaws.com` | Amazon GameLift |": "| `gamelift.<REGION>.amazonaws.com` | Amazon GameLift |",
    "| `glue.<REGION>.amazonaws.com` | AWS Glue |": "| `glue.<REGION>.amazonaws.com` | AWS Glue |",
    "| `inspector.<REGION>.amazonaws.com` | Amazon Inspector |": "| `inspector.<REGION>.amazonaws.com` | Amazon Inspector |",
    "| `kafka.<REGION>.amazonaws.com` | Amazon Managed Streaming for Kafka |": "| `kafka.<REGION>.amazonaws.com` | Amazon Managed Streaming for Kafka |",
    "| `models.lex.<REGION>.amazonaws.com` | Amazon Lex |": "| `models.lex.<REGION>.amazonaws.com` | Amazon Lex |",
    "| `logs.<REGION>.amazonaws.com` | Amazon CloudWatch Logs |": "| `logs.<REGION>.amazonaws.com` | Amazon CloudWatch Logs |",
    "| `api.mediatailor.<REGION>.amazonaws.com` | AWS Elemental MediaTailor |": "| `api.mediatailor.<REGION>.amazonaws.com` | AWS Elemental MediaTailor |",
    "| `mediaconnect.<REGION>.amazonaws.com` | AWS Elemental MediaConnect |": "| `mediaconnect.<REGION>.amazonaws.com` | AWS Elemental MediaConnect |",
    "| `mediapackage.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Live |": "| `mediapackage.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Live |",
    "| `mediapackage-vod.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Video on Demand |": "| `mediapackage-vod.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Video on Demand |",
    "| `opsworks.<REGION>.amazonaws.com` | AWS OpsWorks |": "| `opsworks.<REGION>.amazonaws.com` | AWS OpsWorks |",
    "| `qldb.<REGION>.amazonaws.com` | Amazon QLDB |": "| `qldb.<REGION>.amazonaws.com` | Amazon QLDB |",
    "| `redshift.<REGION>.amazonaws.com` | Amazon Redshift |": "| `redshift.<REGION>.amazonaws.com` | Amazon Redshift |",
    "| `robomaker.<REGION>.amazonaws.com` | AWS RoboMaker |": "| `robomaker.<REGION>.amazonaws.com` | AWS RoboMaker |",
    "| `route53.amazonaws.com` | Amazon Route 53 |": "| `route53.amazonaws.com` | Amazon Route 53 |",
    "| `route53resolver.<REGION>.amazonaws.com` | Amazon Route 53 Resolver |": "| `route53resolver.<REGION>.amazonaws.com` | Amazon Route 53 Resolver |",
    "| `api.sagemaker.<REGION>.amazonaws.com` | Amazon SageMaker Endpoints, Amazon SageMaker Endpoint Instances |": "| `api.sagemaker.<REGION>.amazonaws.com` | Amazon SageMaker Endpoints, Amazon SageMaker Endpoint Instances |",
    "| `sns.<REGION>.amazonaws.com` | Amazon Simple Notification Service (SNS) |": "| `sns.<REGION>.amazonaws.com` | Amazon Simple Notification Service (SNS) |",
    "| `sqs.<REGION>.amazonaws.com` | Amazon Simple Queue Service (SQS) |": "| `sqs.<REGION>.amazonaws.com` | Amazon Simple Queue Service (SQS) |",
    "| `storagegateway.<REGION>.amazonaws.com` | AWS Storage Gateway |": "| `storagegateway.<REGION>.amazonaws.com` | AWS Storage Gateway |",
    "| `swf.<REGION>.amazonaws.com` | Amazon SWF |": "| `swf.<REGION>.amazonaws.com` | Amazon SWF |",
    "| `transfer.<REGION>.amazonaws.com` | AWS Transfer Family |": "| `transfer.<REGION>.amazonaws.com` | AWS Transfer Family |",
    "| `workmail.<REGION>.amazonaws.com` | Amazon WorkMail |": "| `workmail.<REGION>.amazonaws.com` | Amazon WorkMail |",
    "| `workspaces.<REGION>.amazonaws.com` | Amazon WorkSpaces |": "| `workspaces.<REGION>.amazonaws.com` | Amazon WorkSpaces |",
    "### AWS Regions supported by Dynatrace AWS Monitoring": "### Регионы AWS, поддерживаемые Dynatrace AWS Monitoring",
    "* `us-gov-west-1`: AWS GovCloud (US)": "* `us-gov-west-1`: AWS GovCloud (US)",
    "* `us-gov-east-1`: AWS GovCloud (US-East)": "* `us-gov-east-1`: AWS GovCloud (US-East)",
    "* `us-east-1`: US East (N. Virginia)": "* `us-east-1`: US East (N. Virginia)",
    "* `us-east-2`: US East (Ohio)": "* `us-east-2`: US East (Ohio)",
    "* `us-west-1`: US West (N. California)": "* `us-west-1`: US West (N. California)",
    "* `us-west-2`: US West (Oregon)": "* `us-west-2`: US West (Oregon)",
    "* `eu-west-1`: EU (Ireland)": "* `eu-west-1`: EU (Ireland)",
    "* `eu-west-2`: EU (London)": "* `eu-west-2`: EU (London)",
    "* `eu-west-3`: EU (Paris)": "* `eu-west-3`: EU (Paris)",
    "* `eu-central-1`: EU (Frankfurt)": "* `eu-central-1`: EU (Frankfurt)",
    "* `eu-central-2`: EU (Zurich)": "* `eu-central-2`: EU (Zurich)",
    "* `eu-north-1`: EU (Stockholm)": "* `eu-north-1`: EU (Stockholm)",
    "* `eu-south-1`: EU (Milan)": "* `eu-south-1`: EU (Milan)",
    "* `eu-south-2`: EU (Spain)": "* `eu-south-2`: EU (Spain)",
    "* `ap-east-1`: Asia Pacific (Hong Kong)": "* `ap-east-1`: Asia Pacific (Hong Kong)",
    "* `ap-east-2`: Asia Pacific (Taipei)": "* `ap-east-2`: Asia Pacific (Taipei)",
    "* `ap-south-1`: Asia Pacific (Mumbai)": "* `ap-south-1`: Asia Pacific (Mumbai)",
    "* `ap-south-2`: Asia Pacific (Hyderabad)": "* `ap-south-2`: Asia Pacific (Hyderabad)",
    "* `ap-southeast-1`: Asia Pacific (Singapore)": "* `ap-southeast-1`: Asia Pacific (Singapore)",
    "* `ap-southeast-2`: Asia Pacific (Sydney)": "* `ap-southeast-2`: Asia Pacific (Sydney)",
    "* `ap-southeast-3`: Asia Pacific (Jakarta)": "* `ap-southeast-3`: Asia Pacific (Jakarta)",
    "* `ap-southeast-4`: Asia Pacific (Melbourne)": "* `ap-southeast-4`: Asia Pacific (Melbourne)",
    "* `ap-southeast-5`: Asia Pacific (Malaysia)": "* `ap-southeast-5`: Asia Pacific (Malaysia)",
    "* `ap-southeast-6`: Asia Pacific (New Zealand)": "* `ap-southeast-6`: Asia Pacific (New Zealand)",
    "* `ap-southeast-7`: Asia Pacific (Thailand)": "* `ap-southeast-7`: Asia Pacific (Thailand)",
    "* `ap-northeast-1`: Asia Pacific (Tokyo)": "* `ap-northeast-1`: Asia Pacific (Tokyo)",
    "* `ap-northeast-2`: Asia Pacific (Seoul)": "* `ap-northeast-2`: Asia Pacific (Seoul)",
    "* `ap-northeast-3`: Asia Pacific (Osaka)": "* `ap-northeast-3`: Asia Pacific (Osaka)",
    "* `sa-east-1`: South America (Sao Paulo)": "* `sa-east-1`: South America (Sao Paulo)",
    "* `cn-north-1`: China (Beijing)": "* `cn-north-1`: China (Beijing)",
    "* `cn-northwest-1`: China (Ningxia)": "* `cn-northwest-1`: China (Ningxia)",
    "* `ca-central-1`: Canada (Central)": "* `ca-central-1`: Canada (Central)",
    "* `ca-west-1`: Canada West (Calgary)": "* `ca-west-1`: Canada West (Calgary)",
    "* `il-central-1`: Israel (Tel Aviv)": "* `il-central-1`: Israel (Tel Aviv)",
    "* `me-central-1`: Middle East (UAE)": "* `me-central-1`: Middle East (UAE)",
    "* `me-south-1`: Middle East (Bahrain)": "* `me-south-1`: Middle East (Bahrain)",
    "* `mx-central-1`: Mexico (Central)": "* `mx-central-1`: Mexico (Central)",
    "* `af-south-1`: Africa (Cape Town)": "* `af-south-1`: Africa (Cape Town)",
    "* `us-iso-east-1`: US ISO East": "* `us-iso-east-1`: US ISO East",
    "* `us-isob-east-1`: US ISOB East (Ohio)": "* `us-isob-east-1`: US ISOB East (Ohio)",
    "* `us-iso-west-1`: US ISO West": "* `us-iso-west-1`: US ISO West",
    "Proxy": "Прокси",
    "The most frequent cause of certificate issues with the TLS interception proxy is a missing proxy's CA certificate in the ActiveGate truststore.": "Наиболее частой причиной проблем с сертификатами при использовании TLS-перехватывающего прокси является отсутствие CA-сертификата прокси в хранилище доверенных сертификатов ActiveGate.",
    "If you're still having proxy issues, see:": "Если проблемы с прокси сохраняются, обратитесь к:",
    "* [Proxy for ActiveGate](/managed/ingest-from/dynatrace-activegate/configuration/set-up-proxy-authentication-for-activegate \"Learn how to configure ActiveGate properties to set up a proxy.\")": "* [Прокси для ActiveGate](/managed/ingest-from/dynatrace-activegate/configuration/set-up-proxy-authentication-for-activegate \"Настройка свойств ActiveGate для использования прокси.\")",
    "* [Trusted root certificates for ActiveGate](/managed/ingest-from/dynatrace-activegate/configuration/configure-trusted-root-certificates-on-activegate \"Learn how to configure custom trusted root certificates on ActiveGate to establish secure SSL/TLS connections.\")": "* [Доверенные корневые сертификаты для ActiveGate](/managed/ingest-from/dynatrace-activegate/configuration/configure-trusted-root-certificates-on-activegate \"Настройка пользовательских доверенных корневых сертификатов на ActiveGate для защищённых SSL/TLS-соединений.\")",
    "* [Custom SSL certificate for ActiveGate](/managed/ingest-from/dynatrace-activegate/configuration/configure-custom-ssl-certificate-on-activegate \"Learn how to configure the SSL certificate on your ActiveGate.\")": "* [Пользовательский SSL-сертификат для ActiveGate](/managed/ingest-from/dynatrace-activegate/configuration/configure-custom-ssl-certificate-on-activegate \"Настройка SSL-сертификата на ActiveGate.\")",
    "\"Communication error.\"": "«Ошибка связи.»",
    "Make sure that the URLs are whitelisted. Otherwise, you might get communication or timeout errors.": "Убедитесь, что URL-адреса занесены в белый список. В противном случае могут возникнуть ошибки связи или тайм-аута.",
    "3. AWS monitoring policy and role-based authentication": "3. Политика мониторинга AWS и аутентификация на основе ролей",
    "To perform these steps, you need to have AWS admin privileges.": "Для выполнения этих шагов необходимы права администратора AWS.",
    "The AWS monitoring policy defines the minimal scope of permissions you need to give to Dynatrace to monitor the services running in your AWS account. Create it once and use it any time when enabling Dynatrace access to your AWS account.": "Политика мониторинга AWS определяет минимальный набор разрешений, которые необходимо предоставить Dynatrace для мониторинга сервисов, работающих в вашей учётной записи AWS. Создайте её один раз и используйте при каждом включении доступа Dynatrace к учётной записи AWS.",
    "If you don't want to add permissions to all services, and just select permissions for certain services, consult the table below. The table contains a set of permissions that are required for [all AWS cloud services](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Monitor all AWS cloud services with Dynatrace and view available metrics.\"), a list of optional permissions specific to that service.": "Если вы не хотите добавлять разрешения для всех сервисов и хотите выбрать разрешения только для определённых сервисов, обратитесь к таблице ниже. Таблица содержит набор разрешений, необходимых для [всех облачных сервисов AWS](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Мониторинг всех облачных сервисов AWS с помощью Dynatrace и просмотр доступных метрик.\"), а также список необязательных разрешений, специфичных для каждого сервиса.",
    "Permissions required for AWS monitoring integration:": "Разрешения, необходимые для интеграции мониторинга AWS:",
    "* `\"cloudwatch:GetMetricData\"`": "* `\"cloudwatch:GetMetricData\"`",
    "* `\"cloudwatch:GetMetricStatistics\"`": "* `\"cloudwatch:GetMetricStatistics\"`",
    "* `\"cloudwatch:ListMetrics\"`": "* `\"cloudwatch:ListMetrics\"`",
    "* `\"sts:GetCallerIdentity\"`": "* `\"sts:GetCallerIdentity\"`",
    "* `\"tag:GetResources\"`": "* `\"tag:GetResources\"`",
    "* `\"tag:GetTagKeys\"`": "* `\"tag:GetTagKeys\"`",
    "* `\"ec2:DescribeAvailabilityZones\"`": "* `\"ec2:DescribeAvailabilityZones\"`",
    "### Complete list of permissions for cloud services": "### Полный список разрешений для облачных сервисов",
    "| Name | Permissions |": "| Название | Разрешения |",
    "| All monitored Amazon services Required | `cloudwatch:GetMetricData`, `cloudwatch:GetMetricStatistics`, `cloudwatch:ListMetrics`, `sts:GetCallerIdentity`, `tag:GetResources`, `tag:GetTagKeys`, `ec2:DescribeAvailabilityZones` |": "| Все отслеживаемые сервисы Amazon (обязательно) | `cloudwatch:GetMetricData`, `cloudwatch:GetMetricStatistics`, `cloudwatch:ListMetrics`, `sts:GetCallerIdentity`, `tag:GetResources`, `tag:GetTagKeys`, `ec2:DescribeAvailabilityZones` |",
    "| AWS Certificate Manager Private Certificate Authority | `acm-pca:ListCertificateAuthorities` |": "| AWS Certificate Manager Private Certificate Authority | `acm-pca:ListCertificateAuthorities` |",
    "| Amazon MQ |  |": "| Amazon MQ |  |",
    "| Amazon API Gateway | `apigateway:GET` |": "| Amazon API Gateway | `apigateway:GET` |",
    "| AWS App Runner | `apprunner:ListServices` |": "| AWS App Runner | `apprunner:ListServices` |",
    "| Amazon AppStream | `appstream:DescribeFleets` |": "| Amazon AppStream | `appstream:DescribeFleets` |",
    "| AWS AppSync | `appsync:ListGraphqlApis` |": "| AWS AppSync | `appsync:ListGraphqlApis` |",
    "| Amazon Athena | `athena:ListWorkGroups` |": "| Amazon Athena | `athena:ListWorkGroups` |",
    "| Amazon Aurora | `rds:DescribeDBClusters` |": "| Amazon Aurora | `rds:DescribeDBClusters` |",
    "| Amazon EC2 Auto Scaling | `autoscaling:DescribeAutoScalingGroups` |": "| Amazon EC2 Auto Scaling | `autoscaling:DescribeAutoScalingGroups` |",
    "| Amazon EC2 Auto Scaling (built-in) | `autoscaling:DescribeAutoScalingGroups` |": "| Amazon EC2 Auto Scaling (built-in) | `autoscaling:DescribeAutoScalingGroups` |",
    "| AWS Billing |  |": "| AWS Billing |  |",
    "| Amazon Keyspaces |  |": "| Amazon Keyspaces |  |",
    "| AWS Chatbot |  |": "| AWS Chatbot |  |",
    "| Amazon CloudFront | `cloudfront:ListDistributions` |": "| Amazon CloudFront | `cloudfront:ListDistributions` |",
    "| AWS CloudHSM | `cloudhsm:DescribeClusters` |": "| AWS CloudHSM | `cloudhsm:DescribeClusters` |",
    "| Amazon CloudSearch | `cloudsearch:DescribeDomains` |": "| Amazon CloudSearch | `cloudsearch:DescribeDomains` |",
    "| AWS CodeBuild | `codebuild:ListProjects` |": "| AWS CodeBuild | `codebuild:ListProjects` |",
    "| Amazon Cognito |  |": "| Amazon Cognito |  |",
    "| Amazon Connect |  |": "| Amazon Connect |  |",
    "| Amazon Elastic Kubernetes Service (EKS) | `eks:ListClusters` |": "| Amazon Elastic Kubernetes Service (EKS) | `eks:ListClusters` |",
    "| AWS DataSync | `datasync:ListTasks` |": "| AWS DataSync | `datasync:ListTasks` |",
    "| Amazon DynamoDB Accelerator (DAX) | `dax:DescribeClusters` |": "| Amazon DynamoDB Accelerator (DAX) | `dax:DescribeClusters` |",
    "| AWS Database Migration Service (AWS DMS) | `dms:DescribeReplicationInstances` |": "| AWS Database Migration Service (AWS DMS) | `dms:DescribeReplicationInstances` |",
    "| Amazon DocumentDB | `rds:DescribeDBClusters` |": "| Amazon DocumentDB | `rds:DescribeDBClusters` |",
    "| AWS Direct Connect | `directconnect:DescribeConnections` |": "| AWS Direct Connect | `directconnect:DescribeConnections` |",
    "| Amazon DynamoDB | `dynamodb:ListTables` |": "| Amazon DynamoDB | `dynamodb:ListTables` |",
    "| Amazon DynamoDB (built-in) | `dynamodb:ListTables`, `dynamodb:ListTagsOfResource` |": "| Amazon DynamoDB (built-in) | `dynamodb:ListTables`, `dynamodb:ListTagsOfResource` |",
    "| Amazon EBS | `ec2:DescribeVolumes` |": "| Amazon EBS | `ec2:DescribeVolumes` |",
    "| Amazon EBS (built-in) | `ec2:DescribeVolumes` |": "| Amazon EBS (built-in) | `ec2:DescribeVolumes` |",
    "| Amazon EC2 API |  |": "| Amazon EC2 API |  |",
    "| Amazon EC2 (built-in) | `ec2:DescribeInstances` |": "| Amazon EC2 (built-in) | `ec2:DescribeInstances` |",
    "| Amazon EC2 Spot Fleet | `ec2:DescribeSpotFleetRequests` |": "| Amazon EC2 Spot Fleet | `ec2:DescribeSpotFleetRequests` |",
    "| Amazon Elastic Container Service (ECS) | `ecs:ListClusters` |": "| Amazon Elastic Container Service (ECS) | `ecs:ListClusters` |",
    "| Amazon ECS Container Insights | `ecs:ListClusters` |": "| Amazon ECS Container Insights | `ecs:ListClusters` |",
    "| Amazon ElastiCache (EC) | `elasticache:DescribeCacheClusters` |": "| Amazon ElastiCache (EC) | `elasticache:DescribeCacheClusters` |",
    "| AWS Elastic Beanstalk | `elasticbeanstalk:DescribeEnvironments` |": "| AWS Elastic Beanstalk | `elasticbeanstalk:DescribeEnvironments` |",
    "| Amazon Elastic File System (EFS) | `elasticfilesystem:DescribeFileSystems` |": "| Amazon Elastic File System (EFS) | `elasticfilesystem:DescribeFileSystems` |",
    "| Amazon Elastic Inference |  |": "| Amazon Elastic Inference |  |",
    "| Amazon Elastic Map Reduce (EMR) | `elasticmapreduce:ListClusters` |": "| Amazon Elastic Map Reduce (EMR) | `elasticmapreduce:ListClusters` |",
    "| Amazon Elasticsearch Service (ES) | `es:ListDomainNames` |": "| Amazon Elasticsearch Service (ES) | `es:ListDomainNames` |",
    "| Amazon Elastic Transcoder | `elastictranscoder:ListPipelines` |": "| Amazon Elastic Transcoder | `elastictranscoder:ListPipelines` |",
    "| Amazon Elastic Load Balancer (ELB) (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |": "| Amazon Elastic Load Balancer (ELB) (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |",
    "| Amazon EventBridge | `events:ListEventBuses` |": "| Amazon EventBridge | `events:ListEventBuses` |",
    "| Amazon FSx | `fsx:DescribeFileSystems` |": "| Amazon FSx | `fsx:DescribeFileSystems` |",
    "| Amazon GameLift | `gamelift:ListFleets` |": "| Amazon GameLift | `gamelift:ListFleets` |",
    "| AWS Glue | `glue:GetJobs` |": "| AWS Glue | `glue:GetJobs` |",
    "| Amazon Inspector | `inspector:ListAssessmentTemplates` |": "| Amazon Inspector | `inspector:ListAssessmentTemplates` |",
    "| AWS Internet of Things (IoT) |  |": "| AWS Internet of Things (IoT) |  |",
    "| AWS IoT Analytics |  |": "| AWS IoT Analytics |  |",
    "| Amazon Managed Streaming for Kafka | `kafka:ListClusters` |": "| Amazon Managed Streaming for Kafka | `kafka:ListClusters` |",
    "| Amazon Kinesis Data Analytics | `kinesisanalytics:ListApplications` |": "| Amazon Kinesis Data Analytics | `kinesisanalytics:ListApplications` |",
    "| Amazon Data Firehose | `firehose:ListDeliveryStreams` |": "| Amazon Data Firehose | `firehose:ListDeliveryStreams` |",
    "| Amazon Kinesis Data Streams | `kinesis:ListStreams` |": "| Amazon Kinesis Data Streams | `kinesis:ListStreams` |",
    "| Amazon Kinesis Video Streams | `kinesisvideo:ListStreams` |": "| Amazon Kinesis Video Streams | `kinesisvideo:ListStreams` |",
    "| AWS Lambda | `lambda:ListFunctions` |": "| AWS Lambda | `lambda:ListFunctions` |",
    "| AWS Lambda (built-in) | `lambda:ListFunctions`, `lambda:ListTags` |": "| AWS Lambda (built-in) | `lambda:ListFunctions`, `lambda:ListTags` |",
    "| Amazon Lex | `lex:GetBots` |": "| Amazon Lex | `lex:GetBots` |",
    "| Amazon Application and Network Load Balancer (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |": "| Amazon Application and Network Load Balancer (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |",
    "| Amazon CloudWatch Logs | `logs:DescribeLogGroups` |": "| Amazon CloudWatch Logs | `logs:DescribeLogGroups` |",
    "| AWS Elemental MediaConnect | `mediaconnect:ListFlows` |": "| AWS Elemental MediaConnect | `mediaconnect:ListFlows` |",
    "| AWS Elemental MediaConvert | `mediaconvert:DescribeEndpoints` |": "| AWS Elemental MediaConvert | `mediaconvert:DescribeEndpoints` |",
    "| AWS Elemental MediaPackage Live | `mediapackage:ListChannels` |": "| AWS Elemental MediaPackage Live | `mediapackage:ListChannels` |",
    "| AWS Elemental MediaPackage Video on Demand | `mediapackage-vod:ListPackagingConfigurations` |": "| AWS Elemental MediaPackage Video on Demand | `mediapackage-vod:ListPackagingConfigurations` |",
    "| AWS Elemental MediaTailor | `mediatailor:ListPlaybackConfigurations` |": "| AWS Elemental MediaTailor | `mediatailor:ListPlaybackConfigurations` |",
    "| Amazon VPC NAT Gateways | `ec2:DescribeNatGateways` |": "| Amazon VPC NAT Gateways | `ec2:DescribeNatGateways` |",
    "| Amazon Neptune | `rds:DescribeDBClusters` |": "| Amazon Neptune | `rds:DescribeDBClusters` |",
    "| AWS OpsWorks | `opsworks:DescribeStacks` |": "| AWS OpsWorks | `opsworks:DescribeStacks` |",
    "| Amazon Polly |  |": "| Amazon Polly |  |",
    "| Amazon QLDB | `qldb:ListLedgers` |": "| Amazon QLDB | `qldb:ListLedgers` |",
    "| Amazon RDS | `rds:DescribeDBInstances` |": "| Amazon RDS | `rds:DescribeDBInstances` |",
    "| Amazon RDS (built-in) | `rds:DescribeDBInstances`, `rds:DescribeEvents`, `rds:ListTagsForResource` |": "| Amazon RDS (built-in) | `rds:DescribeDBInstances`, `rds:DescribeEvents`, `rds:ListTagsForResource` |",
    "| Amazon Redshift | `redshift:DescribeClusters` |": "| Amazon Redshift | `redshift:DescribeClusters` |",
    "| Amazon Rekognition |  |": "| Amazon Rekognition |  |",
    "| AWS RoboMaker | `robomaker:ListSimulationJobs` |": "| AWS RoboMaker | `robomaker:ListSimulationJobs` |",
    "| Amazon Route 53 | `route53:ListHostedZones` |": "| Amazon Route 53 | `route53:ListHostedZones` |",
    "| Amazon Route 53 Resolver | `route53resolver:ListResolverEndpoints` |": "| Amazon Route 53 Resolver | `route53resolver:ListResolverEndpoints` |",
    "| Amazon S3 | `s3:ListAllMyBuckets` |": "| Amazon S3 | `s3:ListAllMyBuckets` |",
    "| Amazon S3 (built-in) | `s3:ListAllMyBuckets` |": "| Amazon S3 (built-in) | `s3:ListAllMyBuckets` |",
    "| Amazon SageMaker Batch Transform Jobs |  |": "| Amazon SageMaker Batch Transform Jobs |  |",
    "| Amazon SageMaker Endpoint Instances | `sagemaker:ListEndpoints` |": "| Amazon SageMaker Endpoint Instances | `sagemaker:ListEndpoints` |",
    "| Amazon SageMaker Endpoints | `sagemaker:ListEndpoints` |": "| Amazon SageMaker Endpoints | `sagemaker:ListEndpoints` |",
    "| Amazon SageMaker Ground Truth |  |": "| Amazon SageMaker Ground Truth |  |",
    "| Amazon SageMaker Processing Jobs |  |": "| Amazon SageMaker Processing Jobs |  |",
    "| Amazon SageMaker Training Jobs |  |": "| Amazon SageMaker Training Jobs |  |",
    "| AWS Service Catalog |  |": "| AWS Service Catalog |  |",
    "| Amazon Simple Email Service (SES) |  |": "| Amazon Simple Email Service (SES) |  |",
    "| Amazon Simple Notification Service (SNS) | `sns:ListTopics` |": "| Amazon Simple Notification Service (SNS) | `sns:ListTopics` |",
    "| Amazon Simple Queue Service (SQS) | `sqs:ListQueues` |": "| Amazon Simple Queue Service (SQS) | `sqs:ListQueues` |",
    "| AWS Systems Manager - Run Command |  |": "| AWS Systems Manager - Run Command |  |",
    "| AWS Step Functions |  |": "| AWS Step Functions |  |",
    "| AWS Storage Gateway | `storagegateway:ListGateways` |": "| AWS Storage Gateway | `storagegateway:ListGateways` |",
    "| Amazon SWF | `swf:ListDomains` |": "| Amazon SWF | `swf:ListDomains` |",
    "| Amazon Textract |  |": "| Amazon Textract |  |",
    "| AWS IoT Things Graph |  |": "| AWS IoT Things Graph |  |",
    "| AWS Transfer Family | `transfer:ListServers` |": "| AWS Transfer Family | `transfer:ListServers` |",
    "| AWS Transit Gateway | `ec2:DescribeTransitGateways` |": "| AWS Transit Gateway | `ec2:DescribeTransitGateways` |",
    "| Amazon Translate |  |": "| Amazon Translate |  |",
    "| AWS Trusted Advisor |  |": "| AWS Trusted Advisor |  |",
    "| AWS API Usage |  |": "| AWS API Usage |  |",
    "| AWS Site-to-Site VPN | `ec2:DescribeVpnConnections` |": "| AWS Site-to-Site VPN | `ec2:DescribeVpnConnections` |",
    "| AWS WAF Classic |  |": "| AWS WAF Classic |  |",
    "| AWS WAF |  |": "| AWS WAF |  |",
    "| Amazon WorkMail | `workmail:ListOrganizations` |": "| Amazon WorkMail | `workmail:ListOrganizations` |",
    "| Amazon WorkSpaces | `workspaces:DescribeWorkspaces` |": "| Amazon WorkSpaces | `workspaces:DescribeWorkspaces` |",
    "To get the information required for comprehensive AWS cloud-computing monitoring, you have to authorize Dynatrace to access your Amazon metrics. Dynatrace will identify all the virtualized infrastructure components in your AWS environment and collect performance metrics related to those components.": "Для получения информации, необходимой для комплексного мониторинга облачных вычислений AWS, необходимо авторизовать доступ Dynatrace к вашим метрикам Amazon. Dynatrace идентифицирует все виртуализированные компоненты инфраструктуры в вашем окружении AWS и соберёт метрики производительности для этих компонентов.",
    "Next, select the deployment model that best describes your environment and follow the procedure for that model.": "Далее выберите модель развёртывания, наиболее подходящую для вашего окружения, и следуйте соответствующей процедуре.",
    "#### Deployment with existing ActiveGate": "#### Развёртывание с существующим ActiveGate",
    "You won't be able to monitor the AWS cloud services without an AWS-hosted Environment ActiveGate.": "Мониторинг облачных сервисов AWS невозможен без Environment ActiveGate, размещённого в AWS.",
    "The instructions below are applicable whether or not the account hosting your ActiveGate is the same as your monitored account. In a typical setup, you need to create two CloudFormation stacks using CloudFormation templates:": "Приведённые ниже инструкции применимы независимо от того, совпадает ли учётная запись, в которой размещён ваш ActiveGate, с отслеживаемой учётной записью. В типичной конфигурации требуется создать два стека CloudFormation с использованием шаблонов CloudFormation:",
    "* A CloudFormation stack from the account hosting your ActiveGate, containing the following resources:": "* Стек CloudFormation из учётной записи, в которой размещён ваш ActiveGate, содержащий следующие ресурсы:",
    "+ A [role for your Environment ActiveGate](#create-role-ag) hosted in your AWS infrastructure, on an Amazon EC2 host.": "+ [Роль для вашего Environment ActiveGate](#create-role-ag), размещённого в инфраструктуре AWS на хосте Amazon EC2.",
    "+ Its attached policy, defining the monitored account permissions.": "+ Прикреплённая политика, определяющая разрешения отслеживаемой учётной записи.",
    "* A CloudFormation stack from the monitored account, containing the following resources:": "* Стек CloudFormation из отслеживаемой учётной записи, содержащий следующие ресурсы:",
    "+ A dedicated [monitoring role](#create-role-dt) for Dynatrace in your AWS account.": "+ Выделенная [роль мониторинга](#create-role-dt) для Dynatrace в вашей учётной записи AWS.",
    "+ Its attached policy, defining the Dynatrace authentication permissions to your AWS environment.": "+ Прикреплённая политика, определяющая разрешения аутентификации Dynatrace для вашего окружения AWS.",
    "To monitor multiple accounts, use the `role_based_access_AG_account_multiple_monitoring_roles_template.yml` and repeat the [Create a role for ActiveGate on the account that hosts ActiveGate](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics#create-role-dt \"Integrate metrics from Amazon CloudWatch.\") steps to create a stack for each monitored account.": "Для мониторинга нескольких учётных записей используйте `role_based_access_AG_account_multiple_monitoring_roles_template.yml` и повторите шаги [Создание роли для ActiveGate в учётной записи, где размещён ActiveGate](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics#create-role-dt \"Интеграция метрик из Amazon CloudWatch.\") для создания стека для каждой отслеживаемой учётной записи.",
    "You will need:": "Вам понадобится:",
    "* An ActiveGate installed on an Amazon EC2 host. It must be able to assume a role within your AWS account that allows it to read the Dynatrace monitoring data.": "* ActiveGate, установленный на хосте Amazon EC2. Он должен иметь возможность принять роль в вашей учётной записи AWS, позволяющую ему читать данные мониторинга Dynatrace.",
    "* The ID of the AWS account that hosts the ActiveGate (the account that hosts your Dynatrace components, which in this case is the one hosting the Environment ActiveGate).": "* Идентификатор учётной записи AWS, в которой размещён ActiveGate (учётная запись, в которой размещены компоненты Dynatrace, в данном случае это учётная запись, в которой размещён Environment ActiveGate).",
    "* The Amazon Web Services monitored account ID (the account that you want to monitor).": "* Идентификатор отслеживаемой учётной записи Amazon Web Services (учётная запись, которую требуется мониторить).",
    "* The name of the role with which your Environment ActiveGate was started.": "* Имя роли, с которой был запущен ваш Environment ActiveGate.",
    "* The **External ID**, which you can get as follows.": "* **External ID**, который можно получить следующим образом.",
    "1. Go to **Settings** > **Cloud and virtualization** > **AWS**.": "1. Перейдите в **Settings** > **Cloud and virtualization** > **AWS**.",
    "2. Select **Connect new instance**.": "2. Выберите **Connect new instance**.",
    "3. Under **Authentication method**, select **Role-based authentication**.": "3. В разделе **Authentication method** выберите **Role-based authentication**.",
    "4. Under **Token**, select **Copy** to copy the token (the External ID) to your clipboard.": "4. В разделе **Token** выберите **Copy**, чтобы скопировать токен (External ID) в буфер обмена.",
    "Create a role for ActiveGate on the account that hosts ActiveGate": "Создание роли для ActiveGate в учётной записи, где размещён ActiveGate",
    "1. Download the [YAML file with CloudFormation template](https://dt-url.net/pv0306t).": "1. Скачайте [YAML-файл с шаблоном CloudFormation](https://dt-url.net/pv0306t).",
    "2. Create the stack in your Amazon Console:": "2. Создайте стек в Amazon Console:",
    "1. In your Amazon Console, go to CloudFormation.": "1. В Amazon Console перейдите в CloudFormation.",
    "2. Go to **Stacks** and create a new stack with new resources.": "2. Перейдите в **Stacks** и создайте новый стек с новыми ресурсами.",
    "3. Select **Template is ready**, upload the template you created above, and then select **Next**.": "3. Выберите **Template is ready**, загрузите созданный выше шаблон и нажмите **Next**.",
    "4. In **Parameters**, for **Monitored Account ID**, enter the ID of the account Dynatrace will monitor. Optionally, adapt other parameters as needed.": "4. В разделе **Parameters** для **Monitored Account ID** введите идентификатор учётной записи, которую будет отслеживать Dynatrace. При необходимости скорректируйте другие параметры.",
    "5. Enter a name for your stack, and then select **Next** twice.": "5. Введите имя стека и дважды нажмите **Next**.",
    "6. Review your configuration, select **I acknowledge that AWS CloudFormation might create IAM resources with custom names**, and select **Submit**.": "6. Проверьте конфигурацию, установите флажок **I acknowledge that AWS CloudFormation might create IAM resources with custom names** и нажмите **Submit**.",
    "You can also create a stack via CLI using the command below:": "Также можно создать стек через CLI с помощью команды ниже:",
    "3. Go to the Amazon EC2 console, right-click an instance hosting your Environment ActiveGate, and select **Security** > **Modify IAM role**.": "3. Перейдите в консоль Amazon EC2, щёлкните правой кнопкой мыши по экземпляру, где размещён ваш Environment ActiveGate, и выберите **Security** > **Modify IAM role**.",
    "4. Select the role you created and select **Update IAM role**.": "4. Выберите созданную роль и нажмите **Update IAM role**.",
    "Create a monitoring role for Dynatrace on your monitored account": "Создание роли мониторинга для Dynatrace в отслеживаемой учётной записи",
    "After the `Dynatrace_ActiveGate_role` is created on the account hosting the ActiveGate, create a role for the account to be monitored.": "После создания `Dynatrace_ActiveGate_role` в учётной записи, где размещён ActiveGate, создайте роль для отслеживаемой учётной записи.",
    "1. Download a YAML file with CloudFormation template from [github role\\_based\\_access\\_AG\\_account\\_template.yml](https://dt-url.net/f30301j).": "1. Скачайте YAML-файл с шаблоном CloudFormation из [github role\\_based\\_access\\_AG\\_account\\_template.yml](https://dt-url.net/f30301j).",
    "2. Create the stack in your Amazon Console:": "2. Создайте стек в Amazon Console:",
    "3. Select **Template is ready**, upload the template you created above, and select **Next**.": "3. Выберите **Template is ready**, загрузите созданный выше шаблон и нажмите **Next**.",
    "4. In **Parameters**, enter **External ID**, **ActiveGateRoleName** and **ActiveGateAccountID** from the stack you created. Optionally, adapt other parameters if needed.": "4. В разделе **Parameters** введите **External ID**, **ActiveGateRoleName** и **ActiveGateAccountID** из созданного стека. При необходимости скорректируйте другие параметры.",
    "6. Review your configuration, enable **I acknowledge that AWS CloudFormation might create IAM resources with custom names**, and select **Submit**.": "6. Проверьте конфигурацию, включите **I acknowledge that AWS CloudFormation might create IAM resources with custom names** и нажмите **Submit**.",
    "Modify ActiveGate configuration": "Изменение конфигурации ActiveGate",
    "Starting with ActiveGate version 1.217, AWS monitoring is enabled by default. For configuration details, see Customize ActiveGate properties. The following configuration settings refer to earlier ActiveGate versions.": "Начиная с ActiveGate версии 1.217 мониторинг AWS включён по умолчанию. Сведения о конфигурации см. в разделе «Настройка свойств ActiveGate». Следующие параметры конфигурации относятся к более ранним версиям ActiveGate.",
    "1. Edit the `custom.properties` file of your Environment ActiveGate.": "1. Отредактируйте файл `custom.properties` вашего Environment ActiveGate.",
    "2. Make the following property settings:": "2. Задайте следующие параметры:",
    "If the ActiveGate is dedicated to AWS monitoring, you also need to set the MSGrouter property as follows:": "Если ActiveGate предназначен исключительно для мониторинга AWS, необходимо также установить свойство MSGrouter следующим образом:",
    "3. Save the file and restart the ActiveGate main service.": "3. Сохраните файл и перезапустите основной сервис ActiveGate.",
    "Key-based authentication (AWS GovCloud and AWS China only)": "Аутентификация на основе ключей (только для AWS GovCloud и AWS China)",
    "Only for AWS GovCloud and China partitions is key-based authentication allowed.": "Аутентификация на основе ключей разрешена только для разделов AWS GovCloud и China.",
    "In this scenario you have to create an AWS monitoring policy and generate a key pair with that policy.": "В этом сценарии необходимо создать политику мониторинга AWS и сгенерировать пару ключей с этой политикой.",
    "AWS Identity and Access Management (IAM) permission boundaries may deny AWS actions required by Dynatrace. If you use IAM permission boundary on your AWS account, make sure that actions from policy are allowed in all AWS Regions within permission boundary.": "Границы разрешений AWS Identity and Access Management (IAM) могут запрещать действия AWS, необходимые Dynatrace. Если в вашей учётной записи AWS используется граница разрешений IAM, убедитесь, что действия из политики разрешены во всех регионах AWS в пределах этой границы.",
    "To create the AWS monitoring policy": "Создание политики мониторинга AWS",
    "1. In your Amazon Console, go to **Identity and Access Management**.": "1. В Amazon Console перейдите в **Identity and Access Management**.",
    "2. Go to **Policies** and select **Create policy**.": "2. Перейдите в **Policies** и нажмите **Create policy**.",
    "3. Select the JSON tab and paste the predefined policy from the box below.": "3. Выберите вкладку JSON и вставьте предопределённую политику из блока ниже.",
    "4. Give the policy a name.": "4. Задайте имя политики.",
    "5. Select **Create policy**.": "5. Нажмите **Create policy**.",
    "You'll need to generate an **Access key** and a **Secret access key** that Dynatrace can use to get metrics from Amazon Web Services.": "Необходимо сгенерировать **Access key** и **Secret access key**, которые Dynatrace будет использовать для получения метрик из Amazon Web Services.",
    "6. In your Amazon Console, go to **Users** and select **Add Users**.": "6. В Amazon Console перейдите в **Users** и нажмите **Add Users**.",
    "7. Enter the **User name**.": "7. Введите **User name**.",
    "8. In the next screen, choose **Attach policies directly** and attach the policy that you created before.": "8. На следующем экране выберите **Attach policies directly** и прикрепите созданную ранее политику.",
    "9. Review the user details and select **Create user**.": "9. Проверьте сведения о пользователе и нажмите **Create user**.",
    "10. From the list of users, select your newly created user name and go to **Security credentials**, then select **Create access key**.": "10. В списке пользователей выберите только что созданного пользователя и перейдите в **Security credentials**, затем нажмите **Create access key**.",
    "11. On **Access key best practices & alternatives**, select **Third-party service**, then select **Next**.": "11. В разделе **Access key best practices & alternatives** выберите **Third-party service**, затем нажмите **Next**.",
    "12. On **Retrieve access keys**, store the **Access Key ID** name (AKID) and **Secret access key** values.": "12. В разделе **Retrieve access keys** сохраните значения **Access Key ID** (AKID) и **Secret access key**.",
    "13. You can either download the user credentials or copy the credentials displayed online (select **Show**).": "13. Можно скачать учётные данные пользователя или скопировать их, отображаемые онлайн (нажмите **Show**).",
    "Alternative: create AWS roles with Terraform": "Альтернатива: создание ролей AWS с помощью Terraform",
    "Terraform templates are an alternative way of creating and configuring AWS roles. For detailed instructions on how to create AWS roles with Terraform, see [Configuring AWS role-based access with Terraform](https://github.com/dynatrace-oss/cloud-snippets/tree/main/aws/role-based-access/terraform-templates)": "Шаблоны Terraform, это альтернативный способ создания и настройки ролей AWS. Подробные инструкции по созданию ролей AWS с помощью Terraform см. в [Настройке доступа на основе ролей AWS с помощью Terraform](https://github.com/dynatrace-oss/cloud-snippets/tree/main/aws/role-based-access/terraform-templates)",
    "## Create monitoring configuration": "## Создание конфигурации мониторинга",
    "You can create, activate, and manage multiple monitoring connections. Each connection is defined by the credentials and/or access tokens required for Dynatrace to be able to pull in the data.": "Можно создавать, активировать и управлять несколькими подключениями мониторинга. Каждое подключение определяется учётными данными и/или токенами доступа, необходимыми Dynatrace для получения данных.",
    "Why configuration is performed per connection": "Почему конфигурация выполняется для каждого подключения",
    "Allowing for multiple connections and configurations makes it possible to monitor even extremely complex environments. With such an approach, you don't need to configure everything at once. Instead, you can gradually add monitoring configurations to your existing setup. Such an architecture also makes it easy to react to the dynamic changes of the monitored environment, without needing to reconfigure the unaffected elements.": "Поддержка нескольких подключений и конфигураций позволяет отслеживать даже сложные окружения. При таком подходе не нужно настраивать всё сразу: можно постепенно добавлять конфигурации мониторинга к существующей настройке. Такая архитектура также упрощает реагирование на динамические изменения отслеживаемого окружения без необходимости перенастройки незатронутых элементов.",
    "1. Add a new AWS connection": "1. Добавление нового подключения AWS",
    "If you've followed all the prior steps, you're ready to configure Amazon Web Services monitoring.": "Если вы выполнили все предыдущие шаги, можно переходить к настройке мониторинга Amazon Web Services.",
    "To add a new AWS connection": "Добавление нового подключения AWS",
    "1. Go to **Settings** > **Cloud and virtualization** > **AWS**. The page lists AWS connections already configured.": "1. Перейдите в **Settings** > **Cloud and virtualization** > **AWS**. На странице перечислены уже настроенные подключения AWS.",
    "If you haven't provided an ActiveGate required for AWS monitoring (check [Prerequisites](#capable-activegate) for details), the respective information will be provided on the screen and you will not be able to continue with the configuration process.": "Если вы не предоставили ActiveGate, необходимый для мониторинга AWS (см. [Предварительные требования](#capable-activegate)), соответствующее сообщение отобразится на экране и продолжить настройку будет невозможно.",
    "1. Modifying or removing existing connections": "1. Изменение или удаление существующих подключений",
    "You can go back to changing the already configured connections at any later point in time.": "Изменять уже настроенные подключения можно в любой момент.",
    "1. Go to **Settings** > **Cloud and virtualization** > **AWS**. The page lists existing connections.": "1. Перейдите в **Settings** > **Cloud and virtualization** > **AWS**. На странице перечислены существующие подключения.",
    "2. Edit connections as needed.": "2. Отредактируйте подключения по необходимости.",
    "* To edit an existing connection or the monitored services within, select **Edit** ![Edit](https://dt-cdn.net/images/edit-icon-a083c62c49.svg \"Edit\") in that row.": "* Чтобы изменить существующее подключение или отслеживаемые в нём сервисы, нажмите **Edit** ![Edit](https://dt-cdn.net/images/edit-icon-a083c62c49.svg \"Изменить\") в соответствующей строке.",
    "* To delete an existing connection, select **Delete** ![Remove](https://dt-cdn.net/images/remove-icon-105c6a04c2.svg \"Remove\") in that row.": "* Чтобы удалить существующее подключение, нажмите **Delete** ![Remove](https://dt-cdn.net/images/remove-icon-105c6a04c2.svg \"Удалить\") в соответствующей строке.",
    "2. Select **Connect new instance** and complete the following fields.": "2. Выберите **Connect new instance** и заполните следующие поля.",
    "* **Enabled** toggle—make sure it's selected if you want to monitor this configuration.": "* Переключатель **Enabled**: убедитесь, что он включён, если требуется отслеживать эту конфигурацию.",
    "* **Connection name**—enter a descriptive name for the connection.": "* **Connection name**: введите описательное имя подключения.",
    "* **Authentication method**—select `Role-based authentication`.": "* **Authentication method**: выберите `Role-based authentication`.",
    "* **IAM role…**—enter the name of the role you created in Amazon for Dynatrace (either `Dynatrace_monitoring_role` or a customized role name, if you created one). Remember to always use the role that contains [all required permissions](#aws-policy-and-authentication).": "* **IAM role...**: введите имя роли, созданной в Amazon для Dynatrace (`Dynatrace_monitoring_role` или пользовательское имя роли, если оно было задано). Используйте роль, содержащую [все необходимые разрешения](#aws-policy-and-authentication).",
    "* **Your Amazon account ID**—enter your Amazon account ID (the account you want Dynatrace to pull metrics from).": "* **Your Amazon account ID**: введите идентификатор учётной записи Amazon (учётная запись, из которой Dynatrace будет получать метрики).",
    "3. Select **Connect** to verify and save the connection.": "3. Нажмите **Connect** для проверки и сохранения подключения.",
    "Selecting a different AWS partition": "Выбор другого раздела AWS",
    "If your AWS account is on a different partition than the default AWS partition, you can use the **AWS partition** list to select your partition.": "Если ваша учётная запись AWS находится в другом разделе, отличном от раздела AWS по умолчанию, используйте список **AWS partition** для выбора раздела.",
    "Limiting data capture": "Ограничение сбора данных",
    "You can limit the data acquired from the CloudWatch by defining a tag-based filter of specific resources. See [Limit API calls to AWS using tags](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/limit-api-calls-to-aws-using-tags#configure-dynatrace-to-use-aws-tags \"Add and configure AWS tags to limit AWS resources.\") for more details on tag-based filtering.": "Можно ограничить данные, получаемые из CloudWatch, задав фильтр на основе тегов для определённых ресурсов. Подробнее о фильтрации на основе тегов см. в разделе [Ограничение вызовов API к AWS с помощью тегов](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/limit-api-calls-to-aws-using-tags#configure-dynatrace-to-use-aws-tags \"Добавление и настройка тегов AWS для ограничения ресурсов AWS.\").",
    "2. AWS cloud services monitored by default": "2. Облачные сервисы AWS, отслеживаемые по умолчанию",
    "After Dynatrace connects to your AWS environment, it immediately starts monitoring [selected AWS services](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services#aws-default \"Monitor all AWS cloud services with Dynatrace and view available metrics.\"). [Classic (formerly 'built-in') AWS metrics](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/default-aws-metrics \"The list of classic (formerly 'built-in') metrics Dynatrace collects by default for AWS monitoring.\") lists the metrics of AWS cloud services monitored by default.": "После подключения Dynatrace к окружению AWS начинается немедленный мониторинг [выбранных сервисов AWS](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services#aws-default \"Мониторинг всех облачных сервисов AWS с помощью Dynatrace и просмотр доступных метрик.\"). Список метрик облачных сервисов AWS, отслеживаемых по умолчанию, см. в разделе [Классические (ранее «встроенные») метрики AWS](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/default-aws-metrics \"Список классических (ранее «встроенных») метрик, которые Dynatrace собирает по умолчанию для мониторинга AWS.\").",
    "3. Monitor other AWS services": "3. Мониторинг других сервисов AWS",
    "In addition to AWS services, it's also possible to monitor all other AWS cloud services. AWS cloud services are enabled for monitoring per AWS connection.": "Помимо сервисов AWS, можно также отслеживать все остальные облачные сервисы AWS. Облачные сервисы AWS включаются для мониторинга для каждого подключения AWS.",
    "To add a service to monitoring:": "Добавление сервиса в мониторинг:",
    "1. Go to **Settings** > **Cloud and virtualization** > **AWS**.": "1. Перейдите в **Settings** > **Cloud and virtualization** > **AWS**.",
    "2. On the AWS overview page, find the connection that you want to change and select **Edit** ![Edit](https://dt-cdn.net/images/edit-icon-a083c62c49.svg \"Edit\") in that row.": "2. На странице обзора AWS найдите подключение, которое требуется изменить, и нажмите **Edit** ![Edit](https://dt-cdn.net/images/edit-icon-a083c62c49.svg \"Изменить\") в соответствующей строке.",
    "3. Under **Services**, select **Manage services**.": "3. В разделе **Services** выберите **Manage services**.",
    "3. Go to **Services** and select **Manage services**.": "3. Перейдите в **Services** и выберите **Manage services**.",
    "4. Select **Add service**.": "4. Нажмите **Add service**.",
    "5. Select the service from the list and then select **Add service**.": "5. Выберите сервис из списка и нажмите **Add service**.",
    "6. Select **Save changes** to save your configuration.": "6. Нажмите **Save changes** для сохранения конфигурации.",
    "You can add multiple cloud services by repeating the steps above.": "Можно добавить несколько облачных сервисов, повторив указанные шаги.",
    "Configuration of collected metrics per service": "Настройка собираемых метрик для каждого сервиса",
    "After you add a service, Dynatrace automatically starts collecting a set of metrics for this particular service.": "После добавления сервиса Dynatrace автоматически начинает собирать набор метрик для этого сервиса.",
    "Recommended metrics:": "Рекомендуемые метрики:",
    "* Enabled by default": "* Включены по умолчанию",
    "* Can not be disabled": "* Нельзя отключить",
    "* Can come with recommended dimensions (enabled by default, can't be disabled)": "* Могут иметь рекомендуемые измерения (включены по умолчанию, нельзя отключить)",
    "* Can come with optional dimensions (disabled by default, can be enabled)": "* Могут иметь необязательные измерения (отключены по умолчанию, можно включить)",
    "Apart from the recommended metrics, most services have the possibility of enabling optional metrics that can be added and configured manually.": "Помимо рекомендуемых метрик, большинство сервисов поддерживают возможность включения необязательных метрик, которые можно добавлять и настраивать вручную.",
    "List of AWS cloud services and collected metrics": "Список облачных сервисов AWS и собираемых метрик",
    "To see the complete list of AWS cloud services and learn about the metrics collected for each of them, see [All AWS cloud services](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Monitor all AWS cloud services with Dynatrace and view available metrics.\").": "Полный список облачных сервисов AWS и сведения о метриках, собираемых для каждого из них, см. в разделе [Все облачные сервисы AWS](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Мониторинг всех облачных сервисов AWS с помощью Dynatrace и просмотр доступных метрик.\").",
    "Alternatively, you can check the list of supported AWS Services within in-product Dynatrace Hub (search for **AWS**) or in the [web version of Dynatrace Hub](https://www.dynatrace.com/hub/?query=aws).": "Также можно ознакомиться со списком поддерживаемых сервисов AWS в Dynatrace Hub внутри продукта (выполните поиск по **AWS**) или в [веб-версии Dynatrace Hub](https://www.dynatrace.com/hub/?query=aws).",
    "To add and configure metrics": "Добавление и настройка метрик",
    "2. On the AWS overview page, find the connection that you want to change and select the edit icon next to its name.": "2. На странице обзора AWS найдите подключение, которое требуется изменить, и нажмите значок редактирования рядом с его именем.",
    "4. To add a metric select the service for which you want to add metrics and select **Add new metric**.": "4. Чтобы добавить метрику, выберите сервис, для которого нужно добавить метрики, и нажмите **Add new metric**.",
    "5. From the menu select **Add metric** for the metric you want to monitor.": "5. В меню выберите **Add metric** для метрики, которую требуется отслеживать.",
    "6. Select **Edit** to configure the metric.": "6. Нажмите **Edit** для настройки метрики.",
    "7. Select **Apply** to save your configuration.": "7. Нажмите **Apply** для сохранения конфигурации.",
    "After you select the cloud services and save your changes, monitoring of the newly added services starts automatically.": "После выбора облачных сервисов и сохранения изменений мониторинг новых сервисов запускается автоматически.",
    "## What's next?": "## Что дальше?",
    "Within minutes, you'll see the data on your dashboards.": "В течение нескольких минут данные появятся на ваших панелях мониторинга.",
    "To see the core measurements per each of the AWS connections": "Просмотр основных измерений для каждого из подключений AWS",
    "1. Go to **AWS**.": "1. Перейдите в **AWS**.",
    "2. Select the connection for which you want to see an overview of the AWS infrastructure.": "2. Выберите подключение, для которого требуется просмотреть обзор инфраструктуры AWS.",
    "You can also build your own dashboard from the metrics collected for your AWS instances. For details on building dashboards, see [Dashboards](/managed/analyze-explore-automate/dashboards-classic \"Learn how to create, manage, and use Dynatrace Dashboards Classic.\").": "Также можно создать собственную панель мониторинга из метрик, собранных для ваших экземпляров AWS. Подробнее о создании панелей мониторинга см. в разделе [Панели мониторинга](/managed/analyze-explore-automate/dashboards-classic \"Создание, управление и использование классических панелей мониторинга Dynatrace.\").",
    "Virtual Machines, containers, and deep code monitoring with Dynatrace OneAgent": "Виртуальные машины, контейнеры и глубокий мониторинг кода с помощью Dynatrace OneAgent",
    "Dynatrace OneAgent offers unparalleled depth of insight into hosts, containers, and code. To learn more, see [Set up Dynatrace on Amazon Web Services](/managed/ingest-from/amazon-web-services \"Set up and configure monitoring for Amazon Web Services.\").": "Dynatrace OneAgent обеспечивает непревзойдённую глубину анализа хостов, контейнеров и кода. Подробнее см. в разделе [Настройка Dynatrace для Amazon Web Services](/managed/ingest-from/amazon-web-services \"Настройка и конфигурация мониторинга для Amazon Web Services.\").",
    "Further configuration for notifications and alerts": "Дальнейшая настройка уведомлений и оповещений",
    "After you set up AWS monitoring, you can:": "После настройки мониторинга AWS можно:",
    "* [Set up metric events for alerting](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/aws-set-up-metric-events-for-alerting \"Set up and configure metric events for alerting.\"). This enables you to create, enable, disable and configure recommended alerting rules.": "* [Настроить события метрик для оповещения](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/aws-set-up-metric-events-for-alerting \"Настройка и конфигурация событий метрик для оповещения.\"). Это позволяет создавать, включать, отключать и настраивать рекомендуемые правила оповещений.",
    "* [Limit API calls to AWS using tags](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/limit-api-calls-to-aws-using-tags \"Add and configure AWS tags to limit AWS resources.\"). By default, Dynatrace monitors all Amazon Web Services that have been specified in your permission policy. Optionally, you can use tagging to limit the AWS resources that are monitored by Dynatrace.": "* [Ограничить вызовы API к AWS с помощью тегов](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/limit-api-calls-to-aws-using-tags \"Добавление и настройка тегов AWS для ограничения ресурсов AWS.\"). По умолчанию Dynatrace отслеживает все Amazon Web Services, указанные в вашей политике разрешений. При необходимости можно использовать теги для ограничения ресурсов AWS, отслеживаемых Dynatrace.",
    "Integrate CloudWatch Metric Streams": "Интеграция CloudWatch Metric Streams",
    "This method of monitoring does not require an ActiveGate. Dynatrace integration with Amazon CloudWatch Metric Streams provides a simple and safe way to ingest AWS metrics. Amazon CloudWatch Metric Streams allows all metrics issued in a given AWS region to be streamed through Kinesis Firehose to the Dynatrace API. For details, see [Amazon CloudWatch Metric Streams](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-metrics-ingest/cloudwatch-metric-streams \"Ingest metrics from your AWS accounts using Amazon CloudWatch Metric Streams.\").": "Этот метод мониторинга не требует ActiveGate. Интеграция Dynatrace с Amazon CloudWatch Metric Streams обеспечивает простой и безопасный способ приёма метрик AWS. Amazon CloudWatch Metric Streams позволяет передавать все метрики в заданном регионе AWS через Kinesis Firehose в Dynatrace API. Подробнее см. в разделе [Amazon CloudWatch Metric Streams](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-metrics-ingest/cloudwatch-metric-streams \"Приём метрик из учётных записей AWS с помощью Amazon CloudWatch Metric Streams.\").",
    "OpenTelemetry and distributed tracing": "OpenTelemetry и распределённая трассировка",
    "It is also possible to [trace AWS Lambda .NET Core functions with OpenTelemetry .NET](/managed/ingest-from/amazon-web-services/integrate-into-aws/aws-lambda-integration/aws-lambda-classic/aws-lambda-otel-integration/lambda-otel-native \"Learn how to use OpenTelemetry to trace AWS Lambda .NET Core functions.\").": "Также можно [трассировать функции AWS Lambda .NET Core с помощью OpenTelemetry .NET](/managed/ingest-from/amazon-web-services/integrate-into-aws/aws-lambda-integration/aws-lambda-classic/aws-lambda-otel-integration/lambda-otel-native \"Использование OpenTelemetry для трассировки функций AWS Lambda .NET Core.\").",
}

PASS = set()

build_one(REL, "cloudwatch-metrics.md", TRANS, PASS)
qa_one(REL, "cloudwatch-metrics.md")
