# -*- coding: utf-8 -*-
"""Builder for install-zos-java.md (L4-IF.71 canon)."""

import sys, os

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation"
FN = "install-zos-java.md"

# TRANS keys: clean English (no mojibake). Engine (_demoji) handles scraper artefacts.
# Lines inside code-fences, empty lines, ---, source:, scraped: are auto-skipped.

TRANS = {
    # --- frontmatter ---
    "title: Install the z/OS Java module": "title: Установка модуля z/OS Java",
    # --- h1 (appears twice) ---
    "# Install the z/OS Java module": "# Установка модуля z/OS Java",
    # --- metadata ---
    "* 15-min read": "* Чтение: 15 мин",
    "* Updated on Nov 18, 2025": "* Обновлено 18 ноября 2025 г.",
    # --- intro prose ---
    "With the z/OS Java module, you can get observability for your Java applications including IBM MQ and database calls.": "Модуль z/OS Java позволяет получить наблюдаемость для Java-приложений, включая IBM MQ и вызовы к базам данных.",
    # --- intro table ---
    "| Observability for | Including |": "| Наблюдаемость для | Включает |",
    "| --- | --- |": "| --- | --- |",
    "| WebSphere Application Server  WebSphere Liberty | * Incoming web requests on WebSphere Application Server and Liberty * Outgoing web requests from WebSphere Application Server and Liberty via the Apache HttpClient * Outgoing CICS Transaction Gateway requests from WebSphere Application Server and Liberty via the CTG client * Websphere Application Server Websphere Liberty specific metrics (PMI and JMX) * JVM specific managed memory metrics (JMX) |": "| WebSphere Application Server  WebSphere Liberty | * Входящие веб-запросы в WebSphere Application Server и Liberty * Исходящие веб-запросы из WebSphere Application Server и Liberty через Apache HttpClient * Исходящие запросы CICS Transaction Gateway из WebSphere Application Server и Liberty через CTG-клиент * Метрики, специфичные для WebSphere Application Server и WebSphere Liberty (PMI и JMX) * Управляемые метрики памяти JVM (JMX) |",
    "| z/OS Connect | * Incoming web requests on z/OS Connect * Outgoing requests from z/OS Connect via the CICS, IMS, and IBM MQ service providers * z/OS Connect specific metrics (JMX) * JVM specific managed memory metrics (JMX) |": "| z/OS Connect | * Входящие веб-запросы в z/OS Connect * Исходящие запросы из z/OS Connect через поставщиков услуг CICS, IMS и IBM MQ * Метрики, специфичные для z/OS Connect (JMX) * Управляемые метрики памяти JVM (JMX) |",
    "| CICS/IMS transactions | Transactions initiated using  * IBM MQ and JMS * CICS SOAP and CICS Transaction Gateway * IMS SOAP Gateway |": "| Транзакции CICS/IMS | Транзакции, инициированные через * IBM MQ и JMS * CICS SOAP и CICS Transaction Gateway * IMS SOAP Gateway |",
    "| Database calls | Database calls with their SQL statements from Java applications to Db2 via JDBC |": "| Вызовы к базам данных | Вызовы к Db2 с SQL-операторами из Java-приложений через JDBC |",
    # --- intro paragraphs ---
    "Trace your Java applications end-to-end with Dynatrace and quickly detect any anomalies": "Отслеживайте Java-приложения сквозь всю цепочку вызовов с помощью Dynatrace и быстро обнаруживайте аномалии",
    'Analyze the performance of your transactions end-to-end using the [service flow](/managed/observe/application-observability/services-classic/service-backtrace "Trace the sequence of service calls all the way back up to the browser click that triggered the sequence of calls.").': 'Анализируйте производительность транзакций сквозь всю цепочку с помощью [потока служб](/managed/observe/application-observability/services-classic/service-backtrace "Отслеживайте последовательность вызовов служб вплоть до щелчка в браузере, который её инициировал.").',
    "![zOS Java 1](https://dt-cdn.net/images/zos-java-1-2772-facc3b2740.png)": "![zOS Java 1](https://dt-cdn.net/images/zos-java-1-2772-facc3b2740.png)",
    "zOS Java 1": "zOS Java 1",
    'Use the [PurePath distributed traces](/managed/observe/application-observability/distributed-traces "Gain observability into highly distributed, cloud-native architectures to effectively trace and analyze transactions in real time.") to drill down to the code level and to optimize your programs.': 'Используйте [распределённые трассировки PurePath](/managed/observe/application-observability/distributed-traces "Получите наблюдаемость в высокораспределённых, облачно-ориентированных архитектурах для эффективной трассировки и анализа транзакций в реальном времени."), чтобы детализировать данные до уровня кода и оптимизировать программы.',
    "![zOS Java 2](https://dt-cdn.net/images/zos-java-2-2729-43a263828d.png)": "![zOS Java 2](https://dt-cdn.net/images/zos-java-2-2729-43a263828d.png)",
    "zOS Java 2": "zOS Java 2",
    'Quickly detect anomalies with the [Service response time hotspots](/managed/observe/application-observability/services-classic/service-response-time-hotspots "Identify the activities that consume the most response time for each service.").': 'Быстро обнаруживайте аномалии с помощью [горячих точек времени ответа службы](/managed/observe/application-observability/services-classic/service-response-time-hotspots "Определите действия, потребляющие наибольшее время ответа для каждой службы.").',
    "![zOS Java 3](https://dt-cdn.net/images/zos-java-3-2312-97d45f24a2.png)": "![zOS Java 3](https://dt-cdn.net/images/zos-java-3-2312-97d45f24a2.png)",
    "zOS Java 3": "zOS Java 3",
    "Analyze failures and exceptions with detailed stack traces.": "Анализируйте сбои и исключения с подробными стек-трейсами.",
    "![zOS Java 4](https://dt-cdn.net/images/zos-java-4-2674-ebbc7f564d.png)": "![zOS Java 4](https://dt-cdn.net/images/zos-java-4-2674-ebbc7f564d.png)",
    "zOS Java 4": "zOS Java 4",
    "Understand the health and performance of your JVM with the applications deployed on it": "Оценивайте работоспособность и производительность JVM с развёрнутыми на ней приложениями",
    "Gain insights into your JVM with the Dynatrace managed memory metrics:": "Получайте информацию о JVM с помощью управляемых метрик памяти Dynatrace:",
    "![zOS Java metrics 1](https://dt-cdn.net/images/zos-java-metrics-1-2472-ee3a4ee341.png)": "![zOS Java metrics 1](https://dt-cdn.net/images/zos-java-metrics-1-2472-ee3a4ee341.png)",
    "zOS Java metrics 1": "zOS Java metrics 1",
    "Understand the health and performance of your application servers with technology-specific metrics:": "Оценивайте работоспособность и производительность серверов приложений с помощью технологически специфичных метрик:",
    "![zOS Java metrics 2](https://dt-cdn.net/images/zos-java-metrics-2-2473-4cc98e9473.png)": "![zOS Java metrics 2](https://dt-cdn.net/images/zos-java-metrics-2-2473-4cc98e9473.png)",
    "zOS Java metrics 2": "zOS Java metrics 2",
    # --- ### What JMX and PMI metrics ---
    "### What JMX and PMI metrics does Dynatrace provide out of the box?": "### Какие метрики JMX и PMI Dynatrace предоставляет из коробки?",
    "JVM specific metrics:": "Метрики, специфичные для JVM:",
    "| Metric group | Metric | Source |": "| Группа метрик | Метрика | Источник |",
    "| --- | --- | --- |": "| --- | --- | --- |",
    "| JVM memory | Garbage collection total activation count | JMX |": "| JVM memory | Garbage collection total activation count | JMX |",
    "| JVM memory | Garbage collection total collection time | JMX |": "| JVM memory | Garbage collection total collection time | JMX |",
    "| JVM memory pool | Garbage collection count | JMX |": "| JVM memory pool | Garbage collection count | JMX |",
    "| JVM memory pool | Garbage collection time | JMX |": "| JVM memory pool | Garbage collection time | JMX |",
    "| JVM memory pool | Heap memory pool maximum bytes | JMX |": "| JVM memory pool | Heap memory pool maximum bytes | JMX |",
    "| JVM memory pool | Heap memory pool committed bytes | JMX |": "| JVM memory pool | Heap memory pool committed bytes | JMX |",
    "| JVM memory pool | Heap memory pool used bytes | JMX |": "| JVM memory pool | Heap memory pool used bytes | JMX |",
    "| JVM memory runtime | Runtime maximum memory | JMX |": "| JVM memory runtime | Runtime maximum memory | JMX |",
    "| JVM memory runtime | Runtime total memory | JMX |": "| JVM memory runtime | Runtime total memory | JMX |",
    "| JVM memory runtime | Runtime free memory | JMX |": "| JVM memory runtime | Runtime free memory | JMX |",
    "| JVM threads | Thread count | JMX |": "| JVM threads | Thread count | JMX |",
    "| JVM classes | Total number of loaded classes | JMX |": "| JVM classes | Total number of loaded classes | JMX |",
    "| JVM classes | Number of loaded classes | JMX |": "| JVM classes | Number of loaded classes | JMX |",
    "| JVM classes | Number of unloaded classes | JMX |": "| JVM classes | Number of unloaded classes | JMX |",
    "WebSphere Liberty and z/OS Connect specific metrics:": "Метрики, специфичные для WebSphere Liberty и z/OS Connect:",
    "| Metric group | Metric | Metric description | Source |": "| Группа метрик | Метрика | Описание метрики | Источник |",
    "| --- | --- | --- | --- |": "| --- | --- | --- | --- |",
    "| JDBC connection pool | In use connections | The number of connections in use. This number might include multiple connections that are shared from a single managed connection. | JMX |": "| JDBC connection pool | In use connections | Количество используемых соединений. Это число может включать несколько соединений, совместно использующих одно управляемое соединение. | JMX |",
    "| JDBC connection pool | Free connections | The number of managed connections in the free pool. | JMX |": "| JDBC connection pool | Free connections | Количество управляемых соединений в свободном пуле. | JMX |",
    "| JDBC connection pool | Managed connections | The total number of managed connections in the free, shared, and unshared pools. | JMX |": "| JDBC connection pool | Managed connections | Общее количество управляемых соединений в свободном, общем и выделенном пулах. | JMX |",
    "| JDBC connection pool | In use time | The average time in milliseconds that a connection is in use. | JMX |": "| JDBC connection pool | In use time | Среднее время использования соединения в миллисекундах. | JMX |",
    "| JDBC connection pool | Wait time | The average waiting time in milliseconds until a connection is granted if a connection is not currently available. | JMX |": "| JDBC connection pool | Wait time | Среднее время ожидания соединения в миллисекундах, если соединение временно недоступно. | JMX |",
    "| Thread pool | Pool size | The average number of threads in pool. | JMX |": "| Thread pool | Pool size | Среднее количество потоков в пуле. | JMX |",
    "| Thread pool | Active threads | The number of active threads that are serving requests. | JMX |": "| Thread pool | Active threads | Количество активных потоков, обрабатывающих запросы. | JMX |",
    "| Servlet | Request count | The total number of requests that a servlet processed. | JMX |": "| Servlet | Request count | Общее количество запросов, обработанных сервлетом. | JMX |",
    "Websphere Application Server specific metrics:": "Метрики, специфичные для WebSphere Application Server:",
    "| JDBC connection pool | Pool size | The size of the connection pool. | PMI |": "| JDBC connection pool | Pool size | Размер пула соединений. | PMI |",
    "| JDBC connection pool | Free pool size | The number of managed connections that are in the free pool. | PMI |": "| JDBC connection pool | Free pool size | Количество управляемых соединений в свободном пуле. | PMI |",
    "| JDBC connection pool | Concurrent waiters | The number of threads that are currently waiting for a connection. | PMI |": "| JDBC connection pool | Concurrent waiters | Количество потоков, ожидающих соединения в данный момент. | PMI |",
    "| JDBC connection pool | Average wait time | The average waiting time in milliseconds until a connection is granted if a connection is not currently available. | PMI |": "| JDBC connection pool | Average wait time | Среднее время ожидания соединения в миллисекундах, если соединение временно недоступно. | PMI |",
    "| JDBC connection pool | Average use time | The average time in milliseconds that a connection is in use. | PMI |": "| JDBC connection pool | Average use time | Среднее время использования соединения в миллисекундах. | PMI |",
    "| JDBC connection pool | Percent used | The percent of the pool that is in use. | PMI |": "| JDBC connection pool | Percent used | Доля используемого пула в процентах. | PMI |",
    "| Thread pool | Pool size | The average number of threads in pool. | PMI |": "| Thread pool | Pool size | Среднее количество потоков в пуле. | PMI |",
    "| Thread pool | Active threads | The number of concurrently active threads. | PMI |": "| Thread pool | Active threads | Количество одновременно активных потоков. | PMI |",
    "| Servlet | Live sessions | The number of local sessions that are currently cached in memory from the time at which this metric is enabled. | PMI |": "| Servlet | Live sessions | Количество локальных сеансов, кэшированных в памяти с момента включения этой метрики. | PMI |",
    "| Servlet | Total requests | The total number of requests that a servlet processed. | PMI |": "| Servlet | Total requests | Общее количество запросов, обработанных сервлетом. | PMI |",
    # --- ### Can I monitor custom JMX metrics ---
    "### Can I monitor custom JMX metrics with the z/OS Java module?": "### Можно ли отслеживать пользовательские метрики JMX с помощью модуля z/OS Java?",
    'Yes, you can use the z/OS Java module to monitor custom JMX metrics. For more information, see [Monitor JMX metrics on z/OS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/monitoring/zos-java-custom-jmx-metrics "Learn how to set up JMX metrics monitoring for your Java applications on z/OS.").': 'Да, модуль z/OS Java позволяет отслеживать пользовательские метрики JMX. Подробнее см. раздел [Мониторинг метрик JMX в z/OS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/monitoring/zos-java-custom-jmx-metrics "Узнайте, как настроить мониторинг метрик JMX для Java-приложений в z/OS.").',
    # --- ## Prerequisite ---
    "## Prerequisite": "## Предварительное условие",
    'Activate the [OneAgent feature](/managed/ingest-from/dynatrace-oneagent/oneagent-features "Manage OneAgent features globally and per process group.") **Forward Tag 4 trace context extension**.': 'Активируйте [функцию OneAgent](/managed/ingest-from/dynatrace-oneagent/oneagent-features "Управляйте функциями OneAgent глобально и для каждой группы процессов.") **Forward Tag 4 trace context extension**.',
    # --- ## Download ---
    "## Download": "## Загрузка",
    '1. [Download z/OS product datasets](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets "Download and install the Dynatrace product datasets for z/OS.") and extract the JAR file (`dynatrace-oneagent-zos-java.jar`).': '1. [Скачайте наборы данных продукта z/OS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets "Скачайте и установите наборы данных продукта Dynatrace для z/OS.") и извлеките JAR-файл (`dynatrace-oneagent-zos-java.jar`).',
    "2. Transfer the JAR file to your z/OS [Unix System Servicesï»¿](https://www.ibm.com/docs/en/zos/2.5.0?topic=zos-unix-system-services) (USS) environment in binary mode.": "2. Перенесите JAR-файл в окружение z/OS [Unix System Services](https://www.ibm.com/docs/en/zos/2.5.0?topic=zos-unix-system-services) (USS) в бинарном режиме.",
    "3. Create a new file with the name `dtconfig.json` in the z/OS USS folder where the module is located.": "3. Создайте новый файл с именем `dtconfig.json` в папке z/OS USS, где расположен модуль.",
    "A minimal `dtconfig.json` file contains your Dynatrace environment ID (**Tenant**), cluster ID (**ClusterID**), and the zDC subsystem name (**ZdcName**). For example:": "Минимальный файл `dtconfig.json` содержит идентификатор окружения Dynatrace (**Tenant**), идентификатор кластера (**ClusterID**) и имя подсистемы zDC (**ZdcName**). Например:",
    "Replace `myTenant` and `myCluster>` with your Dynatrace environment values. To find these values, go to **Deploy Dynatrace**, select **Start installation** > **z/OS**.": "Замените `myTenant` и `myCluster>` значениями вашего окружения Dynatrace. Чтобы найти эти значения, перейдите в **Deploy Dynatrace**, выберите **Start installation** > **z/OS**.",
    "If the zDC name is defined as `DEFAULT`, the module will connect to the default zDC subsystem ID. To use a different zDC, replace `DEFAULT` with an alternative subsystem ID.": "Если имя zDC задано как `DEFAULT`, модуль подключится к стандартному идентификатору подсистемы zDC. Чтобы использовать другую zDC, замените `DEFAULT` на альтернативный идентификатор подсистемы.",
    'You can find the zDC subsystem name in the [SYSIN parameters](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc#sysin-params "Set up the z/OS Data Collection subsystem (zDC).") of your JCL SYSIN member `ZDCSYSIN`. The default zDC subsystem name is `MEPC`.': 'Имя подсистемы zDC можно найти в [параметрах SYSIN](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc#sysin-params "Настройка подсистемы сбора данных z/OS (zDC).") элемента JCL SYSIN `ZDCSYSIN`. Стандартное имя подсистемы zDC: `MEPC`.',
    'If `DEFAULT` is set to `YES` in the [SYSIN parameters](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc#sysin-params "Set up the z/OS Data Collection subsystem (zDC)."), you can also use `DEFAULT` in the `dtconfig.json` file.': 'Если в [параметрах SYSIN](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc#sysin-params "Настройка подсистемы сбора данных z/OS (zDC).") параметр `DEFAULT` имеет значение `YES`, в файле `dtconfig.json` также можно использовать `DEFAULT`.',
    "* EBCDIC 1047, UTF-8, and ASCII encodings are supported for the `dtconfig.json` file.": "* Для файла `dtconfig.json` поддерживаются кодировки EBCDIC 1047, UTF-8 и ASCII.",
    "* The module automatically reads `dtconfig.json` when it's placed in the same folder as `dynatrace-oneagent-zos-java.jar`.": "* Модуль автоматически читает `dtconfig.json`, если файл находится в той же папке, что и `dynatrace-oneagent-zos-java.jar`.",
    "* If you put `dtconfig.json` in a different folder, you need to specify the path to it via the environment variable `DT_CONFIG_FILE`. The path must include the filename. You can use an absolute path or a path relative to the working folder of the process.": "* Если `dtconfig.json` размещён в другой папке, укажите путь к нему через переменную окружения `DT_CONFIG_FILE`. Путь должен включать имя файла. Допустимы как абсолютный путь, так и путь относительно рабочей папки процесса.",
    # --- ## Installation ---
    "## Installation": "## Установка",
    "### Updating a previously installed version of Dynatrace": "### Обновление ранее установленной версии Dynatrace",
    "If you have Dynatrace installed and are upgrading to a new release, you can jump to section [Update][#update]": "Если Dynatrace уже установлен и вы переходите на новую версию, перейдите к разделу [Обновление][#update]",
    "### Application server": "### Сервер приложений",
    "You need to add the z/OS Java module to the JVM arguments of each application server that you want to monitor.": "Необходимо добавить модуль z/OS Java в аргументы JVM каждого сервера приложений, который требуется отслеживать.",
    "WebSphere Application Server": "WebSphere Application Server",
    "WebSphere Liberty": "WebSphere Liberty",
    "WebSphere Liberty inside a CICS region": "WebSphere Liberty внутри региона CICS",
    "1. Open the WebSphere Application Server Admin Console and navigate to **Application servers**.": "1. Откройте Admin Console WebSphere Application Server и перейдите в раздел **Application servers**.",
    "2. Select `<YOUR_SERVER>` > **Process definition** > **Servant**, and choose **Java Virtual Machine**.": "2. Выберите `<YOUR_SERVER>` > **Process definition** > **Servant** и откройте **Java Virtual Machine**.",
    "3. Copy the JVM argument from your Dynatrace environment and paste it into the **Generic JVM arguments**:": "3. Скопируйте аргумент JVM из окружения Dynatrace и вставьте его в поле **Generic JVM arguments**:",
    "Replace `PATH_TO` with the path to your JAR file.": "Замените `PATH_TO` путём к вашему JAR-файлу.",
    "4. Save the changes and restart your WebSphere Application Server.": "4. Сохраните изменения и перезапустите WebSphere Application Server.",
    "* It's only necessary to add the module to the Servant processes.": "* Модуль необходимо добавлять только в процессы Servant.",
    "* We recommend adding the module as the first JVM argument.": "* Мы рекомендуем добавлять модуль первым в списке аргументов JVM.",
    "* The module must not be appended at the end of the command line.": "* Модуль не должен быть добавлен в конец командной строки.",
    "1. Create the `jvm.options` file in the root folder of your WebSphere Liberty (this folder typically also contains the `server.xml` file) or edit an existing file.": "1. Создайте файл `jvm.options` в корневой папке WebSphere Liberty (в этой папке, как правило, также находится файл `server.xml`) или отредактируйте существующий файл.",
    "2. Copy the JVM argument from your Dynatrace environment and paste it into the `jvm.options` file:": "2. Скопируйте аргумент JVM из окружения Dynatrace и вставьте его в файл `jvm.options`:",
    "Replace `PATH_TO` with the path to your JAR file.": "Замените `PATH_TO` путём к вашему JAR-файлу.",
    "3. Add the `monitor-1.0` feature to your `featureManager` in the `server.xml` file to collect additional metrics like connection pools or thread pools:": "3. Добавьте функцию `monitor-1.0` в `featureManager` файла `server.xml`, чтобы собирать дополнительные метрики, такие как пулы соединений или пулы потоков:",
    "4. Save the changes and restart your WebSphere Liberty.": "4. Сохраните изменения и перезапустите WebSphere Liberty.",
    "* We recommend to add the module as the first JVM argument.": "* Мы рекомендуем добавлять модуль первым в списке аргументов JVM.",
    "* We use the WebSphere Liberty server name as process group instance name per default. If you want to use a different process group instance name, you can override it by adding the following system property to your JVM command line: `-Dwlp.server.name=yourServerName`. Replace `yourServerName` with your individual name.": "* По умолчанию в качестве имени экземпляра группы процессов используется имя сервера WebSphere Liberty. Чтобы задать другое имя экземпляра группы процессов, добавьте следующее системное свойство в командную строку JVM: `-Dwlp.server.name=yourServerName`. Замените `yourServerName` нужным именем.",
    "1. Create the `.jvmprofile` file in your CICS region that belongs to the CICS JVMSERVER that is executing WebSphere Liberty or edit an existing file.": "1. Создайте файл `.jvmprofile` в регионе CICS, принадлежащем CICS JVMSERVER, который выполняет WebSphere Liberty, или отредактируйте существующий файл.",
    "2. Copy the JVM argument from your Dynatrace environment and paste it into the `.jvmprofile` file:": "2. Скопируйте аргумент JVM из окружения Dynatrace и вставьте его в файл `.jvmprofile`:",
    "3. Add the `monitor-1.0` feature to your `featureManager` in the `server.xml` file to collect additional metrics like connection pools or thread pools:": "3. Добавьте функцию `monitor-1.0` в `featureManager` файла `server.xml`, чтобы собирать дополнительные метрики, такие как пулы соединений или пулы потоков:",
    '* Monitoring of both the CICS region and the WebSphere Liberty that operates inside this CICS region is only supported if they report to a different zDC subsystem. If they report to different zDC subsystems, at least one of those zDCs must be started as non-default (see `SUBSYSTEM_ID` in the [zDC SYSIN parameters](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc#sysin-params "Set up the z/OS Data Collection subsystem (zDC).")). However, both zDCs can report to the same zRemote module.': '* Одновременный мониторинг региона CICS и работающего внутри него WebSphere Liberty поддерживается только при условии, что они отправляют данные в разные подсистемы zDC. Если они используют разные подсистемы zDC, хотя бы одна из них должна быть запущена как нестандартная (см. `SUBSYSTEM_ID` в [параметрах SYSIN zDC](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc#sysin-params "Настройка подсистемы сбора данных z/OS (zDC).")). При этом обе подсистемы zDC могут отправлять данные в один модуль zRemote.',
    '+ For the CICS module, the zDC subsystem name is defined in the [CICS SYSIN parameters](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-cics#connect-cics-zdc "Install the Dynatrace CICS module.").': '+ Для кодового модуля CICS имя подсистемы zDC задаётся в [параметрах SYSIN CICS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-cics#connect-cics-zdc "Установка кодового модуля CICS Dynatrace.").',
    "+ For the z/OS Java module, the zDC subsystem name is defined in the [`dtconfig.json` file](#download).": "+ Для модуля z/OS Java имя подсистемы zDC задаётся в [файле `dtconfig.json`](#download).",
    "* OneAgent version 1.281+ Dynatrace version 1.283+ When running in a CICS region, the process group instance name will include both the CICS region name and the WebSphere Liberty server name in the `CICS region (server name)` format.": "* OneAgent версии 1.281+ Dynatrace версии 1.283+ При работе в регионе CICS имя экземпляра группы процессов будет включать как имя региона CICS, так и имя сервера WebSphere Liberty в формате `CICS region (server name)`.",
    # --- ### Middleware ---
    "### Middleware": "### Промежуточное программное обеспечение",
    "You need to add the z/OS Java module to each product that you want to monitor.": "Необходимо добавить модуль z/OS Java в каждый продукт, который требуется отслеживать.",
    "z/OS Connect Enterprise Edition": "z/OS Connect Enterprise Edition",
    "CICS Transaction Gateway": "CICS Transaction Gateway",
    "IMS SOAP Gateway": "IMS SOAP Gateway",
    "1. Add the module to the `JVM_OPTIONS STDENV` variable:": "1. Добавьте модуль в переменную `JVM_OPTIONS STDENV`:",
    "2. Optional Add the `monitor-1.0` feature to your `featureManager` in the `server.xml` file to collect additional metrics like connection pools or thread pools:": "2. Необязательно. Добавьте функцию `monitor-1.0` в `featureManager` файла `server.xml`, чтобы собирать дополнительные метрики, такие как пулы соединений или пулы потоков:",
    "3. Save the changes and restart your z/OS Connect Enterprise Edition.": "3. Сохраните изменения и перезапустите z/OS Connect Enterprise Edition.",
    '4. For the CICS service provider, activate the [OneAgent feature](/managed/ingest-from/dynatrace-oneagent/oneagent-features "Manage OneAgent features globally and per process group.") **z/OS CICS z/OS Connect**.': '4. Для поставщика услуг CICS активируйте [функцию OneAgent](/managed/ingest-from/dynatrace-oneagent/oneagent-features "Управляйте функциями OneAgent глобально и для каждой группы процессов.") **z/OS CICS z/OS Connect**.',
    "5. For the IMS service provider:": "5. Для поставщика услуг IMS:",
    '1. Add the IMS module to **IMS Connect** as described in [Install the IMS module](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-ims#install "Install the Dynatrace IMS module.").': '1. Добавьте модуль IMS в **IMS Connect**, как описано в разделе [Установка модуля IMS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-ims#install "Установка кодового модуля IMS Dynatrace.").',
    '2. Activate the [OneAgent feature](/managed/ingest-from/dynatrace-oneagent/oneagent-features "Manage OneAgent features globally and per process group.") **z/OS IMS z/OS Connect**.': '2. Активируйте [функцию OneAgent](/managed/ingest-from/dynatrace-oneagent/oneagent-features "Управляйте функциями OneAgent глобально и для каждой группы процессов.") **z/OS IMS z/OS Connect**.',
    "6. For the MQ service provider, no additional configuration is needed.": "6. Для поставщика услуг MQ дополнительная настройка не требуется.",
    "1. Add the module to the `CTGENV` member and to the `CTGSTART_OPTS` variable:": "1. Добавьте модуль в элемент `CTGENV` и переменную `CTGSTART_OPTS`:",
    "2. Save the changes and restart your CICS Transaction Gateway.": "2. Сохраните изменения и перезапустите CICS Transaction Gateway.",
    "* Only the EXCI and IPIC protocols are supported.": "* Поддерживаются только протоколы EXCI и IPIC.",
    "* WAS local mode configuration of the CICS Transaction Gateway configuration is not supported.": "* Конфигурация CICS Transaction Gateway в локальном режиме WAS не поддерживается.",
    "1. Add the module as a `zDT` option to the IMS SOAP Gateway parameters:": "1. Добавьте модуль как параметр `zDT` в параметры IMS SOAP Gateway:",
    "2. Export the defined `zDT` option so that `IBM_JAVA_OPTIONS` includes it.": "2. Экспортируйте определённый параметр `zDT`, чтобы он вошёл в состав `IBM_JAVA_OPTIONS`.",
    "3. Save your changes and restart the IMS SOAP Gateway.": "3. Сохраните изменения и перезапустите IMS SOAP Gateway.",
    # --- ## Logging ---
    "## Logging": "## Журналирование",
    "By default, logging is disabled for the z/OS Java module. To enable logging, add one of the following options to the JVM argument:": "По умолчанию журналирование для модуля z/OS Java отключено. Чтобы включить его, добавьте один из следующих параметров в аргумент JVM:",
    "| Option | Default value | Description |": "| Параметр | Значение по умолчанию | Описание |",
    "| log-stdout | `false` | If `true`, write logs to the standard output stream. |": "| log-stdout | `false` | Если `true`, логи записываются в стандартный поток вывода. |",
    "| log-stderr | `false` | If `true`, write logs to the standard error stream. |": "| log-stderr | `false` | Если `true`, логи записываются в стандартный поток ошибок. |",
    "| log-file | `false` | If `true`, write logs to a file using file rotation (persisting the file with index 0). Naming scheme: `dynatrace-oneagent-java.<PID>.<LPAR>.<INDEX>.log`. |": "| log-file | `false` | Если `true`, логи записываются в файл с ротацией (файл с индексом 0 сохраняется). Схема именования: `dynatrace-oneagent-java.<PID>.<LPAR>.<INDEX>.log`. |",
    "If needed, you can log to multiple locations. For example:": "При необходимости запись логов можно вести сразу в несколько мест. Например:",
    "If needed, you can customize the file logging with the following options:": "При необходимости запись логов в файл можно настроить с помощью следующих параметров:",
    "| log-file-dir | `<CODEMODULE_FOLDER>/logs` | By default, write log files to the z/OS Java module folder.  It's also possible to write the log files to an absolute path (schema: `/<PATH_TO>/logs`) or to a path relative to the working folder of the process (schema: `<PATH_TO>/logs`). |": "| log-file-dir | `<CODEMODULE_FOLDER>/logs` | По умолчанию файлы логов записываются в папку модуля z/OS Java. Также поддерживается запись по абсолютному пути (схема: `/<PATH_TO>/logs`) или по пути относительно рабочей папки процесса (схема: `<PATH_TO>/logs`). |",
    "By changing the default folder, ensure that the application server has appropriate write permissions for the folder in which the module should write the log files.": "При изменении папки по умолчанию убедитесь, что сервер приложений имеет права на запись в папку, в которую модуль должен записывать файлы логов.",
    # --- ### OneAgent diagnostics ---
    "### OneAgent diagnostics": "### Диагностика OneAgent",
    'Dynatrace recommends to write the logs to the shared log folder of the zDC so that they are included into the [OneAgent diagnostics](/managed/ingest-from/dynatrace-oneagent/oneagent-troubleshooting/oneagent-diagnostics "Learn how to run OneAgent diagnostics") workflow. For example, if the `dtzagent` binary is located at `/u/dt/agent/lib64/dtzagent` in the z/OS USS environment, the log folder is `/u/dt/log`. Typically, a shared zDC log folder already exists and contains some zDC logs.': 'Dynatrace рекомендует записывать логи в общую папку логов zDC, чтобы они включались в рабочий процесс [диагностики OneAgent](/managed/ingest-from/dynatrace-oneagent/oneagent-troubleshooting/oneagent-diagnostics "Узнайте, как запускать диагностику OneAgent."). Например, если бинарный файл `dtzagent` расположен по пути `/u/dt/agent/lib64/dtzagent` в окружении z/OS USS, папка логов: `/u/dt/log`. Как правило, общая папка логов zDC уже существует и содержит часть логов zDC.',
    "To enable file logging to an absolute path such as the shared zDC log folder `/u/dt/log`, specify the JVM argument as follows:": "Чтобы включить запись логов в файл по абсолютному пути, например в общую папку логов zDC `/u/dt/log`, задайте аргумент JVM следующим образом:",
    "If your zDC is installed in a different location, you must adopt the absolute path of the shared zDC log folder.": "Если zDC установлен в другом расположении, укажите соответствующий абсолютный путь к общей папке логов zDC.",
    # --- ## Update ---
    "## Update": "## Обновление",
    "To update your z/OS Java module to a newer version": "Чтобы обновить модуль z/OS Java до новой версии",
    '1. [Download z/OS product datasets](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets#download-pax "Download and install the Dynatrace product datasets for z/OS.") and transfer the JAR file (`dynatrace-oneagent-zos-java.jar`) to your z/OS USS environment in binary mode.': '1. [Скачайте наборы данных продукта z/OS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets#download-pax "Скачайте и установите наборы данных продукта Dynatrace для z/OS.") и перенесите JAR-файл (`dynatrace-oneagent-zos-java.jar`) в окружение z/OS USS в бинарном режиме.',
    "2. Locate your existing dtconfig.json in the z/OS USS folder where the old version of the module is located and copy it to the z/OS USS folder you used in step(1).": "2. Найдите существующий файл dtconfig.json в папке z/OS USS, где расположена старая версия модуля, и скопируйте его в папку z/OS USS, использованную на шаге 1.",
    "3. Stop your monitored application server or middleware.": "3. Остановите отслеживаемый сервер приложений или промежуточное программное обеспечение.",
    "4. Replace your current JAR file with the new JAR file.": "4. Замените текущий JAR-файл новым.",
    "5. Start your application server or middleware.": "5. Запустите сервер приложений или промежуточное программное обеспечение.",
    # --- ## FAQ ---
    "## FAQ": "## Вопросы и ответы",
    "How can I enable program control for the z/OS Java module?": "Как включить program control для модуля z/OS Java?",
    "If, after starting the application server in z/OS, you may see **Not Marked Program Controlled** messages or errors with the return code 139:": "Если после запуска сервера приложений в z/OS отображаются сообщения **Not Marked Program Controlled** или ошибки с кодом возврата 139:",
    "You need to enable program control for the z/OS Java module. To do so": "Необходимо включить program control для модуля z/OS Java. Для этого",
    "1. Expand `dynatrace-oneagent-zos-java.jar` that you downloaded into a program controlled folder.": "1. Распакуйте загруженный файл `dynatrace-oneagent-zos-java.jar` в папку с program control.",
    "2. Mark the appropriate `.so` file (31 or 64 bit) in the `lib/zos-s390/` directory as program-controlled.": "2. Пометьте соответствующий файл `.so` (31- или 64-разрядный) в каталоге `lib/zos-s390/` как program-controlled.",
    "* Switch to the path that contains the `.so` files.": "* Перейдите в путь, содержащий файлы `.so`.",
    "* Issue the following command using the 31- or 64-bit file:": "* Выполните следующую команду, используя 31- или 64-разрядный файл:",
    "3. Add `zos-native-library-override` to your JVM argument.": "3. Добавьте `zos-native-library-override` в аргумент JVM.",
    "Where:": "Где:",
    "* `<PATH_TO>` is the path to your JAR file.": "* `<PATH_TO>`: путь к вашему JAR-файлу.",
    "* `<PATH_TO_SO>` is the absolute path to the `.so` file that you want to control.": "* `<PATH_TO_SO>`: абсолютный путь к файлу `.so`, для которого требуется program control.",
    "4. Restart your application server.": "4. Перезапустите сервер приложений.",
    "Can I disable sensors of the z/OS Java module?": "Можно ли отключить сенсоры модуля z/OS Java?",
    "By default, all sensors of the z/OS Java module are enabled. In case of problems, you can disable specific sensors by setting their value to `false` in the `dtconfig.json` file.": "По умолчанию все сенсоры модуля z/OS Java включены. В случае проблем можно отключить конкретные сенсоры, установив их значение на `false` в файле `dtconfig.json`.",
}

# Lines that must remain verbatim EN (img-alt captions are already kept in TRANS as-is)
PASS = set()

if __name__ == "__main__":
    build_one(REL, FN, TRANS, PASS)
    qa_one(REL, FN)
