# -*- coding: utf-8 -*-
"""L4-IF.72 — .../data-sources/snmp-extensions/snmptraps-extensions.md"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/extensions/develop-your-extensions/data-sources/snmp-extensions"

TRANS = {
    "* Reference": "* Справочник",
    "* 9-min read": "* Чтение: 9 мин",
    "* Updated on May 06, 2026": "* Обновлено 6 мая 2026 г.",
    "SNMP traps are a standard way to notify your network central management of significant issues and events in your network infrastructure.": "SNMP traps: стандартный способ уведомления центральной системы управления сетью о значимых проблемах и событиях в сетевой инфраструктуре.",
    "Dynatrace provides you with a framework to extend your insights into data related to SNMP traps issued in your infrastructure and forward the trap messages issued by your SNMP devices as log events.": "Dynatrace предоставляет платформу для расширения анализа данных, связанных с SNMP traps, генерируемыми в инфраструктуре, и пересылки trap-сообщений от устройств SNMP в виде событий журнала.",
    "We assume the following:": "Предполагается следующее:",
    "* Your devices are capable of issuing SNMP traps": "* Устройства поддерживают генерацию SNMP traps",
    "* You know how to configure those devices to send traps and have the authority to do so": "* Известно, как настроить устройства на отправку trap-сообщений, и имеются соответствующие полномочия",
    '* You\'re familiar with [Extensions basic concepts](/managed/ingest-from/extensions/concepts "Learn more about the concept of Dynatrace Extensions.") and the general structure of the [extension YAML file](/managed/ingest-from/extensions/develop-your-extensions/extension-yaml "Learn how to create an extension YAML file using the Extensions framework.").': '* Вы знакомы с [базовыми концепциями Extensions](/managed/ingest-from/extensions/concepts "Learn more about the concept of Dynatrace Extensions.") и общей структурой [файла extension YAML](/managed/ingest-from/extensions/develop-your-extensions/extension-yaml "Learn how to create an extension YAML file using the Extensions framework.").',
    "![How SNMP Traps data source works](https://cdn.bfldr.com/B686QPH3/as/kp4g9n43jxqtw76p4bjjbw/SNMP_traps_data_source_-_Light_Mode?auto=webp&format=png&position=1)": "![Принцип работы источника данных SNMP Traps](https://cdn.bfldr.com/B686QPH3/as/kp4g9n43jxqtw76p4bjjbw/SNMP_traps_data_source_-_Light_Mode?auto=webp&format=png&position=1)",
    "How SNMP Traps data source works": "Принцип работы источника данных SNMP Traps",
    "## Prerequisites and support": "## Предварительные требования и поддержка",
    'Learn the prerequisites and scope of the supported technologies. For limits applying to your extension, see [Extensions](/managed/ingest-from/extensions/concepts "Learn more about the concept of Dynatrace Extensions.").': 'Ознакомьтесь с предварительными требованиями и перечнем поддерживаемых технологий. Сведения об ограничениях, применяемых к расширениям, см. в разделе [Extensions](/managed/ingest-from/extensions/concepts "Learn more about the concept of Dynatrace Extensions.").',
    "### Supported Dynatrace versions": "### Поддерживаемые версии Dynatrace",
    "* Dynatrace version 1.236+": "* Dynatrace версии 1.236 и выше",
    "* ActiveGate version 1.235+": "* ActiveGate версии 1.235 и выше",
    "### Supported SNMP versions": "### Поддерживаемые версии SNMP",
    "* SNMPv2c and earlier": "* SNMPv2c и более ранние версии",
    "* SNMPv3 ActiveGate version 1.251+": "* SNMPv3 с ActiveGate версии 1.251 и выше",
    "### Hardware requirements": "### Требования к оборудованию",
    "If a large number of traps is sent, it is possible that many of them may be dropped by the operating system. The same situation occurs when the limit with logs is reached": "При отправке большого количества trap-сообщений операционная система может отбрасывать часть из них. Аналогичная ситуация возникает при достижении лимита журналов",
    "These are values for EEC in default performance profile": "Значения для EEC с профилем производительности по умолчанию",
    "| Instance | CPU | Mem (MiB) | Estimated number of traps | Estimated number of traps for SNMPv3 |": "| Экземпляр | ЦП | Память (МиБ) | Расчётное количество trap-сообщений | Расчётное количество trap-сообщений для SNMPv3 |",
    "| --- | --- | --- | --- | --- |": "| --- | --- | --- | --- | --- |",
    "| c5.large | 5% | 45 MiB | 30k/min (logs enabled) 45k/min (logs disabled) | 17k/min (logs enabled) 32k/min (logs disabled) |": "| c5.large | 5% | 45 МиБ | 30 тыс/мин (журналы включены) 45 тыс/мин (журналы отключены) | 17 тыс/мин (журналы включены) 32 тыс/мин (журналы отключены) |",
    "These are values for EEC set in high performance profile": "Значения для EEC с высокопроизводительным профилем",
    "| c5.large | 15% | 45 MiB | 75k/min (logs enabled) 150k/min (logs disabled) | 60k/min (logs enabled) 105k/min (logs disabled) |": "| c5.large | 15% | 45 МиБ | 75 тыс/мин (журналы включены) 150 тыс/мин (журналы отключены) | 60 тыс/мин (журналы включены) 105 тыс/мин (журналы отключены) |",
    "## Supported authentication": "## Поддерживаемая аутентификация",
    "### SNMP v2c and earlier": "### SNMP v2c и более ранние версии",
    "Community strings.": "Строки community.",
    "### SNMP v3": "### SNMP v3",
    "For SNMP v3, the SNMP traps data source supports the `NoAuthNoPriv`, `authNoPriv`, and `authPriv` security levels and the following authentication protocols:": "Для SNMP v3 источник данных SNMP traps поддерживает уровни безопасности `NoAuthNoPriv`, `authNoPriv` и `authPriv`, а также следующие протоколы аутентификации:",
    "#### `authNoPriv`": "#### `authNoPriv`",
    "| Protocol |  | RFC |": "| Протокол |  | RFC |",
    "| --- | --- | --- |": "| --- | --- | --- |",
    "| MD5 | HMAC-96-MD5 | [rfc3414](https://tools.ietf.org/html/rfc3414) |": "| MD5 | HMAC-96-MD5 | [rfc3414](https://tools.ietf.org/html/rfc3414) |",
    "| SHA | HMAC-96-SHA | [rfc3414](https://tools.ietf.org/html/rfc3414) |": "| SHA | HMAC-96-SHA | [rfc3414](https://tools.ietf.org/html/rfc3414) |",
    "| SHA224 | HMAC-128-SHA-224 | [rfc7860](https://tools.ietf.org/html/rfc7860) |": "| SHA224 | HMAC-128-SHA-224 | [rfc7860](https://tools.ietf.org/html/rfc7860) |",
    "| SHA256 | HMAC-192-SHA-256 | [rfc7860](https://tools.ietf.org/html/rfc7860) |": "| SHA256 | HMAC-192-SHA-256 | [rfc7860](https://tools.ietf.org/html/rfc7860) |",
    "| SHA384 | HMAC-256-SHA-384 | [rfc7860](https://tools.ietf.org/html/rfc7860) |": "| SHA384 | HMAC-256-SHA-384 | [rfc7860](https://tools.ietf.org/html/rfc7860) |",
    "| SHA512 | HMAC-384-SHA-512 | [rfc7860](https://tools.ietf.org/html/rfc7860) |": "| SHA512 | HMAC-384-SHA-512 | [rfc7860](https://tools.ietf.org/html/rfc7860) |",
    "#### `authPriv`": "#### `authPriv`",
    "| Protocol |  | RFC | Notes |": "| Протокол |  | RFC | Примечания |",
    "| --- | --- | --- | --- |": "| --- | --- | --- | --- |",
    "| DES | CBC-DES | [rfc3414](https://tools.ietf.org/html/rfc3414) |  |": "| DES | CBC-DES | [rfc3414](https://tools.ietf.org/html/rfc3414) |  |",
    "| AES | CFB128-AES-128 | [rfc3826](https://tools.ietf.org/html/rfc3826) |  |": "| AES | CFB128-AES-128 | [rfc3826](https://tools.ietf.org/html/rfc3826) |  |",
    "| AES192[1](#fn-1-1-def) |  | n/a | Blumenthal key extension |": "| AES192[1](#fn-1-1-def) |  | n/a | Расширение ключа Blumenthal |",
    "| AES256[1](#fn-1-1-def) |  | n/a | Blumenthal key extension |": "| AES256[1](#fn-1-1-def) |  | n/a | Расширение ключа Blumenthal |",
    "| AES192C[1](#fn-1-1-def) |  | n/a | Reeder key extension |": "| AES192C[1](#fn-1-1-def) |  | n/a | Расширение ключа Reeder |",
    "| AES256C[1](#fn-1-1-def) |  | n/a | Reeder key extension |": "| AES256C[1](#fn-1-1-def) |  | n/a | Расширение ключа Reeder |",
    "1": "1",
    "These encryption algorithms are not officially specified, but they are often supported by network devices. See [SNMPv3 with AES-256](https://www.snmp.com/snmpv3/snmpv3_aes256.shtml).": "Данные алгоритмы шифрования не входят в официальную спецификацию, однако часто поддерживаются сетевыми устройствами. См. [SNMPv3 with AES-256](https://www.snmp.com/snmpv3/snmpv3_aes256.shtml).",
    "See the [Authentication](#authentication) section to learn how to define authentication in your monitoring configuration.": "Сведения об определении аутентификации в конфигурации мониторинга см. в разделе [Аутентификация](#authentication).",
    "### Supported messages": "### Поддерживаемые сообщения",
    "The SNMP traps data source supports only SNMP traps. SNMP inform requests aren't supported.": "Источник данных SNMP traps поддерживает только SNMP traps. SNMP inform-запросы не поддерживаются.",
    "## Events": "## События",
    'Trap events send detailed information about each trap to the [log ingest](/managed/analyze-explore-automate/log-monitoring/acquire-log-data "Learn how to acquire log data in Dynatrace Log Monitoring."). The trap message contains the following information:': 'События trap-сообщений передают подробную информацию о каждом trap-сообщении в [лог-ингест](/managed/analyze-explore-automate/log-monitoring/acquire-log-data "Learn how to acquire log data in Dynatrace Log Monitoring."). Trap-сообщение содержит следующие сведения:',
    "### Context": "### Контекст",
    "The entity for which the log event is accounted. The device IP and the OID are translated to a human-readable form using [MIB files](#mib-files-snmp-traps).": "Сущность, с которой связано событие журнала. IP-адрес устройства и OID переводятся в удобочитаемый формат с помощью [файлов MIB](#mib-files-snmp-traps).",
    "### Message": "### Сообщение",
    "The actual trap message with the trap type.": "Фактическое trap-сообщение с указанием типа trap-сообщения.",
    "### Attributes": "### Атрибуты",
    "Attributes passed to the log event.": "Атрибуты, передаваемые в событие журнала.",
    "#### Main": "#### Основные",
    "* `event.type`—always set to `LOG`": "* `event.type`: всегда имеет значение `LOG`",
    "* `log.source`—always set to `snmptraps`": "* `log.source`: всегда имеет значение `snmptraps`",
    "* `loglevel`—always set to `NONE`": "* `loglevel`: всегда имеет значение `NONE`",
    "* `snmp.version`—always set to `1`, `2c`, or `3`": "* `snmp.version`: всегда имеет значение `1`, `2c` или `3`",
    "### Dynatrace": "### Dynatrace",
    "Dynatrace topological properties.": "Топологические свойства Dynatrace.",
    "* `dt.source_entity`—the ID of the device (entity) for which the log event is accounted.": "* `dt.source_entity`: идентификатор устройства (сущности), с которым связано событие журнала.",
    "### Other": "### Прочее",
    "All variable bindings reported with the trap message and extension-defined variables are added as log event attributes (for example, `device.address` and `snmp.trap_oid`).": "Все привязки переменных, сообщаемые вместе с trap-сообщением, и переменные, определённые расширением, добавляются в качестве атрибутов события журнала (например, `device.address` и `snmp.trap_oid`).",
    "For more information about custom log attributes and log processing rules, see:": "Дополнительные сведения о пользовательских атрибутах журналов и правилах их обработки см. в следующих источниках:",
    '* [Create a custom log attribute](/managed/analyze-explore-automate/log-monitoring/analyze-log-data/log-custom-attributes#create-a-custom-log-attribute "Learn how to create and use custom attributes during log data ingestion.")': '* [Создание пользовательского атрибута журнала](/managed/analyze-explore-automate/log-monitoring/analyze-log-data/log-custom-attributes#create-a-custom-log-attribute "Learn how to create and use custom attributes during log data ingestion.")',
    '* [Log processing rules](/managed/upgrade/unavailable-in-managed "Your selection is unavailable in Dynatrace Managed.")': '* [Правила обработки журналов](/managed/upgrade/unavailable-in-managed "Your selection is unavailable in Dynatrace Managed.")',
    "### Enable trap events": "### Включение событий trap-сообщений",
    "Select the **Events** feature set to enable forwarding trap events to log ingest.": "Выберите набор функций **Events**, чтобы включить пересылку событий trap-сообщений в лог-ингест.",
    "If you use the default feature set, the extension will only report a single metric that counts the number of traps sent by a defined source during a defined interval.": "При использовании набора функций по умолчанию расширение сообщает только одну метрику: количество trap-сообщений, отправленных указанным источником за заданный интервал.",
    "### Log Viewer": "### Log Viewer",
    'In the [Log Viewer](/managed/analyze-explore-automate/log-monitoring/analyze-log-data/log-viewer "Learn how to use Dynatrace log viewer to analyze log data."), go to **Logs** and filter trap events by `log.source: snmptraps`.': 'В [Log Viewer](/managed/analyze-explore-automate/log-monitoring/analyze-log-data/log-viewer "Learn how to use Dynatrace log viewer to analyze log data.") откройте **Logs** и отфильтруйте события trap-сообщений по `log.source: snmptraps`.',
    "Trap event example": "Пример события trap-сообщения",
    "![SNMP trap event example in log viewer](https://dt-cdn.net/images/log-viewer-1087-9f26695568.png)": "![Пример события SNMP trap в Log Viewer](https://dt-cdn.net/images/log-viewer-1087-9f26695568.png)",
    "SNMP trap event example in log viewer": "Пример события SNMP trap в Log Viewer",
    "## Define data scope": "## Определение области данных",
    "* Extension name": "* Имя расширения",
    "* Extension version": "* Версия расширения",
    "* Frequency of metric collection (interval)": "* Частота сбора метрик (интервал)",
    "* Metric name": "* Имя метрики",
    "* Two available dimensions: trap sender and trap OID": "* Два доступных измерения: отправитель trap-сообщения и OID trap-сообщения",
    "### Example YAML definition file": "### Пример файла YAML-определения",
    'Your SNMP traps monitoring scope definition starts with the `snmptraps` YAML node. All the settings under the node pertain to the declared [data source type](/managed/ingest-from/extensions/concepts#data-source-type "Learn more about the concept of Dynatrace Extensions."), which in this case is SNMP traps.': 'Определение области мониторинга SNMP traps начинается с узла YAML `snmptraps`. Все параметры под этим узлом относятся к объявленному [типу источника данных](/managed/ingest-from/extensions/concepts#data-source-type "Learn more about the concept of Dynatrace Extensions."), которым в данном случае является SNMP traps.',
    "## Metrics": "## Метрики",
    "SNMP traps collect just one metric that counts the number of traps sent by a source defined in your monitoring configuration during a defined interval. Your only customization option is to provide its key.": "SNMP traps собирают только одну метрику: количество trap-сообщений, отправленных источником, определённым в конфигурации мониторинга, за заданный интервал. Единственный параметр настройки: ключ метрики.",
    "For example:": "Например:",
    'The metric key string must conform to the [metrics ingestion protocol](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#metric-key-required "Learn how the data ingestion protocol for Dynatrace Metrics API works.").': 'Строка ключа метрики должна соответствовать требованиям [протокола приёма метрик](/managed/ingest-from/extend-dynatrace/extend-metrics/reference/metric-ingestion-protocol#metric-key-required "Learn how the data ingestion protocol for Dynatrace Metrics API works.").',
    "### Best practices for metric keys": "### Рекомендации по именованию ключей метрик",
    "The metrics you ingest into Dynatrace using your extension are just some of the thousands of metrics, built-in and custom, processed by Dynatrace. To make your metrics keys unique and easy to identify in Dynatrace, the best practice is to prefix the metric name with the extension name. This guarantees that the metric key is unique and you can easily appoint a metric to a particular extension in your environment.": "Метрики, принимаемые в Dynatrace с помощью расширения, составляют лишь часть из тысяч встроенных и пользовательских метрик, обрабатываемых Dynatrace. Чтобы ключи метрик были уникальными и легко идентифицировались в Dynatrace, рекомендуется добавлять к имени метрики префикс в виде имени расширения. Это гарантирует уникальность ключа метрики и позволяет легко сопоставить метрику с конкретным расширением в среде.",
    "## Feature set": "## Набор функций",
    'Feature sets are categories into which you organize the data collected by the extension. For more information, see [Feature sets](/managed/ingest-from/extensions/concepts#feature-sets "Learn more about the concept of Dynatrace Extensions."). You can define feature sets at the extension, group, or individual metric level.': 'Наборы функций: категории, по которым организуются данные, собираемые расширением. Подробнее см. в разделе [Наборы функций](/managed/ingest-from/extensions/concepts#feature-sets "Learn more about the concept of Dynatrace Extensions."). Наборы функций можно определять на уровне расширения, группы или отдельной метрики.',
    "When activating your extension using [monitoring configuration](#monitoring-configuration), you can limit monitoring to one of the feature sets.": "При активации расширения с помощью [конфигурации мониторинга](#monitoring-configuration) можно ограничить мониторинг одним из наборов функций.",
    "In highly segmented networks, feature sets can reflect the segments of your environment. Then, when you create monitoring configuration, you can select a feature set and a corresponding ActiveGate group that can connect to this particular segment.": "В сильно сегментированных сетях наборы функций могут соответствовать сегментам среды. При создании конфигурации мониторинга можно выбрать набор функций и соответствующую группу ActiveGate, имеющую доступ к этому сегменту.",
    "All metrics that aren't categorized into any feature set are considered to be default and are always reported.": "Метрики, не отнесённые ни к одному набору функций, считаются метриками по умолчанию и всегда включаются в отчёт.",
    "## Interval": "## Интервал",
    "The interval at which the data measurement will be taken. You can define intervals at the group, subgroup, or individual metric level. You can define intervals with the granularity of one minute. The maximum interval is 2880 minutes (2 days, 48 hours).": "Интервал, с которым выполняется измерение данных. Интервалы можно задавать на уровне группы, подгруппы или отдельной метрики с точностью до одной минуты. Максимальный интервал: 2880 минут (2 суток, 48 часов).",
    "Setting the interval is not possible for JMX data sources.": "Для источников данных JMX задать интервал невозможно.",
    "The above format is supported starting with schema version 1.217. For earlier schema versions, use the following format (supported up to schema version 1.251):": "Приведённый формат поддерживается начиная со схемы версии 1.217. Для более ранних версий схемы используйте следующий формат (поддерживается до версии схемы 1.251 включительно):",
    "## MIB files": "## Файлы MIB",
    "Management Information Base (MIB) files define and describe SNMP objects identified by OIDs, allowing Dynatrace to decode trap messages into readable event data. When a device sends a trap, the extension uses MIBs to interpret the OIDs and present meaningful alerts.": "Файлы Management Information Base (MIB) определяют и описывают объекты SNMP, идентифицируемые по OID, что позволяет Dynatrace декодировать trap-сообщения в читаемые данные событий. При получении trap-сообщения расширение использует файлы MIB для интерпретации OID и формирования информативных оповещений.",
    "## Monitoring configuration": "## Конфигурация мониторинга",
    "After you define the scope of your configuration, you need to identify the network devices you'd like to collect data from and identify the ActiveGates that will execute the extension and connect to your devices.": "После определения области конфигурации необходимо указать сетевые устройства, с которых будут собираться данные, и ActiveGate, которые будут выполнять расширение и подключаться к этим устройствам.",
    'The monitoring configuration is a JSON payload defining the connection details, credentials, and feature sets that you want to monitor. For details, see [Start monitoring](/managed/upgrade/unavailable-in-managed "Your selection is unavailable in Dynatrace Managed.").': 'Конфигурация мониторинга: JSON-полезная нагрузка, определяющая параметры подключения, учётные данные и наборы функций для мониторинга. Подробнее см. в разделе [Запуск мониторинга](/managed/upgrade/unavailable-in-managed "Your selection is unavailable in Dynatrace Managed.").',
    "Example payload to activate an SNMP extension:": "Пример полезной нагрузки для активации расширения SNMP:",
    'When you have your initial extension YAML ready, package it, sign it, and upload it to your Dynatrace environment. For details, see [Manage extension lifecyle](/managed/upgrade/unavailable-in-managed "Your selection is unavailable in Dynatrace Managed.").': 'Когда исходный файл extension YAML готов, упакуйте, подпишите и загрузите его в среду Dynatrace. Подробнее см. в разделе [Управление жизненным циклом расширения](/managed/upgrade/unavailable-in-managed "Your selection is unavailable in Dynatrace Managed.").',
    "The Dynatrace Hub-based extension activation wizard contains a dynamically updated JSON payload with your monitoring configuration": "Мастер активации расширений на основе Dynatrace Hub содержит динамически обновляемую JSON-полезную нагрузку с конфигурацией мониторинга",
    "You can also use the Dynatrace API to download the schema for your extension that will help you create the JSON payload for your monitoring configuration.": "Также можно использовать Dynatrace API для загрузки схемы расширения, которая поможет создать JSON-полезную нагрузку для конфигурации мониторинга.",
    'Use [GET an extension schema](/managed/dynatrace-api/environment-api/extensions-20/extensions/get-schema "View the schema of an extension the Dynatrace Extensions 2.0 API.") endpoint.': 'Используйте эндпоинт [GET an extension schema](/managed/dynatrace-api/environment-api/extensions-20/extensions/get-schema "View the schema of an extension the Dynatrace Extensions 2.0 API.").',
    "Issue the following request:": "Выполните следующий запрос:",
    "Replace `{extension-name}` and `{extension-version}` with values from your extension YAML file. A successful call returns the JSON schema.": "Замените `{extension-name}` и `{extension-version}` значениями из файла extension YAML. Успешный вызов возвращает схему JSON.",
    "### Scope": "### Область",
    'Note that each ActiveGate host running your extension needs the root certificate to verify the authenticity of your extension. For more information, see [Sign extension](/managed/ingest-from/extensions/develop-your-extensions/sign-extensions "Learn how to sign an extension, upload certificates and custom extensions, and configure certificate permissions using the Dynatrace Extensions Framework.").': 'Каждому хосту ActiveGate, выполняющему расширение, необходим корневой сертификат для проверки его подлинности. Подробнее см. в разделе [Подписание расширения](/managed/ingest-from/extensions/develop-your-extensions/sign-extensions "Learn how to sign an extension, upload certificates and custom extensions, and configure certificate permissions using the Dynatrace Extensions Framework.").',
    'The scope is an ActiveGate group that will execute the extension. All of the ActiveGates from the group will run this monitoring configuration at a time. If you plan to use a single ActiveGate, assign it to a dedicated group. You can assign an ActiveGate to a group during or after installation. For more information, see [ActiveGate group](/managed/ingest-from/dynatrace-activegate/activegate-group "Understand the basic concepts of ActiveGate groups.").': 'Область: группа ActiveGate, которая будет выполнять расширение. Все ActiveGate из группы будут одновременно запускать данную конфигурацию мониторинга. При использовании одного ActiveGate назначьте его в выделенную группу. Назначить ActiveGate в группу можно во время или после установки. Подробнее см. в разделе [Группа ActiveGate](/managed/ingest-from/dynatrace-activegate/activegate-group "Understand the basic concepts of ActiveGate groups.").',
    "Use the following format when defining the ActiveGate group:": "При определении группы ActiveGate используйте следующий формат:",
    "Replace `<ActiveGate-group-name>` with the actual name.": "Замените `<ActiveGate-group-name>` фактическим именем.",
    "### Version": "### Версия",
    "Version of this monitoring configuration. Note that a single extension can run multiple monitoring configurations.": "Версия данной конфигурации мониторинга. Одно расширение может выполнять несколько конфигураций мониторинга.",
    "### Description": "### Описание",
    "Human-readable description of the specifics of this monitoring configuration.": "Понятное описание параметров данной конфигурации мониторинга.",
    "### Enabled": "### Включено",
    "If set to `true`, the configuration is active and Dynatrace starts monitoring immediately.": "Если задано значение `true`, конфигурация активна и Dynatrace немедленно начинает мониторинг.",
    "### Sources": "### Источники",
    "You have to define the sources of traps in a monitoring configuration. To define a source, add the following details:": "В конфигурации мониторинга необходимо определить источники trap-сообщений. Для определения источника укажите следующие сведения:",
    "* The network that sends packets with traps provided in the CDIR notation. To configure a single interface address, add the `32` subnet mask after the IP address, for example `172.10.11.0/32`.": "* Сеть, отправляющая пакеты с trap-сообщениями, в нотации CIDR. Для настройки адреса отдельного интерфейса добавьте маску подсети `32` после IP-адреса, например `172.10.11.0/32`.",
    "* UDP port to which traps are sent": "* UDP-порт, на который отправляются trap-сообщения",
    "* Authentication credentials": "* Учётные данные аутентификации",
    "+ SNMPv1 and SNMPv2 are authenticated using community name only.": "+ SNMPv1 и SNMPv2 аутентифицируются только по имени community.",
    "+ SNMPv3 requires advanced authentication and is described in a following section.": "+ SNMPv3 требует расширенной аутентификации, описанной в следующем разделе.",
    "### Authentication": "### Аутентификация",
    "Authentication details passed to the Dynatrace API when activating a monitoring configuration are obfuscated and it's impossible to retrieve them.": "Сведения об аутентификации, передаваемые в Dynatrace API при активации конфигурации мониторинга, обфускируются и не могут быть получены повторно.",
    "Depending on the security level, construct the authentication details using one of the examples below. See the list of [supported protocols](#snmp-v3).": "В зависимости от уровня безопасности сформируйте сведения об аутентификации по одному из приведённых ниже примеров. Список [поддерживаемых протоколов](#snmp-v3) см. ниже.",
    "Security level: authPriv": "Уровень безопасности: authPriv",
    "Security level: authNoPriv": "Уровень безопасности: authNoPriv",
    "Security level: NoAuthNoPriv": "Уровень безопасности: NoAuthNoPriv",
    "### Advanced": "### Дополнительные параметры",
    "In some SNMP traps, variable binding OIDs have dynamic parts at the end that change with each incoming trap. To prevent problems with processing SNMP traps, you can configure variable binding OID trimming.": "В некоторых SNMP traps OID привязок переменных содержат динамические части в конце, которые изменяются с каждым входящим trap-сообщением. Для предотвращения проблем при обработке SNMP traps можно настроить обрезку OID привязок переменных.",
    "#### Format": "#### Формат",
    "* `root`—is used to match the suffix and trim it accordingly. You can specify `root` in raw (`1.3.6.1.4.1.9.9.41.1.2.3.1`) or resolved (`CISCO-SMI::ciscoMgmt.41.1.2.3.1`) format.": "* `root`: используется для сопоставления суффикса и его обрезки. Параметр `root` можно задать в необработанном (`1.3.6.1.4.1.9.9.41.1.2.3.1`) или разрешённом (`CISCO-SMI::ciscoMgmt.41.1.2.3.1`) формате.",
    "* `suffixLen`—specifies the number of octets at the end of the OID that should be trimmed.": "* `suffixLen`: указывает количество октетов в конце OID, которые должны быть обрезаны.",
    "#### Example": "#### Пример",
    "In this example, all variable bindings in the `CISCO-SMI::ciscoMgmt` subtree end in `34024`. With each subsequently generated trap, the number will increase.": "В данном примере все привязки переменных в поддереве `CISCO-SMI::ciscoMgmt` заканчиваются на `34024`. С каждым последующим сгенерированным trap-сообщением это число будет увеличиваться.",
    "Before trimming:": "До обрезки:",
    "All variable bindings that match the value specified in `root` are trimmed.": "Все привязки переменных, соответствующие значению, указанному в `root`, обрезаются.",
    "After trimming:": "После обрезки:",
    "### Feature sets": "### Наборы функций",
    "Add a list of feature sets you want to monitor. To report all feature sets, add `all`.": "Укажите список наборов функций для мониторинга. Чтобы включить все наборы функций, укажите `all`.",
    'You can enable sending traps as [events](/managed/ingest-from/extensions/develop-your-extensions/data-sources/snmp-extensions/snmptraps-extensions#events "Create an SNMP traps extension using the Dynatrace Extensions framework.") by setting `featureSets` to `events`.': 'Отправку trap-сообщений в виде [событий](/managed/ingest-from/extensions/develop-your-extensions/data-sources/snmp-extensions/snmptraps-extensions#events "Create an SNMP traps extension using the Dynatrace Extensions framework.") можно включить, задав `featureSets` значение `events`.',
}

PASS = {
    "title: SNMP traps data source",
    "# SNMP traps data source",
    "source: https://docs.dynatrace.com/managed/ingest-from/extensions/develop-your-extensions/data-sources/snmp-extensions/snmptraps-extensions",
}

if __name__ == "__main__":
    build_one(REL, "snmptraps-extensions.md", TRANS, PASS)
    qa_one(REL, "snmptraps-extensions.md")
