import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/google-cloud-platform/legacy"

TRANS = {
    "title: Set up the Dynatrace GCP metric and/or log integration in a Kubernetes container (legacy)": "title: Настройка интеграции GCP метрик и/или логов Dynatrace в контейнере Kubernetes (устаревшее)",
    "# Set up the Dynatrace GCP metric and/or log integration in a Kubernetes container (legacy)": "# Настройка интеграции GCP метрик и/или логов Dynatrace в контейнере Kubernetes (устаревшее)",
    "* How-to guide": "* Практическое руководство",
    "* 16-min read": "* Чтение: 16 мин",
    "* Published Mar 12, 2021": "* Опубликовано 12 марта 2021 г.",
    "* Deprecated": "* Устарело",
    "This page describes how to install version 0.1 of the GCP integration in a Kubernetes container, which is scheduled for deprecation.": "На этой странице описана установка версии 0.1 интеграции GCP в контейнере Kubernetes, которая готовится к выводу из эксплуатации.",
    "* If you are making a fresh installation, you should [deploy the GCP metric and/or log integration (v.1.0) in a Kubernetes container](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-k8 \"Set up log and metric monitoring for GCP services on a new GKE Autopilot cluster.\").": "* При новой установке используйте [развёртывание интеграции GCP метрик и/или логов (версия 1.0) в контейнере Kubernetes](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-k8 \"Настройка мониторинга логов и метрик для сервисов GCP на новом кластере GKE Autopilot.\").",
    "* If you already have version 0.1 of the GCP integration installed, you should [migrate to version 1.0](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/migrate-gcp-function \"Migrate from Google Cloud integration version 0.1 to version 1.0 on Kubernetes and as a Google Cloud Function.\").": "* Если версия 0.1 интеграции GCP уже установлена, выполните [миграцию на версию 1.0](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/migrate-gcp-function \"Миграция с версии 0.1 на версию 1.0 интеграции Google Cloud в Kubernetes и в виде Google Cloud Function.\").",
    "To ingest metrics and/or logs from Google Cloud, you need to deploy a container on GKE (it also works on Google Autopilot). After it's deployed, you get metrics for services defined in the configmap, preset dashboards, and predefined alerts.": "Для приёма метрик и/или логов из Google Cloud необходимо развернуть контейнер в GKE (также работает в Google Autopilot). После развёртывания доступны метрики сервисов, определённых в configmap, преднастроенные дашборды и предопределённые оповещения.",
    "## Set up generic log ingestion Optional": "## Настройка общего приёма логов (необязательно)",
    "For complete observability of your workloads, be sure to set up generic log ingestion before installation. This requires additional configuration and a second container to forward the logs. See below for instructions.": "Для полной наблюдаемости рабочих нагрузок настройте общий приём логов до установки. Это требует дополнительной конфигурации и второго контейнера для пересылки логов. Инструкции см. ниже.",
    "1. Create a Pub/Sub topic and add a subscription to it. There are two ways to do this:": "1. Создайте топик Pub/Sub и добавьте к нему подписку. Это можно сделать двумя способами:",
    "In the Google Cloud console": "В консоли Google Cloud",
    "[Set up a Pub/Sub topic﻿](https://dt-url.net/zp03r4n) and [add a subscription﻿](https://dt-url.net/5c23r4h) to it.": "[Создайте топик Pub/Sub﻿](https://dt-url.net/zp03r4n) и [добавьте к нему подписку﻿](https://dt-url.net/5c23r4h).",
    "When editing the subscription, we recommend the following values:": "При редактировании подписки рекомендуются следующие значения:",
    "* **Acknowledgement deadline:** `120` seconds": "* **Acknowledgement deadline:** `120` секунд",
    "* **Message retention duration:** `1` day": "* **Message retention duration:** `1` день",
    "* **Retain acknowledged messages:** not selected": "* **Retain acknowledged messages:** не выбрано",
    "In Google Cloud Shell": "В Google Cloud Shell",
    "Run the following shell script in the GCP project you've selected for deployment.": "Выполните следующий shell-скрипт в проекте GCP, выбранном для развёртывания.",
    "Be sure to replace `<your-subscription-name>` and `<your-topic-name>` with your own values.": "Обязательно замените `<your-subscription-name>` и `<your-topic-name>` своими значениями.",
    "2. Configure [log export﻿](https://dt-url.net/4743r02) to send the desired logs to the GCP Pub/Sub topic created in the previous step.": "2. Настройте [экспорт логов﻿](https://dt-url.net/4743r02) для отправки нужных логов в топик GCP Pub/Sub, созданный на предыдущем шаге.",
    "3. If you choose to use an existing ActiveGate during deployment, [configure ActiveGate for generic log ingestion](/managed/analyze-explore-automate/log-monitoring/acquire-log-data/logs-classic-ingestion-api \"Learn how Dynatrace ingests log data and what are potential limits such ingestion.\").": "3. Если при развёртывании планируется использовать существующий ActiveGate, [настройте ActiveGate для общего приёма логов](/managed/analyze-explore-automate/log-monitoring/acquire-log-data/logs-classic-ingestion-api \"Узнайте, как Dynatrace принимает данные логов и каковы возможные ограничения.\").",
    "## Prerequisites": "## Предварительные требования",
    "To deploy the Dynatrace GCP Monitor in a Kubernetes container, you need to make sure the following GCP and Dynatrace requirements are met.": "Для развёртывания Dynatrace GCP Monitor в контейнере Kubernetes убедитесь, что выполнены следующие требования GCP и Dynatrace.",
    "### GCP requirements": "### Требования GCP",
    "#### Permissions": "#### Разрешения",
    "Running the deployment script requires a list of permissions. You can create a custom role (see below) and use it to deploy `dynatrace-gcp-monitor`.": "Выполнение скрипта развёртывания требует ряда разрешений. Создайте пользовательскую роль (см. ниже) и используйте её для развёртывания `dynatrace-gcp-monitor`.",
    "1. Create a YAML file named `dynatrace-gcp-monitor-helm-deployment-role.yaml` with the following content:": "1. Создайте YAML-файл с именем `dynatrace-gcp-monitor-helm-deployment-role.yaml` со следующим содержимым:",
    "dynatrace-gcp-monitor-helm-deployment-role.yaml": "dynatrace-gcp-monitor-helm-deployment-role.yaml",
    "2. Run the command below, replacing `<your_project_ID>` with the project ID where you want to deploy the dynatrace integration.": "2. Выполните команду ниже, заменив `<your_project_ID>` идентификатором проекта, в котором нужно развернуть интеграцию Dynatrace.",
    "Be sure to add this role to your GCP user.": "Обязательно добавьте эту роль своему пользователю GCP.",
    "#### Tools": "#### Инструменты",
    "If you run the deployment from GCP Cloud Shell, you don't need to install additional tools.": "При запуске развёртывания из GCP Cloud Shell дополнительные инструменты не требуются.",
    "If you run the deployment from any host with bash, you need to install:": "При запуске развёртывания с любого хоста с bash необходимо установить:",
    "* [Google Cloud SDK﻿](https://dt-url.net/e8110336)": "* [Google Cloud SDK﻿](https://dt-url.net/e8110336)",
    "* [Kubernetes CLI﻿](https://dt-url.net/ai03q1r)": "* [Kubernetes CLI﻿](https://dt-url.net/ai03q1r)",
    "* [Helm﻿](https://dt-url.net/rh03rrz)": "* [Helm﻿](https://dt-url.net/rh03rrz)",
    "#### Settings": "#### Настройки",
    "If you run the deployment on an existing GKE standard cluster, you need to:": "При развёртывании на существующем стандартном кластере GKE необходимо:",
    "* [Enable Workload Identity on a cluster﻿](https://dt-url.net/2j23qqv)": "* [Включить Workload Identity на кластере﻿](https://dt-url.net/2j23qqv)",
    "* [Enable `GKE_METADATA` on the GKE node pools﻿](https://dt-url.net/an43q2s)": "* [Включить `GKE_METADATA` на пулах узлов GKE﻿](https://dt-url.net/an43q2s)",
    "If you run the deployment on an existing GKE Autopilot cluster, or on a new Autopilot cluster that will be automatically created by deployment script, there are no additional settings.": "При развёртывании на существующем кластере GKE Autopilot или на новом кластере Autopilot, который будет автоматически создан скриптом развёртывания, дополнительные настройки не требуются.",
    "### Dynatrace requirements": "### Требования Dynatrace",
    "Review the requirements for ActiveGate and tokens as described below.": "Ознакомьтесь с требованиями к ActiveGate и токенам, описанными ниже.",
    "#### ActiveGate": "#### ActiveGate",
    "For ActiveGate, you have two options:": "Для ActiveGate доступны два варианта:",
    "* Have the installation script create a dedicated ActiveGate (default option). Recommended": "* Создание выделенного ActiveGate скриптом установки (вариант по умолчанию). Рекомендуется",
    "* Use an existing ActiveGate version 1.213+. Required": "* Использование существующего ActiveGate версии 1.213+. Обязательно",
    "#### Tokens": "#### Токены",
    "The requirements for API and PaaS tokens are as follows:": "Требования к API и PaaS токенам:",
    "* [Create an API token﻿](https://dt-url.net/be03q3a)": "* [Создайте API токен﻿](https://dt-url.net/be03q3a)",
    "* [Enable the following permissions for the API token﻿](https://dt-url.net/c023q1m) as needed:": "* [Включите следующие разрешения для API токена﻿](https://dt-url.net/c023q1m) по необходимости:",
    "+ To ingest metrics: **Ingest metrics** (API v2), **Read configuration** (API v1), **Write configuration** (API v1)": "+ Для приёма метрик: **Ingest metrics** (API v2), **Read configuration** (API v1), **Write configuration** (API v1)",
    "+ To ingest logs: **Ingest logs** (API v2)": "+ Для приёма логов: **Ingest logs** (API v2)",
    "+ To ingest both logs and metrics: **Ingest logs** (API v2), **Ingest metrics** (API v2), **Read configuration** (API v1), **Write configuration** (API v1)": "+ Для приёма логов и метрик: **Ingest logs** (API v2), **Ingest metrics** (API v2), **Read configuration** (API v1), **Write configuration** (API v1)",
    "* [Create a PaaS token](/managed/manage/identity-access-management/access-tokens-and-oauth-clients/access-tokens#paas-token \"Learn the concept of an access token and its scopes.\") (if you choose to set up a new ActiveGate during deployment)": "* [Создайте PaaS токен](/managed/manage/identity-access-management/access-tokens-and-oauth-clients/access-tokens#paas-token \"Узнайте о концепции токена доступа и его областях.\") (если планируется настройка нового ActiveGate при развёртывании)",
    "## Install": "## Установка",
    "To install the GCP Monitor in a Kubernetes cluster, follow the instructions below.": "Для установки GCP Monitor в кластере Kubernetes следуйте приведённым ниже инструкциям.",
    "[![Step 1](https://dt-cdn.net/images/step-1-086e22066c.svg \"Step 1\")": "[![Шаг 1](https://dt-cdn.net/images/step-1-086e22066c.svg \"Шаг 1\")",
    "**Download the helm deployment package in Google Cloud Shell**](/managed/ingest-from/google-cloud-platform/legacy/deployment-k8s-container-legacy#download-package \"Set up log and metric monitoring for GCP services in a Kubernetes container.\")[![Step 2](https://dt-cdn.net/images/step-2-1a1384627e.svg \"Step 2\")": "**Загрузка helm-пакета развёртывания в Google Cloud Shell**](/managed/ingest-from/google-cloud-platform/legacy/deployment-k8s-container-legacy#download-package \"Настройка мониторинга логов и метрик для сервисов GCP в контейнере Kubernetes.\")[![Шаг 2](https://dt-cdn.net/images/step-2-1a1384627e.svg \"Шаг 2\")",
    "**Determine the URL for your environment**](/managed/ingest-from/google-cloud-platform/legacy/deployment-k8s-container-legacy#url \"Set up log and metric monitoring for GCP services in a Kubernetes container.\")[![Step 3](https://dt-cdn.net/images/step-3-350cf6c19a.svg \"Step 3\")": "**Определение URL для вашей среды**](/managed/ingest-from/google-cloud-platform/legacy/deployment-k8s-container-legacy#url \"Настройка мониторинга логов и метрик для сервисов GCP в контейнере Kubernetes.\")[![Шаг 3](https://dt-cdn.net/images/step-3-350cf6c19a.svg \"Шаг 3\")",
    "**Configure parameter values**](/managed/ingest-from/google-cloud-platform/legacy/deployment-k8s-container-legacy#params \"Set up log and metric monitoring for GCP services in a Kubernetes container.\")[![Step 4](https://dt-cdn.net/images/step-4-3f89d67d41.svg \"Step 4\")": "**Настройка значений параметров**](/managed/ingest-from/google-cloud-platform/legacy/deployment-k8s-container-legacy#params \"Настройка мониторинга логов и метрик для сервисов GCP в контейнере Kubernetes.\")[![Шаг 4](https://dt-cdn.net/images/step-4-3f89d67d41.svg \"Шаг 4\")",
    "**Connect your Kubernetes cluster**](/managed/ingest-from/google-cloud-platform/legacy/deployment-k8s-container-legacy#connect-cluster \"Set up log and metric monitoring for GCP services in a Kubernetes container.\")[![Step 5](https://dt-cdn.net/images/step-5-2de312b50f.svg \"Step 5\")": "**Подключение кластера Kubernetes**](/managed/ingest-from/google-cloud-platform/legacy/deployment-k8s-container-legacy#connect-cluster \"Настройка мониторинга логов и метрик для сервисов GCP в контейнере Kubernetes.\")[![Шаг 5](https://dt-cdn.net/images/step-5-2de312b50f.svg \"Шаг 5\")",
    "**Run the script**](/managed/ingest-from/google-cloud-platform/legacy/deployment-k8s-container-legacy#script \"Set up log and metric monitoring for GCP services in a Kubernetes container.\")": "**Запуск скрипта**](/managed/ingest-from/google-cloud-platform/legacy/deployment-k8s-container-legacy#script \"Настройка мониторинга логов и метрик для сервисов GCP в контейнере Kubernetes.\")",
    "### Step 1 Download the helm deployment package in Google Cloud Shell": "### Шаг 1 Загрузка helm-пакета развёртывания в Google Cloud Shell",
    "Download and run the installation script below, making sure to replace `<VERSION>` with the release version you want to download, for example `0.1.19`.": "Загрузите и запустите скрипт установки ниже, заменив `<VERSION>` нужной версией релиза, например `0.1.19`.",
    "Be sure to choose one of the versions before `release-1.0.0`, as the newer versions require [different installation instructions](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-k8 \"Set up log and metric monitoring for GCP services on a new GKE Autopilot cluster.\").": "Выбирайте версии до `release-1.0.0`, так как более новые версии требуют [других инструкций по установке](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-k8 \"Настройка мониторинга логов и метрик для сервисов GCP на новом кластере GKE Autopilot.\").",
    "### Step 2 Determine the URL for your environment": "### Шаг 2 Определение URL для вашей среды",
    "* For Dynatrace SaaS: `https://<your-environment-id>.live.dynatrace.com`": "* Для Dynatrace SaaS: `https://<your-environment-id>.live.dynatrace.com`",
    "* For Dynatrace Managed: `https://<your-domain>/e/<your-environment-id>`": "* Для Dynatrace Managed: `https://<your-domain>/e/<your-environment-id>`",
    "* For ActiveGate (if you choose to use an existing ActiveGate to ingest logs): `https://<your-active-gate-IP-or-hostname>:9999/e/<your-environment-id>`": "* Для ActiveGate (при использовании существующего ActiveGate для приёма логов): `https://<your-active-gate-IP-or-hostname>:9999/e/<your-environment-id>`",
    "To determine `<your-environment-id>`, see [environment ID﻿](https://dt-url.net/ej43qge).": "Для определения `<your-environment-id>` см. [идентификатор среды﻿](https://dt-url.net/ej43qge).",
    "### Step 3 Configure parameter values": "### Шаг 3 Настройка значений параметров",
    "The `values.yaml` file located in `helm-deployment-package/dynatrace-gcp-monitor` allows you to set the required and optional parameter values. See below for the complete list of parameters available for this integration.": "Файл `values.yaml`, расположенный в `helm-deployment-package/dynatrace-gcp-monitor`, позволяет задать обязательные и необязательные значения параметров. Полный список доступных параметров интеграции см. ниже.",
    "#### Parameters for metrics and logs ingestion (deployment type: all)": "#### Параметры для приёма метрик и логов (тип развёртывания: all)",
    "| Parameter name | Description | Default value |": "| Имя параметра | Описание | Значение по умолчанию |",
    "| `gcpProjectId` | The GCP project ID where the Dynatrace GCP Monitor should be deployed. Use the GCP project of log Sink Pub/Sub subscription. For details, see [Set up generic log ingestion](#logingest). | Your current project ID |": "| `gcpProjectId` | Идентификатор проекта GCP, в котором будет развёрнут Dynatrace GCP Monitor. Используйте проект GCP с подпиской Pub/Sub для приёма логов. Подробнее см. [Настройка общего приёма логов](#logingest). | Идентификатор текущего проекта |",
    "| `deploymentType` | Set to 'all'. | `all` |": "| `deploymentType` | Установите значение 'all'. | `all` |",
    "| `dynatraceAccessKey` | Your Dynatrace API token with the required permissions according to your selected deployment. For details, see [Token requirements](#tokens). |  |": "| `dynatraceAccessKey` | Ваш API токен Dynatrace с необходимыми разрешениями в соответствии с выбранным типом развёртывания. Подробнее см. [Требования к токенам](#tokens). |  |",
    "| `activeGate.dynatracePaasToken` | Your PaaS token. For details, see [Token requirements](#tokens). |  |": "| `activeGate.dynatracePaasToken` | Ваш PaaS токен. Подробнее см. [Требования к токенам](#tokens). |  |",
    "| `dynatraceUrl` | Your Dynatrace environment endpoint. For details, see [Determine the URL for your environment](#url). |  |": "| `dynatraceUrl` | Эндпоинт вашей среды Dynatrace. Подробнее см. [Определение URL для вашей среды](#url). |  |",
    "| `logsSubscriptionId` | The ID of your log Sink Pub/Sub subscription. For details, see [Set up generic log ingestion](#logingest). |  |": "| `logsSubscriptionId` | Идентификатор подписки Pub/Sub для приёма логов. Подробнее см. [Настройка общего приёма логов](#logingest). |  |",
    "#### Optional additional parameters for metrics and logs ingestion": "#### Дополнительные необязательные параметры для приёма метрик и логов",
    "Optional": "Необязательно",
    "| `activeGate.useExisting` | Set to true if you choose to use an existing ActiveGate to ingest logs. For details, see [ActiveGate requirements](#ag). | `false` |": "| `activeGate.useExisting` | Установите true, если используется существующий ActiveGate для приёма логов. Подробнее см. [Требования к ActiveGate](#ag). | `false` |",
    "| `dynatraceLogIngestUrl` | Your ActiveGate endpoint used to ingest logs to Dynatrace. For details, see [Determine the URL for your environment](#url). |  |": "| `dynatraceLogIngestUrl` | Эндпоинт ActiveGate для приёма логов в Dynatrace. Подробнее см. [Определение URL для вашей среды](#url). |  |",
    "| `requireValidCertificate` | If set to `true`, Dynatrace requires the SSL certificate of your Dynatrace environment. | `true` |": "| `requireValidCertificate` | При значении `true` Dynatrace требует SSL-сертификат вашей среды Dynatrace. | `true` |",
    "| `selfMonitoringEnabled` | Send custom metrics to GCP to quickly diagnose if `dynatrace-gcp-monitor` processes and sends metrics/logs to Dynatrace properly. | `false` |": "| `selfMonitoringEnabled` | Отправка пользовательских метрик в GCP для быстрой диагностики корректности обработки и отправки метрик/логов в Dynatrace службой `dynatrace-gcp-monitor`. | `false` |",
    "| `dockerImage` | Dynatrace GCP Monitor docker image. We recommend using the default value, but you can adapt it if needed. | `dynatrace/dynatrace-gcp-monitor` |": "| `dockerImage` | Docker-образ Dynatrace GCP Monitor. Рекомендуется использовать значение по умолчанию, однако при необходимости его можно изменить. | `dynatrace/dynatrace-gcp-monitor` |",
    "| `logIngestContentMaxLength` | The maximum content length of a log event. Should be less than or equal to the setting on your Dynatrace environment. | `8192` |": "| `logIngestContentMaxLength` | Максимальная длина содержимого события лога. Должна быть меньше или равна настройке вашей среды Dynatrace. | `8192` |",
    "| `logIngestAttributeValueMaxLength` | The maximum length of the log event attribute value. If it exceeds the server limit, content will be truncated. | `250` |": "| `logIngestAttributeValueMaxLength` | Максимальная длина значения атрибута события лога. При превышении серверного лимита содержимое будет усечено. | `250` |",
    "| `logIngestRequestMaxEvents` | The maximum number of log events in a single payload to the logs ingestion endpoint. If it exceeds the server limit, payload will be rejected with code `413`. | `5000` |": "| `logIngestRequestMaxEvents` | Максимальное число событий лога в одном запросе к эндпоинту приёма логов. При превышении серверного лимита запрос будет отклонён с кодом `413`. | `5000` |",
    "| `logIngestRequestMaxSize` | The maximum size in bytes of a single payload to the logs ingestion endpoint. If it exceeds the server limit, payload will be rejected with code `413`. | `1048576` |": "| `logIngestRequestMaxSize` | Максимальный размер (в байтах) одного запроса к эндпоинту приёма логов. При превышении серверного лимита запрос будет отклонён с кодом `413`. | `1048576` |",
    "| `logIngestEventMaxAgeSeconds` | Determines the maximum age of a forwarded log event. Should be less than or equal to the setting on your Dynatrace environment. | `86400` |": "| `logIngestEventMaxAgeSeconds` | Определяет максимальный возраст пересылаемого события лога. Должно быть меньше или равно настройке вашей среды Dynatrace. | `86400` |",
    "| `printMetricIngestInput` | If set to `true`, the GCP Monitor outputs the lines of metrics to stdout. | `false` |": "| `printMetricIngestInput` | При значении `true` GCP Monitor выводит строки метрик в stdout. | `false` |",
    "| `serviceUsageBooking` | Service usage booking is used for metrics and determines a caller-specified project for quota and billing purposes. If set to `source`, monitoring API calls are booked in the project where the Kubernetes container is running. If set to `destination`, monitoring API calls are booked in the project that is monitored. For details, see [Monitor multiple GCP projects - Step 4](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/monitor-multiple-projects \"Push metrics to Dynatrace from multiple Google Cloud projects.\"). | `source` |": "| `serviceUsageBooking` | Учёт использования сервисов применяется для метрик и определяет проект, указанный вызывающей стороной, в целях квот и выставления счетов. При значении `source` вызовы monitoring API учитываются в проекте, где запущен контейнер Kubernetes. При значении `destination` - в отслеживаемом проекте. Подробнее см. [Мониторинг нескольких проектов GCP - Шаг 4](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/monitor-multiple-projects \"Отправка метрик в Dynatrace из нескольких проектов Google Cloud.\"). | `source` |",
    "| `useProxy` | Depending on the value you set for this flag, the GCP Monitor will use the following proxy settings: Dynatrace (set to `DT_ONLY`), GCP API (set to `GCP_ONLY`), or both (set to `ALL`). | By default, proxy settings are not used. |": "| `useProxy` | В зависимости от значения этого флага GCP Monitor будет использовать следующие настройки прокси: Dynatrace (значение `DT_ONLY`), GCP API (значение `GCP_ONLY`) или оба варианта (значение `ALL`). | По умолчанию настройки прокси не используются. |",
    "| `httpProxy` | The proxy HTTP address; use this flag in conjunction with `USE_PROXY`. |  |": "| `httpProxy` | HTTP-адрес прокси; используется совместно с `USE_PROXY`. |  |",
    "| `httpsProxy` | The proxy HTTPS address; use this flag in conjunction with `USE_PROXY`. |  |": "| `httpsProxy` | HTTPS-адрес прокси; используется совместно с `USE_PROXY`. |  |",
    "| `importDashboards` | Import predefined dashboards for selected services. | `true` |": "| `importDashboards` | Импорт предопределённых дашбордов для выбранных сервисов. | `true` |",
    "| `importAlerts` | Import predefined alerting rules for selected services. | `true` |": "| `importAlerts` | Импорт предопределённых правил оповещений для выбранных сервисов. | `true` |",
    "| `gcpServicesYaml` | Configuration file for GCP services. |  |": "| `gcpServicesYaml` | Файл конфигурации для сервисов GCP. |  |",
    "| `queryInterval` | Metrics polling interval in minutes. Allowed values: `1` - `6` | `3` |": "| `queryInterval` | Интервал опроса метрик в минутах. Допустимые значения: `1` - `6` | `3` |",
    "#### Parameters for metrics-only ingestion (deployment type: metrics)": "#### Параметры для приёма только метрик (тип развёртывания: metrics)",
    "| `deploymentType` | Set to 'metrics'. | `all` |": "| `deploymentType` | Установите значение 'metrics'. | `all` |",
    "| `dynatraceAccessKey` | Your Dynatrace API token with the required permissions according to your selected deployment. For details, see [Token requirements](#token). |  |": "| `dynatraceAccessKey` | Ваш API токен Dynatrace с необходимыми разрешениями в соответствии с выбранным типом развёртывания. Подробнее см. [Требования к токенам](#token). |  |",
    "| `dynatraceUrl` | Your Dynatrace environment endpoint. For details, see [Determine the URL for your environment](#url). |  |": "| `dynatraceUrl` | Эндпоинт вашей среды Dynatrace. Подробнее см. [Определение URL для вашей среды](#url). |  |",
    "#### Optional additional parameters for metrics-only ingestion": "#### Дополнительные необязательные параметры для приёма только метрик",
    "#### Parameters for logs-only ingestion (deployment type: logs)": "#### Параметры для приёма только логов (тип развёртывания: logs)",
    "| `deploymentType` | Set to 'logs'. | `all` |": "| `deploymentType` | Установите значение 'logs'. | `all` |",
    "| `activeGate.dynatracePaasToken` | Your PaaS token. For details, see [Token requirements](#token). |  |": "| `activeGate.dynatracePaasToken` | Ваш PaaS токен. Подробнее см. [Требования к токенам](#token). |  |",
    "| `logsSubscriptionId` | The ID of your log Sink Pub/Sub subscription. For details, see [Set up generic log ingestion](#logingest). |  |": "| `logsSubscriptionId` | Идентификатор подписки Pub/Sub для приёма логов. Подробнее см. [Настройка общего приёма логов](#logingest). |  |",
    "#### Optional additional parameters for logs-only ingestion": "#### Дополнительные необязательные параметры для приёма только логов",
    "| `logIngestAttributeValueMaxLength` | The maximum length of the log event attribute value. If it exceeds server limit, content will be truncated. | `250` |": "| `logIngestAttributeValueMaxLength` | Максимальная длина значения атрибута события лога. При превышении серверного лимита содержимое будет усечено. | `250` |",
    "### Step 4 Connect your Kubernetes cluster": "### Шаг 4 Подключение кластера Kubernetes",
    "* If you want to have a new GKE Autopilot cluster created by the deployment script, add `--create-autopilot-cluster` to the script. No connection is needed in this case, because the deployment script will connect to the new cluster automatically.": "* Чтобы создать новый кластер GKE Autopilot скриптом развёртывания, добавьте `--create-autopilot-cluster` к скрипту. В этом случае подключение не требуется, так как скрипт автоматически подключится к новому кластеру.",
    "* If you run the deployment on an existing GKE standard cluster or an existing GKE Autopilot cluster, you can connect to your cluster from the GCP console or via terminal. Follow the instructions below.": "* При развёртывании на существующем стандартном кластере GKE или существующем кластере GKE Autopilot подключитесь к кластеру из консоли GCP или через терминал. Следуйте приведённым ниже инструкциям.",
    "From the GCP console": "Из консоли GCP",
    "Via terminal": "Через терминал",
    "1. In your GCP console, go to your Kubernetes Engine.": "1. В консоли GCP перейдите в Kubernetes Engine.",
    "2. Select **Clusters** > **Connect**.": "2. Выберите **Clusters** > **Connect**.",
    "3. Select **Run in Cloud Shell**.": "3. Выберите **Run in Cloud Shell**.",
    "Run the command below, making sure to replace": "Выполните команду ниже, заменив",
    "* `<cluster>` with your cluster name": "* `<cluster>` именем кластера",
    "* `<region>` with the region where your cluster is running": "* `<region>` регионом, в котором работает кластер",
    "* `<project>` with the project ID where your cluster is running": "* `<project>` идентификатором проекта, в котором работает кластер",
    "For details, see [Configuring cluster access for kubectl﻿](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#generate_kubeconfig_entry).": "Подробнее см. [Настройка доступа к кластеру для kubectl﻿](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#generate_kubeconfig_entry).",
    "### Step 5 Run the script": "### Шаг 5 Запуск скрипта",
    "* If you run the deployment on an existing GKE standard cluster or an existing GKE Autopilot cluster, the script will create an IAM service account with the necessary roles and deploy `dynatrace-gcp-monitor` to your Kubernetes cluster.": "* При развёртывании на существующем стандартном кластере GKE или существующем кластере GKE Autopilot скрипт создаст IAM service account с необходимыми ролями и развернёт `dynatrace-gcp-monitor` в кластере Kubernetes.",
    "* If you run the deployment with the `--create-autopilot-cluster` option, the script will automatically create the new GKE Autopilot cluster and deploy `dynatrace-gcp-monitor` to it.": "* При запуске с параметром `--create-autopilot-cluster` скрипт автоматически создаст новый кластер GKE Autopilot и развернёт в нём `dynatrace-gcp-monitor`.",
    "To run the script, follow the instructions below.": "Для запуска скрипта следуйте приведённым ниже инструкциям.",
    "Run on existing cluster": "Запуск на существующем кластере",
    "Run on new cluster": "Запуск на новом кластере",
    "You have two options:": "Доступны два варианта:",
    "* Run the script without parameters if you want to use the default values provided (`dynatrace-gcp-monitor-sa` for the IAM service account name and `dynatrace_monitor` for the IAM role name prefix):": "* Запустите скрипт без параметров для использования значений по умолчанию (`dynatrace-gcp-monitor-sa` для имени IAM service account и `dynatrace_monitor` для префикса имени IAM роли):",
    "* Run the script with parameters if you want to set your own values (be sure to replace the placeholders with your desired values):": "* Запустите скрипт с параметрами для задания собственных значений (замените плейсхолдеры нужными значениями):",
    "Run the command below.": "Выполните команду ниже.",
    "## Verify installation": "## Проверка установки",
    "To check whether installation was successful": "Чтобы проверить успешность установки:",
    "1. Check if the container is running.": "1. Проверьте, запущен ли контейнер.",
    "After the installation, it may take couple of minutes until the container is up and running.": "После установки может потребоваться несколько минут, пока контейнер запустится.",
    "2. Check the container logs for errors or exceptions. You have two options:": "2. Проверьте логи контейнера на наличие ошибок или исключений. Доступны два варианта:",
    "In the Kubernetes CLI": "В Kubernetes CLI",
    "In your GCP console": "В консоли GCP",
    "* For deployments of type 'metrics', run:": "* Для развёртываний типа 'metrics' выполните:",
    "* For deployments of type 'logs', run:": "* Для развёртываний типа 'logs' выполните:",
    "* For deployments of type 'all', run:": "* Для развёртываний типа 'all' выполните:",
    "To check the container logs for errors in your GCP console": "Проверка логов контейнера на наличие ошибок в консоли GCP",
    "1. Go to **Logs explorer**.": "1. Перейдите в **Logs explorer**.",
    "2. Use the filters below to get metric and/or log ingest logs from the Kubernetes container:": "2. Используйте следующие фильтры для получения логов приёма метрик и/или логов из контейнера Kubernetes:",
    "* `resource.type=\"k8s_container\"`": "* `resource.type=\"k8s_container\"`",
    "* `resource.labels.container_name=\"dynatrace-gcp-monitor-metrics\"` (for metric ingest logs)": "* `resource.labels.container_name=\"dynatrace-gcp-monitor-metrics\"` (для логов приёма метрик)",
    "* `resource.labels.container_name=\"dynatrace-gcp-monitor-logs\"` (for log ingest logs)": "* `resource.labels.container_name=\"dynatrace-gcp-monitor-logs\"` (для логов приёма логов)",
    "3. Check if dashboards are imported (for deployments of type 'metrics' or 'all').": "3. Проверьте импорт дашбордов (для развёртываний типа 'metrics' или 'all').",
    "Go to **Dashboards** and filter by **Tag** for **Google Cloud**. A number of dashboards for Google Cloud Services should be available.": "Перейдите в **Dashboards** и отфильтруйте по **Tag** со значением **Google Cloud**. Должен быть доступен ряд дашбордов для сервисов Google Cloud.",
    "## View metrics and/or logs": "## Просмотр метрик и/или логов",
    "After deploying the integration, depending on your deployment type, you can:": "После развёртывания интеграции, в зависимости от типа развёртывания, доступны следующие возможности:",
    "* See metrics from monitored services: go to **Metrics**.": "* Просмотр метрик отслеживаемых сервисов: перейдите в **Metrics**.",
    "* View and analyze GCP logs: in Dynatrace, go to **Logs** and, to look for GCP logs, filter by `cloud.provider: gcp`.": "* Просмотр и анализ логов GCP: в Dynatrace перейдите в **Logs** и для поиска логов GCP отфильтруйте по `cloud.provider: gcp`.",
    "![Log gcp](https://dt-cdn.net/images/2021-05-12-11-58-05-1506-4dddfe1936.png)": "![Логи GCP](https://dt-cdn.net/images/2021-05-12-11-58-05-1506-4dddfe1936.png)",
    "Log gcp": "Логи GCP",
    "## Troubleshooting": "## Устранение неполадок",
    "To investigate potential deployment and connectivity issues, see [Troubleshoot Google Cloud monitoring setup](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-k8 \"Set up log and metric monitoring for GCP services on a new GKE Autopilot cluster.\").": "Для диагностики возможных проблем с развёртыванием и подключением см. [Устранение неполадок настройки мониторинга Google Cloud](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-k8 \"Настройка мониторинга логов и метрик для сервисов GCP на новом кластере GKE Autopilot.\").",
    "## Related topics": "## Связанные темы",
    "* [Set up Dynatrace on Google Cloud](/managed/ingest-from/google-cloud-platform \"Monitor Google Cloud with Dynatrace.\")": "* [Настройка Dynatrace на Google Cloud](/managed/ingest-from/google-cloud-platform \"Мониторинг Google Cloud с помощью Dynatrace.\")",
}

PASS = {
    "source: https://docs.dynatrace.com/managed/ingest-from/google-cloud-platform/legacy/deployment-k8s-container-legacy",
    "| --- | --- | --- |",
}

build_one(REL, "deployment-k8s-container-legacy.md", TRANS, PASS)
qa_one(REL, "deployment-k8s-container-legacy.md")
