# -*- coding: utf-8 -*-
"""Builder for install-cics.md (L4-IF.71 canon)."""

import sys, os

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation"
FN = "install-cics.md"

# Mojibake note: EN source has scraping artifacts.
# U+00C2 U+00AE  = Â® (Davis® encoded as DavisÂ®)
# U+00EF U+00BB U+00BF = ï»¿ (BOM artifact embedded inline)
# U+00E2 = â (part of double-encoded em-dash/dash: â€" etc.)
# Keys below use CLEAN English — the _demoji() engine in _zos_canon_l4if71
# decodes latin1->utf8 automatically before matching, so write clean keys.

TRANS = {
    # --- frontmatter ---
    "title: Install the CICS module": "title: Установка модуля CICS",
    # --- h1 (appears twice) ---
    "# Install the CICS module": "# Установка модуля CICS",
    # --- metadata ---
    "* 14-min read": "* Чтение: 14 мин",
    "* Updated on Jan 28, 2026": "* Обновлено 28 января 2026 г.",
    # --- intro prose ---
    "With the CICS module, you can get observability for your CICS transactions and programs including DB2, DLI, and VSAM calls.": "С модулем CICS вы получаете наблюдаемость транзакций и программ CICS, включая вызовы DB2, DLI и VSAM.",
    # --- table header ---
    "| Observability for | Including |": "| Наблюдаемость для | Включает |",
    "| --- | --- |": "| --- | --- |",
    "| CICS transactions | Transactions initiated using  * IBM MQ Bridge and Trigger Monitor * CICS Transaction Gateway, HTTP/S, SOAP over HTTP/S, JSON using non-Java JSON pipeline * 3270 terminal |": "| Транзакции CICS | Транзакции, инициируемые через: * IBM MQ Bridge и Trigger Monitor * CICS Transaction Gateway, HTTP/S, SOAP over HTTP/S, JSON через non-Java JSON pipeline * терминал 3270 |",
    "| CICS programs | * Programs invoked using CICS LINK * Transaction details for DPL LINK and START TRANSACTION requests in a distributed trace |": "| Программы CICS | * Программы, вызываемые через CICS LINK * Детали транзакций для запросов DPL LINK и START TRANSACTION в распределённой трассировке |",
    "| Database calls | Database calls with their SQL statements from CICS to Db2 and IMS DB via the DL/I access method |": "| Обращения к базам данных | Обращения к базам данных с их SQL-выражениями из CICS в Db2 и IMS DB через метод доступа DL/I |",
    '| File access | [File access](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/monitoring/monitor-cics-file-access "File access monitoring of CICS applications using the CICS module.") from CICS via the VSAM and BDAM access methods. |': '| Доступ к файлам | [Мониторинг доступа к файлам в приложениях CICS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/monitoring/monitor-cics-file-access "Мониторинг доступа к файлам в приложениях CICS с использованием модуля CICS.") через методы доступа VSAM и BDAM. |',
    # --- callout: Trace your CICS transactions ---
    "Trace your CICS transactions end-to-end with Dynatrace": "Полная сквозная трассировка транзакций CICS с Dynatrace",
    'Analyze the performance of your transactions end-to-end using the [Service flow](/managed/observe/application-observability/services-classic/service-backtrace "Trace the sequence of service calls all the way back up to the browser click that triggered the sequence of calls.").': 'Анализируйте производительность транзакций end-to-end с помощью [Service flow](/managed/observe/application-observability/services-classic/service-backtrace "Отслеживайте последовательность вызовов сервисов вплоть до клика в браузере, который инициировал эту цепочку.").',
    # --- images (alt text stays EN per glossary; caption text translates) ---
    "![CICS service flow](https://dt-cdn.net/images/cics-trace-2357-0a7717e199.png)": "![CICS: поток сервиса](https://dt-cdn.net/images/cics-trace-2357-0a7717e199.png)",
    "CICS service flow": "CICS: поток сервиса",
    'Use the [PurePath distributed traces](/managed/observe/application-observability/distributed-traces "Gain observability into highly distributed, cloud-native architectures to effectively trace and analyze transactions in real time.") to drill down to the code level and to optimize your programs.': 'Используйте [PurePath distributed traces](/managed/observe/application-observability/distributed-traces "Получите наблюдаемость в высоко распределённых облачно-нативных архитектурах для эффективной трассировки и анализа транзакций в реальном времени.") для детализации до уровня кода и оптимизации программ.',
    "![CICS code-level](https://dt-cdn.net/images/cics-code-level-1984-d6aeff52fb.png)": "![CICS: уровень кода](https://dt-cdn.net/images/cics-code-level-1984-d6aeff52fb.png)",
    "CICS code-level": "CICS: уровень кода",
    "Understand exceptions in the context of your transactions down to the Db2 database layer.": "Анализируйте исключения в контексте транзакций вплоть до уровня базы данных Db2.",
    "![CICS distributed trace with exception](https://dt-cdn.net/images/cics-distributed-trace-1986-97b2240549.png)": "![CICS: распределённая трассировка с исключением](https://dt-cdn.net/images/cics-distributed-trace-1986-97b2240549.png)",
    "CICS distributed trace with exception": "CICS: распределённая трассировка с исключением",
    # --- callout: Detect CICS anomalies ---
    "Detect CICS anomalies and isolate fault domains with Dynatrace": "Обнаружение аномалий CICS и изоляция зон сбоев с Dynatrace",
    # mojibake: "Davis® AI" encoded as "DavisÂ® AI" — write clean key
    "Davis® AI automatically pinpoints the root cause of problems and assesses their user impact so that you can prioritize mitigation strategies and reduce the mean time to repair.": "Davis® AI автоматически определяет первопричину проблем и оценивает их влияние на пользователей, что позволяет расставлять приоритеты в стратегиях устранения и сокращать среднее время восстановления.",
    "![CICS automatic fault domain isolation](https://dt-cdn.net/images/cics-problem-1985-100d80f55c.png)": "![CICS: автоматическая изоляция зоны сбоя](https://dt-cdn.net/images/cics-problem-1985-100d80f55c.png)",
    "CICS automatic fault domain isolation": "CICS: автоматическая изоляция зоны сбоя",
    "Analyze failures with exception details in the context of transactions.": "Анализируйте сбои с подробностями исключений в контексте транзакций.",
    "![CICS failure analysis](https://dt-cdn.net/images/cics-exceptions-1985-478b6f8ba6.png)": "![CICS: анализ сбоев](https://dt-cdn.net/images/cics-exceptions-1985-478b6f8ba6.png)",
    "CICS failure analysis": "CICS: анализ сбоев",
    # --- ## Installation ---
    "## Installation": "## Установка",
    "The CICS module includes a PLT program that initiates at CICS startup. This program uses hooks to instrument CICS terminal and application owning regions, creating events of interest. It forwards monitoring data to the zDC subsystem via shared buffers.": "Модуль CICS включает PLT-программу, которая инициализируется при запуске CICS. Эта программа использует хуки для инструментирования CICS-регионов, владеющих терминалами и приложениями, создавая интересующие события. Данные мониторинга передаются в подсистему zDC через общие буферы.",
    "You need to install the CICS module in every CICS region you want to monitor. If Dynatrace is already installed on a CICS and you want to update your CICS module without restarting the CICS region, see [Update the CICS module without region restart](#cics-update).": "Модуль CICS нужно установить в каждом регионе CICS, который требуется мониторить. Если Dynatrace уже установлен в CICS и нужно обновить модуль CICS без перезапуска региона, см. раздел [Обновление без перезапуска региона](#cics-update).",
    'You need to add the [z/OS Java module](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zos-java#middleware "Set up Java monitoring on z/OS using the Java module.") to each CICS Transaction Gateway you want to monitor.': 'Необходимо добавить [модуль z/OS Java](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zos-java#middleware "Настройка мониторинга Java на z/OS с помощью модуля Java.") к каждому CICS Transaction Gateway, который требуется мониторить.',
    # --- ### CTS 6.2 support ---
    "### CTS 6.2 support": "### Поддержка CTS 6.2",
    "Beginning with OneAgent version 1.299, we are providing support for CTS 6.2, which is a major change and follows the latest security enhancements for the CICS subsystem.": "Начиная с OneAgent версии 1.299 обеспечивается поддержка CTS 6.2. Это значительное изменение, соответствующее последним улучшениям безопасности подсистемы CICS.",
    "CTS 6.2 support requires the `DFHBPZDT` load module that is supplied in the `SZDTAUTH` to be available at CICS region startup.": "Поддержка CTS 6.2 требует, чтобы загрузочный модуль `DFHBPZDT`, поставляемый в `SZDTAUTH`, был доступен при запуске региона CICS.",
    "Recommended installation procedure:": "Рекомендуемая процедура установки:",
    "Add a line similar to the example below to a PROGxx parmlib member. Note that the `SZDTAUTH` should be APF authorized.": "Добавьте строку, аналогичную приведённому ниже примеру, в элемент parmlib PROGxx. Обратите внимание, что `SZDTAUTH` должен иметь APF-авторизацию.",
    "To add the module to LPA immediately, enter a console command similar to the below example.": "Чтобы немедленно добавить модуль в LPA, введите консольную команду, аналогичную приведённому ниже примеру.",
    "Alternatively, it is also possible to add `DFHBPZDT` to the `STEPLIB` of the CICS 6.2 regions where the Dynatrace agent is installed.": "Также возможно добавить `DFHBPZDT` в `STEPLIB` регионов CICS 6.2, в которых установлен агент Dynatrace.",
    "However, we do not recommend adding the entire `SZDTAUTH` to the CICS STEPLIB.": "Тем не менее добавлять весь `SZDTAUTH` в CICS STEPLIB не рекомендуется.",
    "To verify the installation, CTS 6.2 prints the following mesage:": "Для проверки установки CTS 6.2 выводит следующее сообщение:",
    # --- ### CICS library definition ---
    "### CICS library definition": "### Определение библиотеки CICS",
    "You can dynamically add the load library as a CICS library definition in the CSD. The CEDA definition is in `SZDTSAMP` member `CICRDO`. You can find it in the example in the next section.": "Загрузочную библиотеку можно динамически добавить как определение библиотеки CICS в CSD. Определение CEDA находится в элементе `CICRDO` набора данных `SZDTSAMP`. Пример приведён в следующем разделе.",
    "If you don't want to use the CICS Library definition, you need to add the following PDS (or its contents) to the DFHRPL concatenation:": "Если использовать определение библиотеки CICS не нужно, добавьте следующий PDS (или его содержимое) в конкатенацию DFHRPL:",
    'Regardless of which option you decide to use, you need to tailor the DSN by replacing `<hlq>` with the high-level qualifier you set during [Download z/OS product datasets](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets "Download and install the Dynatrace product datasets for z/OS.").': 'Независимо от выбранного варианта необходимо скорректировать DSN, заменив `<hlq>` высококвалифицированным квалификатором, заданным при выполнении процедуры [Загрузка наборов данных продукта z/OS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets "Загрузите и установите наборы данных продукта Dynatrace для z/OS.").',
    # --- ### Dynatrace CICS programs and transaction ---
    "### Dynatrace CICS programs and transaction": "### Программы и транзакция CICS Dynatrace",
    "The CICS resource definitions for the Dynatrace CICS module can be found in `SZDTSAMP` member `CICRDO`, which is provided for use with the batch `RDO` utility `DFHCSDUP`.": "Определения ресурсов CICS для модуля CICS Dynatrace находятся в элементе `CICRDO` набора данных `SZDTSAMP`, предназначенном для использования с пакетной служебной программой `RDO` `DFHCSDUP`.",
    "We recommend to use these transaction and group names, but you can change them in accordance with your installation policies. Coordinate the group name and group list name with your CICS administrator. Replace `XYZLIST` with the name of your group list (`GRPLIST`).": "Рекомендуется использовать приведённые имена транзакций и групп, однако их можно изменить в соответствии с политиками вашей инсталляции. Согласуйте имя группы и имя списка групп с администратором CICS. Замените `XYZLIST` именем вашего списка групп (`GRPLIST`).",
    "While we recommend to use the default transaction ID `DTAX` for `ZDTPLT`, you can also use a custom transaction ID instead of `DTAX` in your definitions if you have conflicting transaction definitions.": "Рекомендуется использовать идентификатор транзакции по умолчанию `DTAX` для `ZDTPLT`, однако при наличии конфликтующих определений транзакций можно указать пользовательский идентификатор вместо `DTAX`.",
    # --- ### CICS startup program list table ---
    "### CICS startup program list table": "### Таблица списка программ запуска CICS",
    "Add the CICS startup program (`ZDTPLT`) after the `DFHDELIM` entry in your PLTPI source code and assemble the table.": "Добавьте программу запуска CICS (`ZDTPLT`) после записи `DFHDELIM` в исходном коде PLTPI и соберите таблицу.",
    'This step is optional for test installations because the [DTAX transaction](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction "Manage the CICS module via DTAX transactions.") can be used instead to enable the module after CICS initialization. We recommend that you place the `ZDTPLT` entry immediately before the `TYPE=FINAL` specification.': 'Этот шаг необязателен для тестовых инсталляций, так как для активации модуля после инициализации CICS можно воспользоваться [DTAX-транзакцией](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction "Управление модулем CICS через DTAX-транзакции."). Рекомендуется размещать запись `ZDTPLT` непосредственно перед спецификацией `TYPE=FINAL`.',
    "The JCL procedure `DFHAUPLE` in `CICSHLQ.SDFHINST(DFHAUPLE)` can be used to build the PLTPI table.": "Для формирования таблицы PLTPI можно использовать JCL-процедуру `DFHAUPLE` из `CICSHLQ.SDFHINST(DFHAUPLE)`.",
    "An example of the PLTPI table that contains the CICS startup program": "Пример таблицы PLTPI, содержащей программу запуска CICS",
    "Compuware Xpediter Global storage protection users": "Пользователи Compuware Xpediter Global Storage Protection",
    "The PLT startup program (`ZDTPLT`) initializes the CICS module's exit work area, which CICS obtains on its behalf. Products such as Compuware Xpediter/CICS may be configured to enforce strict storage access controls and may abend `ZDTPLT` and prevent the CICS module from starting unless it is excluded from these controls. If you use the Xpediter/CICS global storage protection feature, add a `monitor exceptions` entry to the XDDBPINP DD in the CICS region JCL to exclude `ZDTPLT*`. For example:": "PLT-программа запуска (`ZDTPLT`) инициализирует рабочую область выхода модуля CICS, которую CICS получает от его имени. Такие продукты, как Compuware Xpediter/CICS, могут быть настроены на применение строгого контроля доступа к памяти и вызывать аварийное завершение `ZDTPLT`, препятствуя запуску модуля CICS, если он не исключён из этих ограничений. При использовании функции глобальной защиты памяти Xpediter/CICS добавьте запись `monitor exceptions` в DD XDDBPINP JCL региона CICS для исключения `ZDTPLT*`. Например:",
    # --- ### CICS shutdown program list table ---
    "### CICS shutdown program list table": "### Таблица списка программ завершения CICS",
    "Add the CICS shutdown program (`ZDTPLTSD`) before the `DFHDELIM` entry in your PLTSD source code and assemble the table.": "Добавьте программу завершения CICS (`ZDTPLTSD`) перед записью `DFHDELIM` в исходном коде PLTSD и соберите таблицу.",
    "We recommend to place the `ZDTPLTSD` entry immediately after the `TYPE=INITIAL` specification.": "Рекомендуется размещать запись `ZDTPLTSD` непосредственно после спецификации `TYPE=INITIAL`.",
    "The JCL procedure `DFHAUPLE` in `CICSHLQ.SDFHINST(DFHAUPLE)` can be used to build the PLTSD table.": "Для формирования таблицы PLTSD можно использовать JCL-процедуру `DFHAUPLE` из `CICSHLQ.SDFHINST(DFHAUPLE)`.",
    "An example of the PLTSD table that contains the CICS shutdown program": "Пример таблицы PLTSD, содержащей программу завершения CICS",
    # --- ### Connect the CICS module to a zDC subsystem ---
    "### Connect the CICS module to a zDC subsystem": "### Подключение модуля CICS к подсистеме zDC",
    "The PLT startup program (`ZDTPLT`) automatically connects to the default zDC subsystem at CICS region initialization.": "PLT-программа запуска (`ZDTPLT`) автоматически подключается к подсистеме zDC по умолчанию при инициализации региона CICS.",
    "If multiple zDCs subsystems are running, it connects to the zDC that specifies `DEFAULT(YES)`, unless an `INITPARM` override parameter in the CICS SYSIN parameters specifies that it must connect to a zDC with a particular name:": "При работе нескольких подсистем zDC подключение выполняется к той, для которой задан параметр `DEFAULT(YES)`, если только параметр переопределения `INITPARM` в параметрах CICS SYSIN не указывает на подключение к zDC с конкретным именем:",
    "`<option>` sets the log level for the CICS module; see [Logging](#logging).": "`<option>` задаёт уровень журналирования для модуля CICS; см. раздел [Журналирование](#logging).",
    'To verify the connectivity between the CICS module and the zDC subsystem, [send a ping message](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction#ping "Manage the CICS module via DTAX transactions.").': 'Для проверки связи между модулем CICS и подсистемой zDC [отправьте ping-сообщение](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction#ping "Управление модулем CICS через DTAX-транзакции.").',
    # --- ## Customization ---
    "## Customization": "## Настройка",
    # --- ### CICSPlex name grouping ---
    "### CICSPlex name grouping": "### Группировка регионов по имени CICSPlex",
    "You can group CICS regions belonging to the same CICSPlex into a single process group. To do so": "Регионы CICS, принадлежащие одному CICSPlex, можно объединить в одну группу процессов. Для этого:",
    "1. Go to **Settings** > **Mainframe** > **Transaction monitoring**.": "1. Перейдите в **Settings** > **Mainframe** > **Transaction monitoring**.",
    "2. Turn on **Group CICS regions that belong to the same CICSPlex**.": "2. Включите **Group CICS regions that belong to the same CICSPlex**.",
    "3. Add `MASPLTWAIT(YES)` to your LMAS parameter. It instructs the CICS region to wait for the CICSPlex to become available before proceeding. If the CICSPlex isn't available, the module can't consider it.": "3. Добавьте `MASPLTWAIT(YES)` в параметр LMAS. Это указывает региону CICS ожидать доступности CICSPlex перед продолжением работы. Если CICSPlex недоступен, модуль не сможет его учесть.",
    "4. Optional The `MASINITTIME(10)` timeout interal defaults to 10 minutes. You can customize it in the range of 5 minutes to 59 minutes.": "4. Необязательно. Интервал ожидания `MASINITTIME(10)` по умолчанию составляет 10 минут. Его можно настроить в диапазоне от 5 до 59 минут.",
    'If you enabled CICSPlex name grouping **after** the CICS region is up, you need to run the [DTAX transaction](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction "Manage the CICS module via DTAX transactions.") `DTAX DISABLE` and `DTAX ENABLE`.': 'Если группировка по имени CICSPlex была включена **после** запуска региона CICS, необходимо выполнить [DTAX-транзакцию](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction "Управление модулем CICS через DTAX-транзакции.") `DTAX DISABLE` и `DTAX ENABLE`.',
    # --- ### CICS web services support ---
    "### CICS web services support": "### Поддержка веб-сервисов CICS",
    "The CICS module can trace the CICS web services invoked through a SOAP request or a JSON request (non-Java JSON pipeline). You need OneAgent version 1.257 or later to trace JSON requests.": "Модуль CICS позволяет трассировать веб-сервисы CICS, вызываемые через SOAP-запрос или JSON-запрос (non-Java JSON pipeline). Для трассировки JSON-запросов требуется OneAgent версии 1.257 или новее.",
    "To trace the CICS web service provider programs that are invoked by handler programs from CICS SOAP pipelines or from CICS non-Java JSON pipelines, update the provider pipeline config (`.xml`) file with `ZDTSOAPH` as shown below.": "Для трассировки программ провайдера веб-сервисов CICS, вызываемых программами-обработчиками из CICS SOAP pipelines или CICS non-Java JSON pipelines, обновите файл конфигурации провайдера (`.xml`), добавив `ZDTSOAPH`, как показано ниже.",
    "Only pipelines using the standard terminal handler are supported by Dynatrace. If you are running a non-standard terminal handler, it can be instrumented via the CICS and IMS SDK. As a starting point, you can use the following code samples:": "Dynatrace поддерживает только конвейеры со стандартным обработчиком терминала. При использовании нестандартного обработчика его инструментирование возможно через CICS and IMS SDK. В качестве отправной точки можно воспользоваться следующими примерами кода:",
    # mojibake: source has ï»¿ (U+FEFF BOM) inside link text and â€" (double-encoded em-dash U+2014)
    # after _demoji(): ﻿ stays inside [...], norm() strips it; — stays in norm() key.
    # Keys must use U+2014 (em-dash) before "CICS" — norm() does NOT strip em-dash.
    "* [ADKJSONA](https://assets.dynatrace.com/global/doc/appmon/integrations-and-extensions/development-kits/agent-development-kit-adk/cics-and-ims-adk/adkjsona.txt)—CICS assembler example of starting paths for JSON requests in a user-written apphandler.": "* [ADKJSONA](https://assets.dynatrace.com/global/doc/appmon/integrations-and-extensions/development-kits/agent-development-kit-adk/cics-and-ims-adk/adkjsona.txt): пример на ассемблере CICS стартовых путей для JSON-запросов в пользовательском apphandler.",
    "* [ADKJSONC](https://assets.dynatrace.com/global/doc/appmon/integrations-and-extensions/development-kits/agent-development-kit-adk/cics-and-ims-adk/adkjsonc.txt)—CICS COBOL example of starting paths for JSON requests in a user-written apphandler.": "* [ADKJSONC](https://assets.dynatrace.com/global/doc/appmon/integrations-and-extensions/development-kits/agent-development-kit-adk/cics-and-ims-adk/adkjsonc.txt): пример на CICS COBOL стартовых путей для JSON-запросов в пользовательском apphandler.",
    # --- #### CICS SOAP pipeline ---
    "#### CICS SOAP pipeline": "#### CICS SOAP pipeline",
    "`DFHPITP` is the app handler program used in the CICS SOAP pipeline config that invokes the service provider programs. In addition to the `DFHPITP` in the pipeline, the CICS code module also supports user-written terminal programs.": "`DFHPITP`: программа-обработчик приложений, используемая в конфигурации CICS SOAP pipeline для вызова программ провайдера сервиса. Помимо `DFHPITP` в конвейере, кодовый модуль CICS также поддерживает пользовательские программы обработчика терминала.",
    "Update your pipeline config file to include `ZDTSOAPH` in the `<headerprogram>` stanza under the SOAP handler element. Note that all SOAP pipelines have the SOAP handler element `<cics_soap_1.1_handler>` or `<cics_soap_1.2_handler>` where `ZDTSOAPH` is added. Below is a sample CICS SOAP provider pipeline updated with `ZDTSOAPH`.": "Обновите файл конфигурации конвейера, добавив `ZDTSOAPH` в секцию `<headerprogram>` под элементом обработчика SOAP. Все SOAP-конвейеры содержат элемент обработчика SOAP `<cics_soap_1.1_handler>` или `<cics_soap_1.2_handler>`, в который добавляется `ZDTSOAPH`. Ниже приведён пример CICS SOAP provider pipeline с добавленным `ZDTSOAPH`.",
    "To trace outbound SOAP requests that originate within CICS transactions that are traced by a CICS module, add the `<headerprogram>` stanza to the service requester pipeline definitions of those SOAP services that should be traced. Outbound SOAP requests that occur within CICS transactions that aren't traced are ignored. However, tracing isn't limited to requests from SOAP programs that act as CICS SOAP service providers.": "Для трассировки исходящих SOAP-запросов, возникающих в рамках CICS-транзакций, отслеживаемых модулем CICS, добавьте секцию `<headerprogram>` в определения конвейера запрашивающей стороны для тех SOAP-сервисов, которые нужно трассировать. Исходящие SOAP-запросы, возникающие в рамках не отслеживаемых CICS-транзакций, игнорируются. При этом трассировка не ограничена запросами от SOAP-программ, выступающих провайдерами сервиса CICS SOAP.",
    # --- #### OneAgent version 1.257+ CICS non-Java JSON pipeline ---
    "#### OneAgent version 1.257+ CICS non-Java JSON pipeline": "#### CICS non-Java JSON pipeline (OneAgent версии 1.257 и новее)",
    "`DFHPIJT` is the terminal handler program used in the CICS non-Java JSON pipeline that invokes the service provider programs. To trace the CICS web service provider invoked through the non-Java JSON pipeline, update your pipeline config file to include `ZDTSOAPH` in the `<handler>` stanza under the `<default_http_transport_handler_list>` xml tags. Below is a sample CICS non-Java JSON provider pipeline updated with `ZDTSOAPH`.": "`DFHPIJT`: программа-обработчик терминала, используемая в CICS non-Java JSON pipeline для вызова программ провайдера сервиса. Для трассировки провайдера веб-сервиса CICS, вызываемого через non-Java JSON pipeline, обновите файл конфигурации конвейера, добавив `ZDTSOAPH` в секцию `<handler>` под XML-тегами `<default_http_transport_handler_list>`. Ниже приведён пример CICS non-Java JSON provider pipeline с добавленным `ZDTSOAPH`.",
    # --- ### Route DTAX messages using TDQueue ---
    "### Route DTAX messages using TDQueue": "### Маршрутизация сообщений DTAX через TDQueue",
    "Optional To route DTAX messages to the Dynatrace TDQueue (Transient Data Queue), use the `ZDTQ` resource definition provided above in your `CICRDO` member.": "Необязательно. Для маршрутизации сообщений DTAX в TDQueue Dynatrace (Transient Data Queue) используйте определение ресурса `ZDTQ`, приведённое выше в элементе `CICRDO`.",
    "DTAX messages will only be written to the ZDTQ TDQueue if the queue is open. If you use the supplied resource definition, the queue remains closed due to the `OPENTIME(DEFERRED)` attribute. You can manually open it by using the `CEMT INQUIRE|SET TDQUEUE` command or you can set up the queue to open at initialization time, by modifying the TDQUEUE definition for ZDTQ to use the `OPENTIME(INITIAL)` attribute.": "Сообщения DTAX записываются в TDQueue ZDTQ только при открытой очереди. При использовании предоставленного определения ресурса очередь остаётся закрытой из-за атрибута `OPENTIME(DEFERRED)`. Открыть её вручную можно командой `CEMT INQUIRE|SET TDQUEUE`, либо настроить открытие при инициализации, изменив определение TDQUEUE для ZDTQ на атрибут `OPENTIME(INITIAL)`.",
    # --- ## Logging ---
    "## Logging": "## Журналирование",
    'You can control the CICS module log level either by using the [DTAX transaction](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction "Manage the CICS module via DTAX transactions.") or by specifying an optional `INITPARM` at CICS region startup.': 'Уровень журналирования модуля CICS можно задавать с помощью [DTAX-транзакции](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction "Управление модулем CICS через DTAX-транзакции.") или необязательного параметра `INITPARM` при запуске региона CICS.',
    "`<Option>` sets the logging level for CICS module. Accepted values are:": "`<Option>` задаёт уровень журналирования для модуля CICS. Допустимые значения:",
    "1. `FINE` | `F` for fine logging. We recommend to enable it only when the CICS module has difficulties during startup.": "1. `FINE` | `F`: детальное журналирование. Рекомендуется включать только при проблемах с запуском модуля CICS.",
    "2. `INFO` | `I` for info logging. This is the default.": "2. `INFO` | `I`: информационное журналирование. Значение по умолчанию.",
    "3. `WARNING` | `W` for warning messages logging.": "3. `WARNING` | `W`: журналирование предупреждений.",
    "4. `SEVERE` | `S` for severe messages logging.": "4. `SEVERE` | `S`: журналирование сообщений об ошибках.",
    "There are two different sets of CICS logs:": "Существует два набора логов CICS:",
    '* One set of messages occurs when the [DTAX transaction](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction "Manage the CICS module via DTAX transactions.") issues the `DISABLE` and `ENABLE` commands. These messages are written to the CICS CSMT Transient Data Queue(usually written to MSGUSR). View these messages in the CICS job spool. DTAX also writes a set of messages to the CEEOUT SYSOUT statement when errors occur in the connection between the zDC and the DTAX transaction. View these messages in the CICS Job spool. As long as the DTAX transaction can connect to the zDC, it logs its messages to the zRemote.': '* Один набор сообщений формируется при выполнении [DTAX-транзакцией](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction "Управление модулем CICS через DTAX-транзакции.") команд `DISABLE` и `ENABLE`. Эти сообщения записываются в CICS CSMT Transient Data Queue (обычно в MSGUSR). Просматривайте их в спуле задания CICS. DTAX также записывает набор сообщений в оператор CEEOUT SYSOUT при возникновении ошибок соединения между zDC и DTAX-транзакцией. Просматривайте эти сообщения в спуле задания CICS. Пока DTAX-транзакция может подключаться к zDC, она журналирует свои сообщения в zRemote.',
    "* The CICS module monitoring transaction activity routes its log messages to the zDC, and subsequently to the zRemote. The log shows if any corrupted distributed traces, timeouts, or other errors occurred. You may also see some statistical information in these logs.": "* Мониторинговая транзакционная активность модуля CICS направляет свои сообщения журнала в zDC, а затем в zRemote. Лог отражает наличие повреждённых распределённых трассировок, таймаутов и других ошибок. В этих логах также могут присутствовать статистические сведения.",
    'You can access the CICS logs via the [zRemote logs](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zremote#logging "Prepare and install the zRemote for z/OS monitoring.").': 'Доступ к логам CICS можно получить через [логи zRemote](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zremote#logging "Подготовка и установка модуля zRemote для мониторинга z/OS.").',
    # --- ## Update without region restart ---
    "## Update without region restart": "## Обновление без перезапуска региона",
    "To update your CICS module to a newer version without restarting the region": "Для обновления модуля CICS до новой версии без перезапуска региона:",
    '1. [Download z/OS product datasets](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets#download-pax "Download and install the Dynatrace product datasets for z/OS.") and [extract them](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets#extract-datasets "Download and install the Dynatrace product datasets for z/OS.").': '1. [Загрузите наборы данных продукта z/OS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets#download-pax "Загрузите и установите наборы данных продукта Dynatrace для z/OS.") и [распакуйте их](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets#extract-datasets "Загрузите и установите наборы данных продукта Dynatrace для z/OS.").',
    '2. Use the [DTAX transaction](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction "Manage the CICS module via DTAX transactions.") to disable the CICS module in the CICS region with the `DISABLE` command.': '2. С помощью [DTAX-транзакции](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction "Управление модулем CICS через DTAX-транзакции.") отключите модуль CICS в регионе CICS командой `DISABLE`.',
    "3. Copy the CICS modules in the `SZDTLOAD` dataset into the Dynatrace `DFHRPL` dataset defined to your CICS region.": "3. Скопируйте модули CICS из набора данных `SZDTLOAD` в набор данных Dynatrace `DFHRPL`, определённый для вашего региона CICS.",
    "4. Use the CICS command `CEMT I PROG(ZDT*)` to display the CICS modules. Use the `SET PROG(ZDT*) NEWCOPY` command to tell CICS a new version of each program will be used.": "4. Используйте команду CICS `CEMT I PROG(ZDT*)` для отображения модулей CICS. Выполните команду `SET PROG(ZDT*) NEWCOPY`, чтобы указать CICS на использование новой версии каждой программы.",
    "5. Use the DTAX transaction to enable the CICS module with the `ENABLE` command. Verify that the new CICS module version is displayed on the DTAX panel.": "5. С помощью DTAX-транзакции включите модуль CICS командой `ENABLE`. Убедитесь, что на панели DTAX отображается новая версия модуля CICS.",
    # --- ## FAQ ---
    "## FAQ": "## Вопросы и ответы",
    "How can I verify whether the CICS module and resources are installed correctly?": "Как проверить правильность установки модуля CICS и его ресурсов?",
    "The group name might be different, as well as the two-character suffix representing the CICS release of the module (for example, CTS52 uses 69).": "Имя группы может отличаться, как и двухсимвольный суффикс, обозначающий релиз CICS модуля (например, CTS52 использует 69).",
    "From the CICS region, look for these messages to validate the CICS module resources have been defined:": "В регионе CICS найдите приведённые ниже сообщения для подтверждения определения ресурсов модуля CICS:",
    "How can I verify whether the CICS module PLT program is invoked?": "Как проверить, вызывается ли PLT-программа модуля CICS?",
    "The CICS module logs initialization messages to the zRemote log.": "Модуль CICS записывает сообщения инициализации в лог zRemote.",
    "The zRemote log can be accessed from within Dynatrace, in the same manner as all the other module log files. Look for log entries similar to the following:": "Лог zRemote доступен из Dynatrace так же, как и все остальные файлы логов модулей. Найдите записи лога, аналогичные следующим:",
    "What should I do if a CICS region cannot connect to the zDC?": "Что делать, если регион CICS не может подключиться к zDC?",
    "Check the job log of the affected CICS regions for the following message, where `yyyy` is the subsystem ID of the zDC that the CICS region is trying to connect to. It might be blank if the CICS region is trying to connect to the default subsystem that is configured with the DEFAULT(YES) parameter. We recommend to simply search for the error message code.": "Проверьте лог задания затронутых регионов CICS на наличие следующего сообщения (`yyyy` здесь означает идентификатор подсистемы zDC, к которой подключается регион; значение может быть пустым, если регион подключается к подсистеме по умолчанию с параметром DEFAULT(YES)). Рекомендуется просто выполнить поиск по коду сообщения об ошибке.",
    'Verify that the zDC with that subsystem ID is started. If so, try to issue the [DTAX transaction](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction "Manage the CICS module via DTAX transactions.") command `ENABLE` to re-enable the connections.': 'Убедитесь, что zDC с данным идентификатором подсистемы запущен. Если это так, попробуйте выполнить команду `ENABLE` [DTAX-транзакции](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/operation/dtax-transaction "Управление модулем CICS через DTAX-транзакции.") для повторного включения соединений.',
    "How can I detect a version incompatibility?": "Как обнаружить несовместимость версий?",
    "Ensure that the CICS module version is less than or equal to zRemote module version. Don't connect newer CICS modules to older zRemote modules. Following is a sample message in the zRemote log when an CICS module version is incompatible with the zRemote version.": "Версия модуля CICS должна быть меньше или равна версии модуля zRemote. Не подключайте более новые модули CICS к более старым модулям zRemote. Ниже приведён пример сообщения в логе zRemote при несовместимости версий модуля CICS и модуля zRemote.",
}

# Lines that must remain verbatim EN
PASS = set()

if __name__ == "__main__":
    build_one(REL, FN, TRANS, PASS)
    qa_one(REL, FN)
