# -*- coding: utf-8 -*-
"""L4-IF.73 — ingest-from/microsoft-azure-services/azure-platform/azure-native-integration.md"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/microsoft-azure-services/azure-platform"

TT_LOGMON = "Узнайте, как включить мониторинг журналов, какую аналитику он предоставляет и многое другое."
TT_METRICS = "Узнайте о классических метриках, предлагаемых Dynatrace."
TT_DEFMETRICS = "Список классических метрик, собираемых Dynatrace по умолчанию для мониторинга Azure."
TT_HOSTGROUP = "Узнайте, как Dynatrace позволяет организовывать хосты, процессы и сервисы с помощью групп хостов."
TT_PAAS = "Узнайте о концепции токена доступа и его областях действия."
TT_ROLEBASED = "Разрешения на основе ролей."
TT_ALLSVC = "Мониторинг сервисов Azure с помощью Dynatrace и просмотр доступных метрик."
TT_TAGS = "Узнайте, как определять и применять теги вручную и автоматически."
TT_ENVPERM = "Разрешения на уровне среды."
TT_DASHBOARDS = (
    "Узнайте, как создавать, управлять и использовать Dynatrace Dashboards Classic."
)
TT_LOGVIEWER = "Узнайте, как использовать просмотрщик журналов Dynatrace для анализа данных журналов."
TT_SMARTSCAPE = (
    "Узнайте, как Smartscape визуализирует все сущности и зависимости в вашей среде."
)
TT_AZURE_INTEGRATIONS = (
    "Настройте глубокий мониторинг кода Azure с помощью OneAgent или OpenTelemetry."
)
TT_AZURE_DEFAULT = "Настройте среду Dynatrace SaaS с помощью Azure Marketplace."

TRANS = {
    "title: Azure Native Dynatrace Service": "title: Azure Native Dynatrace Service",
    "# Azure Native Dynatrace Service": "# Azure Native Dynatrace Service",
    "* Explanation": "* Концепция",
    "* 17-min read": "* Чтение: 17 мин",
    "* Updated on Jul 23, 2024": "* Обновлено 23 июля 2024 г.",
    "Azure Marketplace integration enables you to build a streamlined experience for purchasing, configuring, and managing Dynatrace directly inside the Azure portal. After setting up the integration, Dynatrace appears as an Azure native service, and you can manage its configuration from Azure Portal.": "Интеграция через Azure Marketplace позволяет организовать удобный процесс приобретения, настройки и управления Dynatrace непосредственно в портале Azure. После настройки интеграции Dynatrace отображается как нативный сервис Azure, и конфигурацией можно управлять из Azure Portal.",
    "Capabilities and limitations": "Возможности и ограничения",
    "**Capabilities:**": "**Возможности:**",
    "* **Seamless onboarding:** Easy onboarding to Dynatrace SaaS as an integrated service on Azure via Azure Marketplace. To set up the integration:": "* **Простое подключение:** удобное подключение Dynatrace SaaS как интегрированного сервиса Azure через Azure Marketplace. Чтобы настроить интеграцию:",
    "+ No event hubs, cloud functions, or configurations are required": "+ не требуется настройка концентраторов событий, облачных функций или конфигураций",
    "* **Unified billing:** Get a single bill for all the resources you consume on Azure, including all Dynatrace SaaS consumption.": "* **Единый биллинг:** единый счёт за все ресурсы, потребляемые в Azure, включая потребление Dynatrace SaaS.",
    "* **Single sign-on:** You don't need separate credentials for the Dynatrace portal. Sign in once on the Azure portal and seamlessly transition to Dynatrace when needed.": "* **Единый вход (SSO):** отдельные учётные данные для портала Dynatrace не нужны. Достаточно один раз войти на портал Azure и при необходимости перейти в Dynatrace.",
    f'* **Log monitoring:** Enables forwarding of subscription activity and resource logs to Dynatrace. For details, see [Log Monitoring](/managed/analyze-explore-automate/log-monitoring "Learn how to enable Log Monitoring, the insights that Log Monitoring can provide, and more.").': f'* **Мониторинг журналов:** обеспечивает пересылку журналов активности подписки и ресурсов в Dynatrace. Подробнее см. в разделе [Мониторинг журналов](/managed/analyze-explore-automate/log-monitoring "{TT_LOGMON}").',
    "* **OneAgent deployment:** You get a unified management experience of Dynatrace OneAgents. You can install and uninstall Dynatrace OneAgents as extensions on Azure Virtual Machines and Azure App Services.": "* **Развёртывание OneAgent:** единый интерфейс управления экземплярами Dynatrace OneAgent. Можно устанавливать и удалять Dynatrace OneAgent в качестве расширений на Azure Virtual Machines и Azure App Services.",
    "**Limitations:**": "**Ограничения:**",
    "* The integration will create a new Dynatrace environment and account; it can't run on an existing Dynatrace environment.": "* Интеграция создаёт новую среду и аккаунт Dynatrace; запустить её в существующей среде Dynatrace невозможно.",
    "Azure Marketplace": "Azure Marketplace",
    "The Azure Native Dynatrace service is available via the [Azure marketplace](https://dt-url.net/9n039mv).": "Azure Native Dynatrace Service доступен через [Azure Marketplace](https://dt-url.net/9n039mv).",
    "For getting a customized private offer for the Azure Native Dynatrace Service, reach out to Dynatrace sales via email to [sales@dynatrace.com](mailto:sales@dynatrace.com).": "Чтобы получить индивидуальное частное предложение для Azure Native Dynatrace Service, обратитесь в отдел продаж Dynatrace по адресу [sales@dynatrace.com](mailto:sales@dynatrace.com).",
    "## Prerequisites": "## Предварительные требования",
    "Activate the private plan for Azure Native Dynatrace Service": "Активация частного плана для Azure Native Dynatrace Service",
    "The Azure Native Dynatrace Service is available via a [private plan](https://dt-url.net/3d03xln). To have Dynatrace create a private plan for you, [contact Dynatrace](https://dt-url.net/m003xf1). Once you accept the offer, the private plan for Azure Native Dynatrace Service will be accessible on Azure Marketplace.": "Azure Native Dynatrace Service доступен через [частный план](https://dt-url.net/3d03xln). Чтобы Dynatrace создал для вас частный план, [свяжитесь с Dynatrace](https://dt-url.net/m003xf1). После принятия предложения частный план для Azure Native Dynatrace Service будет доступен в Azure Marketplace.",
    "Register the Dynatrace resource provider": "Регистрация поставщика ресурсов Dynatrace",
    "To create and manage the Dynatrace resources using the Azure Portal, you need to register a Dynatrace resource provider named `Dynatrace.Observability` in your Azure subscription.": "Чтобы создавать ресурсы Dynatrace и управлять ими через Azure Portal, необходимо зарегистрировать поставщика ресурсов Dynatrace с именем `Dynatrace.Observability` в подписке Azure.",
    "How to register the Dynatrace resource provider": "Как зарегистрировать поставщика ресурсов Dynatrace",
    "On the Azure Portal": "На Azure Portal",
    "Using the Azure CLI": "Через Azure CLI",
    "Follow the instructions on [Azure resource providers and types](https://dt-url.net/fu03x5j).": "Следуйте инструкциям в разделе [Поставщики ресурсов и типы Azure](https://dt-url.net/fu03x5j).",
    "Run the command below, making sure to replace `<subscription-id>` with your own subscription ID.": "Выполните приведённую ниже команду, заменив `<subscription-id>` на идентификатор своей подписки.",
    "Set up permissions": "Настройка разрешений",
    "#### General permissions": "#### Общие разрешения",
    "* You need a `Contributor` permission to the Azure subscription.": "* Требуется разрешение `Contributor` для подписки Azure.",
    "The first user creating the first Dynatrace resource and environment in a subscription becomes the Dynatrace account owner of the Dynatrace account that is created during the integration deployment. For all subsequent Dynatrace resources and environments that are created in the same subscription by other users, the account owner will also have full permissions.": "Первый пользователь, создавший первый ресурс и среду Dynatrace в подписке, становится владельцем аккаунта Dynatrace, созданного при развёртывании интеграции. Для всех последующих ресурсов и сред Dynatrace, созданных в той же подписке другими пользователями, владелец аккаунта также будет иметь полные права.",
    "## Set up the integration": "## Настройка интеграции",
    "When you first deploy the Azure Native Dynatrace Service, a new Dynatrace environment hosted on a new Dynatrace resource is created.": "При первом развёртывании Azure Native Dynatrace Service создаётся новая среда Dynatrace, размещённая на новом ресурсе Dynatrace.",
    "* The Dynatrace resource is created in the Azure subscription and resource group that you select during the installation deployment. You can configure, manage, and troubleshoot issues on your Dynatrace resource from the Azure Portal.": "* Ресурс Dynatrace создаётся в подписке Azure и группе ресурсов, выбранных при развёртывании. Настраивать, управлять и устранять неполадки ресурса Dynatrace можно из Azure Portal.",
    f"* The Dynatrace environment is created in the same Azure region in which you create the Dynatrace resource. In this new environment:": "* Среда Dynatrace создаётся в том же регионе Azure, в котором создаётся ресурс Dynatrace. В этой новой среде:",
    f'+ After you [install OneAgent](#oa), you can start monitoring [metrics](/managed/analyze-explore-automate/metrics-classic "Learn about metrics classic that Dynatrace offers.") from your Azure resources. You can also collect metrics from the [default services](/managed/ingest-from/microsoft-azure-services/azure-platform/azure-native-integration#default "Set and configure your Dynatrace SaaS environment using Azure Marketplace.")': f'+ После [установки OneAgent](#oa) можно начать мониторинг [метрик](/managed/analyze-explore-automate/metrics-classic "{TT_METRICS}") из ресурсов Azure. Также можно собирать метрики со [стандартных сервисов](/managed/ingest-from/microsoft-azure-services/azure-platform/azure-native-integration#default "{TT_AZURE_DEFAULT}")',
    f'+ You can collect [logs](/managed/analyze-explore-automate/log-monitoring "Learn how to enable Log Monitoring, the insights that Log Monitoring can provide, and more.") from your Azure resources': f'+ Можно собирать [журналы](/managed/analyze-explore-automate/log-monitoring "{TT_LOGMON}") из ресурсов Azure',
    "+ You do not need an environment ActiveGate for this integration.": "+ ActiveGate среды для этой интеграции не требуется.",
    "To set up the integration": "Настройка интеграции",
    "1. Go to the Azure subscription where you want to create the Dynatrace resource.": "1. Откройте подписку Azure, в которой нужно создать ресурс Dynatrace.",
    "2. Select **Resources**, and then select **Create**.": "2. Выберите **Resources**, затем выберите **Create**.",
    "3. Search for **Azure Native Dynatrace Service**. You should see the message that a private product is available.": "3. Найдите **Azure Native Dynatrace Service**. Должно появиться сообщение о доступности частного продукта.",
    "4. Select the tile **Azure Native Dynatrace Service**.": "4. Выберите плитку **Azure Native Dynatrace Service**.",
    "5. In the list for choosing a plan, select the private plan that you accepted in [Activate the private plan for Azure Native Dynatrace Service](#step-1) and then select **Subscribe**.": "5. В списке выбора плана выберите частный план, принятый в разделе [Активация частного плана для Azure Native Dynatrace Service](#step-1), затем нажмите **Subscribe**.",
    "6. On **Create a new Dynatrace environment**, select **Create**.": "6. На странице **Create a new Dynatrace environment** нажмите **Create**.",
    "7. In **Basics**, for **Resource group**, specify whether to create a new resource group or use an existing one.": "7. В разделе **Basics** для поля **Resource group** укажите, нужно ли создать новую группу ресурсов или использовать существующую.",
    "A resource group is a container that holds related resources for an Azure solution. For more information, see [Azure Resource Group overview](https://dt-url.net/xv43x96).": "Группа ресурсов (resource group): контейнер, в котором хранятся связанные ресурсы решения Azure. Подробнее см. в разделе [Обзор групп ресурсов Azure](https://dt-url.net/xv43x96).",
    "8. Enter a **Resource name** for the Dynatrace resource, and then select a **Region** from the dropdown menu. The Dynatrace resource in Azure and the Dynatrace environment will be created in the selected region.": "8. Введите **Resource name** для ресурса Dynatrace, затем выберите **Region** из выпадающего меню. Ресурс Dynatrace в Azure и среда Dynatrace будут созданы в выбранном регионе.",
    "9. Select your **Pricing plan**, and then select **Next: Metrics and Logs**.": "9. Выберите **Pricing plan**, затем нажмите **Next: Metrics and Logs**.",
    "10. Optional Select whether to **Send subscription activity logs** and/or **Send Azure resource logs**. For details, see [Configure metrics and logs](#metrics-logs).": "10. Необязательно: выберите, нужно ли включить **Send subscription activity logs** и/или **Send Azure resource logs**. Подробнее см. в разделе [Настройка метрик и журналов](#metrics-logs).",
    "If you select **Send Azure resource logs for all defined services**, Azure resource logs are sent for all defined resources by default, which means logs are collected for all supported resources. To filter the specific set of Azure resources sending logs to Dynatrace, you can use Azure resource tags. Tag rules are:": "Если выбрать **Send Azure resource logs for all defined services**, журналы ресурсов Azure по умолчанию отправляются для всех определённых ресурсов, то есть журналы собираются для всех поддерживаемых ресурсов. Чтобы фильтровать конкретный набор ресурсов Azure, отправляющих журналы в Dynatrace, можно использовать теги ресурсов Azure. Правила тегов:",
    "* Azure resources with `Include` tags send logs to Dynatrace.": "* Ресурсы Azure с тегами `Include` отправляют журналы в Dynatrace.",
    "* Azure resources with `Exclude` tags don't send logs to Dynatrace.": "* Ресурсы Azure с тегами `Exclude` не отправляют журналы в Dynatrace.",
    "* If there's a conflict between inclusion and exclusion rules, exclusion takes priority.": "* При конфликте правил включения и исключения приоритет имеют правила исключения.",
    "There is a limit of 20 entries for either `Include` or `Exclude` tags.": "Лимит записей для тегов `Include` и `Exclude` составляет по 20 штук.",
    "11. Select **Next: Single sign-on**.": "11. Нажмите **Next: Single sign-on**.",
    "12. Optional Choose whether to **Enable SSO through Microsoft Entra ID**.": "12. Необязательно: выберите, нужно ли включить **Enable SSO through Microsoft Entra ID**.",
    "* If you don't want to enable this feature, select **Next: Tags**.": "* Если эта функция не нужна, нажмите **Next: Tags**.",
    "* If you want to enable this feature, select it, select the Dynatrace application ID that is displayed, and then select **Next: Tags**.": "* Если нужно включить эту функцию, выберите её, укажите отображаемый идентификатор приложения Dynatrace, затем нажмите **Next: Tags**.",
    "13. Optional [Specify tags](#tags) for the new Dynatrace resource, and then select **Next: Review + create**.": "13. Необязательно: [укажите теги](#tags) для нового ресурса Dynatrace, затем нажмите **Next: Review + create**.",
    "14. Verify if the information submitted is correct, and then select **Create**. When the deployment is complete, you can select **Go to resource** to navigate to the specific Dynatrace resource.": "14. Проверьте правильность введённых данных, затем нажмите **Create**. После завершения развёртывания можно нажать **Go to resource** для перехода к конкретному ресурсу Dynatrace.",
    "## Link multiple Azure subscriptions to one Dynatrace environment Optional": "## Привязка нескольких подписок Azure к одной среде Dynatrace (необязательно)",
    "Ensure that your Azure account has access to the Dynatrace account with the following permissions:": "Убедитесь, что аккаунт Azure имеет доступ к аккаунту Dynatrace со следующими разрешениями:",
    "* View Account": "* Просмотр аккаунта (View Account)",
    "* View Environment": "* Просмотр среды (View Environment)",
    "* Install OneAgent": "* Установка OneAgent (Install OneAgent)",
    "* Manage Monitoring Settings": "* Управление параметрами мониторинга (Manage Monitoring Settings)",
    f'For more details, see [Environment permissions](/managed/manage/identity-access-management/permission-management/role-based-permissions#environment "Role-based permissions").': f'Подробнее см. в разделе [Разрешения среды](/managed/manage/identity-access-management/permission-management/role-based-permissions#environment "{TT_ENVPERM}").',
    "After deploying the Azure integration, you can:": "После развёртывания интеграции Azure можно:",
    "* Link more Azure subscriptions to your newly created Dynatrace environment.": "* Привязать дополнительные подписки Azure к только что созданной среде Dynatrace.",
    "* Link more Dynatrace environments to a single Azure subscription.": "* Привязать несколько сред Dynatrace к одной подписке Azure.",
    f'When linking multiple Azure subscriptions and creating the resource, you must have Dynatrace Account privileges `tenant-manage-settings` and `tenant-agent-install` permissions. For more information on how to configure these permissions, see [Role-based permissions](/managed/manage/identity-access-management/permission-management/role-based-permissions "Role-based permissions").': f'При привязке нескольких подписок Azure и создании ресурса необходимы привилегии аккаунта Dynatrace `tenant-manage-settings` и разрешения `tenant-agent-install`. Подробнее о настройке этих разрешений см. в разделе [Разрешения на основе ролей](/managed/manage/identity-access-management/permission-management/role-based-permissions "{TT_ROLEBASED}").',
    "Follow the steps below, making sure to repeat the procedure for every subscription that you want to link.": "Выполните приведённые ниже шаги, повторив процедуру для каждой подписки, которую нужно привязать.",
    "1. Go to Azure Portal and search for `Azure Native Dynatrace Service` from the top search bar.": "1. Откройте Azure Portal и найдите `Azure Native Dynatrace Service` через строку поиска вверху.",
    "2. Select **Azure Native Dynatrace Service**.": "2. Выберите **Azure Native Dynatrace Service**.",
    "3. Select **Create**.": "3. Нажмите **Create**.",
    "4. In **Basics**, for **Resource group**, specify whether to create a new resource group or use an existing one.": "4. В разделе **Basics** для поля **Resource group** укажите, нужно ли создать новую группу ресурсов или использовать существующую.",
    "5. Enter a **Resource name** and then select a **Region** from the dropdown menu.": "5. Введите **Resource name**, затем выберите **Region** из выпадающего меню.",
    "The Dynatrace environment to link and your new Dynatrace resource must be in the same region.": "Привязываемая среда Dynatrace и новый ресурс Dynatrace должны находиться в одном регионе.",
    "6. Select the **Dynatrace environment** to link to the Azure subscription, and then select **Next: Metrics and Logs**.": "6. Выберите **Dynatrace environment** для привязки к подписке Azure, затем нажмите **Next: Metrics and Logs**.",
    "7. Optional Select whether to **Send subscription activity logs** and/or **Send Azure resource logs**. For details, see [Configure metrics and logs](#metrics-logs).": "7. Необязательно: выберите, нужно ли включить **Send subscription activity logs** и/или **Send Azure resource logs**. Подробнее см. в разделе [Настройка метрик и журналов](#metrics-logs).",
    "If you select **Send Azure resource logs for all defined services**, Azure resource logs are sent for all defined resources by default, which means that logs are collected for all supported resources. To filter the specific set of Azure resources sending logs to Dynatrace, you can use Azure resource tags. Tag rules are:": "Если выбрать **Send Azure resource logs for all defined services**, журналы ресурсов Azure по умолчанию отправляются для всех определённых ресурсов, то есть журналы собираются для всех поддерживаемых ресурсов. Чтобы фильтровать конкретный набор ресурсов Azure, отправляющих журналы в Dynatrace, можно использовать теги ресурсов Azure. Правила тегов:",
    "8. Skip **Next: Single sign-on** (you can only configure SSO after deployment) and then select **Next: Tags**.": "8. Пропустите **Next: Single sign-on** (SSO можно настроить только после развёртывания) и нажмите **Next: Tags**.",
    "9. Optional [Specify tags](#tags) for the new Dynatrace resource, and then select **Next: Review + create**.": "9. Необязательно: [укажите теги](#tags) для нового ресурса Dynatrace, затем нажмите **Next: Review + create**.",
    "10. Verify if the information submitted is correct, and then select **Create**. When the deployment is complete, you can select **Go to resource** to navigate to the specific Dynatrace resource.": "10. Проверьте правильность введённых данных, затем нажмите **Create**. После завершения развёртывания можно нажать **Go to resource** для перехода к конкретному ресурсу Dynatrace.",
    "## Access your Dynatrace environment": "## Доступ к среде Dynatrace",
    "After you set up the integration, you can access your Dynatrace environment directly from Azure Portal.": "После настройки интеграции доступ к среде Dynatrace можно получить непосредственно из Azure Portal.",
    "In Azure Portal, go to your Dynatrace resource and select **Overview**. All details of your Dynatrace environment will appear there, including direct links to the following web UI pages:": "В Azure Portal перейдите к ресурсу Dynatrace и выберите **Overview**. Там отобразятся все сведения о среде Dynatrace, включая прямые ссылки на следующие страницы веб-интерфейса:",
    f'* **Dashboards** - For details, see [Dashboards](/managed/analyze-explore-automate/dashboards-classic "Learn how to create, manage, and use Dynatrace Dashboards Classic.").': f'* **Dashboards**: подробнее см. в разделе [Dashboards](/managed/analyze-explore-automate/dashboards-classic "{TT_DASHBOARDS}").',
    f'* **Log Viewer** - For details, see [Log viewer (Logs Classic)](/managed/analyze-explore-automate/log-monitoring/analyze-log-data/log-viewer "Learn how to use Dynatrace log viewer to analyze log data.").': f'* **Log Viewer**: подробнее см. в разделе [Log viewer (Logs Classic)](/managed/analyze-explore-automate/log-monitoring/analyze-log-data/log-viewer "{TT_LOGVIEWER}").',
    f'* **Smartscape topology** - For details, see [Visualize your environment through Smartscape](/managed/analyze-explore-automate/smartscape-classic "Learn how Smartscape visualizes all the entities and dependencies in your environment.").': f'* **Smartscape topology**: подробнее см. в разделе [Визуализация среды через Smartscape](/managed/analyze-explore-automate/smartscape-classic "{TT_SMARTSCAPE}").',
    "## Configure metrics and logs": "## Настройка метрик и журналов",
    "### Metrics": "### Метрики",
    f'* You can activate [metrics](/managed/analyze-explore-automate/metrics-classic "Learn about metrics classic that Dynatrace offers.") after the Azure integration deployment.': f'* Можно активировать [метрики](/managed/analyze-explore-automate/metrics-classic "{TT_METRICS}") после развёртывания интеграции Azure.',
    "Collect metrics from Virtual Machines and App Services": "Сбор метрик с Virtual Machines и App Services",
    "To start collecting metrics from your Virtual Machines and App Services, you need to [install Dynatrace OneAgent on these resources as an extension](#oa) .": "Чтобы начать сбор метрик с Virtual Machines и App Services, необходимо [установить Dynatrace OneAgent на этих ресурсах в качестве расширения](#oa).",
    "Collect metrics from cloud services": "Сбор метрик с облачных сервисов",
    "All services and metrics are enabled by default. You can disable them if needed by selecting the delete button from the list of services.": "Все сервисы и метрики включены по умолчанию. При необходимости их можно отключить, нажав кнопку удаления в списке сервисов.",
    f"After Dynatrace connects to your Azure environment, it immediately starts monitoring Azure's built-in services for the service principal you have defined. [Classic (formerly 'built-in') Azure metrics](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-monitoring-guide/default-azure-metrics \"The list of classic metrics Dynatrace collects by default for Azure monitoring.\") lists the metrics of Azure cloud services monitored by default.": f'После подключения Dynatrace к среде Azure немедленно начинается мониторинг встроенных сервисов Azure для определённого вами service principal. В разделе [Классические метрики Azure (ранее встроенные)](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-monitoring-guide/default-azure-metrics "{TT_DEFMETRICS}") приведён список метрик облачных сервисов Azure, собираемых по умолчанию.',
    "### Manage cloud services": "### Управление облачными сервисами",
    "All cloud services are monitored by default, but you can quickly disable them from the list or re-enable them as needed.": "Все облачные сервисы мониторятся по умолчанию, но их можно быстро отключить из списка или повторно включить при необходимости.",
    "To add services to monitoring": "Добавление сервисов в мониторинг",
    "1. Go to **Settings** > **Cloud and virtualization** > **Azure**.": "1. Откройте **Settings** > **Cloud and virtualization** > **Azure**.",
    '2. On the Azure overview page, find the connection that you want to change and select **Edit** ![Edit](https://dt-cdn.net/images/edit-icon-a083c62c49.svg "Edit") in that row.': '2. На странице обзора Azure найдите нужное подключение и нажмите **Edit** ![Edit](https://dt-cdn.net/images/edit-icon-a083c62c49.svg "Редактировать") в этой строке.',
    "3. Under **Services**, select **Manage services**.": "3. В разделе **Services** выберите **Manage services**.",
    "4. For each service that you want to add: select **Add service**, select the service from the list, and then select **Add service**.": "4. Для каждого сервиса, который нужно добавить: выберите **Add service**, выберите сервис из списка, затем снова нажмите **Add service**.",
    "5. Select **Save changes** to save your configuration.": "5. Нажмите **Save changes**, чтобы сохранить конфигурацию.",
    "Configuration of collected metrics per service": "Настройка собираемых метрик для каждого сервиса",
    "After you add a service, Dynatrace automatically starts collecting a set of metrics for that service.": "После добавления сервиса Dynatrace автоматически начинает собирать набор метрик для него.",
    "Recommended metrics:": "Рекомендуемые метрики:",
    "* Are enabled by default and can't be disabled.": "* Включены по умолчанию и не могут быть отключены.",
    "* Can come with recommended dimensions (enabled by default, can't be disabled) and optional dimensions (disabled by default, can be enabled).": "* Могут включать рекомендуемые измерения (включены по умолчанию, нельзя отключить) и необязательные измерения (отключены по умолчанию, можно включить).",
    "Apart from the recommended metrics, most services offer the possibility of enabling optional metrics that can be added and configured manually.": "Помимо рекомендуемых метрик, большинство сервисов позволяют включать необязательные метрики, которые можно добавлять и настраивать вручную.",
    "List of Azure cloud services and collected metrics": "Список облачных сервисов Azure и собираемых метрик",
    f'To see the complete list of Azure cloud services and learn about the metrics collected for each of them, see [All Azure cloud services](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-cloud-services-metrics "Monitor Azure services with Dynatrace and view available metrics.").': f'Полный список облачных сервисов Azure и сведения о собираемых метриках см. в разделе [Все облачные сервисы Azure](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-cloud-services-metrics "{TT_ALLSVC}").',
    "Alternatively, you can check the list of supported Azure services within in-product Dynatrace Hub (search for **Azure**) or in the [web version of Dynatrace Hub](https://www.dynatrace.com/hub/?query=azure).": "Также можно просмотреть список поддерживаемых сервисов Azure в Dynatrace Hub внутри продукта (поиск по **Azure**) или в [веб-версии Dynatrace Hub](https://www.dynatrace.com/hub/?query=azure).",
    "To add and configure metrics": "Добавление и настройка метрик",
    "4. Select the service for which you want to add metrics. The service details page lists the metrics you are already monitoring for that service.": "4. Выберите сервис, для которого нужно добавить метрики. На странице сведений о сервисе отображается список уже отслеживаемых метрик.",
    "5. Select **Add metric**.": "5. Нажмите **Add metric**.",
    "6. From the **Add new metric** list, select the metric and then select **Add metric**.": "6. В списке **Add new metric** выберите метрику, затем нажмите **Add metric**.",
    '7. Select ![Expand row](https://dt-cdn.net/images/expand-row-icon-9c4950fc2e.svg "Expand row") to expand the metric details and configure the metric.': '7. Нажмите ![Развернуть строку](https://dt-cdn.net/images/expand-row-icon-9c4950fc2e.svg "Развернуть строку"), чтобы раскрыть сведения о метрике и настроить её.',
    "8. Select **Apply** to save your configuration.": "8. Нажмите **Apply**, чтобы сохранить конфигурацию.",
    "After you select the cloud services and save your changes, monitoring of the newly added services starts automatically.": "После выбора облачных сервисов и сохранения изменений мониторинг вновь добавленных сервисов запускается автоматически.",
    "### Logs": "### Журналы",
    f'* You can activate [logs](/managed/analyze-explore-automate/log-monitoring "Learn how to enable Log Monitoring, the insights that Log Monitoring can provide, and more.") either [during the Azure integration deployment](#setup) or [after deployment](#how-to-logs).': f'* Можно активировать [журналы](/managed/analyze-explore-automate/log-monitoring "{TT_LOGMON}") [во время развёртывания интеграции Azure](#setup) или [после развёртывания](#how-to-logs).',
    "You can set up two types of logs from Azure to Dynatrace: [subscription activity logs](#activity) and [Azure resource logs](#resource).": "Можно настроить два типа журналов из Azure в Dynatrace: [журналы активности подписки](#activity) и [журналы ресурсов Azure](#resource).",
    "#### Subscription activity logs": "#### Журналы активности подписки",
    "Subscription activity logs provide insights into the operations (PUT, POST, DELETE) performed on each Azure resource in your subscription (the management plane). For each Azure subscription, there's a single activity log.": "Журналы активности подписки содержат сведения об операциях (PUT, POST, DELETE), выполняемых с каждым ресурсом Azure в подписке (плоскость управления). Для каждой подписки Azure существует один журнал активности.",
    "#### Azure resource logs": "#### Журналы ресурсов Azure",
    "Azure resource logs provide insights into operations that were performed within an Azure resource (the data plane), such as getting a secret from a key vault or making a request to a database. The content of resource logs varies by the Azure service and resource type.": "Журналы ресурсов Azure содержат сведения об операциях, выполняемых внутри ресурса Azure (плоскость данных), например получение секрета из хранилища ключей или запрос к базе данных. Содержимое журналов ресурсов зависит от сервиса Azure и типа ресурса.",
    "All Azure services in the [Azure Monitor log categories](https://dt-url.net/fja38sr) ingest logs, including Microsoft Entra ID and [Azure Monitor Integration Service](https://dt-url.net/dpc38am).": "Все сервисы Azure из [категорий журналов Azure Monitor](https://dt-url.net/fja38sr) принимают журналы, включая Microsoft Entra ID и [Azure Monitor Integration Service](https://dt-url.net/dpc38am).",
    "For a list of Azure resource logs, see [Supported categories for Azure Monitor resource logs](https://dt-url.net/ea03xvn).": "Список журналов ресурсов Azure см. в разделе [Поддерживаемые категории журналов ресурсов Azure Monitor](https://dt-url.net/ea03xvn).",
    "#### How to activate logs after deployment": "#### Активация журналов после развёртывания",
    "Activate subscription activity logs": "Активация журналов активности подписки",
    "Activate Azure resource logs": "Активация журналов ресурсов Azure",
    "1. On the Azure Portal, go to your Dynatrace resource and select **Metrics and logs**.": "1. На Azure Portal перейдите к ресурсу Dynatrace и выберите **Metrics and logs**.",
    "2. Select **Send subscription activity logs**.": "2. Выберите **Send subscription activity logs**.",
    "3. Select **Save**.": "3. Нажмите **Save**.",
    "2. Select **Send Azure resource logs for all defined sources**.": "2. Выберите **Send Azure resource logs for all defined sources**.",
    "When selecting this option, Azure resource logs are sent for all defined resources by default, which means that logs are collected for all supported resources.": "При выборе этого параметра журналы ресурсов Azure по умолчанию отправляются для всех определённых ресурсов, то есть журналы собираются для всех поддерживаемых ресурсов.",
    "3. Optional If you want to filter the specific set of Azure resources sending logs to Dynatrace, you can use Azure resource tags. Tag rules are:": "3. Необязательно: чтобы фильтровать конкретный набор ресурсов Azure, отправляющих журналы в Dynatrace, можно использовать теги ресурсов Azure. Правила тегов:",
    "4. Select **Save**.": "4. Нажмите **Save**.",
    "Azure Native Dynatrace Service automatically enables log forwarding in the Azure subscription where the Dynatrace resource is enabled. Log forwarding is enabled for all supported services and resources. Tag filtering rules can be defined to include or exclude certain Azure resources from sending logs.": "Azure Native Dynatrace Service автоматически включает log forwarding в подписке Azure, в которой включён ресурс Dynatrace. Log forwarding включается для всех поддерживаемых сервисов и ресурсов. Можно определить правила фильтрации по тегам для включения или исключения определённых ресурсов Azure из отправки журналов.",
    "Azure Native Dynatrace Service uses Dynatrace access token called `azure-native-integration` which is rotated every 24 hours.": "Azure Native Dynatrace Service использует токен доступа Dynatrace с именем `azure-native-integration`, ротация которого выполняется каждые 24 часа.",
    "## Create tags": "## Создание тегов",
    f'* You can create [tags](/managed/manage/tags-and-metadata/setup/how-to-define-tags "Find out how to define and apply tags manually and automatically.") either [during the Azure integration deployment](#setup) or [after deployment](#how-to-tags).': f'* Можно создавать [теги](/managed/manage/tags-and-metadata/setup/how-to-define-tags "{TT_TAGS}") [во время развёртывания интеграции Azure](#setup) или [после развёртывания](#how-to-tags).',
    "You can apply tags to your Azure resources, resource groups, and subscriptions to logically organize them into a taxonomy. You can specify tags for the new Dynatrace resource in Azure by adding custom key/value pairs:": "Теги можно применять к ресурсам Azure, группам ресурсов и подпискам для логической организации их в таксономию. Можно указать теги для нового ресурса Dynatrace в Azure, добавив пользовательские пары ключ/значение:",
    "* For **Name**, enter the name of the tag corresponding to the Azure Dynatrace resource (for example, `owner`).": "* В поле **Name** введите имя тега, соответствующего ресурсу Azure Dynatrace (например, `owner`).",
    "* For **Value**, enter the value of the tag corresponding to the Azure Dynatrace resource (for example, the owner's email account).": "* В поле **Value** введите значение тега, соответствующего ресурсу Azure Dynatrace (например, адрес электронной почты владельца).",
    "If you don't set any tags, all logs from the monitored resources on your Azure subscription are sent to Dynatrace.": "Если теги не заданы, все журналы с отслеживаемых ресурсов подписки Azure отправляются в Dynatrace.",
    "### How to create tags after deployment": "### Создание тегов после развёртывания",
    "On the Azure Portal, go to your new Dynatrace resource, and then select **Tags**. Alternatively, you can select **Monitored resources**, and then select **Edit tags** for the desired resources.": "На Azure Portal перейдите к новому ресурсу Dynatrace и выберите **Tags**. Также можно выбрать **Monitored resources**, затем нажать **Edit tags** для нужных ресурсов.",
    "## Manage monitored resources in Azure Portal": "## Управление отслеживаемыми ресурсами в Azure Portal",
    "After deploying the Azure Native Dynatrace Service, you can view, manage, and monitor your Azure resources, and you can install OneAgent on your Azure Virtual Machines and Azure App Services.": "После развёртывания Azure Native Dynatrace Service можно просматривать, управлять и отслеживать ресурсы Azure, а также устанавливать OneAgent на Azure Virtual Machines и Azure App Services.",
    "To view your list of resources, on the Azure Portal, go to your Dynatrace resource and select **Monitored resources**. You can filter the list of resources displayed by **Resource name** (Azure resource name), **Resource type** (Azure resource type), **Resource group** (resource group name for the Azure resource), **Region** (location of the Azure resource), and **Logs to Dynatrace** (whether the resource is sending logs to Dynatrace).": "Чтобы просмотреть список ресурсов, на Azure Portal перейдите к ресурсу Dynatrace и выберите **Monitored resources**. Список можно фильтровать по: **Resource name** (имя ресурса Azure), **Resource type** (тип ресурса Azure), **Resource group** (имя группы ресурсов для ресурса Azure), **Region** (расположение ресурса Azure) и **Logs to Dynatrace** (отправляет ли ресурс журналы в Dynatrace).",
    "## Deploy OneAgent on Azure Virtual Machines and Azure App Services": "## Развёртывание OneAgent на Azure Virtual Machines и Azure App Services",
    "* You can deploy OneAgent after the Azure integration deployment.": "* OneAgent можно развернуть после развёртывания интеграции Azure.",
    "To monitor your Azure Virtual Machines or Azure App Services, you can install Dynatrace OneAgent on these resources as an extension.": "Для мониторинга Azure Virtual Machines или Azure App Services можно установить Dynatrace OneAgent на этих ресурсах в качестве расширения.",
    "Install OneAgent on Virtual Machine": "Установка OneAgent на виртуальную машину",
    "Install OneAgent on App Service": "Установка OneAgent на App Service",
    "1. On the Azure Portal, go to your Dynatrace resource and select **Virtual Machines**.": "1. На Azure Portal перейдите к ресурсу Dynatrace и выберите **Virtual Machines**.",
    "2. Select a Virtual Machine from the list, on which you want to install the OneAgent extension.": "2. Выберите виртуальную машину из списка, на которой нужно установить расширение OneAgent.",
    "3. Select **Install extension**.": "3. Нажмите **Install extension**.",
    "4. Optional Select whether to enable log analytics.": "4. Необязательно: выберите, нужно ли включить аналитику журналов.",
    f'5. Optional Provide a [host group](/managed/observe/infrastructure-observability/hosts/configuration/organize-your-environment-using-host-groups "Find out how Dynatrace enables you to organize your hosts, processes, and services using host groups.") for OneAgent.': f'5. Необязательно: укажите [группу хостов](/managed/observe/infrastructure-observability/hosts/configuration/organize-your-environment-using-host-groups "{TT_HOSTGROUP}") для OneAgent.',
    "6. Select **OK** to start the installation process.": "6. Нажмите **OK**, чтобы начать процесс установки.",
    "7. When the installation is complete, the **OneAgent status** for the selected Virtual Machine displays **Installed**.": "7. После завершения установки в поле **OneAgent status** для выбранной виртуальной машины отобразится **Installed**.",
    "* To see details about the installed OneAgent, select your Virtual Machine and go to **Extensions**.": "* Чтобы просмотреть сведения об установленном OneAgent, выберите виртуальную машину и перейдите в раздел **Extensions**.",
    "* To uninstall OneAgent, select your Virtual Machine, and then select **Uninstall extension**.": "* Чтобы удалить OneAgent, выберите виртуальную машину, затем нажмите **Uninstall extension**.",
    "1. On the Azure Portal, go to your Dynatrace resource and select **App Services**.": "1. На Azure Portal перейдите к ресурсу Dynatrace и выберите **App Services**.",
    "2. From the list, select the App Service on which you want to install the OneAgent extension.": "2. Из списка выберите App Service, на котором нужно установить расширение OneAgent.",
    "7. When the installation is complete, the **OneAgent status** for the selected Virtual Machine displays **Installed**.": "7. После завершения установки в поле **OneAgent status** для выбранного App Service отобразится **Installed**.",
    "* To see details about the installed OneAgent, select your App Service and go to **Extensions**.": "* Чтобы просмотреть сведения об установленном OneAgent, выберите App Service и перейдите в раздел **Extensions**.",
    "* To uninstall OneAgent, select your App Service, and then select **Uninstall extension**.": "* Чтобы удалить OneAgent, выберите App Service, затем нажмите **Uninstall extension**.",
    "If you cannot see the App Service in Dynatrace after enabling the integration, restart your App Service plan.": "Если App Service не отображается в Dynatrace после включения интеграции, перезапустите App Service Plan.",
    f'To run OneAgent on Virtual Machine Scale Sets with Dynatrace Azure integration, use the [Dynatrace OneAgent extension for Virtual Machines](#vm) and create a [PaaS token](/managed/manage/identity-access-management/access-tokens-and-oauth-clients/access-tokens#paas-token "Learn the concept of an access token and its scopes.").': f'Чтобы запустить OneAgent на Virtual Machine Scale Sets с интеграцией Dynatrace Azure, используйте [расширение Dynatrace OneAgent для Virtual Machines](#vm) и создайте [PaaS token](/managed/manage/identity-access-management/access-tokens-and-oauth-clients/access-tokens#paas-token "{TT_PAAS}").',
    "## Uninstall the Azure Native Dynatrace Service": "## Удаление Azure Native Dynatrace Service",
    "To uninstall the Azure Native Dynatrace Service, you need to delete the Dynatrace resource. When the Dynatrace resource is deleted from Azure, logs and metrics are no longer sent to Dynatrace and all billing for Dynatrace through Azure Marketplace stops.": "Чтобы удалить Azure Native Dynatrace Service, необходимо удалить ресурс Dynatrace. После удаления ресурса Dynatrace из Azure журналы и метрики перестают отправляться в Dynatrace, а все расчёты за Dynatrace через Azure Marketplace прекращаются.",
    "To delete the Dynatrace resource": "Удаление ресурса Dynatrace",
    "1. On the Azure Portal, go to your Dynatrace resource and select **Overview**.": "1. На Azure Portal перейдите к ресурсу Dynatrace и выберите **Overview**.",
    "2. Select **Delete**.": "2. Нажмите **Delete**.",
    "3. Enter the name of the application you want to delete, then select **Delete**.": "3. Введите имя приложения, которое нужно удалить, затем нажмите **Delete**.",
    "## How to request new features": "## Как запросить новые функции",
    "If you have a feature request, use the [Microsoft Developer Community](https://dt-url.net/po239hy) to suggest new features.": "Чтобы предложить новую функцию, воспользуйтесь [Microsoft Developer Community](https://dt-url.net/po239hy).",
    "## Troubleshooting": "## Устранение неполадок",
    "* [I can't enable SSO integration](https://dt-url.net/tq237c7)": "* [Не удаётся включить интеграцию SSO](https://dt-url.net/tq237c7)",
    "* [I don't have permissions to configure SSO for a linked Dynatrace environment](https://dt-url.net/3o038vp)": "* [Нет разрешений для настройки SSO для связанной среды Dynatrace](https://dt-url.net/3o038vp)",
    "* [How can I get logs from an Azure subscription in another Azure tenant?](https://dt-url.net/4rc37kk)": "* [Как получить журналы из подписки Azure в другом тенанте Azure?](https://dt-url.net/4rc37kk)",
    "* [Azure resources not forwarding logs to Dynatrace](https://dt-url.net/il438i2)": "* [Ресурсы Azure не пересылают журналы в Dynatrace](https://dt-url.net/il438i2)",
    "## Log ingest FAQ": "## Вопросы и ответы по приёму журналов",
    "* [What are the limits for Azure Native Dynatrace Service log ingest?](https://dt-url.net/ine37te)": "* [Какие ограничения существуют для приёма журналов в Azure Native Dynatrace Service?](https://dt-url.net/ine37te)",
    "* [How does the Azure Native Dynatrace Service logging impact Azure costs?](https://dt-url.net/da2380g)": "* [Как ведение журналов Azure Native Dynatrace Service влияет на стоимость Azure?](https://dt-url.net/da2380g)",
    "* [Isn't it cheaper to send data with the existing Dynatrace Azure log forwarding to Dynatrace SaaS in AWS rather than to use Azure Native Dynatrace Service?](https://dt-url.net/bp038gb)": "* [Разве не дешевле отправлять данные с помощью существующего log forwarding Dynatrace Azure в Dynatrace SaaS в AWS, а не использовать Azure Native Dynatrace Service?](https://dt-url.net/bp038gb)",
    "## Related topics": "## Связанные темы",
    f'* [Microsoft Azure Integrations](/managed/ingest-from/microsoft-azure-services/azure-integrations "Set up Dynatrace deep code monitoring on Azure using OneAgent or OpenTelemetry.")': f'* [Интеграции с Microsoft Azure](/managed/ingest-from/microsoft-azure-services/azure-integrations "{TT_AZURE_INTEGRATIONS}")',
}

PASS = set()

if __name__ == "__main__":
    build_one(REL, "azure-native-integration.md", TRANS, PASS)
    qa_one(REL, "azure-native-integration.md")
