# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/google-cloud-platform/gcp-integrations/gcp-functions"

TRANS = {
    "title: Integrate on Google Cloud Functions .NET": "title: Интеграция на Google Cloud Functions .NET",
    "# Integrate on Google Cloud Functions .NET": "# Интеграция на Google Cloud Functions .NET",
    "* How-to guide": "* Практическое руководство",
    "* 3-min read": "* Чтение: 3 мин",
    "* Published Jul 25, 2023": "* Опубликовано 25 июля 2023 г.",
    "The `Dynatrace.OpenTelemetry.Instrumentation.GoogleCloudFunctions` NuGet package provides APIs for tracing server-side .NET Google Cloud Function (GCF) invocations.": "Пакет NuGet `Dynatrace.OpenTelemetry.Instrumentation.GoogleCloudFunctions` предоставляет API для трассировки серверных вызовов .NET Google Cloud Function (GCF).",
    "## Prerequisites": "## Предварительные требования",
    "* [Set up OpenTelemetry monitoring for Google Cloud Functions](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf \"Monitor Google Cloud Functions with OpenTelemetry and Dynatrace.\").": "* [Настройка мониторинга OpenTelemetry для Google Cloud Functions](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf \"Мониторинг Google Cloud Functions с OpenTelemetry и Dynatrace.\").",
    "* Dynatrace.OpenTelemetry.Instrumentation.GoogleCloudFunctions version 1.273+": "* Dynatrace.OpenTelemetry.Instrumentation.GoogleCloudFunctions версии 1.273+",
    "* Cloud Functions product versions: 1st gen, 2nd gen": "* Версии продукта Cloud Functions: 1st gen, 2nd gen",
    "## Installation": "## Установка",
    "To set up OpenTelemetry .NET integration on Google Cloud Functions, run the command below in the root directory of your Google Cloud Function project.": "Чтобы настроить интеграцию OpenTelemetry для .NET на Google Cloud Functions, выполните следующую команду в корневой директории проекта Google Cloud Function.",
    "This adds the latest version of the `Dynatrace.OpenTelemetry.Instrumentation.GoogleCloudFunctions` NuGet package as a dependency on your project.": "Это добавляет последнюю версию пакета NuGet `Dynatrace.OpenTelemetry.Instrumentation.GoogleCloudFunctions` как зависимость проекта.",
    "## Trace export": "## Экспорт трассировок",
    "[![Step 1](https://dt-cdn.net/images/step-1-086e22066c.svg \"Step 1\")": "[![Шаг 1](https://dt-cdn.net/images/step-1-086e22066c.svg \"Шаг 1\")",
    "**Initialize tracing**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-dotnet#initialize \"Monitor Google Cloud Functions with OpenTelemetry for .NET and Dynatrace.\")[![Step 2](https://dt-cdn.net/images/step-2-1a1384627e.svg \"Step 2\")": "**Инициализация трассировки**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-dotnet#initialize \"Мониторинг Google Cloud Functions с OpenTelemetry для .NET и Dynatrace.\")[![Шаг 2](https://dt-cdn.net/images/step-2-1a1384627e.svg \"Шаг 2\")",
    "**Instrument a handler function**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-dotnet#instrument \"Monitor Google Cloud Functions with OpenTelemetry for .NET and Dynatrace.\")": "**Инструментирование функции-обработчика**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf-dotnet#instrument \"Мониторинг Google Cloud Functions с OpenTelemetry для .NET и Dynatrace.\")",
    "## Step 1 Initialize tracing": "## Шаг 1 Инициализация трассировки",
    "The initialization code for GCF tracing in your `Function.cs` file could look as follows (where `Function` is the configured GCF handler class):": "Код инициализации трассировки GCF в файле `Function.cs` может выглядеть следующим образом (где `Function` является настроенным классом-обработчиком GCF):",
    "## Step 2 Instrument a handler function": "## Шаг 2 Инструментирование функции-обработчика",
    "Dynatrace.OpenTelemetry.Instrumentation.GoogleCloudFunctions version 1.273 Only tracing of incoming calls for HTTP-triggered functions is supported.": "Dynatrace.OpenTelemetry.Instrumentation.GoogleCloudFunctions версии 1.273 Поддерживается только трассировка входящих вызовов для HTTP-функций.",
    "To instrument an HTTP-triggered function to trace incoming calls, in addition to the [initialization code above](#initialization), wrap the GCF function handler method using either `GoogleCloudFunctionsWrapper.Trace` or `GoogleCloudFunctionsWrapper.TraceAsync` as shown in the following example.": "Для инструментирования HTTP-функции с целью трассировки входящих вызовов, в дополнение к [коду инициализации выше](#initialization), оберните метод-обработчик функции GCF с помощью `GoogleCloudFunctionsWrapper.Trace` или `GoogleCloudFunctionsWrapper.TraceAsync`, как показано в следующем примере.",
    "## Cold start": "## Холодный старт",
    "When the function handler is invoked for the first time after a [cold start](https://cloud.google.com/functions/docs/concepts/exec#cold_starts), the instrumentation initialization method `AddGoogleCloudFunctionsInstrumentation`": "При первом вызове обработчика функции после [холодного старта](https://cloud.google.com/functions/docs/concepts/exec#cold_starts) метод инициализации инструментирования `AddGoogleCloudFunctionsInstrumentation`",
    "makes additional HTTP requests to fetch metadata from your [Google Cloud environment](https://cloud.google.com/compute/docs/metadata/overview). This metadata is used to set the required attributes for Dynatrace to process": "выполняет дополнительные HTTP-запросы для получения метаданных из [среды Google Cloud](https://cloud.google.com/compute/docs/metadata/overview). Эти метаданные используются для задания необходимых атрибутов, по которым Dynatrace обрабатывает",
    "the span (\"Activity\" in .NET terminology).": "спан (\"Activity\" в терминологии .NET).",
    "### Limitations": "### Ограничения",
    "The additional HTTP requests from `AddGoogleCloudFunctionsInstrumentation` method might cause unhandled exceptions during the initialization phase (for example, `HttpRequestException` in the case of a broken network connection). If your code is set to avoid monitoring when startup fails, exceptions will still be caught.": "Дополнительные HTTP-запросы метода `AddGoogleCloudFunctionsInstrumentation` могут вызвать необработанные исключения на этапе инициализации (например, `HttpRequestException` при нарушении сетевого соединения). Если в коде предусмотрено отключение мониторинга при сбое запуска, исключения всё равно будут перехвачены.",
    "## Span flush": "## Сброс спанов",
    "By default, all wrapping `Trace/TraceAsync` methods automatically perform a flush operation before the end of function invocation to ensure that all spans are exported properly. Because span flushing becomes part of the function's execution logic, it might result in a longer execution time.": "По умолчанию все оборачивающие методы `Trace/TraceAsync` автоматически выполняют операцию сброса перед завершением вызова функции для корректного экспорта всех спанов. Поскольку сброс спанов становится частью логики выполнения функции, это может увеличить время выполнения.",
    "To disable flushing after every invocation, you can provide a configuration parameter with the flag `ForceFlushAfterEachInvocation` set to `false` in the `AddGoogleCloudFunctionsInstrumentation` method. Spans will still be periodically exported in the background.": "Чтобы отключить сброс после каждого вызова, передайте параметр конфигурации с флагом `ForceFlushAfterEachInvocation`, равным `false`, в метод `AddGoogleCloudFunctionsInstrumentation`. Спаны по-прежнему будут периодически экспортироваться в фоновом режиме.",
    "Because code running outside the function execution can be terminated at any time, it's discouraged by Google Cloud Functions.": "Поскольку код, выполняемый вне контекста функции, может быть завершён в любой момент, Google Cloud Functions не рекомендует такой подход.",
    "* Google Cloud Functions 1st gen": "* Google Cloud Functions 1st gen",
    "Background task execution after function invocation is not guaranteed without flushing spans and might result in span loss. In practice, samples have shown that not explicitly flushing spans usually still results in correctly exported spans.": "Выполнение фоновых задач после вызова функции без сброса спанов не гарантировано и может привести к потере спанов. Практика показывает, что в большинстве случаев спаны корректно экспортируются даже без явного сброса.",
    "* Google Cloud Functions 2nd gen": "* Google Cloud Functions 2nd gen",
    "Google Cloud Functions 2nd gen can handle multiple concurrent requests in a single function instance. The flush operation of one invocation can prolong the execution time of another function invocation.": "Google Cloud Functions 2nd gen поддерживает обработку нескольких одновременных запросов в рамках одного экземпляра функции. Операция сброса одного вызова может увеличить время выполнения другого.",
    "Because function instances usually need to be kept idle for some time to handle multiple concurrent requests, you can disable the flushing of spans to improve performance. For details, see [Instance lifecycle](https://cloud.google.com/run/docs/container-contract#lifecycle-services).": "Так как экземпляры функции обычно должны оставаться в режиме ожидания для обработки параллельных запросов, можно отключить сброс спанов для повышения производительности. Подробнее см. [Instance lifecycle](https://cloud.google.com/run/docs/container-contract#lifecycle-services).",
    "Note that idle function instances are not guaranteed to be allocated CPU unless their [CPU allocation](https://cloud.google.com/run/docs/configuring/cpu-allocation) mode is set to `CPU always allocated`.": "Обратите внимание: простаивающим экземплярам функции не гарантируется выделение CPU, если режим [CPU allocation](https://cloud.google.com/run/docs/configuring/cpu-allocation) не установлен в `CPU always allocated`.",
    "For details, see [Function execution timeline](https://cloud.google.com/functions/docs/concepts/execution-environment#execution-timeline).": "Подробнее см. [Function execution timeline](https://cloud.google.com/functions/docs/concepts/execution-environment#execution-timeline).",
    "## Dynatrace overhead": "## Накладные расходы Dynatrace",
    "* Because span export and metadata fetch take some time during cold starts, they increase the duration of the function and subsequently increase costs.": "* Экспорт спанов и получение метаданных при холодных стартах занимают время, увеличивая продолжительность выполнения функции и соответственно затраты.",
    "* Pay attention to infrequently invoked functions (usually with cold starts), which might require more time for the TCP handshake during span export.": "* Обратите особое внимание на редко вызываемые функции (как правило, с холодными стартами): они могут требовать больше времени на TCP-рукопожатие при экспорте спанов.",
    "* Any network problem between the exporter and Dynatrace backend might also lead to unexpectedly high overhead.": "* Любые сетевые проблемы между экспортером и бэкендом Dynatrace также могут привести к неожиданно высоким накладным расходам.",
    "## Related topics": "## Связанные темы",
    "* [Set up Dynatrace on Google Cloud](/managed/ingest-from/google-cloud-platform \"Monitor Google Cloud with Dynatrace.\")": "* [Настройка Dynatrace в Google Cloud](/managed/ingest-from/google-cloud-platform \"Мониторинг Google Cloud с Dynatrace.\")",
    "* [Google Cloud monitoring](https://www.dynatrace.com/technologies/google-cloud-monitoring/)": "* [Google Cloud monitoring](https://www.dynatrace.com/technologies/google-cloud-monitoring/)",
}

PASS = set()

build_one(REL, "opentelemetry-on-gcf-dotnet.md", TRANS, PASS)
qa_one(REL, "opentelemetry-on-gcf-dotnet.md")
