# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/cloudwatch-ec2"

TRANS = {
    "title: Amazon EC2 Auto Scaling": "title: Amazon EC2 Auto Scaling",
    "# Amazon EC2 Auto Scaling": "# Amazon EC2 Auto Scaling",
    "* How-to guide": "* Практическое руководство",
    "* 1-min read": "* Чтение: 1 мин",
    "* Updated on Nov 15, 2023": "* Обновлено 15 ноября 2023 г.",
    "For information about differences between classic services and other services, see [Migrate from AWS classic (formerly 'built-in') services to cloud services](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/aws-migration-guide \"Migrate AWS classic services to their new versions.\").": "Сведения о различиях между классическими сервисами и другими сервисами см. в разделе [Миграция с классических сервисов AWS (ранее «встроенных») на облачные сервисы](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/aws-migration-guide \"Миграция классических сервисов AWS на новые версии.\").",
    "Dynatrace ingests metrics for multiple preselected namespaces, including Amazon EC2 Auto Scaling. You can view metrics for each service instance, split metrics into multiple dimensions, and create custom charts that you can pin to your dashboards.": "Dynatrace собирает метрики для множества предварительно выбранных пространств имён, включая Amazon EC2 Auto Scaling. Можно просматривать метрики для каждого экземпляра сервиса, разделять метрики по нескольким измерениям и создавать пользовательские диаграммы, которые можно закрепить на дашбордах.",
    "## Prerequisites": "## Предварительные требования",
    "To enable monitoring for this service, you need": "Для включения мониторинга этого сервиса необходимо",
    "* ActiveGate version 1.197+": "* ActiveGate версии 1.197+",
    "* For Dynatrace Managed deployments, you can use any kind of ActiveGate.": "* Для развёртываний Dynatrace Managed можно использовать любой тип ActiveGate.",
    "For role-based access in [Managed](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#role-based-access \"Connect your Amazon account with Dynatrace Managed and start monitoring.\") deployment, you need an [Environment ActiveGate](/managed/ingest-from/dynatrace-activegate/installation \"Learn how to configure ActiveGate\") installed on an Amazon EC2 host.": "Для доступа на основе ролей в развёртывании [Managed](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#role-based-access \"Подключение аккаунта Amazon к Dynatrace Managed и начало мониторинга.\") требуется [Environment ActiveGate](/managed/ingest-from/dynatrace-activegate/installation \"Узнайте, как настроить ActiveGate\"), установленный на хосте Amazon EC2.",
    "* Dynatrace version 1.200+": "* Dynatrace версии 1.200+",
    "* An updated [AWS monitoring policy](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics#monitoring-policy \"Integrate metrics from Amazon CloudWatch.\") to include the additional AWS services.": "* Обновлённая [политика мониторинга AWS](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics#monitoring-policy \"Интеграция метрик из Amazon CloudWatch.\") для включения дополнительных сервисов AWS.",
    "To [update the AWS IAM policy﻿](https://dt-url.net/8q038eb), use the JSON below, containing the monitoring policy (permissions) for all supporting services.": "Чтобы [обновить политику AWS IAM﻿](https://dt-url.net/8q038eb), используйте приведённый ниже JSON, содержащий политику мониторинга (разрешения) для всех поддерживаемых сервисов.",
    "JSON predefined policy for all supporting services": "Предопределённая JSON-политика для всех поддерживаемых сервисов",
    "If you don't want to add permissions to all services, and just select permissions for certain services, consult the table below. The table contains a set of permissions that are required for [All AWS cloud services](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Monitor all AWS cloud services with Dynatrace and view available metrics.\") and, for each supporting service, a list of optional permissions specific to that service.": "Если не нужно добавлять разрешения для всех сервисов, а только для определённых, обратитесь к таблице ниже. Таблица содержит набор разрешений, необходимых для [всех облачных сервисов AWS](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Мониторинг всех облачных сервисов AWS с Dynatrace и просмотр доступных метрик.\"), а для каждого поддерживаемого сервиса приводится список необязательных разрешений, специфичных для этого сервиса.",
    "Permissions required for AWS monitoring integration:": "Разрешения, необходимые для интеграции мониторинга AWS:",
    "### Complete list of permissions for cloud services": "### Полный список разрешений для облачных сервисов",
    "| Name | Permissions |": "| Название | Разрешения |",
    "| --- | --- |": "| --- | --- |",
    "| All monitored Amazon services Required | `cloudwatch:GetMetricData`, `cloudwatch:GetMetricStatistics`, `cloudwatch:ListMetrics`, `sts:GetCallerIdentity`, `tag:GetResources`, `tag:GetTagKeys`, `ec2:DescribeAvailabilityZones` |": "| Все мониторируемые сервисы Amazon (обязательные) | `cloudwatch:GetMetricData`, `cloudwatch:GetMetricStatistics`, `cloudwatch:ListMetrics`, `sts:GetCallerIdentity`, `tag:GetResources`, `tag:GetTagKeys`, `ec2:DescribeAvailabilityZones` |",
    "| AWS Certificate Manager Private Certificate Authority | `acm-pca:ListCertificateAuthorities` |": "| AWS Certificate Manager Private Certificate Authority | `acm-pca:ListCertificateAuthorities` |",
    "| Amazon MQ |  |": "| Amazon MQ |  |",
    "| Amazon API Gateway | `apigateway:GET` |": "| Amazon API Gateway | `apigateway:GET` |",
    "| AWS App Runner | `apprunner:ListServices` |": "| AWS App Runner | `apprunner:ListServices` |",
    "| Amazon AppStream | `appstream:DescribeFleets` |": "| Amazon AppStream | `appstream:DescribeFleets` |",
    "| AWS AppSync | `appsync:ListGraphqlApis` |": "| AWS AppSync | `appsync:ListGraphqlApis` |",
    "| Amazon Athena | `athena:ListWorkGroups` |": "| Amazon Athena | `athena:ListWorkGroups` |",
    "| Amazon Aurora | `rds:DescribeDBClusters` |": "| Amazon Aurora | `rds:DescribeDBClusters` |",
    "| Amazon EC2 Auto Scaling | `autoscaling:DescribeAutoScalingGroups` |": "| Amazon EC2 Auto Scaling | `autoscaling:DescribeAutoScalingGroups` |",
    "| Amazon EC2 Auto Scaling (built-in) | `autoscaling:DescribeAutoScalingGroups` |": "| Amazon EC2 Auto Scaling (встроенный) | `autoscaling:DescribeAutoScalingGroups` |",
    "| AWS Billing |  |": "| AWS Billing |  |",
    "| Amazon Keyspaces |  |": "| Amazon Keyspaces |  |",
    "| AWS Chatbot |  |": "| AWS Chatbot |  |",
    "| Amazon CloudFront | `cloudfront:ListDistributions` |": "| Amazon CloudFront | `cloudfront:ListDistributions` |",
    "| AWS CloudHSM | `cloudhsm:DescribeClusters` |": "| AWS CloudHSM | `cloudhsm:DescribeClusters` |",
    "| Amazon CloudSearch | `cloudsearch:DescribeDomains` |": "| Amazon CloudSearch | `cloudsearch:DescribeDomains` |",
    "| AWS CodeBuild | `codebuild:ListProjects` |": "| AWS CodeBuild | `codebuild:ListProjects` |",
    "| Amazon Cognito |  |": "| Amazon Cognito |  |",
    "| Amazon Connect |  |": "| Amazon Connect |  |",
    "| Amazon Elastic Kubernetes Service (EKS) | `eks:ListClusters` |": "| Amazon Elastic Kubernetes Service (EKS) | `eks:ListClusters` |",
    "| AWS DataSync | `datasync:ListTasks` |": "| AWS DataSync | `datasync:ListTasks` |",
    "| Amazon DynamoDB Accelerator (DAX) | `dax:DescribeClusters` |": "| Amazon DynamoDB Accelerator (DAX) | `dax:DescribeClusters` |",
    "| AWS Database Migration Service (AWS DMS) | `dms:DescribeReplicationInstances` |": "| AWS Database Migration Service (AWS DMS) | `dms:DescribeReplicationInstances` |",
    "| Amazon DocumentDB | `rds:DescribeDBClusters` |": "| Amazon DocumentDB | `rds:DescribeDBClusters` |",
    "| AWS Direct Connect | `directconnect:DescribeConnections` |": "| AWS Direct Connect | `directconnect:DescribeConnections` |",
    "| Amazon DynamoDB | `dynamodb:ListTables` |": "| Amazon DynamoDB | `dynamodb:ListTables` |",
    "| Amazon DynamoDB (built-in) | `dynamodb:ListTables`, `dynamodb:ListTagsOfResource` |": "| Amazon DynamoDB (встроенный) | `dynamodb:ListTables`, `dynamodb:ListTagsOfResource` |",
    "| Amazon EBS | `ec2:DescribeVolumes` |": "| Amazon EBS | `ec2:DescribeVolumes` |",
    "| Amazon EBS (built-in) | `ec2:DescribeVolumes` |": "| Amazon EBS (встроенный) | `ec2:DescribeVolumes` |",
    "| Amazon EC2 API |  |": "| Amazon EC2 API |  |",
    "| Amazon EC2 (built-in) | `ec2:DescribeInstances` |": "| Amazon EC2 (встроенный) | `ec2:DescribeInstances` |",
    "| Amazon EC2 Spot Fleet | `ec2:DescribeSpotFleetRequests` |": "| Amazon EC2 Spot Fleet | `ec2:DescribeSpotFleetRequests` |",
    "| Amazon Elastic Container Service (ECS) | `ecs:ListClusters` |": "| Amazon Elastic Container Service (ECS) | `ecs:ListClusters` |",
    "| Amazon ECS Container Insights | `ecs:ListClusters` |": "| Amazon ECS Container Insights | `ecs:ListClusters` |",
    "| Amazon ElastiCache (EC) | `elasticache:DescribeCacheClusters` |": "| Amazon ElastiCache (EC) | `elasticache:DescribeCacheClusters` |",
    "| AWS Elastic Beanstalk | `elasticbeanstalk:DescribeEnvironments` |": "| AWS Elastic Beanstalk | `elasticbeanstalk:DescribeEnvironments` |",
    "| Amazon Elastic File System (EFS) | `elasticfilesystem:DescribeFileSystems` |": "| Amazon Elastic File System (EFS) | `elasticfilesystem:DescribeFileSystems` |",
    "| Amazon Elastic Inference |  |": "| Amazon Elastic Inference |  |",
    "| Amazon Elastic Map Reduce (EMR) | `elasticmapreduce:ListClusters` |": "| Amazon Elastic Map Reduce (EMR) | `elasticmapreduce:ListClusters` |",
    "| Amazon Elasticsearch Service (ES) | `es:ListDomainNames` |": "| Amazon Elasticsearch Service (ES) | `es:ListDomainNames` |",
    "| Amazon Elastic Transcoder | `elastictranscoder:ListPipelines` |": "| Amazon Elastic Transcoder | `elastictranscoder:ListPipelines` |",
    "| Amazon Elastic Load Balancer (ELB) (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |": "| Amazon Elastic Load Balancer (ELB) (встроенный) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |",
    "| Amazon EventBridge | `events:ListEventBuses` |": "| Amazon EventBridge | `events:ListEventBuses` |",
    "| Amazon FSx | `fsx:DescribeFileSystems` |": "| Amazon FSx | `fsx:DescribeFileSystems` |",
    "| Amazon GameLift | `gamelift:ListFleets` |": "| Amazon GameLift | `gamelift:ListFleets` |",
    "| AWS Glue | `glue:GetJobs` |": "| AWS Glue | `glue:GetJobs` |",
    "| Amazon Inspector | `inspector:ListAssessmentTemplates` |": "| Amazon Inspector | `inspector:ListAssessmentTemplates` |",
    "| AWS Internet of Things (IoT) |  |": "| AWS Internet of Things (IoT) |  |",
    "| AWS IoT Analytics |  |": "| AWS IoT Analytics |  |",
    "| Amazon Managed Streaming for Kafka | `kafka:ListClusters` |": "| Amazon Managed Streaming for Kafka | `kafka:ListClusters` |",
    "| Amazon Kinesis Data Analytics | `kinesisanalytics:ListApplications` |": "| Amazon Kinesis Data Analytics | `kinesisanalytics:ListApplications` |",
    "| Amazon Data Firehose | `firehose:ListDeliveryStreams` |": "| Amazon Data Firehose | `firehose:ListDeliveryStreams` |",
    "| Amazon Kinesis Data Streams | `kinesis:ListStreams` |": "| Amazon Kinesis Data Streams | `kinesis:ListStreams` |",
    "| Amazon Kinesis Video Streams | `kinesisvideo:ListStreams` |": "| Amazon Kinesis Video Streams | `kinesisvideo:ListStreams` |",
    "| AWS Lambda | `lambda:ListFunctions` |": "| AWS Lambda | `lambda:ListFunctions` |",
    "| AWS Lambda (built-in) | `lambda:ListFunctions`, `lambda:ListTags` |": "| AWS Lambda (встроенный) | `lambda:ListFunctions`, `lambda:ListTags` |",
    "| Amazon Lex | `lex:GetBots` |": "| Amazon Lex | `lex:GetBots` |",
    "| Amazon Application and Network Load Balancer (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |": "| Amazon Application and Network Load Balancer (встроенный) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |",
    "| Amazon CloudWatch Logs | `logs:DescribeLogGroups` |": "| Amazon CloudWatch Logs | `logs:DescribeLogGroups` |",
    "| AWS Elemental MediaConnect | `mediaconnect:ListFlows` |": "| AWS Elemental MediaConnect | `mediaconnect:ListFlows` |",
    "| AWS Elemental MediaConvert | `mediaconvert:DescribeEndpoints` |": "| AWS Elemental MediaConvert | `mediaconvert:DescribeEndpoints` |",
    "| AWS Elemental MediaPackage Live | `mediapackage:ListChannels` |": "| AWS Elemental MediaPackage Live | `mediapackage:ListChannels` |",
    "| AWS Elemental MediaPackage Video on Demand | `mediapackage-vod:ListPackagingConfigurations` |": "| AWS Elemental MediaPackage Video on Demand | `mediapackage-vod:ListPackagingConfigurations` |",
    "| AWS Elemental MediaTailor | `mediatailor:ListPlaybackConfigurations` |": "| AWS Elemental MediaTailor | `mediatailor:ListPlaybackConfigurations` |",
    "| Amazon VPC NAT Gateways | `ec2:DescribeNatGateways` |": "| Amazon VPC NAT Gateways | `ec2:DescribeNatGateways` |",
    "| Amazon Neptune | `rds:DescribeDBClusters` |": "| Amazon Neptune | `rds:DescribeDBClusters` |",
    "| AWS OpsWorks | `opsworks:DescribeStacks` |": "| AWS OpsWorks | `opsworks:DescribeStacks` |",
    "| Amazon Polly |  |": "| Amazon Polly |  |",
    "| Amazon QLDB | `qldb:ListLedgers` |": "| Amazon QLDB | `qldb:ListLedgers` |",
    "| Amazon RDS | `rds:DescribeDBInstances` |": "| Amazon RDS | `rds:DescribeDBInstances` |",
    "| Amazon RDS (built-in) | `rds:DescribeDBInstances`, `rds:DescribeEvents`, `rds:ListTagsForResource` |": "| Amazon RDS (встроенный) | `rds:DescribeDBInstances`, `rds:DescribeEvents`, `rds:ListTagsForResource` |",
    "| Amazon Redshift | `redshift:DescribeClusters` |": "| Amazon Redshift | `redshift:DescribeClusters` |",
    "| Amazon Rekognition |  |": "| Amazon Rekognition |  |",
    "| AWS RoboMaker | `robomaker:ListSimulationJobs` |": "| AWS RoboMaker | `robomaker:ListSimulationJobs` |",
    "| Amazon Route 53 | `route53:ListHostedZones` |": "| Amazon Route 53 | `route53:ListHostedZones` |",
    "| Amazon Route 53 Resolver | `route53resolver:ListResolverEndpoints` |": "| Amazon Route 53 Resolver | `route53resolver:ListResolverEndpoints` |",
    "| Amazon S3 | `s3:ListAllMyBuckets` |": "| Amazon S3 | `s3:ListAllMyBuckets` |",
    "| Amazon S3 (built-in) | `s3:ListAllMyBuckets` |": "| Amazon S3 (встроенный) | `s3:ListAllMyBuckets` |",
    "| Amazon SageMaker Batch Transform Jobs |  |": "| Amazon SageMaker Batch Transform Jobs |  |",
    "| Amazon SageMaker Endpoint Instances | `sagemaker:ListEndpoints` |": "| Amazon SageMaker Endpoint Instances | `sagemaker:ListEndpoints` |",
    "| Amazon SageMaker Endpoints | `sagemaker:ListEndpoints` |": "| Amazon SageMaker Endpoints | `sagemaker:ListEndpoints` |",
    "| Amazon SageMaker Ground Truth |  |": "| Amazon SageMaker Ground Truth |  |",
    "| Amazon SageMaker Processing Jobs |  |": "| Amazon SageMaker Processing Jobs |  |",
    "| Amazon SageMaker Training Jobs |  |": "| Amazon SageMaker Training Jobs |  |",
    "| AWS Service Catalog |  |": "| AWS Service Catalog |  |",
    "| Amazon Simple Email Service (SES) |  |": "| Amazon Simple Email Service (SES) |  |",
    "| Amazon Simple Notification Service (SNS) | `sns:ListTopics` |": "| Amazon Simple Notification Service (SNS) | `sns:ListTopics` |",
    "| Amazon Simple Queue Service (SQS) | `sqs:ListQueues` |": "| Amazon Simple Queue Service (SQS) | `sqs:ListQueues` |",
    "| AWS Systems Manager - Run Command |  |": "| AWS Systems Manager - Run Command |  |",
    "| AWS Step Functions |  |": "| AWS Step Functions |  |",
    "| AWS Storage Gateway | `storagegateway:ListGateways` |": "| AWS Storage Gateway | `storagegateway:ListGateways` |",
    "| Amazon SWF | `swf:ListDomains` |": "| Amazon SWF | `swf:ListDomains` |",
    "| Amazon Textract |  |": "| Amazon Textract |  |",
    "| AWS IoT Things Graph |  |": "| AWS IoT Things Graph |  |",
    "| AWS Transfer Family | `transfer:ListServers` |": "| AWS Transfer Family | `transfer:ListServers` |",
    "| AWS Transit Gateway | `ec2:DescribeTransitGateways` |": "| AWS Transit Gateway | `ec2:DescribeTransitGateways` |",
    "| Amazon Translate |  |": "| Amazon Translate |  |",
    "| AWS Trusted Advisor |  |": "| AWS Trusted Advisor |  |",
    "| AWS API Usage |  |": "| AWS API Usage |  |",
    "| AWS Site-to-Site VPN | `ec2:DescribeVpnConnections` |": "| AWS Site-to-Site VPN | `ec2:DescribeVpnConnections` |",
    "| AWS WAF Classic |  |": "| AWS WAF Classic |  |",
    "| AWS WAF |  |": "| AWS WAF |  |",
    "| Amazon WorkMail | `workmail:ListOrganizations` |": "| Amazon WorkMail | `workmail:ListOrganizations` |",
    "| Amazon WorkSpaces | `workspaces:DescribeWorkspaces` |": "| Amazon WorkSpaces | `workspaces:DescribeWorkspaces` |",
    "Example of JSON policy for one single service.": "Пример JSON-политики для одного сервиса приведён ниже.",
    "JSON policy for Amazon API Gateway": "JSON-политика для Amazon API Gateway",
    "In this example, from the complete list of permissions you need to select": "В этом примере из полного списка разрешений необходимо выбрать",
    "* `\"apigateway:GET\"` for **Amazon API Gateway**": "* `\"apigateway:GET\"` для **Amazon API Gateway**",
    "* `\"cloudwatch:GetMetricData\"`, `\"cloudwatch:GetMetricStatistics\"`, `\"cloudwatch:ListMetrics\"`, `\"sts:GetCallerIdentity\"`, `\"tag:GetResources\"`, `\"tag:GetTagKeys\"`, and `\"ec2:DescribeAvailabilityZones\"` for **All AWS cloud services**.": "* `\"cloudwatch:GetMetricData\"`, `\"cloudwatch:GetMetricStatistics\"`, `\"cloudwatch:ListMetrics\"`, `\"sts:GetCallerIdentity\"`, `\"tag:GetResources\"`, `\"tag:GetTagKeys\"` и `\"ec2:DescribeAvailabilityZones\"` для **всех облачных сервисов AWS**.",
    "### AWS endpoints that need to be reachable from ActiveGate with corresponding AWS services": "### Эндпоинты AWS, которые должны быть доступны из ActiveGate, с соответствующими сервисами AWS",
    "| Endpoint | Service |": "| Эндпоинт | Сервис |",
    "| `autoscaling.<REGION>.amazonaws.com` | Amazon EC2 Auto Scaling (built-in), Amazon EC2 Auto Scaling |": "| `autoscaling.<REGION>.amazonaws.com` | Amazon EC2 Auto Scaling (встроенный), Amazon EC2 Auto Scaling |",
    "| `lambda.<REGION>.amazonaws.com` | AWS Lambda (built-in), AWS Lambda |": "| `lambda.<REGION>.amazonaws.com` | AWS Lambda (встроенный), AWS Lambda |",
    "| `elasticloadbalancing.<REGION>.amazonaws.com` | Amazon Application and Network Load Balancer (built-in), Amazon Elastic Load Balancer (ELB) (built-in) |": "| `elasticloadbalancing.<REGION>.amazonaws.com` | Amazon Application and Network Load Balancer (встроенный), Amazon Elastic Load Balancer (ELB) (встроенный) |",
    "| `dynamodb.<REGION>.amazonaws.com` | Amazon DynamoDB (built-in), Amazon DynamoDB |": "| `dynamodb.<REGION>.amazonaws.com` | Amazon DynamoDB (встроенный), Amazon DynamoDB |",
    "| `ec2.<REGION>.amazonaws.com` | Amazon EBS (built-in), Amazon EC2 (built-in), Amazon EBS, Amazon EC2 Spot Fleet, Amazon VPC NAT Gateways, AWS Transit Gateway, AWS Site-to-Site VPN |": "| `ec2.<REGION>.amazonaws.com` | Amazon EBS (встроенный), Amazon EC2 (встроенный), Amazon EBS, Amazon EC2 Spot Fleet, Amazon VPC NAT Gateways, AWS Transit Gateway, AWS Site-to-Site VPN |",
    "| `rds.<REGION>.amazonaws.com` | Amazon RDS (built-in), Amazon Aurora, Amazon DocumentDB, Amazon Neptune, Amazon RDS |": "| `rds.<REGION>.amazonaws.com` | Amazon RDS (встроенный), Amazon Aurora, Amazon DocumentDB, Amazon Neptune, Amazon RDS |",
    "| `s3.<REGION>.amazonaws.com` | Amazon S3 (built-in) |": "| `s3.<REGION>.amazonaws.com` | Amazon S3 (встроенный) |",
    "| `acm-pca.<REGION>.amazonaws.com` | AWS Certificate Manager Private Certificate Authority |": "| `acm-pca.<REGION>.amazonaws.com` | AWS Certificate Manager Private Certificate Authority |",
    "| `apigateway.<REGION>.amazonaws.com` | Amazon API Gateway |": "| `apigateway.<REGION>.amazonaws.com` | Amazon API Gateway |",
    "| `apprunner.<REGION>.amazonaws.com` | AWS App Runner |": "| `apprunner.<REGION>.amazonaws.com` | AWS App Runner |",
    "| `appstream2.<REGION>.amazonaws.com` | Amazon AppStream |": "| `appstream2.<REGION>.amazonaws.com` | Amazon AppStream |",
    "| `appsync.<REGION>.amazonaws.com` | AWS AppSync |": "| `appsync.<REGION>.amazonaws.com` | AWS AppSync |",
    "| `athena.<REGION>.amazonaws.com` | Amazon Athena |": "| `athena.<REGION>.amazonaws.com` | Amazon Athena |",
    "| `cloudfront.amazonaws.com` | Amazon CloudFront |": "| `cloudfront.amazonaws.com` | Amazon CloudFront |",
    "| `cloudhsmv2.<REGION>.amazonaws.com` | AWS CloudHSM |": "| `cloudhsmv2.<REGION>.amazonaws.com` | AWS CloudHSM |",
    "| `cloudsearch.<REGION>.amazonaws.com` | Amazon CloudSearch |": "| `cloudsearch.<REGION>.amazonaws.com` | Amazon CloudSearch |",
    "| `codebuild.<REGION>.amazonaws.com` | AWS CodeBuild |": "| `codebuild.<REGION>.amazonaws.com` | AWS CodeBuild |",
    "| `datasync.<REGION>.amazonaws.com` | AWS DataSync |": "| `datasync.<REGION>.amazonaws.com` | AWS DataSync |",
    "| `dax.<REGION>.amazonaws.com` | Amazon DynamoDB Accelerator (DAX) |": "| `dax.<REGION>.amazonaws.com` | Amazon DynamoDB Accelerator (DAX) |",
    "| `dms.<REGION>.amazonaws.com` | AWS Database Migration Service (AWS DMS) |": "| `dms.<REGION>.amazonaws.com` | AWS Database Migration Service (AWS DMS) |",
    "| `directconnect.<REGION>.amazonaws.com` | AWS Direct Connect |": "| `directconnect.<REGION>.amazonaws.com` | AWS Direct Connect |",
    "| `ecs.<REGION>.amazonaws.com` | Amazon Elastic Container Service (ECS), Amazon ECS Container Insights |": "| `ecs.<REGION>.amazonaws.com` | Amazon Elastic Container Service (ECS), Amazon ECS Container Insights |",
    "| `elasticfilesystem.<REGION>.amazonaws.com` | Amazon Elastic File System (EFS) |": "| `elasticfilesystem.<REGION>.amazonaws.com` | Amazon Elastic File System (EFS) |",
    "| `eks.<REGION>.amazonaws.com` | Amazon Elastic Kubernetes Service (EKS) |": "| `eks.<REGION>.amazonaws.com` | Amazon Elastic Kubernetes Service (EKS) |",
    "| `elasticache.<REGION>.amazonaws.com` | Amazon ElastiCache (EC) |": "| `elasticache.<REGION>.amazonaws.com` | Amazon ElastiCache (EC) |",
    "| `elasticbeanstalk.<REGION>.amazonaws.com` | AWS Elastic Beanstalk |": "| `elasticbeanstalk.<REGION>.amazonaws.com` | AWS Elastic Beanstalk |",
    "| `elastictranscoder.<REGION>.amazonaws.com` | Amazon Elastic Transcoder |": "| `elastictranscoder.<REGION>.amazonaws.com` | Amazon Elastic Transcoder |",
    "| `es.<REGION>.amazonaws.com` | Amazon Elasticsearch Service (ES) |": "| `es.<REGION>.amazonaws.com` | Amazon Elasticsearch Service (ES) |",
    "| `events.<REGION>.amazonaws.com` | Amazon EventBridge |": "| `events.<REGION>.amazonaws.com` | Amazon EventBridge |",
    "| `fsx.<REGION>.amazonaws.com` | Amazon FSx |": "| `fsx.<REGION>.amazonaws.com` | Amazon FSx |",
    "| `gamelift.<REGION>.amazonaws.com` | Amazon GameLift |": "| `gamelift.<REGION>.amazonaws.com` | Amazon GameLift |",
    "| `glue.<REGION>.amazonaws.com` | AWS Glue |": "| `glue.<REGION>.amazonaws.com` | AWS Glue |",
    "| `inspector.<REGION>.amazonaws.com` | Amazon Inspector |": "| `inspector.<REGION>.amazonaws.com` | Amazon Inspector |",
    "| `kafka.<REGION>.amazonaws.com` | Amazon Managed Streaming for Kafka |": "| `kafka.<REGION>.amazonaws.com` | Amazon Managed Streaming for Kafka |",
    "| `models.lex.<REGION>.amazonaws.com` | Amazon Lex |": "| `models.lex.<REGION>.amazonaws.com` | Amazon Lex |",
    "| `logs.<REGION>.amazonaws.com` | Amazon CloudWatch Logs |": "| `logs.<REGION>.amazonaws.com` | Amazon CloudWatch Logs |",
    "| `api.mediatailor.<REGION>.amazonaws.com` | AWS Elemental MediaTailor |": "| `api.mediatailor.<REGION>.amazonaws.com` | AWS Elemental MediaTailor |",
    "| `mediaconnect.<REGION>.amazonaws.com` | AWS Elemental MediaConnect |": "| `mediaconnect.<REGION>.amazonaws.com` | AWS Elemental MediaConnect |",
    "| `mediapackage.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Live |": "| `mediapackage.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Live |",
    "| `mediapackage-vod.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Video on Demand |": "| `mediapackage-vod.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Video on Demand |",
    "| `opsworks.<REGION>.amazonaws.com` | AWS OpsWorks |": "| `opsworks.<REGION>.amazonaws.com` | AWS OpsWorks |",
    "| `qldb.<REGION>.amazonaws.com` | Amazon QLDB |": "| `qldb.<REGION>.amazonaws.com` | Amazon QLDB |",
    "| `redshift.<REGION>.amazonaws.com` | Amazon Redshift |": "| `redshift.<REGION>.amazonaws.com` | Amazon Redshift |",
    "| `robomaker.<REGION>.amazonaws.com` | AWS RoboMaker |": "| `robomaker.<REGION>.amazonaws.com` | AWS RoboMaker |",
    "| `route53.amazonaws.com` | Amazon Route 53 |": "| `route53.amazonaws.com` | Amazon Route 53 |",
    "| `route53resolver.<REGION>.amazonaws.com` | Amazon Route 53 Resolver |": "| `route53resolver.<REGION>.amazonaws.com` | Amazon Route 53 Resolver |",
    "| `api.sagemaker.<REGION>.amazonaws.com` | Amazon SageMaker Endpoints, Amazon SageMaker Endpoint Instances |": "| `api.sagemaker.<REGION>.amazonaws.com` | Amazon SageMaker Endpoints, Amazon SageMaker Endpoint Instances |",
    "| `sns.<REGION>.amazonaws.com` | Amazon Simple Notification Service (SNS) |": "| `sns.<REGION>.amazonaws.com` | Amazon Simple Notification Service (SNS) |",
    "| `sqs.<REGION>.amazonaws.com` | Amazon Simple Queue Service (SQS) |": "| `sqs.<REGION>.amazonaws.com` | Amazon Simple Queue Service (SQS) |",
    "| `storagegateway.<REGION>.amazonaws.com` | AWS Storage Gateway |": "| `storagegateway.<REGION>.amazonaws.com` | AWS Storage Gateway |",
    "| `swf.<REGION>.amazonaws.com` | Amazon SWF |": "| `swf.<REGION>.amazonaws.com` | Amazon SWF |",
    "| `transfer.<REGION>.amazonaws.com` | AWS Transfer Family |": "| `transfer.<REGION>.amazonaws.com` | AWS Transfer Family |",
    "| `workmail.<REGION>.amazonaws.com` | Amazon WorkMail |": "| `workmail.<REGION>.amazonaws.com` | Amazon WorkMail |",
    "| `workspaces.<REGION>.amazonaws.com` | Amazon WorkSpaces |": "| `workspaces.<REGION>.amazonaws.com` | Amazon WorkSpaces |",
    "This service monitors Amazon EC2 Auto Scaling. For this service you can see only instances with metrics.": "Данный сервис мониторирует Amazon EC2 Auto Scaling. Для него отображаются только экземпляры с метриками.",
    "Remember that if you have Amazon EC2 Auto Scaling service configured, you can’t have [Amazon EC2 Auto Scaling (built-in)](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/cloudwatch-ec2/ec2-auto-scaling-builltin \"Monitor Amazon EC2 Auto Scaling and view available metrics.\") service turned on. To monitor extended metrics, you need to select **Amazon EC2 Auto Scaling**, otherwise Amazon EC2 Auto Scaling (built-in) will provide only a basic count of EC2 instances in the scaling group.": "Обратите внимание: если настроен сервис Amazon EC2 Auto Scaling, нельзя одновременно включить сервис [Amazon EC2 Auto Scaling (встроенный)](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/cloudwatch-ec2/ec2-auto-scaling-builltin \"Мониторинг Amazon EC2 Auto Scaling и просмотр доступных метрик.\"). Для мониторинга расширенных метрик необходимо выбрать **Amazon EC2 Auto Scaling**, иначе Amazon EC2 Auto Scaling (встроенный) будет предоставлять только базовое количество экземпляров EC2 в группе масштабирования.",
    "By default, Auto Scaling Group metrics aren't reported. To have them reported, you need to enable them in the **AWS Auto Scaling Group** console.": "По умолчанию метрики Auto Scaling Group не передаются. Чтобы включить их передачу, необходимо активировать их в консоли **AWS Auto Scaling Group**.",
    "## Enable monitoring": "## Включение мониторинга",
    "To learn how to enable service monitoring, see [Enable service monitoring](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-metrics-ingest/aws-enable-service-monitoring \"Enable AWS monitoring in Dynatrace.\").": "Чтобы узнать, как включить мониторинг сервиса, см. [Включение мониторинга сервиса](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-metrics-ingest/aws-enable-service-monitoring \"Включение мониторинга AWS в Dynatrace.\").",
    "## View service metrics": "## Просмотр метрик сервиса",
    "You can view the service metrics in your Dynatrace environment either on the **custom device overview page** or on your **Dashboards** page.": "Метрики сервиса можно просматривать в среде Dynatrace на **странице обзора пользовательского устройства** или на странице **Dashboards**.",
    "### View metrics on the custom device overview page": "### Просмотр метрик на странице обзора пользовательского устройства",
    "To access the custom device overview page": "Чтобы перейти на страницу обзора пользовательского устройства",
    "1. Go to **Technologies & Processes**.": "1. Перейдите в **Technologies & Processes**.",
    "2. Filter by service name and select the relevant custom device group.": "2. Отфильтруйте по имени сервиса и выберите соответствующую группу пользовательских устройств.",
    "3. Once you select the custom device group, you're on the **custom device group overview page**.": "3. После выбора группы пользовательских устройств вы окажетесь на **странице обзора группы пользовательских устройств**.",
    "4. The **custom device group overview page** lists all instances (custom devices) belonging to the group. Select an instance to view the **custom device overview page**.": "4. На **странице обзора группы пользовательских устройств** перечислены все экземпляры (пользовательские устройства), принадлежащие группе. Выберите экземпляр для просмотра **страницы обзора пользовательского устройства**.",
    "### View metrics on your dashboard": "### Просмотр метрик на дашборде",
    "After you add the service to monitoring, a preset dashboard containing all recommended metrics is automatically listed on your **Dashboards** page. To look for specific dashboards, filter by **Preset** and then by **Name**.": "После добавления сервиса в мониторинг на странице **Dashboards** автоматически появляется предустановленный дашборд со всеми рекомендуемыми метриками. Для поиска конкретных дашбордов отфильтруйте по **Preset**, а затем по **Name**.",
    "![AWS presets](https://dt-cdn.net/images/image-26-1645-389f58aa89.png)": "![AWS presets](https://dt-cdn.net/images/image-26-1645-389f58aa89.png)",
    "AWS presets": "AWS presets",
    "For existing monitored services, you might need to resave your credentials for the preset dashboard to appear on the **Dashboards** page. To resave your credentials, go to **Settings** > **Cloud and virtualization** > **AWS**, select the desired AWS instance, and then select **Save**.": "Для существующих мониторируемых сервисов может потребоваться повторно сохранить учётные данные, чтобы предустановленный дашборд появился на странице **Dashboards**. Для этого перейдите в **Settings** > **Cloud and virtualization** > **AWS**, выберите нужный экземпляр AWS и нажмите **Save**.",
    "You can't make changes on a preset dashboard directly, but you can clone and edit it. To clone a dashboard, open the browse menu (**…**) and select **Clone**.": "Вносить изменения в предустановленный дашборд напрямую нельзя, но его можно клонировать и редактировать. Чтобы клонировать дашборд, откройте меню обзора (**...**) и выберите **Clone**.",
    "To remove a dashboard from the dashboards page, you can hide it. To hide a dashboard, open the browse menu (**…**) and select **Hide**.": "Чтобы убрать дашборд со страницы дашбордов, его можно скрыть. Для этого откройте меню обзора (**...**) и выберите **Hide**.",
    "Hiding a dashboard doesn't affect other users.": "Скрытие дашборда не влияет на других пользователей.",
    "![Clone hide AWS](https://dt-cdn.net/images/2020-12-10-15-04-09-1502-b899a29d73.png)": "![Clone hide AWS](https://dt-cdn.net/images/2020-12-10-15-04-09-1502-b899a29d73.png)",
    "Clone hide AWS": "Clone hide AWS",
    "To check the availability of preset dashboards for each AWS service, see the list below.": "Чтобы проверить доступность предустановленных дашбордов для каждого сервиса AWS, см. список ниже.",
    "### Preset dashboard availability list": "### Список доступности предустановленных дашбордов",
    "| AWS service | Preset dashboard |": "| Сервис AWS | Предустановленный дашборд |",
    "| Amazon EC2 Auto Scaling (built-in) | Not applicable |": "| Amazon EC2 Auto Scaling (встроенный) | Недоступен |",
    "| AWS Lambda (built-in) | Not applicable |": "| AWS Lambda (встроенный) | Недоступен |",
    "| Amazon Application and Network Load Balancer (built-in) | Not applicable |": "| Amazon Application and Network Load Balancer (встроенный) | Недоступен |",
    "| Amazon DynamoDB (built-in) | Not applicable |": "| Amazon DynamoDB (встроенный) | Недоступен |",
    "| Amazon EBS (built-in) | Not applicable |": "| Amazon EBS (встроенный) | Недоступен |",
    "| Amazon EC2 (built-in) | Not applicable |": "| Amazon EC2 (встроенный) | Недоступен |",
    "| Amazon Elastic Load Balancer (ELB) (built-in) | Not applicable |": "| Amazon Elastic Load Balancer (ELB) (встроенный) | Недоступен |",
    "| Amazon RDS (built-in) | Not applicable |": "| Amazon RDS (встроенный) | Недоступен |",
    "| Amazon S3 (built-in) | Not applicable |": "| Amazon S3 (встроенный) | Недоступен |",
    "| AWS Certificate Manager Private Certificate Authority | Not applicable |": "| AWS Certificate Manager Private Certificate Authority | Недоступен |",
    "| All monitored Amazon services | Not applicable |": "| Все мониторируемые сервисы Amazon | Недоступен |",
    "| Amazon API Gateway | Not applicable |": "| Amazon API Gateway | Недоступен |",
    "| AWS App Runner | Not applicable |": "| AWS App Runner | Недоступен |",
    "| Amazon AppStream | Applicable |": "| Amazon AppStream | Доступен |",
    "| AWS AppSync | Applicable |": "| AWS AppSync | Доступен |",
    "| Amazon Athena | Applicable |": "| Amazon Athena | Доступен |",
    "| Amazon Aurora | Not applicable |": "| Amazon Aurora | Недоступен |",
    "| Amazon EC2 Auto Scaling | Applicable |": "| Amazon EC2 Auto Scaling | Доступен |",
    "| AWS Billing | Applicable |": "| AWS Billing | Доступен |",
    "| Amazon Keyspaces | Applicable |": "| Amazon Keyspaces | Доступен |",
    "| AWS Chatbot | Applicable |": "| AWS Chatbot | Доступен |",
    "| Amazon CloudFront | Not applicable |": "| Amazon CloudFront | Недоступен |",
    "| AWS CloudHSM | Applicable |": "| AWS CloudHSM | Доступен |",
    "| Amazon CloudSearch | Applicable |": "| Amazon CloudSearch | Доступен |",
    "| AWS CodeBuild | Applicable |": "| AWS CodeBuild | Доступен |",
    "| Amazon Cognito | Not applicable |": "| Amazon Cognito | Недоступен |",
    "| Amazon Connect | Applicable |": "| Amazon Connect | Доступен |",
    "| AWS DataSync | Applicable |": "| AWS DataSync | Доступен |",
    "| Amazon DynamoDB Accelerator (DAX) | Applicable |": "| Amazon DynamoDB Accelerator (DAX) | Доступен |",
    "| AWS Database Migration Service (AWS DMS) | Applicable |": "| AWS Database Migration Service (AWS DMS) | Доступен |",
    "| Amazon DocumentDB | Applicable |": "| Amazon DocumentDB | Доступен |",
    "| AWS Direct Connect | Applicable |": "| AWS Direct Connect | Доступен |",
    "| Amazon DynamoDB | Not applicable |": "| Amazon DynamoDB | Недоступен |",
    "| Amazon EBS | Not applicable |": "| Amazon EBS | Недоступен |",
    "| Amazon EC2 Spot Fleet | Not applicable |": "| Amazon EC2 Spot Fleet | Недоступен |",
    "| Amazon EC2 API | Applicable |": "| Amazon EC2 API | Доступен |",
    "| Amazon Elastic Container Service (ECS) | Not applicable |": "| Amazon Elastic Container Service (ECS) | Недоступен |",
    "| Amazon ECS Container Insights | Applicable |": "| Amazon ECS Container Insights | Доступен |",
    "| Amazon Elastic File System (EFS) | Not applicable |": "| Amazon Elastic File System (EFS) | Недоступен |",
    "| Amazon Elastic Kubernetes Service (EKS) | Applicable |": "| Amazon Elastic Kubernetes Service (EKS) | Доступен |",
    "| Amazon ElastiCache (EC) | Not applicable |": "| Amazon ElastiCache (EC) | Недоступен |",
    "| AWS Elastic Beanstalk | Applicable |": "| AWS Elastic Beanstalk | Доступен |",
    "| Amazon Elastic Inference | Applicable |": "| Amazon Elastic Inference | Доступен |",
    "| Amazon Elastic Transcoder | Applicable |": "| Amazon Elastic Transcoder | Доступен |",
    "| Amazon Elastic Map Reduce (EMR) | Not applicable |": "| Amazon Elastic Map Reduce (EMR) | Недоступен |",
    "| Amazon Elasticsearch Service (ES) | Not applicable |": "| Amazon Elasticsearch Service (ES) | Недоступен |",
    "| Amazon EventBridge | Applicable |": "| Amazon EventBridge | Доступен |",
    "| Amazon FSx | Applicable |": "| Amazon FSx | Доступен |",
    "| Amazon GameLift | Applicable |": "| Amazon GameLift | Доступен |",
    "| AWS Glue | Not applicable |": "| AWS Glue | Недоступен |",
    "| Amazon Inspector | Applicable |": "| Amazon Inspector | Доступен |",
    "| AWS Internet of Things (IoT) | Not applicable |": "| AWS Internet of Things (IoT) | Недоступен |",
    "| AWS IoT Things Graph | Applicable |": "| AWS IoT Things Graph | Доступен |",
    "| AWS IoT Analytics | Applicable |": "| AWS IoT Analytics | Доступен |",
    "| Amazon Managed Streaming for Kafka | Applicable |": "| Amazon Managed Streaming for Kafka | Доступен |",
    "| Amazon Kinesis Data Analytics | Not applicable |": "| Amazon Kinesis Data Analytics | Недоступен |",
    "| Amazon Data Firehose | Not applicable |": "| Amazon Data Firehose | Недоступен |",
    "| Amazon Kinesis Data Streams | Not applicable |": "| Amazon Kinesis Data Streams | Недоступен |",
    "| Amazon Kinesis Video Streams | Not applicable |": "| Amazon Kinesis Video Streams | Недоступен |",
    "| AWS Lambda | Not applicable |": "| AWS Lambda | Недоступен |",
    "| Amazon Lex | Applicable |": "| Amazon Lex | Доступен |",
    "| Amazon CloudWatch Logs | Applicable |": "| Amazon CloudWatch Logs | Доступен |",
    "| AWS Elemental MediaTailor | Applicable |": "| AWS Elemental MediaTailor | Доступен |",
    "| AWS Elemental MediaConnect | Applicable |": "| AWS Elemental MediaConnect | Доступен |",
    "| AWS Elemental MediaConvert | Applicable |": "| AWS Elemental MediaConvert | Доступен |",
    "| AWS Elemental MediaPackage Live | Applicable |": "| AWS Elemental MediaPackage Live | Доступен |",
    "| AWS Elemental MediaPackage Video on Demand | Applicable |": "| AWS Elemental MediaPackage Video on Demand | Доступен |",
    "| Amazon MQ | Applicable |": "| Amazon MQ | Доступен |",
    "| Amazon VPC NAT Gateways | Not applicable |": "| Amazon VPC NAT Gateways | Недоступен |",
    "| Amazon Neptune | Applicable |": "| Amazon Neptune | Доступен |",
    "| AWS OpsWorks | Applicable |": "| AWS OpsWorks | Доступен |",
    "| Amazon Polly | Applicable |": "| Amazon Polly | Доступен |",
    "| Amazon QLDB | Applicable |": "| Amazon QLDB | Доступен |",
    "| Amazon RDS | Not applicable |": "| Amazon RDS | Недоступен |",
    "| Amazon Redshift | Not applicable |": "| Amazon Redshift | Недоступен |",
    "| Amazon Rekognition | Applicable |": "| Amazon Rekognition | Доступен |",
    "| AWS RoboMaker | Applicable |": "| AWS RoboMaker | Доступен |",
    "| Amazon Route 53 | Applicable |": "| Amazon Route 53 | Доступен |",
    "| Amazon Route 53 Resolver | Applicable |": "| Amazon Route 53 Resolver | Доступен |",
    "| Amazon S3 | Not applicable |": "| Amazon S3 | Недоступен |",
    "| Amazon SageMaker Batch Transform Jobs | Not applicable |": "| Amazon SageMaker Batch Transform Jobs | Недоступен |",
    "| Amazon SageMaker Endpoints | Not applicable |": "| Amazon SageMaker Endpoints | Недоступен |",
    "| Amazon SageMaker Endpoint Instances | Not applicable |": "| Amazon SageMaker Endpoint Instances | Недоступен |",
    "| Amazon SageMaker Ground Truth | Not applicable |": "| Amazon SageMaker Ground Truth | Недоступен |",
    "| Amazon SageMaker Processing Jobs | Not applicable |": "| Amazon SageMaker Processing Jobs | Недоступен |",
    "| Amazon SageMaker Training Jobs | Not applicable |": "| Amazon SageMaker Training Jobs | Недоступен |",
    "| AWS Service Catalog | Applicable |": "| AWS Service Catalog | Доступен |",
    "| Amazon Simple Email Service (SES) | Not applicable |": "| Amazon Simple Email Service (SES) | Недоступен |",
    "| Amazon Simple Notification Service (SNS) | Not applicable |": "| Amazon Simple Notification Service (SNS) | Недоступен |",
    "| Amazon Simple Queue Service (SQS) | Not applicable |": "| Amazon Simple Queue Service (SQS) | Недоступен |",
    "| AWS Systems Manager - Run Command | Applicable |": "| AWS Systems Manager - Run Command | Доступен |",
    "| AWS Step Functions | Applicable |": "| AWS Step Functions | Доступен |",
    "| AWS Storage Gateway | Applicable |": "| AWS Storage Gateway | Доступен |",
    "| Amazon SWF | Applicable |": "| Amazon SWF | Доступен |",
    "| Amazon Textract | Applicable |": "| Amazon Textract | Доступен |",
    "| AWS Transfer Family | Applicable |": "| AWS Transfer Family | Доступен |",
    "| AWS Transit Gateway | Applicable |": "| AWS Transit Gateway | Доступен |",
    "| Amazon Translate | Applicable |": "| Amazon Translate | Доступен |",
    "| AWS Trusted Advisor | Applicable |": "| AWS Trusted Advisor | Доступен |",
    "| AWS API Usage | Applicable |": "| AWS API Usage | Доступен |",
    "| AWS Site-to-Site VPN | Applicable |": "| AWS Site-to-Site VPN | Доступен |",
    "| AWS WAF Classic | Applicable |": "| AWS WAF Classic | Доступен |",
    "| AWS WAF | Applicable |": "| AWS WAF | Доступен |",
    "| Amazon WorkMail | Applicable |": "| Amazon WorkMail | Доступен |",
    "| Amazon WorkSpaces | Applicable |": "| Amazon WorkSpaces | Доступен |",
    "![EC2](https://dt-cdn.net/images/dashboard-25-1620-092f9f7aab.png)": "![EC2](https://dt-cdn.net/images/dashboard-25-1620-092f9f7aab.png)",
    "EC2": "EC2",
    "## Available metrics": "## Доступные метрики",
    "`AutoScalingGroupName` is the main dimension.": "`AutoScalingGroupName` является основным измерением.",
    "| Name | Description | Unit | Statistics | Dimensions | Recommended |": "| Название | Описание | Единица | Статистика | Измерения | Рекомендуемая |",
    "| --- | --- | --- | --- | --- | --- |": "| --- | --- | --- | --- | --- | --- |",
    "| GroupAndWarmPoolDesiredCapacity | The desired capacity of the Auto Scaling group and the warm pool combined. | Count | Average | AutoScalingGroupName |  |": "| GroupAndWarmPoolDesiredCapacity | Желаемая ёмкость группы Auto Scaling и резервного пула вместе. | Количество | Average | AutoScalingGroupName |  |",
    "| GroupAndWarmPoolTotalCapacity | The total capacity of the Auto Scaling group and the warm pool combined. This includes instances that are running, stopped, pending, terminating, or in service. | Count | Average | AutoScalingGroupName |  |": "| GroupAndWarmPoolTotalCapacity | Общая ёмкость группы Auto Scaling и резервного пула вместе. Включает экземпляры в состоянии running, stopped, pending, terminating или in service. | Количество | Average | AutoScalingGroupName |  |",
    "| GroupDesiredCapacity | The number of instances that the Auto Scaling group attempts to maintain | Count | Average | AutoScalingGroupName | Applicable |": "| GroupDesiredCapacity | Количество экземпляров, которое группа Auto Scaling пытается поддерживать. | Количество | Average | AutoScalingGroupName | Доступна |",
    "| GroupInServiceCapacity | The number of capacity units that are running as part of the Auto Scaling group | Count | Average | AutoScalingGroupName |  |": "| GroupInServiceCapacity | Количество единиц ёмкости, работающих в составе группы Auto Scaling. | Количество | Average | AutoScalingGroupName |  |",
    "| GroupInServiceInstances | The number of instances that are running as part of the Auto Scaling group. This metric does not include instances that are pending or terminating. | Count | Average | AutoScalingGroupName | Applicable |": "| GroupInServiceInstances | Количество экземпляров, работающих в составе группы Auto Scaling. Не включает экземпляры в состоянии pending или terminating. | Количество | Average | AutoScalingGroupName | Доступна |",
    "| GroupMaxSize | The maximum size of the Auto Scaling group | Count | Average | AutoScalingGroupName | Applicable |": "| GroupMaxSize | Максимальный размер группы Auto Scaling. | Количество | Average | AutoScalingGroupName | Доступна |",
    "| GroupMinSize | The minimum size of the Auto Scaling group | Count | Average | AutoScalingGroupName | Applicable |": "| GroupMinSize | Минимальный размер группы Auto Scaling. | Количество | Average | AutoScalingGroupName | Доступна |",
    "| GroupPendingCapacity | The number of capacity units that are pending | Count | Average | AutoScalingGroupName |  |": "| GroupPendingCapacity | Количество единиц ёмкости в состоянии pending. | Количество | Average | AutoScalingGroupName |  |",
    "| GroupPendingInstances | The number of instances that are pending. A pending instance is not yet in service. This metric does not include instances that are in service or terminating. | Count | Average | AutoScalingGroupName | Applicable |": "| GroupPendingInstances | Количество экземпляров в состоянии pending. Экземпляр в состоянии pending ещё не введён в сервис. Не включает экземпляры в состоянии in service или terminating. | Количество | Average | AutoScalingGroupName | Доступна |",
    "| GroupStandbyCapacity | The number of capacity units that are in a standby state | Count | Average | AutoScalingGroupName |  |": "| GroupStandbyCapacity | Количество единиц ёмкости в состоянии standby. | Количество | Average | AutoScalingGroupName |  |",
    "| GroupStandbyInstances | The number of instances that are in a standby state. Instances in this state are still running but are not actively in service. | Count | Average | AutoScalingGroupName | Applicable |": "| GroupStandbyInstances | Количество экземпляров в состоянии standby. Такие экземпляры работают, но не находятся в активном сервисе. | Количество | Average | AutoScalingGroupName | Доступна |",
    "| GroupTerminatingCapacity | The number of capacity units that are in the process of terminating | Count | Average | AutoScalingGroupName |  |": "| GroupTerminatingCapacity | Количество единиц ёмкости в процессе завершения. | Количество | Average | AutoScalingGroupName |  |",
    "| GroupTerminatingInstances | The number of instances that are in the process of terminating. This metric does not include instances that are in service or pending. | Count | Average | AutoScalingGroupName | Applicable |": "| GroupTerminatingInstances | Количество экземпляров в процессе завершения. Не включает экземпляры в состоянии in service или pending. | Количество | Average | AutoScalingGroupName | Доступна |",
    "| GroupTotalCapacity | The total number of capacity units in the Auto Scaling group | Count | Average | AutoScalingGroupName |  |": "| GroupTotalCapacity | Общее количество единиц ёмкости в группе Auto Scaling. | Количество | Average | AutoScalingGroupName |  |",
    "| GroupTotalInstances | The total number of instances in the Auto Scaling group. This metric identifies the number of instances that are in service, pending, and terminating. | Count | Average | AutoScalingGroupName | Applicable |": "| GroupTotalInstances | Общее количество экземпляров в группе Auto Scaling. Включает экземпляры в состоянии in service, pending и terminating. | Количество | Average | AutoScalingGroupName | Доступна |",
    "| WarmPoolDesiredCapacity | The amount of capacity that Amazon EC2 Auto Scaling attempts to maintain in the warm pool. | Count | Average | AutoScalingGroupName |  |": "| WarmPoolDesiredCapacity | Объём ёмкости, который Amazon EC2 Auto Scaling пытается поддерживать в резервном пуле. | Количество | Average | AutoScalingGroupName |  |",
    "| WarmPoolMinSize | The minimum size of the warm pool. | Count | Average | AutoScalingGroupName |  |": "| WarmPoolMinSize | Минимальный размер резервного пула. | Количество | Average | AutoScalingGroupName |  |",
    "| WarmPoolPendingCapacity | The amount of capacity in the warm pool that is pending. This metric does not include instances that are running, stopped, or terminating. | Count | Average | AutoScalingGroupName |  |": "| WarmPoolPendingCapacity | Объём ёмкости в резервном пуле в состоянии pending. Не включает экземпляры в состоянии running, stopped или terminating. | Количество | Average | AutoScalingGroupName |  |",
    "| WarmPoolTerminatingCapacity | The amount of capacity in the warm pool that is in the process of terminating. This metric does not include instances that are running, stopped, or pending. | Count | Average | AutoScalingGroupName |  |": "| WarmPoolTerminatingCapacity | Объём ёмкости в резервном пуле в процессе завершения. Не включает экземпляры в состоянии running, stopped или pending. | Количество | Average | AutoScalingGroupName |  |",
    "| WarmPoolTotalCapacity | The total capacity of the warm pool, including instances that are running, stopped, pending, or terminating. | Count | Average | AutoScalingGroupName |  |": "| WarmPoolTotalCapacity | Общая ёмкость резервного пула, включая экземпляры в состоянии running, stopped, pending или terminating. | Количество | Average | AutoScalingGroupName |  |",
    "| WarmPoolWarmedCapacity | The amount of capacity available to enter the Auto Scaling group during scale out. This metric does not include instances that are pending or terminating. | Count | Average | AutoScalingGroupName |  |": "| WarmPoolWarmedCapacity | Объём ёмкости, доступной для перехода в группу Auto Scaling при масштабировании. Не включает экземпляры в состоянии pending или terminating. | Количество | Average | AutoScalingGroupName |  |",
    "## Limitations": "## Ограничения",
    "Tagging isn't available for Amazon EC2 Auto Scaling.": "Теги недоступны для Amazon EC2 Auto Scaling.",
    "Dynatrace entities of this AWS service are not enriched with the ARN property.": "Сущности Dynatrace для этого сервиса AWS не обогащаются свойством ARN.",
}

PASS = {
    "* `\"cloudwatch:GetMetricData\"`",
    "* `\"cloudwatch:GetMetricStatistics\"`",
    "* `\"cloudwatch:ListMetrics\"`",
    "* `\"sts:GetCallerIdentity\"`",
    "* `\"tag:GetResources\"`",
    "* `\"tag:GetTagKeys\"`",
    "* `\"ec2:DescribeAvailabilityZones\"`",
}

build_one(REL, "ec2-auto-scaling.md", TRANS, PASS)
qa_one(REL, "ec2-auto-scaling.md")
