# -*- coding: utf-8 -*-
"""Builder for oneagent-configuration-via-command-line-interface.md (L4-IF.71 canon)."""

import sys, os

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/dynatrace-oneagent"
FN = "oneagent-configuration-via-command-line-interface.md"

TRANS = {
    # --- frontmatter ---
    "title: OneAgent configuration via command-line interface": "title: Настройка OneAgent через интерфейс командной строки",
    # --- h1 (appears twice) ---
    "# OneAgent configuration via command-line interface": "# Настройка OneAgent через интерфейс командной строки",
    # --- metadata ---
    "* Reference": "* Справочник",
    "* 20-min read": "* Чтение: 20 мин",
    "* Updated on Sep 17, 2025": "* Обновлено 17 сентября 2025 г.",
    # --- intro ---
    "Use the `oneagentctl` command-line interface to perform some post-installation OneAgent configuration at the individual host level.": "Используйте интерфейс командной строки `oneagentctl` для выполнения ряда задач настройки OneAgent после установки на уровне отдельного хоста.",
    # --- ## Location ---
    "## Location": "## Расположение",
    "The tool location depends on whether you customized the OneAgent installation using the `<INSTALL_PATH>` parameter:": "Расположение инструмента зависит от того, задавали ли вы параметр `<INSTALL_PATH>` при установке OneAgent:",
    "* **Linux** or **AIX**:": "* **Linux** или **AIX**:",
    "`<INSTALL_PATH>/agent/tools`, by default `/opt/dynatrace/oneagent/agent/tools`": "`<INSTALL_PATH>/agent/tools`, по умолчанию `/opt/dynatrace/oneagent/agent/tools`",
    "You need root privileges.": "Требуются привилегии root.",
    "* **Docker-based deployment**": "* **Развёртывание на основе Docker**",
    "Note that this path will differ for a volume-based deployment.": "Обратите внимание, что для развёртывания с томами путь будет другим.",
    "* **Windows**:": "* **Windows**:",
    "`<INSTALL_PATH>\\agent\\tools`, by default `%PROGRAMFILES%\\dynatrace\\oneagent\\agent\\tools`": "`<INSTALL_PATH>\\agent\\tools`, по умолчанию `%PROGRAMFILES%\\dynatrace\\oneagent\\agent\\tools`",
    "You need administrator privileges. If you try to run `oneagentctl` in a non-admin Windows console, Windows will display a User Account Control pop-up and fail.": "Требуются права администратора. Если запустить `oneagentctl` в консоли Windows без прав администратора, Windows отобразит диалог управления учётными записями пользователей (UAC) и завершит работу с ошибкой.",
    # --- ## Parameter types ---
    "## Parameter types": "## Типы параметров",
    "The `oneagentctl` command accepts the `get` parameter to check the state or value of a setting, and the `set` parameter to change a setting. Note that you can use multiple `set` parameters in a single command.": "Команда `oneagentctl` принимает параметр `get` для проверки состояния или значения настройки и параметр `set` для изменения настройки. В одной команде можно использовать несколько параметров `set`.",
    # --- ## OneAgent restart ---
    "## OneAgent restart": "## Перезапуск OneAgent",
    "When you use the `set` parameters, you need to restart OneAgent service to apply changes. You can use the `--restart-service` parameter with the command that triggers the restart automatically. In some cases you'll also need to restart monitored applications. You can also use the restart parameter on its own, without other parameters. See an example command below.": "При использовании параметров `set` для применения изменений нужно перезапустить сервис OneAgent. Параметр `--restart-service` позволяет выполнить перезапуск автоматически вместе с основной командой. В некоторых случаях также потребуется перезапустить отслеживаемые приложения. Параметр перезапуска можно также использовать отдельно, без других параметров. Пример команды приведён ниже.",
    "* **Linux** or **AIX**:  ": "* **Linux** или **AIX**:  ",
    "`./oneagentctl --set-proxy=my-proxy.com --restart-service`": "`./oneagentctl --set-proxy=my-proxy.com --restart-service`",
    "* **Windows**:  ": "* **Windows**:  ",
    "`.\\.oneagentctl.exe --set-proxy=my-proxy.com --restart-service`": "`.\\.oneagentctl.exe --set-proxy=my-proxy.com --restart-service`",
    # --- ## Display help ---
    "## Display help": "## Отображение справки",
    "Use the `--help` parameter to display all supported parameters.": "Используйте параметр `--help` для отображения всех поддерживаемых параметров.",
    "`./oneagentctl --help`": "`./oneagentctl --help`",
    "`.\\.oneagentctl.exe --help`": "`.\\.oneagentctl.exe --help`",
    # --- ## Display OneAgent version ---
    "## Display OneAgent version": "## Отображение версии OneAgent",
    "Use the `--version` parameter to display the OneAgent version.": "Используйте параметр `--version` для отображения версии OneAgent.",
    "`./oneagentctl --version`": "`./oneagentctl --version`",
    "`.\\.oneagentctl.exe --version`": "`.\\.oneagentctl.exe --version`",
    # --- ## OneAgent communication ---
    "## OneAgent communication": "## Взаимодействие OneAgent",
    # --- ### Set OneAgent communication settings ---
    "### Set OneAgent communication settings": "### Задать параметры взаимодействия OneAgent",
    "Use the `--set-server` parameter to set a OneAgent communication endpoint. Use the IP address or name, combined with the `/communication` suffix. Depending on your deployment, it can be a Dynatrace Server, Dynatrace Managed Cluster, or ActiveGate.": "Используйте параметр `--set-server` для задания endpoint взаимодействия OneAgent. Укажите IP-адрес или имя в сочетании с суффиксом `/communication`. В зависимости от развёртывания это может быть Dynatrace Server, Dynatrace Managed Cluster или ActiveGate.",
    "Run the following command to adjust OneAgent connection settings:": "Выполните следующую команду для изменения настроек подключения OneAgent:",
    "`./oneagentctl --set-server=https://my-server.com:9999/communication --set-tenant=abc123456 --set-tenant-token=abcdefg123456790 --set-proxy=my-proxy.com`": "`./oneagentctl --set-server=https://my-server.com:9999/communication --set-tenant=abc123456 --set-tenant-token=abcdefg123456790 --set-proxy=my-proxy.com`",
    "`.\\.oneagentctl.exe --set-server=https://my-server.com:9999/communication --set-tenant=abc123456 --set-tenant-token=abcdefg123456790 --set-proxy=my-proxy.com`": "`.\\.oneagentctl.exe --set-server=https://my-server.com:9999/communication --set-tenant=abc123456 --set-tenant-token=abcdefg123456790 --set-proxy=my-proxy.com`",
    'To define multiple endpoints, separate them by semicolon and add the quotes. For example, `--set-server="https://server1;https://server2"`.': 'Для задания нескольких endpoint разделите их точкой с запятой и заключите в кавычки. Например: `--set-server="https://server1;https://server2"`.',
    'These parameters require restart of OneAgent, as well as restart of all the applications monitored with deep code modules. Add [`--restart-service`](#oneagent-restart) to the command to restart OneAgent automatically (version 1.189+) or stop and start OneAgent process manually. For OS-specific instructions, see [Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/stop-restart-oneagent-on-linux "Learn how to stop and restart OneAgent on Linux."), [Windows](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/windows/operation/stop-restart-oneagent-on-windows "Learn how to stop and restart OneAgent on Windows."), or [AIX](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/aix/operation/stop-restart-oneagent-on-aix "Learn how to stop and restart OneAgent on AIX.").': 'Эти параметры требуют перезапуска OneAgent, а также перезапуска всех приложений, отслеживаемых с помощью глубоких кодовых модулей. Добавьте [`--restart-service`](#oneagent-restart) к команде для автоматического перезапуска OneAgent (версия 1.189+) или остановите и запустите процесс OneAgent вручную. Инструкции для конкретной ОС см. в разделах [Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/stop-restart-oneagent-on-linux "Узнайте, как остановить и перезапустить OneAgent на Linux."), [Windows](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/windows/operation/stop-restart-oneagent-on-windows "Узнайте, как остановить и перезапустить OneAgent на Windows.") или [AIX](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/aix/operation/stop-restart-oneagent-on-aix "Узнайте, как остановить и перезапустить OneAgent на AIX.").',
    "This command will immediately change the OS module connection endpoint, but the code modules won't be able to read the new setting until the next restart.": "Эта команда немедленно изменит endpoint подключения модуля ОС, однако кодовые модули смогут применить новую настройку только после следующего перезапуска.",
    "OneAgent and Dynatrace Cluster automatically maintain a working connection. If an endpoint detail changes, the cluster notifies OneAgent of the change and OneAgent automatically updates the endpoint you set using the `--set-server` to the new working value.": "OneAgent и Dynatrace Cluster автоматически поддерживают рабочее подключение. При изменении параметров endpoint кластер уведомляет OneAgent, и OneAgent автоматически обновляет endpoint, заданный через `--set-server`, на новое рабочее значение.",
    "Directing OneAgent traffic through ActiveGate": "Направление трафика OneAgent через ActiveGate",
    "Routing OneAgent traffic through an ActiveGate can enhance the security of your data by ensuring it remains within controlled network paths and is encrypted during transmission.": "Маршрутизация трафика OneAgent через ActiveGate позволяет повысить безопасность данных: они остаются в контролируемых сетевых путях и шифруются при передаче.",
    "1. Determine the IP address or hostname of the ActiveGate that will handle traffic.": "1. Определите IP-адрес или имя хоста ActiveGate, который будет обрабатывать трафик.",
    "2. [Set the Communication Endpoint](#set-oneagent-communication-settings).": "2. [Задайте endpoint взаимодействия](#set-oneagent-communication-settings).",
    "Configure OneAgent by specifying the ActiveGate as its new endpoint. For example:": "Настройте OneAgent, указав ActiveGate в качестве нового endpoint. Например:",
    "3. [Check if auto-update is enabled](#check-if-auto-update-is-enabled).": "3. [Проверьте, включено ли автоматическое обновление](#check-if-auto-update-is-enabled).",
    # --- ### Show current communication endpoints ---
    "### Show current communication endpoints": "### Показать текущие endpoint взаимодействия",
    "Use the `--get-server` parameter to display the endpoints that OneAgent is to send the data to. These can be Dynatrace Server, Dynatrace Managed Cluster or ActiveGate.": "Используйте параметр `--get-server` для отображения endpoint, на которые OneAgent отправляет данные. Это может быть Dynatrace Server, Dynatrace Managed Cluster или ActiveGate.",
    "`./oneagentctl --get-server`": "`./oneagentctl --get-server`",
    "`.\\.oneagentctl.exe --get-server`": "`.\\.oneagentctl.exe --get-server`",
    "Starting with OneAgent version 1.207, endpoints are reported using a format in which endpoints of equal priority are grouped using braces (`{...}`) and sorted according to connection priority. An asterisk (`*`) indicates the endpoint to which OneAgent currently sends the data. Endpoints are separated by a semicolon (`;`).": "Начиная с OneAgent версии 1.207 endpoint отображаются в формате, при котором endpoint одинакового приоритета группируются в фигурные скобки (`{...}`) и сортируются по приоритету подключения. Звёздочка (`*`) обозначает endpoint, на который OneAgent в данный момент отправляет данные. Endpoint разделяются точкой с запятой (`;`).",
    "For example:": "Например:",
    # --- ### Set environment ID ---
    "### Set environment ID": "### Задать идентификатор окружения",
    "Use the `--set-tenant` parameter to set an [environment ID](/managed/discover-dynatrace/get-started/monitoring-environment \"Understand and learn how to work with monitoring environments.\"). By default, this is already set to the correct value. If you're selling Dynatrace-based services, use this option to set your customers' IDs from the pool of IDs you purchased from Dynatrace.": 'Используйте параметр `--set-tenant` для задания [идентификатора окружения](/managed/discover-dynatrace/get-started/monitoring-environment "Узнайте, как работать с окружениями мониторинга."). По умолчанию это значение уже задано корректно. Если вы перепродаёте услуги на основе Dynatrace, используйте этот параметр для задания идентификаторов ваших клиентов из пула идентификаторов, приобретённых у Dynatrace.',
    "`./oneagentctl --set-tenant=abc123456`": "`./oneagentctl --set-tenant=abc123456`",
    "`.\\.oneagentctl.exe --set-tenant=abc123456`": "`.\\.oneagentctl.exe --set-tenant=abc123456`",
    'Always use in combination with `--set-tenant-token`, which defines the [tenant token](/managed/manage/identity-access-management/access-tokens-and-oauth-clients/access-tokens/rotate-tenant-token "Learn what a tenant token is and how to change it.") for internal authentication.': 'Всегда используйте в сочетании с `--set-tenant-token`, который задаёт [токен тенанта](/managed/manage/identity-access-management/access-tokens-and-oauth-clients/access-tokens/rotate-tenant-token "Узнайте, что такое токен тенанта и как его изменить.") для внутренней аутентификации.',
    # --- ### Show environment ID ---
    "### Show environment ID": "### Показать идентификатор окружения",
    'The Dynatrace [environment ID](/managed/discover-dynatrace/get-started/monitoring-environment "Understand and learn how to work with monitoring environments.") you received with your activation email.': 'Идентификатор [окружения](/managed/discover-dynatrace/get-started/monitoring-environment "Узнайте, как работать с окружениями мониторинга.") Dynatrace, который вы получили в письме с активацией.',
    "Use the `--get-tenant` parameter to display the environment ID:": "Используйте параметр `--get-tenant` для отображения идентификатора окружения:",
    "`./oneagentctl --get-tenant`": "`./oneagentctl --get-tenant`",
    "`.\\.oneagentctl.exe --get-tenant`": "`.\\.oneagentctl.exe --get-tenant`",
    # --- ### Set tenant token ---
    "### Set tenant token": "### Задать токен тенанта",
    'Use the `--set-tenant-token` parameter to set the [tenant token](/managed/manage/identity-access-management/access-tokens-and-oauth-clients/access-tokens/rotate-tenant-token "Learn what a tenant token is and how to change it."), which is used to authenticate communication with the defined endpoint. Always use in combination with `--set-tenant`.': 'Используйте параметр `--set-tenant-token` для задания [токена тенанта](/managed/manage/identity-access-management/access-tokens-and-oauth-clients/access-tokens/rotate-tenant-token "Узнайте, что такое токен тенанта и как его изменить."), используемого для аутентификации взаимодействия с заданным endpoint. Всегда используйте в сочетании с `--set-tenant`.',
    "`./oneagentctl --set-tenant-token=abcdefg123456790`": "`./oneagentctl --set-tenant-token=abcdefg123456790`",
    "`.\\.oneagentctl.exe --set-tenant-token=abcdefg123456790`": "`.\\.oneagentctl.exe --set-tenant-token=abcdefg123456790`",
    # --- ### Show tenant token ---
    "### Show tenant token": "### Показать токен тенанта",
    "Use the `--get-tenant-token` parameter to display the currently defined token:": "Используйте параметр `--get-tenant-token` для отображения текущего токена:",
    "`./oneagentctl --get-tenant-token`": "`./oneagentctl --get-tenant-token`",
    "`.\\.oneagentctl.exe --get-tenant-token`": "`.\\.oneagentctl.exe --get-tenant-token`",
    # --- ### Set proxy configuration ---
    "### Set proxy configuration": "### Задать конфигурацию прокси",
    "Use the `--set-proxy` parameter to set a proxy server:": "Используйте параметр `--set-proxy` для задания прокси-сервера:",
    "`./oneagentctl --set-proxy=my-proxy.com`": "`./oneagentctl --set-proxy=my-proxy.com`",
    "`.\\.oneagentctl.exe --set-proxy=my-proxy.com`": "`.\\.oneagentctl.exe --set-proxy=my-proxy.com`",
    # --- ### Clear proxy configuration ---
    "### Clear proxy configuration": "### Очистить конфигурацию прокси",
    "Use the `--set-proxy` parameter set to an empty value to clear proxy configuration:": "Используйте параметр `--set-proxy` с пустым значением для очистки конфигурации прокси:",
    "`./oneagentctl --set-proxy=`": "`./oneagentctl --set-proxy=`",
    "`.\\.oneagentctl.exe --set-proxy=`": "`.\\.oneagentctl.exe --set-proxy=`",
    "Restart OneAgent service to apply changes.": "Перезапустите сервис OneAgent для применения изменений.",
    # --- ### Show current proxy ---
    "### Show current proxy": "### Показать текущий прокси",
    "Use the `--get-proxy` parameter to display the currently defined proxy OneAgent connects through:": "Используйте параметр `--get-proxy` для отображения текущего прокси, через который подключается OneAgent:",
    "`./oneagentctl --get-proxy`": "`./oneagentctl --get-proxy`",
    "`.\\.oneagentctl.exe --get-proxy`": "`.\\.oneagentctl.exe --get-proxy`",
    # --- ### Exclude specific IPs from proxy ---
    "### Exclude specific IPs from proxy": "### Исключить определённые IP-адреса из прокси",
    "Use the `--set-no-proxy` parameter to exclude certain domains or IP addresses from using the proxy:": "Используйте параметр `--set-no-proxy` для исключения определённых доменов или IP-адресов из использования прокси:",
    "`./oneagentctl --set-no-proxy=my-proxy.com`": "`./oneagentctl --set-no-proxy=my-proxy.com`",
    "`.\\.oneagentctl.exe --set-no-proxy=my-proxy.com`": "`.\\.oneagentctl.exe --set-no-proxy=my-proxy.com`",
    # --- ### Show current no-proxy settings ---
    "### Show current no-proxy settings": "### Показать текущие настройки no-proxy",
    "Use the `--get-no-proxy` parameter to view the currently configured settings for domains and IP ranges excluded from using the proxy:": "Используйте параметр `--get-no-proxy` для просмотра текущих настроек доменов и диапазонов IP-адресов, исключённых из использования прокси:",
    "`./oneagentctl --get-no-proxy`": "`./oneagentctl --get-no-proxy`",
    "`.\\.oneagentctl.exe --get-no-proxy`": "`.\\.oneagentctl.exe --get-no-proxy`",
    # --- ### Check current port range ---
    "### Check current port range": "### Проверить текущий диапазон портов",
    "OneAgent consists of different processes that communicate via a TCP port with a watchdog. At startup, OneAgent watchdog attempts to open the first available port between port 50000 and 50100. In some cases you may need this port for your own applications that are started after OneAgent.": "OneAgent состоит из различных процессов, взаимодействующих с watchdog через TCP-порт. При запуске watchdog OneAgent пытается открыть первый доступный порт в диапазоне от 50000 до 50100. В некоторых случаях этот порт может потребоваться для ваших приложений, запускаемых после OneAgent.",
    "Use the `--get-watchdog-portrange` parameter to check the current port range defined for the watchdog.": "Используйте параметр `--get-watchdog-portrange` для проверки текущего диапазона портов, заданного для watchdog.",
    "`./oneagentctl --get-watchdog-portrange`": "`./oneagentctl --get-watchdog-portrange`",
    "`.\\.oneagentctl.exe --get-watchdog-portrange`": "`.\\.oneagentctl.exe --get-watchdog-portrange`",
    # --- ### Set a new port range ---
    "### Set a new port range": "### Задать новый диапазон портов",
    "Deprecated": "Устарело",
    "Starting with OneAgent version 1.301, OneAgent doesn't use the TCP ports for its own inter-process communication. In case OneAgent occupies your applications' ports, upgrade OneAgent to version 1.301+.": "Начиная с OneAgent версии 1.301 OneAgent не использует TCP-порты для внутреннего взаимодействия между процессами. Если OneAgent занимает порты ваших приложений, обновите OneAgent до версии 1.301+.",
    "Watchdog is a binary used for starting and monitoring OneAgent monitoring processes:": "Watchdog, это исполняемый файл, используемый для запуска и мониторинга процессов OneAgent:",
    "* `oneagentos`\xe2operating system monitoring": "* `oneagentos`, мониторинг операционной системы",
    '* `oneagentplugin`\xe2monitoring using [OneAgent extensions](/managed/ingest-from/extensions/develop-your-extensions#oneagent-extensions "Develop your own Extensions in Dynatrace.")': '* `oneagentplugin`, мониторинг с помощью [расширений OneAgent](/managed/ingest-from/extensions/develop-your-extensions#oneagent-extensions "Разрабатывайте собственные расширения в Dynatrace.")',
    '* `oneagentextensions`\xe2monitoring using local [Extensions](/managed/ingest-from/extensions "Learn how to create and manage Dynatrace Extensions.")': '* `oneagentextensions`, мониторинг с помощью локальных [расширений](/managed/ingest-from/extensions "Узнайте, как создавать расширения Dynatrace и управлять ими.")',
    '* `oneagentloganalytics`\xe2[Log Monitoring](/managed/analyze-explore-automate/log-monitoring "Learn how to enable Log Monitoring, the insights that Log Monitoring can provide, and more.")': '* `oneagentloganalytics`, [мониторинг журналов](/managed/analyze-explore-automate/log-monitoring "Узнайте, как включить мониторинг журналов и какие возможности он предоставляет.")',
    '* `oneagentnetwork`\xe2[network monitoring](/managed/observe/infrastructure-observability/networks "Learn how to monitor network communications.")': '* `oneagentnetwork`, [мониторинг сети](/managed/observe/infrastructure-observability/networks "Узнайте, как вести мониторинг сетевых коммуникаций.")',
    "Use the `--set-watchdog-portrange=arg` parameter to change the watchdog listening port range to `<arg>`. The `<arg>` must contain two port numbers separated by a colon (`:`). For example `50000:50100`. The maximum supported port range is from 1024 to 65535. The port range must cover at least 4 ports. The port number starting the range must be lower.": "Используйте параметр `--set-watchdog-portrange=arg` для изменения диапазона прослушиваемых портов watchdog на `<arg>`. Значение `<arg>` должно содержать два номера портов, разделённых двоеточием (`:`). Например: `50000:50100`. Максимально поддерживаемый диапазон: от 1024 до 65535. Диапазон должен включать не менее 4 портов. Начальный номер порта должен быть меньше конечного.",
    "`./oneagentctl --set-watchdog-portrange=50000:50100`": "`./oneagentctl --set-watchdog-portrange=50000:50100`",
    "`.\\.oneagentctl.exe --set-watchdog-portrange=50000:50100`": "`.\\.oneagentctl.exe --set-watchdog-portrange=50000:50100`",
    # --- ## Automatic updates ---
    "## Automatic updates": "## Автоматические обновления",
    'For more information, see update OneAgent topics for [Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/update-oneagent-on-linux "Learn about the different ways to update OneAgent on Linux."), [Windows](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/windows/operation/update-oneagent-on-windows "Learn about the different ways to update Dynatrace OneAgent on Windows."), and [AIX](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/aix/operation/update-oneagent-on-aix "Learn how you can update Dynatrace OneAgent on AIX.").': 'Подробнее см. в разделах обновления OneAgent: [Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/update-oneagent-on-linux "Узнайте о различных способах обновления OneAgent на Linux."), [Windows](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/windows/operation/update-oneagent-on-windows "Узнайте о различных способах обновления Dynatrace OneAgent на Windows.") и [AIX](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/aix/operation/update-oneagent-on-aix "Узнайте, как обновить Dynatrace OneAgent на AIX.").',
    # --- ### Check if auto-update is enabled ---
    "### Check if auto-update is enabled": "### Проверить, включено ли автоматическое обновление",
    "Use the `get-auto-update-enabled` parameter to check whether OneAgent auto-update is enabled:": "Используйте параметр `get-auto-update-enabled` для проверки того, включено ли автоматическое обновление OneAgent:",
    "`./oneagentctl --get-auto-update-enabled`": "`./oneagentctl --get-auto-update-enabled`",
    "`.\\.oneagentctl.exe --get-auto-update-enabled`": "`.\\.oneagentctl.exe --get-auto-update-enabled`",
    # --- ### Enable or disable auto-update ---
    "### Enable or disable auto-update": "### Включить или отключить автоматическое обновление",
    "Set the `--set-auto-update-enabled` parameter to `true` or `false` to disable or enable OneAgent auto-update:": "Установите параметр `--set-auto-update-enabled` в `true` или `false` для включения или отключения автоматического обновления OneAgent:",
    "`./oneagentctl --set-auto-update-enabled=true`": "`./oneagentctl --set-auto-update-enabled=true`",
    "`.\\.oneagentctl.exe --set-auto-update-enabled=true`": "`.\\.oneagentctl.exe --set-auto-update-enabled=true`",
    "After you use this command to disable auto-updates, you won't be able to control OneAgent automatic updates using Dynatrace at **Settings** > **Updates** > **OneAgent updates**.": "После отключения автоматических обновлений этой командой управление ими через Dynatrace по пути **Settings** > **Updates** > **OneAgent updates** станет недоступным.",
    # --- ## Log monitoring ---
    "## Log monitoring": "## Мониторинг журналов",
    "For more information, see [Log Monitoring\xef\xbb\xbf](https://docs.dynatrace.com/docs/shortlink/log-management-and-analytics).": "Подробнее см. [Мониторинг журналов](https://docs.dynatrace.com/docs/shortlink/log-management-and-analytics).",
    # --- ### Check if Log Monitoring is enabled ---
    "### Check if Log Monitoring is enabled": "### Проверить, включён ли мониторинг журналов",
    "Use the `--get-app-log-content-access` parameter to check whether Log Monitoring is enabled:": "Используйте параметр `--get-app-log-content-access` для проверки того, включён ли мониторинг журналов:",
    "* **Linux**:  ": "* **Linux**:  ",
    "`./oneagentctl --get-app-log-content-access`": "`./oneagentctl --get-app-log-content-access`",
    "`.\\.oneagentctl.exe --get-app-log-content-access`": "`.\\.oneagentctl.exe --get-app-log-content-access`",
    # --- ### Enable or disable Log Monitoring ---
    "### Enable or disable Log Monitoring": "### Включить или отключить мониторинг журналов",
    "Set the `--set-app-log-content-access` parameter to `true` or `false` to disable or enable Log Monitoring:": "Установите параметр `--set-app-log-content-access` в `true` или `false` для включения или отключения мониторинга журналов:",
    "* **Linux**:": "* **Linux**:",
    "`./oneagentctl --set-app-log-content-access=true`": "`./oneagentctl --set-app-log-content-access=true`",
    "`.\\.oneagentctl.exe --set-app-log-content-access=true`": "`.\\.oneagentctl.exe --set-app-log-content-access=true`",
    # --- ## Create support archive ---
    "## Create support archive": "## Создать архив поддержки",
    "OneAgent version 1.225+": "OneAgent версии 1.225+",
    'If you don\'t have access to Dynatrace or you would like to script diagnostic data collection, you can use the `oneagentctl` command to collect a [subset](#contents) of the full [OneAgent diagnostics](/managed/ingest-from/dynatrace-oneagent/oneagent-troubleshooting/oneagent-diagnostics "Learn how to run OneAgent diagnostics") data right on the host where OneAgent is installed. With the diagnostic data collected for OneAgent, you can:': 'Если доступ к Dynatrace отсутствует или нужно автоматизировать сбор диагностических данных, используйте команду `oneagentctl` для сбора [подмножества](#contents) данных полной [диагностики OneAgent](/managed/ingest-from/dynatrace-oneagent/oneagent-troubleshooting/oneagent-diagnostics "Узнайте, как выполнять диагностику OneAgent.") прямо на хосте, где установлен OneAgent. После сбора диагностических данных можно:',
    "* Easily collect the diagnostic data for a specific host": "* Легко собирать диагностические данные для конкретного хоста",
    "* Directly provide Dynatrace Support the details they need to diagnose the issue": "* Напрямую предоставить в Dynatrace Support все необходимые для диагностики подробности",
    "The command requires the OneAgent service to be running.": "Для выполнения команды сервис OneAgent должен быть запущен.",
    "To create a support archive with diagnostic data, run `oneagentctl` with the `--create-support-archive` parameter. By default, the support archive contains the data for a 7-day time frame and is created in the current working directory. Optionally, you can set a custom directory and timeframe with the `directory` and `days` parameters. Note that `onegentctl` won't create a directory; you must point it to an existing directory with a relative or absolute path. For example:": "Для создания архива поддержки с диагностическими данными запустите `oneagentctl` с параметром `--create-support-archive`. По умолчанию архив поддержки содержит данные за 7 дней и создаётся в текущем рабочем каталоге. При необходимости можно задать собственный каталог и период с помощью параметров `directory` и `days`. Обратите внимание, что `oneagentctl` не создаёт каталог самостоятельно: нужно указать путь к уже существующему каталогу (относительный или абсолютный). Например:",
    "`./oneagentctl --create-support-archive directory=/data/support-archive days=30`": "`./oneagentctl --create-support-archive directory=/data/support-archive days=30`",
    "`.\\.oneagentctl.exe --create-support-archive directory=C:\\data\\support-archive days=30`": "`.\\.oneagentctl.exe --create-support-archive directory=C:\\data\\support-archive days=30`",
    "The command saves the archive as the `support_archive_agent_YYYY-MM-DD_hhmmss.zip` file. For example:": "Команда сохраняет архив в файл `support_archive_agent_YYYY-MM-DD_hhmmss.zip`. Например:",
    # --- ### Contents of diagnostic data ---
    "### Contents of diagnostic data": "### Содержимое диагностических данных",
    'All the collected diagnostic data is compressed into a `support_archive_agent_YYYY-MM-DD_hhmmss.zip` archive that includes the following subset of the full [OneAgent diagnostics](/managed/ingest-from/dynatrace-oneagent/oneagent-troubleshooting/oneagent-diagnostics "Learn how to run OneAgent diagnostics") data:': 'Все собранные диагностические данные сжимаются в архив `support_archive_agent_YYYY-MM-DD_hhmmss.zip`, который включает следующее подмножество данных полной [диагностики OneAgent](/managed/ingest-from/dynatrace-oneagent/oneagent-troubleshooting/oneagent-diagnostics "Узнайте, как выполнять диагностику OneAgent."):',
    "| Folder or file | Description |": "| Папка или файл | Описание |",
    "| --- | --- |": "| --- | --- |",
    "| `support_archive` (ZIP) | Contains the local configuration of the OneAgent installed on the host or process where you\xe2ve run the troubleshooting, as well as the OneAgent-related log files. |": "| `support_archive` (ZIP) | Содержит локальную конфигурацию OneAgent, установленного на хосте или в процессе, для которых выполнялась диагностика, а также связанные с OneAgent файлы журналов. |",
    "| `diagnostic_files` (ZIP) | Contains information about process group detection, auto-injection problems, and extension configuration. |": "| `diagnostic_files` (ZIP) | Содержит информацию об обнаружении групп процессов, проблемах автоматической инъекции и конфигурации расширений. |",
    # --- ## Access to system logs ---
    "## Access to system logs for proactive support": "## Доступ к системным журналам для проактивной поддержки",
    "OneAgent downloads specific system logs so that Dynatrace can diagnose issues that may be caused by conditions in your environment. The logs are also saved in the support archive. Most often such issues are related to deep monitoring or auto-update installations.": "OneAgent загружает определённые системные журналы, чтобы Dynatrace мог диагностировать проблемы, вызванные условиями в вашем окружении. Журналы также сохраняются в архиве поддержки. Чаще всего такие проблемы связаны с глубоким мониторингом или установками автоматических обновлений.",
    # --- ### Check if access to system logs is enabled ---
    "### Check if access to system logs is enabled": "### Проверить, включён ли доступ к системным журналам",
    "Use the `--get-system-logs-access-enabled` parameter to check whether access to system logs is enabled:": "Используйте параметр `--get-system-logs-access-enabled` для проверки того, включён ли доступ к системным журналам:",
    "`./oneagentctl --get-system-logs-access-enabled`": "`./oneagentctl --get-system-logs-access-enabled`",
    "`.\\.oneagentctl.exe --get-system-logs-access-enabled`": "`.\\.oneagentctl.exe --get-system-logs-access-enabled`",
    # --- ### Enable or disable access to system logs ---
    "### Enable or disable access to system logs": "### Включить или отключить доступ к системным журналам",
    "Set the `--set-system-logs-access-enabled` parameter to `true` or `false` to disable or enable access to system logs:": "Установите параметр `--set-system-logs-access-enabled` в `true` или `false` для включения или отключения доступа к системным журналам:",
    "`./oneagentctl --set-system-logs-access-enabled=true`": "`./oneagentctl --set-system-logs-access-enabled=true`",
    "`.\\.oneagentctl.exe --set-system-logs-access-enabled=true`": "`.\\.oneagentctl.exe --set-system-logs-access-enabled=true`",
    "Restart OneAgent service to apply changes.": "Перезапустите сервис OneAgent для применения изменений.",
    "Note that the `--set-system-logs-access-enabled` and `--get-system-logs-access-enabled` parameters refer to a self-diagnostics setting and are not related to [Log Monitoring](#log-monitoring).": "Параметры `--set-system-logs-access-enabled` и `--get-system-logs-access-enabled` относятся к настройке самодиагностики и не связаны с [мониторингом журналов](#log-monitoring).",
    "Disabling system log access limits our ability to diagnose and solve issues proactively. With access to system logs revoked, you may need to manually provide Dynatrace with the contents of your system logs to help us diagnose issues within your environment.": "Отключение доступа к системным журналам ограничивает возможности проактивной диагностики и устранения неполадок. При отозванном доступе к системным журналам может потребоваться передать содержимое системных журналов в Dynatrace вручную для диагностики проблем в вашем окружении.",
    # --- ## Host ID ---
    "## Host ID": "## Идентификатор хоста",
    'Dynatrace assigns a unique ID to each host monitored in your environment. Host IDs can be used as parameters in Dynatrace API requests, for example [Topology and Smartscape API - Hosts API](/managed/dynatrace-api/environment-api/topology-and-smartscape/hosts-api "Learn how you can use the Dynatrace API to manage monitored hosts."). The host ID also constitutes the URL of the **Host overview** page, for example, `https://environment.org/#newhosts/hostdetails;id=HOST-6E56EE455C84E232`.': 'Dynatrace присваивает уникальный идентификатор каждому хосту, отслеживаемому в вашем окружении. Идентификаторы хостов можно использовать в качестве параметров в запросах к Dynatrace API, например [Topology and Smartscape API - Hosts API](/managed/dynatrace-api/environment-api/topology-and-smartscape/hosts-api "Узнайте, как использовать Dynatrace API для управления отслеживаемыми хостами."). Идентификатор хоста также является частью URL страницы **Host overview**, например: `https://environment.org/#newhosts/hostdetails;id=HOST-6E56EE455C84E232`.',
    # --- ### Display your host ID ---
    "### Display your host ID": "### Отобразить идентификатор хоста",
    "To find a host ID, use the `--get-host-id` parameter. For example:": "Для получения идентификатора хоста используйте параметр `--get-host-id`. Например:",
    "`./oneagentctl --get-host-id`": "`./oneagentctl --get-host-id`",
    "`.\\.oneagentctl.exe --get-host-id`": "`.\\.oneagentctl.exe --get-host-id`",
    # --- ### Define the host ID source ---
    "### Define the host ID source": "### Определить источник идентификатора хоста",
    "Available on all supported platforms for OneAgent version 1.223+. For OneAgent version 1.221 and earlier, this feature is supported only for Citrix Virtual Apps and Desktops.": "Доступно на всех поддерживаемых платформах для OneAgent версии 1.223+. Для OneAgent версии 1.221 и более ранних эта функция поддерживается только для Citrix Virtual Apps and Desktops.",
    "It's particularly important to keep your host ID static in dynamic virtual environments where hosts are recreated on a daily basis.": "Сохранение статического идентификатора хоста особенно важно в динамических виртуальных окружениях, где хосты пересоздаются ежедневно.",
    "To **define the source for host ID generation**, use `--set-host-id-source` and set it to one of the predefined values:": "Для **определения источника генерации идентификатора хоста** используйте `--set-host-id-source` и задайте одно из предопределённых значений:",
    "* `auto` \xe2 Let Dynatrace generate the host ID automatically": "* `auto`, Dynatrace генерирует идентификатор хоста автоматически",
    "* `ip-addresses` \xe2 Generate host ID based on the host IP address": "* `ip-addresses`, идентификатор хоста генерируется на основе IP-адреса хоста",
    "* `mac-addresses` \xe2 Generate host ID based on the host's NIC MAC address": "* `mac-addresses`, идентификатор хоста генерируется на основе MAC-адреса сетевого адаптера хоста",
    "* `fqdn` \xe2 Generate host ID based on the host fully qualified domain name (FQDN) in the `host.domain` format. If the FQDN doesn't contain a dot character, the NIC MAC address is used instead.": "* `fqdn`, идентификатор хоста генерируется на основе полного доменного имени (FQDN) хоста в формате `host.domain`. Если FQDN не содержит точки, используется MAC-адрес сетевого адаптера.",
    "* If you monitor multiple environments, you can split the hosts with identical IPs, MAC addresses, or FQDNs using a different namespace for each environment. The namespace can contain only alphanumeric characters, hyphens, underscores, and periods; the maximum length is 256 characters.": "* При мониторинге нескольких окружений можно разделить хосты с одинаковыми IP-адресами, MAC-адресами или FQDN, задав разные пространства имён для каждого окружения. Пространство имён может содержать только буквенно-цифровые символы, дефисы, знаки подчёркивания и точки; максимальная длина: 256 символов.",
    "+ `ip-addresses;namespace=<namespace>`": "+ `ip-addresses;namespace=<namespace>`",
    "+ `mac-addresses;namespace=<namespace>`": "+ `mac-addresses;namespace=<namespace>`",
    "+ `fqdn;namespace=<namespace>`": "+ `fqdn;namespace=<namespace>`",
    "For example, to set the host ID source to `ip-addresses` and assign it to a namespace called `test`, run `oneagentctl` with the following parameter:": "Например, чтобы задать `ip-addresses` в качестве источника идентификатора хоста и назначить пространство имён `test`, запустите `oneagentctl` со следующим параметром:",
    '`./oneagentctl --set-host-id-source="ip-addresses;namespace=test"`': '`./oneagentctl --set-host-id-source="ip-addresses;namespace=test"`',
    '`.\\.oneagentctl.exe --set-host-id-source="ip-addresses;namespace=test"`': '`.\\.oneagentctl.exe --set-host-id-source="ip-addresses;namespace=test"`',
    'After you change the host ID source, you must restart all your monitored applications and then restart the OneAgent service to create the new host entity in your environment. You can use the `--restart-service` parameter with `oneagentctl` to restart OneAgent automatically or stop and start OneAgent process manually. For OS-specific instructions, see [Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/stop-restart-oneagent-on-linux "Learn how to stop and restart OneAgent on Linux."), [Windows](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/windows/operation/stop-restart-oneagent-on-windows "Learn how to stop and restart OneAgent on Windows."), or [AIX](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/aix/operation/stop-restart-oneagent-on-aix "Learn how to stop and restart OneAgent on AIX.").': 'После изменения источника идентификатора хоста нужно перезапустить все отслеживаемые приложения, а затем перезапустить сервис OneAgent для создания новой сущности хоста в вашем окружении. Используйте параметр `--restart-service` с `oneagentctl` для автоматического перезапуска OneAgent или остановите и запустите процесс OneAgent вручную. Инструкции для конкретной ОС см. в разделах [Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/stop-restart-oneagent-on-linux "Узнайте, как остановить и перезапустить OneAgent на Linux."), [Windows](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/windows/operation/stop-restart-oneagent-on-windows "Узнайте, как остановить и перезапустить OneAgent на Windows.") или [AIX](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/aix/operation/stop-restart-oneagent-on-aix "Узнайте, как остановить и перезапустить OneAgent на AIX.").',
    "To **check the host ID source**, use the `--get-host-id-source` parameter:": "Для **проверки источника идентификатора хоста** используйте параметр `--get-host-id-source`:",
    "`./oneagentctl --get-host-id-source`": "`./oneagentctl --get-host-id-source`",
    "`.\\.oneagentctl.exe --get-host-id-source`": "`.\\.oneagentctl.exe --get-host-id-source`",
    "For host ID source set to `ip-addresses` and the `test` namespace, the command will return the following result:": "Для источника идентификатора хоста `ip-addresses` с пространством имён `test` команда вернёт следующий результат:",
    # --- ## Host groups ---
    "## Host groups": "## Группы хостов",
    'For an overview of how to use host groups, see [Organize your environment using host groups](/managed/observe/infrastructure-observability/hosts/configuration/organize-your-environment-using-host-groups "Find out how Dynatrace enables you to organize your hosts, processes, and services using host groups.").': 'Обзор использования групп хостов см. в разделе [Организация окружения с помощью групп хостов](/managed/observe/infrastructure-observability/hosts/configuration/organize-your-environment-using-host-groups "Узнайте, как Dynatrace позволяет организовывать хосты, процессы и сервисы с помощью групп хостов.").',
    'Alternatively, to modify host group assignment centrally from the Dynatrace Cluster, you can use [Remote configuration management](/managed/ingest-from/bulk-configuration#configure-oneagents "Perform OneAgent and ActiveGate configuration on hosts from the Deployment status page or at scale using the Dynatrace API.") (select the **modify host group** action).': 'Для централизованного изменения назначения групп хостов из Dynatrace Cluster можно использовать [удалённое управление конфигурацией](/managed/ingest-from/bulk-configuration#configure-oneagents "Настраивайте OneAgent и ActiveGate на хостах со страницы статуса развёртывания или массово через Dynatrace API.") (действие **modify host group**).',
    # --- ### Change host group assignment ---
    "### Change host group assignment": "### Изменить назначение группы хостов",
    "Use the `--set-host-group` parameter to change the host group assignment.": "Используйте параметр `--set-host-group` для изменения назначения группы хостов.",
    "To assign the host to `MyHostGroup`:": "Для назначения хоста в `MyHostGroup`:",
    "`./oneagentctl --set-host-group=MyHostGroup`": "`./oneagentctl --set-host-group=MyHostGroup`",
    "`.\\.oneagentctl.exe --set-host-group=MyHostGroup`": "`.\\.oneagentctl.exe --set-host-group=MyHostGroup`",
    "Host group string requirements:": "Требования к строке группы хостов:",
    "* Can contain only alphanumeric characters, hyphens, underscores, and periods": "* Может содержать только буквенно-цифровые символы, дефисы, знаки подчёркивания и точки",
    "* Must not start with `dt.`": "* Не должна начинаться с `dt.`",
    "* Maximum length is 100 characters": "* Максимальная длина: 100 символов",
    'Using `--set-host-group` requires restart of OneAgent, as well as restart of all the monitored services. Add [`--restart-service`](#oneagent-restart) to the command to restart OneAgent automatically (version 1.189+) or stop and start OneAgent process manually. For OS-specific instructions, see [Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/stop-restart-oneagent-on-linux "Learn how to stop and restart OneAgent on Linux."), [Windows](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/windows/operation/stop-restart-oneagent-on-windows "Learn how to stop and restart OneAgent on Windows."), or [AIX](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/aix/operation/stop-restart-oneagent-on-aix "Learn how to stop and restart OneAgent on AIX.").': 'Использование `--set-host-group` требует перезапуска OneAgent, а также перезапуска всех отслеживаемых сервисов. Добавьте [`--restart-service`](#oneagent-restart) к команде для автоматического перезапуска OneAgent (версия 1.189+) или остановите и запустите процесс OneAgent вручную. Инструкции для конкретной ОС см. в разделах [Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/stop-restart-oneagent-on-linux "Узнайте, как остановить и перезапустить OneAgent на Linux."), [Windows](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/windows/operation/stop-restart-oneagent-on-windows "Узнайте, как остановить и перезапустить OneAgent на Windows.") или [AIX](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/aix/operation/stop-restart-oneagent-on-aix "Узнайте, как остановить и перезапустить OneAgent на AIX.").',
    'Changing the host group assignments results in recalculation of process group IDs, which impacts data aggregation. To read more about the impact of host group changes on process group detection, see [Organize your environment using host groups](/managed/observe/infrastructure-observability/hosts/configuration/organize-your-environment-using-host-groups#how-host-groups-affect-your-monitoring-environment "Find out how Dynatrace enables you to organize your hosts, processes, and services using host groups.").': 'Изменение назначения группы хостов приводит к пересчёту идентификаторов групп процессов, что влияет на агрегацию данных. Подробнее о влиянии изменений групп хостов на обнаружение групп процессов см. в разделе [Организация окружения с помощью групп хостов](/managed/observe/infrastructure-observability/hosts/configuration/organize-your-environment-using-host-groups#how-host-groups-affect-your-monitoring-environment "Узнайте, как Dynatrace позволяет организовывать хосты, процессы и сервисы с помощью групп хостов.").',
    # --- ### Clear host group assignment ---
    "### Clear host group assignment": "### Очистить назначение группы хостов",
    "Use the `--set-host-group` parameter with an empty value to clear the host group assignment:": "Используйте параметр `--set-host-group` с пустым значением для удаления назначения группы хостов:",
    "`./oneagentctl --set-host-group=`": "`./oneagentctl --set-host-group=`",
    "`.\\.oneagentctl.exe --set-host-group=`": "`.\\.oneagentctl.exe --set-host-group=`",
    # --- ### Display host group assignment ---
    "### Display host group assignment": "### Отобразить назначение группы хостов",
    "Use the `--get-host-group` parameter to display the current host group assignment:": "Используйте параметр `--get-host-group` для отображения текущего назначения группы хостов:",
    "`./oneagentctl --get-host-group`": "`./oneagentctl --get-host-group`",
    "`.\\.oneagentctl.exe --get-host-group`": "`.\\.oneagentctl.exe --get-host-group`",
    # --- ## Host tags and metadata ---
    "## Host tags and metadata": "## Теги и метаданные хоста",
    "Within dynamic or large environments, manual host tagging can be impractical. For dynamic deployments that include frequently changing host instances and names (for example, AWS or MS Azure), you can use dedicated `oneagentctl` parameters to apply custom tags, names, and metadata to your hosts.": "В динамических или крупных окружениях ручная расстановка тегов на хостах может быть нецелесообразной. Для динамических развёртываний с часто меняющимися экземплярами хостов и именами (например, AWS или MS Azure) используйте специальные параметры `oneagentctl` для применения пользовательских тегов, имён и метаданных к хостам.",
    "The `oneagentctl` methods listed below allow only for editing the metadata added using `oneagentctl` itself or previously using the configuration files. Tags and metadata added using Dynatrace, as well as retrieved from a monitored environment (for example the AWS tags) are not editable with `oneagentctl` and won't be displayed using `--get-host-tags` and `--get-host-properties` parameters.": "Перечисленные ниже методы `oneagentctl` позволяют редактировать только метаданные, добавленные с помощью самого `oneagentctl` или ранее через конфигурационные файлы. Теги и метаданные, добавленные через Dynatrace или полученные из отслеживаемого окружения (например, теги AWS), не редактируются через `oneagentctl` и не отображаются параметрами `--get-host-tags` и `--get-host-properties`.",
    # --- ### Cloud metadata detection ---
    "### Cloud metadata detection": "### Обнаружение метаданных облака",
    "By default, the `oneagentos` process automatically detects cloud environments such as AWS, Azure, and Google Compute Engine. It sends requests to the dedicated Metadata API located at the internal IP address `169.254.169.254`. The OneAgent uses the retrieved metadata to provide additional context about the monitored resources within these environments.": "По умолчанию процесс `oneagentos` автоматически определяет облачные окружения, такие как AWS, Azure и Google Compute Engine. Он отправляет запросы к специальному Metadata API по внутреннему IP-адресу `169.254.169.254`. OneAgent использует полученные метаданные для предоставления дополнительного контекста об отслеживаемых ресурсах в этих окружениях.",
    # --- ### Custom host name ---
    "### Custom host name": "### Пользовательское имя хоста",
    "Use the `oneagentctl` command-line tool with the `--set-host-name` parameter to override an automatically detected host name. A host name must not contain the `<`, `>`, `&`, `CR` (carriage return), or `LF` (line feed) characters. The maximum length is 256 characters.": "Используйте инструмент командной строки `oneagentctl` с параметром `--set-host-name` для переопределения автоматически обнаруженного имени хоста. Имя хоста не должно содержать символы `<`, `>`, `&`, `CR` (возврат каретки) или `LF` (перевод строки). Максимальная длина: 256 символов.",
    'This command adds a custom host name to display in the UI, but the detected host name is not changed. For details, see [Set custom host names](/managed/observe/infrastructure-observability/hosts/configuration/set-custom-host-names-in-dynamic-environments "Learn how to change a monitored host name.").': 'Эта команда добавляет пользовательское имя хоста для отображения в UI, не изменяя обнаруженное имя. Подробнее см. в разделе [Задание пользовательских имён хостов](/managed/observe/infrastructure-observability/hosts/configuration/set-custom-host-names-in-dynamic-environments "Узнайте, как изменить имя отслеживаемого хоста.").',
    "To change the host name:": "Для изменения имени хоста:",
    "* **Linux** or **AIX**:": "* **Linux** или **AIX**:",
    "`./oneagentctl --set-host-name=myhostname`": "`./oneagentctl --set-host-name=myhostname`",
    "* **Windows**:": "* **Windows**:",
    "`.\\.oneagentctl.exe --set-host-name=myhostname`": "`.\\.oneagentctl.exe --set-host-name=myhostname`",
    'To revert to the auto-detected host name, set the `--set-host-name` parameter to an empty value, as in `--set-host-name=""`. For example:': 'Для возврата к автоматически определённому имени хоста задайте параметру `--set-host-name` пустое значение: `--set-host-name=""`. Например:',
    '`./oneagentctl --set-host-name=""`': '`./oneagentctl --set-host-name=""`',
    '`.\\.oneagentctl.exe --set-host-name=""`': '`.\\.oneagentctl.exe --set-host-name=""`',
    "The change might not be reflected in the Dynatrace web UI for up to 6 minutes.": "Изменение может отобразиться в веб-интерфейсе Dynatrace с задержкой до 6 минут.",
    'Using `--set-host-name` requires restart of OneAgent. Add `--restart-service` to the command to restart OneAgent automatically (version 1.189+) or stop and start the OneAgent process manually. For OS-specific instructions, see [Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/stop-restart-oneagent-on-linux "Learn how to stop and restart OneAgent on Linux."), [Windows](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/windows/operation/stop-restart-oneagent-on-windows "Learn how to stop and restart OneAgent on Windows."), or [AIX](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/aix/operation/stop-restart-oneagent-on-aix "Learn how to stop and restart OneAgent on AIX.").': 'Использование `--set-host-name` требует перезапуска OneAgent. Добавьте `--restart-service` к команде для автоматического перезапуска OneAgent (версия 1.189+) или остановите и запустите процесс OneAgent вручную. Инструкции для конкретной ОС см. в разделах [Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/stop-restart-oneagent-on-linux "Узнайте, как остановить и перезапустить OneAgent на Linux."), [Windows](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/windows/operation/stop-restart-oneagent-on-windows "Узнайте, как остановить и перезапустить OneAgent на Windows.") или [AIX](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/aix/operation/stop-restart-oneagent-on-aix "Узнайте, как остановить и перезапустить OneAgent на AIX.").',
    "To show the host name:": "Для отображения имени хоста:",
    "`./oneagentctl --get-host-name`": "`./oneagentctl --get-host-name`",
    "`.\\.oneagentctl.exe --get-host-name`": "`.\\.oneagentctl.exe --get-host-name`",
    # --- ### Custom host metadata ---
    "### Custom host metadata": "### Пользовательские метаданные хоста",
    "Once configured, custom metadata is displayed as a set of properties at the bottom of the **Properties and tags** section of the host overview page. The property values must not contain an `=` character (unless used as a key-value delimiter) or whitespace characters. The maximum length is 256 characters, including the key-value delimiter. The key name must not start with a `#` character.": "После настройки пользовательские метаданные отображаются как набор свойств в нижней части раздела **Properties and tags** страницы обзора хоста. Значения свойств не должны содержать символ `=` (если только он не используется как разделитель ключа и значения) или пробельные символы. Максимальная длина: 256 символов, включая разделитель ключа и значения. Имя ключа не должно начинаться с символа `#`.",
    'Alternatively, to modify host metadata centrally from the Dynatrace Cluster, you can use [Remote configuration management](/managed/ingest-from/bulk-configuration#configure-oneagents "Perform OneAgent and ActiveGate configuration on hosts from the Deployment status page or at scale using the Dynatrace API.") (select the **modify host properties** action).': 'Для централизованного изменения метаданных хоста из Dynatrace Cluster можно использовать [удалённое управление конфигурацией](/managed/ingest-from/bulk-configuration#configure-oneagents "Настраивайте OneAgent и ActiveGate на хостах со страницы статуса развёртывания или массово через Dynatrace API.") (действие **modify host properties**).',
    'For versions earlier than 1.189, use a [host metadata configuration file](/managed/observe/infrastructure-observability/hosts/configuration/define-tags-and-metadata-for-hosts#edit-the-host-metadata-configuration-file "Learn how to tag and set additional properties for a monitored host.").': 'Для версий ниже 1.189 используйте [файл конфигурации метаданных хоста](/managed/observe/infrastructure-observability/hosts/configuration/define-tags-and-metadata-for-hosts#edit-the-host-metadata-configuration-file "Узнайте, как задавать теги и дополнительные свойства для отслеживаемого хоста.").',
    "To **add or change host properties**, run the following command:": "Для **добавления или изменения свойств хоста** выполните следующую команду:",
    "* **Linux** and **AIX**  ": "* **Linux** и **AIX**  ",
    "`./oneagentctl --set-host-property=AppName --set-host-property=Environment=Dev`": "`./oneagentctl --set-host-property=AppName --set-host-property=Environment=Dev`",
    "* **Windows**  ": "* **Windows**  ",
    "`.\\.oneagentctl.exe --set-host-property=AppName --set-host-property Environment=Dev`": "`.\\.oneagentctl.exe --set-host-property=AppName --set-host-property Environment=Dev`",
    "You can add or change more than one property in the same command.": "В одной команде можно добавить или изменить несколько свойств.",
    "Set a security context for your host": "Задать контекст безопасности для хоста",
    "To set a security context for your host, use the following command:": "Для задания контекста безопасности для хоста используйте следующую команду:",
    "`./oneagentctl --set-host-property=dt.security_context=easytrade_sec`": "`./oneagentctl --set-host-property=dt.security_context=easytrade_sec`",
    "`.\\.oneagentctl.exe --set-host-property=dt.security_context=easytrade_sec`": "`.\\.oneagentctl.exe --set-host-property=dt.security_context=easytrade_sec`",
    "To **remove host properties**, run the following command:": "Для **удаления свойств хоста** выполните следующую команду:",
    "`./oneagentctl --remove-host-property=AppName --remove-host-property=Environment=Dev`": "`./oneagentctl --remove-host-property=AppName --remove-host-property=Environment=Dev`",
    "`.\\.oneagentctl.exe --remove-host-property=AppName --remove-host-property=Environment=Dev`": "`.\\.oneagentctl.exe --remove-host-property=AppName --remove-host-property=Environment=Dev`",
    "You can remove more than one property with a single command. If a property key that's passed in the command doesn't exist, a non-zero exit code will be returned, but all the existing properties passed in the command will be removed. After you remove host properties, they remain visible in Dynatrace for up to 7 hours.": "В одной команде можно удалить несколько свойств. Если ключ свойства, переданный в команде, не существует, будет возвращён ненулевой код выхода, однако все существующие свойства, указанные в команде, будут удалены. После удаления свойства остаются видимы в Dynatrace до 7 часов.",
    "To **show all properties** configured for the host, run the following command:": "Для **отображения всех свойств**, настроенных для хоста, выполните следующую команду:",
    "`./oneagentctl --get-host-properties`": "`./oneagentctl --get-host-properties`",
    "`.\\.oneagentctl.exe --get-host-properties`": "`.\\.oneagentctl.exe --get-host-properties`",
    # --- ### Custom host tags ---
    "### Custom host tags": "### Пользовательские теги хоста",
    "After you configure custom host tags, they are displayed at the top of the **Properties and tags** section of the host overview page. A property value must not contain `=` (unless used as a key-value delimiter) or whitespace characters. The maximum length is 256 characters, including the key-value delimiter. A key name must not start with `#`.": "После настройки пользовательские теги хоста отображаются в верхней части раздела **Properties and tags** страницы обзора хоста. Значение свойства не должно содержать `=` (если только он не используется как разделитель ключа и значения) или пробельные символы. Максимальная длина: 256 символов, включая разделитель ключа и значения. Имя ключа не должно начинаться с `#`.",
    'Alternatively, to modify host tags centrally from the Dynatrace Cluster, you can use [Remote configuration management](/managed/ingest-from/bulk-configuration#configure-oneagents "Perform OneAgent and ActiveGate configuration on hosts from the Deployment status page or at scale using the Dynatrace API.") (select the **modify host tags** action).': 'Для централизованного изменения тегов хоста из Dynatrace Cluster можно использовать [удалённое управление конфигурацией](/managed/ingest-from/bulk-configuration#configure-oneagents "Настраивайте OneAgent и ActiveGate на хостах со страницы статуса развёртывания или массово через Dynatrace API.") (действие **modify host tags**).',
    "To **add or change host tags**, run the following command:": "Для **добавления или изменения тегов хоста** выполните следующую команду:",
    "`./oneagentctl --set-host-tag=TestHost --set-host-tag=role=fallback --set-host-tag=Gdansk`": "`./oneagentctl --set-host-tag=TestHost --set-host-tag=role=fallback --set-host-tag=Gdansk`",
    "`.\\.oneagentctl.exe --set-host-tag=TestHost --set-host-tag=role=fallback --set-host-tag=Gdansk`": "`.\\.oneagentctl.exe --set-host-tag=TestHost --set-host-tag=role=fallback --set-host-tag=Gdansk`",
    "You can add or change more than one tag in the same command. It is allowed to define tags with the same key but different values.": "В одной команде можно добавить или изменить несколько тегов. Допускается задавать теги с одинаковым ключом, но разными значениями.",
    "To **remove tags**, run the following command:": "Для **удаления тегов** выполните следующую команду:",
    "`./oneagentctl --remove-host-tag=role=fallback --remove-host-tag=Gdansk`": "`./oneagentctl --remove-host-tag=role=fallback --remove-host-tag=Gdansk`",
    "`.\\.oneagentctl.exe --remove-host-tag=role=fallback --remove-host-tag=Gdansk`": "`.\\.oneagentctl.exe --remove-host-tag=role=fallback --remove-host-tag=Gdansk`",
    "You can remove more than one tag with the same command. If a tag passed in the command doesn't exist, a non-zero exit code is returned, but all the existing tags passed in the command are removed. After you remove tags, they remain visible in Dynatrace for up to 6 hours.": "В одной команде можно удалить несколько тегов. Если тег, переданный в команде, не существует, возвращается ненулевой код выхода, однако все существующие теги, указанные в команде, удаляются. После удаления теги остаются видимы в Dynatrace до 6 часов.",
    "To **show all tags** configured for the host, run the following command:": "Для **отображения всех тегов**, настроенных для хоста, выполните следующую команду:",
    "`./oneagentctl --get-host-tags`": "`./oneagentctl --get-host-tags`",
    "`.\\.oneagentctl.exe --get-host-tags`": "`.\\.oneagentctl.exe --get-host-tags`",
    # --- ## Monitoring modes ---
    "## Monitoring modes": "## Режимы мониторинга",
    "Activates one of the OneAgent monitoring modes:": "Активирует один из режимов мониторинга OneAgent:",
    "* `fullstack`: Full-Stack Monitoring": "* `fullstack`: Full-Stack Monitoring",
    "* `infra-only`: Infrastructure Monitoring": "* `infra-only`: Infrastructure Monitoring",
    "* `discovery`: Discovery": "* `discovery`: Discovery",
    "To enable a specific monitoring mode, set the `--set-monitoring-mode` parameter to one of the values:": "Для включения определённого режима мониторинга установите параметр `--set-monitoring-mode` в одно из следующих значений:",
    "* `fullstack`": "* `fullstack`",
    "* `infra-only`": "* `infra-only`",
    "* `discovery`": "* `discovery`",
    'Use Infrastructure Monitoring mode or Discovery mode in place of Full-Stack Monitoring mode. With this approach, you receive infrastructure health data, with no application or user performance data. For details, see [Monitoring modes](/managed/platform/oneagent/monitoring-modes/monitoring-modes "Find out more about the available monitoring modes when using OneAgent.").': 'Используйте режим Infrastructure Monitoring или Discovery вместо Full-Stack Monitoring. При таком подходе доступны данные о состоянии инфраструктуры без данных о производительности приложений или пользователей. Подробнее см. в разделе [Режимы мониторинга](/managed/platform/oneagent/monitoring-modes/monitoring-modes "Узнайте больше о доступных режимах мониторинга при использовании OneAgent.").',
    # --- ### Check which monitoring mode is enabled ---
    "### Check which monitoring mode is enabled": "### Проверить, какой режим мониторинга включён",
    "Use the `--get-monitoring-mode` parameter to check which monitoring mode is enabled:": "Используйте параметр `--get-monitoring-mode` для проверки текущего режима мониторинга:",
    "`./oneagentctl --get-monitoring-mode`": "`./oneagentctl --get-monitoring-mode`",
    "`.\\.oneagentctl.exe --get-monitoring-mode`": "`.\\.oneagentctl.exe --get-monitoring-mode`",
    "The command returns one of the following:": "Команда возвращает одно из следующих значений:",
    "* `fullstack`: Full-Stack Monitoring mode": "* `fullstack`: режим Full-Stack Monitoring",
    "* `infra-only`: Infrastructure Monitoring mode": "* `infra-only`: режим Infrastructure Monitoring",
    "* `discovery`: Discovery mode": "* `discovery`: режим Discovery",
    'Changing the Infrastructure Monitoring mode requires restart of OneAgent, as well as restart of all monitored services. Add [`--restart-service`](#oneagent-restart) to the command to restart OneAgent automatically (version 1.189+) or stop and start the OneAgent process manually. For OS-specific instructions, see [Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/stop-restart-oneagent-on-linux "Learn how to stop and restart OneAgent on Linux."), [Windows](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/windows/operation/stop-restart-oneagent-on-windows "Learn how to stop and restart OneAgent on Windows."), or [AIX](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/aix/operation/stop-restart-oneagent-on-aix "Learn how to stop and restart OneAgent on AIX.").': 'Изменение режима Infrastructure Monitoring требует перезапуска OneAgent, а также перезапуска всех отслеживаемых сервисов. Добавьте [`--restart-service`](#oneagent-restart) к команде для автоматического перезапуска OneAgent (версия 1.189+) или остановите и запустите процесс OneAgent вручную. Инструкции для конкретной ОС см. в разделах [Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/operation/stop-restart-oneagent-on-linux "Узнайте, как остановить и перезапустить OneAgent на Linux."), [Windows](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/windows/operation/stop-restart-oneagent-on-windows "Узнайте, как остановить и перезапустить OneAgent на Windows.") или [AIX](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/aix/operation/stop-restart-oneagent-on-aix "Узнайте, как остановить и перезапустить OneAgent на AIX.").',
    # --- ## Automatic injection for Infrastructure Monitoring mode ---
    "## Automatic injection for Infrastructure Monitoring mode": "## Автоматическая инъекция в режиме Infrastructure Monitoring",
    "OneAgent version 1.213": "OneAgent версии 1.213",
    "Automatic OneAgent injection is enabled by default in Infrastructure Monitoring mode. It's required to collect JMX/PMI metrics and to handle Application Security in Infrastructure Monitoring mode.": "Автоматическая инъекция OneAgent включена по умолчанию в режиме Infrastructure Monitoring. Она необходима для сбора метрик JMX/PMI и обработки Application Security в режиме Infrastructure Monitoring.",
    'For more information, see [OneAgent monitoring modes](/managed/platform/oneagent/monitoring-modes/monitoring-modes "Find out more about the available monitoring modes when using OneAgent.").': 'Подробнее см. в разделе [Режимы мониторинга OneAgent](/managed/platform/oneagent/monitoring-modes/monitoring-modes "Узнайте больше о доступных режимах мониторинга при использовании OneAgent.").',
    # --- ### Check if auto-injection is enabled ---
    "### Check if auto-injection is enabled": "### Проверить, включена ли автоматическая инъекция",
    "Use the `get-auto-injection-enabled` parameter to check whether OneAgent auto-injection is enabled:": "Используйте параметр `get-auto-injection-enabled` для проверки того, включена ли автоматическая инъекция OneAgent:",
    "`./oneagentctl --get-auto-injection-enabled`": "`./oneagentctl --get-auto-injection-enabled`",
    "`.\\.oneagentctl.exe --get-auto-injection-enabled`": "`.\\.oneagentctl.exe --get-auto-injection-enabled`",
    # --- ### Enable or disable auto-injection ---
    "### Enable or disable auto-injection": "### Включить или отключить автоматическую инъекцию",
    "Set the `--set-auto-injection-enabled` parameter to `true` or `false` to enable or disable OneAgent auto-injection:": "Установите параметр `--set-auto-injection-enabled` в `true` или `false` для включения или отключения автоматической инъекции OneAgent:",
    "To enable auto-injections:": "Для включения автоматической инъекции:",
    "`./oneagentctl --set-auto-injection-enabled=true`": "`./oneagentctl --set-auto-injection-enabled=true`",
    "`.\\.oneagentctl.exe --set-auto-injection-enabled=true`": "`.\\.oneagentctl.exe --set-auto-injection-enabled=true`",
    "To disable auto-injections:": "Для отключения автоматической инъекции:",
    "`./oneagentctl --set-auto-injection-enabled=false`": "`./oneagentctl --set-auto-injection-enabled=false`",
    "`.\\.oneagentctl.exe --set-auto-injection-enabled=false`": "`.\\.oneagentctl.exe --set-auto-injection-enabled=false`",
    'For more information, see [Disable auto-injection](/managed/platform/oneagent/monitoring-modes/monitoring-modes#disable-auto-injection "Find out more about the available monitoring modes when using OneAgent.").': 'Подробнее см. в разделе [Отключение автоматической инъекции](/managed/platform/oneagent/monitoring-modes/monitoring-modes#disable-auto-injection "Узнайте больше о доступных режимах мониторинга при использовании OneAgent.").',
    # --- ## Metric ingestion ---
    "## Metric ingestion": "## Приём метрик",
    "Local metric ingestion is currently supported only on Windows and Linux.": "Локальный приём метрик в настоящее время поддерживается только на Windows и Linux.",
    'You can use the `oneagentctl` command to check or change communication ports used for local metric ingestion using the [OneAgent metric API](/managed/ingest-from/extend-dynatrace/extend-metrics/ingestion-methods/oneagent-metric-api "Use the Dynatrace API to retrieve the metrics of monitored entities."), [Scripting integration](/managed/ingest-from/extend-dynatrace/extend-metrics/ingestion-methods/oneagent-pipe "Learn how to ingest metrics using local scripting integration."), [Telegraf](/managed/ingest-from/extend-dynatrace/extend-metrics/ingestion-methods/telegraf "Ingest Telegraf metrics into Dynatrace."), or [DynatraceStatsd](/managed/ingest-from/extend-dynatrace/extend-metrics/ingestion-methods/statsd "Ingest metrics into Dynatrace using OneAgent and the ActiveGate StatsD client."). Changing the metric ingestion port requires restart of OneAgent. Add [`--restart-service`](#oneagent-restart) to the command to restart OneAgent automatically.': 'Используйте команду `oneagentctl` для проверки или изменения портов взаимодействия, используемых для локального приёма метрик через [OneAgent metric API](/managed/ingest-from/extend-dynatrace/extend-metrics/ingestion-methods/oneagent-metric-api "Используйте Dynatrace API для получения метрик отслеживаемых сущностей."), [интеграцию сценариев](/managed/ingest-from/extend-dynatrace/extend-metrics/ingestion-methods/oneagent-pipe "Узнайте, как принимать метрики с помощью локальной интеграции сценариев."), [Telegraf](/managed/ingest-from/extend-dynatrace/extend-metrics/ingestion-methods/telegraf "Принимайте метрики Telegraf в Dynatrace.") или [DynatraceStatsd](/managed/ingest-from/extend-dynatrace/extend-metrics/ingestion-methods/statsd "Принимайте метрики в Dynatrace с помощью OneAgent и клиента StatsD для ActiveGate."). Изменение порта приёма метрик требует перезапуска OneAgent. Добавьте [`--restart-service`](#oneagent-restart) к команде для автоматического перезапуска OneAgent.',
    'See [Metrics ingestion](/managed/ingest-from/extend-dynatrace/extend-metrics "Learn how to extend metric observability in Dynatrace.") to learn more.': 'Подробнее см. раздел [Приём метрик](/managed/ingest-from/extend-dynatrace/extend-metrics "Узнайте, как расширить наблюдаемость метрик в Dynatrace.").',
    # --- ### OneAgent API, scripting integration, and Telegraf ---
    "### OneAgent API, scripting integration, and Telegraf": "### OneAgent API, интеграция сценариев и Telegraf",
    'The default metric ingestion port is `14499`. If necessary, you can use the [oneagentctl](/managed/ingest-from/dynatrace-oneagent/oneagent-configuration-via-command-line-interface#metrics "Learn how to perform some OneAgent configuration tasks without the need to reinstall OneAgent.") command to check or change the port. Changing the metric ingestion port requires restart of OneAgent. Add [`--restart-service`](/managed/ingest-from/dynatrace-oneagent/oneagent-configuration-via-command-line-interface#oneagent-restart "Learn how to perform some OneAgent configuration tasks without the need to reinstall OneAgent.") to the command to restart OneAgent automatically.': 'Порт приёма метрик по умолчанию: `14499`. При необходимости используйте команду [oneagentctl](/managed/ingest-from/dynatrace-oneagent/oneagent-configuration-via-command-line-interface#metrics "Узнайте, как выполнять задачи настройки OneAgent без переустановки.") для проверки или изменения порта. Изменение порта требует перезапуска OneAgent. Добавьте [`--restart-service`](/managed/ingest-from/dynatrace-oneagent/oneagent-configuration-via-command-line-interface#oneagent-restart "Узнайте, как выполнять задачи настройки OneAgent без переустановки.") к команде для автоматического перезапуска OneAgent.',
    # --- ### Check the ingestion port ---
    "### Check the ingestion port": "### Проверить порт приёма метрик",
    "Use the `--get-extensions-ingest-port` parameter to show the current local ingestion port, `14499` by default.": "Используйте параметр `--get-extensions-ingest-port` для отображения текущего локального порта приёма метрик (по умолчанию: `14499`).",
    "* **Linux**, **AIX**:": "* **Linux**, **AIX**:",
    "`./oneagentctl --get-extensions-ingest-port`": "`./oneagentctl --get-extensions-ingest-port`",
    "`.\\.oneagentctl.exe --get-extensions-ingest-port`": "`.\\.oneagentctl.exe --get-extensions-ingest-port`",
    # --- ### Set a custom ingestion port ---
    "### Set a custom ingestion port": "### Задать пользовательский порт приёма метрик",
    "Use the `--set-extensions-ingest-port=<arg>` parameter to set a custom local ingestion port.": "Используйте параметр `--set-extensions-ingest-port=<arg>` для задания пользовательского локального порта приёма метрик.",
    "`./oneagentctl --set-extensions-ingest-port=14499 --restart-service`": "`./oneagentctl --set-extensions-ingest-port=14499 --restart-service`",
    "`.\\.oneagentctl.exe --set-extensions-ingest-port=14499 --restart-service`": "`.\\.oneagentctl.exe --set-extensions-ingest-port=14499 --restart-service`",
    # --- ### Configure proxy ---
    "### Configure proxy": "### Настроить прокси",
    "Configure your host proxy to allow localhost traffic going to the metric ingestion port, `14499` by default.": "Настройте прокси хоста так, чтобы разрешить локальный трафик на порт приёма метрик (по умолчанию: `14499`).",
    # --- ### StatsD ---
    "### StatsD": "### StatsD",
    "### OneAgent listener": "### Прослушиватель OneAgent",
    'The default DynatraceStatsD UDP listening port for the OneAgent listener is `18125`. If necessary, you can use the [oneagentctl](/managed/ingest-from/dynatrace-oneagent/oneagent-configuration-via-command-line-interface#metrics "Learn how to perform some OneAgent configuration tasks without the need to reinstall OneAgent.") command to check or change the metric ingestion port. Changing the port requires restart of OneAgent. Add [`--restart-service`](/managed/ingest-from/dynatrace-oneagent/oneagent-configuration-via-command-line-interface#oneagent-restart "Learn how to perform some OneAgent configuration tasks without the need to reinstall OneAgent.") to the command to restart OneAgent automatically.': 'Порт UDP-прослушивания DynatraceStatsD для прослушивателя OneAgent по умолчанию: `18125`. При необходимости используйте команду [oneagentctl](/managed/ingest-from/dynatrace-oneagent/oneagent-configuration-via-command-line-interface#metrics "Узнайте, как выполнять задачи настройки OneAgent без переустановки.") для проверки или изменения порта приёма метрик. Изменение порта требует перезапуска OneAgent. Добавьте [`--restart-service`](/managed/ingest-from/dynatrace-oneagent/oneagent-configuration-via-command-line-interface#oneagent-restart "Узнайте, как выполнять задачи настройки OneAgent без переустановки.") к команде для автоматического перезапуска OneAgent.',
    # --- #### Check the ingestion port (StatsD) ---
    "#### Check the ingestion port": "#### Проверить порт приёма метрик",
    "Use the `--get-extensions-statsd-port` parameter to show the current DynatraceStatsd UDP listening port (default = `18125`).": "Используйте параметр `--get-extensions-statsd-port` для отображения текущего UDP-порта прослушивания DynatraceStatsd (по умолчанию: `18125`).",
    "* **Linux**:": "* **Linux**:",
    "`./oneagentctl --get-extensions-statsd-port`": "`./oneagentctl --get-extensions-statsd-port`",
    "`.\\.oneagentctl.exe --get-extensions-statsd-port`": "`.\\.oneagentctl.exe --get-extensions-statsd-port`",
    # --- #### Set a custom ingestion port (StatsD) ---
    "#### Set a custom ingestion port": "#### Задать пользовательский порт приёма метрик",
    "Use the `--set-extensions-statsd-port=<arg>` parameter to set a custom DynatraceStatsd UDP listening port.": "Используйте параметр `--set-extensions-statsd-port=<arg>` для задания пользовательского UDP-порта прослушивания DynatraceStatsd.",
    "`./oneagentctl --set-extensions-statsd-port=18125 --restart-service`": "`./oneagentctl --set-extensions-statsd-port=18125 --restart-service`",
    "`.\\.oneagentctl.exe --set-extensions-statsd-port=18125 --restart-service`": "`.\\.oneagentctl.exe --set-extensions-statsd-port=18125 --restart-service`",
    # --- ### Remote StatsD ---
    "### Remote StatsD": "### Удалённый StatsD",
    "The default DynatraceStatsD UDP listening port for a remote listener is `18126`.": "UDP-порт прослушивания DynatraceStatsD для удалённого прослушивателя по умолчанию: `18126`.",
    "To change the default `18126` listening port, modify the `StatsdPort` parameter in the ActiveGate `extensionsuser.conf` file:": "Для изменения порта прослушивания `18126` по умолчанию измените параметр `StatsdPort` в файле `extensionsuser.conf` ActiveGate:",
    "* Linux": "* Linux",
    "`/var/lib/dynatrace/remotepluginmodule/agent/conf/extensionsuser.conf`": "`/var/lib/dynatrace/remotepluginmodule/agent/conf/extensionsuser.conf`",
    "* Windows": "* Windows",
    "`C:\\ProgramData\\dynatrace\\remotepluginmodule\\agent\\conf\\extensionsuser.conf`:": "`C:\\ProgramData\\dynatrace\\remotepluginmodule\\agent\\conf\\extensionsuser.conf`:",
    # --- ## Network zones ---
    "## Network zones": "## Сетевые зоны",
    'To learn about network zone naming rules and other reference information, see [Network zones](/managed/manage/network-zones "Find out how network zones work in Dynatrace.").': 'Сведения о правилах именования сетевых зон и другая справочная информация: [Сетевые зоны](/managed/manage/network-zones "Узнайте, как работают сетевые зоны в Dynatrace.").',
    'Alternatively, to modify network zone assignment centrally from the Dynatrace Cluster, you can use [Remote configuration management](/managed/ingest-from/bulk-configuration#configure-oneagents "Perform OneAgent and ActiveGate configuration on hosts from the Deployment status page or at scale using the Dynatrace API.") (select the **modify network zone** action).': 'Для централизованного изменения назначения сетевой зоны из Dynatrace Cluster можно использовать [удалённое управление конфигурацией](/managed/ingest-from/bulk-configuration#configure-oneagents "Настраивайте OneAgent и ActiveGate на хостах со страницы статуса развёртывания или массово через Dynatrace API.") (действие **modify network zone**).',
    # --- ### Set a network zone ---
    "### Set a network zone": "### Задать сетевую зону",
    'Use the `--set-network-zone` parameter to instruct OneAgent to communicate via the specified network zone. The name of a network zone is a string of alphanumeric characters. You can also use hyphens (`-`), underscores (`_`), and a dot (`.`) as a seperator. The network zone name must not start with a dot. The length of the string is limited to 256 characters. Network zone names are not case-sensitive. Dynatrace stores these names in lowercase. For more information, see the section on [network zone naming](/managed/manage/network-zones/network-zones-basic-info#naming "Learn how to get started with network zones.")': 'Используйте параметр `--set-network-zone` для настройки взаимодействия OneAgent через указанную сетевую зону. Имя сетевой зоны, это строка буквенно-цифровых символов. Допускается использование дефисов (`-`), знаков подчёркивания (`_`) и точки (`.`) в качестве разделителя. Имя сетевой зоны не должно начинаться с точки. Длина строки ограничена 256 символами. Имена сетевых зон нечувствительны к регистру; Dynatrace хранит их в нижнем регистре. Подробнее см. раздел [именование сетевых зон](/managed/manage/network-zones/network-zones-basic-info#naming "Узнайте, как приступить к работе с сетевыми зонами.")',
    "* On **Linux** or **AIX**:  ": "* На **Linux** или **AIX**:  ",
    "`./oneagentctl --set-network-zone=<your.network.zone>`": "`./oneagentctl --set-network-zone=<your.network.zone>`",
    "* On **Windows**:  ": "* На **Windows**:  ",
    "`.\\.oneagentctl.exe --set-network-zone=<your.network.zone>`": "`.\\.oneagentctl.exe --set-network-zone=<your.network.zone>`",
    # --- #### Reset a network zone ---
    "#### Reset a network zone": "#### Сбросить сетевую зону",
    "You can reset the network zone setting by passing an empty network zone name:": "Для сброса настройки сетевой зоны передайте пустое имя сетевой зоны:",
    "* On **Linux** or **AIX**:": "* На **Linux** или **AIX**:",
    '`./oneagentctl --set-network-zone=""`': '`./oneagentctl --set-network-zone=""`',
    "* On **Windows**:": "* На **Windows**:",
    '`.\\.oneagentctl.exe --set-network-zone=""`': '`.\\.oneagentctl.exe --set-network-zone=""`',
    # --- ### Display network zone setting ---
    "### Display network zone setting": "### Отобразить настройку сетевой зоны",
    "Use the `--get-network-zone` parameter to display the current network zone configuration:": "Используйте параметр `--get-network-zone` для отображения текущей конфигурации сетевой зоны:",
    "* On **Linux** or **AIX**:  ": "* На **Linux** или **AIX**:  ",
    "`./oneagentctl --get-network-zone`": "`./oneagentctl --get-network-zone`",
    "* On **Windows**:  ": "* На **Windows**:  ",
    "`.\\.oneagentctl.exe --get-network-zone`": "`.\\.oneagentctl.exe --get-network-zone`",
    # --- ## Passing configuration parameters during installation ---
    "## Passing configuration parameters during installation": "## Передача параметров конфигурации при установке",
    "You can pass the `--set-*` parameters at installation time. The configuration parameters are applied right before OneAgent service starts and there's no need to restart it to apply your configuration.": "Параметры `--set-*` можно передавать во время установки. Параметры конфигурации применяются непосредственно перед запуском сервиса OneAgent, перезапуск для их применения не требуется.",
    "Linux and AIX": "Linux и AIX",
    "Windows": "Windows",
    "To pass through the configuration parameters, simply add the parameter and precede the value with the equals sign (`=`). For example:": "Для передачи параметров конфигурации добавьте параметр и укажите значение после знака равенства (`=`). Например:",
    # --- ### EXE installer ---
    "### EXE installer": "### Установщик EXE",
    "To pass the configuration parameters through using the EXE installer, simply add the parameter and precede the value with the equals sign (`=`). For example:": "Для передачи параметров конфигурации через EXE-установщик добавьте параметр и укажите значение после знака равенства (`=`). Например:",
    # --- ### MSI package ---
    "### MSI package": "### Пакет MSI",
    "You can also pass the configuration parameters through using the MSI package. This time however, you must use an extra `ADDITIONAL_CONFIGURATION` parameter. For example:": "Параметры конфигурации можно передать и через MSI-пакет. В этом случае необходимо использовать дополнительный параметр `ADDITIONAL_CONFIGURATION`. Например:",
    # --- ## FIPS 140 cryptographic algorithms ---
    "## FIPS 140 cryptographic algorithms": "## Криптографические алгоритмы FIPS 140",
    "OneAgent version 1.245+": "OneAgent версии 1.245+",
    "OneAgent uses the FIPS mode to be compliant with the FIPS 140-3 computer security standard.": "OneAgent использует режим FIPS для соответствия стандарту компьютерной безопасности FIPS 140-3.",
    # --- ### Check if FIPS 140 is enabled ---
    "### Check if FIPS 140 is enabled": "### Проверить, включён ли FIPS 140",
    "Use the `--get-fips-enabled` to check if OneAgent uses FIPS 140 validated cryptographic algorithms.": "Используйте `--get-fips-enabled` для проверки того, использует ли OneAgent криптографические алгоритмы, прошедшие валидацию FIPS 140.",
    "* On **Linux** or **AIX**  ": "* На **Linux** или **AIX**  ",
    "`./oneagentctl --get-fips-enabled`": "`./oneagentctl --get-fips-enabled`",
    "* On **Windows**  ": "* На **Windows**  ",
    "`.\\.oneagentctl.exe --get-fips-enabled`": "`.\\.oneagentctl.exe --get-fips-enabled`",
    # --- ### Enable or disable FIPS 140 ---
    "### Enable or disable FIPS 140": "### Включить или отключить FIPS 140",
    "Enabling or disabling of FIPS 140 validated cryptographic algorithms can only be done during installation.": "Включение или отключение криптографических алгоритмов, прошедших валидацию FIPS 140, возможно только во время установки.",
    "Set the `--set-fips-enabled` parameter to `true` or `false` to enable or disable the FIPS 140 validated cryptographic algorithms on OneAgent. The default value for first time installation is `false`.": "Установите параметр `--set-fips-enabled` в `true` или `false` для включения или отключения криптографических алгоритмов, прошедших валидацию FIPS 140, в OneAgent. Значение по умолчанию при первоначальной установке: `false`.",
    "To enable FIPS mode:": "Для включения режима FIPS:",
    "* On **Linux**, **AIX** or **Windows**:": "* На **Linux**, **AIX** или **Windows**:",
    "Run the installer with `--set-fips-enabled=true`": "Запустите установщик с параметром `--set-fips-enabled=true`",
    "To disable FIPS mode:": "Для отключения режима FIPS:",
    "Run the installer with `--set-fips-enabled==false`": "Запустите установщик с параметром `--set-fips-enabled==false`",
    "If you want to enable FIPS mode for application-only deployment, go to `/paas/package/agent` and delete `dt_fips_disabled.flag`.": "Для включения режима FIPS при развёртывании только приложения перейдите в `/paas/package/agent` и удалите файл `dt_fips_disabled.flag`.",
    # --- ## cap_setuid for OS Agent ---
    "## cap\\_setuid for OS Agent": "## cap\\_setuid для OS Agent",
    "GPFS monitoring": "Мониторинг GPFS",
    "OneAgent version 1.293+": "OneAgent версии 1.293+",
    "Enabling `cap_setuid` for OS Agent is required for GPFS monitoring.": "Включение `cap_setuid` для OS Agent необходимо для мониторинга GPFS.",
    'Following parameters are only available in [OneAgent non-privileged mode on Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/installation/linux-non-privileged "Find out when Dynatrace OneAgent requires root privileges on Linux.").': 'Следующие параметры доступны только в [непривилегированном режиме OneAgent на Linux](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/linux/installation/linux-non-privileged "Узнайте, когда Dynatrace OneAgent требует привилегий root на Linux.").',
    "* `get-osagent-cap-setuid-enabled`": "* `get-osagent-cap-setuid-enabled`",
    "* `set-osagent-cap-setuid-enabled`": "* `set-osagent-cap-setuid-enabled`",
    "You can enable `cap_setuid` for OS Agent starting from OneAgent version 1.293+, but you can use GPFS monitoring only from OneAgent version 1.295+.": "Включить `cap_setuid` для OS Agent можно начиная с OneAgent версии 1.293+, однако мониторинг GPFS доступен только с OneAgent версии 1.295+.",
    # --- ### Check if cap_setuid for OS Agent is enabled ---
    "### Check if cap\\_setuid for OS Agent is enabled": "### Проверить, включён ли cap\\_setuid для OS Agent",
    "Use the `get-osagent-cap-setuid-enabled` parameter to check whether cap\\_setuid for OS Agent is enabled:": "Используйте параметр `get-osagent-cap-setuid-enabled` для проверки того, включён ли cap\\_setuid для OS Agent:",
    "`./oneagentctl --get-osagent-cap-setuid-enabled`": "`./oneagentctl --get-osagent-cap-setuid-enabled`",
    # --- ### Enable or disable cap_setuid for OS Agent ---
    "### Enable or disable cap\\_setuid for OS Agent": "### Включить или отключить cap\\_setuid для OS Agent",
    "Set the `--set-osagent-cap-setuid-enabled` parameter to `true` or `false` to disable or enable cap\\_setuid for OS Agent:": "Установите параметр `--set-osagent-cap-setuid-enabled` в `true` или `false` для включения или отключения cap\\_setuid для OS Agent:",
    "`./oneagentctl --set-osagent-cap-setuid-enabled=true`": "`./oneagentctl --set-osagent-cap-setuid-enabled=true`",
    # --- additional missing lines (platform headers + mojibake variants) ---
    '* `oneagentos`—operating system monitoring': '* `oneagentos`: мониторинг операционной системы',
    '* `oneagentplugin`—monitoring using [OneAgent extensions](/managed/ingest-from/extensions/develop-your-extensions#oneagent-extensions "Develop your own Extensions in Dynatrace.")': '* `oneagentplugin`: мониторинг с помощью [расширений OneAgent](/managed/ingest-from/extensions/develop-your-extensions#oneagent-extensions "Разрабатывайте собственные расширения в Dynatrace.")',
    '* `oneagentextensions`—monitoring using local [Extensions](/managed/ingest-from/extensions "Learn how to create and manage Dynatrace Extensions.")': '* `oneagentextensions`: мониторинг с помощью локальных [расширений](/managed/ingest-from/extensions "Узнайте, как создавать расширения Dynatrace и управлять ими.")',
    '* `oneagentloganalytics`—[Log Monitoring](/managed/analyze-explore-automate/log-monitoring "Learn how to enable Log Monitoring, the insights that Log Monitoring can provide, and more.")': '* `oneagentloganalytics`: [мониторинг журналов](/managed/analyze-explore-automate/log-monitoring "Узнайте, как включить мониторинг журналов и какие возможности он предоставляет.")',
    '* `oneagentnetwork`—[network monitoring](/managed/observe/infrastructure-observability/networks "Learn how to monitor network communications.")': '* `oneagentnetwork`: [мониторинг сети](/managed/observe/infrastructure-observability/networks "Узнайте, как вести мониторинг сетевых коммуникаций.")',
    '| `support_archive` (ZIP) | Contains the local configuration of the OneAgent installed on the host or process where you’ve run the troubleshooting, as well as the OneAgent-related log files. |': '| `support_archive` (ZIP) | Содержит локальную конфигурацию OneAgent, установленного на хосте или в процессе, для которых выполнялась диагностика, а также связанные с OneAgent файлы журналов. |',
    '* `auto` — Let Dynatrace generate the host ID automatically': '* `auto`: Dynatrace генерирует идентификатор хоста автоматически',
    '* `ip-addresses` — Generate host ID based on the host IP address': '* `ip-addresses`: идентификатор хоста генерируется на основе IP-адреса хоста',
    "* `mac-addresses` — Generate host ID based on the host's NIC MAC address": '* `mac-addresses`: идентификатор хоста генерируется на основе MAC-адреса сетевого адаптера хоста',
    "* `fqdn` — Generate host ID based on the host fully qualified domain name (FQDN) in the `host.domain` format. If the FQDN doesn't contain a dot character, the NIC MAC address is used instead.": '* `fqdn`: идентификатор хоста генерируется на основе полного доменного имени (FQDN) хоста в формате `host.domain`. Если FQDN не содержит точки, используется MAC-адрес сетевого адаптера.',
    '* **Linux** and **AIX**': '* **Linux** и **AIX**',
    '* **Windows**': '* **Windows**',
    '* On **Linux** or **AIX**': '* На **Linux** или **AIX**',
    '* On **Windows**': '* На **Windows**',
}

# Lines that must remain verbatim EN (command names, flags, output literals)
PASS = {
    '`.\\oneagentctl.exe --set-proxy=my-proxy.com --restart-service`',
    '`.\\oneagentctl.exe --help`',
    '`.\\oneagentctl.exe --version`',
    '`.\\oneagentctl.exe --set-server=https://my-server.com:9999/communication --set-tenant=abc123456 --set-tenant-token=abcdefg123456790 --set-proxy=my-proxy.com`',
    '`.\\oneagentctl.exe --get-server`',
    '`.\\oneagentctl.exe --set-tenant=abc123456`',
    '`.\\oneagentctl.exe --get-tenant`',
    '`.\\oneagentctl.exe --set-tenant-token=abcdefg123456790`',
    '`.\\oneagentctl.exe --get-tenant-token`',
    '`.\\oneagentctl.exe --set-proxy=my-proxy.com`',
    '`.\\oneagentctl.exe --set-proxy=`',
    '`.\\oneagentctl.exe --get-proxy`',
    '`.\\oneagentctl.exe --set-no-proxy=my-proxy.com`',
    '`.\\oneagentctl.exe --get-no-proxy`',
    '`.\\oneagentctl.exe --get-watchdog-portrange`',
    '`.\\oneagentctl.exe --set-watchdog-portrange=50000:50100`',
    '`.\\oneagentctl.exe --get-auto-update-enabled`',
    '`.\\oneagentctl.exe --set-auto-update-enabled=true`',
    '`.\\oneagentctl.exe --get-app-log-content-access`',
    '`.\\oneagentctl.exe --set-app-log-content-access=true`',
    '`.\\oneagentctl.exe --create-support-archive directory=C:\\data\\support-archive days=30`',
    '`.\\oneagentctl.exe --get-system-logs-access-enabled`',
    '`.\\oneagentctl.exe --set-system-logs-access-enabled=true`',
    '`.\\oneagentctl.exe --get-host-id`',
    '`.\\oneagentctl.exe --set-host-id-source="ip-addresses;namespace=test"`',
    '`.\\oneagentctl.exe --get-host-id-source`',
    '`.\\oneagentctl.exe --set-host-group=MyHostGroup`',
    '`.\\oneagentctl.exe --set-host-group=`',
    '`.\\oneagentctl.exe --get-host-group`',
    '`.\\oneagentctl.exe --set-host-name=myhostname`',
    '`.\\oneagentctl.exe --set-host-name=""`',
    '`.\\oneagentctl.exe --get-host-name`',
    '`.\\oneagentctl.exe --set-host-property=AppName --set-host-property Environment=Dev`',
    '`.\\oneagentctl.exe --set-host-property=dt.security_context=easytrade_sec`',
    '`.\\oneagentctl.exe --remove-host-property=AppName --remove-host-property=Environment=Dev`',
    '`.\\oneagentctl.exe --get-host-properties`',
    '`.\\oneagentctl.exe --set-host-tag=TestHost --set-host-tag=role=fallback --set-host-tag=Gdansk`',
    '`.\\oneagentctl.exe --remove-host-tag=role=fallback --remove-host-tag=Gdansk`',
    '`.\\oneagentctl.exe --get-host-tags`',
    '`.\\oneagentctl.exe --get-monitoring-mode`',
    '`.\\oneagentctl.exe --get-auto-injection-enabled`',
    '`.\\oneagentctl.exe --set-auto-injection-enabled=true`',
    '`.\\oneagentctl.exe --set-auto-injection-enabled=false`',
    '`.\\oneagentctl.exe --get-extensions-ingest-port`',
    '`.\\oneagentctl.exe --set-extensions-ingest-port=14499 --restart-service`',
    '`.\\oneagentctl.exe --get-extensions-statsd-port`',
    '`.\\oneagentctl.exe --set-extensions-statsd-port=18125 --restart-service`',
    '`.\\oneagentctl.exe --set-network-zone=<your.network.zone>`',
    '`.\\oneagentctl.exe --set-network-zone=""`',
    '`.\\oneagentctl.exe --get-network-zone`',
    '`.\\oneagentctl.exe --get-fips-enabled`',
}

if __name__ == "__main__":
    build_one(REL, FN, TRANS, PASS)
    qa_one(REL, FN)
