# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/cloudwatch-ec2"

TRANS = {
    "title: Amazon EC2 Auto Scaling (built-in)": "title: Amazon EC2 Auto Scaling (встроенный)",
    "# Amazon EC2 Auto Scaling (built-in)": "# Amazon EC2 Auto Scaling (встроенный)",
    "* How-to guide": "* Практическое руководство",
    "* 1-min read": "* Чтение: 1 мин",
    "* Updated on Nov 15, 2023": "* Обновлено 15 ноября 2023 г.",
    "For information about differences between classic services and other services, see [Migrate from AWS classic (formerly 'built-in') services to cloud services](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/aws-migration-guide \"Migrate AWS classic services to their new versions.\").": "Сведения о различиях между классическими сервисами и другими сервисами см. в разделе [Миграция с классических сервисов AWS (ранее «встроенных») на облачные сервисы](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/aws-migration-guide \"Миграция классических сервисов AWS на новые версии.\").",
    "Dynatrace ingests metrics for multiple preselected namespaces, including Amazon EC2 Auto Scaling. You can view metrics for each service instance, split metrics into multiple dimensions, and create custom charts that you can pin to your dashboards.": "Dynatrace собирает метрики для множества предварительно выбранных пространств имён, включая Amazon EC2 Auto Scaling. Можно просматривать метрики для каждого экземпляра сервиса, разделять метрики по нескольким измерениям и создавать пользовательские диаграммы, которые можно закрепить на дашбордах.",
    "## Prerequisites": "## Предварительные требования",
    "To enable monitoring for this service, you need:": "Для включения мониторинга этого сервиса необходимо:",
    "* Any version of ActiveGate in both Dynatrace SaaS and Managed deployments.": "* Любая версия ActiveGate для развёртываний Dynatrace SaaS и Managed.",
    "For role-based access (whether in a [SaaS](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics#role-based-access \"Integrate metrics from Amazon CloudWatch.\") or [Managed](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#role-based-access \"Connect your Amazon account with Dynatrace Managed and start monitoring.\") deployment), you need an ActiveGate installed on an Amazon EC2 host.": "Для доступа на основе ролей (будь то развёртывание [SaaS](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics#role-based-access \"Интеграция метрик из Amazon CloudWatch.\") или [Managed](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#role-based-access \"Подключение аккаунта Amazon к Dynatrace Managed и начало мониторинга.\")) требуется ActiveGate, установленный на хосте Amazon EC2.",
    "* An updated [AWS monitoring policy](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics#aws-policy-and-authentication \"Integrate metrics from Amazon CloudWatch.\") to include the additional AWS services.": "* Обновлённая [политика мониторинга AWS](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics#aws-policy-and-authentication \"Интеграция метрик из Amazon CloudWatch.\") для включения дополнительных сервисов AWS.",
    "To [update the AWS IAM policy﻿](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-edit.html#edit-managed-policy-console), use the JSON below, containing the monitoring policy (permissions) for all cloud services.": "Чтобы [обновить политику AWS IAM﻿](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-edit.html#edit-managed-policy-console), используйте приведённый ниже JSON, содержащий политику мониторинга (разрешения) для всех облачных сервисов.",
    "JSON predefined policy for all cloud services": "Предопределённая JSON-политика для всех облачных сервисов",
    "If you don't want to add permissions to all services, and just select permissions for certain services, consult the table below. The table contains a set of permissions that are required for [All AWS cloud services](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Monitor all AWS cloud services with Dynatrace and view available metrics.\") and, for each cloud service, a list of optional permissions specific to that service.": "Если не нужно добавлять разрешения для всех сервисов, а только для определённых, обратитесь к таблице ниже. Таблица содержит набор разрешений, необходимых для [всех облачных сервисов AWS](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Мониторинг всех облачных сервисов AWS с Dynatrace и просмотр доступных метрик.\"), а для каждого облачного сервиса приводится список необязательных разрешений, специфичных для этого сервиса.",
    "Permissions required for AWS monitoring integration:": "Разрешения, необходимые для интеграции мониторинга AWS:",
    "### Complete list of permissions for cloud services": "### Полный список разрешений для облачных сервисов",
    "| Name | Permissions |": "| Название | Разрешения |",
    "| --- | --- |": "| --- | --- |",
    "| All monitored Amazon services Required | `cloudwatch:GetMetricData`, `cloudwatch:GetMetricStatistics`, `cloudwatch:ListMetrics`, `sts:GetCallerIdentity`, `tag:GetResources`, `tag:GetTagKeys`, `ec2:DescribeAvailabilityZones` |": "| Все мониторируемые сервисы Amazon (обязательные) | `cloudwatch:GetMetricData`, `cloudwatch:GetMetricStatistics`, `cloudwatch:ListMetrics`, `sts:GetCallerIdentity`, `tag:GetResources`, `tag:GetTagKeys`, `ec2:DescribeAvailabilityZones` |",
    "| AWS Certificate Manager Private Certificate Authority | `acm-pca:ListCertificateAuthorities` |": "| AWS Certificate Manager Private Certificate Authority | `acm-pca:ListCertificateAuthorities` |",
    "| Amazon MQ |  |": "| Amazon MQ |  |",
    "| Amazon API Gateway | `apigateway:GET` |": "| Amazon API Gateway | `apigateway:GET` |",
    "| AWS App Runner | `apprunner:ListServices` |": "| AWS App Runner | `apprunner:ListServices` |",
    "| Amazon AppStream | `appstream:DescribeFleets` |": "| Amazon AppStream | `appstream:DescribeFleets` |",
    "| AWS AppSync | `appsync:ListGraphqlApis` |": "| AWS AppSync | `appsync:ListGraphqlApis` |",
    "| Amazon Athena | `athena:ListWorkGroups` |": "| Amazon Athena | `athena:ListWorkGroups` |",
    "| Amazon Aurora | `rds:DescribeDBClusters` |": "| Amazon Aurora | `rds:DescribeDBClusters` |",
    "| Amazon EC2 Auto Scaling | `autoscaling:DescribeAutoScalingGroups` |": "| Amazon EC2 Auto Scaling | `autoscaling:DescribeAutoScalingGroups` |",
    "| Amazon EC2 Auto Scaling (built-in) | `autoscaling:DescribeAutoScalingGroups` |": "| Amazon EC2 Auto Scaling (встроенный) | `autoscaling:DescribeAutoScalingGroups` |",
    "| AWS Billing |  |": "| AWS Billing |  |",
    "| Amazon Keyspaces |  |": "| Amazon Keyspaces |  |",
    "| AWS Chatbot |  |": "| AWS Chatbot |  |",
    "| Amazon CloudFront | `cloudfront:ListDistributions` |": "| Amazon CloudFront | `cloudfront:ListDistributions` |",
    "| AWS CloudHSM | `cloudhsm:DescribeClusters` |": "| AWS CloudHSM | `cloudhsm:DescribeClusters` |",
    "| Amazon CloudSearch | `cloudsearch:DescribeDomains` |": "| Amazon CloudSearch | `cloudsearch:DescribeDomains` |",
    "| AWS CodeBuild | `codebuild:ListProjects` |": "| AWS CodeBuild | `codebuild:ListProjects` |",
    "| Amazon Cognito |  |": "| Amazon Cognito |  |",
    "| Amazon Connect |  |": "| Amazon Connect |  |",
    "| Amazon Elastic Kubernetes Service (EKS) | `eks:ListClusters` |": "| Amazon Elastic Kubernetes Service (EKS) | `eks:ListClusters` |",
    "| AWS DataSync | `datasync:ListTasks` |": "| AWS DataSync | `datasync:ListTasks` |",
    "| Amazon DynamoDB Accelerator (DAX) | `dax:DescribeClusters` |": "| Amazon DynamoDB Accelerator (DAX) | `dax:DescribeClusters` |",
    "| AWS Database Migration Service (AWS DMS) | `dms:DescribeReplicationInstances` |": "| AWS Database Migration Service (AWS DMS) | `dms:DescribeReplicationInstances` |",
    "| Amazon DocumentDB | `rds:DescribeDBClusters` |": "| Amazon DocumentDB | `rds:DescribeDBClusters` |",
    "| AWS Direct Connect | `directconnect:DescribeConnections` |": "| AWS Direct Connect | `directconnect:DescribeConnections` |",
    "| Amazon DynamoDB | `dynamodb:ListTables` |": "| Amazon DynamoDB | `dynamodb:ListTables` |",
    "| Amazon DynamoDB (built-in) | `dynamodb:ListTables`, `dynamodb:ListTagsOfResource` |": "| Amazon DynamoDB (встроенный) | `dynamodb:ListTables`, `dynamodb:ListTagsOfResource` |",
    "| Amazon EBS | `ec2:DescribeVolumes` |": "| Amazon EBS | `ec2:DescribeVolumes` |",
    "| Amazon EBS (built-in) | `ec2:DescribeVolumes` |": "| Amazon EBS (встроенный) | `ec2:DescribeVolumes` |",
    "| Amazon EC2 API |  |": "| Amazon EC2 API |  |",
    "| Amazon EC2 (built-in) | `ec2:DescribeInstances` |": "| Amazon EC2 (встроенный) | `ec2:DescribeInstances` |",
    "| Amazon EC2 Spot Fleet | `ec2:DescribeSpotFleetRequests` |": "| Amazon EC2 Spot Fleet | `ec2:DescribeSpotFleetRequests` |",
    "| Amazon Elastic Container Service (ECS) | `ecs:ListClusters` |": "| Amazon Elastic Container Service (ECS) | `ecs:ListClusters` |",
    "| Amazon ECS Container Insights | `ecs:ListClusters` |": "| Amazon ECS Container Insights | `ecs:ListClusters` |",
    "| Amazon ElastiCache (EC) | `elasticache:DescribeCacheClusters` |": "| Amazon ElastiCache (EC) | `elasticache:DescribeCacheClusters` |",
    "| AWS Elastic Beanstalk | `elasticbeanstalk:DescribeEnvironments` |": "| AWS Elastic Beanstalk | `elasticbeanstalk:DescribeEnvironments` |",
    "| Amazon Elastic File System (EFS) | `elasticfilesystem:DescribeFileSystems` |": "| Amazon Elastic File System (EFS) | `elasticfilesystem:DescribeFileSystems` |",
    "| Amazon Elastic Inference |  |": "| Amazon Elastic Inference |  |",
    "| Amazon Elastic Map Reduce (EMR) | `elasticmapreduce:ListClusters` |": "| Amazon Elastic Map Reduce (EMR) | `elasticmapreduce:ListClusters` |",
    "| Amazon Elasticsearch Service (ES) | `es:ListDomainNames` |": "| Amazon Elasticsearch Service (ES) | `es:ListDomainNames` |",
    "| Amazon Elastic Transcoder | `elastictranscoder:ListPipelines` |": "| Amazon Elastic Transcoder | `elastictranscoder:ListPipelines` |",
    "| Amazon Elastic Load Balancer (ELB) (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |": "| Amazon Elastic Load Balancer (ELB) (встроенный) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |",
    "| Amazon EventBridge | `events:ListEventBuses` |": "| Amazon EventBridge | `events:ListEventBuses` |",
    "| Amazon FSx | `fsx:DescribeFileSystems` |": "| Amazon FSx | `fsx:DescribeFileSystems` |",
    "| Amazon GameLift | `gamelift:ListFleets` |": "| Amazon GameLift | `gamelift:ListFleets` |",
    "| AWS Glue | `glue:GetJobs` |": "| AWS Glue | `glue:GetJobs` |",
    "| Amazon Inspector | `inspector:ListAssessmentTemplates` |": "| Amazon Inspector | `inspector:ListAssessmentTemplates` |",
    "| AWS Internet of Things (IoT) |  |": "| AWS Internet of Things (IoT) |  |",
    "| AWS IoT Analytics |  |": "| AWS IoT Analytics |  |",
    "| Amazon Managed Streaming for Kafka | `kafka:ListClusters` |": "| Amazon Managed Streaming for Kafka | `kafka:ListClusters` |",
    "| Amazon Kinesis Data Analytics | `kinesisanalytics:ListApplications` |": "| Amazon Kinesis Data Analytics | `kinesisanalytics:ListApplications` |",
    "| Amazon Data Firehose | `firehose:ListDeliveryStreams` |": "| Amazon Data Firehose | `firehose:ListDeliveryStreams` |",
    "| Amazon Kinesis Data Streams | `kinesis:ListStreams` |": "| Amazon Kinesis Data Streams | `kinesis:ListStreams` |",
    "| Amazon Kinesis Video Streams | `kinesisvideo:ListStreams` |": "| Amazon Kinesis Video Streams | `kinesisvideo:ListStreams` |",
    "| AWS Lambda | `lambda:ListFunctions` |": "| AWS Lambda | `lambda:ListFunctions` |",
    "| AWS Lambda (built-in) | `lambda:ListFunctions`, `lambda:ListTags` |": "| AWS Lambda (встроенный) | `lambda:ListFunctions`, `lambda:ListTags` |",
    "| Amazon Lex | `lex:GetBots` |": "| Amazon Lex | `lex:GetBots` |",
    "| Amazon Application and Network Load Balancer (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |": "| Amazon Application and Network Load Balancer (встроенный) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |",
    "| Amazon CloudWatch Logs | `logs:DescribeLogGroups` |": "| Amazon CloudWatch Logs | `logs:DescribeLogGroups` |",
    "| AWS Elemental MediaConnect | `mediaconnect:ListFlows` |": "| AWS Elemental MediaConnect | `mediaconnect:ListFlows` |",
    "| AWS Elemental MediaConvert | `mediaconvert:DescribeEndpoints` |": "| AWS Elemental MediaConvert | `mediaconvert:DescribeEndpoints` |",
    "| AWS Elemental MediaPackage Live | `mediapackage:ListChannels` |": "| AWS Elemental MediaPackage Live | `mediapackage:ListChannels` |",
    "| AWS Elemental MediaPackage Video on Demand | `mediapackage-vod:ListPackagingConfigurations` |": "| AWS Elemental MediaPackage Video on Demand | `mediapackage-vod:ListPackagingConfigurations` |",
    "| AWS Elemental MediaTailor | `mediatailor:ListPlaybackConfigurations` |": "| AWS Elemental MediaTailor | `mediatailor:ListPlaybackConfigurations` |",
    "| Amazon VPC NAT Gateways | `ec2:DescribeNatGateways` |": "| Amazon VPC NAT Gateways | `ec2:DescribeNatGateways` |",
    "| Amazon Neptune | `rds:DescribeDBClusters` |": "| Amazon Neptune | `rds:DescribeDBClusters` |",
    "| AWS OpsWorks | `opsworks:DescribeStacks` |": "| AWS OpsWorks | `opsworks:DescribeStacks` |",
    "| Amazon Polly |  |": "| Amazon Polly |  |",
    "| Amazon QLDB | `qldb:ListLedgers` |": "| Amazon QLDB | `qldb:ListLedgers` |",
    "| Amazon RDS | `rds:DescribeDBInstances` |": "| Amazon RDS | `rds:DescribeDBInstances` |",
    "| Amazon RDS (built-in) | `rds:DescribeDBInstances`, `rds:DescribeEvents`, `rds:ListTagsForResource` |": "| Amazon RDS (встроенный) | `rds:DescribeDBInstances`, `rds:DescribeEvents`, `rds:ListTagsForResource` |",
    "| Amazon Redshift | `redshift:DescribeClusters` |": "| Amazon Redshift | `redshift:DescribeClusters` |",
    "| Amazon Rekognition |  |": "| Amazon Rekognition |  |",
    "| AWS RoboMaker | `robomaker:ListSimulationJobs` |": "| AWS RoboMaker | `robomaker:ListSimulationJobs` |",
    "| Amazon Route 53 | `route53:ListHostedZones` |": "| Amazon Route 53 | `route53:ListHostedZones` |",
    "| Amazon Route 53 Resolver | `route53resolver:ListResolverEndpoints` |": "| Amazon Route 53 Resolver | `route53resolver:ListResolverEndpoints` |",
    "| Amazon S3 | `s3:ListAllMyBuckets` |": "| Amazon S3 | `s3:ListAllMyBuckets` |",
    "| Amazon S3 (built-in) | `s3:ListAllMyBuckets` |": "| Amazon S3 (встроенный) | `s3:ListAllMyBuckets` |",
    "| Amazon SageMaker Batch Transform Jobs |  |": "| Amazon SageMaker Batch Transform Jobs |  |",
    "| Amazon SageMaker Endpoint Instances | `sagemaker:ListEndpoints` |": "| Amazon SageMaker Endpoint Instances | `sagemaker:ListEndpoints` |",
    "| Amazon SageMaker Endpoints | `sagemaker:ListEndpoints` |": "| Amazon SageMaker Endpoints | `sagemaker:ListEndpoints` |",
    "| Amazon SageMaker Ground Truth |  |": "| Amazon SageMaker Ground Truth |  |",
    "| Amazon SageMaker Processing Jobs |  |": "| Amazon SageMaker Processing Jobs |  |",
    "| Amazon SageMaker Training Jobs |  |": "| Amazon SageMaker Training Jobs |  |",
    "| AWS Service Catalog |  |": "| AWS Service Catalog |  |",
    "| Amazon Simple Email Service (SES) |  |": "| Amazon Simple Email Service (SES) |  |",
    "| Amazon Simple Notification Service (SNS) | `sns:ListTopics` |": "| Amazon Simple Notification Service (SNS) | `sns:ListTopics` |",
    "| Amazon Simple Queue Service (SQS) | `sqs:ListQueues` |": "| Amazon Simple Queue Service (SQS) | `sqs:ListQueues` |",
    "| AWS Systems Manager - Run Command |  |": "| AWS Systems Manager - Run Command |  |",
    "| AWS Step Functions |  |": "| AWS Step Functions |  |",
    "| AWS Storage Gateway | `storagegateway:ListGateways` |": "| AWS Storage Gateway | `storagegateway:ListGateways` |",
    "| Amazon SWF | `swf:ListDomains` |": "| Amazon SWF | `swf:ListDomains` |",
    "| Amazon Textract |  |": "| Amazon Textract |  |",
    "| AWS IoT Things Graph |  |": "| AWS IoT Things Graph |  |",
    "| AWS Transfer Family | `transfer:ListServers` |": "| AWS Transfer Family | `transfer:ListServers` |",
    "| AWS Transit Gateway | `ec2:DescribeTransitGateways` |": "| AWS Transit Gateway | `ec2:DescribeTransitGateways` |",
    "| Amazon Translate |  |": "| Amazon Translate |  |",
    "| AWS Trusted Advisor |  |": "| AWS Trusted Advisor |  |",
    "| AWS API Usage |  |": "| AWS API Usage |  |",
    "| AWS Site-to-Site VPN | `ec2:DescribeVpnConnections` |": "| AWS Site-to-Site VPN | `ec2:DescribeVpnConnections` |",
    "| AWS WAF Classic |  |": "| AWS WAF Classic |  |",
    "| AWS WAF |  |": "| AWS WAF |  |",
    "| Amazon WorkMail | `workmail:ListOrganizations` |": "| Amazon WorkMail | `workmail:ListOrganizations` |",
    "| Amazon WorkSpaces | `workspaces:DescribeWorkspaces` |": "| Amazon WorkSpaces | `workspaces:DescribeWorkspaces` |",
    "Example of JSON policy for one single service.": "Пример JSON-политики для одного сервиса приведён ниже.",
    "JSON policy for Amazon API Gateway": "JSON-политика для Amazon API Gateway",
    "In this example, from the complete list of permissions you need to select": "В этом примере из полного списка разрешений необходимо выбрать",
    "* `\"apigateway:GET\"` for **Amazon API Gateway**": "* `\"apigateway:GET\"` для **Amazon API Gateway**",
    "* `\"cloudwatch:GetMetricData\"`, `\"cloudwatch:GetMetricStatistics\"`, `\"cloudwatch:ListMetrics\"`, `\"sts:GetCallerIdentity\"`, `\"tag:GetResources\"`, `\"tag:GetTagKeys\"`, and `\"ec2:DescribeAvailabilityZones\"` for **All AWS cloud services**.": "* `\"cloudwatch:GetMetricData\"`, `\"cloudwatch:GetMetricStatistics\"`, `\"cloudwatch:ListMetrics\"`, `\"sts:GetCallerIdentity\"`, `\"tag:GetResources\"`, `\"tag:GetTagKeys\"` и `\"ec2:DescribeAvailabilityZones\"` для **всех облачных сервисов AWS**.",
    "* To disable monitoring of built-in services, you need Environment ActiveGate version 1.245+ and Dynatrace version 1.247+.": "* Для отключения мониторинга встроенных сервисов требуется Environment ActiveGate версии 1.245+ и Dynatrace версии 1.247+.",
    "### AWS endpoints that need to be reachable from ActiveGate with corresponding AWS services": "### Эндпоинты AWS, которые должны быть доступны из ActiveGate, с соответствующими сервисами AWS",
    "| Endpoint | Service |": "| Эндпоинт | Сервис |",
    "| `autoscaling.<REGION>.amazonaws.com` | Amazon EC2 Auto Scaling (built-in), Amazon EC2 Auto Scaling |": "| `autoscaling.<REGION>.amazonaws.com` | Amazon EC2 Auto Scaling (встроенный), Amazon EC2 Auto Scaling |",
    "| `lambda.<REGION>.amazonaws.com` | AWS Lambda (built-in), AWS Lambda |": "| `lambda.<REGION>.amazonaws.com` | AWS Lambda (встроенный), AWS Lambda |",
    "| `elasticloadbalancing.<REGION>.amazonaws.com` | Amazon Application and Network Load Balancer (built-in), Amazon Elastic Load Balancer (ELB) (built-in) |": "| `elasticloadbalancing.<REGION>.amazonaws.com` | Amazon Application and Network Load Balancer (встроенный), Amazon Elastic Load Balancer (ELB) (встроенный) |",
    "| `dynamodb.<REGION>.amazonaws.com` | Amazon DynamoDB (built-in), Amazon DynamoDB |": "| `dynamodb.<REGION>.amazonaws.com` | Amazon DynamoDB (встроенный), Amazon DynamoDB |",
    "| `ec2.<REGION>.amazonaws.com` | Amazon EBS (built-in), Amazon EC2 (built-in), Amazon EBS, Amazon EC2 Spot Fleet, Amazon VPC NAT Gateways, AWS Transit Gateway, AWS Site-to-Site VPN |": "| `ec2.<REGION>.amazonaws.com` | Amazon EBS (встроенный), Amazon EC2 (встроенный), Amazon EBS, Amazon EC2 Spot Fleet, Amazon VPC NAT Gateways, AWS Transit Gateway, AWS Site-to-Site VPN |",
    "| `rds.<REGION>.amazonaws.com` | Amazon RDS (built-in), Amazon Aurora, Amazon DocumentDB, Amazon Neptune, Amazon RDS |": "| `rds.<REGION>.amazonaws.com` | Amazon RDS (встроенный), Amazon Aurora, Amazon DocumentDB, Amazon Neptune, Amazon RDS |",
    "| `s3.<REGION>.amazonaws.com` | Amazon S3 (built-in) |": "| `s3.<REGION>.amazonaws.com` | Amazon S3 (встроенный) |",
    "| `acm-pca.<REGION>.amazonaws.com` | AWS Certificate Manager Private Certificate Authority |": "| `acm-pca.<REGION>.amazonaws.com` | AWS Certificate Manager Private Certificate Authority |",
    "| `apigateway.<REGION>.amazonaws.com` | Amazon API Gateway |": "| `apigateway.<REGION>.amazonaws.com` | Amazon API Gateway |",
    "| `apprunner.<REGION>.amazonaws.com` | AWS App Runner |": "| `apprunner.<REGION>.amazonaws.com` | AWS App Runner |",
    "| `appstream2.<REGION>.amazonaws.com` | Amazon AppStream |": "| `appstream2.<REGION>.amazonaws.com` | Amazon AppStream |",
    "| `appsync.<REGION>.amazonaws.com` | AWS AppSync |": "| `appsync.<REGION>.amazonaws.com` | AWS AppSync |",
    "| `athena.<REGION>.amazonaws.com` | Amazon Athena |": "| `athena.<REGION>.amazonaws.com` | Amazon Athena |",
    "| `cloudfront.amazonaws.com` | Amazon CloudFront |": "| `cloudfront.amazonaws.com` | Amazon CloudFront |",
    "| `cloudhsmv2.<REGION>.amazonaws.com` | AWS CloudHSM |": "| `cloudhsmv2.<REGION>.amazonaws.com` | AWS CloudHSM |",
    "| `cloudsearch.<REGION>.amazonaws.com` | Amazon CloudSearch |": "| `cloudsearch.<REGION>.amazonaws.com` | Amazon CloudSearch |",
    "| `codebuild.<REGION>.amazonaws.com` | AWS CodeBuild |": "| `codebuild.<REGION>.amazonaws.com` | AWS CodeBuild |",
    "| `datasync.<REGION>.amazonaws.com` | AWS DataSync |": "| `datasync.<REGION>.amazonaws.com` | AWS DataSync |",
    "| `dax.<REGION>.amazonaws.com` | Amazon DynamoDB Accelerator (DAX) |": "| `dax.<REGION>.amazonaws.com` | Amazon DynamoDB Accelerator (DAX) |",
    "| `dms.<REGION>.amazonaws.com` | AWS Database Migration Service (AWS DMS) |": "| `dms.<REGION>.amazonaws.com` | AWS Database Migration Service (AWS DMS) |",
    "| `directconnect.<REGION>.amazonaws.com` | AWS Direct Connect |": "| `directconnect.<REGION>.amazonaws.com` | AWS Direct Connect |",
    "| `ecs.<REGION>.amazonaws.com` | Amazon Elastic Container Service (ECS), Amazon ECS Container Insights |": "| `ecs.<REGION>.amazonaws.com` | Amazon Elastic Container Service (ECS), Amazon ECS Container Insights |",
    "| `elasticfilesystem.<REGION>.amazonaws.com` | Amazon Elastic File System (EFS) |": "| `elasticfilesystem.<REGION>.amazonaws.com` | Amazon Elastic File System (EFS) |",
    "| `eks.<REGION>.amazonaws.com` | Amazon Elastic Kubernetes Service (EKS) |": "| `eks.<REGION>.amazonaws.com` | Amazon Elastic Kubernetes Service (EKS) |",
    "| `elasticache.<REGION>.amazonaws.com` | Amazon ElastiCache (EC) |": "| `elasticache.<REGION>.amazonaws.com` | Amazon ElastiCache (EC) |",
    "| `elasticbeanstalk.<REGION>.amazonaws.com` | AWS Elastic Beanstalk |": "| `elasticbeanstalk.<REGION>.amazonaws.com` | AWS Elastic Beanstalk |",
    "| `elastictranscoder.<REGION>.amazonaws.com` | Amazon Elastic Transcoder |": "| `elastictranscoder.<REGION>.amazonaws.com` | Amazon Elastic Transcoder |",
    "| `es.<REGION>.amazonaws.com` | Amazon Elasticsearch Service (ES) |": "| `es.<REGION>.amazonaws.com` | Amazon Elasticsearch Service (ES) |",
    "| `events.<REGION>.amazonaws.com` | Amazon EventBridge |": "| `events.<REGION>.amazonaws.com` | Amazon EventBridge |",
    "| `fsx.<REGION>.amazonaws.com` | Amazon FSx |": "| `fsx.<REGION>.amazonaws.com` | Amazon FSx |",
    "| `gamelift.<REGION>.amazonaws.com` | Amazon GameLift |": "| `gamelift.<REGION>.amazonaws.com` | Amazon GameLift |",
    "| `glue.<REGION>.amazonaws.com` | AWS Glue |": "| `glue.<REGION>.amazonaws.com` | AWS Glue |",
    "| `inspector.<REGION>.amazonaws.com` | Amazon Inspector |": "| `inspector.<REGION>.amazonaws.com` | Amazon Inspector |",
    "| `kafka.<REGION>.amazonaws.com` | Amazon Managed Streaming for Kafka |": "| `kafka.<REGION>.amazonaws.com` | Amazon Managed Streaming for Kafka |",
    "| `models.lex.<REGION>.amazonaws.com` | Amazon Lex |": "| `models.lex.<REGION>.amazonaws.com` | Amazon Lex |",
    "| `logs.<REGION>.amazonaws.com` | Amazon CloudWatch Logs |": "| `logs.<REGION>.amazonaws.com` | Amazon CloudWatch Logs |",
    "| `api.mediatailor.<REGION>.amazonaws.com` | AWS Elemental MediaTailor |": "| `api.mediatailor.<REGION>.amazonaws.com` | AWS Elemental MediaTailor |",
    "| `mediaconnect.<REGION>.amazonaws.com` | AWS Elemental MediaConnect |": "| `mediaconnect.<REGION>.amazonaws.com` | AWS Elemental MediaConnect |",
    "| `mediapackage.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Live |": "| `mediapackage.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Live |",
    "| `mediapackage-vod.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Video on Demand |": "| `mediapackage-vod.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Video on Demand |",
    "| `opsworks.<REGION>.amazonaws.com` | AWS OpsWorks |": "| `opsworks.<REGION>.amazonaws.com` | AWS OpsWorks |",
    "| `qldb.<REGION>.amazonaws.com` | Amazon QLDB |": "| `qldb.<REGION>.amazonaws.com` | Amazon QLDB |",
    "| `redshift.<REGION>.amazonaws.com` | Amazon Redshift |": "| `redshift.<REGION>.amazonaws.com` | Amazon Redshift |",
    "| `robomaker.<REGION>.amazonaws.com` | AWS RoboMaker |": "| `robomaker.<REGION>.amazonaws.com` | AWS RoboMaker |",
    "| `route53.amazonaws.com` | Amazon Route 53 |": "| `route53.amazonaws.com` | Amazon Route 53 |",
    "| `route53resolver.<REGION>.amazonaws.com` | Amazon Route 53 Resolver |": "| `route53resolver.<REGION>.amazonaws.com` | Amazon Route 53 Resolver |",
    "| `api.sagemaker.<REGION>.amazonaws.com` | Amazon SageMaker Endpoints, Amazon SageMaker Endpoint Instances |": "| `api.sagemaker.<REGION>.amazonaws.com` | Amazon SageMaker Endpoints, Amazon SageMaker Endpoint Instances |",
    "| `sns.<REGION>.amazonaws.com` | Amazon Simple Notification Service (SNS) |": "| `sns.<REGION>.amazonaws.com` | Amazon Simple Notification Service (SNS) |",
    "| `sqs.<REGION>.amazonaws.com` | Amazon Simple Queue Service (SQS) |": "| `sqs.<REGION>.amazonaws.com` | Amazon Simple Queue Service (SQS) |",
    "| `storagegateway.<REGION>.amazonaws.com` | AWS Storage Gateway |": "| `storagegateway.<REGION>.amazonaws.com` | AWS Storage Gateway |",
    "| `swf.<REGION>.amazonaws.com` | Amazon SWF |": "| `swf.<REGION>.amazonaws.com` | Amazon SWF |",
    "| `transfer.<REGION>.amazonaws.com` | AWS Transfer Family |": "| `transfer.<REGION>.amazonaws.com` | AWS Transfer Family |",
    "| `workmail.<REGION>.amazonaws.com` | Amazon WorkMail |": "| `workmail.<REGION>.amazonaws.com` | Amazon WorkMail |",
    "| `workspaces.<REGION>.amazonaws.com` | Amazon WorkSpaces |": "| `workspaces.<REGION>.amazonaws.com` | Amazon WorkSpaces |",
    "Amazon EC2 Auto Scaling (built-in) provides only basic metrics with the count of EC2 instances in the scaling group. To fully monitor extended metrics, you need to select [Amazon EC2 Auto Scaling](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/cloudwatch-ec2/ec2-auto-scaling \"Monitor Amazon EC2 Auto Scaling and view available metrics.\") (non-built-in) service.": "Amazon EC2 Auto Scaling (встроенный) предоставляет только базовые метрики с количеством экземпляров EC2 в группе масштабирования. Для полного мониторинга расширенных метрик необходимо выбрать сервис [Amazon EC2 Auto Scaling](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/cloudwatch-ec2/ec2-auto-scaling \"Мониторинг Amazon EC2 Auto Scaling и просмотр доступных метрик.\") (не встроенный).",
    "Remember that if you have EC2 Auto Scaling (built-in) service configured, you can’t have Amazon EC2 Auto Scaling (non-built-in) service turned on.": "Обратите внимание: если настроен сервис EC2 Auto Scaling (встроенный), нельзя одновременно включить сервис Amazon EC2 Auto Scaling (не встроенный).",
    "By default, Auto Scaling Group metrics aren't reported. To have them reported, you need to enable them in the **AWS Auto Scaling Group** console.": "По умолчанию метрики Auto Scaling Group не передаются. Чтобы включить их передачу, необходимо активировать их в консоли **AWS Auto Scaling Group**.",
    "## Enable monitoring": "## Включение мониторинга",
    "To learn how to enable service monitoring, see [Enable service monitoring](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-metrics-ingest/aws-enable-service-monitoring \"Enable AWS monitoring in Dynatrace.\").": "Чтобы узнать, как включить мониторинг сервиса, см. [Включение мониторинга сервиса](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-metrics-ingest/aws-enable-service-monitoring \"Включение мониторинга AWS в Dynatrace.\").",
    "## View service metrics": "## Просмотр метрик сервиса",
    "You can view the service metrics in your Dynatrace environment either on the **AWS account page** or on your **Dashboards** page.": "Метрики сервиса можно просматривать в среде Dynatrace на **странице аккаунта AWS** или на странице **Dashboards**.",
    "### View metrics on the AWS account page": "### Просмотр метрик на странице аккаунта AWS",
    "To view metrics on the AWS account page": "Чтобы просмотреть метрики на странице аккаунта AWS",
    "1. Go to **AWS**.": "1. Перейдите в **AWS**.",
    "2. Choose AWS account you want to check metrics for.": "2. Выберите аккаунт AWS, для которого нужно проверить метрики.",
    "3. Select **Service** box. Metrics for the selected service are visible under the infographic in the service section.": "3. Выберите блок **Service**. Метрики выбранного сервиса отображаются под инфографикой в разделе сервиса.",
    "### View metrics on the Dashboard": "### Просмотр метрик на дашборде",
    "You can also create your own dashboard. For more information on how to create dashboards, go to [Create and edit Dynatrace dashboards](/managed/analyze-explore-automate/dashboards-classic/dashboards/create-dashboards \"Learn how to create and edit Dynatrace dashboards.\")": "Также можно создать собственный дашборд. Дополнительные сведения о создании дашбордов см. в разделе [Создание и редактирование дашбордов Dynatrace](/managed/analyze-explore-automate/dashboards-classic/dashboards/create-dashboards \"Узнайте, как создавать и редактировать дашборды Dynatrace.\").",
    "Built-in services specifics": "Особенности встроенных сервисов",
    "This is a built-in service. It's monitored out-of-the-box once a new AWS integration instance is created. For built-in services, all metrics are recommended (changing configuration is not possible).": "Это встроенный сервис. Он мониторируется автоматически после создания нового экземпляра интеграции AWS. Для встроенных сервисов все метрики рекомендованы (изменить конфигурацию невозможно).",
    "**Example of AWS built-in monitoring service**": "**Пример встроенного сервиса мониторинга AWS**",
    "![example of AWS builtin monitoring service ](https://dt-cdn.net/images/aws-builtin-example-2481-6a8831f5b3.png)": "![example of AWS builtin monitoring service ](https://dt-cdn.net/images/aws-builtin-example-2481-6a8831f5b3.png)",
    "example of AWS builtin monitoring service": "example of AWS builtin monitoring service",
    "## Available metrics": "## Доступные метрики",
    "`AutoScalingGroupName` is the main dimension.": "`AutoScalingGroupName` является основным измерением.",
    "| Metric key | Name | Unit | Aggregations | Monitoring consumption |": "| Ключ метрики | Название | Единица | Агрегации | Потребление мониторинга |",
    "| --- | --- | --- | --- | --- |": "| --- | --- | --- | --- | --- |",
    "| builtin:cloud.aws.asg.running | Number of running EC2 instances (ASG) | Count | autoavgmaxmin | DDUs |": "| builtin:cloud.aws.asg.running | Количество запущенных экземпляров EC2 (ASG) | Количество | autoavgmaxmin | DDU |",
    "| builtin:cloud.aws.asg.stopped | Number of stopped EC2 instances (ASG) | Count | autoavgmaxmin | DDUs |": "| builtin:cloud.aws.asg.stopped | Количество остановленных экземпляров EC2 (ASG) | Количество | autoavgmaxmin | DDU |",
    "| builtin:cloud.aws.asg.terminated | Number of terminated EC2 instances (ASG) | Count | autoavgmaxmin | DDUs |": "| builtin:cloud.aws.asg.terminated | Количество завершённых экземпляров EC2 (ASG) | Количество | autoavgmaxmin | DDU |",
}

PASS = {
    "* `\"cloudwatch:GetMetricData\"`",
    "* `\"cloudwatch:GetMetricStatistics\"`",
    "* `\"cloudwatch:ListMetrics\"`",
    "* `\"sts:GetCallerIdentity\"`",
    "* `\"tag:GetResources\"`",
    "* `\"tag:GetTagKeys\"`",
    "* `\"ec2:DescribeAvailabilityZones\"`",
}

build_one(REL, "ec2-auto-scaling-builltin.md", TRANS, PASS)
qa_one(REL, "ec2-auto-scaling-builltin.md")
