# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/google-cloud-platform/gcp-integrations/gcp-guide"
FILE = "deploy-with-google-cloud-function.md"

TRANS = {
    "title: Deploy the Dynatrace Google Cloud metric integration in Google Cloud Functions": "title: Развёртывание интеграции метрик Dynatrace Google Cloud в Google Cloud Functions",
    "# Deploy the Dynatrace Google Cloud metric integration in Google Cloud Functions": "# Развёртывание интеграции метрик Dynatrace Google Cloud в Google Cloud Functions",
    "* How-to guide": "* Практическое руководство",
    "* 7-min read": "* Чтение: 7 мин",
    "* Updated on Sep 06, 2022": "* Обновлено 6 сентября 2022 г.",
    "* Deprecated": "* Устарело",
    "Dynatrace version 1.230+": "Dynatrace версии 1.230+",
    "Dynatrace Google Cloud metric integration in Google Cloud Functions is **not** supported anymore.": "Интеграция метрик Dynatrace Google Cloud в Google Cloud Functions **больше не** поддерживается.",
    "If you're using this kind of deployment, you should switch to k8s-based Google Cloud integration as soon as possible.": "Если используется такой тип развёртывания, необходимо как можно скорее перейти на интеграцию Google Cloud на основе k8s.",
    'See [Migrate from Google Cloud Functions 1.0 to Google Cloud k8s 1.0](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/migrate-gcp-function-1-to-k8s-1 "Migrate from Google Cloud Functions v1.0 to Google Cloud k8s v1.0.").': 'См. раздел [Миграция с Google Cloud Functions 1.0 на Google Cloud k8s 1.0](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/migrate-gcp-function-1-to-k8s-1 "Миграция с Google Cloud Functions v1.0 на Google Cloud k8s v1.0.").',
    'As an alternative to the [main deployment](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-k8 "Set up log and metric monitoring for GCP services on a new GKE Autopilot cluster."), that provides Google Cloud monitoring for both metrics and logs, and where the deployment takes place in a GKE cluster, you can choose to set up monitoring for metrics only, in Google Cloud Cloud Function. Note that the Google Cloud Cloud Function deployment isn\'t recommended for large environments and doesn\'t support log forwarding.': 'В качестве альтернативы [основному развёртыванию](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-k8 "Настройка мониторинга логов и метрик для сервисов GCP в новом кластере GKE Autopilot."), которое обеспечивает мониторинг Google Cloud как для метрик, так и для логов в кластере GKE, можно настроить мониторинг только метрик в Google Cloud Cloud Function. Развёртывание через Google Cloud Cloud Function не рекомендуется для крупных сред и не поддерживает пересылку логов.',
    "In this scenario, you will be able run the deployment script either in Google Cloud Shell or in bash. After installation, you'll get metrics, dashboards, and alerts for your configured services in Dynatrace.": "В этом сценарии скрипт развёртывания запускается в Google Cloud Shell или bash. После установки в Dynatrace появятся метрики, дашборды и оповещения для настроенных сервисов.",
    'For other deployment options, see [Alternative deployment scenarios](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide "Other options to set up log and/or metric monitoring for Google Cloud services").': 'Другие варианты развёртывания описаны в разделе [Альтернативные сценарии развёртывания](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide "Другие варианты настройки мониторинга логов и/или метрик для сервисов Google Cloud").',
    "This page describes how to deploy version 1.0 of the Dynatrace Google Cloud integration in Google Cloud Cloud Function.": "На этой странице описывается развёртывание версии 1.0 интеграции Dynatrace Google Cloud в Google Cloud Cloud Function.",
    '* If you already have an [earlier version](/managed/ingest-from/google-cloud-platform/legacy/deploy-with-google-cloud-function-legacy "Set up monitoring for Google Cloud services using a Google Cloud Function.") of the Google Cloud Monitor installed, you need to [migrate](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/migrate-gcp-function "Migrate from Google Cloud integration version 0.1 to version 1.0 on Kubernetes and as a Google Cloud Function.").': '* Если установлена [более ранняя версия](/managed/ingest-from/google-cloud-platform/legacy/deploy-with-google-cloud-function-legacy "Настройка мониторинга для сервисов Google Cloud с использованием Google Cloud Function.") Google Cloud Monitor, необходимо выполнить [миграцию](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/migrate-gcp-function "Миграция с Google Cloud integration версии 0.1 на версию 1.0 в Kubernetes и как Google Cloud Function.").',
    "## Prerequisites": "## Предварительные требования",
    "### Tools": "### Инструменты",
    "You can deploy the Dynatrace Google Cloud integration in Google Cloud Shell or in bash.": "Интеграцию Dynatrace Google Cloud можно развернуть в Google Cloud Shell или bash.",
    "If you use bash, you need to install:": "При использовании bash необходимо установить:",
    "* [Google Cloud SDK](https://dt-url.net/e8110336)": "* [Google Cloud SDK](https://dt-url.net/e8110336)",
    "### Google Cloud permissions": "### Разрешения Google Cloud",
    "Running the deployment script requires a list of permissions. You need to create a custom role and use it to deploy `dynatrace-gcp-monitor`.": "Для запуска скрипта развёртывания требуется набор разрешений. Необходимо создать пользовательскую роль и использовать её для развёртывания `dynatrace-gcp-monitor`.",
    "To create a custom role": "Чтобы создать пользовательскую роль",
    "1. Create a YAML file named `dynatrace-gcp-monitor-cloud-function-deployment-role.yaml` with the following content:": "1. Создайте YAML-файл с именем `dynatrace-gcp-monitor-cloud-function-deployment-role.yaml` со следующим содержимым:",
    "dynatrace-gcp-monitor-cloud-function-deployment-role.yaml": "dynatrace-gcp-monitor-cloud-function-deployment-role.yaml",
    "2. Run the command below, replacing `<your_project_ID>` with the project ID where you want to deploy the Dynatrace integration.": "2. Выполните команду ниже, заменив `<your_project_ID>` на идентификатор проекта, в котором требуется развернуть интеграцию Dynatrace.",
    "Be sure to add this role to your Google Cloud user. For details, see [Grant or revoke a single role](https://dt-url.net/vx03vid).": "Обязательно добавьте эту роль своему пользователю Google Cloud. Подробности см. в разделе [Предоставление или отзыв одной роли](https://dt-url.net/vx03vid).",
    "### Dynatrace permissions": "### Разрешения Dynatrace",
    "[Create an API token](https://dt-url.net/be03q3a) and [enable the following permissions](https://dt-url.net/c023q1m):": "[Создайте API-токен](https://dt-url.net/be03q3a) и [включите следующие разрешения](https://dt-url.net/c023q1m):",
    "* API v1:": "* API v1:",
    "+ **Read configuration**": "+ **Чтение конфигурации**",
    "+ **Write configuration**": "+ **Запись конфигурации**",
    "* API v2:": "* API v2:",
    "+ **Ingest metrics**": "+ **Приём метрик**",
    "+ **Read extensions**": "+ **Чтение расширений**",
    "+ **Write extensions**": "+ **Запись расширений**",
    "+ **Read extension monitoring configurations**": "+ **Чтение конфигураций мониторинга расширений**",
    "+ **Write extension monitoring configurations**": "+ **Запись конфигураций мониторинга расширений**",
    "+ **Read extension environment configurations**": "+ **Чтение конфигураций среды расширений**",
    "+ **Write extension environment configurations**": "+ **Запись конфигураций среды расширений**",
    "### Dynatrace URL": "### URL Dynatrace",
    "Determine the URL for your environment.": "Определите URL своей среды.",
    "* For Dynatrace SaaS: `https://<your-environment-id>.live.dynatrace.com/`": "* Для Dynatrace SaaS: `https://<your-environment-id>.live.dynatrace.com/`",
    "* For Dynatrace Managed: `https://<your-domain>/e/<your-environment-id>/`": "* Для Dynatrace Managed: `https://<your-domain>/e/<your-environment-id>/`",
    "To determine `<your-environment-id>`, see [environment ID](https://dt-url.net/ej43qge).": "Чтобы узнать `<your-environment-id>`, см. раздел [Идентификатор среды](https://dt-url.net/ej43qge).",
    "## Install": "## Установка",
    "You can deploy the Dynatrace Google Cloud integration in Google Cloud Shell or in bash. To set up integration, follow the instructions below.": "Интеграцию Dynatrace Google Cloud можно развернуть в Google Cloud Shell или bash. Для настройки интеграции следуйте инструкциям ниже.",
    "For bash deployment, be sure to restart the console and [initialize Cloud SDK](https://dt-url.net/ac43q0f) before you start installation.": "При развёртывании в bash перед установкой необходимо перезапустить консоль и [инициализировать Cloud SDK](https://dt-url.net/ac43q0f).",
    "To initialize Cloud SDK, run": "Чтобы инициализировать Cloud SDK, выполните",
    '[![Step 1](https://dt-cdn.net/images/step-1-086e22066c.svg "Step 1")': '[![Шаг 1](https://dt-cdn.net/images/step-1-086e22066c.svg "Шаг 1")',
    '**Download the deployment package**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-with-google-cloud-function#dwld "Set up monitoring for Google Cloud services in Google Cloud Functions.")[![Step 2](https://dt-cdn.net/images/step-2-1a1384627e.svg "Step 2")': '**Загрузить пакет развёртывания**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-with-google-cloud-function#dwld "Настройка мониторинга сервисов Google Cloud в Google Cloud Functions.")[![Шаг 2](https://dt-cdn.net/images/step-2-1a1384627e.svg "Шаг 2")',
    '**Configure deployment**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-with-google-cloud-function#configure-deployment "Set up monitoring for Google Cloud services in Google Cloud Functions.")[![Step 3](https://dt-cdn.net/images/step-3-350cf6c19a.svg "Step 3")': '**Настроить развёртывание**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-with-google-cloud-function#configure-deployment "Настройка мониторинга сервисов Google Cloud в Google Cloud Functions.")[![Шаг 3](https://dt-cdn.net/images/step-3-350cf6c19a.svg "Шаг 3")',
    '**Run the deployment script**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-with-google-cloud-function#script "Set up monitoring for Google Cloud services in Google Cloud Functions.")': '**Запустить скрипт развёртывания**](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-with-google-cloud-function#script "Настройка мониторинга сервисов Google Cloud в Google Cloud Functions.")',
    "### Step 1 Download the deployment package": "### Шаг 1 Загрузка пакета развёртывания",
    "### Step 2 Configure deployment": "### Шаг 2 Настройка развёртывания",
    "1. Adjust the parameters in the `activation-config.yaml` file from the deployment package.": "1. Настройте параметры в файле `activation-config.yaml` из пакета развёртывания.",
    "You might want to store this file somewhere for future updates, since it will be needed in case of redeployments. Also, keep in mind that its schema can change. In such case, you should use the new file and only copy over the parameter values.": "Рекомендуется сохранить этот файл для будущих обновлений, так как он потребуется при повторных развёртываниях. Учтите, что его схема может меняться: в таком случае следует использовать новый файл и переносить только значения параметров.",
    "2. Choose which services you want Dynatrace to monitor.": "2. Выберите сервисы для мониторинга в Dynatrace.",
    "By default, the Google Cloud integration starts monitoring a series of selected services. Uncomment any additional services you want Dynatrace to monitor in the `activation-config.yaml` file.": "По умолчанию интеграция Google Cloud начинает мониторинг набора выбранных сервисов. Раскомментируйте в файле `activation-config.yaml` дополнительные сервисы для мониторинга в Dynatrace.",
    "For DDU consumption information, see [Monitoring consumption](#ddu).": "Информацию о потреблении DDU см. в разделе [Потребление при мониторинге](#ddu).",
    "### Step 3 Run the deployment script": "### Шаг 3 Запуск скрипта развёртывания",
    "Version upgrade of extensions is done by default. To keep the versions of existing extensions, run the script with the `--without-extensions-upgrade` parameter.": "Обновление версий расширений выполняется по умолчанию. Чтобы сохранить текущие версии существующих расширений, запустите скрипт с параметром `--without-extensions-upgrade`.",
    "The script may ask you for confirmations during deployment. For CI/CD purposes, you can add the `-d` option to make the script noninteractive.": "Во время развёртывания скрипт может запрашивать подтверждения. Для целей CI/CD добавьте параметр `-d`, чтобы скрипт работал в неинтерактивном режиме.",
    "After deploying the integration, you can see metrics from monitored services. If you want to change the monitoring scope (services & featureSets) or update the Google Cloud integration, see [Change deployment settings](#manage) below.": "После развёртывания интеграции в Dynatrace появятся метрики отслеживаемых сервисов. Чтобы изменить область мониторинга (сервисы и featureSets) или обновить интеграцию Google Cloud, см. раздел [Изменение параметров развёртывания](#manage) ниже.",
    "## Verify installation": "## Проверка установки",
    "To check whether installation was successful": "Чтобы проверить успешность установки",
    "1. In your Google Cloud console, go to Cloud Functions and make sure that `dynatrace-gcp-monitor` is there.": "1. В консоли Google Cloud перейдите в раздел Cloud Functions и убедитесь, что `dynatrace-gcp-monitor` присутствует.",
    "2. Select the newly deployed Google Cloud Monitor function and go to **Logs** to make sure there are no error messages.": "2. Выберите только что развёрнутую функцию Google Cloud Monitor и перейдите в раздел **Logs**, чтобы убедиться в отсутствии сообщений об ошибках.",
    "## Enable alerting": "## Включение оповещений",
    "To activate alerting, you need to enable metric events for alerting in Dynatrace.": "Для активации оповещений необходимо включить метрические события для оповещений в Dynatrace.",
    "To enable custom events": "Чтобы включить пользовательские события",
    "1. Go to **Settings**.": "1. Перейдите в раздел **Settings**.",
    "2. In **Anomaly detection**, select **Metric events**.": "2. В разделе **Anomaly detection** выберите **Metric events**.",
    "3. Filter for GCP alerts and turn on **On/Off** for the alerts you want to activate.": "3. Отфильтруйте оповещения GCP и включите **On/Off** для нужных оповещений.",
    "## View enabled services": "## Просмотр включённых сервисов",
    "To find the list of currently enabled services, go to Cloud Function in your Google Cloud console, and check the `ACTIVATION_CONFIG` environment variable.": "Чтобы найти список включённых сервисов, перейдите в Cloud Function в консоли Google Cloud и проверьте переменную среды `ACTIVATION_CONFIG`.",
    "## Update services": "## Обновление сервисов",
    "Adding, removing and updating versions of existing services is done by modyfing the corresponding list of services and redeploying.": "Добавление, удаление и обновление версий существующих сервисов выполняется путём изменения соответствующего списка сервисов и повторного развёртывания.",
    "1. Apply your changes to `activation-config.yaml` by commenting or uncommenting configuration blocks corresponding to specific services.": "1. Внесите изменения в `activation-config.yaml`, закомментировав или раскомментировав блоки конфигурации для конкретных сервисов.",
    "Terminology within the file includes:": "Терминология файла включает:",
    "* `service`: represents Google Cloud service name you want to monitor. Services are grouped by extensions, but you can decide what you need to monitor on a lower level (`featureSets`)": "* `service`: название сервиса Google Cloud для мониторинга. Сервисы сгруппированы по расширениям, но можно указать, что отслеживать на более детальном уровне (`featureSets`).",
    "* `featureSet`: a set of metrics for a given service. `default_metrics` is a default `featureSet` with a recommended set of metrics to be monitored. In more specific use cases, you can consider monitoring such sets as `istio featureSet` for `gae_instance service`": "* `featureSet`: набор метрик для конкретного сервиса. `default_metrics` является набором `featureSet` по умолчанию с рекомендуемыми метриками. В отдельных случаях можно рассмотреть мониторинг таких наборов, как `istio featureSet` для `gae_instance service`.",
    "* `filter_conditions`: a service-level filter that enables you to narrow the monitoring scope. It is based on the [Google Cloud Monitoring filters](https://cloud.google.com/monitoring/api/v3/filters?hl=en_US).": "* `filter_conditions`: фильтр уровня сервиса для сужения области мониторинга на основе [фильтров GCP Monitoring](https://cloud.google.com/monitoring/api/v3/filters?hl=en_US).",
    "Example:": "Пример:",
    "2. Update monitored services by running the script below.": "2. Обновите отслеживаемые сервисы, запустив скрипт ниже.",
    "3. If you removed services from monitoring, find the relevant extensions in Dynatrace Hub and delete them to remove service-specific assets (such as dashboards and alerts).": "3. Если сервисы были исключены из мониторинга, найдите соответствующие расширения в Dynatrace Hub и удалите их, чтобы убрать специфические ресурсы (дашборды и оповещения).",
    "### Example": "### Пример",
    "In the following example": "В следующем примере",
    "* The `gae_instance` service is disabled.": "* Сервис `gae_instance` отключён.",
    "* For the `gce_instance` service, only two feature sets are enabled: `default_metrics` and `istio`.": "* Для сервиса `gce_instance` включены только два набора функций: `default_metrics` и `istio`.",
    'For a complete list of the Google Cloud supported services, see [Google Cloud supported services](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-supported-service-metrics-new#services "Monitor Google Cloud services with Dynatrace and view available metrics.").': 'Полный список поддерживаемых сервисов Google Cloud см. в разделе [Поддерживаемые сервисы Google Cloud](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-supported-service-metrics-new#services "Мониторинг сервисов Google Cloud с помощью Dynatrace и просмотр доступных метрик.").',
    "## Change deployment settings": "## Изменение параметров развёртывания",
    "To add or remove services, or to update parameters, you need to redeploy the integration.": "Для добавления или удаления сервисов либо обновления параметров необходимо повторно развернуть интеграцию.",
    "1. Apply your changes to `activation-config.yaml`.": "1. Внесите изменения в `activation-config.yaml`.",
    "Be sure to use the same value for the `FUNCTION_NAME` parameter as before.": "Обязательно используйте то же значение параметра `FUNCTION_NAME`, что и раньше.",
    "2. [Rerun the deployment script](#script).": "2. [Повторно запустите скрипт развёртывания](#script).",
    "## Verification": "## Верификация",
    "To investigate potential deployment and connectivity issues": "Для диагностики возможных проблем с развёртыванием и подключением",
    "1. [Verify installation](#verify)": "1. [Проверьте установку](#verify)",
    '2. [Enable self-monitoring](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-k8/self-monitoring-gcp "Determine if your self-monitoring function is properly processing and sending logs to Dynatrace.") Optional': '2. [Включите самомониторинг](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-k8/self-monitoring-gcp "Определите, правильно ли функция самомониторинга обрабатывает и отправляет логи в Dynatrace.") Опционально',
    "3. Check the `dynatrace_gcp_<date_time>.log` log file created during the installation process.": "3. Проверьте лог-файл `dynatrace_gcp_<date_time>.log`, созданный в процессе установки.",
    "* This file will be created each time the installation script runs.": "* Этот файл создаётся при каждом запуске скрипта установки.",
    "* The debug information won't contain sensitive data such as the Dynatrace access key.": "* Отладочная информация не содержит конфиденциальных данных, таких как ключ доступа Dynatrace.",
    "* If you are contacting a Dynatrace product expert via live chat:": "* При обращении к эксперту Dynatrace через чат:",
    "+ Make sure to provide the `dynatrace_gcp_<date_time>.log` log file described in the previous step.": "+ Предоставьте лог-файл `dynatrace_gcp_<date_time>.log`, описанный на предыдущем шаге.",
    "+ Provide version information.": "+ Укажите информацию о версии.",
    "- For issues during installation, check the `version.txt` file.": "- Для проблем при установке проверьте файл `version.txt`.",
    "- For issues during runtime, [check function logs](#verify).": "- Для проблем во время работы [проверьте логи функции](#verify).",
    "## Uninstall": "## Удаление",
    "1. Go to your installation directory and run the command below.": "1. Перейдите в каталог установки и выполните команду ниже.",
    "2. To remove all monitoring assets (such as dashboards and alerts) from Dynatrace, you need to remove all Google Cloud extensions.": "2. Чтобы удалить все ресурсы мониторинга (дашборды и оповещения) из Dynatrace, необходимо удалить все расширения Google Cloud.",
    "You can find and delete relevant extensions via Dynatrace Hub.": "Найти и удалить соответствующие расширения можно через Dynatrace Hub.",
    "## Monitoring consumption": "## Потребление при мониторинге",
    'All cloud services consume DDUs. The amount of DDU consumption per service instance depends on the number of monitored metrics and their dimensions (each metric dimension results in the ingestion of 1 data point; 1 data point consumes 0.001 DDUs). For details, see [Extending Dynatrace (Davis data units)](/managed/license/monitoring-consumption-classic/davis-data-units "Understand how Dynatrace monitoring consumption is calculated based on Davis data units (DDU).").' : 'Все облачные сервисы потребляют DDU. Объём потребления DDU на экземпляр сервиса зависит от числа отслеживаемых метрик и их измерений (каждое измерение метрики приводит к приёму 1 точки данных; 1 точка данных потребляет 0,001 DDU). Подробности см. в разделе [Расширение Dynatrace (единицы данных Davis)](/managed/license/monitoring-consumption-classic/davis-data-units "Понимание расчёта потребления мониторинга Dynatrace на основе единиц данных Davis (DDU).").',
    "## Related topics": "## Связанные темы",
    '* [Set up Dynatrace on Google Cloud](/managed/ingest-from/google-cloud-platform "Monitor Google Cloud with Dynatrace.")': '* [Настройка Dynatrace в Google Cloud](/managed/ingest-from/google-cloud-platform "Мониторинг Google Cloud с помощью Dynatrace.")',
}

PASS = {
    "source: https://docs.dynatrace.com/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-with-google-cloud-function",
    "scraped: 2026-05-12T11:51:49.839631",
}

build_one(REL, FILE, TRANS, PASS)
qa_one(REL, FILE)
