# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/google-cloud-platform/legacy"
FNAME = "deploy-with-google-cloud-function-legacy.md"

TRANS = {
    "title: Deploy the Dynatrace Google Cloud metric integration using a Google Cloud Function (legacy)": "title: Развёртывание интеграции метрик Dynatrace Google Cloud с использованием Google Cloud Function (устаревшее)",
    "# Deploy the Dynatrace Google Cloud metric integration using a Google Cloud Function (legacy)": "# Развёртывание интеграции метрик Dynatrace Google Cloud с использованием Google Cloud Function (устаревшее)",
    "* How-to guide": "* Практическое руководство",
    "* 5-min read": "* Чтение: 5 мин",
    "* Published Mar 12, 2021": "* Опубликовано 12 марта 2021 г.",
    "* Deprecated": "* Устаревшее",
    "This page describes how to install Google Cloud Function version 0.1, which is scheduled for deprecation.": "На этой странице описывается установка Google Cloud Function версии 0.1, которая запланирована к устареванию.",
    '* If you are making a fresh installation, you should [deploy Google Cloud Function version 1.0](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-with-google-cloud-function "Set up monitoring for Google Cloud services in Google Cloud Functions.").': '* Для новой установки следует [развернуть Google Cloud Function версии 1.0](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-with-google-cloud-function "Настройка мониторинга сервисов Google Cloud с помощью Google Cloud Functions.").',
    '* If you already have version 0.1 of the Google Cloud Function installed, you should [migrate to Google Cloud Function version 1.0](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/migrate-gcp-function "Migrate from Google Cloud integration version 0.1 to version 1.0 on Kubernetes and as a Google Cloud Function.").': '* Если Google Cloud Function версии 0.1 уже установлена, следует [выполнить миграцию на Google Cloud Function версии 1.0](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/migrate-gcp-function "Миграция интеграции с Google Cloud с версии 0.1 на версию 1.0 в Kubernetes и в виде Google Cloud Function.").',
    "## Install": "## Установка",
    "To set up the Dynatrace integration as a Google Cloud Function, follow the instructions below.": "Для настройки интеграции Dynatrace в виде Google Cloud Function следуйте инструкциям ниже.",
    "Deploy in Google Cloud Shell": "Развёртывание в Google Cloud Shell",
    "Deploy in bash": "Развёртывание в bash",
    "### Prerequisites": "### Предварительные условия",
    "* [Install yq version 4.9.8﻿](https://dt-url.net/411p0nlq)": "* [Установите yq версии 4.9.8﻿](https://dt-url.net/411p0nlq)",
    "**Example command to install yq:**": "**Пример команды для установки yq:**",
    "* [Install jq﻿](https://dt-url.net/cl1203zc)": "* [Установите jq﻿](https://dt-url.net/cl1203zc)",
    "* [Create an API token﻿](https://dt-url.net/be03q3a)": "* [Создайте API-токен﻿](https://dt-url.net/be03q3a)",
    "* [Enable the following permissions for the API token﻿](https://dt-url.net/c023q1m): `Ingest metrics` (API v2), `Read configuration` (API v1), and `Write configuration` (API v1)": "* [Включите следующие разрешения для API-токена﻿](https://dt-url.net/c023q1m): `Ingest metrics` (API v2), `Read configuration` (API v1) и `Write configuration` (API v1)",
    "* Determine the URL for your environment.": "* Определите URL вашей среды.",
    "+ For Dynatrace SaaS: `https://<your-environment-id>.live.dynatrace.com/`": "+ Для Dynatrace SaaS: `https://<your-environment-id>.live.dynatrace.com/`",
    "+ For Dynatrace Managed: `https://<your-domain>/e/<your-environment-id>/`": "+ Для Dynatrace Managed: `https://<your-domain>/e/<your-environment-id>/`",
    "To determine `<your-environment-id>`, see [environment ID﻿](https://dt-url.net/ej43qge).": "Чтобы определить `<your-environment-id>`, см. [идентификатор среды﻿](https://dt-url.net/ej43qge).",
    "* Running the deployment script requires a list of permissions. You can create a custom role (instruction below) and use it to deploy `dynatrace-gcp-monitor`.": "* Для запуска скрипта развёртывания требуется набор разрешений. Можно создать пользовательскую роль (инструкция ниже) и использовать её для развёртывания `dynatrace-gcp-monitor`.",
    "1. Create a YAML file named `dynatrace-gcp-monitor-cloud-function-deployment-role.yaml` with the following content:": "1. Создайте YAML-файл с именем `dynatrace-gcp-monitor-cloud-function-deployment-role.yaml` со следующим содержимым:",
    "dynatrace-gcp-monitor-cloud-function-deployment-role.yaml": "dynatrace-gcp-monitor-cloud-function-deployment-role.yaml",
    "2. Run the command below, replacing `<your_project_ID>` with the project ID where you want to deploy the Dynatrace integration.": "2. Выполните приведённую ниже команду, заменив `<your_project_ID>` на идентификатор проекта, в котором нужно развернуть интеграцию Dynatrace.",
    "Be sure to add this role to your GCP user.": "Обязательно добавьте эту роль своему пользователю GCP.",
    "To deploy the Dynatrace GCP function in Google Cloud Shell, download and run the installation script below, making sure to replace `<VERSION>` with the release version you want to download, for example `0.1.19`.": "Для развёртывания функции Dynatrace GCP в Google Cloud Shell загрузите и запустите скрипт установки ниже, заменив `<VERSION>` на нужную версию релиза, например `0.1.19`.",
    'Be sure to choose one of the versions before `release-1.0.0`, as the newer versions require [different installation instructions](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-k8 "Set up log and metric monitoring for GCP services on a new GKE Autopilot cluster.").': 'Обязательно выбирайте версию, выпущенную до `release-1.0.0`, так как более новые версии требуют [других инструкций по установке](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-guide/deploy-k8 "Настройка мониторинга логов и метрик для сервисов GCP в новом кластере GKE Autopilot.").',
    "The Dynatrace GCP Monitor uses [Cloud Scheduler﻿](https://dt-url.net/n483qgj), which requires the App Engine application. If you don't have App Engine installed, the installer script will prompt you to create App Engine and select the region where you want the installer script to run.": "Dynatrace GCP Monitor использует [Cloud Scheduler﻿](https://dt-url.net/n483qgj), которому требуется приложение App Engine. Если App Engine не установлен, скрипт установки предложит создать его и выбрать регион, в котором будет выполняться скрипт.",
    "The installation script will prompt for the following parameters:": "Скрипт установки запросит следующие параметры:",
    "* **GCP project ID** - The ID of the Google Cloud project where you want to deploy the Dynatrace GCP Monitor. The default is set to the current project ID, for the gcloud CLI.": "* **GCP project ID**: идентификатор проекта Google Cloud, в котором нужно развернуть Dynatrace GCP Monitor. По умолчанию используется текущий идентификатор проекта из gcloud CLI.",
    "* **Function size** - The amount of memory that you want to allocate to the function. You can select one of the following:": "* **Function size**: объём памяти для выделения функции. Доступные варианты:",
    "+ `[s]` - Small (allocates 256 MB memory to the function). Select this option if you have up to 500 GCP service instances.": "+ `[s]`: Small (выделяет 256 МБ памяти функции). Выберите этот вариант, если у вас до 500 экземпляров сервисов GCP.",
    "+ `[m]` - Medium (allocates 512 MB memory to the function). Select this option if you have up to 1,000 GCP service instances.": "+ `[m]`: Medium (выделяет 512 МБ памяти функции). Выберите этот вариант, если у вас до 1000 экземпляров сервисов GCP.",
    "+ `[l]` - Large (allocates 2,048 MB memory to the function). Select this option if you have up to 5,000 GCP service instances.": "+ `[l]`: Large (выделяет 2048 МБ памяти функции). Выберите этот вариант, если у вас до 5000 экземпляров сервисов GCP.",
    "You can adjust the amount of memory after installation.": "Объём памяти можно изменить после установки.",
    "* **Dynatrace tenant URI** - Your Dynatrace environment URL. See **Prerequisites** for details.": "* **Dynatrace tenant URI**: URL вашей среды Dynatrace. Подробнее см. в разделе **Предварительные условия**.",
    "* **Dynatrace API token** - Your Dynatrace API token. See **Prerequisites** for details.": "* **Dynatrace API token**: ваш API-токен Dynatrace. Подробнее см. в разделе **Предварительные условия**.",
    "* [Install jq﻿](https://dt-url.net/cl1203zc)": "* [Установите jq﻿](https://dt-url.net/cl1203zc)",
    "* [Install yq 4.9.x﻿](https://dt-url.net/411p0nlq)": "* [Установите yq 4.9.x﻿](https://dt-url.net/411p0nlq)",
    "* [Install Google Cloud SDK﻿](https://dt-url.net/e8110336)": "* [Установите Google Cloud SDK﻿](https://dt-url.net/e8110336)",
    "* [Create an API token﻿](https://dt-url.net/be03q3a)": "* [Создайте API-токен﻿](https://dt-url.net/be03q3a)",
    "* [Enable the `Ingest metrics`, `Read configuration`, and `Write configuration` permissions for the API token﻿](https://dt-url.net/c023q1m)": "* [Включите разрешения `Ingest metrics`, `Read configuration` и `Write configuration` для API-токена﻿](https://dt-url.net/c023q1m)",
    "* Determine the URL for your environment.": "* Определите URL вашей среды.",
    "**For SaaS:**": "**Для SaaS:**",
    "`https://<your-environment-id>.live.dynatrace.com/`": "`https://<your-environment-id>.live.dynatrace.com/`",
    "**For Managed:**": "**Для Managed:**",
    "`https://<your-domain>/e/<your-environment-id>/`": "`https://<your-domain>/e/<your-environment-id>/`",
    "To determine `<your-environment-id>`, see [environment ID﻿](https://dt-url.net/ej43qge).": "Чтобы определить `<your-environment-id>`, см. [идентификатор среды﻿](https://dt-url.net/ej43qge).",
    "* Running the deployment script requires a list of permissions. You can create a custom role (instruction below) and use it to deploy `dynatrace-gcp-monitor`.": "* Для запуска скрипта развёртывания требуется набор разрешений. Можно создать пользовательскую роль (инструкция ниже) и использовать её для развёртывания `dynatrace-gcp-monitor`.",
    "1. Create a YAML file named `dynatrace-gcp-monitor-cloud-function-deployment-role.yaml` with the following content:": "1. Создайте YAML-файл с именем `dynatrace-gcp-monitor-cloud-function-deployment-role.yaml` со следующим содержимым:",
    "2. Run the command below, replacing `<your_project_ID>` with the project ID where you want to deploy the Dynatrace integration.": "2. Выполните приведённую ниже команду, заменив `<your_project_ID>` на идентификатор проекта, в котором нужно развернуть интеграцию Dynatrace.",
    "Be sure to add this role to your GCP user.": "Обязательно добавьте эту роль своему пользователю GCP.",
    "To deploy the Dynatrace GCP function in bash": "Для развёртывания функции Dynatrace GCP в bash",
    "1. Restart the console and [initialize Cloud SDK﻿](https://dt-url.net/ac43q0f).": "1. Перезапустите консоль и [инициализируйте Cloud SDK﻿](https://dt-url.net/ac43q0f).",
    "2. Download and run the installation script below.": "2. Загрузите и запустите скрипт установки ниже.",
    "After deploying the integration, you can see metrics from monitored services. If you want to add services to monitoring, see [Expand monitoring](#expand) below.": "После развёртывания интеграции доступны метрики отслеживаемых сервисов. Чтобы добавить сервисы в мониторинг, см. раздел [Расширение мониторинга](#expand) ниже.",
    "## Verify installation": "## Проверка установки",
    "To check whether installation was successful": "Чтобы проверить успешность установки",
    "1. In your Google Cloud console, go to Cloud Functions and make sure that `dynatrace-gcp-monitor` is there.": "1. В консоли Google Cloud перейдите в Cloud Functions и убедитесь, что `dynatrace-gcp-monitor` присутствует.",
    "2. Select the newly deployed function and go to **Logs** to make sure there are no error messages.": "2. Выберите только что развёрнутую функцию и перейдите в раздел **Logs**, чтобы убедиться в отсутствии сообщений об ошибках.",
    "## Expand monitoring": "## Расширение мониторинга",
    "There are two ways to add services to Dynatrace monitoring when using a Google Cloud Function: via the service configuration file or using the GCP console. See below for instructions.": "Добавить сервисы в мониторинг Dynatrace при использовании Google Cloud Function можно двумя способами: через файл конфигурации сервиса или через консоль GCP. Инструкции приведены ниже.",
    "In the service configuration file": "В файле конфигурации сервиса",
    "In the Google Cloud console": "В консоли Google Cloud",
    "To add services in the service configuration file": "Чтобы добавить сервисы через файл конфигурации сервиса",
    "1. Download the `activation-config.yaml` service configuration file, making sure to replace `<VERSION>` with your function release version.": "1. Загрузите файл конфигурации сервиса `activation-config.yaml`, заменив `<VERSION>` на версию релиза вашей функции.",
    "2. Edit the `activation.metrics.services` section in `activation-config.yaml` by uncommenting the services you want to monitor.": "2. Отредактируйте раздел `activation.metrics.services` в файле `activation-config.yaml`, раскомментировав сервисы, которые нужно отслеживать.",
    "3. Download and run the `dynatrace-gcp-monitor` installation script in the same folder where you downloaded `activation-config.yaml`.": "3. Загрузите и запустите скрипт установки `dynatrace-gcp-monitor` в той же папке, куда был загружен файл `activation-config.yaml`.",
    "To add services in the Google Cloud console": "Чтобы добавить сервисы через консоль Google Cloud",
    "1. Go to **Cloud Functions**": "1. Перейдите в **Cloud Functions**",
    "2. Select **dynatrace-gcp-monitor**": "2. Выберите **dynatrace-gcp-monitor**",
    "3. Select **Edit**": "3. Выберите **Edit**",
    "4. Under **Variables, networking and advanced settings**, select **Environment variables**": "4. В разделе **Variables, networking and advanced settings** выберите **Environment variables**",
    "5. Select **Runtime environment variables**": "5. Выберите **Runtime environment variables**",
    "6. Modify the value for **GCP services** to include the services or configurations you want to monitor (for example, `cloud_function`, `gce_instance/agent`).": "6. Измените значение параметра **GCP services**, добавив нужные сервисы или конфигурации (например, `cloud_function`, `gce_instance/agent`).",
    "7. Select **Next**, then select **Deploy**": "7. Выберите **Next**, затем **Deploy**",
    "## Related topics": "## Связанные темы",
    '* [Set up Dynatrace on Google Cloud](/managed/ingest-from/google-cloud-platform "Monitor Google Cloud with Dynatrace.")': '* [Настройка Dynatrace в Google Cloud](/managed/ingest-from/google-cloud-platform "Мониторинг Google Cloud с помощью Dynatrace.")',
}

PASS = set()

build_one(REL, FNAME, TRANS, PASS)
qa_one(REL, FNAME)
