# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/google-cloud-platform/gcp-integrations/gcp-functions"
FILE = "opentelemetry-on-gcf-go.md"

TRANS = {
    "title: Integrate on Google Cloud Functions GoLang": "title: Интеграция OpenTelemetry на Google Cloud Functions Go",
    "# Integrate on Google Cloud Functions GoLang": "# Интеграция OpenTelemetry на Google Cloud Functions Go",
    "* How-to guide": "* Практическое руководство",
    "* 8-min read": "* Чтение: 8 мин",
    "* Updated on Jun 16, 2023": "* Обновлено 16 июня 2023 г.",
    "The [`dynatrace-oss/opentelemetry-exporter-go`ï»¿](https://dt-url.net/jq034sr) package provides an API for tracing Go code on Google Cloud Functions. This package provides a way to instrument your code with Dynatrace-enhanced OpenTelemetry traces.": "Пакет [`dynatrace-oss/opentelemetry-exporter-go`](https://dt-url.net/jq034sr) предоставляет API для трассировки кода Go на Google Cloud Functions и позволяет инструментировать код с помощью улучшенных трассировок OpenTelemetry от Dynatrace.",
    "We recommend using this package. As an alternative, you can instrument your Google Cloud Functions with plain OpenTelemetry, see [Trace Google Cloud Functions in Go with OpenTelemetry](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/otel-gcf-go \"Learn how to instrument Google Cloud Functions in Go with OpenTelemetry and export the traces to Dynatrace.\").": "Рекомендуем использовать этот пакет. В качестве альтернативы можно инструментировать Google Cloud Functions с помощью стандартного OpenTelemetry, см. [Трассировка Google Cloud Functions в Go с OpenTelemetry](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/otel-gcf-go \"Узнайте, как инструментировать Google Cloud Functions в Go с помощью OpenTelemetry и экспортировать трассировки в Dynatrace.\").",
    "## Prerequisites": "## Предварительные требования",
    "Ensure that you have followed the **initial configuration** steps described in [Set up OpenTelemetry monitoring for Google Cloud Functions](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf \"Monitor Google Cloud Functions with OpenTelemetry and Dynatrace.\") before using the packages below.": "Перед использованием приведённых ниже пакетов убедитесь, что выполнены шаги **начальной настройки** из раздела [Настройка мониторинга OpenTelemetry для Google Cloud Functions](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf \"Мониторинг Google Cloud Functions с помощью OpenTelemetry и Dynatrace.\").",
    "* Dynatrace version 1.222+": "* Dynatrace версии 1.222+",
    "* Cloud Functions Go Runtime 1.16+": "* Cloud Functions Go Runtime 1.16+",
    "* Cloud Functions product version:": "* Версия продукта Cloud Functions:",
    "+ 1st gen": "+ 1-го поколения",
    "+ dynatrace-oss/opentelemetry-exporter-go version 1.267+ 2nd gen": "+ dynatrace-oss/opentelemetry-exporter-go версии 1.267+ 2-го поколения",
    "## Installation": "## Установка",
    "Run the following command in the root directory of your Google Cloud Function project to install the latest version of the [`dynatrace-oss/opentelemetry-exporter-go`ï»¿](https://dt-url.net/jq034sr) package from GitHub.": "Выполните следующую команду в корневом каталоге вашего проекта Google Cloud Function для установки последней версии пакета [`dynatrace-oss/opentelemetry-exporter-go`](https://dt-url.net/jq034sr) с GitHub.",
    "Note that this package by itself is not enough to get Dynatrace-enhanced traces. Further initialization code and dependencies need to be added, as described below.": "Обратите внимание: одного этого пакета недостаточно для получения улучшенных трассировок Dynatrace. Необходимо добавить дополнительный код инициализации и зависимости, как описано ниже.",
    "## Usage": "## Использование",
    "Follow the steps below to instrument your Google Cloud Functions.": "Следуйте приведённым ниже шагам для инструментирования Google Cloud Functions.",
    "[![Step 1](https://dt-cdn.net/images/step-1-086e22066c.svg \"Step 1\")": "[![Шаг 1](https://dt-cdn.net/images/step-1-086e22066c.svg \"Шаг 1\")",
    "**Install dependencies**](#dependencies)[![Step 2](https://dt-cdn.net/images/step-2-1a1384627e.svg \"Step 2\")": "**Установка зависимостей**](#dependencies)[![Шаг 2](https://dt-cdn.net/images/step-2-1a1384627e.svg \"Шаг 2\")",
    "**Set up OpenTelemetry**](#otel-setup)[![Step 3](https://dt-cdn.net/images/step-3-350cf6c19a.svg \"Step 3\")": "**Настройка OpenTelemetry**](#otel-setup)[![Шаг 3](https://dt-cdn.net/images/step-3-350cf6c19a.svg \"Шаг 3\")",
    "**Instrument the function entry point**](#instrument-handler)[![Step 4](https://dt-cdn.net/images/step-4-3f89d67d41.svg \"Step 4\")": "**Инструментирование точки входа функции**](#instrument-handler)[![Шаг 4](https://dt-cdn.net/images/step-4-3f89d67d41.svg \"Шаг 4\")",
    "**Instrument outgoing requests**](#outgoing-instrument)": "**Инструментирование исходящих запросов**](#outgoing-instrument)",
    "### Step 1 Install dependencies": "### Шаг 1 Установка зависимостей",
    "Use the following commands to add the required OpenTelemetry and Google Cloud dependencies to your function. If your project already contains any of these dependencies, you might want to skip the corresponding `go get` call, otherwise, it will upgrade you to the latest version of the dependency.": "Используйте следующие команды для добавления необходимых зависимостей OpenTelemetry и Google Cloud в функцию. Если проект уже содержит какие-либо из этих зависимостей, соответствующий вызов `go get` можно пропустить, иначе он обновит зависимость до последней версии.",
    "### Step 2 Set up OpenTelemetry": "### Шаг 2 Настройка OpenTelemetry",
    "Some initialization code is required to set up OpenTelemetry before you can start instrumenting your Cloud Function. The following code snippet will initialize the required `DtTracerProvider` and `DtTextMapPropagator` instances, and register them via the OpenTelemetry API.": "Перед инструментированием Cloud Function необходимо выполнить некоторый код инициализации для настройки OpenTelemetry. Следующий фрагмент кода инициализирует необходимые экземпляры `DtTracerProvider` и `DtTextMapPropagator` и зарегистрирует их через OpenTelemetry API.",
    "### Step 3 Instrument the function entry point": "### Шаг 3 Инструментирование точки входа функции",
    "There are several trigger types for Google Cloud Functions. See below how to instrument Cloud Functions with [HTTP triggersï»¿](https://dt-url.net/al234i0) and [Pub/Sub triggersï»¿](https://dt-url.net/oq434w7).": "Для Google Cloud Functions существует несколько типов триггеров. Ниже описано, как инструментировать Cloud Functions с [триггерами HTTP](https://dt-url.net/al234i0) и [триггерами Pub/Sub](https://dt-url.net/oq434w7).",
    "Instrument HTTP trigger": "Инструментирование триггера HTTP",
    "Instrument Pub/Sub trigger": "Инструментирование триггера Pub/Sub",
    "When your Cloud Function has an HTTP trigger, you can instrument it with the help of the [`otelhttp`ï»¿](https://dt-url.net/6c634nr) package. First, install the package:": "Если Cloud Function использует триггер HTTP, её можно инструментировать с помощью пакета [`otelhttp`](https://dt-url.net/6c634nr). Сначала установите пакет:",
    "For ease of use, you can create a wrapper function for your entry point. The following code samples contain several utility functions which will help you set the required attributes on your spans.": "Для удобства можно создать функцию-обёртку для точки входа. Следующие примеры кода содержат несколько вспомогательных функций, которые помогут задать необходимые атрибуты на спанах.",
    "To put everything together, instrument your Google Cloud Function entry point as follows:": "Объединяя всё вместе, инструментируйте точку входа Google Cloud Function следующим образом:",
    "When using any version before [version 0.37.0 of the `otelhttp` packageï»¿](https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.12.0), it is required to explicitly call `w.WriteHeader(...)` or `w.Write(...)` in your HTTP function handler. Other methods which write content to the `ResponseWriter`, such as `fmt.Fprint(w, \"OK\")`, are also valid. Your function handler should then look something like this:": "При использовании любой версии до [версии 0.37.0 пакета `otelhttp`](https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.12.0) необходимо явно вызывать `w.WriteHeader(...)` или `w.Write(...)` в обработчике HTTP-функции. Другие методы записи в `ResponseWriter`, например `fmt.Fprint(w, \"OK\")`, также допустимы. Обработчик функции должен выглядеть примерно так:",
    "OpenTelemetry currently doesn't provide out-of-the-box instrumentation for Pub/Sub, so instrumenting a Pub/Sub triggered Cloud Function requires some manual configuration.": "OpenTelemetry пока не предоставляет готового инструментирования для Pub/Sub, поэтому инструментирование Cloud Function с триггером Pub/Sub требует некоторой ручной настройки.",
    "Then, instrument your Google Cloud Function entry point as follows:": "Затем инструментируйте точку входа Google Cloud Function следующим образом:",
    "The code samples above apply to [CloudEvent functionsï»¿](https://dt-url.net/fm834cy). The code would require minor adaptations, such as removing the `MessagePublishedData` object and unmarshalling the event data directly to a `PubSubMessage` object, when using [*background functions*ï»¿](https://dt-url.net/83a34xp).": "Приведённые примеры кода применяются к [функциям CloudEvent](https://dt-url.net/fm834cy). При использовании [*фоновых функций*](https://dt-url.net/83a34xp) потребуются небольшие адаптации: удаление объекта `MessagePublishedData` и десериализация данных события напрямую в объект `PubSubMessage`.",
    "For instructions on how to deploy your Cloud Function, see [Create and deploy a Cloud Function by using the Google Cloud CLIï»¿](https://dt-url.net/l2c342b).": "Инструкции по развёртыванию Cloud Function см. в разделе [Создание и развёртывание Cloud Function с помощью Google Cloud CLI](https://dt-url.net/l2c342b).",
    "### Step 4 Instrument outgoing requests": "### Шаг 4 Инструментирование исходящих запросов",
    "If you have any outgoing requests in your Cloud Function, you can instrument them as well to achieve full end-to-end tracing. Your requests can be instrumented by using instrumentation libraries provided by OpenTelemetry.": "Если Cloud Function содержит исходящие запросы, их также можно инструментировать для достижения полной сквозной трассировки. Для инструментирования запросов используйте библиотеки инструментирования, предоставляемые OpenTelemetry.",
    "Instrumenting outgoing requests works equivalently with the Dynatrace-enhanced tracing package and plain OpenTelemetry. For instructions on how to instrument outgoing requests, see [Trace Google Cloud Functions in Go with OpenTelemetry](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/otel-gcf-go#outgoing-instrument \"Learn how to instrument Google Cloud Functions in Go with OpenTelemetry and export the traces to Dynatrace.\").": "Инструментирование исходящих запросов одинаково работает как с пакетом улучшенной трассировки Dynatrace, так и со стандартным OpenTelemetry. Инструкции по инструментированию исходящих запросов см. в разделе [Трассировка Google Cloud Functions в Go с OpenTelemetry](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/otel-gcf-go#outgoing-instrument \"Узнайте, как инструментировать Google Cloud Functions в Go с помощью OpenTelemetry и экспортировать трассировки в Dynatrace.\").",
    "## Span flush": "## Сброс спанов",
    "In the code snippets above, `ForceFlush` is explicitly called after every function invocation to ensure that spans are exported properly.": "В приведённых выше фрагментах кода `ForceFlush` явно вызывается после каждого вызова функции для обеспечения корректного экспорта спанов.",
    "Because flushing spans becomes part of the function's execution logic, it results in longer execution times. To avoid this, you can omit the call to `ForceFlush`. Spans will still be periodically exported in the background.": "Поскольку сброс спанов становится частью логики выполнения функции, это увеличивает время выполнения. Чтобы избежать этого, можно пропустить вызов `ForceFlush`: спаны всё равно будут периодически экспортироваться в фоновом режиме.",
    "Because code running outside the function execution can be terminated at any time, it's discouraged by Google Cloud Functions.": "Поскольку код, выполняющийся за пределами выполнения функции, может быть завершён в любой момент, Google Cloud Functions не рекомендует такой подход.",
    "* Google Cloud Functions 1st gen": "* Google Cloud Functions 1-го поколения",
    "Background task execution after function invocation is not guaranteed without flushing spans and might result in span loss. In practice, samples have shown that not explicitly flushing spans usually still results in correctly exported spans.": "Выполнение фоновых задач после вызова функции без сброса спанов не гарантировано и может привести к потере спанов. На практике примеры показали, что отсутствие явного сброса спанов, как правило, всё равно приводит к их корректному экспорту.",
    "* Google Cloud Functions 2nd gen": "* Google Cloud Functions 2-го поколения",
    "Google Cloud Functions 2nd gen can handle multiple concurrent requests in a single function instance. The flush operation of one invocation can prolong the execution time of another function invocation.": "Google Cloud Functions 2-го поколения может обрабатывать несколько одновременных запросов в одном экземпляре функции. Операция сброса одного вызова может увеличить время выполнения другого вызова функции.",
    "Because function instances usually need to be kept idle for some time to handle multiple concurrent requests, you can disable the flushing of spans to improve performance. For details, see [Instance lifecycleï»¿](https://cloud.google.com/run/docs/container-contract#lifecycle-services).": "Поскольку экземпляры функций обычно должны некоторое время оставаться в режиме ожидания для обработки нескольких одновременных запросов, можно отключить сброс спанов для повышения производительности. Подробнее см. [Жизненный цикл экземпляра](https://cloud.google.com/run/docs/container-contract#lifecycle-services).",
    "Note that idle function instances are not guaranteed to be allocated CPU unless their [CPU allocationï»¿](https://cloud.google.com/run/docs/configuring/cpu-allocation) mode is set to `CPU always allocated`.": "Обратите внимание: простаивающим экземплярам функций не гарантировано выделение CPU, если их режим [выделения CPU](https://cloud.google.com/run/docs/configuring/cpu-allocation) не установлен в `CPU always allocated`.",
    "For details, see [Function execution timelineï»¿](https://cloud.google.com/functions/docs/concepts/execution-environment#execution-timeline).": "Подробнее см. [Временная шкала выполнения функции](https://cloud.google.com/functions/docs/concepts/execution-environment#execution-timeline).",
    "## Dynatrace overhead": "## Накладные расходы Dynatrace",
    "* Because span export and metadata fetch take some time during cold starts, they increase the duration of the function and subsequently increase costs.": "* Поскольку экспорт спанов и получение метаданных занимают некоторое время при холодных стартах, они увеличивают продолжительность выполнения функции и, следовательно, повышают затраты.",
    "* Pay attention to infrequently invoked functions (usually with cold starts), which might require more time for the TCP handshake during span export.": "* Обратите внимание на редко вызываемые функции (как правило, с холодными стартами): им может потребоваться больше времени для TCP-рукопожатия при экспорте спанов.",
    "* Any network problem between the exporter and Dynatrace backend might also lead to unexpectedly high overhead.": "* Любые сетевые проблемы между экспортером и бэкендом Dynatrace могут также привести к неожиданно высоким накладным расходам.",
    "## Related topics": "## Связанные темы",
    "* [Set up OpenTelemetry monitoring for Google Cloud Functions](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf \"Monitor Google Cloud Functions with OpenTelemetry and Dynatrace.\")": "* [Настройка мониторинга OpenTelemetry для Google Cloud Functions](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf \"Мониторинг Google Cloud Functions с помощью OpenTelemetry и Dynatrace.\")",
    "* [Trace Google Cloud Functions in Go with OpenTelemetry](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/otel-gcf-go \"Learn how to instrument Google Cloud Functions in Go with OpenTelemetry and export the traces to Dynatrace.\")": "* [Трассировка Google Cloud Functions в Go с OpenTelemetry](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/otel-gcf-go \"Узнайте, как инструментировать Google Cloud Functions в Go с помощью OpenTelemetry и экспортировать трассировки в Dynatrace.\")",
    "* [Set up Dynatrace on Google Cloud](/managed/ingest-from/google-cloud-platform \"Monitor Google Cloud with Dynatrace.\")": "* [Настройка Dynatrace на Google Cloud](/managed/ingest-from/google-cloud-platform \"Мониторинг Google Cloud с помощью Dynatrace.\")",
    "* [Google Cloud monitoringï»¿](https://www.dynatrace.com/technologies/google-cloud-monitoring/)": "* [Мониторинг Google Cloud](https://www.dynatrace.com/technologies/google-cloud-monitoring/)",
}

PASS = set()

build_one(REL, FILE, TRANS, PASS)
qa_one(REL, FILE)
