# -*- coding: utf-8 -*-
"""L4-IF.72 — ingest-from/extensions/develop-your-extensions/addon-for-vscode/commands.md"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/extensions/develop-your-extensions/addon-for-vscode"

TRANS = {
    "* Reference": "* Справочник",
    "* 11-min read": "* Чтение: 11 мин",
    "* Published Jun 16, 2025": "* Опубликовано 16 июня 2025 г.",
    "All major workflows automated by the **Dynatrace Extensions** add-on are exposed as VS Code commands and accessible from the editor's command palette. To open the command palette, press the F1 key, where you can find all available commands with the **Dynatrace extensions** prefix.": "Все основные рабочие процессы, автоматизированные дополнением **Dynatrace Extensions**, доступны как команды VS Code из палитры команд редактора. Чтобы открыть палитру команд, нажмите клавишу F1. Там находятся все доступные команды с префиксом **Dynatrace extensions**.",
    "## Command overview": "## Обзор команд",
    "| Command | Description |": "| Команда | Описание |",
    "| --- | --- |": "| --- | --- |",
    "| [Initialize workspace](#initialize-workspace) | Register and initialize your workspace. The first step to get started |": "| [Initialize workspace](#initialize-workspace) | Регистрация и инициализация рабочего пространства. Первый шаг для начала работы |",
    "| [Load schemas](#load-schemas) | Download schema files and setup manifest validation |": "| [Load schemas](#load-schemas) | Загрузка файлов схем и настройка проверки манифеста |",
    "| [Generate certificates](#generate-certificates) | Generate developer certificates for signing extensions |": "| [Generate certificates](#generate-certificates) | Генерация разработческих сертификатов для подписи расширений |",
    "| [Distribute certificate](#distribute-certificate) | Distribute your CA certificate to components that use it |": "| [Distribute certificate](#distribute-certificate) | Распространение корневого сертификата на компоненты, которые его используют |",
    "| [Build](#build) | Build your extension and create a signed package |": "| [Build](#build) | Сборка расширения и создание подписанного пакета |",
    "| [Upload](#upload) | Upload the latest extension package to your Dynatrace environment |": "| [Upload](#upload) | Загрузка последнего пакета расширения в окружение Dynatrace |",
    "| [Activate](#activate) | Activate a version of the current extension |": "| [Activate](#activate) | Активация версии текущего расширения |",
    "| [Create documentation](#create-documentation) | Generate a README.md file about the extension and its contents |": "| [Create documentation](#create-documentation) | Генерация файла README.md с описанием расширения и его содержимого |",
    "| [Create a dashboard](#create-a-dashboard) | Generate a landing page dashboard to bundle with your extension |": "| [Create a dashboard](#create-a-dashboard) | Генерация лендингового дашборда для включения в расширение |",
    "| [Create alert](#create-alert) | Generate metric events for alerting to bundle with your extension |": "| [Create alert](#create-alert) | Генерация событий метрик для оповещений для включения в расширение |",
    "| [Convert JMX](#convert-jmx) | Convert a Java management extensions (JMX) extension to the 2.0 framework |": "| [Convert JMX](#convert-jmx) | Конвертация расширения Java Management Extensions (JMX) в платформу 2.0 |",
    "## Initialize workspace": "## Initialize workspace",
    "This command initializes a new or existing workspace for Extension 2.0 development and registers it with our VS Code add-on. As part of initialization, a starting folder structure and some template extension files are created to help any project start correctly.": "Эта команда инициализирует новое или существующее рабочее пространство для разработки Extension 2.0 и регистрирует его в дополнении VS Code. В процессе инициализации создаётся начальная структура папок и шаблонные файлы расширения, чтобы любой проект начинался корректно.",
    'You can explore this command in detail by visiting our [Getting started guide](/managed/ingest-from/extensions/develop-your-extensions/addon-for-vscode/getting-started "Set up your Visual Studio Code editor and get your first extension built and uploaded to Dynatrace in 5 minutes.").': 'Подробнее об этой команде см. в [руководстве по началу работы](/managed/ingest-from/extensions/develop-your-extensions/addon-for-vscode/getting-started "Настройте редактор Visual Studio Code и соберите и загрузите первое расширение в Dynatrace за 5 минут.").',
    "### Command prerequisites": "### Предварительные требования",
    "* A workspace or folder needs to be opened in the VS Code window.": "* В окне VS Code должно быть открыто рабочее пространство или папка.",
    "* You need to be connected to a Dynatrace environment.": "* Требуется подключение к окружению Dynatrace.",
    "### Workflow steps": "### Шаги рабочего процесса",
    "1. Provisions internal storage for this project.": "1. Выделяет внутреннее хранилище для проекта.",
    "2. Invoke the workflow from [Load schemas](#load-schemas). You can skip this step if you have already registered your workspace with Dynatrace Extensions.": "2. Запускает рабочий процесс из [Load schemas](#load-schemas). Этот шаг можно пропустить, если рабочее пространство уже зарегистрировано в Dynatrace Extensions.",
    "3. Associate certificates with the workspace. Allow choice:": "3. Связывает сертификаты с рабочим пространством. Доступны варианты:",
    "* **Use existing**: Checks settings for developer certificate and key.": "* **Use existing**: проверяет настройки разработческого сертификата и ключа.",
    "* **Generate new ones**: Invokes workflow from [Generate certificates](#generate-certificates).": "* **Generate new ones**: запускает рабочий процесс из [Generate certificates](#generate-certificates).",
    "4. Register the workspace with Dynatrace Extensions.": "4. Регистрирует рабочее пространство в Dynatrace Extensions.",
    "5. Create a project folder and files based on the chosen template.": "5. Создаёт папку проекта и файлы на основе выбранного шаблона.",
    "### Project templates": "### Шаблоны проектов",
    "#### Extension 2.0": "#### Extension 2.0",
    "It's the default choice. Whether you already have all the contents and want to register the workspace with our add-on or start a new extension from scratch. It'll generate the extension folder and a manifest with the minimum mandatory details required for any extension.": "Это выбор по умолчанию: если все содержимое уже есть и нужно зарегистрировать рабочее пространство в дополнении, или если начинается новое расширение с нуля. Создаётся папка расширения и манифест с минимально обязательными данными для любого расширения.",
    "#### Python extension 2.0": "#### Python extension 2.0",
    "This option creates a new extension that uses the Python data source. As part of the setup, we'll also download and install the [Dynatrace Extensions SDK](https://github.com/dynatrace-extensions/dt-extensions-python-sdk) module for Python.": "Этот вариант создаёт новое расширение, использующее источник данных Python. В процессе настройки также загружается и устанавливается модуль [Dynatrace Extensions SDK](https://github.com/dynatrace-extensions/dt-extensions-python-sdk) для Python.",
    "#### JMX 1.0 conversion": "#### JMX 1.0 conversion",
    "The JMX data source is now available with Extensions, meaning it's time to convert your JMX extensions from the 1.0 framework. This type of project will guide you to provide a 1.0 JMX Extension (either from a local file or your tenant), and it will convert it to the new framework and create your manifest.": "Источник данных JMX теперь доступен в Extensions, и пришло время конвертировать расширения JMX из платформы 1.0. Этот тип проекта предложит указать расширение JMX 1.0 (из локального файла или тенанта) и конвертирует его в новую платформу с созданием манифеста.",
    "#### Existing 2.0 extension": "#### Existing 2.0 extension",
    "Need to edit an already deployed extension? Are you curious about what the content of a Dynatrace-built extension looks like? This option downloads an extension 2.0 package from your tenant and unpacks it into your workspace.": "Нужно отредактировать уже развёрнутое расширение или посмотреть, как выглядит содержимое расширения, собранного Dynatrace? Этот вариант загружает пакет расширения 2.0 из тенанта и распаковывает его в рабочее пространство.",
    "## Load schemas": "## Load schemas",
    "This command downloads schema files of a specific version from your connected Dynatrace environment and sets up validation for the extension manifest. If your project already has an extension manifest, this is updated with the chosen version.": "Эта команда загружает файлы схем определённой версии из подключённого окружения Dynatrace и настраивает проверку манифеста расширения. Если в проекте уже есть манифест расширения, он обновляется до выбранной версии.",
    "1. Your Dynatrace environment is queried for the list of available schema versions. And you'll be prompted to select which version to use.": "1. Запрашивается список доступных версий схем в окружении Dynatrace, затем предлагается выбрать нужную версию.",
    "2. The files associated with the selected schema version are downloaded and stored in the global Visual Studio Code storage.": "2. Файлы выбранной версии схемы загружаются и сохраняются в глобальном хранилище Visual Studio Code.",
    "* If you have downloaded the files before, you'll be prompted and can skip this step.": "* Если файлы уже загружались ранее, появится запрос с возможностью пропустить этот шаг.",
    "3. Workspace settings are updated to enable validation of your extension manifest with the selected schema.": "3. Настройки рабочего пространства обновляются для включения проверки манифеста расширения по выбранной схеме.",
    "* If a manifest file is present in the workspace, it will be updated with the selected minimum version.": "* Если в рабочем пространстве есть файл манифеста, он будет обновлён до выбранной минимальной версии.",
    "## Generate certificates": "## Generate certificates",
    "This command generates all the credentials needed for signing and validating Extensions.": "Эта команда генерирует все учётные данные, необходимые для подписи и проверки Extensions.",
    "* A workspace or folder needs to be opened in the VS Code window.": "* В окне VS Code должно быть открыто рабочее пространство или папка.",
    "1. An RSA key pair is generated to generate your CA certificate.": "1. Генерируется пара ключей RSA для создания корневого сертификата.",
    "2. Another RSA key pair is generated, then used to generate your developer certificate, adding your CA certificate as the issuing authority on this credential.": "2. Генерируется ещё одна пара ключей RSA, которая используется для создания разработческого сертификата; корневой сертификат добавляется как удостоверяющий центр для этих учётных данных.",
    "3. The developer certificate is generated from the RSA key pair, and the CA certificate is added as the issuing authority on this certificate.": "3. Разработческий сертификат создаётся из пары ключей RSA, а корневой сертификат добавляется как удостоверяющий центр для этого сертификата.",
    "* **Note:** You can customize all details used for generating these certificates through the settings.": "* **Примечание:** все параметры, используемые при генерации сертификатов, можно настроить в настройках.",
    '4. All intermediary files are stored in the VS Code workspace storage, and the [credential settings](/managed/ingest-from/extensions/develop-your-extensions/addon-for-vscode/settings#credentials "Details of settings available to configure Dynatrace Extensions") for this workspace are updated with the paths to the generated files. And this is done in the `./vscode/settings.json` file.': '4. Все промежуточные файлы сохраняются в хранилище рабочего пространства VS Code, а [настройки учётных данных](/managed/ingest-from/extensions/develop-your-extensions/addon-for-vscode/settings#credentials "Подробности настроек для конфигурации Dynatrace Extensions") для этого рабочего пространства обновляются путями к сгенерированным файлам. Это выполняется в файле `./vscode/settings.json`.',
    "5. Invoke workflow from [Distribute certificate](#distribute-certificate)": "5. Запускается рабочий процесс из [Distribute certificate](#distribute-certificate).",
    "## Distribute certificate": "## Distribute certificate",
    "This command uploads the workspace's CA certificate to the Dynatrace Credentials Vault. Additionally, if it detects locally installed OneAgents or ActiveGates, it also uploads this certificate to them.": "Эта команда загружает корневой сертификат рабочего пространства в хранилище учётных данных Dynatrace. Если дополнительно обнаруживаются локально установленные OneAgent или ActiveGate, сертификат загружается и в них.",
    "* The `dynatraceExtensions.rootOrCaCertificate` setting needs to be set either globally or for the workspace.": "* Настройка `dynatraceExtensions.rootOrCaCertificate` должна быть задана глобально или для рабочего пространства.",
    "1. The add-on checks whether a Dynatrace Credentials Vault entry ID is already associated with this workspace and prompts whether the entry should be overwritten.": "1. Дополнение проверяет, связан ли с рабочим пространством идентификатор записи в хранилище учётных данных Dynatrace, и запрашивает, следует ли перезаписать запись.",
    "* If overwrite is selected, the entry is updated with the new file.": "* При выборе перезаписи запись обновляется новым файлом.",
    "* Otherwise, the workflow continues with creating a new Credential Vault entry.": "* В противном случае рабочий процесс продолжается с созданием новой записи в хранилище учётных данных.",
    "2. You are prompted to provide a name for this credential and an optional description. Then the file is uploaded with these details.": "2. Предлагается указать имя учётных данных и необязательное описание, после чего файл загружается с этими данными.",
    "3. Local OneAgent and ActiveGate paths are checked for existence, and the flow prompts whether the certificate should also be uploaded to these locations.": "3. Проверяется наличие локальных путей OneAgent и ActiveGate, и предлагается также загрузить сертификат в эти места.",
    "* On Windows:": "* В Windows:",
    "+ OneAgent: `%PROGRAMDATA%\\dynatrace\\oneagent\\agent\\config\\certificates`": "+ OneAgent: `%PROGRAMDATA%\\dynatrace\\oneagent\\agent\\config\\certificates`",
    "+ ActiveGate: `%PROGRAMDATA%\\dynatrace\\remotepluginmodule\\agent\\conf\\certificates`": "+ ActiveGate: `%PROGRAMDATA%\\dynatrace\\remotepluginmodule\\agent\\conf\\certificates`",
    "* On Linux:": "* В Linux:",
    "+ OneAgent: `/var/lib/dynatrace/oneagent/agent/config/certificates`": "+ OneAgent: `/var/lib/dynatrace/oneagent/agent/config/certificates`",
    "+ ActiveGate: `<CONFIG>/remotepluginmodule/agent/conf/certificates/`": "+ ActiveGate: `<CONFIG>/remotepluginmodule/agent/conf/certificates/`",
    "This step requires VS Code to run with administrator-level permissions. For example, for Windows, use **Run As Administrator**.": "Этот шаг требует запуска VS Code с правами администратора. Например, в Windows используйте **Run As Administrator**.",
    "## Build": "## Build",
    "This command builds your extension and bundles it into a signed ZIP file archive, then places it in the `dist` folder of the workspace.": "Эта команда собирает расширение и упаковывает его в подписанный ZIP-архив, который помещается в папку `dist` рабочего пространства.",
    "* A registered workspace needs to be open in the VS Code window.": "* В окне VS Code должно быть открыто зарегистрированное рабочее пространство.",
    "* Developer certificates need to be associated with the workspace.": "* С рабочим пространством должны быть связаны разработческие сертификаты.",
    "* No error/problems need to be detected with the extension manifest.": "* В манифесте расширения не должно быть ошибок.",
    "1. The extension version is picked up from the manifest. If you're connected to a Dynatrace environment, the version is checked for conflicts and automatically incremented if needed.": "1. Версия расширения берётся из манифеста. При подключении к окружению Dynatrace версия проверяется на конфликты и при необходимости автоматически увеличивается.",
    "2. The extension manifest and assets are bundled into a ZIP file archive signed using your developer credentials. The resulting signature and the archive are added to a final ZIP file representing the extension package.": "2. Манифест расширения и ресурсы упаковываются в ZIP-архив, подписанный разработческими учётными данными. Полученная подпись и архив добавляются в итоговый ZIP-файл, представляющий пакет расширения.",
    "3. If you're connected to a Dynatrace environment, the package is validated against it. Any validation errors are communicated in an Output Channel (within your editor window), and the workflow terminates. Only valid packages are moved to your workspace's `dist` folder.": "3. При подключении к окружению Dynatrace пакет проверяется по нему. Ошибки проверки отображаются в Output Channel (в окне редактора), после чего рабочий процесс завершается. В папку `dist` рабочего пространства перемещаются только допустимые пакеты.",
    "4. Invoke workflow from [Upload](#upload).": "4. Запускается рабочий процесс из [Upload](#upload).",
    "## Upload": "## Upload",
    "This command uploads the most recent package from your workspace's `dist` folder to your connected environment.": "Эта команда загружает последний пакет из папки `dist` рабочего пространства в подключённое окружение.",
    "* A ZIP file archive needs to be in the workspace's `dist` folder.": "* В папке `dist` рабочего пространства должен находиться ZIP-архив.",
    "1. We check if an upload is possible by querying the number of versions already deployed for this extension.": "1. Проверяется возможность загрузки путём запроса количества уже развёрнутых версий расширения.",
    "* If too many versions exist, you'll be prompted to remove the oldest one.": "* Если версий слишком много, предлагается удалить самую старую.",
    "* The add-on attempts to remove the oldest version; however, if this fails (for example, monitoring configurations may be linked to it), you'll be prompted to choose a different version to remove.": "* Дополнение пытается удалить самую старую версию; если это не удаётся (например, с ней могут быть связаны конфигурации мониторинга), предлагается выбрать другую версию для удаления.",
    "2. When it's possible, the extension is uploaded.": "2. Если загрузка возможна, расширение загружается.",
    "3. Invoke workflow from [Activate](#activate) to activate this version.": "3. Запускается рабочий процесс из [Activate](#activate) для активации этой версии.",
    "## Activate": "## Activate",
    "This command activates a version of your workspace's extension.": "Эта команда активирует версию расширения рабочего пространства.",
    "1. The extension name is read from the manifest in your workspace.": "1. Имя расширения считывается из манифеста рабочего пространства.",
    "2. Your Dynatrace environment is queried for the available versions of the extension, and you'll be prompted to choose which one to activate.": "2. В окружении Dynatrace запрашиваются доступные версии расширения, и предлагается выбрать, какую из них активировать.",
    "* This step is skipped when the command is invoked from another workflow. For example, [Upload](#upload)": "* Этот шаг пропускается, если команда вызвана из другого рабочего процесса, например из [Upload](#upload).",
    "3. The chosen version is activated in your Dynatrace environment.": "3. Выбранная версия активируется в окружении Dynatrace.",
    "## Create documentation": "## Create documentation",
    "This command automatically generates rich documentation in a `README.md` file by analyzing the extension package and its contents.": "Эта команда автоматически генерирует подробную документацию в файле `README.md`, анализируя пакет расширения и его содержимое.",
    "1. The command reads through the extension manifest, extracting all generic topology entities.": "1. Команда просматривает манифест расширения и извлекает все универсальные топологические сущности.",
    "2. Next, metrics are extracted from the manifest.": "2. Затем из манифеста извлекаются метрики.",
    "3. Next, dashboards are extracted from the manifest.": "3. Затем из манифеста извлекаются дашборды.",
    "4. After that, alerts are processed into human-readable summaries.": "4. После этого оповещения преобразуются в понятные сводки.",
    "5. Metrics are mapped to feature sets and linked to the defined entities.": "5. Метрики сопоставляются с наборами функций и связываются с определёнными сущностями.",
    "6. The readme file is created, with missing information skipped as needed.": "6. Создаётся файл readme; при необходимости отсутствующие сведения пропускаются.",
    "## Create a dashboard": "## Create a dashboard",
    "This command reads through the extension manifest and generates an overview dashboard which serves as a landing page for the extension.": "Эта команда просматривает манифест расширения и создаёт обзорный дашборд, служащий лендинговой страницей расширения.",
    '* The extension manifest needs to contain at least a [topology definition](/managed/ingest-from/extensions/develop-your-extensions/data-sources/wmi-extensions/wmi-tutorial/wmi-tutorial-04 "Learn about WMI extensions in the Extensions framework.").': '* Манифест расширения должен содержать как минимум [определение топологии](/managed/ingest-from/extensions/develop-your-extensions/data-sources/wmi-extensions/wmi-tutorial/wmi-tutorial-04 "Узнайте о расширениях WMI в платформе Extensions.").',
    "1. The command extracts the generic entity types defined in your manifest and any metrics associated with them. The first one or two metrics are taken for each entity type.": "1. Команда извлекает универсальные типы сущностей, определённые в манифесте, и все связанные с ними метрики. Для каждого типа сущностей берётся одна или две первые метрики.",
    "2. Your dashboard is created from a template containing the following:": "2. Дашборд создаётся из шаблона, который содержит следующее:",
    "* Single value tiles which show the count of distinct monitored entities.": "* Плитки с одним значением, показывающие количество уникальных отслеживаемых сущностей.",
    "* A list of markdown links so that each entity has a quick entry point to its unified analysis screen.": "* Список ссылок в формате markdown, предоставляющих быстрый переход к экрану единого анализа каждой сущности.",
    "* Tables for each entity type, alongside graph charts based on associated metrics.": "* Таблицы для каждого типа сущностей и графики на основе связанных метрик.",
    "3. Your dashboard is saved in the `./extension/dashboards/overview_dashboard.json` file, and the extension manifest is edited to include the reference to this asset.": "3. Дашборд сохраняется в файл `./extension/dashboards/overview_dashboard.json`, а манифест расширения обновляется для включения ссылки на этот ресурс.",
    "4. The workflow finishes with the prompt to upload this dashboard to your Dynatrace environment.": "4. Рабочий процесс завершается запросом о загрузке дашборда в окружение Dynatrace.",
    "Your dashboard will automatically be uploaded as part of the extension deployment. This final step is offered if you want an early preview of the asset before your extension deployment.": "Дашборд будет автоматически загружен в процессе развёртывания расширения. Этот последний шаг предлагается, если нужен предварительный просмотр ресурса до развёртывания расширения.",
    "## Create alert": "## Create alert",
    'This command creates a [metric event](/managed/dynatrace-intelligence/anomaly-detection/metric-events "Learn about metric events in Dynatrace") based on metrics defined in your extension\'s manifest.': 'Эта команда создаёт [событие метрики](/managed/dynatrace-intelligence/anomaly-detection/metric-events "Узнайте о событиях метрик в Dynatrace") на основе метрик, определённых в манифесте расширения.',
    "* The extension manifest needs to contain metrics metadata.": "* Манифест расширения должен содержать метаданные метрик.",
    "1. The command parses your extension manifest and presents a selection box with all available metrics. Select one to continue.": "1. Команда разбирает манифест расширения и отображает список всех доступных метрик. Выберите одну для продолжения.",
    "2. You are then prompted for a title for this alert.": "2. Затем предлагается ввести заголовок для оповещения.",
    "3. You need to choose whether your threshold breach happens when the metric goes **above** or **below** a given level.": "3. Нужно выбрать, срабатывает ли порог, когда метрика превышает (**above**) или опускается ниже (**below**) заданного уровня.",
    "4. Finally, provide the actual value the alert threshold relates to.": "4. Наконец, укажите фактическое значение порога оповещения.",
    "5. The command completes by writing your alert JSON file in the `./extension/alerts` folder and updating your extension manifest to include the newly generated alert.": "5. Команда завершается записью JSON-файла оповещения в папку `./extension/alerts` и обновлением манифеста расширения для включения созданного оповещения.",
    "## Convert JMX": "## Convert JMX",
    "This command converts an existing JMX extension to Extension 2.0.": "Эта команда конвертирует существующее расширение JMX в Extension 2.0.",
    "1. You're prompted on how the JMX extension should be loaded in:": "1. Предлагается выбрать способ загрузки расширения JMX:",
    "* **Locally** - browse your filesystem and select a JSON or ZIP file containing the JMX extension.": "* **Locally**: перейдите в файловой системе и выберите JSON- или ZIP-файл, содержащий расширение JMX.",
    "* **Remotely** - browse JMX extensions available on your connected tenant.": "* **Remotely**: просмотрите расширения JMX, доступные на подключённом тенанте.",
    "2. You're prompted to select a process technology if one can't be detected automatically.": "2. Если технология процесса не определяется автоматически, предлагается выбрать её вручную.",
    "3. You're asked whether to include the data on your host's details page.": "3. Запрашивается, включать ли данные на странице сведений о хосте.",
    "4. The workflow processes the JMX extension JSON file and converts it to an equivalent extension 2.0 manifest.": "4. Рабочий процесс обрабатывает JSON-файл расширения JMX и конвертирует его в эквивалентный манифест расширения 2.0.",
    "5. The workflow saves the generated manifest at `extension/extension.yaml` or prompts you for a save destination if this folder doesn't exist in your workspace.": "5. Рабочий процесс сохраняет сгенерированный манифест в `extension/extension.yaml` или запрашивает место сохранения, если эта папка отсутствует в рабочем пространстве.",
    'You can explore this workflow as part of our [JMX 1.0 Conversion guide](/managed/ingest-from/extensions/develop-your-extensions/addon-for-vscode/guides/jmx-conversion "Migrate JMX Extensions to the Extensions Framework.").': 'Ознакомьтесь с этим рабочим процессом подробнее в [руководстве по конвертации JMX 1.0](/managed/ingest-from/extensions/develop-your-extensions/addon-for-vscode/guides/jmx-conversion "Миграция расширений JMX в платформу Extensions.").',
}

PASS = {
    "title: Commands reference",
    "# Commands reference",
}

if __name__ == "__main__":
    build_one(REL, "commands.md", TRANS, PASS)
    qa_one(REL, "commands.md")
