# -*- coding: utf-8 -*-
"""Builder for install-zdc.md (L4-IF.71 canon)."""

import sys, os

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation"
FN = "install-zdc.md"

# Keys: EN text without leading indent, exactly as norm() sees it after _demoji().
# EN source has ï»¿ BOM-like scraping artifact; engine strips mojibake, so write clean keys.

TRANS = {
    # --- frontmatter ---
    "title: Install the zDC subsystem": "title: Установка подсистемы zDC",
    # --- h1 (appears twice) ---
    "# Install the zDC subsystem": "# Установка подсистемы zDC",
    # --- metadata ---
    "* 18-min read": "* Чтение: 18 мин",
    "* Updated on Feb 03, 2026": "* Обновлено 3 февраля 2026 г.",
    # --- intro para 1 ---
    "The z/OS Data Collection (zDC) subsystem interacts with the CICS, IMS, and z/OS Java modules via shared memory object (SMO) on a LPAR. The zDC subsystem maintains this SMO, and the modules write their monitoring data to it.": "Подсистема z/OS Data Collection (zDC) взаимодействует с кодовыми модулями CICS, IMS и z/OS Java через объект общей памяти (SMO) на LPAR. Подсистема zDC поддерживает этот SMO, а модули записывают в него данные мониторинга.",
    # --- intro para 2 (ï»¿ in USS link text — norm() strips it, key must have full markdown link) ---
    "The zLocal (`libdtzagent.so`), hosted in the z/OS [Unix System Services](https://www.ibm.com/docs/en/zos/2.5.0?topic=zos-unix-system-services) (USS) environment, runs as part of the zDC. It manages the TCP/IP socket connection to the zRemote module, reads monitoring data from SMO, and transfers these data to the zRemote.": "Модуль zLocal (`libdtzagent.so`), размещённый в среде z/OS [Unix System Services](https://www.ibm.com/docs/en/zos/2.5.0?topic=zos-unix-system-services) (USS), работает в составе zDC. Он управляет TCP/IP-сокетным соединением с модулем zRemote, считывает данные мониторинга из SMO и передаёт их в zRemote.",
    # --- intro para 3 ---
    "The bootstrapper (`dtzagent`), hosted in the z/OS USS environment, runs as part of the zDC. It manages the update process of the zLocal.": "Начальный загрузчик (`dtzagent`), размещённый в среде z/OS USS, работает в составе zDC. Он управляет процессом обновления zLocal.",
    # --- intro para 4 ---
    "When the zDC initializes (system startup or manual start), it starts the bootstrapper, and the bootstrapper starts the zLocal. When the zDC terminates, the zLocal and the bootstrapper are stopped.": "При инициализации zDC (при запуске системы или вручную) он запускает начальный загрузчик, а тот запускает zLocal. При завершении работы zDC zLocal и начальный загрузчик останавливаются.",
    # --- ## System security ---
    "## System security": "## Безопасность системы",
    "The zDC (zLocal) uses TCP/IP socket connections, so it may be necessary to update your security system's access rules if they are configured to deny TCP/IP access by default.": "zDC (zLocal) использует TCP/IP-сокетные соединения, поэтому может потребоваться обновить правила доступа вашей системы безопасности, если они настроены на запрет TCP/IP-доступа по умолчанию.",
    "The zDC doesn't limit which user IDs can enter operator commands.": "zDC не ограничивает перечень идентификаторов пользователей, которые могут вводить команды оператора.",
    "You can control permissions assigned to files created by the zLocal and bootstrapper by setting `DT_UMASK`. The default is `umask(022)`.": "Разрешения, назначаемые файлам, создаваемым zLocal и начальным загрузчиком, можно регулировать с помощью параметра `DT_UMASK`. По умолчанию используется `umask(022)`.",
    # --- ## Installation ---
    "## Installation": "## Установка",
    "The zDC runs as an authorized z/OS process (typically as a system task). This means the programs must reside in an authorized library. It is intended to start automatically as a started task at a system IPL. This gives the zDC continuous availability to collect monitoring data from modules.": "zDC работает как авторизованный процесс z/OS (обычно как системная задача). Это означает, что программы должны находиться в авторизованной библиотеке. Предполагается, что zDC запускается автоматически как запускаемая задача при IPL системы, что обеспечивает его непрерывную доступность для сбора данных мониторинга из модулей.",
    "The zDC can also be run as a batch job. The service class of the zDC must be high enough so that it is always available for keep-alive messages from the zRemote. The zDC should have a priority higher than the monitored CICS and IMS regions.": "zDC может также работать как пакетное задание. Класс обслуживания zDC должен быть достаточно высоким, чтобы он всегда был доступен для keep-alive-сообщений от zRemote. Приоритет zDC должен быть выше, чем у отслеживаемых регионов CICS и IMS.",
    "A zDC subsystem must be installed on each LPAR you want to monitor.": "Подсистема zDC должна быть установлена на каждом LPAR, который нужно отслеживать.",
    # --- step 1 ---
    '1. [Download z/OS product datasets](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets "Download and install the Dynatrace product datasets for z/OS."). Make a note of the high-level qualifier used in the download procedure.': '1. [Загрузите наборы данных продукта z/OS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets "Скачайте и установите наборы данных продукта Dynatrace для z/OS."). Запишите квалификатор высокого уровня, использованный в процедуре загрузки.',
    # --- step 2 ---
    "2. Create the RACF user ID for the zDC process. This ID must have a z/OS USS segment. The recommended home directory name is `/u/dt`.": "2. Создайте RACF-идентификатор пользователя для процесса zDC. Этот идентификатор должен иметь сегмент z/OS USS. Рекомендуемое имя домашнего каталога: `/u/dt`.",
    "If a home directory other than `/u/dt` is set, change in step 8 the path to the bootstrapper, which defaults to `/u/dt/agent/lib64/dtzagent`. The path names below the home directory can't be changed.": "Если задан домашний каталог, отличный от `/u/dt`, измените в шаге 8 путь к начальному загрузчику, который по умолчанию равен `/u/dt/agent/lib64/dtzagent`. Имена путей ниже домашнего каталога изменить нельзя.",
    "The home directory or the high-level qualifier that replaces it must be writeable by the zDC process.": "Домашний каталог или заменяющий его квалификатор высокого уровня должны быть доступны для записи процессом zDC.",
    "* It writes the zLocal binary to `/u/dt/agent/downloads/native/a.b.c.d/zos-s390-64/libdtzagent.so`, where `a.b.c.d` is the version of the zLocal (i.e. 1.0.1.0).": "* zDC записывает бинарный файл zLocal по пути `/u/dt/agent/downloads/native/a.b.c.d/zos-s390-64/libdtzagent.so` (версия zLocal, например 1.0.1.0).",
    "* It writes the zDC and zLocal logs to `/u/dt/log/dtxxx.log`.": "* zDC записывает логи zDC и zLocal по пути `/u/dt/log/dtxxx.log`.",
    "If write fails, the zDC processes use the directory `/tmp/dynaTrace`.": "При сбое записи процессы zDC используют каталог `/tmp/dynaTrace`.",
    "If the zDC is run as a started task, the ID must be capable of representing the zDC started task and have access to the USS path above.": "Если zDC запускается как запускаемая задача, данный идентификатор должен быть способен представлять запускаемую задачу zDC и иметь доступ к указанному USS-пути.",
    # --- step 3 ---
    '3. Change the dataset high-level qualifier represented by <hlq> in member `COPYAGNT` of `SZDTSAMP` to the value you used in the [Download z/OS product datasets](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets "Download and install the Dynatrace product datasets for z/OS.") procedure.': '3. Замените квалификатор высокого уровня набора данных, обозначенный как <hlq>, в элементе `COPYAGNT` набора `SZDTSAMP` на значение, использованное в процедуре [Загрузки наборов данных продукта z/OS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets "Скачайте и установите наборы данных продукта Dynatrace для z/OS.").',
    # --- step 4 ---
    "4. Run the `COPYAGNT` job to create the required z/OS USS subdirectories under the home directory of the zDC started task.": "4. Запустите задание `COPYAGNT`, чтобы создать необходимые подкаталоги z/OS USS в домашнем каталоге запускаемой задачи zDC.",
    # --- step 5 ---
    "5. Copy the `dtzagent` binary from `SZDTSAMP` and set it to be executable.": "5. Скопируйте бинарный файл `dtzagent` из `SZDTSAMP` и установите для него атрибут исполняемого файла.",
    "If you're using the default home directory of `/u/dt`, the resulting path is `/u/dt/agent/lib64/dtzagent`.": "При использовании домашнего каталога по умолчанию `/u/dt` результирующий путь: `/u/dt/agent/lib64/dtzagent`.",
    "If a home directory other than `/u/dt` is used, the path in this job must be changed accordingly. File and directory names are case-sensitive. The path names below the home directory can't be changed.": "Если используется домашний каталог, отличный от `/u/dt`, путь в этом задании необходимо изменить соответствующим образом. Имена файлов и каталогов чувствительны к регистру. Имена путей ниже домашнего каталога изменить нельзя.",
    "The `COPYAGNT` job should run under the user ID that was created for the zDC process, so that user ID owns the `dtzagent` binary. If this is inconvenient, you can also use the `chown` and `chgrp` commands to reset the owning user and group for the `dtzagent` binary after running `COPYAGNT`.": "Задание `COPYAGNT` рекомендуется запускать под идентификатором пользователя, созданным для процесса zDC, чтобы этот идентификатор владел бинарным файлом `dtzagent`. Если это неудобно, можно использовать команды `chown` и `chgrp` для сброса владельца и группы бинарного файла `dtzagent` после выполнения `COPYAGNT`.",
    # --- step 6 ---
    '6. Authorize `<hlq>.SZDTAUTH` where `<hlq>` is the high-level qualifier value you used in the [Download z/OS product datasets](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets "Download and install the Dynatrace product datasets for z/OS.") procedure.': '6. Авторизуйте `<hlq>.SZDTAUTH`, подставив вместо `<hlq>` квалификатор высокого уровня из процедуры [Загрузки наборов данных продукта z/OS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets "Скачайте и установите наборы данных продукта Dynatrace для z/OS.").',
    "For example, create a member named `SYS1.PARMLIB(PROGDT)` containing:": "Например, создайте элемент `SYS1.PARMLIB(PROGDT)` со следующим содержимым:",
    "Then issue the console command:": "Затем введите команду консоли:",
    # --- step 7 ---
    "7. Copy the `ZDCMEPC` sample zDC started task PROC from `SZDTSAMP` to a system PROCLIB used for started tasks.": "7. Скопируйте образец PROC запускаемой задачи zDC `ZDCMEPC` из `SZDTSAMP` в системную библиотеку PROCLIB, используемую для запускаемых задач.",
    "The default name for the PROC is `MEPC`. Customize it as necessary for local standards. If a different subsystem name is chosen, change the `SUBSYSTEM_ID()` parameter in the [SYSIN parameters](#sysin-parameters) to match.": "Имя PROC по умолчанию: `MEPC`. Настройте его в соответствии с местными стандартами. Если выбрано другое имя подсистемы, измените параметр `SUBSYSTEM_ID()` в [параметрах SYSIN](#sysin-parameters) соответственно.",
    "The PROC and the two JCL SYSIN members `ZDCSYSIN` and `ZDCMEPCA` that it uses contain dataset names that must be edited to replace `<hlq>.` with the appropriate high-level qualifiers.": "PROC и два элемента JCL SYSIN `ZDCSYSIN` и `ZDCMEPCA`, которые он использует, содержат имена наборов данных, в которых необходимо заменить `<hlq>.` на соответствующие квалификаторы высокого уровня.",
    # --- step 8 ---
    "8. Update the `DTAGTCMD()` parameter in the [SYSIN parameter](#sysin-parameters) to reflect your definitions.": "8. Обновите параметр `DTAGTCMD()` в [параметрах SYSIN](#sysin-parameters) в соответствии с вашими определениями.",
    "* `/u/dt/agent/lib64/dtzagent` sets the path to the bootstrapper. The default home directory name is `/u/dt`. If you have set a different home directory in step 2, change it accordingly.": "* `/u/dt/agent/lib64/dtzagent` задаёт путь к начальному загрузчику. Имя домашнего каталога по умолчанию: `/u/dt`. Если в шаге 2 задан другой домашний каталог, измените значение соответственно.",
    "* `nobootstrap=false` enables the bootstrapper to automatically update the zLocal once a newer version is available. Per default, the zLocal receives automatic updates. Set `true` to disable automatic updates and [manually update the zLocal](#update-zlocal).": "* `nobootstrap=false` разрешает начальному загрузчику автоматически обновлять zLocal при появлении новой версии. По умолчанию zLocal получает автоматические обновления. Установите `true`, чтобы отключить автоматические обновления и [обновлять zLocal вручную](#update-zlocal).",
    '* `zremote=<ipaddress>[:port]` set the IP address and port of a [installed zRemote module](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zremote "Prepare and install the zRemote for z/OS monitoring."). The IP address is required, the port is optional and defaults to 8898.': '* `zremote=<ipaddress>[:port]` задаёт IP-адрес и порт [установленного модуля zRemote](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zremote "Подготовьте и установите zRemote для мониторинга z/OS."). IP-адрес обязателен, порт необязателен и по умолчанию равен 8898.',
    # --- step 9 ---
    "9. Verify that the appropriate exit is active, according to the OneAgent version.": "9. Проверьте, что соответствующий выход активен согласно версии OneAgent.",
    "| OneAgent version | Exit(s) | Additional notes |": "| Версия OneAgent | Выход(ы) | Дополнительные примечания |",
    "| --- | --- | --- |": "| --- | --- | --- |",
    # Table row 1 — very long; demoji converts â\x80\x94 to em-dash U+2014 in "1.300—OneAgent"
    "| OneAgent version 1.300+ | U86 | * Required You need to be running z/OS 2.3 or later. * Required The U86 exit is required to report LPAR usage for DPS metrics and billing. + OneAgent version 1.300—OneAgent version 1.314: Dynatrace may suspend tracing without DPS metrics.   + OneAgent version 1.315+: Tracing will be automatically suspended if a `host.zos.msu_hours` metric is not received for 12 consecutive hours.  When this occurs, the following message is recorded in the zRemote log:  `Tracing has been disabled. The LPAR[LPAR] has not sent valid billing metrics.`  Tracing will be automatically re-enabled once valid `host.zos.msu_hours` metrics are received again. |": "| OneAgent версии 1.300+ | U86 | * Обязательно Необходимо, чтобы работала z/OS 2.3 или более поздняя версия. * Обязательно Выход U86 необходим для передачи данных о загрузке LPAR для метрик DPS и биллинга. + OneAgent версии 1.300 до OneAgent версии 1.314: Dynatrace может приостановить трассировку при отсутствии метрик DPS.   + OneAgent версии 1.315+: трассировка будет автоматически приостановлена, если метрика `host.zos.msu_hours` не получена в течение 12 последовательных часов.  При этом в лог zRemote записывается следующее сообщение:  `Tracing has been disabled. The LPAR[LPAR] has not sent valid billing metrics.`  Трассировка будет автоматически возобновлена после получения допустимых метрик `host.zos.msu_hours`. |",
    "| OneAgent version 1.300 and earlier | U83 |  |": "| OneAgent версии 1.300 и ранее | U83 |  |",
    "To verify that SMF exit U86 is active, run the following command:": "Чтобы проверить активность выхода SMF U86, выполните следующую команду:",
    "Look in the command output for `SUBSYS(STC,EXITS(IEFU83))` and `SYS(EXITS(IEFU83))`, or `SUBSYS(STC,EXITS(IEFU86))` and `SYS(EXITS(IEFU86))`.": "В выводе команды найдите строки `SUBSYS(STC,EXITS(IEFU83))` и `SYS(EXITS(IEFU83))` или `SUBSYS(STC,EXITS(IEFU86))` и `SYS(EXITS(IEFU86))`.",
    "* If you find this, the SMF U83 and/or U86 exit is active. Go to the next step.": "* Если эти строки найдены, выход SMF U83 и/или U86 активен. Перейдите к следующему шагу.",
    "* If you don't find this, you need to add it to your SMFPRMxx parmlib member.": "* Если строки не найдены, добавьте их в элемент parmlib SMFPRMxx.",
    "+ U83:": "+ U83:",
    "+ U86:": "+ U86:",
    "Then enable it.": "Затем активируйте его.",
    # --- step 10 ---
    "10. Optional Add a command to your system startup to automatically start the zDC subsystem at IPL.": "10. Необязательно Добавьте команду в процедуру запуска системы для автоматического старта подсистемы zDC при IPL.",
    # --- step 11 ---
    "11. Use the `ZDCIVP` PROC in `SZDTSAMP` to verify the zDC installation and the zRemote connectivity.": "11. Используйте PROC `ZDCIVP` из `SZDTSAMP` для проверки установки zDC и подключения к zRemote.",
    "Good test for the zRemote connectivity returns `Connection timeout`, as the zRemote does not support FTP protocol. If a zRemote connectivity problem exist, it is indicated by `EDC8128I Connection refused`. This implies that the zRemote is not listening on the expected port.": "Успешный тест подключения к zRemote возвращает `Connection timeout`, так как zRemote не поддерживает протокол FTP. При наличии проблемы с подключением к zRemote она обозначается сообщением `EDC8128I Connection refused`. Это означает, что zRemote не прослушивает ожидаемый порт.",
    "Step ZDCXVER - expect JOBLOG messages::": "Шаг ZDCXVER, ожидаемые сообщения JOBLOG:",
    "Step ZDCXVER //SYSTSPRT spool - note special chars are for TSO 3270 formatting": "Шаг ZDCXVER, спул //SYSTSPRT; специальные символы используются для форматирования TSO 3270",
    "Step SHOWIP //SYSTSPRT spool - Note: sample output": "Шаг SHOWIP, спул //SYSTSPRT, пример вывода",
    # --- ## Verify installation ---
    "## Verify installation": "## Проверка установки",
    "After the installation is complete, verify its correctness.": "После завершения установки проверьте её корректность.",
    # --- ### Verify the zDC started correctly ---
    "### Verify the zDC started correctly": "### Проверка корректного запуска zDC",
    "Verify that the zDC has started the correct version, initialized successfully, and has started the zLocal. Look for the following messages in `zDC SYSPRINT DD`.": "Убедитесь, что zDC запустился в правильной версии, успешно инициализировался и запустил zLocal. Найдите следующие сообщения в `zDC SYSPRINT DD`.",
    '`If the following message appears in the zDC job log (your subsystem name might be different than `MEPC`), [restart the zDC](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#terminate-zdc "Customize the zDC subsystem.") with a different `SUBSYSTEM_ID` in the [SYSIN parameters](#sysin-parameters).`': '`Если в журнале заданий zDC появляется следующее сообщение (имя вашей подсистемы может отличаться от `MEPC`), [перезапустите zDC](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#terminate-zdc "Настройка подсистемы zDC.") с другим значением `SUBSYSTEM_ID` в [параметрах SYSIN](#sysin-parameters).`',
    'If the following message appears in the zDC job log (your subsystem name might be different than `MEPC`), [restart the zDC](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#terminate-zdc "Customize the zDC subsystem.") with a different `SUBSYSTEM_ID` in the [SYSIN parameters](#sysin-parameters).': 'Если в журнале заданий zDC появляется следующее сообщение (имя вашей подсистемы может отличаться от `MEPC`), [перезапустите zDC](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#terminate-zdc "Настройка подсистемы zDC.") с другим значением `SUBSYSTEM_ID` в [параметрах SYSIN](#sysin-parameters).',
    # --- ### Verify the zLocal started correctly ---
    "### Verify the zLocal started correctly and connected to the zRemote": "### Проверка корректного запуска zLocal и его подключения к zRemote",
    "The zLocal writes log messages to the zDC SYSPRINT DD in addition to `/u/dt/log` in the z/OS USS environment. The zLocal log contains information relating to zLocal startup, versioning, and connectivity to the zRemote.": "zLocal записывает сообщения журнала в zDC SYSPRINT DD, а также в `/u/dt/log` в среде z/OS USS. Лог zLocal содержит сведения о запуске zLocal, версионировании и подключении к zRemote.",
    "To verify that all the channels in zLocal are connected to the zRemote, look for the following messages in the SYSPRINT:": "Чтобы убедиться, что все каналы zLocal подключены к zRemote, найдите следующие сообщения в SYSPRINT:",
    '`Use the [z/OS MODIFY command](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#Thezos-modify-cmd "Customize the zDC subsystem.") below to instruct the zDC to display the zLocal status and to locate the log file paths of zLocal and zRemote.`': '`Используйте приведённую ниже [команду z/OS MODIFY](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#Thezos-modify-cmd "Настройка подсистемы zDC."), чтобы instructать zDC отобразить статус zLocal и найти пути к файлам журналов zLocal и zRemote.`',
    'Use the [z/OS MODIFY command](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#Thezos-modify-cmd "Customize the zDC subsystem.") below to instruct the zDC to display the zLocal status and to locate the log file paths of zLocal and zRemote.': 'Используйте приведённую ниже [команду z/OS MODIFY](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#Thezos-modify-cmd "Настройка подсистемы zDC."), чтобы указать zDC отобразить статус zLocal и найти пути к файлам журналов zLocal и zRemote.',
    "Once the zLocal log file is located, you can access it using the standard techniques. Use OMVS, ssh/telnet, or view it in the Dynatrace web UI like a regular OneAgent log file.": "После обнаружения файла журнала zLocal к нему можно получить доступ стандартными методами. Используйте OMVS, ssh/telnet или просмотрите его в веб-интерфейсе Dynatrace как обычный файл журнала OneAgent.",
    "Also, look for the following messages in the corresponding zRemote log file (the values inside the bracket should reflect your live data).": "Также найдите следующие сообщения в соответствующем файле журнала zRemote (значения в скобках должны отражать реальные данные).",
    # --- ### Check maintenance level ---
    "### Check maintenance level of the zLocal load module": "### Проверка уровня обслуживания загрузочного модуля zLocal",
    "Browse the install library `<hlq>.R1nnnxx.SZDTAUTH`, where `<hlq>` is the high-level qualifier of the product dataset, to find the `ZDCDTAGT` load module for the zLocal.": "Просмотрите установочную библиотеку `<hlq>.R1nnnxx.SZDTAUTH` (квалификатор высокого уровня набора данных продукта), чтобы найти загрузочный модуль `ZDCDTAGT` для zLocal.",
    "In the header example below, you can see `1.nnn.00`, which indicates this is the version of the load module without any maintenance. When service is applied, the field contains a subversion number like `1.nnn.01`. The dates vary over time.": "В приведённом ниже примере заголовка видно значение `1.nnn.00`, которое означает, что это версия загрузочного модуля без применённого обслуживания. При применении обслуживания поле содержит номер подверсии, например `1.nnn.01`. Даты меняются со временем.",
    "The `ZDCDTAGT` load module can produce diagnostic messages in the following format:": "Загрузочный модуль `ZDCDTAGT` может выдавать диагностические сообщения в следующем формате:",
    "Where `n` is the log level, and `i` is the severity.": "Здесь `n` обозначает уровень журналирования, а `i` обозначает степень серьёзности.",
    # --- ### Insufficient access authority ---
    "### Insufficient access authority message when starting the zDC": "### Сообщение о недостаточных правах доступа при запуске zDC",
    "If the following messages (or something similar) appear in the zDC job log:": "Если в журнале заданий zDC появляются следующие сообщения (или аналогичные):",
    "And the associated messages appear in the zLocal log file:": "И в файле журнала zLocal появляются связанные сообщения:",
    "These can be safely ignored.": "Их можно безопасно проигнорировать.",
    "After the initial download of the zLocal, the operating system tries to set a flag for the downloaded library that is needed in certain circumstances. The flag is not set during the second run because the library will not be downloaded anymore if it already exists.": "После первоначальной загрузки zLocal операционная система пытается установить флаг для загруженной библиотеки, который необходим в определённых обстоятельствах. Флаг не устанавливается при повторном запуске, так как библиотека больше не загружается, если она уже существует.",
    # --- ## SYSIN dataset ---
    "## SYSIN dataset": "## Набор данных SYSIN",
    "All values that tailor the execution of the zDC reside in the dataset pointed to by `DDNAME SYSIN`. The sample started task PROC `ZDCMEPC` refers to the JCL SYSIN member `ZDCSYSIN` of `SZDTSAMP` as shown below:": "Все значения, настраивающие выполнение zDC, хранятся в наборе данных, на который указывает `DDNAME SYSIN`. Образец PROC запускаемой задачи `ZDCMEPC` ссылается на элемент JCL SYSIN `ZDCSYSIN` набора `SZDTSAMP`, как показано ниже:",
    "The dataset must contain 80 character records, blocked to a multiple of 80 bytes.": "Набор данных должен содержать записи по 80 символов, блокированные кратно 80 байтам.",
    "When you make any change to the SYSIN dataset, you must restart the zDC process for the change to take effect.": "При внесении любых изменений в набор данных SYSIN для их вступления в силу необходимо перезапустить процесс zDC.",
    # --- ### SYSIN parameters ---
    "### SYSIN parameters": "### Параметры SYSIN",
    "Positions 1 through 71 of each statement can contain parameter values. Positions 72 through 80 are ignored and can optionally contain a sequence number.": "Позиции с 1 по 71 каждого оператора могут содержать значения параметров. Позиции с 72 по 80 игнорируются и могут содержать порядковый номер.",
    "Each parameter uses `KEYWORD(value)` format. Each keyword and the requirements for the values associated with it are documented in the JCL SYSIN member `ZDCSYSIN` of `SZDTSAMP`.": "Каждый параметр использует формат `KEYWORD(value)`. Каждое ключевое слово и требования к связанным с ним значениям задокументированы в элементе JCL SYSIN `ZDCSYSIN` набора `SZDTSAMP`.",
    "If a parameter value spans multiple lines, specify the value through position 71 and continue the value on the next statement starting in position 1.": "Если значение параметра занимает несколько строк, укажите значение до позиции 71 и продолжите его на следующем операторе, начиная с позиции 1.",
    "How can I add a comment to a statement?": "Как добавить комментарий к оператору?",
    "If you want to use a comment, specify it by placing an asterisk in position 1 of a statement. The entire statement is considered part of the comment.": "Чтобы использовать комментарий, поместите звёздочку в позицию 1 оператора. Весь оператор считается частью комментария.",
    "A comment can be enclosed between a slash-asterisk and an asterisk-slash.": "Комментарий может быть заключён между косой чертой со звёздочкой и звёздочкой с косой чертой.",
    "Multiple lines can be contained within comments of this type.": "Комментарии такого типа могут занимать несколько строк.",
    "| Parameter(default value) | Description |": "| Параметр(значение по умолчанию) | Описание |",
    "| --- | --- |": "| --- | --- |",
    '| DTAGTCMD(/u/dt/agent/lib64/dtzagent) | Sets the path to the bootstrapper `dtzagent`.  Additional parameters:  * `nobootstrap=false` enables the bootstrapper to automatically update the zLocal once a newer version is available. Set `true` to disable automatic updates. * `zremote=<ipaddress>[:port]` sets the IP address and port of the [installed zRemote module](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zremote "Prepare and install the zRemote for z/OS monitoring."). The IP address is required, the port is optional and defaults to 8898. * `name=zlocal_<lpar>` defines the name of the zLocal for log files. The name should reflect that this is a zLocal. It could include the SMF ID of the LPAR that it services. * `loglevel=<value>` sets the log level of the zLocal. Log level values include `FINEST`, `FINER`, `FINE`, `CONFIG`, `INFO`, `WARNING`, `SEVERE`, `DEBUG`, `NONE`). No default value. |': '| DTAGTCMD(/u/dt/agent/lib64/dtzagent) | Задаёт путь к начальному загрузчику `dtzagent`.  Дополнительные параметры:  * `nobootstrap=false` разрешает начальному загрузчику автоматически обновлять zLocal при появлении новой версии. Установите `true`, чтобы отключить автоматические обновления. * `zremote=<ipaddress>[:port]` задаёт IP-адрес и порт [установленного модуля zRemote](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zremote "Подготовьте и установите zRemote для мониторинга z/OS."). IP-адрес обязателен, порт необязателен и по умолчанию равен 8898. * `name=zlocal_<lpar>` задаёт имя zLocal для файлов журналов. Имя должно отражать, что это zLocal, и может включать SMF ID обслуживаемого LPAR. * `loglevel=<value>` задаёт уровень журналирования zLocal. Допустимые значения: `FINEST`, `FINER`, `FINE`, `CONFIG`, `INFO`, `WARNING`, `SEVERE`, `DEBUG`, `NONE`). Значение по умолчанию отсутствует. |',
    "| SUBSYSTEM\\_ID(MEPC) | Defines the name of the zDC subsystem. It must be four non-blank characters:  * The first character must be upper case alpha (A:Z). * The last three characters upper case alphanumeric (#,$,@,A:Z,0-9). |": "| SUBSYSTEM\\_ID(MEPC) | Определяет имя подсистемы zDC. Должно содержать четыре непробельных символа:  * Первый символ: прописная буква (A:Z). * Последние три символа: прописные буквы или цифры (#,$,@,A:Z,0-9). |",
    "| DEFAULT(YES) | Defines a zDC subsystem as default. Monitoring data is collected by the default zDC subsystem that defines `DEFAULT(YES)`. If you run multiple zDC subsystems on a single LPAR, you need to specify `DEFAULT(NO)` for each additional zDC, otherwise, they fail to initialize. |": "| DEFAULT(YES) | Определяет подсистему zDC как основную. Данные мониторинга собирает основная подсистема zDC, в которой задано `DEFAULT(YES)`. При запуске нескольких подсистем zDC на одном LPAR необходимо указать `DEFAULT(NO)` для каждой дополнительной подсистемы, иначе они не инициализируются. |",
    "| DISPLAY\\_NAME() | Defines a display name for this zDC subsystem to identify it in certain log messages. |": "| DISPLAY\\_NAME() | Определяет отображаемое имя данной подсистемы zDC для её идентификации в определённых сообщениях журнала. |",
    "| DTLOGLEVEL(3) | Sets the log level of the zDC. Log level values range from `0` to `8`. Set the value to `4` to suppress informational messages. Values lower than `3` should be only used for diagnostic debugging. |": "| DTLOGLEVEL(3) | Задаёт уровень журналирования zDC. Допустимые значения: от `0` до `8`. Установите значение `4`, чтобы подавить информационные сообщения. Значения ниже `3` следует использовать только для диагностической отладки. |",
    "| DTMSG\\_SMOSIZE(1) | Sets the maximum amount of storage (MB) for messages that can be queued in the zDC shared memory object while awaiting writing to the z/OS modules. The default of 1 MB should be adequate in most cases when transaction buffering is enabled. When transaction buffering is disabled (not recommended), set the SMO size to 10 MB if very high volumes of transactions are traced. |": "| DTMSG\\_SMOSIZE(1) | Задаёт максимальный объём памяти (МБ) для сообщений, которые могут находиться в очереди в объекте общей памяти zDC в ожидании записи в модули z/OS. Значение по умолчанию 1 МБ достаточно в большинстве случаев при включённой буферизации транзакций. При отключённой буферизации транзакций (не рекомендуется) при очень большом объёме трассируемых транзакций установите размер SMO 10 МБ. |",
    "| DTCHDIR(/u/dt) | Changes the z/OS USS current directory where the bootstrapper `dtzagent` creates temporary files for `stdin`, `stdout`, and `stderr`. It defaults to the home directory of the associated user ID. |": "| DTCHDIR(/u/dt) | Изменяет текущий каталог z/OS USS, в котором начальный загрузчик `dtzagent` создаёт временные файлы для `stdin`, `stdout` и `stderr`. По умолчанию используется домашний каталог связанного идентификатора пользователя. |",
    "| DTMSG\\_TRANBUFSIZE(n,m) | Overrides the default number and size of transaction buffers. Transaction buffers offer better performance for CICS and IMS modules by placing event messages related to each distributed trace into dedicated buffers. Rather than send individual event messages for each distributed trace as they occur, they are blocked into one or more buffers and sent together. Additionally, the buffer of related messages is processed more efficiently by the zRemote.  The `n` parameter is the number of buffers in thousands. For example, 2 = 2,000 buffers. A zero value disables transaction buffers. The `m` parameter must be either `2` or `4` to specify a 2 K or 4 K buffer size. We recommend the 4 K buffer size, unless storage consumption is a significant concern. The minimum non-disabled value is `1,2`. The maximum is `126,4` or `248,2`, corresponding to a total size of 512 MB. An upper bound for the number of buffers that may be required is one for each IMS message region and MAXTASK times the number of CICS regions, but actual requirements are likely to be considerably smaller. |": "| DTMSG\\_TRANBUFSIZE(n,m) | Переопределяет количество и размер буферов транзакций по умолчанию. Буферы транзакций повышают производительность для модулей CICS и IMS, помещая сообщения о событиях, связанных с каждой распределённой трассировкой, в выделенные буферы. Вместо отправки отдельных сообщений о событиях по мере их возникновения они группируются в один или несколько буферов и отправляются совместно. Кроме того, буфер связанных сообщений обрабатывается zRemote более эффективно.  Параметр `n` задаёт количество буферов в тысячах. Например, 2 = 2 000 буферов. Нулевое значение отключает буферы транзакций. Параметр `m` должен быть равен `2` или `4`, задавая размер буфера 2 КБ или 4 КБ. Мы рекомендуем размер буфера 4 КБ, если потребление памяти не является критически важным. Минимальное ненулевое значение: `1,2`. Максимальное: `126,4` или `248,2`, что соответствует общему размеру 512 МБ. Верхняя граница требуемого числа буферов: один на каждый регион сообщений IMS и MAXTASK, умноженное на количество регионов CICS; однако фактические потребности, как правило, значительно меньше. |",
    # --- ## Logging ---
    "## Logging": "## Журналирование",
    '`The log level of the zDC is set with the `DTLOGLEVEL()` parameter in the [SYSIN parameters](#sysin-parameters). You can change this log level dynamically by issuing a [z/OS MODIFY command](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#Thezos-modify-cmd "Customize the zDC subsystem.").`': '`Уровень журналирования zDC задаётся параметром `DTLOGLEVEL()` в [параметрах SYSIN](#sysin-parameters). Изменить уровень журналирования динамически можно с помощью [команды z/OS MODIFY](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#Thezos-modify-cmd "Настройка подсистемы zDC.").`',
    'The log level of the zDC is set with the `DTLOGLEVEL()` parameter in the [SYSIN parameters](#sysin-parameters). You can change this log level dynamically by issuing a [z/OS MODIFY command](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#Thezos-modify-cmd "Customize the zDC subsystem.").': 'Уровень журналирования zDC задаётся параметром `DTLOGLEVEL()` в [параметрах SYSIN](#sysin-parameters). Изменить уровень журналирования динамически можно с помощью [команды z/OS MODIFY](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#Thezos-modify-cmd "Настройка подсистемы zDC.").',
    "View log message output in the zDC job spool. The job spool helps determine errors that may occur during the zDC startup or when connecting with the zRemote. Once the zDC successfully connects to the zRemote, error messages from the zDC subsystem and the CICS and IMS modules are routed to the zRemote.": "Просматривайте вывод сообщений журнала в спуле заданий zDC. Спул заданий помогает определить ошибки, которые могут возникнуть при запуске zDC или при подключении к zRemote. После успешного подключения zDC к zRemote сообщения об ошибках от подсистемы zDC и модулей CICS и IMS направляются в zRemote.",
    '`The log level of the zLocal is set with the `DTAGTCMD(loglevel=INFO)` parameter in the [SYSIN parameters](#sysin-parameters). You can change this log level dynamically by issuing a [z/OS MODIFY command](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#Thezos-modify-cmd "Customize the zDC subsystem."). The `DTAGTCMD(name=zlocal_<lpar>)` defines the name of the zLocal for log files. The name should reflect that this is a zLocal. It could include the SMF ID of the LPAR that it services.`': '`Уровень журналирования zLocal задаётся параметром `DTAGTCMD(loglevel=INFO)` в [параметрах SYSIN](#sysin-parameters). Изменить уровень журналирования динамически можно с помощью [команды z/OS MODIFY](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#Thezos-modify-cmd "Настройка подсистемы zDC."). Параметр `DTAGTCMD(name=zlocal_<lpar>)` задаёт имя zLocal для файлов журналов. Имя должно отражать, что это zLocal, и может включать SMF ID обслуживаемого LPAR.`',
    'The log level of the zLocal is set with the `DTAGTCMD(loglevel=INFO)` parameter in the [SYSIN parameters](#sysin-parameters). You can change this log level dynamically by issuing a [z/OS MODIFY command](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#Thezos-modify-cmd "Customize the zDC subsystem."). The `DTAGTCMD(name=zlocal_<lpar>)` defines the name of the zLocal for log files. The name should reflect that this is a zLocal. It could include the SMF ID of the LPAR that it services.': 'Уровень журналирования zLocal задаётся параметром `DTAGTCMD(loglevel=INFO)` в [параметрах SYSIN](#sysin-parameters). Изменить уровень журналирования динамически можно с помощью [команды z/OS MODIFY](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/install-zdc/customize-zdc#Thezos-modify-cmd "Настройка подсистемы zDC."). Параметр `DTAGTCMD(name=zlocal_<lpar>)` задаёт имя zLocal для файлов журналов. Имя должно отражать, что это zLocal, и может включать SMF ID обслуживаемого LPAR.',
    "There are two sets of logs created for the zLocal. Both are created in the OMVS file system. One set is a temporary set of logs only valid for the current execution of the zDC, and the location of these logs defaults to the home directory of the zDC user ID. You can override the location by using the `DTCHDIR()` parameter in the [SYSIN parameters](#sysin-parameters).": "Для zLocal создаются два набора журналов. Оба набора создаются в файловой системе OMVS. Один набор является временным и действителен только для текущего выполнения zDC; расположение этих журналов по умолчанию соответствует домашнему каталогу идентификатора пользователя zDC. Переопределить расположение можно с помощью параметра `DTCHDIR()` в [параметрах SYSIN](#sysin-parameters).",
    "The zLocal also creates a standard set of logs, one for the bootstrapper, and one for the zLocal itself. These logs are in the standard Dynatrace log locations on the OMVS file system.": "zLocal также создаёт стандартный набор журналов: один для начального загрузчика и один для самого zLocal. Эти журналы находятся в стандартных расположениях журналов Dynatrace в файловой системе OMVS.",
    # --- ## Update and maintenance ---
    "## Update and maintenance": "## Обновление и обслуживание",
    '1. [Download z/OS product datasets](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets#download-pax "Download and install the Dynatrace product datasets for z/OS.") and [extract them](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets#extract-datasets "Download and install the Dynatrace product datasets for z/OS.").': '1. [Загрузите наборы данных продукта z/OS](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets#download-pax "Скачайте и установите наборы данных продукта Dynatrace для z/OS.") и [распакуйте их](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets#extract-datasets "Скачайте и установите наборы данных продукта Dynatrace для z/OS.").',
    '2. Update the zDC job to point to the new `<hlq>.SZDTAUTH`. If you have [defined an alias](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets#alias "Download and install the Dynatrace product datasets for z/OS."), redefine the alias. For example:': '2. Обновите задание zDC так, чтобы оно указывало на новый `<hlq>.SZDTAUTH`. Если вы [задали псевдоним](/managed/ingest-from/dynatrace-oneagent/installation-and-operation/zos/installation/zosmf-installer/download-zos-datasets#alias "Скачайте и установите наборы данных продукта Dynatrace для z/OS."), переопределите его. Например:',
    "Updating the zDC subsystem from version 1.211 or earlier": "Обновление подсистемы zDC с версии 1.211 или более ранней",
    "A special handling is required to avoid abends in CICS regions that you're monitoring when updating the zDC subsystem from a version 1.211 or earlier.": "При обновлении подсистемы zDC с версии 1.211 или более ранней требуется специальная обработка, чтобы избежать аварийного завершения (abend) в отслеживаемых регионах CICS.",
    "1. Stop the zDC.": "1. Остановите zDC.",
    "2. Wait for **15 minutes** for the CICS module to reset and clean up the control blocks.": "2. Подождите **15 минут**, пока модуль CICS сбросит и очистит управляющие блоки.",
    "3. Update the zDC to the newer version.": "3. Обновите zDC до более новой версии.",
    "4. Start the zDC.": "4. Запустите zDC.",
    # --- ### zLocal ---
    "### zLocal": "### zLocal",
    "By default, the zLocal receives automatic updates if `DTAGTCMD(nobootstrap=false)` is set in the [SYSIN parameters](#sysin-parameters). At every start of the zDC, the bootstrapper queries the zRemote module for available updates. The latest zLocal is installed as part of the zRemote installation. If an update is available, the zLocal will be automatically downloaded from the zRemote and updated.": "По умолчанию zLocal получает автоматические обновления, если в [параметрах SYSIN](#sysin-parameters) задано `DTAGTCMD(nobootstrap=false)`. При каждом запуске zDC начальный загрузчик запрашивает у модуля zRemote наличие доступных обновлений. Последняя версия zLocal устанавливается в составе установки zRemote. При наличии обновления zLocal автоматически загружается из zRemote и обновляется.",
    "Log message examples in the zDC job output in case of automatic updates": "Примеры сообщений журнала в выводе заданий zDC при автоматических обновлениях",
    # --- ### Manually update the zLocal ---
    "### Manually update the zLocal": "### Обновление zLocal вручную",
    "* Don't use the manual update process for the zLocal when connecting the first time to your Dynatrace environment because the zDC won't start successfully.": "* Не используйте процедуру обновления вручную для zLocal при первом подключении к вашему окружению Dynatrace, так как zDC не запустится успешно.",
    "* The zRemote module must be running when starting the zDC for the first time to avoid a `U103` [user abend](#user-abends).": "* Модуль zRemote должен быть запущен при первом старте zDC, чтобы избежать [аварийного завершения пользователя](#user-abends) `U103`.",
    "Suppose you don't want to receive automatic updates for the zLocal, set `DTAGTCMD(nobootstrap=true)` in the [SYSIN parameters](#sysin-parameters). For the manual update process, the zLocal binary `libdtzagent.so` must be present on the LPAR in the `/u/dt/agent/lib64` directory.": "Если получение автоматических обновлений для zLocal не требуется, задайте `DTAGTCMD(nobootstrap=true)` в [параметрах SYSIN](#sysin-parameters). При ручном обновлении бинарный файл zLocal `libdtzagent.so` должен находиться на LPAR в каталоге `/u/dt/agent/lib64`.",
    "To accomplish this": "Для этого выполните следующее",
    "1. Run the bootstrapper `dtzagent` at least once in either a production LPAR or non-production LPAR.": "1. Запустите начальный загрузчик `dtzagent` хотя бы один раз на производственном или непроизводственном LPAR.",
    "2. Copy the zLocal binary to the target LPAR. In the `SZDTSAMP` dataset, the member `OCOPYAGT` is a job that copies the zLocal binary `libdtzagent.so` to the `/u/dt/agent/lib64` directory.": "2. Скопируйте бинарный файл zLocal на целевой LPAR. В наборе данных `SZDTSAMP` элемент `OCOPYAGT` является заданием, которое копирует бинарный файл zLocal `libdtzagent.so` в каталог `/u/dt/agent/lib64`.",
    "3. Complete the instructions to start the zDC and connect it to your Dynatrace environment.": "3. Выполните инструкции по запуску zDC и его подключению к вашему окружению Dynatrace.",
    "4. If the zDC successfully connects to Dynatrace, `libdtzagent.so` is copied to the `/u/dt/agent/downloads/native/a.b.c.d/zos-s390-64/libdtzagent.so` directory, where `a.b.c.d` is the version of the zLocal (i.e. 1.0.1.0)": "4. При успешном подключении zDC к Dynatrace файл `libdtzagent.so` копируется в каталог `/u/dt/agent/downloads/native/a.b.c.d/zos-s390-64/libdtzagent.so` (версия zLocal, например 1.0.1.0).",
    "Log message examples in the zDC job output in case of manual updates": "Примеры сообщений журнала в выводе заданий zDC при обновлении вручную",
    # --- ## zDC user abends ---
    "## zDC user abends": "## Аварийные завершения пользователя zDC",
    "A zDC may terminate with a user abend due to internal errors and initialization failures. All user abends, except for `U103` and `U106`, create a dump file. See the list of possible user abends below.": "zDC может завершиться аварийным завершением пользователя (user abend) из-за внутренних ошибок и сбоев инициализации. Все аварийные завершения, кроме `U103` и `U106`, создают дамп-файл. Ниже приведён список возможных аварийных завершений.",
    "| Abend | Description |": "| Аварийное завершение | Описание |",
    "| U100 | An internal error occurred due to zDC initialization failure. |": "| U100 | Внутренняя ошибка вследствие сбоя инициализации zDC. |",
    "| U101 | zDC initialization failed and is unable to display the failure message. |": "| U101 | Инициализация zDC завершилась сбоем, отобразить сообщение об ошибке невозможно. |",
    "| U102 | ECSA storage is not available for the zDC. |": "| U102 | Хранилище ECSA недоступно для zDC. |",
    "| U103 | A problem occurred during a RETRY operation from a recovery exit routine. |": "| U103 | Проблема возникла во время операции RETRY из подпрограммы восстановления. |",
    "| U104 | A queue task ended abnormally. This abend is accompanied by a `ZDC066E` message in the SYSLOG. |": "| U104 | Задача очереди завершилась аварийно. Это аварийное завершение сопровождается сообщением `ZDC066E` в SYSLOG. |",
    "| U105 | A queue task ended abnormally while shutdown was NOT in progress. |": "| U105 | Задача очереди завершилась аварийно, когда завершение работы НЕ выполнялось. |",
    "| U106 | A fatal error occurred in TCPSP routine. |": "| U106 | Фатальная ошибка в подпрограмме TCPSP. |",
    "| U110 | This abend might occur for various internal error reasons. It is accompanied by one of the following zDC error messages in the SYSLOG:  * `ZDC988E` * `ZDC987E` * `ZDC985E` * `ZDC984E` * `ZDC983E` * `ZDC982E` * `ZDC981E` * `ZDC988E` * `ZDC982E` * `ZDC981E` * `ZDC979E` * `ZDC978E` |": "| U110 | Это аварийное завершение может возникать по различным причинам внутренних ошибок. Оно сопровождается одним из следующих сообщений об ошибках zDC в SYSLOG:  * `ZDC988E` * `ZDC987E` * `ZDC985E` * `ZDC984E` * `ZDC983E` * `ZDC982E` * `ZDC981E` * `ZDC988E` * `ZDC982E` * `ZDC981E` * `ZDC979E` * `ZDC978E` |",
    "| U111 | An internal error occurred in one of the zDC modules. The abend is accompanied by one of the following error messages in the SYSLOG:  * `AgtSt:DqrIErr-Get Token/Name for FML failed` * `AgtSt:DqrILod LOAD failed` * `AgtSt:Waiting for Que Data Space failed-Abort` |": "| U111 | Внутренняя ошибка в одном из модулей zDC. Аварийное завершение сопровождается одним из следующих сообщений об ошибках в SYSLOG:  * `AgtSt:DqrIErr-Get Token/Name for FML failed` * `AgtSt:DqrILod LOAD failed` * `AgtSt:Waiting for Que Data Space failed-Abort` |",
    "| U205 | The zDC is unable to open SYSPRINT or SYSPRIN3 DD for displaying log messages. |": "| U205 | zDC не может открыть SYSPRINT или SYSPRIN3 DD для отображения сообщений журнала. |",
    "| U222 | An internal error occurred in one of the zDC modules. The abend is accompanied by one of the following messages in the SYSLOG:  * `066E IEAVRLS Error limit!` * `066E Freed dead TBC Error-Abend222` |": "| U222 | Внутренняя ошибка в одном из модулей zDC. Аварийное завершение сопровождается одним из следующих сообщений в SYSLOG:  * `066E IEAVRLS Error limit!` * `066E Freed dead TBC Error-Abend222` |",
    # --- ## Troubleshooting ---
    "## Troubleshooting": "## Устранение неполадок",
    "* [zDC subsystem troubleshooting](https://dt-url.net/al03k4i)": "* [Устранение неполадок подсистемы zDC](https://dt-url.net/al03k4i)",
}

# Lines that remain verbatim EN (UI labels, command names, etc.)
PASS = set()

if __name__ == "__main__":
    build_one(REL, FN, TRANS, PASS)
    qa_one(REL, FN)
