# -*- coding: utf-8 -*-
from _otel_canon import S, build_one, qa_one

REL = "ingest-from/opentelemetry/collector"
FNAME = "configuration.md"

TRANS = {
    # --- frontmatter ---
    "title: Configure the OTel Collector": "title: Настройка OTel Collector",
    # --- page headings (h1 appears twice in source) ---
    "# Configure the OTel Collector": "# Настройка OTel Collector",
    # --- metadata ---
    "* 4-min read": "* Чтение: 4 мин",
    "* Updated on Apr 16, 2026": "* Обновлено 16 апреля 2026 г.",
    # --- intro paragraph ---
    "To successfully configure your OTel Collector instance, you need to configure each component (receiver, optional processor, and exporter) individually in the Collector YAML configuration file and enable them via additional pipeline objects.": "Для успешной настройки экземпляра OTel Collector нужно настроить каждый компонент (receiver, необязательный processor и exporter) по отдельности в файле конфигурации YAML Collector и включить их с помощью дополнительных объектов конвейера.",
    # --- admonition: product name, keep EN ---
    "Dynatrace OTel Collector": "Dynatrace OTel Collector",
    "As part of a Dynatrace OTel Collector setup, note that you can only configure the components shipped with Dynatrace OTel Collector.": "При использовании дистрибутива Dynatrace OTel Collector следует учитывать, что настраивать можно только компоненты, входящие в его состав.",
    'For a complete list of components that the Dynatrace OTel Collector supports, see [OTel Collector for ingesting telemetry into Dynatrace](/managed/ingest-from/opentelemetry/collector#dt-collector-dist "Learn how to use the OpenTelemetry Collector, including the Dynatrace OTel Collector, to ingest telemetry from OpenTelemetry.").': 'Полный список компонентов, поддерживаемых Dynatrace OTel Collector, см. в разделе [OTel Collector для приёма телеметрии в Dynatrace](/managed/ingest-from/opentelemetry/collector#dt-collector-dist "Узнайте, как использовать OpenTelemetry Collector, включая Dynatrace OTel Collector, для приёма телеметрии из OpenTelemetry.").',
    # --- section: Configuration example ---
    "## Configuration example": "## Пример конфигурации",
    "Here is an example YAML file for a very basic Collector configuration that can be used to export OpenTelemetry traces, metrics, and logs to Dynatrace.": "Ниже приведён пример файла YAML с минимальной конфигурацией Collector, которую можно использовать для экспорта трассировок, метрик и логов OpenTelemetry в Dynatrace.",
    # --- admonition: Cumulativetodelta processor recommendation (descriptive title, translate) ---
    "Cumulativetodelta processor recommendation": "Рекомендации по processor cumulativetodelta",
    # NOTE: source line 145 contains mojibake ï»¿ inside the link text; reproduced verbatim in key (norm() strips BOM but the key here uses the clean form since norm() resolves it before matching).
    "It is recommended to set the `max_staleness` parameter of the [cumulativetodelta processorï»¿](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/processor/cumulativetodeltaprocessor) to a value higher than how often the Collector receives metrics (e.g., how often metrics via OTLP are received, or how long the Prometheus scrape interval is). This ensures that no references to abandoned metric streams accumulate in memory over time.": "Параметру `max_staleness` [processor cumulativetodelta](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/processor/cumulativetodeltaprocessor) рекомендуется задавать значение, превышающее интервал поступления метрик в Collector (например, интервал поступления метрик по OTLP или интервал сбора Prometheus). Это гарантирует, что ссылки на заброшенные потоки метрик не будут накапливаться в памяти с течением времени.",
    # --- prose after the YAML block ---
    "In this YAML file, we configure the following components:": "В этом файле YAML мы настраиваем следующие компоненты:",
    "* An OTLP receiver (`otlp`) that can receive data via gRPC and HTTP.": "* Receiver OTLP (`otlp`), способный принимать данные по gRPC и HTTP.",
    "* A processor to convert any metrics with cumulative temporality to delta temporality (see [Delta metrics](#delta-metrics) for more details).": "* Processor для преобразования метрик с кумулятивной темпоральностью в дельта-темпоральность (подробнее см. в разделе [Дельта-метрики](#delta-metrics)).",
    "* An OTLP HTTP exporter (`otlp_http`) configured with:": "* Exporter OTLP HTTP (`otlp_http`), настроенный с указанием:",
    '+ The Dynatrace endpoint, see [Base URLs](/managed/ingest-from/opentelemetry/otlp-api#base-url "Learn about the OTLP API endpoints that your application uses to export OpenTelemetry data to Dynatrace.")': '+ эндпоинта Dynatrace, см. раздел [Базовые URL](/managed/ingest-from/opentelemetry/otlp-api#base-url "Узнайте об эндпоинтах OTLP API, которые ваше приложение использует для экспорта данных OpenTelemetry в Dynatrace.")',
    '+ An API token, see [Authentication](/managed/ingest-from/opentelemetry/otlp-api#authentication-export-to-activegate "Learn about the OTLP API endpoints that your application uses to export OpenTelemetry data to Dynatrace.").': '+ API-токена, см. раздел [Аутентификация](/managed/ingest-from/opentelemetry/otlp-api#authentication-export-to-activegate "Узнайте об эндпоинтах OTLP API, которые ваше приложение использует для экспорта данных OpenTelemetry в Dynatrace.").',
    "As part of the `otlp_http` exporter configuration, you can also set the `logs_endpoint` to control how Dynatrace processes structured log data: keep the original nested structure (raw), or flatten it into key paths (flattened).": "В рамках конфигурации exporter `otlp_http` также можно задать `logs_endpoint`, чтобы управлять обработкой структурированных данных логов в Dynatrace: сохранять исходную вложенную структуру (`raw`) или выравнивать её в виде путей к ключам (`flattened`).",
    "For more information, see [Configure structured logs processing](#structured-logs).": "Дополнительные сведения см. в разделе [Настройка обработки структурированных логов](#structured-logs).",
    "In the example configuration above, the Dynatrace token needs to have the **Ingest OpenTelemetry traces** (`openTelemetryTrace.ingest`), the **Ingest metrics** (`metrics.ingest`), and the **Ingest logs** (`logs.ingest`) permissions.": "В приведённом выше примере конфигурации токен Dynatrace должен иметь разрешения **Ingest OpenTelemetry traces** (`openTelemetryTrace.ingest`), **Ingest metrics** (`metrics.ingest`) и **Ingest logs** (`logs.ingest`).",
    "Within the service section, you define each component separately.": "В разделе `service` каждый компонент определяется по отдельности.",
    "* Extensions can be enabled in their own section, while receivers, processors, and exporters are grouped under a pipeline section.": "* Extensions включаются в собственном разделе, тогда как receivers, processors и exporters группируются в разделе конвейера.",
    "* Pipelines can be of type traces, metrics, or logs.": "* Конвейеры могут быть типа traces, metrics или logs.",
    "* Each receiver/processor/exporter can be used in more than one pipeline. For processors referenced in multiple pipelines, each pipeline gets a separate instance of the processors. This contrasts with receivers/exporters referenced in multiple pipelines, where only one instance of a receiver/exporter is used for all pipelines. Also, note that the order of processors dictates the order in which data is processed.": "* Каждый receiver/processor/exporter можно использовать в нескольких конвейерах. Для processors, задействованных в нескольких конвейерах, каждый конвейер получает отдельный экземпляр processor. В отличие от них, receivers/exporters, задействованные в нескольких конвейерах, используют единственный экземпляр receiver/exporter для всех конвейеров. Следует также учитывать, что порядок processors определяет порядок обработки данных.",
    "* You can also define the same components more than once. For example, you can have two different receivers or even two or more distinct parts of the pipeline.": "* Одни и те же компоненты можно определять более одного раза. Например, можно задать два разных receiver или даже два и более отдельных участка конвейера.",
    "* Even if a component is properly configured in its section, it will not be enabled unless it's also defined in the service section.": "* Даже если компонент правильно настроен в своём разделе, он не будет активирован, пока не будет также определён в разделе `service`.",
    # --- section: Validate the configuration ---
    "## Validate the configuration": "## Проверка конфигурации",
    "It is important to ensure the used Collector configuration is syntactically and semantically correct. For example, YAML uses spaces (not tabs) for indentation, to define the document hierarchy, and it is necessary to use the right level of indentation for each section and component. The Collector provides the built-in `validate` command to verify the configuration and its components and services are properly configured.": "Важно убедиться, что используемая конфигурация Collector синтаксически и семантически корректна. Например, в YAML для определения иерархии документа используются пробелы (не символы табуляции), и для каждого раздела и компонента необходим правильный уровень отступа. Collector предоставляет встроенную команду `validate` для проверки корректности конфигурации, её компонентов и сервисов.",
    "If you run a container instance of the Collector, you can also use the following Docker command to run the validation directly from your container.": "Если экземпляр Collector запущен в контейнере, для выполнения проверки непосредственно из контейнера также можно использовать следующую команду Docker.",
    # --- section: Delta metrics ---
    "## Delta metrics": "## Дельта-метрики",
    'Dynatrace requires metrics data to be [sent with delta temporality](/managed/ingest-from/opentelemetry/otlp-api/ingest-otlp-metrics/about-metrics-ingest#aggregation-temporality "Learn how Dynatrace ingests OpenTelemetry metrics and what limitations apply.") and **not** cumulative temporality.': 'Dynatrace требует, чтобы данные метрик [передавались с дельта-темпоральностью](/managed/ingest-from/opentelemetry/otlp-api/ingest-otlp-metrics/about-metrics-ingest#aggregation-temporality "Узнайте, как Dynatrace принимает метрики OpenTelemetry и какие ограничения применяются."), а **не** с кумулятивной темпоральностью.',
    "If your application doesn't allow you to configure delta temporality, you can use the [`cumulativetodelta` processorï»¿](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/processor/cumulativetodeltaprocessor) to have your Collector instance adjust cumulative values to delta values. The [configuration example](#configuration-example) above shows how to configure and reference the processor in your Collector configuration.": "Если в приложении нет возможности настроить дельта-темпоральность, можно использовать [processor `cumulativetodelta`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/processor/cumulativetodeltaprocessor), чтобы экземпляр Collector преобразовывал кумулятивные значения в значения с дельта-темпоральностью. В [примере конфигурации](#configuration-example) выше показано, как настроить processor и указать его в конфигурации Collector.",
    # --- section: Chained and load-balanced Collectors ---
    "## Chained and load-balanced Collectors": "## Цепочечные Collector и балансировка нагрузки",
    "When you use more than one Collector instance, it's important to maintain stable value propagation across all instances.": "При использовании нескольких экземпляров Collector важно обеспечить стабильное распространение значений между всеми экземплярами.",
    "This is particularly important when you send OTLP requests across different Collector instances (for example, load balancing), as each Collector instance keeps track of its own delta offset, which may break the data reported to the Dynatrace backend.": "Это особенно важно при отправке запросов OTLP через разные экземпляры Collector (например, при балансировке нагрузки), поскольку каждый экземпляр Collector отслеживает собственное дельта-смещение, что может нарушить корректность данных, передаваемых в бэкенд Dynatrace.",
    "In such scenarios, we recommend routing your OTLP requests through a single, outbound Collector instance that forwards the data to the Dynatrace backend and takes care of the delta conversion. The other Collector instances should use a cumulative aggregation, to ensure stable and consistent value propagation.": "В таких сценариях мы рекомендуем направлять запросы OTLP через единственный исходящий экземпляр Collector, который пересылает данные в бэкенд Dynatrace и выполняет преобразование дельта-значений. Остальные экземпляры Collector должны использовать кумулятивную агрегацию для обеспечения стабильного и согласованного распространения значений.",
    # --- section: Configure structured logs processing ---
    "## Configure structured logs processing": "## Настройка обработки структурированных логов",
    "When you export structured logs to Dynatrace, Dynatrace processes the log data in one of two ways.": "При экспорте структурированных логов в Dynatrace обработка данных логов выполняется одним из двух способов.",
    "It either:": "Варианты:",
    '* Keeps the original nested structure from your logs source ("raw").': '* Сохранить исходную вложенную структуру из источника логов (`"raw"`).',
    '* Flattens it so all log attribute values are accessible via key paths ("flattened").': '* Выровнять её так, чтобы все значения атрибутов логов были доступны через пути к ключам (`"flattened"`).',
    "To configure this behavior, use the `logs_endpoint` setting as shown in the example below:": "Для настройки этого поведения используйте параметр `logs_endpoint`, как показано в примере ниже:",
    "Make sure to include the complete API endpoint path including `/v1/logs` (environment variables are allowed), followed by the desired behavior.": "Нужно указать полный путь к эндпоинту API, включая `/v1/logs` (допускаются переменные окружения), а затем желаемое поведение.",
    "* To keep the original nested structure, use `structure=raw`.": "* Чтобы сохранить исходную вложенную структуру, используйте `structure=raw`.",
    "* To flatten the log data, use `structure=flattened`.": "* Чтобы выровнять данные логов, используйте `structure=flattened`.",
    'For more information, see [Log ingestion API processing](/managed/ingest-from/opentelemetry/otlp-api/ingest-logs#otlp-structured-logs "Learn how Dynatrace ingests OpenTelemetry log records and what limitations apply.").': 'Дополнительные сведения см. в разделе [Обработка API приёма логов](/managed/ingest-from/opentelemetry/otlp-api/ingest-logs#otlp-structured-logs "Узнайте, как Dynatrace принимает записи логов OpenTelemetry и какие ограничения применяются.").',
    "If this configuration option is not specified, the default behavior depends on when your environment was created.": "Если этот параметр конфигурации не задан, поведение по умолчанию зависит от даты создания среды.",
    "* For Dynatrace version 1.331+ and environments created after February 1, 2026: Raw.": "* Для Dynatrace версии 1.331+ и сред, созданных после 1 февраля 2026 г.: Raw.",
    "* For environments created before February 1, 2026: Flattened.": "* Для сред, созданных до 1 февраля 2026 г.: Flattened.",
    **S,
}

PASS = set()

if __name__ == "__main__":
    build_one(REL, FNAME, TRANS, PASS)
    qa_one(REL, FNAME)
