# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/google-cloud-platform/gcp-integrations/gcp-functions"
FILE = "opentelemetry-on-gcf-nodejs.md"

TRANS = {
    "title: Integrate on Google Cloud Functions Node.js": "title: Интеграция OpenTelemetry на Google Cloud Functions Node.js",
    "# Integrate on Google Cloud Functions Node.js": "# Интеграция OpenTelemetry на Google Cloud Functions Node.js",
    "* How-to guide": "* Практическое руководство",
    "* 4-min read": "* Чтение: 4 мин",
    "* Updated on Sep 26, 2025": "* Обновлено 26 сентября 2025 г.",
    "The [`@dynatrace/opentelemetry-gcf`ï»¿](https://dt-url.net/zm03ye8) module provides APIs for tracing Node.js on Google Cloud Functions (GCF).": "Модуль [`@dynatrace/opentelemetry-gcf`](https://dt-url.net/zm03ye8) предоставляет API для трассировки Node.js на Google Cloud Functions (GCF).",
    "## Prerequisites": "## Предварительные требования",
    "Make sure you have followed the instructions on how to [integrate OpenTelemetry on Google Cloud Functions](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf \"Monitor Google Cloud Functions with OpenTelemetry and Dynatrace.\").": "Убедитесь, что вы выполнили инструкции по [интеграции OpenTelemetry на Google Cloud Functions](/managed/ingest-from/google-cloud-platform/gcp-integrations/gcp-functions/opentelemetry-on-gcf \"Мониторинг Google Cloud Functions с помощью OpenTelemetry и Dynatrace.\").",
    "* So far, only [HTTP triggersï»¿](https://dt-url.net/os23yfz) are supported.": "* На данный момент поддерживаются только [триггеры HTTP](https://dt-url.net/os23yfz).",
    "* Cloud Function product version: 1st gen, 2nd gen": "* Версия продукта Cloud Function: 1-го поколения, 2-го поколения",
    "## Installation": "## Установка",
    "To set up OpenTelemetry Node.js integration on Google Cloud Functions, run the command below in the root directory of your Google Cloud Function project.": "Чтобы настроить интеграцию OpenTelemetry Node.js на Google Cloud Functions, выполните следующую команду в корневом каталоге вашего проекта Google Cloud Function.",
    "This will install the latest version of the [`@dynatrace/opentelemetry-gcf`ï»¿](https://dt-url.net/zm03ye8) module from NPM. Note that this library by itself is not enough to start tracing your Google Cloud Functions.": "Будет установлена последняя версия модуля [`@dynatrace/opentelemetry-gcf`](https://dt-url.net/zm03ye8) из NPM. Обратите внимание: одной этой библиотеки недостаточно для начала трассировки Google Cloud Functions.",
    "See the [Usage](#usage) section below for the remaining required steps.": "Оставшиеся необходимые шаги см. в разделе [Использование](#usage) ниже.",
    "## Usage": "## Использование",
    "To export traces to Dynatrace": "Чтобы экспортировать трассировки в Dynatrace",
    "1. Select one of the two ways below to initialize tracing.": "1. Выберите один из двух способов инициализации трассировки.",
    "* `NodeTracerProvider` used to initialize tracing is more lightweight than `NodeSDK`.": "* `NodeTracerProvider` для инициализации трассировки легче, чем `NodeSDK`.",
    "* `NodeSDK` is typically used if you're interested in additional OpenTelemetry signals such as metrics.": "* `NodeSDK` обычно используется, если требуются дополнительные сигналы OpenTelemetry, например метрики.",
    "Using NodeTracerProvider (recommended)": "Использование NodeTracerProvider (рекомендуется)",
    "Using NodeSDK": "Использование NodeSDK",
    "Install the required OpenTelemetry packages with the command below.": "Установите необходимые пакеты OpenTelemetry следующей командой.",
    "After you install the packages, initialize tracing using the following snippet as an example.": "После установки пакетов инициализируйте трассировку с помощью следующего примера кода.",
    "2. Start the root Google Cloud Function server span, using one of the two general patterns in OpenTelemetry below.": "2. Запустите корневой серверный спан Google Cloud Function, используя один из двух шаблонов OpenTelemetry.",
    "Start an active span (recommended)": "Запуск активного спана (рекомендуется)",
    "Start the span and activate it later": "Запуск спана с последующей активацией",
    "Example that starts and immediately activates a span inside a Google Cloud Function:": "Пример запуска и немедленной активации спана внутри Google Cloud Function:",
    "Example that starts a span inside a Google Cloud Function and later activates it within the same function.": "Пример запуска спана внутри Google Cloud Function с последующей активацией в той же функции.",
    "## Compatibility": "## Совместимость",
    "| OneAgent version | OpenTelemetry API | OpenTelemetry SDK |": "| Версия OneAgent | OpenTelemetry API | OpenTelemetry SDK |",
    "| --- | --- | --- |": "| --- | --- | --- |",
    "| 1.243 - 1.255 | 1.x.y | 1.0.x |": "| 1.243 - 1.255 | 1.x.y | 1.0.x |",
    "| 1.257+ | 1.x.y | 1.0.x - 1.7.x |": "| 1.257+ | 1.x.y | 1.0.x - 1.7.x |",
    "| 1.259+ | 1.x.y | 1.0.x - 1.8.x |": "| 1.259+ | 1.x.y | 1.0.x - 1.8.x |",
    "| 1.261+ | 1.x.y | 1.0.x - 1.9.x |": "| 1.261+ | 1.x.y | 1.0.x - 1.9.x |",
    "| 1.265+ | 1.x.y | 1.0.x - 1.10.x |": "| 1.265+ | 1.x.y | 1.0.x - 1.10.x |",
    "| 1.273+ | 1.x.y | 1.0.x - 1.15.x |": "| 1.273+ | 1.x.y | 1.0.x - 1.15.x |",
    "| 1.279+ | 1.x.y | 1.0.x - 1.17.x |": "| 1.279+ | 1.x.y | 1.0.x - 1.17.x |",
    "| 1.283+ | 1.x.y | 1.0.x - 1.18.x |": "| 1.283+ | 1.x.y | 1.0.x - 1.18.x |",
    "| 1.285+ | 1.x.y | 1.0.x - 1.20.x |": "| 1.285+ | 1.x.y | 1.0.x - 1.20.x |",
    "| 1.289+ | 1.x.y | 1.0.x - 1.22.x |": "| 1.289+ | 1.x.y | 1.0.x - 1.22.x |",
    "| 1.293+ | 1.x.y | 1.0.x - 1.24.x |": "| 1.293+ | 1.x.y | 1.0.x - 1.24.x |",
    "| 1.297+ | 1.x.y | 1.0.x - 1.25.x |": "| 1.297+ | 1.x.y | 1.0.x - 1.25.x |",
    "| 1.303+ | 1.x.y | 1.0.x - 1.26.x |": "| 1.303+ | 1.x.y | 1.0.x - 1.26.x |",
    "| 1.307+ | 1.x.y | 1.0.x - 1.29.x |": "| 1.307+ | 1.x.y | 1.0.x - 1.29.x |",
    "| 1.313+ | 1.x.y | 1.0.x - 1.30.x |": "| 1.313+ | 1.x.y | 1.0.x - 1.30.x |",
    "| 1.327+ | 1.x.y | 1.0.x - 2.0.x |": "| 1.327+ | 1.x.y | 1.0.x - 2.0.x |",
    "| 1.331+ | 1.x.y | 1.0.x - 2.2.x |": "| 1.331+ | 1.x.y | 1.0.x - 2.2.x |",
    "| 1.335+ | 1.x.y | 1.0.x - 2.5.x |": "| 1.335+ | 1.x.y | 1.0.x - 2.5.x |",
    "Dynatrace version 1.327+ The `@dynatrace/opentelemetry-gcf` module supports OpenTelemetry SDK V2. To use V2 (instead of V1), override the version of `@dynatrace/opentelemetry-core` module (required by `@dynatrace/opentelemetry-gcf`) with a version that supports OpenTelemetry SDK V2.": "Dynatrace версии 1.327+ Модуль `@dynatrace/opentelemetry-gcf` поддерживает OpenTelemetry SDK V2. Чтобы использовать V2 (вместо V1), переопределите версию модуля `@dynatrace/opentelemetry-core` (требуемого `@dynatrace/opentelemetry-gcf`) на версию с поддержкой OpenTelemetry SDK V2.",
    "1. From the table above, choose a version that supports OpenTelemetry SDK V2.": "1. Из таблицы выше выберите версию с поддержкой OpenTelemetry SDK V2.",
    "2. In your `package.json` file, adding the `overrides` section and specify one of the versions of the `@dynatrace/opentelemetry-core` module to enforce.": "2. В файле `package.json` добавьте раздел `overrides` и укажите одну из версий модуля `@dynatrace/opentelemetry-core` для принудительного использования.",
    "3. Run `npm install` to apply the changes.": "3. Выполните `npm install` для применения изменений.",
    "Example:": "Пример:",
    "Once `@dynatrace/opentelemetry-gcf` is changed to use OpenTelemetry SDK V2 by default, this override won't be needed anymore.": "После того как `@dynatrace/opentelemetry-gcf` будет по умолчанию переключён на OpenTelemetry SDK V2, это переопределение больше не потребуется.",
    "## Cold start": "## Холодный старт",
    "Starting a Google Cloud Function span during [cold startsï»¿](https://dt-url.net/j543yr9) produces additional HTTP requests to fetch metadata from your [Google Cloud environmentï»¿](https://dt-url.net/jc83y1m) and set the attributes required for Dynatrace to process the spans.": "Запуск спана Google Cloud Function при [холодных стартах](https://dt-url.net/j543yr9) генерирует дополнительные HTTP-запросы для получения метаданных из [среды Google Cloud](https://dt-url.net/jc83y1m) и установки атрибутов, необходимых Dynatrace для обработки спанов.",
    "## Span flush": "## Сброс спанов",
    "To ensure that spans are exported properly, you need to flush the spans before a function's response is sent to the client. For details on this limitation, see [Signalling function terminationï»¿](https://dt-url.net/5ta3ywp).": "Чтобы спаны экспортировались корректно, необходимо выполнить их сброс до отправки ответа функции клиенту. Подробнее об этом ограничении см. [Сигнализация завершения функции](https://dt-url.net/5ta3ywp).",
    "You can use `endHttpSpan()` and `flushSpans()` separately instead of `endHttpSpanAndFlush()` when needed.": "При необходимости можно использовать `endHttpSpan()` и `flushSpans()` раздельно вместо `endHttpSpanAndFlush()`.",
    "Flushing spans in the function's code results in longer execution times, as this operation becomes part of the function's execution logic. To avoid this, you can omit the flush operation. Spans will still be periodically exported in the background.": "Сброс спанов в коде функции увеличивает время выполнения, поскольку эта операция становится частью логики выполнения функции. Чтобы избежать этого, можно пропустить операцию сброса: спаны всё равно будут периодически экспортироваться в фоновом режиме.",
    "Because code running outside the function execution can be terminated at any time, it's discouraged by Google Cloud Functions.": "Поскольку код, выполняющийся за пределами выполнения функции, может быть завершён в любой момент, Google Cloud Functions не рекомендует такой подход.",
    "* Google Cloud Functions 1st gen": "* Google Cloud Functions 1-го поколения",
    "Background task execution after function invocation is not guaranteed without flushing spans and might result in span loss. In practice, samples have shown that not explicitly flushing spans usually still results in correctly exported spans.": "Выполнение фоновых задач после вызова функции без сброса спанов не гарантировано и может привести к потере спанов. На практике примеры показали, что отсутствие явного сброса спанов, как правило, всё равно приводит к их корректному экспорту.",
    "* Google Cloud Functions 2nd gen": "* Google Cloud Functions 2-го поколения",
    "Google Cloud Functions 2nd gen can handle multiple concurrent requests in a single function instance. The flush operation of one invocation can prolong the execution time of another function invocation.": "Google Cloud Functions 2-го поколения может обрабатывать несколько одновременных запросов в одном экземпляре функции. Операция сброса одного вызова может увеличить время выполнения другого вызова функции.",
    "Because function instances usually need to be kept idle for some time to handle multiple concurrent requests, you can disable the flushing of spans to improve performance. For details, see [Instance lifecycleï»¿](https://cloud.google.com/run/docs/container-contract#lifecycle-services).": "Поскольку экземпляры функций обычно должны некоторое время оставаться в режиме ожидания для обработки нескольких одновременных запросов, можно отключить сброс спанов для повышения производительности. Подробнее см. [Жизненный цикл экземпляра](https://cloud.google.com/run/docs/container-contract#lifecycle-services).",
    "Note that idle function instances are not guaranteed to be allocated CPU unless their [CPU allocationï»¿](https://cloud.google.com/run/docs/configuring/cpu-allocation) mode is set to `CPU always allocated`.": "Обратите внимание: простаивающим экземплярам функций не гарантировано выделение CPU, если их режим [выделения CPU](https://cloud.google.com/run/docs/configuring/cpu-allocation) не установлен в `CPU always allocated`.",
    "For details, see [Function execution timelineï»¿](https://cloud.google.com/functions/docs/concepts/execution-environment#execution-timeline).": "Подробнее см. [Временная шкала выполнения функции](https://cloud.google.com/functions/docs/concepts/execution-environment#execution-timeline).",
    "## Caveats": "## Особые замечания",
    "You need to pay special attention to cases like unhandled exceptions or function timeouts. If not handled properly, they could lead to a non-ended, and therefore non-exported, span.": "Необходимо уделять особое внимание случаям необработанных исключений или тайм-аутов функции. При ненадлежащей обработке они могут привести к незавершённому и, следовательно, неэкспортированному спану.",
    "## Dynatrace overhead": "## Накладные расходы Dynatrace",
    "* Because span export and metadata fetch take some time during cold starts, they increase the duration of the function and subsequently increase costs.": "* Поскольку экспорт спанов и получение метаданных занимают некоторое время при холодных стартах, они увеличивают продолжительность выполнения функции и, следовательно, повышают затраты.",
    "* Pay attention to infrequently invoked functions (usually with cold starts), which might require more time for the TCP handshake during span export.": "* Обратите внимание на редко вызываемые функции (как правило, с холодными стартами): им может потребоваться больше времени для TCP-рукопожатия при экспорте спанов.",
    "* Any network problem between the exporter and Dynatrace backend might also lead to unexpectedly high overhead.": "* Любые сетевые проблемы между экспортером и бэкендом Dynatrace могут также привести к неожиданно высоким накладным расходам.",
    "## Related topics": "## Связанные темы",
    "* [Set up Dynatrace on Google Cloud](/managed/ingest-from/google-cloud-platform \"Monitor Google Cloud with Dynatrace.\")": "* [Настройка Dynatrace на Google Cloud](/managed/ingest-from/google-cloud-platform \"Мониторинг Google Cloud с помощью Dynatrace.\")",
    "* [Google Cloud monitoringï»¿](https://www.dynatrace.com/technologies/google-cloud-monitoring/)": "* [Мониторинг Google Cloud](https://www.dynatrace.com/technologies/google-cloud-monitoring/)",
}

PASS = set()

build_one(REL, FILE, TRANS, PASS)
qa_one(REL, FILE)
