# -*- coding: utf-8 -*-
from _otel_canon import S, SUB, build_one, qa_one

TRANS = {
    # title / H1 (H1 appears twice in source)
    "title: Sampling with the OTel Collector": "title: Сэмплирование с помощью OTel Collector",
    "# Sampling with the OTel Collector": "# Сэмплирование с помощью OTel Collector",
    # metadata unique to this file
    "* 5-min read": "* Чтение: 5 мин",
    "* Published May 28, 2024": "* Опубликовано 28 мая 2024 г.",
    # intro (note: mojibaked em-dashes in source -> rendered as colon/comma per style)
    "A distributed application under heavy load may generate a massive amount of observability data. This data incurs generation, processing, transmission, and storage costs. However, it's often possible to use sampling—where you use only a relatively small portion of the observability data and drop the rest—to reduce costs and still effectively monitor your application.": "Распределённое приложение под высокой нагрузкой может генерировать огромный объём данных наблюдаемости. Эти данные влекут затраты на генерацию, обработку, передачу и хранение. Однако зачастую можно использовать сэмплирование, при котором используется лишь относительно небольшая часть данных наблюдаемости, а остальные отбрасываются, чтобы сократить затраты и при этом эффективно отслеживать ваше приложение.",
    "In OpenTelemetry, there are two main sampling methods:": "В OpenTelemetry есть два основных метода сэмплирования:",
    "* **Head sampling** is done within your application by the OpenTelemetry SDK, and typically involves saving a random sample of transactions.": "* **Сэмплирование на входе (head sampling)** выполняется внутри вашего приложения с помощью OpenTelemetry SDK и обычно заключается в сохранении случайной выборки транзакций.",
    "Head sampling is simple and effective, but it has important limitations. For example, because the sampling decision needs to be made at the start of the transaction, it can't be affected by anything that happens after that point.": "Сэмплирование на входе простое и эффективное, но у него есть важные ограничения. Например, поскольку решение о сэмплировании нужно принимать в начале транзакции, на него не может повлиять ничего из того, что происходит после этого момента.",
    "* **Tail sampling** is used to make sampling decisions based on information unknown at the start of the transaction.": "* **Сэмплирование на выходе (tail sampling)** используется для принятия решений о сэмплировании на основе информации, неизвестной в начале транзакции.",
    "In OpenTelemetry, tail sampling is typically done with the OTel Collector by temporarily storing the full set of monitoring data until a transaction is completed. The Collector then decides to either save or drop the transaction data based on a set of sampling policies.": "В OpenTelemetry сэмплирование на выходе обычно выполняется с помощью OTel Collector путём временного хранения полного набора данных мониторинга до завершения транзакции. Затем Collector решает, сохранить или отбросить данные транзакции, на основе набора политик сэмплирования.",
    "Because tail sampling typically is not random, it's important to ensure that any calculated metrics are unbiased. This can be done by calculating metrics from the full set of transactions, as shown below, or from a separate, randomly sampled stream.": "Поскольку сэмплирование на выходе обычно не случайно, важно убедиться, что любые вычисляемые метрики несмещённые. Этого можно добиться, вычисляя метрики из полного набора транзакций, как показано ниже, или из отдельного, случайно сэмплированного потока.",
    "The following configuration example shows how to configure a Collector instance to sample trace data and import it as an OTLP request into Dynatrace. It uses the [`spanmetrics` connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/connector/spanmetricsconnector) to compute service metrics from traces before sampling in order to ensure their accuracy.": "В следующем примере конфигурации показано, как настроить экземпляр Collector для сэмплирования данных трассировок и их импорта в виде запроса OTLP в Dynatrace. В нём используется [connector `spanmetrics`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/connector/spanmetricsconnector) для вычисления метрик сервисов из трассировок до сэмплирования, чтобы обеспечить их точность.",
    # prerequisites (unique: processors + spanmetrics connector bullet)
    "* One of the following Collector distributions with the [`transform`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/processor/transformprocessor), [`filter`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/processor/filterprocessor), and [`tail_sampling`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/processor/tailsamplingprocessor) processors, and the [`spanmetrics`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/connector/spanmetricsconnector) connector:": "* Один из следующих дистрибутивов Collector с processor `transform` ([`transform`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/processor/transformprocessor)), `filter` ([`filter`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/processor/filterprocessor)) и `tail_sampling` ([`tail_sampling`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/processor/tailsamplingprocessor)), а также connector `spanmetrics` ([`spanmetrics`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/connector/spanmetricsconnector)):",
    # distribution bullet unique to this file ("The ... distribution" wrapper)
    '+ The OpenTelemetry [Contrib](/managed/ingest-from/opentelemetry/collector#collector-contrib "Learn how to use the OpenTelemetry Collector, including the Dynatrace OTel Collector, to ingest telemetry from OpenTelemetry.") distribution': '+ Дистрибутив OpenTelemetry [Contrib](/managed/ingest-from/opentelemetry/collector#collector-contrib "Узнайте, как использовать OpenTelemetry Collector, включая Dynatrace OTel Collector, для приёма телеметрии из OpenTelemetry.")',
    # Receivers body
    "Under `receivers`, we specify the standard `otlp` receiver as active receiver component for our Collector instance and configure it to accept OTLP requests on gRPC and HTTP.": "В разделе `receivers` мы указываем стандартный receiver `otlp` в качестве активного компонента receiver для нашего экземпляра Collector и настраиваем его на приём запросов OTLP по gRPC и HTTP.",
    # Processors body
    "* [`tail_sampling`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/processor/tailsamplingprocessor) to sample distributed traces based on properties of the trace.": "* [`tail_sampling`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/processor/tailsamplingprocessor) для сэмплирования распределённых трассировок на основе свойств трассировки.",
    # Connectors body
    "Under `connectors`, we specify the [`spanmetrics` connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/connector/spanmetricsconnector) to compute service metrics from spans.": "В разделе `connectors` мы указываем [connector `spanmetrics`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/connector/spanmetricsconnector) для вычисления метрик сервисов из спанов.",
    # Service pipelines body
    "Under `service`, we assemble three pipelines:": "В разделе `service` мы собираем три конвейера:",
    "* `traces` assembles the OTLP receiver, tail sampling processor, and `otlp_http` exporter to send sampled spans to Dynatrace.": "* `traces` собирает receiver OTLP, processor сэмплирования на выходе и exporter `otlp_http` для отправки сэмплированных спанов в Dynatrace.",
    "* `traces/spanmetrics` uses the same OTLP receiver and the `spanmetrics` connector to compute service metrics from received spans, without sampling, and forwards the computed metrics to `metrics`.": "* `traces/spanmetrics` использует тот же receiver OTLP и connector `spanmetrics` для вычисления метрик сервисов из полученных спанов без сэмплирования и пересылает вычисленные метрики в `metrics`.",
    "* `metrics` uses the `transform`, `filter`, and `transform/spanmetrics` processors to format metrics for Dynatrace metric ingest before sending metrics to Dynatrace using the `otlp_http` exporter.": "* `metrics` использует processor `transform`, `filter` и `transform/spanmetrics` для форматирования метрик под приём метрик Dynatrace перед отправкой метрик в Dynatrace с помощью exporter `otlp_http`.",
    # OpenTelemetry sampling considerations
    "## OpenTelemetry sampling considerations": "## Особенности сэмплирования OpenTelemetry",
    "### Mixed-mode sampling": "### Смешанный режим сэмплирования",
    "OpenTelemetry and OneAgent use incompatible approaches to sampling that should not be mixed. If a distributed trace, which may include multiple applications and services, only partially utilizes either method, it's likely to result in inconsistent results and incomplete distributed traces. Each distributed trace should be sampled by only one of the methods to ensure it's captured in its entirety.": "OpenTelemetry и OneAgent используют несовместимые подходы к сэмплированию, которые не следует смешивать. Если распределённая трассировка, которая может включать несколько приложений и сервисов, лишь частично использует тот или иной метод, это, скорее всего, приведёт к несогласованным результатам и неполным распределённым трассировкам. Каждая распределённая трассировка должна сэмплироваться только одним из методов, чтобы гарантировать её захват целиком.",
    "### Trace-derived service metrics": "### Метрики сервисов, производные от трассировок",
    "Dynatrace trace-derived metrics are calculated from trace data after it's ingested into Dynatrace.": "Производные от трассировок метрики Dynatrace вычисляются из данных трассировок после их приёма в Dynatrace.",
    "If OpenTelemetry traces are sampled, the trace-derived metrics are calculated only from the sampled subset of trace data. This means that some trace-derived metrics might be biased or incorrect.": "Если трассировки OpenTelemetry сэмплируются, производные от трассировок метрики вычисляются только из сэмплированного подмножества данных трассировок. Это означает, что некоторые производные от трассировок метрики могут быть смещёнными или неверными.",
    "For example, a probabilistic sampler that saves 5% of traffic will result in a throughput metric that shows 5% of the actual throughput. If you use OpenTelemetry tail-based sampling to also capture 100% of slow or error traces, your service metrics will not only show incorrect throughput, but will also incorrectly bias error rates and response times.": "Например, вероятностный сэмплер, сохраняющий 5% трафика, даст метрику пропускной способности, показывающую 5% фактической пропускной способности. Если использовать сэмплирование OpenTelemetry на выходе, чтобы дополнительно захватывать 100% медленных или ошибочных трассировок, метрики сервисов не только покажут неверную пропускную способность, но и внесут некорректное смещение в доли ошибок и время отклика.",
    "To mitigate this, if you want to sample OpenTelemetry traces, you should calculate service metrics before sampling and use those metrics rather than the trace-derived metrics calculated by Dynatrace. If you're using the Collector for sampling, trace-derived metrics should be calculated by the Collector before applying sampling, or by the SDK. This can be done with the [`spanmetrics` connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/connector/spanmetricsconnector) as shown in the example above.": "Чтобы смягчить это, при сэмплировании трассировок OpenTelemetry следует вычислять метрики сервисов до сэмплирования и использовать эти метрики вместо производных от трассировок метрик, вычисляемых Dynatrace. Если для сэмплирования используется Collector, производные от трассировок метрики должны вычисляться Collector до применения сэмплирования или с помощью SDK. Этого можно добиться с помощью [connector `spanmetrics`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.151.0/connector/spanmetricsconnector), как показано в примере выше.",
    # Related topics (link text variants unique to this file)
    '* [Batch OTLP requests with the OTel Collector](/managed/ingest-from/opentelemetry/collector/use-cases/batch "Configure the OpenTelemetry Collector to send data in batches to the Dynatrace backend.")': '* [Группирование запросов OTLP с помощью OTel Collector](/managed/ingest-from/opentelemetry/collector/use-cases/batch "Настройте OpenTelemetry Collector для отправки данных группами в бэкенд Dynatrace.")',
    '* [Compute histogram summaries with the OTel Collector](/managed/ingest-from/opentelemetry/collector/use-cases/histograms "Configure the OpenTelemetry Collector to compute histogram summaries.")': '* [Вычисление сводок гистограмм с помощью OTel Collector](/managed/ingest-from/opentelemetry/collector/use-cases/histograms "Настройте OpenTelemetry Collector для вычисления сводок гистограмм.")',
    '* [Apply memory limits to the OTel Collector](/managed/ingest-from/opentelemetry/collector/use-cases/memory "Configure the OpenTelemetry Collector to respect memory limits and not use excessive system resources.")': '* [Применение ограничений памяти к OTel Collector](/managed/ingest-from/opentelemetry/collector/use-cases/memory "Настройте OpenTelemetry Collector для соблюдения ограничений памяти и предотвращения чрезмерного использования системных ресурсов.")',
    '* [Send OpenTelemetry data to multiple backends](/managed/ingest-from/opentelemetry/collector/use-cases/multi-export "Configure the OpenTelemetry Collector to send data to more than one backend.")': '* [Отправка данных OpenTelemetry в несколько бэкендов](/managed/ingest-from/opentelemetry/collector/use-cases/multi-export "Настройте OpenTelemetry Collector для отправки данных более чем в один бэкенд.")',
    **S,
}

PASS = {"### Receivers", "### Processors", "### Connectors", "### Exporters"}

if __name__ == "__main__":
    build_one(SUB, "sampling.md", TRANS, PASS)
    qa_one(SUB, "sampling.md")
