# -*- coding: utf-8 -*-
"""L4-IF.73 — ingest-from/microsoft-azure-services/azure-integrations/azure-functions/func-dynamic-plans/opentelemetry-on-azure-functions-dotnet.md"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/microsoft-azure-services/azure-integrations/azure-functions/func-dynamic-plans"

TT_OTEL_FUNC = "Мониторинг плана Consumption для Azure Functions с помощью OpenTelemetry и Dynatrace."
TT_AZURE = "Настройка и конфигурирование мониторинга для Microsoft Azure."

TRANS = {
    "title: Trace Azure Functions written in .NET": "title: Трассировка Azure Functions на .NET",
    "# Trace Azure Functions written in .NET": "# Трассировка Azure Functions на .NET",
    "* How-to guide": "* Практическое руководство",
    "* 10-min read": "* Чтение: 10 мин",
    "* Updated on Jul 31, 2024": "* Обновлено 31 июля 2024 г.",
    "## Prerequisites": "## Предварительные требования",
    f'Ensure that you have followed the **initial configuration** steps described in [Set up OpenTelemetry monitoring for Azure Functions on Consumption Plan](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-functions/func-dynamic-plans/opentelemetry-on-azure-functions "Monitor Azure Functions consumption plan with OpenTelemetry and Dynatrace.") before using the packages below.': f'Перед использованием приведённых ниже пакетов убедитесь, что выполнили шаги **начальной настройки**, описанные в разделе [Настройка мониторинга OpenTelemetry для Azure Functions в плане Consumption](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-functions/func-dynamic-plans/opentelemetry-on-azure-functions "{TT_OTEL_FUNC}").',
    ".NET version 8 or earlier": ".NET версии 8 или более ранней",
    "## Installation": "## Установка",
    "1. Add the following dependencies to your project.": "1. Добавьте в проект следующие зависимости.",
    "* Required `Dynatrace.OpenTelemetry`—provides integration of Dynatrace-specific components (for activity export and propagation) into OpenTelemetry .NET.": "* Обязательный `Dynatrace.OpenTelemetry`, обеспечивающий интеграцию компонентов Dynatrace (для экспорта activity и propagation) в OpenTelemetry .NET.",
    f"* Optional [`OpenTelemetry.Extensions.Hosting`](https://dt-url.net/w603yxv)—uses a `TracerProvider` with a dependency injection. While the latest release is supported for worker functions, in-process functions require OpenTelemetry.Extensions.Hosting version 1.0.0-rc9.5 or earlier. For details, see [Compatibility with `dotnet` (in-process) runtime](#compatibility-with-dotnet-in-process-runtime) below.": f"* Необязательный [`OpenTelemetry.Extensions.Hosting`](https://dt-url.net/w603yxv): использует `TracerProvider` с внедрением зависимостей. Последний релиз поддерживается для worker functions, однако in-process functions требуют OpenTelemetry.Extensions.Hosting версии 1.0.0-rc9.5 или более ранней. Подробнее см. раздел [Совместимость с `dotnet` (in-process) runtime](#compatibility-with-dotnet-in-process-runtime) ниже.",
    "Example commands to add dependencies": "Примеры команд для добавления зависимостей",
    "2. Additionally, depending on the runtime you use, we recommend that you use the following Azure-functions helper packages:": "2. Кроме того, в зависимости от используемого runtime рекомендуется использовать следующие вспомогательные пакеты Azure Functions:",
    "* Recommended For in-process (library) functions (`dotnet` runtime)": "* Рекомендуется для in-process (library) functions (`dotnet` runtime)",
    "To add the packages, run the command below.": "Чтобы добавить пакеты, выполните команду ниже.",
    "* Recommended For isolated aka worker functions (`dotnet-isolated` runtime)": "* Рекомендуется для isolated, то есть worker functions (`dotnet-isolated` runtime)",
    "To add the package, run the command below.": "Чтобы добавить пакет, выполните команду ниже.",
    "* Optional Alternatively, on both runtimes you can use a Dynatrace package called `Dynatrace.OpenTelemetry.Instrumentation.AzureFunctions.Core` with the following functions:": "* Необязательно. В качестве альтернативы на обоих runtime можно использовать пакет Dynatrace `Dynatrace.OpenTelemetry.Instrumentation.AzureFunctions.Core` со следующими функциями:",
    "## Compatibility with OpenTelemetry and `System.Diagnostics.DiagnosticSource` versions": "## Совместимость с версиями OpenTelemetry и `System.Diagnostics.DiagnosticSource`",
    "Periodically, we need to upgrade the minimum version of the `OpenTelemetry` NuGet package": "Периодически требуется обновлять минимальную версию NuGet-пакета `OpenTelemetry`,",
    "our components depend on, and consequently, the minimum version of the `System.Diagnostics.DiagnosticSource` library.": "от которого зависят компоненты, и соответственно минимальную версию библиотеки `System.Diagnostics.DiagnosticSource`.",
    "This table lists the compatibility between `Dynatrace.OpenTelemetry`, `OpenTelemetry`, and `System.Diagnostics.DiagnosticSource` versions.": "В таблице приведена совместимость версий `Dynatrace.OpenTelemetry`, `OpenTelemetry` и `System.Diagnostics.DiagnosticSource`.",
    "| `Dynatrace.OpenTelemetry` version | Minimum `OpenTelemetry` version | Minimum `System.Diagnostics.DiagnosticSource` version |": "| Версия `Dynatrace.OpenTelemetry` | Минимальная версия `OpenTelemetry` | Минимальная версия `System.Diagnostics.DiagnosticSource` |",
    "| --- | --- | --- |": "| --- | --- | --- |",
    "| 1.273 and earlier | 1.1.0 | 5.0.1 |": "| 1.273 и ранее | 1.1.0 | 5.0.1 |",
    "| 1.275+ | 1.3.1 | 6.0.0 |": "| 1.275+ | 1.3.1 | 6.0.0 |",
    "You don't usually need to worry about these dependencies as they're defined for you in our NuGet package. This": "Как правило, об этих зависимостях не нужно беспокоиться, так как они определены в NuGet-пакете. Это",
    "means that when you upgrade `Dynatrace.OpenTelemetry`, NuGet might implicitly upgrade your `OpenTelemetry` or": "означает, что при обновлении `Dynatrace.OpenTelemetry` NuGet может неявно обновить `OpenTelemetry` или",
    "`System.Diagnostics.DiagnosticSource` version if you are currently on an earlier one.": "`System.Diagnostics.DiagnosticSource` до более новой версии, если текущая устарела.",
    "## Compatibility with `dotnet` (in-process) runtime": "## Совместимость с `dotnet` (in-process) runtime",
    "For the `dotnet` (in-process) runtime, only certain versions of OpenTelemetry are compatible with certain versions of the Azure runtime:": "Для `dotnet` (in-process) runtime только определённые версии OpenTelemetry совместимы с определёнными версиями Azure runtime:",
    "* Azure Functions `dotnet` runtime v3 is not compatible with OpenTelemetry.": "* Azure Functions `dotnet` runtime v3 не совместим с OpenTelemetry.",
    "* Azure Functions `dotnet` runtime v4 is compatible with OpenTelemetry 1.3.x (`System.Diagnostics.DiagnosticSource` 6).": "* Azure Functions `dotnet` runtime v4 совместим с OpenTelemetry 1.3.x (`System.Diagnostics.DiagnosticSource` 6).",
    "When using the `dotnet` (in-process) runtime, functions are loaded into the same CLR as the runtime. For instrumentation to work properly, the same `System.Diagnostics.DiagnosticSource` assembly needs to be used in the runtime and by the OpenTelemetry dependencies of the function. Symptoms of incompatible combinations may include your function failing to build, failing to load at runtime, or producing incomplete traces.": "При использовании `dotnet` (in-process) runtime функции загружаются в тот же CLR, что и сам runtime. Для корректной работы инструментирования необходимо, чтобы в runtime и в зависимостях OpenTelemetry функции использовалась одна и та же сборка `System.Diagnostics.DiagnosticSource`. Признаки несовместимых комбинаций: сбой сборки функции, сбой загрузки во время выполнения или неполные трассировки.",
    "## Example using the dotnet (in-process) runtime": "## Пример с использованием dotnet (in-process) runtime",
    "Your `Startup.cs` could look as follows:": "Файл `Startup.cs` может выглядеть следующим образом:",
    "An instrumented in-process function could look like this:": "Пример инструментированной in-process function:",
    "Additionally, you need to modify `host.json` to allow logging for `Dynatrace.OpenTelemetry`.": "Кроме того, необходимо изменить `host.json`, чтобы разрешить ведение журнала для `Dynatrace.OpenTelemetry`.",
    f'Note that this does not enable logging unless [explicitly configured](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-functions/func-dynamic-plans/opentelemetry-on-azure-functions "Monitor Azure Functions consumption plan with OpenTelemetry and Dynatrace."). See [InitializeLogging](#initializelogging).': f'Обратите внимание, что это не активирует ведение журнала, если оно не [настроено явно](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-functions/func-dynamic-plans/opentelemetry-on-azure-functions "{TT_OTEL_FUNC}"). См. [InitializeLogging](#initializelogging).',
    "## Example using the dotnet-isolated runtime": "## Пример с использованием dotnet-isolated runtime",
    "The following examples use the [built-in HTTP model](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#built-in-http-model) of Azure functions and do **not** apply to functions using the [ASP.NET core integration](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration) of isolated Azure functions. See the chapter about [`ASP.NET core integration`](#asp-net-core-integration) below.": "Приведённые примеры используют [встроенную HTTP-модель](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#built-in-http-model) Azure Functions и **не** применяются к функциям, использующим [ASP.NET core integration](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration) изолированных Azure Functions. См. раздел [`ASP.NET core integration`](#asp-net-core-integration) ниже.",
    "Your `Program.cs` could look as follows:": "Файл `Program.cs` может выглядеть следующим образом:",
    "OpenTelemetry versions earlier than 1.4": "Версии OpenTelemetry ранее 1.4",
    "OpenTelemetry version 1.4+": "OpenTelemetry версии 1.4+",
    "No additional code is needed to instrument functions; everything is handled by the middleware.": "Дополнительный код для инструментирования функций не требуется: всё обрабатывается middleware.",
    "## ASP.NET core integration (isolated runtime)": "## ASP.NET core integration (isolated runtime)",
    "If you create a new project for Azure function .NET8 or later—for example, using Visual Studio template—then, it'll add [ASP.NET core integration](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration) in Azure Function by default.": "При создании нового проекта для Azure Function .NET8 или более поздней версии, например с помощью шаблона Visual Studio, по умолчанию добавляется [ASP.NET core integration](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration) в Azure Function.",
    "To enable function tracing, you need to use only the `ConfigureFunctionsWebApplication` method instead of `ConfigureFunctionsWorkerDefaults` in your initialization code given in [`ASP.NET core integration`](#asp-net-core-integration). The initialization code may look as follows:": "Чтобы включить трассировку функций, нужно использовать метод `ConfigureFunctionsWebApplication` вместо `ConfigureFunctionsWorkerDefaults` в коде инициализации, приведённом в [`ASP.NET core integration`](#asp-net-core-integration). Код инициализации может выглядеть следующим образом:",
    "## Technical details": "## Технические сведения",
    "### `InitializeLogging`": "### `InitializeLogging`",
    f"* Calling `InitializeLogging` is required even if you don't plan to enable logging, and the actual log messages won't be logged even after calling this method, unless [configured](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-functions/func-dynamic-plans/opentelemetry-on-azure-functions \"Monitor Azure Functions consumption plan with OpenTelemetry and Dynatrace.\").": f'* Вызов `InitializeLogging` обязателен, даже если вести журнал не планируется. Реальные сообщения журнала не будут логироваться после вызова этого метода, если только не [настроено](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-functions/func-dynamic-plans/opentelemetry-on-azure-functions "{TT_OTEL_FUNC}").',
    "* If you use the [`dotnet-isolated` runtime](https://dt-url.net/2i23yrm) (out-of-process, worker functions), you need to call `InitializeLogging` in your `Main` method before calling `AddDynatrace`. You can pass `null` as `loggerFactory`, so that, if enabled, logging can use `Console.Out`/`Console.Error`. This is automatically forwarded to AppInsights for the `dotnet-isolated` runtime.": "* При использовании [`dotnet-isolated` runtime](https://dt-url.net/2i23yrm) (out-of-process, worker functions) нужно вызвать `InitializeLogging` в методе `Main` перед вызовом `AddDynatrace`. Можно передать `null` в качестве `loggerFactory`, чтобы при включённом ведении журнала использовались `Console.Out`/`Console.Error`. Для `dotnet-isolated` runtime это автоматически перенаправляется в AppInsights.",
    "* If you have specific requirements, you can also pass any custom `LoggingFactory`.": "* При наличии особых требований можно также передать произвольный `LoggingFactory`.",
    "* For the [`dotnet` runtime](https://dt-url.net/2r43yf7) (in-process, class-library), sending logs to AppInsights requires using an `ILogger` or `ILoggerFactory` injected into the function with a dependency injection. Thus, you shouldn't use `null` as an argument for the `loggerFactory` parameter, but call `InitializeLogging` the first time any function in your Function App is invoked. To get the `ILoggerFactory`, simply add a parameter of that type.": "* Для [`dotnet` runtime](https://dt-url.net/2r43yf7) (in-process, class-library) отправка журналов в AppInsights требует использования `ILogger` или `ILoggerFactory`, внедрённых в функцию через dependency injection. Поэтому не следует передавать `null` в качестве аргумента параметра `loggerFactory`: нужно вызывать `InitializeLogging` при первом вызове любой функции в Function App. Чтобы получить `ILoggerFactory`, достаточно добавить параметр соответствующего типа.",
    "* If you use the `ILoggerFactory` provided by Azure Functions, you also need to modify `host.json` to enable logging there. We recommend that you always use the `debug` log-level in `host.json`, as the actual log messages handed to the ILogger are separately configured in the Dynatrace configuration.": "* При использовании `ILoggerFactory`, предоставляемого Azure Functions, также необходимо изменить `host.json`, чтобы включить там ведение журнала. Рекомендуется всегда использовать уровень журнала `debug` в `host.json`, поскольку реальные сообщения, передаваемые ILogger, настраиваются отдельно в конфигурации Dynatrace.",
    "### `AddDynatrace`": "### `AddDynatrace`",
    f"* `AddDynatrace` is an extension method to OpenTelemetry's `TracerProvider`. It requires `using Dynatrace.OpenTelemetry`. Currently, there aren't any additional parameters for this function, as configuration is read from environment variables and a `dtconfig.json` file. For details, see [Set up OpenTelemetry monitoring for Azure Functions on Consumption Plan](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-functions/func-dynamic-plans/opentelemetry-on-azure-functions \"Monitor Azure Functions consumption plan with OpenTelemetry and Dynatrace.\").": f'* `AddDynatrace` является методом расширения `TracerProvider` OpenTelemetry. Для его использования необходим `using Dynatrace.OpenTelemetry`. На данный момент дополнительных параметров у этой функции нет: конфигурация считывается из переменных окружения и файла `dtconfig.json`. Подробнее см. [Настройка мониторинга OpenTelemetry для Azure Functions в плане Consumption](/managed/ingest-from/microsoft-azure-services/azure-integrations/azure-functions/func-dynamic-plans/opentelemetry-on-azure-functions "{TT_OTEL_FUNC}").',
    "* `AddDynatrace` mainly adds an `ActivityProcessor` to the `TracerProvider` that will send all activities to Dynatrace. This extension:": "* `AddDynatrace` преимущественно добавляет `ActivityProcessor` в `TracerProvider`, который отправляет все activity в Dynatrace. Это расширение:",
    "+ Sets the resources required by Dynatrace. Due to [an issue with the OpenTelemetry .NET SDK](https://github.com/open-telemetry/opentelemetry-dotnet/issues/2909), this will override any existing resources. If you need custom resources, you need to call `SetResourceBuilder` on the `TracerProvider` *after* `AddDynatrace`. Be aware that this will override the resources configured by `AddDynatrace` and you need to readd them as part of the same `SetResourceBuilder` call. You can do this by calling the OpenTelemetry SDK's `AddTelemetrySdk` extension method on the `ResourceBuilder`.": "+ Устанавливает ресурсы, необходимые Dynatrace. Из-за [проблемы с OpenTelemetry .NET SDK](https://github.com/open-telemetry/opentelemetry-dotnet/issues/2909) это переопределяет существующие ресурсы. Если нужны пользовательские ресурсы, необходимо вызвать `SetResourceBuilder` на `TracerProvider` *после* `AddDynatrace`. Обратите внимание, что это переопределит ресурсы, настроенные `AddDynatrace`, и их нужно добавить заново в том же вызове `SetResourceBuilder`. Для этого вызовите метод расширения `AddTelemetrySdk` из OpenTelemetry SDK на `ResourceBuilder`.",
    "+ Exchanges the global `Propagators.DefaultTextMapPropagator` with a custom one that is based on the default W3C-format, but does additional processing of `tracestate` and additional Dynatrace-specific HTTP headers. The baggage propagator is also enabled, as is default for OpenTelemetry .NET. There's currently no way to disable it. Using another propagator isn't supported and will lead to missing links in the distributed traces.": "+ Заменяет глобальный `Propagators.DefaultTextMapPropagator` на пользовательский, основанный на стандартном формате W3C, но выполняющий дополнительную обработку `tracestate` и специфичных для Dynatrace HTTP-заголовков. Также включается propagator baggage, что является стандартным для OpenTelemetry .NET. Отключить его в настоящее время невозможно. Использование другого propagator не поддерживается и приведёт к потере связей в распределённых трассировках.",
    "The following minimal snippet might be used to initialize a `TracerProvider` with `AddDynatrace`:": "Следующий минимальный фрагмент можно использовать для инициализации `TracerProvider` с помощью `AddDynatrace`:",
    "### `AzureFunctionsCoreInstrumentation.Trace`/`TraceAsync`": "### `AzureFunctionsCoreInstrumentation.Trace`/`TraceAsync`",
    "This is the low-level instrumentation function provided in the `Dynatrace.OpenTelemetry.Instrumentation.AzureFunctions.Core` package. You usually shouldn't use these, but instead use the runtime-specific helpers, as in the [examples above](#helper-usage-examples).": "Это низкоуровневая функция инструментирования из пакета `Dynatrace.OpenTelemetry.Instrumentation.AzureFunctions.Core`. Как правило, использовать её не рекомендуется: вместо неё используйте вспомогательные средства, специфичные для runtime, как в [приведённых выше примерах](#helper-usage-examples).",
    "This function creates and starts a `System.Diagnostics.Activity`. It runs the handler function argument, then stops `Activity` and records any exception on it. An example usage could look like this:": "Функция создаёт и запускает `System.Diagnostics.Activity`, выполняет переданный обработчик, затем останавливает `Activity` и фиксирует на ней любое исключение. Пример использования:",
    "The parent `ActivityContext` must be extracted from the HTTP headers using the `Propagators.DefaultTextMapPropagator`, which `AddDynatrace` initializes. If you don't pass any parent, a trace root span will be created (`Activity.Current` won't be used).": "Родительский `ActivityContext` необходимо извлечь из HTTP-заголовков с помощью `Propagators.DefaultTextMapPropagator`, инициализируемого `AddDynatrace`. Если родительский контекст не передан, будет создан корневой спан трассировки (`Activity.Current` использоваться не будет).",
    "This is how a parent could be manually extracted with in-process functions for use with `AzureFunctionsCoreInstrumentation.Trace`/`TraceAsync` when not using the ASP.NET core instrumentation:": "Пример ручного извлечения родительского контекста для in-process functions при использовании `AzureFunctionsCoreInstrumentation.Trace`/`TraceAsync` без ASP.NET core instrumentation:",
    "For worker functions, the code can become more complex because in addition to HTTP headers, you may want to": "Для worker functions код может усложниться, так как помимо HTTP-заголовков можно (но не обязательно) использовать",
    "(but don't have to) use the W3C TraceContext provided in the `FunctionContext`:": "W3C TraceContext из `FunctionContext`:",
    "## Instrumenting `HttpClient` calls (outgoing HTTP requests)": "## Инструментирование вызовов `HttpClient` (исходящие HTTP-запросы)",
    "A very common need is to trace outgoing HTTP requests. This can be achieved by using the [`OpenTelemetry.Instrumentation.Http` NuGet package](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Http).": "Трассировка исходящих HTTP-запросов является частой задачей. Её можно решить с помощью [NuGet-пакета `OpenTelemetry.Instrumentation.Http`](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Http).",
    "The instrumentation then has to be added to your `TracerProvider` setup by calling `AddHttpClientInstrumentation`, for example, in `Program.cs`:": "Инструментирование нужно добавить в настройку `TracerProvider`, вызвав `AddHttpClientInstrumentation`, например в `Program.cs`:",
    "Using a request filter as in the example above is highly recommended, as otherwise, depending on your Function Apps configuration, you might observe a large number of periodic requests to `https://rt.services.visualstudio.com/QuickPulseService.svc/ping` or similar URLs.": "Настоятельно рекомендуется использовать фильтр запросов, как в примере выше: в противном случае, в зависимости от конфигурации Function Apps, может наблюдаться большое количество периодических запросов на `https://rt.services.visualstudio.com/QuickPulseService.svc/ping` или аналогичные URL.",
    "Alternatively, you can [disable telemetry dynamically](https://dt-url.net/95038ca).": "Кроме того, можно [динамически отключить телеметрию](https://dt-url.net/95038ca).",
    "We recommend to use the helper function `AzureFunctionsCoreInstrumentation.FilterExternalTelemetry` which is available in package `Dynatrace.OpenTelemetry.Instrumentation.AzureFunctions.Core` since version 1.267. In earlier versions, you can use the following filter instead:": "Рекомендуется использовать вспомогательную функцию `AzureFunctionsCoreInstrumentation.FilterExternalTelemetry`, доступную в пакете `Dynatrace.OpenTelemetry.Instrumentation.AzureFunctions.Core` начиная с версии 1.267. В более ранних версиях вместо неё можно использовать следующий фильтр:",
    "Because of an [Azure Functions runtime issue](https://github.com/Azure/azure-functions-host/issues/7278), the HTTP instrumentation won't work on Azure Functions in-process version 3.x.": "Из-за [проблемы Azure Functions runtime](https://github.com/Azure/azure-functions-host/issues/7278) HTTP-инструментирование не работает в Azure Functions in-process версии 3.x.",
    "The underlying issue can also affect other instrumentations. Therefore, we do not recommend using in-process version 3 functions.": "Эта же проблема может затронуть другие инструментирования. Поэтому не рекомендуется использовать in-process functions версии 3.",
    "## Related topics": "## Связанные темы",
    f'* [Set up Dynatrace on Microsoft Azure](/managed/ingest-from/microsoft-azure-services "Set up and configure monitoring for Microsoft Azure.")': f'* [Настройка Dynatrace в Microsoft Azure](/managed/ingest-from/microsoft-azure-services "{TT_AZURE}")',
}

PASS = {
    "+ `Dynatrace.OpenTelemetry.Instrumentation.AzureFunctions`",
    "+ `OpenTelemetry.Instrumentation.AspNetCore`",
    "+ `Dynatrace.OpenTelemetry.Instrumentation.AzureFunctions.Worker`",
    "+ [`AzureFunctionsCoreInstrumentation.Trace`](#manual-trace-instrumentation)",
    "+ [`AzureFunctionsCoreInstrumentation.TraceAsync`](#manual-trace-instrumentation)",
}

if __name__ == "__main__":
    build_one(REL, "opentelemetry-on-azure-functions-dotnet.md", TRANS, PASS)
    qa_one(REL, "opentelemetry-on-azure-functions-dotnet.md")
