# -*- coding: utf-8 -*-
"""L4-IF.72 — ingest-from/extensions/.../addon-for-vscode/development-assistance.md"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/extensions/develop-your-extensions/addon-for-vscode"

TRANS = {
    "* Explanation": "* Пояснение",
    "* 10-min read": "* Чтение: 10 мин",
    "* Published Jun 16, 2025": "* Опубликовано 16 июня 2025 г.",
    "**Dynatrace Extensions** leverages the full power of your VS Code editor to help you create better extensions faster.": "**Dynatrace Extensions** использует все возможности редактора VS Code, чтобы помочь создавать более качественные расширения быстрее.",
    "Read on to learn how to make the most out of these features.": "Читайте дальше, чтобы узнать, как максимально эффективно использовать эти функции.",
    "## Feature overview": "## Обзор функций",
    "| Feature type | Description |": "| Тип функции | Описание |",
    "| --- | --- |": "| --- | --- |",
    "| [Code completions](#code-completions) | Suggestions for auto-completing words or fields of the manifest |": "| [Дополнение кода](#code-completions) | Предложения по автодополнению слов или полей манифеста |",
    "| [Code actions](#code-actions) | Commands generating or editing the content of your extension's manifest |": "| [Действия с кодом](#code-actions) | Команды для создания или редактирования содержимого манифеста расширения |",
    "| [Code lens](#code-lens) | Additional commands to interact with extension data |": "| [Code lens](#code-lens) | Дополнительные команды для взаимодействия с данными расширения |",
    "| [Fast development mode](#fast-development-mode) | A workflow focused on speed of delivery |": "| [Режим быстрой разработки](#fast-development-mode) | Рабочий процесс, ориентированный на скорость доставки |",
    "| [Diagnostics](#diagnostics) | Additional diagnostics beyond simple schema validation |": "| [Диагностика](#diagnostics) | Дополнительная диагностика помимо базовой проверки схемы |",
    "## Code completions": "## Дополнение кода",
    "Code completions or suggestions happen at key points within the extension manifest. Either automatically or on-demand (using Ctrl + Space), these offer known values that can be inserted at the location of your cursor.": "Дополнение кода или подсказки срабатывают в ключевых точках манифеста расширения. В автоматическом режиме или по запросу (Ctrl + Space) предлагаются известные значения, которые можно вставить в позицию курсора.",
    "### Implemented triggers": "### Реализованные триггеры",
    "| Keyword trigger | Effects |": "| Ключевое слово-триггер | Эффекты |",
    "| On `fromType:` or `toType:` inside `topology.relationships` list items | Browse built-in and custom entity types |": "| При `fromType:` или `toType:` внутри элементов списка `topology.relationships` | Просмотр встроенных и пользовательских типов сущностей |",
    "| On `sourceAttribute:` inside `mappingRules` list items of topology relationships | Browse entity attributes (entity needs to be present in the `fromType` attribute) |": "| При `sourceAttribute:` внутри элементов списка `mappingRules` топологических связей | Просмотр атрибутов сущности (сущность должна присутствовать в атрибуте `fromType`) |",
    "| On `destinationAttribute:` inside `mappingRules` list items of topology relationships | Browse entity attributes (entity needs to be present in `toType` attribute) |": "| При `destinationAttribute:` внутри элементов списка `mappingRules` топологических связей | Просмотр атрибутов сущности (сущность должна присутствовать в атрибуте `toType`) |",
    "| On `entityType:` and `entityTypes:` | Browse relevant entity types |": "| При `entityType:` и `entityTypes:` | Просмотр соответствующих типов сущностей |",
    "| On `key:` (of attributes inside screen properties) | Attributes are suggested from topology and built-in values |": "| При `key:` (атрибутов внутри свойств экрана) | Атрибуты предлагаются из топологии и встроенных значений |",
    "| On `entitySelectorTemplate:` | Use Ctrl + Space to trigger completions as you build your selector or choose one of the pre-built selectors (from relationships seen in your manifest) |": "| При `entitySelectorTemplate:` | Используйте Ctrl + Space для вызова дополнений при построении селектора или выберите один из готовых селекторов (из связей, видимых в манифесте) |",
    "| On `iconPattern:` (within topology rules) or `icon:` (within staticContent header) | Browse available Barista icon codes |": "| При `iconPattern:` (в правилах топологии) или `icon:` (в заголовке staticContent) | Просмотр доступных кодов иконок Barista |",
    "| On `key:` (of cards in `screens`, either in layout or individual lists) | Browse keys of cards defined but not yet utilized |": "| При `key:` (карточек в `screens`, как в макете, так и в отдельных списках) | Просмотр ключей определённых, но ещё не используемых карточек |",
    "| On `value:`, for metrics and dimensions of a Prometheus extension | Browse metrics and dimensions scraped using the Prometheus code lens |": "| При `value:` для метрик и измерений расширения Prometheus | Просмотр метрик и измерений, собранных с помощью Prometheus code lens |",
    "| On `description:` (in the `metrics` section of the manifest) | For those metrics that have been scraped using the Prometheus code lens, add the description from the scraped data |": "| При `description:` (в разделе `metrics` манифеста) | Для метрик, собранных с помощью Prometheus code lens, добавляет описание из собранных данных |",
    "## Code actions": "## Действия с кодом",
    "Code actions happen on key lines of your extension manifest. Your editor will automatically show a lightbulb icon": "Действия с кодом срабатывают на ключевых строках манифеста расширения. Редактор автоматически отображает значок лампочки",
    "whenever actions are relevant to the clicked line. Typically these will generate and insert content into": "когда действия применимы к выбранной строке. Как правило, они создают и вставляют содержимое в",
    "your extension manifest or fix issues highlighted by **Dynatrace Extensions**.": "манифест расширения или исправляют проблемы, выделенные **Dynatrace Extensions**.",
    "### Currently implemented triggers": "### Текущие реализованные триггеры",
    "| Action trigger | Effects |": "| Триггер действия | Эффекты |",
    "| Inside `propertiesCard` when clicking on properties | Automatically add properties for the entity's attributes and relations |": "| Внутри `propertiesCard` при нажатии на свойства | Автоматически добавляет свойства для атрибутов и связей сущности |",
    "| Inside `entitiesListCards` when clicking on columns | Automatically add columns for the listed entity's attributes and relations |": "| Внутри `entitiesListCards` при нажатии на столбцы | Автоматически добавляет столбцы для атрибутов и связей перечисленной сущности |",
    "| Inside `chartsCards` and `entitiesListCards` when clicking on charts inside a card | Automatically add charts for metrics that aren't already in the card |": "| Внутри `chartsCards` и `entitiesListCards` при нажатии на диаграммы внутри карточки | Автоматически добавляет диаграммы для метрик, которых ещё нет в карточке |",
    "| Inside `graphChartConfig` when clicking on metrics | Add more metrics to your chart that aren't used within the surrounding card |": "| Внутри `graphChartConfig` при нажатии на метрики | Добавляет дополнительные метрики в диаграмму, которые не используются в окружающей карточке |",
    "| Inside `screens` when clicking on `chartsCards` | Automatically add chart cards for entire feature sets of metrics |": "| Внутри `screens` при нажатии на `chartsCards` | Автоматически добавляет карточки с диаграммами для целых наборов функций метрик |",
    "| Inside `screens` when clicking on `entitiesListCards` | Automatically add cards for listing this entity as well as the related ones |": "| Внутри `screens` при нажатии на `entitiesListCards` | Автоматически добавляет карточки для перечисления данной сущности и связанных с ней |",
    "| When clicking on `metrics` within the Prometheus data source | Automatically add details from a [scraped Prometheus endpoint](#prometheus) |": "| При нажатии на `metrics` в источнике данных Prometheus | Автоматически добавляет сведения из [собранного эндпоинта Prometheus](#prometheus) |",
    "| On `screens` | Automatically generate entire unified analysis screens for your entities |": "| На `screens` | Автоматически создаёт полные экраны унифицированного анализа для сущностей |",
    "| Inside `entitiesListCards` when clicking on `filtering` | Insert entire filtering blocks with a default filter by name |": "| Внутри `entitiesListCards` при нажатии на `filtering` | Вставляет целые блоки фильтрации с фильтром по умолчанию по имени |",
    "| Inside `entitiesListCards` and inside `filtering`, when clicking on `filters` | Insert individual filter for the entity's attributes |": "| Внутри `entitiesListCards` и внутри `filtering` при нажатии на `filters` | Вставляет отдельный фильтр для атрибутов сущности |",
    "| Inside `screens` when clicking on `actions` | Insert global actions to configure the extension |": "| Внутри `screens` при нажатии на `actions` | Вставляет глобальные действия для настройки расширения |",
    "| Inside `actions` when clicking on `actions` | Insert an action expression to configure the extension |": "| Внутри `actions` при нажатии на `actions` | Вставляет выражение действия для настройки расширения |",
    "## Code lens": "## Code lens",
    "Code lenses are actionable, contextual information interspersed with your code. For **Dynatrace Extensions**, these can help trigger": "Code lens: применимая контекстная информация, встроенная в код. В **Dynatrace Extensions** они помогают запускать",
    "code-related actions to your Dynatrace environment or other external endpoints.": "действия, связанные с кодом, в среде Dynatrace или на других внешних эндпоинтах.",
    "### Metric selectors": "### Селекторы метрик",
    "The lens appears automatically wherever `metricSelector` and shows:": "Lens появляется автоматически везде, где встречается `metricSelector`, и отображает:",
    "* Query data - an action that runs the metric selector query and visualizes its results": "* Query data: действие, которое выполняет запрос селектора метрик и визуализирует его результаты",
    "* Validate selector - an action to verify this selector against your Dynatrace environment": "* Validate selector: действие для проверки селектора в среде Dynatrace",
    "* An icon representing the last validation status for this selector. You can hover over it for more details": "* Значок, показывающий статус последней проверки данного селектора. Наведите курсор для получения подробностей",
    "Metric selector results are displayed within a separate metric panel.": "Результаты селектора метрик отображаются в отдельной панели метрик.",
    "Any errors from querying your environment are displayed in the Dynatrace output panel (by default at the bottom of your editor).": "Любые ошибки при запросе среды отображаются в панели вывода Dynatrace (по умолчанию внизу редактора).",
    "### Entity selectors": "### Селекторы сущностей",
    "The lens appears automatically wherever `entitySelector` is mentioned and shows:": "Lens появляется автоматически везде, где упоминается `entitySelector`, и отображает:",
    "* Query data - an action that runs the entity selector query and visualizes its results": "* Query data: действие, которое выполняет запрос селектора сущностей и визуализирует его результаты",
    "* Validate selector - an action to verify this selector against your Dynatrace environment": "* Validate selector: действие для проверки селектора в среде Dynatrace",
    "* An icon representing the last validation status for this selector. You can hover over it for more details": "* Значок, показывающий статус последней проверки данного селектора. Наведите курсор для получения подробностей",
    "Entity selector results, as well as any errors, are displayed within the Dynatrace output panel (by default at the bottom of your editor).": "Результаты селектора сущностей, а также любые ошибки отображаются в панели вывода Dynatrace (по умолчанию внизу редактора).",
    "### Prometheus": "### Prometheus",
    "The lens appears automatically when the Prometheus data source is defined and shows:": "Lens появляется автоматически, когда определён источник данных Prometheus, и отображает:",
    "* Scrape data - an action that connects to a Prometheus scraper endpoint and collects its data": "* Scrape data: действие, которое подключается к эндпоинту сборщика Prometheus и собирает его данные",
    "* Edit config - an action that allows you to make changes to the connected Prometheus endpoint": "* Edit config: действие, позволяющее вносить изменения в подключённый эндпоинт Prometheus",
    "* Text indicating the status of the last scrape action, such as the timestamp and number of metrics scraped": "* Текст, показывающий статус последнего сбора данных: временную метку и количество собранных метрик",
    "After the data has been scraped, this can be used with [Code actions](#code-actions) to:": "После сбора данных их можно использовать с [действиями с кодом](#code-actions) для:",
    "* insert metric definitions in the `prometheus` section of the manifest": "* вставки определений метрик в раздел `prometheus` манифеста",
    "* insert dimensions in the `prometheus` section of the manifest": "* вставки измерений в раздел `prometheus` манифеста",
    "* insert metric metadata in the `metrics` section of the manifest": "* вставки метаданных метрик в раздел `metrics` манифеста",
    "### Windows Management Interface (WMI) queries": "### Запросы Windows Management Interface (WMI)",
    "The lens appears automatically over queries inside the WMI data source definition and shows:": "Lens появляется автоматически над запросами внутри определения источника данных WMI и отображает:",
    "* Run WMI Query: an action that runs your query against the local Windows machine": "* Run WMI Query: действие, которое выполняет запрос к локальной машине Windows",
    "* Text indicating the summary of the query results (i.e., how many object instances were found)": "* Текст с сводкой результатов запроса (то есть количество найденных экземпляров объектов)",
    "The full results of running the WMI query are displayed in a separate panel. After a query is run, you can use the results with [Code completions](#code-completions).": "Полные результаты выполнения запроса WMI отображаются в отдельной панели. После выполнения запроса результаты можно использовать с [дополнением кода](#code-completions).",
    "### Unified analysis screens": "### Экраны унифицированного анализа",
    "The lens appears automatically over entity type definitions inside the `screens` element of the manifest": "Lens появляется автоматически над определениями типов сущностей внутри элемента `screens` манифеста",
    "and shows:": "и отображает:",
    '* Open List View: an action to open a browser window to this entity\'s [Unified analysis list view](/managed/ingest-from/extend-dynatrace/extend-ui/unified-analysis#page-types "Extend the Dynatrace web UI using entity-tailored unified analysis pages.")': '* Open List View: действие для открытия браузера с [представлением списка унифицированного анализа](/managed/ingest-from/extend-dynatrace/extend-ui/unified-analysis#page-types "Расширяйте веб-интерфейс Dynatrace с помощью страниц унифицированного анализа, адаптированных для конкретных сущностей.") данной сущности',
    '* Open Details view: an action to open a browser window to this entity\'s [Unified analysis details view](/managed/ingest-from/extend-dynatrace/extend-ui/unified-analysis#page-types "Extend the Dynatrace web UI using entity-tailored unified analysis pages.")': '* Open Details view: действие для открытия браузера с [представлением сведений унифицированного анализа](/managed/ingest-from/extend-dynatrace/extend-ui/unified-analysis#page-types "Расширяйте веб-интерфейс Dynatrace с помощью страниц унифицированного анализа, адаптированных для конкретных сущностей.") данной сущности',
    "A 404 response code is expected if your entity type does exist yet.": "Код ответа 404 ожидается, если тип сущности ещё не существует.",
    "## Fast development mode": "## Режим быстрой разработки",
    "Fast development mode is a workflow designed to allow advanced developers to gain immediate feedback on the current state of their extension and minimize the steps and time it takes to see updates in their connected Dynatrace environment.": "Режим быстрой разработки: рабочий процесс, позволяющий опытным разработчикам получать немедленную обратную связь о текущем состоянии расширения и сокращать количество шагов и время, необходимое для просмотра обновлений в подключённой среде Dynatrace.",
    "### How does it work?": "### Как это работает?",
    "When enabled, every time the extension manifest saves, the extension version automatically increments, and the extension is packaged, signed, and uploaded to your connected environment. The workflow is **hands-free**, so if the maximum number of extension versions is reached, one will be removed automatically so the upload can succeed.": "При включении каждый раз при сохранении манифеста расширения версия расширения автоматически увеличивается, расширение упаковывается, подписывается и загружается в подключённую среду. Рабочий процесс **полностью автоматизирован**: при достижении максимального количества версий расширения одна из них будет удалена автоматически, чтобы загрузка прошла успешно.",
    "An accompanying status bar confirms the mode is active and displays the status of the last attempted build.": "Сопутствующая строка состояния подтверждает активность режима и отображает статус последней попытки сборки.",
    "With this workflow, pre-upload validation is skipped in favor of speed, and any issues are communicated immediately via an output channel.": "В этом рабочем процессе предварительная проверка перед загрузкой пропускается в пользу скорости, а все проблемы немедленно сообщаются через канал вывода.",
    "When developing your static assets, such as the unified analysis screens, this mode is the quickest way": "При разработке статических ресурсов, например экранов унифицированного анализа, этот режим является самым быстрым способом",
    "to cycle through a variety of changes before finding your ideal configuration.": "перебрать различные изменения перед нахождением оптимальной конфигурации.",
    "## Diagnostics": "## Диагностика",
    "Often, perfectly valid YAML still produces a manifest that causes issues when we upload the": "Нередко абсолютно корректный YAML создаёт манифест, который вызывает проблемы при загрузке",
    "extension to Dynatrace or later when it tries to run. Many of these situations can be caught early, and **Dynatrace Extensions** aims to bring these to light so you can fix them and reduce the number": "расширения в Dynatrace или при его последующем выполнении. Многие из таких ситуаций можно выявить заблаговременно, и **Dynatrace Extensions** стремится сделать их явными, чтобы можно было исправить и сократить количество",
    "of failed deployment attempts.": "неудачных попыток развёртывания.",
    "### How do custom diagnostics work?": "### Как работает пользовательская диагностика?",
    "On every edit of your extension manifest, the diagnostics suite will trigger an update of all diagnostic": "При каждом редактировании манифеста расширения набор диагностических инструментов запускает обновление всех диагностических",
    "items applicable to that file. Based on findings, relevant content is highlighted within the manifest, and": "элементов, применимых к данному файлу. По результатам проверки соответствующее содержимое выделяется в манифесте, а",
    "hovering over the highlight will provide more details about the issue.": "наведение курсора на выделенный фрагмент предоставляет подробности о проблеме.",
    "Some issues may provide a **Quick fix** link as part of the hover information. If this is available, it will": "Для некоторых проблем в составе информации при наведении курсора может присутствовать ссылка **Quick fix**. При её наличии",
    "trigger a content change of the document to resolve the highlighted issue.": "она инициирует изменение содержимого документа для устранения выделенной проблемы.",
    "Diagnostic severities:": "Уровни серьёзности диагностики:",
    '* `Error` - these findings are highlighted in red and represent issues that would break your extension when deployed. The [Build command](/managed/ingest-from/extensions/develop-your-extensions/addon-for-vscode/commands#build "Overview of all the commands available within Dynatrace Extensions") won\'t work if `Error` severity diagnostics are in your manifest.': '* `Error`: эти результаты выделяются красным и представляют проблемы, которые нарушат работу расширения при развёртывании. [Команда Build](/managed/ingest-from/extensions/develop-your-extensions/addon-for-vscode/commands#build "Обзор всех команд, доступных в Dynatrace Extensions") не будет работать, если в манифесте есть диагностика уровня `Error`.',
    "* `Warning` - these findings are highlighted in yellow and represent issues that would not stop an extension from functioning but may still produce undesired behaviors.": "* `Warning`: эти результаты выделяются жёлтым и представляют проблемы, которые не остановят работу расширения, но могут вызывать нежелательное поведение.",
    "### Currently implemented diagnostics": "### Текущие реализованные диагностики",
    "| Code | Severity | What does it mean? |": "| Код | Серьёзность | Что это означает? |",
    "| --- | --- | --- |": "| --- | --- | --- |",
    "| DED001 | `Error` | Your extension doesn't have a name, which is mandatory. |": "| DED001 | `Error` | У расширения нет имени, которое является обязательным. |",
    "| DED002 | `Error` | Your extension's name needs to be less that 50 character. characters. |": "| DED002 | `Error` | Имя расширения должно содержать менее 50 символов. |",
    "| DED003 | `Error` | Your extension's name is invalid. It should only contain lowercase letters, numbers, hyphens, underscores, or dots. |": "| DED003 | `Error` | Имя расширения недопустимо. Оно должно содержать только строчные буквы, цифры, дефисы, символы подчёркивания или точки. |",
    "| DED004 | `Error` | Your extension's name needs to start with custom: but it doesn't. |": "| DED004 | `Error` | Имя расширения должно начинаться с custom:, но это условие не выполнено. |",
    "| DED005 | `Warning` | Internal Dynatrace extension names shouldn't start with custom:. |": "| DED005 | `Warning` | Имена внутренних расширений Dynatrace не должны начинаться с custom:. |",
    "| DED006 | `Warning` | Metrics of type count should have keys ending in **.count** or **\\_count**. |": "| DED006 | `Warning` | Метрики типа count должны иметь ключи, оканчивающиеся на **.count** или **\\_count**. |",
    "| DED007 | `Warning` | Metrics of type gauge shouldn't have keys ending in **.count** or **\\_count**. |": "| DED007 | `Warning` | Метрики типа gauge не должны иметь ключи, оканчивающиеся на **.count** или **\\_count**. |",
    "| DED008 | `Error` | You referenced this card key in a screen layout, but it doesn't have a definition. |": "| DED008 | `Error` | Этот ключ карточки используется в макете экрана, но не имеет определения. |",
    "| DED009 | `Warning` | You defined this card, but you're not referencing it in the screen layout. |": "| DED009 | `Warning` | Карточка определена, но не используется в макете экрана. |",
    "| DED010 | `Warning` | There is no online data about this Object Identifier (OID). You may want to validate it. |": "| DED010 | `Warning` | Отсутствуют онлайн-данные об этом идентификаторе объекта (OID). Рекомендуется проверить его. |",
    "| DED011 | `Error` | This OID isn't readable. The access permissions ([MAX-ACCESS](https://learn.microsoft.com/en-us/windows/win32/wmisdk/access-and-max-access-clauses)) don't allow it. |": "| DED011 | `Error` | Этот OID недоступен для чтения. Разрешения доступа ([MAX-ACCESS](https://learn.microsoft.com/en-us/windows/win32/wmisdk/access-and-max-access-clauses)) не допускают это. |",
    "| DED012 | `Error` | This OID returns a string, but you're using it as a metric value. |": "| DED012 | `Error` | Этот OID возвращает строку, но используется как значение метрики. |",
    "| DED013 | `Warning` | This OID returns a Counter, but you're using it as a Gauge metric. |": "| DED013 | `Warning` | Этот OID возвращает Counter, но используется как метрика Gauge. |",
    "| DED014 | `Warning` | This OID returns a Gauge, but you're using it as a Counter metric. |": "| DED014 | `Warning` | Этот OID возвращает Gauge, но используется как метрика Counter. |",
    "| DED015 | `Error` | Invalid OID syntax. OID shouldn't start/end with '.' and may only contain dots and digits. |": "| DED015 | `Error` | Недопустимый синтаксис OID. OID не должен начинаться или заканчиваться на '.' и может содержать только точки и цифры. |",
    "| DED016 | `Error` | Invalid OID syntax. OIDs shouldn't end in '.0' when 'table' is set to 'true' in the subgroup. |": "| DED016 | `Error` | Недопустимый синтаксис OID. OID не должен заканчиваться на '.0', если в подгруппе для 'table' задано значение 'true'. |",
    "| DED017 | `Error` | Invalid OID syntax. OIDs needs to end in '.0' when 'table' is set to 'false' in the subgroup. |": "| DED017 | `Error` | Недопустимый синтаксис OID. OID должен заканчиваться на '.0', если в подгруппе для 'table' задано значение 'false'. |",
    "| DED018 | `Error` | Online data lists this OID as static, but you're using it inside a 'table' subgroup. |": "| DED018 | `Error` | Онлайн-данные указывают, что этот OID является статическим, но он используется внутри подгруппы 'table'. |",
    "| DED019 | `Error` | Online data maps this OID to table entries, but you're not using it inside a 'table' subgroup. |": "| DED019 | `Error` | Онлайн-данные сопоставляют этот OID с записями таблицы, но он не используется внутри подгруппы 'table'. |",
    "The code itself doesn't mean anything; it just provides a unique identifier within all diagnostics that may come up": "Код сам по себе ничего не означает: он лишь предоставляет уникальный идентификатор среди всех диагностических сообщений, которые могут появиться",
    "in VS Code. We chose the **DED** prefix to stand for Dynatrace Extensions Diagnostic.": "в VS Code. Префикс **DED** выбран как сокращение от Dynatrace Extensions Diagnostic.",
}

PASS = {
    "title: Development assistance",
    "# Development assistance",
}

if __name__ == "__main__":
    build_one(REL, "development-assistance.md", TRANS, PASS)
    qa_one(REL, "development-assistance.md")
