# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics"

TRANS = {
    "title: Limit API calls to AWS using tags": "title: Ограничение API-вызовов к AWS с помощью тегов",
    "# Limit API calls to AWS using tags": "# Ограничение API-вызовов к AWS с помощью тегов",
    "* How-to guide": "* Практическое руководство",
    "* 2-min read": "* Чтение: 2 мин",
    "* Published Jul 19, 2017": "* Опубликовано 19 июля 2017 г.",
    "By default, Dynatrace monitors all Amazon Web Services that have been specified in your permission policy. Optionally, you can use tagging to limit the AWS resources (AWS service instances) that are monitored by Dynatrace.": "По умолчанию Dynatrace отслеживает все сервисы Amazon Web Services, указанные в политике разрешений. При необходимости можно использовать теги для ограничения ресурсов AWS (экземпляров сервисов AWS), отслеживаемых Dynatrace.",
    "## Add tags in AWS": "## Добавление тегов в AWS",
    "To add a tag": "Чтобы добавить тег",
    "1. Sign in to your AWS Management Console and go to the dashboard of the service you want to tag.": "1. Войдите в AWS Management Console и перейдите на дашборд сервиса, которому необходимо присвоить тег.",
    "2. Select **Instances** to see a list of your environments, then select an instance.": "2. Выберите **Instances**, чтобы просмотреть список окружений, затем выберите экземпляр.",
    "3. In the panel below the list, select **Tags**.": "3. На панели под списком выберите **Tags**.",
    "4. Select **Add/Edit tags**, then select **Create tag**.": "4. Выберите **Add/Edit tags**, затем **Create tag**.",
    "5. Enter a tag key/value pair (for example, 'monitor\\_dynatrace' for **Key**, and 'true' for **Value**).": "5. Введите пару ключ/значение тега (например, 'monitor\\_dynatrace' для **Key** и 'true' для **Value**).",
    "6. Select **Save**.": "6. Нажмите **Save**.",
    "Dynatrace monitoring tags work for built-in: EC2, RDS, ELB, EBS, auto-scaling groups, DynamoDB, Lambda, and most cloud services.": "Теги мониторинга Dynatrace работают со встроенными сервисами: EC2, RDS, ELB, EBS, группами автомасштабирования, DynamoDB, Lambda, а также большинством облачных сервисов.",
    "Expand the table below to see which services can be filtered by tags.": "Раскройте таблицу ниже, чтобы узнать, для каких сервисов доступна фильтрация по тегам.",
    "### Tag filtering per service": "### Фильтрация по тегам для каждого сервиса",
    "| Name | Tags monitoring & filtering |": "| Название | Мониторинг и фильтрация по тегам |",
    "| --- | --- |": "| --- | --- |",
    "| Amazon EC2 Auto Scaling (built-in) | yes |": "| Amazon EC2 Auto Scaling (built-in) | да |",
    "| AWS Lambda (built-in) | yes |": "| AWS Lambda (built-in) | да |",
    "| Amazon Application and Network Load Balancer (built-in) | yes |": "| Amazon Application and Network Load Balancer (built-in) | да |",
    "| Amazon DynamoDB (built-in) | yes |": "| Amazon DynamoDB (built-in) | да |",
    "| Amazon EBS (built-in) | yes |": "| Amazon EBS (built-in) | да |",
    "| Amazon EC2 (built-in) | yes |": "| Amazon EC2 (built-in) | да |",
    "| Amazon Elastic Load Balancer (ELB) (built-in) | yes |": "| Amazon Elastic Load Balancer (ELB) (built-in) | да |",
    "| Amazon RDS (built-in) | yes |": "| Amazon RDS (built-in) | да |",
    "| Amazon S3 (built-in) | yes |": "| Amazon S3 (built-in) | да |",
    "| AWS Certificate Manager Private Certificate Authority | yes |": "| AWS Certificate Manager Private Certificate Authority | да |",
    "| Amazon API Gateway | yes |": "| Amazon API Gateway | да |",
    "| AWS App Runner | yes |": "| AWS App Runner | да |",
    "| Amazon AppStream | yes |": "| Amazon AppStream | да |",
    "| AWS AppSync | yes |": "| AWS AppSync | да |",
    "| Amazon Athena | yes |": "| Amazon Athena | да |",
    "| Amazon Aurora | yes |": "| Amazon Aurora | да |",
    "| Amazon EC2 Auto Scaling | - |": "| Amazon EC2 Auto Scaling | - |",
    "| AWS Billing | - |": "| AWS Billing | - |",
    "| Amazon Keyspaces | yes |": "| Amazon Keyspaces | да |",
    "| AWS Chatbot | - |": "| AWS Chatbot | - |",
    "| Amazon CloudFront | yes |": "| Amazon CloudFront | да |",
    "| AWS CloudHSM | yes |": "| AWS CloudHSM | да |",
    "| Amazon CloudSearch | - |": "| Amazon CloudSearch | - |",
    "| AWS CodeBuild | yes |": "| AWS CodeBuild | да |",
    "| Amazon Cognito | - |": "| Amazon Cognito | - |",
    "| Amazon Connect | - |": "| Amazon Connect | - |",
    "| AWS DataSync | yes |": "| AWS DataSync | да |",
    "| Amazon DynamoDB Accelerator (DAX) | yes |": "| Amazon DynamoDB Accelerator (DAX) | да |",
    "| AWS Database Migration Service (AWS DMS) | yes |": "| AWS Database Migration Service (AWS DMS) | да |",
    "| Amazon DocumentDB | yes |": "| Amazon DocumentDB | да |",
    "| AWS Direct Connect | yes |": "| AWS Direct Connect | да |",
    "| Amazon DynamoDB | yes |": "| Amazon DynamoDB | да |",
    "| Amazon EBS | yes |": "| Amazon EBS | да |",
    "| Amazon EC2 Spot Fleet | - |": "| Amazon EC2 Spot Fleet | - |",
    "| Amazon EC2 API | - |": "| Amazon EC2 API | - |",
    "| Amazon Elastic Container Service (ECS) | yes |": "| Amazon Elastic Container Service (ECS) | да |",
    "| Amazon ECS Container Insights | yes |": "| Amazon ECS Container Insights | да |",
    "| Amazon Elastic File System (EFS) | yes |": "| Amazon Elastic File System (EFS) | да |",
    "| Amazon Elastic Kubernetes Service (EKS) | yes |": "| Amazon Elastic Kubernetes Service (EKS) | да |",
    "| Amazon ElastiCache (EC) | yes |": "| Amazon ElastiCache (EC) | да |",
    "| AWS Elastic Beanstalk | yes |": "| AWS Elastic Beanstalk | да |",
    "| Amazon Elastic Inference | yes |": "| Amazon Elastic Inference | да |",
    "| Amazon Elastic Transcoder | - |": "| Amazon Elastic Transcoder | - |",
    "| Amazon Elastic Map Reduce (EMR) | yes |": "| Amazon Elastic Map Reduce (EMR) | да |",
    "| Amazon Elasticsearch Service (ES) | yes |": "| Amazon Elasticsearch Service (ES) | да |",
    "| Amazon EventBridge | yes |": "| Amazon EventBridge | да |",
    "| Amazon FSx | yes |": "| Amazon FSx | да |",
    "| Amazon GameLift | - |": "| Amazon GameLift | - |",
    "| AWS Glue | yes |": "| AWS Glue | да |",
    "| Amazon Inspector | yes |": "| Amazon Inspector | да |",
    "| AWS Internet of Things (IoT) | - |": "| AWS Internet of Things (IoT) | - |",
    "| AWS IoT Things Graph | - |": "| AWS IoT Things Graph | - |",
    "| AWS IoT Analytics | - |": "| AWS IoT Analytics | - |",
    "| Amazon Managed Streaming for Kafka | yes |": "| Amazon Managed Streaming for Kafka | да |",
    "| Amazon Kinesis Data Analytics | yes |": "| Amazon Kinesis Data Analytics | да |",
    "| Amazon Data Firehose | yes |": "| Amazon Data Firehose | да |",
    "| Amazon Kinesis Data Streams | yes |": "| Amazon Kinesis Data Streams | да |",
    "| Amazon Kinesis Video Streams | yes |": "| Amazon Kinesis Video Streams | да |",
    "| AWS Lambda | yes |": "| AWS Lambda | да |",
    "| Amazon Lex | yes |": "| Amazon Lex | да |",
    "| Amazon CloudWatch Logs | yes |": "| Amazon CloudWatch Logs | да |",
    "| AWS Elemental MediaTailor | yes |": "| AWS Elemental MediaTailor | да |",
    "| AWS Elemental MediaConnect | - |": "| AWS Elemental MediaConnect | - |",
    "| AWS Elemental MediaConvert | yes |": "| AWS Elemental MediaConvert | да |",
    "| AWS Elemental MediaPackage Live | yes |": "| AWS Elemental MediaPackage Live | да |",
    "| AWS Elemental MediaPackage Video on Demand | yes |": "| AWS Elemental MediaPackage Video on Demand | да |",
    "| Amazon MQ | - |": "| Amazon MQ | - |",
    "| Amazon VPC NAT Gateways | yes |": "| Amazon VPC NAT Gateways | да |",
    "| Amazon Neptune | yes |": "| Amazon Neptune | да |",
    "| AWS OpsWorks | yes |": "| AWS OpsWorks | да |",
    "| Amazon Polly | - |": "| Amazon Polly | - |",
    "| Amazon QLDB | yes |": "| Amazon QLDB | да |",
    "| Amazon RDS | yes |": "| Amazon RDS | да |",
    "| Amazon Redshift | yes |": "| Amazon Redshift | да |",
    "| Amazon Rekognition | - |": "| Amazon Rekognition | - |",
    "| AWS RoboMaker | yes |": "| AWS RoboMaker | да |",
    "| Amazon Route 53 | yes |": "| Amazon Route 53 | да |",
    "| Amazon Route 53 Resolver | yes |": "| Amazon Route 53 Resolver | да |",
    "| Amazon S3 | yes |": "| Amazon S3 | да |",
    "| Amazon SageMaker Batch Transform Jobs | - |": "| Amazon SageMaker Batch Transform Jobs | - |",
    "| Amazon SageMaker Endpoints | yes |": "| Amazon SageMaker Endpoints | да |",
    "| Amazon SageMaker Endpoint Instances | yes |": "| Amazon SageMaker Endpoint Instances | да |",
    "| Amazon SageMaker Ground Truth | - |": "| Amazon SageMaker Ground Truth | - |",
    "| Amazon SageMaker Processing Jobs | - |": "| Amazon SageMaker Processing Jobs | - |",
    "| Amazon SageMaker Training Jobs | - |": "| Amazon SageMaker Training Jobs | - |",
    "| AWS Service Catalog | - |": "| AWS Service Catalog | - |",
    "| Amazon Simple Email Service (SES) | - |": "| Amazon Simple Email Service (SES) | - |",
    "| Amazon Simple Notification Service (SNS) | yes |": "| Amazon Simple Notification Service (SNS) | да |",
    "| Amazon Simple Queue Service (SQS) | yes |": "| Amazon Simple Queue Service (SQS) | да |",
    "| AWS Systems Manager - Run Command | - |": "| AWS Systems Manager - Run Command | - |",
    "| AWS Step Functions | - |": "| AWS Step Functions | - |",
    "| AWS Storage Gateway | yes |": "| AWS Storage Gateway | да |",
    "| Amazon SWF | - |": "| Amazon SWF | - |",
    "| Amazon Textract | - |": "| Amazon Textract | - |",
    "| AWS Transfer Family | yes |": "| AWS Transfer Family | да |",
    "| AWS Transit Gateway | yes |": "| AWS Transit Gateway | да |",
    "| Amazon Translate | - |": "| Amazon Translate | - |",
    "| AWS Trusted Advisor | - |": "| AWS Trusted Advisor | - |",
    "| AWS API Usage | - |": "| AWS API Usage | - |",
    "| AWS Site-to-Site VPN | yes |": "| AWS Site-to-Site VPN | да |",
    "| AWS WAF Classic | - |": "| AWS WAF Classic | - |",
    "| AWS WAF | - |": "| AWS WAF | - |",
    "| Amazon WorkMail | yes |": "| Amazon WorkMail | да |",
    "| Amazon WorkSpaces | yes |": "| Amazon WorkSpaces | да |",
    "## Configure Dynatrace to use AWS tags": "## Настройка Dynatrace для использования тегов AWS",
    "Dynatrace enables you to use up to 10 AWS tags at a time. Once configured, Dynatrace takes tagged services into account when querying performance counters.": "Dynatrace позволяет использовать до 10 тегов AWS одновременно. После настройки Dynatrace учитывает сервисы с тегами при запросе счётчиков производительности.",
    "AWS tag key/value pairs are executed with an OR operator. Keys don't need to be unique.": "Пары ключ/значение тегов AWS обрабатываются с оператором OR. Ключи не обязаны быть уникальными.",
    "Tag-based AWS monitoring offers a lot of flexibility and is particularly helpful if:": "Мониторинг AWS на основе тегов обладает высокой гибкостью и особенно полезен, если:",
    "* You leverage multiple Dynatrace environments and you want to monitor distinct AWS services running under the same AWS account.": "* используется несколько окружений Dynatrace и нужно отслеживать отдельные сервисы AWS, работающие в одной учётной записи AWS.",
    "**Tag examples:** `monitor_dynatrace : myenvironment1; monitor_dynatrace : myenvironment2`": "**Примеры тегов:** `monitor_dynatrace : myenvironment1; monitor_dynatrace : myenvironment2`",
    "* You need to monitor the same AWS account, but distinguish between production and staging services.": "* необходимо отслеживать одну учётную запись AWS, но разделять сервисы производственной среды и среды тестирования.",
    "**Tag examples:**": "**Примеры тегов:**",
    "`monitor_dynatrace : production; monitor_dynatrace : staging`": "`monitor_dynatrace : production; monitor_dynatrace : staging`",
    "To assign tags to a specific AWS instance": "Чтобы назначить теги конкретному экземпляру AWS",
    "1. [Set up Dynatrace for AWS monitoring](/managed/observe/infrastructure-observability/cloud-platform-monitoring/aws-monitoring \"Monitor AWS with Dynatrace\").": "1. [Настройте Dynatrace для мониторинга AWS](/managed/observe/infrastructure-observability/cloud-platform-monitoring/aws-monitoring \"Monitor AWS with Dynatrace\").",
    "2. In Dynatrace, go to **Settings** > **Cloud and virtualization** > **AWS** and select the AWS instance.": "2. В Dynatrace перейдите в **Settings** > **Cloud and virtualization** > **AWS** и выберите экземпляр AWS.",
    "3. For **Resources to be monitored**, select **Monitor resources selected by tags**.": "3. В поле **Resources to be monitored** выберите **Monitor resources selected by tags**.",
    "4. Enter the **Key** and **Value**.": "4. Введите **Key** и **Value**.",
    "5. Select **Save**.": "5. Нажмите **Save**.",
}

PASS = set()

build_one(REL, "limit-api-calls-to-aws-using-tags.md", TRANS, PASS)
qa_one(REL, "limit-api-calls-to-aws-using-tags.md")
