# -*- coding: utf-8 -*-
from _otel_canon import S, SUB, build_one, qa_one

TRANS = {
    "title: Batch OTLP requests with the OTel Collector": "title: Группирование запросов OTLP с помощью OTel Collector",
    "# Batch OTLP requests with the OTel Collector": "# Группирование запросов OTLP с помощью OTel Collector",
    "The following configuration example shows how you configure a Collector instance and its native batch processor to queue and batch OTLP requests and improve throughput performance.": "В следующем примере конфигурации показано, как настроить экземпляр Collector и его встроенный processor `batch` для постановки в очередь и группирования запросов OTLP и повышения производительности по пропускной способности.",
    "Recommended configuration": "Рекомендуемая конфигурация",
    "For optimal performance of your Collector instance, we recommend that you apply this configuration with all setups.": "Для оптимальной производительности вашего экземпляра Collector мы рекомендуем применять эту конфигурацию во всех установках.",
    "If you use other processors, make sure the batch processor is configured last in your pipeline.": "Если вы используете другие processor, убедитесь, что processor `batch` настроен последним в вашем конвейере.",
    "* One of the following Collector distributions with the [batch processor](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.151.0/processor/batchprocessor):": "* Один из следующих дистрибутивов Collector с [processor `batch`](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.151.0/processor/batchprocessor):",
    '+ The OpenTelemetry [Core](/managed/ingest-from/opentelemetry/collector#collector-core "Learn how to use the OpenTelemetry Collector, including the Dynatrace OTel Collector, to ingest telemetry from OpenTelemetry.") or [Contrib](/managed/ingest-from/opentelemetry/collector#collector-contrib "Learn how to use the OpenTelemetry Collector, including the Dynatrace OTel Collector, to ingest telemetry from OpenTelemetry.") distribution': '+ Дистрибутив OpenTelemetry [Core](/managed/ingest-from/opentelemetry/collector#collector-core "Узнайте, как использовать OpenTelemetry Collector, включая Dynatrace OTel Collector, для приёма телеметрии из OpenTelemetry.") или [Contrib](/managed/ingest-from/opentelemetry/collector#collector-contrib "Узнайте, как использовать OpenTelemetry Collector, включая Dynatrace OTel Collector, для приёма телеметрии из OpenTelemetry.")',
    "Under `receivers`, we specify the standard `otlp` receiver as active receiver component for our Collector instance.": "В разделе `receivers` мы указываем стандартный receiver `otlp` в качестве активного компонента receiver для нашего экземпляра Collector.",
    "This is for demonstration purposes. You can specify any other valid receiver here (for example, `zipkin`).": "Это сделано в демонстрационных целях. Здесь можно указать любой другой допустимый receiver (например, `zipkin`).",
    "Under `processors`, we specify a different [`batch` processor](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.151.0/processor/batchprocessor)": "В разделе `processors` мы указываем отдельный [processor `batch`](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.151.0/processor/batchprocessor)",
    "for each telemetry signal, with the following parameters:": "для каждого сигнала телеметрии со следующими параметрами:",
    "* `send_batch_size`: sets the minimum number of entries the processor will queue before sending the whole batch.": "* `send_batch_size`: задаёт минимальное число записей, которые processor поставит в очередь перед отправкой всей группы.",
    "* `send_batch_max_size`: sets the maximum number of entries a batch may contain. More entries will split the batch into smaller ones.": "* `send_batch_max_size`: задаёт максимальное число записей, которые может содержать группа. При большем числе записей группа разбивается на более мелкие.",
    "* `timeout`: defines the duration after which the batch will be sent. A batch is sent after the `timeout` only when the `send_batch_size` condition is not reached.": "* `timeout`: определяет длительность, по истечении которой группа будет отправлена. Группа отправляется по `timeout` только тогда, когда условие `send_batch_size` не достигнуто.",
    "With this configuration, the OTel Collector queues telemetry entries in batches, ensuring a good balance between the size and number of export requests": "При такой конфигурации OTel Collector ставит записи телеметрии в очередь группами, обеспечивая хороший баланс между размером и числом запросов на экспорт",
    "to the Dynatrace API.": "к Dynatrace API.",
    "Batch size values": "Значения размера группы",
    "Not only the number of individual telemetry entries will contribute to the eventual size": "На итоговый размер группы влияет не только число отдельных записей телеметрии,",
    "of a batch, but also the number of associated attributes and their size.": "но и число связанных атрибутов и их размер.",
    "For example, attributes on spans/metrics/logs can make a batch size with the same amount of entries larger,": "Например, атрибуты на спанах/метриках/логах могут увеличить размер группы с тем же числом записей",
    "depending on how many/how large the attributes are.": "в зависимости от того, сколько атрибутов и насколько они велики.",
    "Use the configuration values above as a starting point, but be sure to adapt them to fit your data volume": "Используйте приведённые выше значения конфигурации как отправную точку, но обязательно адаптируйте их под ваш объём данных",
    'and comply with the Dynatrace API limits for each signal type ([traces](/managed/ingest-from/opentelemetry/otlp-api/ingest-traces#ingestion-limits "Learn how Dynatrace ingests OpenTelemetry traces and what limitations apply."),': 'и соблюдайте лимиты Dynatrace API для каждого типа сигнала ([трассировки](/managed/ingest-from/opentelemetry/otlp-api/ingest-traces#ingestion-limits "Узнайте, как Dynatrace принимает трассировки OpenTelemetry и какие ограничения применяются."),',
    '[metrics](/managed/ingest-from/opentelemetry/otlp-api/ingest-otlp-metrics/about-metrics-ingest#limits "Learn how Dynatrace ingests OpenTelemetry metrics and what limitations apply."), [logs](/managed/ingest-from/opentelemetry/otlp-api/ingest-logs#ingestion-limits "Learn how Dynatrace ingests OpenTelemetry log records and what limitations apply.")) to avoid request rejections.': '[метрики](/managed/ingest-from/opentelemetry/otlp-api/ingest-otlp-metrics/about-metrics-ingest#limits "Узнайте, как Dynatrace принимает метрики OpenTelemetry и какие ограничения применяются."), [логи](/managed/ingest-from/opentelemetry/otlp-api/ingest-logs#ingestion-limits "Узнайте, как Dynatrace принимает записи логов OpenTelemetry и какие ограничения применяются.")), чтобы избежать отклонения запросов.',
    'You can use the [ActiveGate self-monitoring metrics](/managed/ingest-from/dynatrace-activegate/activegate-sfm-metrics#rest "Explore ActiveGate self-monitoring  metrics.")': 'Для устранения проблем с отклонёнными запросами можно использовать [метрики самомониторинга ActiveGate](/managed/ingest-from/dynatrace-activegate/activegate-sfm-metrics#rest "Изучите метрики самомониторинга ActiveGate.").',
    "to troubleshoot rejected requests. For example, you can use: `dsfm:active_gate.rest.request_count` filtering for the `operation`": "Например, можно использовать: `dsfm:active_gate.rest.request_count` с фильтрацией по измерению `operation`",
    "dimension (`POST /otlp/v1/<...>` for OTLP ingest) and split by `response_code`. Large requests are rejected with HTTP status code `413`.": "(`POST /otlp/v1/<...>` для приёма OTLP) и разбивкой по `response_code`. Большие запросы отклоняются с кодом состояния HTTP `413`.",
    "Another alternative is checking the Collector logs for error messages such as: `HTTP Status Code 413, Message=Max Payload size of`.": "Ещё один вариант: проверить логи Collector на наличие сообщений об ошибках, таких как: `HTTP Status Code 413, Message=Max Payload size of`.",
    "Under `service`, we assemble our receiver and exporter objects into pipelines for traces, metrics, and logs and enable our batch processor by referencing it under `processors` for each respective pipeline.": "В разделе `service` мы собираем наши объекты receiver и exporter в конвейеры для трассировок, метрик и логов и включаем наш processor `batch`, ссылаясь на него в разделе `processors` для каждого соответствующего конвейера.",
    **S,
}
PASS = {"### Receivers", "### Processors", "### Exporters"}
if __name__ == "__main__":
    build_one(SUB, "batch.md", TRANS, PASS)
    qa_one(SUB, "batch.md")
