# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/amazon-web-services"

TRANS = {
    "title: Set up Dynatrace Managed for AWS monitoring": "title: Настройка Dynatrace Managed для мониторинга AWS",
    "# Set up Dynatrace Managed for AWS monitoring": "# Настройка Dynatrace Managed для мониторинга AWS",
    "* Updated on Jun 27, 2022": "* Обновлено 27 июня 2022 г.",
    "You can integrate Dynatrace with [Amazon Web Services (AWS)](https://www.dynatrace.com/technologies/aws-monitoring/) for intelligent monitoring of services running in the Amazon Cloud. AWS integration helps you stay on top of the dynamics of your data center in the cloud.": "Dynatrace можно интегрировать с [Amazon Web Services (AWS)](https://www.dynatrace.com/technologies/aws-monitoring/) для интеллектуального мониторинга сервисов, работающих в облаке Amazon. Интеграция с AWS помогает отслеживать динамику центра обработки данных в облаке.",
    "Dynatrace can be deployed with or without Environment ActiveGate.": "Dynatrace можно развернуть с Environment ActiveGate или без него.",
    "While using the role-based access method, make sure that you meet one of the following deployment requirements:": "При использовании метода доступа на основе ролей необходимо выполнить одно из следующих требований к развёртыванию:",
    "* For deployments with Environment ActiveGate, the Environment ActiveGate must be hosted in AWS.": "* При развёртывании с Environment ActiveGate среда Environment ActiveGate должна быть размещена в AWS.",
    "* For deployments without Environment ActiveGate, a Dynatrace Managed Server must be hosted in AWS.": "* При развёртывании без Environment ActiveGate Dynatrace Managed Server должен быть размещён в AWS.",
    "## Overview": "## Обзор",
    "Follow these basic steps to integrate Dynatrace Managed with Amazon Web Services (AWS):": "Выполните следующие основные шаги для интеграции Dynatrace Managed с Amazon Web Services (AWS):",
    "1. [Configure the access method](#access-method)": "1. [Настройте метод доступа](#access-method)",
    "2. [Select your AWS partition](#partition)": "2. [Выберите раздел AWS](#partition)",
    "3. [Adjust monitoring to your needs](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#define-aws-resource-tagging \"Connect your Amazon account with Dynatrace Managed and start monitoring.\")": "3. [Настройте мониторинг под свои потребности](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#define-aws-resource-tagging \"Подключите Amazon-аккаунт к Dynatrace Managed и начните мониторинг.\")",
    "Cloud-service monitoring consumption": "Потребление для мониторинга облачных сервисов",
    "All cloud services consume [Davis data units (DDUs)](/managed/license/monitoring-consumption-classic/davis-data-units \"Understand how Dynatrace monitoring consumption is calculated based on Davis data units (DDU).\"). The amount of DDU consumption per service instance depends on the number of monitored metrics and their dimensions (each metric dimension results in the ingestion of 1 data point; 1 data point consumes 0.001 DDUs).": "Все облачные сервисы потребляют [единицы данных Davis (DDU)](/managed/license/monitoring-consumption-classic/davis-data-units \"Узнайте, как рассчитывается потребление мониторинга Dynatrace на основе единиц данных Davis (DDU).\"). Объём потребления DDU на экземпляр сервиса зависит от количества отслеживаемых метрик и их измерений (каждое измерение метрики приводит к получению 1 точки данных; 1 точка данных потребляет 0,001 DDU).",
    "### AWS costs": "### Затраты AWS",
    "Dynatrace makes Amazon API requests every five minutes. In addition to CloudWatch API calls, Dynatrace makes API calls to the monitored AWS services to learn about their instances, tags, etc. The list of called services and actions is available below in the [Create the monitoring policy](#monitoring-policy) section.": "Dynatrace выполняет API-запросы к Amazon каждые пять минут. Помимо API-вызовов CloudWatch, Dynatrace отправляет API-запросы к отслеживаемым сервисам AWS для получения сведений об экземплярах, тегах и т. д. Список вызываемых сервисов и действий доступен ниже в разделе [Создание политики мониторинга](#monitoring-policy).",
    "Here's a rough estimate of AWS monitoring costs:": "Ниже приведена приблизительная оценка затрат на мониторинг AWS:",
    "| AWS service | Number of metrics | Daily cost per instance (USD) |": "| Сервис AWS | Количество метрик | Суточная стоимость на экземпляр (USD) |",
    "| --- | --- | --- |": "| --- | --- | --- |",
    "| Elastic Compute Cloud (EC2) | 7 | $0.02016 |": "| Elastic Compute Cloud (EC2) | 7 | $0,02016 |",
    "| Elastic Block Store (EBS) | 8 | $0.02304 |": "| Elastic Block Store (EBS) | 8 | $0,02304 |",
    "| Elastic Load Balancer (ELB) | 11 | $0.03168 |": "| Elastic Load Balancer (ELB) | 11 | $0,03168 |",
    "| Relational Database Service (RDS) | 11 | $0.03168 |": "| Relational Database Service (RDS) | 11 | $0,03168 |",
    "| DynamoDB | 15 | $0.06912 |": "| DynamoDB | 15 | $0,06912 |",
    "| Lambda | 4 | $0.01152 |": "| Lambda | 4 | $0,01152 |",
    "Amazon charges": "Оплата Amazon",
    "Amazon will charge about $0.01 per 1,000 metrics requested from the CloudWatch API and include the cost in the bill for the AWS account you use with Dynatrace.": "Amazon взимает около $0,01 за 1000 метрик, запрошенных через CloudWatch API, и включает эту стоимость в счёт для AWS-аккаунта, используемого с Dynatrace.",
    "## AWS monitoring policy": "## Политика мониторинга AWS",
    "The AWS monitoring policy defines the minimal scope of permissions you need to give to Dynatrace to monitor the services running in your AWS account. Create it once and use it any time when enabling Dynatrace access to your AWS account.": "Политика мониторинга AWS определяет минимальный набор разрешений, которые необходимо предоставить Dynatrace для мониторинга сервисов в AWS-аккаунте. Создайте её один раз и используйте каждый раз при предоставлении Dynatrace доступа к AWS-аккаунту.",
    "If you don't want to add permissions to all services, and just select permissions for certain services, consult the table below. The table contains a set of permissions that are required for [All AWS cloud services](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Monitor all AWS cloud services with Dynatrace and view available metrics.\") and, for each cloud service, a list of optional permissions specific to that service.": "Если не нужно добавлять разрешения для всех сервисов и требуется выбрать разрешения только для определённых, обратитесь к таблице ниже. В таблице содержится набор разрешений, необходимых для [всех облачных сервисов AWS](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Мониторинг всех облачных сервисов AWS с помощью Dynatrace и просмотр доступных метрик.\"), а также список необязательных разрешений для каждого облачного сервиса.",
    "Permissions required for AWS monitoring integration:": "Разрешения, необходимые для интеграции мониторинга AWS:",
    '* `"cloudwatch:GetMetricData"`': '* `"cloudwatch:GetMetricData"`',
    '* `"cloudwatch:GetMetricStatistics"`': '* `"cloudwatch:GetMetricStatistics"`',
    '* `"cloudwatch:ListMetrics"`': '* `"cloudwatch:ListMetrics"`',
    '* `"sts:GetCallerIdentity"`': '* `"sts:GetCallerIdentity"`',
    '* `"tag:GetResources"`': '* `"tag:GetResources"`',
    '* `"tag:GetTagKeys"`': '* `"tag:GetTagKeys"`',
    '* `"ec2:DescribeAvailabilityZones"`': '* `"ec2:DescribeAvailabilityZones"`',
    "### Complete list of permissions for cloud services": "### Полный список разрешений для облачных сервисов",
    "| Name | Permissions |": "| Название | Разрешения |",
    "| --- | --- |": "| --- | --- |",
    "| All monitored Amazon services Required | `cloudwatch:GetMetricData`, `cloudwatch:GetMetricStatistics`, `cloudwatch:ListMetrics`, `sts:GetCallerIdentity`, `tag:GetResources`, `tag:GetTagKeys`, `ec2:DescribeAvailabilityZones` |": "| Все отслеживаемые сервисы Amazon (обязательно) | `cloudwatch:GetMetricData`, `cloudwatch:GetMetricStatistics`, `cloudwatch:ListMetrics`, `sts:GetCallerIdentity`, `tag:GetResources`, `tag:GetTagKeys`, `ec2:DescribeAvailabilityZones` |",
    "| AWS Certificate Manager Private Certificate Authority | `acm-pca:ListCertificateAuthorities` |": "| AWS Certificate Manager Private Certificate Authority | `acm-pca:ListCertificateAuthorities` |",
    "| Amazon MQ |  |": "| Amazon MQ |  |",
    "| Amazon API Gateway | `apigateway:GET` |": "| Amazon API Gateway | `apigateway:GET` |",
    "| AWS App Runner | `apprunner:ListServices` |": "| AWS App Runner | `apprunner:ListServices` |",
    "| Amazon AppStream | `appstream:DescribeFleets` |": "| Amazon AppStream | `appstream:DescribeFleets` |",
    "| AWS AppSync | `appsync:ListGraphqlApis` |": "| AWS AppSync | `appsync:ListGraphqlApis` |",
    "| Amazon Athena | `athena:ListWorkGroups` |": "| Amazon Athena | `athena:ListWorkGroups` |",
    "| Amazon Aurora | `rds:DescribeDBClusters` |": "| Amazon Aurora | `rds:DescribeDBClusters` |",
    "| Amazon EC2 Auto Scaling | `autoscaling:DescribeAutoScalingGroups` |": "| Amazon EC2 Auto Scaling | `autoscaling:DescribeAutoScalingGroups` |",
    "| Amazon EC2 Auto Scaling (built-in) | `autoscaling:DescribeAutoScalingGroups` |": "| Amazon EC2 Auto Scaling (built-in) | `autoscaling:DescribeAutoScalingGroups` |",
    "| AWS Billing |  |": "| AWS Billing |  |",
    "| Amazon Keyspaces |  |": "| Amazon Keyspaces |  |",
    "| AWS Chatbot |  |": "| AWS Chatbot |  |",
    "| Amazon CloudFront | `cloudfront:ListDistributions` |": "| Amazon CloudFront | `cloudfront:ListDistributions` |",
    "| AWS CloudHSM | `cloudhsm:DescribeClusters` |": "| AWS CloudHSM | `cloudhsm:DescribeClusters` |",
    "| Amazon CloudSearch | `cloudsearch:DescribeDomains` |": "| Amazon CloudSearch | `cloudsearch:DescribeDomains` |",
    "| AWS CodeBuild | `codebuild:ListProjects` |": "| AWS CodeBuild | `codebuild:ListProjects` |",
    "| Amazon Cognito |  |": "| Amazon Cognito |  |",
    "| Amazon Connect |  |": "| Amazon Connect |  |",
    "| Amazon Elastic Kubernetes Service (EKS) | `eks:ListClusters` |": "| Amazon Elastic Kubernetes Service (EKS) | `eks:ListClusters` |",
    "| AWS DataSync | `datasync:ListTasks` |": "| AWS DataSync | `datasync:ListTasks` |",
    "| Amazon DynamoDB Accelerator (DAX) | `dax:DescribeClusters` |": "| Amazon DynamoDB Accelerator (DAX) | `dax:DescribeClusters` |",
    "| AWS Database Migration Service (AWS DMS) | `dms:DescribeReplicationInstances` |": "| AWS Database Migration Service (AWS DMS) | `dms:DescribeReplicationInstances` |",
    "| Amazon DocumentDB | `rds:DescribeDBClusters` |": "| Amazon DocumentDB | `rds:DescribeDBClusters` |",
    "| AWS Direct Connect | `directconnect:DescribeConnections` |": "| AWS Direct Connect | `directconnect:DescribeConnections` |",
    "| Amazon DynamoDB | `dynamodb:ListTables` |": "| Amazon DynamoDB | `dynamodb:ListTables` |",
    "| Amazon DynamoDB (built-in) | `dynamodb:ListTables`, `dynamodb:ListTagsOfResource` |": "| Amazon DynamoDB (built-in) | `dynamodb:ListTables`, `dynamodb:ListTagsOfResource` |",
    "| Amazon EBS | `ec2:DescribeVolumes` |": "| Amazon EBS | `ec2:DescribeVolumes` |",
    "| Amazon EBS (built-in) | `ec2:DescribeVolumes` |": "| Amazon EBS (built-in) | `ec2:DescribeVolumes` |",
    "| Amazon EC2 API |  |": "| Amazon EC2 API |  |",
    "| Amazon EC2 (built-in) | `ec2:DescribeInstances` |": "| Amazon EC2 (built-in) | `ec2:DescribeInstances` |",
    "| Amazon EC2 Spot Fleet | `ec2:DescribeSpotFleetRequests` |": "| Amazon EC2 Spot Fleet | `ec2:DescribeSpotFleetRequests` |",
    "| Amazon Elastic Container Service (ECS) | `ecs:ListClusters` |": "| Amazon Elastic Container Service (ECS) | `ecs:ListClusters` |",
    "| Amazon ECS Container Insights | `ecs:ListClusters` |": "| Amazon ECS Container Insights | `ecs:ListClusters` |",
    "| Amazon ElastiCache (EC) | `elasticache:DescribeCacheClusters` |": "| Amazon ElastiCache (EC) | `elasticache:DescribeCacheClusters` |",
    "| AWS Elastic Beanstalk | `elasticbeanstalk:DescribeEnvironments` |": "| AWS Elastic Beanstalk | `elasticbeanstalk:DescribeEnvironments` |",
    "| Amazon Elastic File System (EFS) | `elasticfilesystem:DescribeFileSystems` |": "| Amazon Elastic File System (EFS) | `elasticfilesystem:DescribeFileSystems` |",
    "| Amazon Elastic Inference |  |": "| Amazon Elastic Inference |  |",
    "| Amazon Elastic Map Reduce (EMR) | `elasticmapreduce:ListClusters` |": "| Amazon Elastic Map Reduce (EMR) | `elasticmapreduce:ListClusters` |",
    "| Amazon Elasticsearch Service (ES) | `es:ListDomainNames` |": "| Amazon Elasticsearch Service (ES) | `es:ListDomainNames` |",
    "| Amazon Elastic Transcoder | `elastictranscoder:ListPipelines` |": "| Amazon Elastic Transcoder | `elastictranscoder:ListPipelines` |",
    "| Amazon Elastic Load Balancer (ELB) (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |": "| Amazon Elastic Load Balancer (ELB) (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |",
    "| Amazon EventBridge | `events:ListEventBuses` |": "| Amazon EventBridge | `events:ListEventBuses` |",
    "| Amazon FSx | `fsx:DescribeFileSystems` |": "| Amazon FSx | `fsx:DescribeFileSystems` |",
    "| Amazon GameLift | `gamelift:ListFleets` |": "| Amazon GameLift | `gamelift:ListFleets` |",
    "| AWS Glue | `glue:GetJobs` |": "| AWS Glue | `glue:GetJobs` |",
    "| Amazon Inspector | `inspector:ListAssessmentTemplates` |": "| Amazon Inspector | `inspector:ListAssessmentTemplates` |",
    "| AWS Internet of Things (IoT) |  |": "| AWS Internet of Things (IoT) |  |",
    "| AWS IoT Analytics |  |": "| AWS IoT Analytics |  |",
    "| Amazon Managed Streaming for Kafka | `kafka:ListClusters` |": "| Amazon Managed Streaming for Kafka | `kafka:ListClusters` |",
    "| Amazon Kinesis Data Analytics | `kinesisanalytics:ListApplications` |": "| Amazon Kinesis Data Analytics | `kinesisanalytics:ListApplications` |",
    "| Amazon Data Firehose | `firehose:ListDeliveryStreams` |": "| Amazon Data Firehose | `firehose:ListDeliveryStreams` |",
    "| Amazon Kinesis Data Streams | `kinesis:ListStreams` |": "| Amazon Kinesis Data Streams | `kinesis:ListStreams` |",
    "| Amazon Kinesis Video Streams | `kinesisvideo:ListStreams` |": "| Amazon Kinesis Video Streams | `kinesisvideo:ListStreams` |",
    "| AWS Lambda | `lambda:ListFunctions` |": "| AWS Lambda | `lambda:ListFunctions` |",
    "| AWS Lambda (built-in) | `lambda:ListFunctions`, `lambda:ListTags` |": "| AWS Lambda (built-in) | `lambda:ListFunctions`, `lambda:ListTags` |",
    "| Amazon Lex | `lex:GetBots` |": "| Amazon Lex | `lex:GetBots` |",
    "| Amazon Application and Network Load Balancer (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |": "| Amazon Application and Network Load Balancer (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |",
    "| Amazon CloudWatch Logs | `logs:DescribeLogGroups` |": "| Amazon CloudWatch Logs | `logs:DescribeLogGroups` |",
    "| AWS Elemental MediaConnect | `mediaconnect:ListFlows` |": "| AWS Elemental MediaConnect | `mediaconnect:ListFlows` |",
    "| AWS Elemental MediaConvert | `mediaconvert:DescribeEndpoints` |": "| AWS Elemental MediaConvert | `mediaconvert:DescribeEndpoints` |",
    "| AWS Elemental MediaPackage Live | `mediapackage:ListChannels` |": "| AWS Elemental MediaPackage Live | `mediapackage:ListChannels` |",
    "| AWS Elemental MediaPackage Video on Demand | `mediapackage-vod:ListPackagingConfigurations` |": "| AWS Elemental MediaPackage Video on Demand | `mediapackage-vod:ListPackagingConfigurations` |",
    "| AWS Elemental MediaTailor | `mediatailor:ListPlaybackConfigurations` |": "| AWS Elemental MediaTailor | `mediatailor:ListPlaybackConfigurations` |",
    "| Amazon VPC NAT Gateways | `ec2:DescribeNatGateways` |": "| Amazon VPC NAT Gateways | `ec2:DescribeNatGateways` |",
    "| Amazon Neptune | `rds:DescribeDBClusters` |": "| Amazon Neptune | `rds:DescribeDBClusters` |",
    "| AWS OpsWorks | `opsworks:DescribeStacks` |": "| AWS OpsWorks | `opsworks:DescribeStacks` |",
    "| Amazon Polly |  |": "| Amazon Polly |  |",
    "| Amazon QLDB | `qldb:ListLedgers` |": "| Amazon QLDB | `qldb:ListLedgers` |",
    "| Amazon RDS | `rds:DescribeDBInstances` |": "| Amazon RDS | `rds:DescribeDBInstances` |",
    "| Amazon RDS (built-in) | `rds:DescribeDBInstances`, `rds:DescribeEvents`, `rds:ListTagsForResource` |": "| Amazon RDS (built-in) | `rds:DescribeDBInstances`, `rds:DescribeEvents`, `rds:ListTagsForResource` |",
    "| Amazon Redshift | `redshift:DescribeClusters` |": "| Amazon Redshift | `redshift:DescribeClusters` |",
    "| Amazon Rekognition |  |": "| Amazon Rekognition |  |",
    "| AWS RoboMaker | `robomaker:ListSimulationJobs` |": "| AWS RoboMaker | `robomaker:ListSimulationJobs` |",
    "| Amazon Route 53 | `route53:ListHostedZones` |": "| Amazon Route 53 | `route53:ListHostedZones` |",
    "| Amazon Route 53 Resolver | `route53resolver:ListResolverEndpoints` |": "| Amazon Route 53 Resolver | `route53resolver:ListResolverEndpoints` |",
    "| Amazon S3 | `s3:ListAllMyBuckets` |": "| Amazon S3 | `s3:ListAllMyBuckets` |",
    "| Amazon S3 (built-in) | `s3:ListAllMyBuckets` |": "| Amazon S3 (built-in) | `s3:ListAllMyBuckets` |",
    "| Amazon SageMaker Batch Transform Jobs |  |": "| Amazon SageMaker Batch Transform Jobs |  |",
    "| Amazon SageMaker Endpoint Instances | `sagemaker:ListEndpoints` |": "| Amazon SageMaker Endpoint Instances | `sagemaker:ListEndpoints` |",
    "| Amazon SageMaker Endpoints | `sagemaker:ListEndpoints` |": "| Amazon SageMaker Endpoints | `sagemaker:ListEndpoints` |",
    "| Amazon SageMaker Ground Truth |  |": "| Amazon SageMaker Ground Truth |  |",
    "| Amazon SageMaker Processing Jobs |  |": "| Amazon SageMaker Processing Jobs |  |",
    "| Amazon SageMaker Training Jobs |  |": "| Amazon SageMaker Training Jobs |  |",
    "| AWS Service Catalog |  |": "| AWS Service Catalog |  |",
    "| Amazon Simple Email Service (SES) |  |": "| Amazon Simple Email Service (SES) |  |",
    "| Amazon Simple Notification Service (SNS) | `sns:ListTopics` |": "| Amazon Simple Notification Service (SNS) | `sns:ListTopics` |",
    "| Amazon Simple Queue Service (SQS) | `sqs:ListQueues` |": "| Amazon Simple Queue Service (SQS) | `sqs:ListQueues` |",
    "| AWS Systems Manager - Run Command |  |": "| AWS Systems Manager - Run Command |  |",
    "| AWS Step Functions |  |": "| AWS Step Functions |  |",
    "| AWS Storage Gateway | `storagegateway:ListGateways` |": "| AWS Storage Gateway | `storagegateway:ListGateways` |",
    "| Amazon SWF | `swf:ListDomains` |": "| Amazon SWF | `swf:ListDomains` |",
    "| Amazon Textract |  |": "| Amazon Textract |  |",
    "| AWS IoT Things Graph |  |": "| AWS IoT Things Graph |  |",
    "| AWS Transfer Family | `transfer:ListServers` |": "| AWS Transfer Family | `transfer:ListServers` |",
    "| AWS Transit Gateway | `ec2:DescribeTransitGateways` |": "| AWS Transit Gateway | `ec2:DescribeTransitGateways` |",
    "| Amazon Translate |  |": "| Amazon Translate |  |",
    "| AWS Trusted Advisor |  |": "| AWS Trusted Advisor |  |",
    "| AWS API Usage |  |": "| AWS API Usage |  |",
    "| AWS Site-to-Site VPN | `ec2:DescribeVpnConnections` |": "| AWS Site-to-Site VPN | `ec2:DescribeVpnConnections` |",
    "| AWS WAF Classic |  |": "| AWS WAF Classic |  |",
    "| AWS WAF |  |": "| AWS WAF |  |",
    "| Amazon WorkMail | `workmail:ListOrganizations` |": "| Amazon WorkMail | `workmail:ListOrganizations` |",
    "| Amazon WorkSpaces | `workspaces:DescribeWorkspaces` |": "| Amazon WorkSpaces | `workspaces:DescribeWorkspaces` |",
    "## Access method": "## Метод доступа",
    "To get the information required for comprehensive AWS cloud-computing monitoring, Dynatrace needs to identify all the virtualized infrastructure components in your AWS environment and collect performance metrics related to those components. We use this information to understand the context of your applications, services, and hosts. For this to happen, you need to authorize Dynatrace to access your Amazon metrics.": "Для получения информации, необходимой для комплексного мониторинга облачных вычислений AWS, Dynatrace должен идентифицировать все компоненты виртуализированной инфраструктуры в AWS-окружении и собирать метрики производительности этих компонентов. Эта информация используется для понимания контекста приложений, сервисов и хостов. Для этого необходимо авторизовать доступ Dynatrace к метрикам Amazon.",
    "Make sure that your Environment ActiveGate or Managed Cluster has a working connection to AWS. Configure your proxy for [Managed](/managed/managed-cluster/configuration/internet-proxy \"Configure a proxy connection for your Managed Cluster if you don't have direct internet access.\") or [ActiveGate](/managed/ingest-from/dynatrace-activegate/configuration/set-up-proxy-authentication-for-activegate \"Learn how to configure ActiveGate properties to set up a proxy.\"), or allow access to `*.amazonaws.com` in your firewall settings.": "Убедитесь, что Environment ActiveGate или Managed Cluster имеет рабочее подключение к AWS. Настройте прокси для [Managed](/managed/managed-cluster/configuration/internet-proxy \"Настройка прокси-подключения для Managed Cluster при отсутствии прямого доступа в интернет.\") или [ActiveGate](/managed/ingest-from/dynatrace-activegate/configuration/set-up-proxy-authentication-for-activegate \"Узнайте, как настроить свойства ActiveGate для работы через прокси.\"), либо разрешите доступ к `*.amazonaws.com` в настройках брандмауэра.",
    "## Role-based access with Environment ActiveGate or Dynatrace Managed Server": "## Доступ на основе ролей с Environment ActiveGate или Dynatrace Managed Server",
    "The instructions below apply whether or not the account hosting your ActiveGate is the same as your monitored account.": "Приведённые ниже инструкции применяются независимо от того, совпадает ли аккаунт, в котором размещён ActiveGate, с отслеживаемым аккаунтом.",
    "In a typical setup, you need to create two CloudFormation stacks using CloudFormation templates:": "В типовой конфигурации необходимо создать два стека CloudFormation с использованием шаблонов CloudFormation:",
    "* A CloudFormation stack from the account hosting your ActiveGate, containing the following resources:": "* Стек CloudFormation из аккаунта, в котором размещён ActiveGate, содержащий следующие ресурсы:",
    "+ A role for your Environment ActiveGate or Dynatrace Managed Server hosted in your AWS infrastructure, on an Amazon EC2 host.": "+ роль для Environment ActiveGate или Dynatrace Managed Server, размещённого в инфраструктуре AWS на хосте Amazon EC2;",
    "+ Its attached policy, which defines the monitored account permissions.": "+ прикреплённую политику, определяющую разрешения отслеживаемого аккаунта.",
    "* A CloudFormation stack from the monitored account, containing the following resources:": "* Стек CloudFormation из отслеживаемого аккаунта, содержащий следующие ресурсы:",
    "+ A dedicated monitoring role for Dynatrace in your AWS account.": "+ выделенную роль мониторинга для Dynatrace в AWS-аккаунте;",
    "+ Its attached policy, which defines the Dynatrace authentication permissions to your AWS environment.": "+ прикреплённую политику, определяющую разрешения аутентификации Dynatrace для AWS-окружения.",
    "To monitor multiple accounts, add all resources to the **Resource** array in the template in [Step 1](#step1) and repeat [Step 2](#step2) to create a stack for each monitored account.": "Для мониторинга нескольких аккаунтов добавьте все ресурсы в массив **Resource** шаблона в [Шаге 1](#step1) и повторите [Шаг 2](#step2) для создания стека для каждого отслеживаемого аккаунта.",
    "### Prerequisites for role-based access, with Environment ActiveGate or Dynatrace Managed Server": "### Предварительные требования для доступа на основе ролей с Environment ActiveGate или Dynatrace Managed Server",
    "* [Dynatrace Managed Server](/managed/managed-cluster/installation/install-managed-cluster \"Install a Managed Cluster by downloading and verifying the installer, running it, and completing the initial configuration.\") installed on an Amazon EC2 host. It must be able to assume a role within your AWS account that allows it to read the Dynatrace monitoring data.": "* [Dynatrace Managed Server](/managed/managed-cluster/installation/install-managed-cluster \"Установите Managed Cluster, загрузив и проверив установщик, запустив его и выполнив начальную конфигурацию.\"), установленный на хосте Amazon EC2. Он должен иметь возможность принять роль в AWS-аккаунте, разрешающую чтение данных мониторинга Dynatrace.",
    "* The ID of the AWS account that hosts the ActiveGate (for example, the account that hosts your Dynatrace components, which in this case is the one hosting Environment ActiveGate or Dynatrace Managed Server).": "* Идентификатор AWS-аккаунта, в котором размещён ActiveGate (например, аккаунт, в котором размещены компоненты Dynatrace, в данном случае это аккаунт с Environment ActiveGate или Dynatrace Managed Server).",
    "* The Amazon Web Services monitored account ID (the account you want to monitor).": "* Идентификатор отслеживаемого AWS-аккаунта (аккаунт, который требуется мониторить).",
    "* The name of the role with which your Environment ActiveGate or Dynatrace Managed Server was started.": "* Имя роли, с которой был запущен Environment ActiveGate или Dynatrace Managed Server.",
    "* The External ID.": "* Внешний идентификатор (External ID).",
    "How to get the External ID": "Как получить внешний идентификатор",
    "1. Go to **Settings**.": "1. Перейдите в **Settings**.",
    "2. Select **Cloud and virtualization** > **AWS** > **Connect new instance**.": "2. Выберите **Cloud and virtualization** > **AWS** > **Connect new instance**.",
    "3. Under **Authentication method**, select **Role-based authentication**.": "3. В разделе **Authentication method** выберите **Role-based authentication**.",
    "4. Under **Your Amazon account ID**, select **Copy** to copy the token (the External ID).": "4. В разделе **Your Amazon account ID** нажмите **Copy**, чтобы скопировать токен (внешний идентификатор).",
    "To enable access to your Amazon account using role-based access, follow the steps below.": "Чтобы разрешить доступ к Amazon-аккаунту с использованием доступа на основе ролей, выполните следующие шаги.",
    "[![Step 1](https://dt-cdn.net/images/step-1-086e22066c.svg \"Step 1\")": "[![Шаг 1](https://dt-cdn.net/images/step-1-086e22066c.svg \"Шаг 1\")",
    "**Create a role for ActiveGate on the account that hosts ActiveGate**](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#step1 \"Connect your Amazon account with Dynatrace Managed and start monitoring.\")[![Step 2](https://dt-cdn.net/images/step-2-1a1384627e.svg \"Step 2\")": "**Создание роли для ActiveGate в аккаунте, где размещён ActiveGate**](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#step1 \"Подключите Amazon-аккаунт к Dynatrace Managed и начните мониторинг.\")[![Шаг 2](https://dt-cdn.net/images/step-2-1a1384627e.svg \"Шаг 2\")",
    "**Create a monitoring role for Dynatrace on your monitored account**](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#step2 \"Connect your Amazon account with Dynatrace Managed and start monitoring.\")[![Step 3](https://dt-cdn.net/images/step-3-350cf6c19a.svg \"Step 3\")": "**Создание роли мониторинга для Dynatrace в отслеживаемом аккаунте**](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#step2 \"Подключите Amazon-аккаунт к Dynatrace Managed и начните мониторинг.\")[![Шаг 3](https://dt-cdn.net/images/step-3-350cf6c19a.svg \"Шаг 3\")",
    "**Modify ActiveGate configuration**](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#step3 \"Connect your Amazon account with Dynatrace Managed and start monitoring.\")": "**Изменение конфигурации ActiveGate**](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#step3 \"Подключите Amazon-аккаунт к Dynatrace Managed и начните мониторинг.\")",
    "### Step 1 Create a role for ActiveGate on the account that hosts ActiveGate": "### Шаг 1 Создание роли для ActiveGate в аккаунте, где размещён ActiveGate",
    "1. Create a YAML file and paste the contents of [github `role_based_access_AG_account_template.yml`](https://dt-url.net/2t03ydj).": "1. Создайте YAML-файл и вставьте содержимое [github `role_based_access_AG_account_template.yml`](https://dt-url.net/2t03ydj).",
    "For multiple monitored accounts": "Для нескольких отслеживаемых аккаунтов",
    "For each account you want to monitor, in the **Resource** section of the template above, add a new item to the `!Sub` array in the following format: `'arn:aws:iam::<new_monitored_account_id>:role/<new_monitoring_role_name>'`.": "Для каждого аккаунта, который требуется отслеживать, в разделе **Resource** приведённого выше шаблона добавьте новый элемент в массив `!Sub` в следующем формате: `'arn:aws:iam::<new_monitored_account_id>:role/<new_monitoring_role_name>'`.",
    "Be sure to replace the placeholders (`<new_monitored_account_id>` and `<new_monitoring_role_name>`) with your own values.": "Обязательно замените заполнители (`<new_monitored_account_id>` и `<new_monitoring_role_name>`) собственными значениями.",
    "2. Create the stack in your Amazon Console or using the CLI.": "2. Создайте стек в Amazon Console или через CLI.",
    "In the Amazon Console": "В Amazon Console",
    "1. In your Amazon Console, go to CloudFormation.": "1. В Amazon Console перейдите в CloudFormation.",
    "2. Go to **Stacks** and create a new stack with new resources.": "2. Перейдите в **Stacks** и создайте новый стек с новыми ресурсами.",
    "3. Select **Template is ready**, upload the template you created above, and select **Next**.": "3. Выберите **Template is ready**, загрузите созданный выше шаблон и нажмите **Next**.",
    "4. In **Parameters**, for **MonitoredAccountID**, enter the ID of the account Dynatrace will monitor. Optionally, adapt other parameters as needed.": "4. В разделе **Parameters** в поле **MonitoredAccountID** введите идентификатор аккаунта, который будет отслеживаться Dynatrace. При необходимости адаптируйте другие параметры.",
    "5. Enter a name for your stack, and then select **Next** twice.": "5. Введите имя стека, затем дважды нажмите **Next**.",
    "6. Review your configuration, select **I acknowledge that AWS CloudFormation might create IAM resources with custom names**, and select **Create stack**.": "6. Проверьте конфигурацию, установите флажок **I acknowledge that AWS CloudFormation might create IAM resources with custom names** и нажмите **Create stack**.",
    "Using the CLI": "Через CLI",
    "Run the command below, making sure to replace the parameter values with your actual values.": "Выполните приведённую ниже команду, заменив значения параметров фактическими.",
    "You need to remove the angle brackets (`<` and `>`).": "Угловые скобки (`<` и `>`) необходимо удалить.",
    "3. Go to the Amazon EC2 console, right-click an instance hosting your Environment ActiveGate, and select **Security** > **Modify IAM role**.": "3. Перейдите в консоль Amazon EC2, щёлкните правой кнопкой мыши экземпляр, на котором размещён Environment ActiveGate, и выберите **Security** > **Modify IAM role**.",
    "4. Select the role you created at step 1 (for example, Dynatrace\\_ActiveGate\\_role), and select **Apply**.": "4. Выберите роль, созданную на шаге 1 (например, Dynatrace\\_ActiveGate\\_role), и нажмите **Apply**.",
    "### Step 2 Create a monitoring role for Dynatrace on your monitored account": "### Шаг 2 Создание роли мониторинга для Dynatrace в отслеживаемом аккаунте",
    "After the `Dynatrace_ActiveGate_role` is created on the account hosting the ActiveGate, create a role for the account to be monitored.": "После создания `Dynatrace_ActiveGate_role` в аккаунте, где размещён ActiveGate, создайте роль для отслеживаемого аккаунта.",
    "1. Create a YAML file and paste the content from the [github `role_based_access_monitored_account_template.yml`](https://dt-url.net/pm03yni).": "1. Создайте YAML-файл и вставьте содержимое [github `role_based_access_monitored_account_template.yml`](https://dt-url.net/pm03yni).",
    "2. Create the stack in your Amazon Console or using the CLI.": "2. Создайте стек в Amazon Console или через CLI.",
    "1. In your Amazon Console, go to CloudFormation.": "1. В Amazon Console перейдите в CloudFormation.",
    "2. Go to **Stacks** and create a new stack with new resources.": "2. Перейдите в **Stacks** и создайте новый стек с новыми ресурсами.",
    "3. Select **Template is ready**, upload the template you created above, and select **Next**.": "3. Выберите **Template is ready**, загрузите созданный выше шаблон и нажмите **Next**.",
    "4. In **Parameters**, enter:": "4. В разделе **Parameters** введите:",
    "* The **External ID**. For details, see [Prerequisites](#env-ag)": "* **External ID**. Подробнее см. [Предварительные требования](#env-ag).",
    "* The **ActiveGateRoleName** and the **ActiveGateAccountID** from the stack created in [Step 1](#step1).": "* **ActiveGateRoleName** и **ActiveGateAccountID** из стека, созданного в [Шаге 1](#step1).",
    "Optionally, adapt other parameters as needed.": "При необходимости адаптируйте другие параметры.",
    "5. Enter a name for your stack, and then select **Next** twice.": "5. Введите имя стека, затем дважды нажмите **Next**.",
    "6. Review your configuration, enable **I acknowledge that AWS CloudFormation might create IAM resources with custom names**, and select **Create stack**.": "6. Проверьте конфигурацию, установите флажок **I acknowledge that AWS CloudFormation might create IAM resources with custom names** и нажмите **Create stack**.",
    "### Step 3 Modify ActiveGate configuration": "### Шаг 3 Изменение конфигурации ActiveGate",
    "Starting with ActiveGate version 1.217, AWS monitoring is enabled by default. For configuration details, see [Customize ActiveGate properties](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#aws-monitoring \"Learn which ActiveGate properties you can configure based on your needs and requirements.\"). The following configuration settings refer to earlier ActiveGate versions.": "Начиная с ActiveGate версии 1.217, мониторинг AWS включён по умолчанию. Подробнее о конфигурации см. [Настройка свойств ActiveGate](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate#aws-monitoring \"Узнайте, какие свойства ActiveGate можно настроить в соответствии с потребностями и требованиями.\"). Следующие параметры конфигурации относятся к более ранним версиям ActiveGate.",
    "1. Edit the [`custom.properties`](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate \"Learn which ActiveGate properties you can configure based on your needs and requirements.\") configuration file of the ActiveGate that you want to use for AWS monitoring.": "1. Отредактируйте файл конфигурации [`custom.properties`](/managed/ingest-from/dynatrace-activegate/configuration/configure-activegate \"Узнайте, какие свойства ActiveGate можно настроить в соответствии с потребностями и требованиями.\") ActiveGate, который планируется использовать для мониторинга AWS.",
    "2. Set the following properties as below:": "2. Задайте следующие свойства:",
    "ActiveGate version 1.183 or earlier": "ActiveGate версии 1.183 и ниже",
    "Multiple ActiveGates": "Несколько ActiveGate",
    "It's enough to use only one ActiveGate dedicated for AWS monitoring. However, some deployment scenarios (for example, for redundancy purposes) might require multiple ActiveGates in your deployment.": "Достаточно одного ActiveGate, выделенного для мониторинга AWS. Однако некоторые сценарии развёртывания (например, для обеспечения избыточности) могут потребовать нескольких ActiveGate.",
    "Make sure that only properly configured ActiveGates have `aws_monitoring_enabled` set to `true`.": "Убедитесь, что только надлежащим образом настроенные ActiveGate имеют `aws_monitoring_enabled` со значением `true`.",
    "* They need network access to AWS endpoints.": "* Им необходим сетевой доступ к эндпоинтам AWS.",
    "* For role-based monitoring, they must have proper roles attached.": "* Для мониторинга на основе ролей к ним должны быть прикреплены соответствующие роли.",
    "Keep in mind that Dynatrace cluster nodes contain embedded ActiveGates. Make sure to set the `aws_monitoring_enabled` property to `false` on these ActiveGates if they're not configured fully for AWS monitoring.": "Учтите, что узлы кластера Dynatrace содержат встроенные ActiveGate. Для таких ActiveGate, не настроенных полностью для мониторинга AWS, необходимо установить свойство `aws_monitoring_enabled` в `false`.",
    "If the ActiveGate is dedicated to AWS monitoring, you must also set the `MSGrouter` property to `false`:": "Если ActiveGate предназначен только для мониторинга AWS, также необходимо установить свойство `MSGrouter` в `false`:",
    "Remove `aws_proxy_account` and `aws_proxy_role` properties.": "Удалите свойства `aws_proxy_account` и `aws_proxy_role`.",
    "3. Save the file and [restart the ActiveGate main service](/managed/ingest-from/dynatrace-activegate/operation/stop-restart-activegate \"Learn how you can start, stop and restart ActiveGate on Windows or Linux.\").": "3. Сохраните файл и [перезапустите основной сервис ActiveGate](/managed/ingest-from/dynatrace-activegate/operation/stop-restart-activegate \"Узнайте, как запустить, остановить и перезапустить ActiveGate в Windows или Linux.\").",
    "Key-based access (AWS GovCloud and AWS China only)": "Доступ на основе ключей (только для AWS GovCloud и AWS China)",
    "Key-based authentication is only allowed for AWS GovCloud and China partitions.": "Аутентификация на основе ключей разрешена только для разделов AWS GovCloud и China.",
    "In this scenario, you have to create an AWS monitoring policy and generate a key pair with that policy.": "В этом сценарии необходимо создать политику мониторинга AWS и сгенерировать пару ключей с этой политикой.",
    "AWS IAM permissions boundaries may prohibit AWS actions required by Dynatrace. If you use an IAM permissions boundary on your AWS account, make sure that the actions from that policy are allowed in all AWS Regions within that permissions boundary.": "Границы разрешений AWS IAM могут запрещать действия AWS, необходимые Dynatrace. При использовании границы разрешений IAM в AWS-аккаунте убедитесь, что действия из этой политики разрешены во всех регионах AWS в пределах этой границы.",
    "To create the AWS monitoring policy": "Для создания политики мониторинга AWS",
    "1. In your Amazon Console, go to **Identity and Access Management**.": "1. В Amazon Console перейдите в **Identity and Access Management**.",
    "2. Go to **Policies** and select **Create policy**.": "2. Перейдите в **Policies** и выберите **Create policy**.",
    "3. Select the JSON tab and paste the predefined policy from the box below.": "3. Выберите вкладку JSON и вставьте предопределённую политику из блока ниже.",
    "4. Give the policy a name.": "4. Задайте имя политики.",
    "5. Select **Create policy**.": "5. Нажмите **Create policy**.",
    "Dynatrace can use access keys to make secure REST or Query protocol requests to the AWS service API. You'll need to generate an **Access key ID** and a **Secret access key** that Dynatrace can use to get metrics from Amazon Web Services.": "Dynatrace может использовать ключи доступа для выполнения безопасных запросов по протоколу REST или Query к API сервиса AWS. Необходимо сгенерировать **Access key ID** и **Secret access key**, которые Dynatrace будет использовать для получения метрик из Amazon Web Services.",
    "6. In your Amazon Console, go to **Users** and select **Add Users**.": "6. В Amazon Console перейдите в **Users** и выберите **Add Users**.",
    "7. Enter the **User name**.": "7. Введите **User name**.",
    "8. In the next screen, choose **Attach policies directly** and attach the policy that you created before.": "8. На следующем экране выберите **Attach policies directly** и прикрепите ранее созданную политику.",
    "9. Review the user details and select **Create user**.": "9. Проверьте данные пользователя и нажмите **Create user**.",
    "10. From the list of users, select your newly created user name and go to **Security credentials**, then select **Create access key**.": "10. В списке пользователей выберите только что созданного пользователя, перейдите в **Security credentials** и нажмите **Create access key**.",
    "11. In the **Access key best practices & alternatives** screen, select **Third-party service**, then select **Next**.": "11. На экране **Access key best practices & alternatives** выберите **Third-party service**, затем нажмите **Next**.",
    "12. You will be transferred to the **Retrieve access keys** screen, where both your **Access key** and a **Secret access key** are present.": "12. Откроется экран **Retrieve access keys**, на котором отображаются **Access key** и **Secret access key**.",
    "13. Store the **Access Key ID** name (AKID) and **Secret access key** values.": "13. Сохраните значения **Access Key ID** (AKID) и **Secret access key**.",
    "14. You can either download the user credentials or copy the credentials displayed online (select **Show**).": "14. Можно либо загрузить учётные данные пользователя, либо скопировать отображаемые онлайн учётные данные (нажмите **Show**).",
    "## Connect your Amazon account": "## Подключение Amazon-аккаунта",
    "Once you've granted AWS access to Dynatrace, it's time to connect Dynatrace to your Amazon AWS account.": "После предоставления Dynatrace доступа к AWS можно подключить Dynatrace к Amazon AWS-аккаунту.",
    "1. In Dynatrace, go to **Settings > Cloud and virtualization > AWS** and select **Connect new instance**.": "1. В Dynatrace перейдите в **Settings > Cloud and virtualization > AWS** и нажмите **Connect new instance**.",
    "2. Select the **Role-based authentication** method.": "2. Выберите метод **Role-based authentication**.",
    "* Create a name for this connection. If you leave this field empty, the name **Role** will be used on Dynatrace pages to define this connection.": "* Задайте имя для этого подключения. Если поле оставить пустым, для определения подключения на страницах Dynatrace будет использоваться имя **Role**.",
    "* In the **Role** field, type the name of the role you created in Amazon for Dynatrace (for example, `Dynatrace_monitoring_role`).": "* В поле **Role** введите имя роли, созданной в Amazon для Dynatrace (например, `Dynatrace_monitoring_role`).",
    "* Type your **Account ID** (the account you want us to pull metrics from).": "* Введите **Account ID** (аккаунт, из которого будут запрашиваться метрики).",
    "* Select **Connect** to verify and save the connection.": "* Нажмите **Connect** для проверки и сохранения подключения.",
    "3. Once the connection is successfully verified and saved, your AWS account will be listed in the **Cloud and virtualization** settings page.": "3. После успешной проверки и сохранения подключения AWS-аккаунт отобразится на странице настроек **Cloud and virtualization**.",
    "You should soon begin to see AWS cloud monitoring data.": "Вскоре станут доступны данные мониторинга облака AWS.",
    "## Select your AWS partition": "## Выбор раздела AWS",
    "If your AWS account is on a different partition than the default `aws` partition, you can select it and Dynatrace will connect to it instead.": "Если AWS-аккаунт находится в разделе, отличном от раздела `aws` по умолчанию, его можно выбрать, и Dynatrace будет подключаться именно к нему.",
    "To change your AWS partition": "Для изменения раздела AWS",
    "1. Go to **Settings** > **Cloud and virtualization** > **AWS**.": "1. Перейдите в **Settings** > **Cloud and virtualization** > **AWS**.",
    "2. Find the instance where you want to change the partition and select ![Edit](https://dt-cdn.net/images/edit-icon-a083c62c49.svg \"Edit\") to edit the instance.": "2. Найдите экземпляр, для которого требуется изменить раздел, и нажмите ![Edit](https://dt-cdn.net/images/edit-icon-a083c62c49.svg \"Edit\") для его редактирования.",
    "3. In the **AWS partition** list, select your partition.": "3. В списке **AWS partition** выберите раздел.",
    "4. Select **Save**.": "4. Нажмите **Save**.",
    "## Adjust monitoring to your needs": "## Настройка мониторинга",
    "You can alter the scope and content of your monitoring depending on your preferences by using tags and listing services needed.": "Область и содержимое мониторинга можно настроить под свои потребности с помощью тегов и перечня необходимых сервисов.",
    "### Limit monitored resources using tags": "### Ограничение отслеживаемых ресурсов с помощью тегов",
    "We recommend that you limit the scope of your AWS monitoring and reduce the number API calls to Amazon. You can use [tagging](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/limit-api-calls-to-aws-using-tags \"Add and configure AWS tags to limit AWS resources.\") to limit the AWS resources (AWS service instances) that are monitored by Dynatrace.": "Рекомендуется ограничить область мониторинга AWS и сократить количество API-вызовов к Amazon. Для ограничения ресурсов AWS (экземпляров сервисов AWS), отслеживаемых Dynatrace, можно использовать [теги](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/limit-api-calls-to-aws-using-tags \"Добавьте и настройте теги AWS для ограничения ресурсов AWS.\").",
    "## Set up metric events for alerting": "## Настройка метрических событий для оповещений",
    "To configure metric events for alerting, follow this [guide](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/aws-set-up-metric-events-for-alerting \"Set up and configure metric events for alerting.\").": "Для настройки метрических событий для оповещений следуйте этому [руководству](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/aws-set-up-metric-events-for-alerting \"Настройка метрических событий для оповещений.\").",
    "### Choose Cloud services to be monitored": "### Выбор облачных сервисов для мониторинга",
    "Once your credentials are saved, you can decide which services will be monitored.": "После сохранения учётных данных можно выбрать отслеживаемые сервисы.",
    "To select your preferred services": "Для выбора нужных сервисов",
    "1. Go to **Settings** > **Cloud and virtualization** > **AWS**.": "1. Перейдите в **Settings** > **Cloud and virtualization** > **AWS**.",
    "2. Find the instance where you want to perform your monitoring and select ![Edit](https://dt-cdn.net/images/edit-icon-a083c62c49.svg \"Edit\") to edit the instance.": "2. Найдите экземпляр, для которого требуется выполнить мониторинг, и нажмите ![Edit](https://dt-cdn.net/images/edit-icon-a083c62c49.svg \"Edit\") для его редактирования.",
    "3. In the **Services** section, select **Manage services**.": "3. В разделе **Services** нажмите **Manage services**.",
    "4. The following services are added by default: Amazon EC2, AWS Lambda, Amazon RDS, Amazon DynamoDB, Amazon ALB, Amazon ELB, Amazon S3, and Amazon EBS. You can extend this list by choosing services from the dropdown menu. The full list of services is also available at [All AWS cloud services](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Monitor all AWS cloud services with Dynatrace and view available metrics.\").": "4. По умолчанию добавлены следующие сервисы: Amazon EC2, AWS Lambda, Amazon RDS, Amazon DynamoDB, Amazon ALB, Amazon ELB, Amazon S3 и Amazon EBS. Список можно расширить, выбирая сервисы из выпадающего меню. Полный список сервисов также доступен в разделе [Все облачные сервисы AWS](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Мониторинг всех облачных сервисов AWS с помощью Dynatrace и просмотр доступных метрик.\").",
    "5. Select **Add service**": "5. Нажмите **Add service**.",
    "6. Select the service from the list and then select **Add service**.": "6. Выберите сервис из списка, затем нажмите **Add service**.",
    "7. Select **Save changes** to save your configuration.": "7. Нажмите **Save changes** для сохранения конфигурации.",
    "## Related topics": "## Связанные темы",
    "* [Set up Dynatrace on Amazon Web Services](/managed/ingest-from/amazon-web-services \"Set up and configure monitoring for Amazon Web Services.\")": "* [Настройка Dynatrace для Amazon Web Services](/managed/ingest-from/amazon-web-services \"Настройка и конфигурация мониторинга для Amazon Web Services.\")",
    "* [Dynatrace OneAgent](/managed/ingest-from/dynatrace-oneagent \"Understand the important concepts related to OneAgent and find out how to install and operate OneAgent on different platforms.\")": "* [Dynatrace OneAgent](/managed/ingest-from/dynatrace-oneagent \"Изучите ключевые концепции, связанные с OneAgent, и узнайте, как устанавливать OneAgent на разных платформах и работать с ним.\")",
    "* [Limit API calls to AWS using tags](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/limit-api-calls-to-aws-using-tags \"Add and configure AWS tags to limit AWS resources.\")": "* [Ограничение API-вызовов к AWS с помощью тегов](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics/limit-api-calls-to-aws-using-tags \"Добавьте и настройте теги AWS, чтобы ограничить ресурсы AWS.\")",
}

PASS = set()

build_one(REL, "set-up-aws-monitoring-with-managed.md", TRANS, PASS)
qa_one(REL, "set-up-aws-monitoring-with-managed.md")
