# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from _zos_canon_l4if71 import build_one, qa_one

REL = "ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics"

TRANS = {
    "title: Monitor AWS Elastic Beanstalk with CloudWatch metrics": "title: Мониторинг AWS Elastic Beanstalk с помощью метрик CloudWatch",
    "# Monitor AWS Elastic Beanstalk with CloudWatch metrics": "# Мониторинг AWS Elastic Beanstalk с помощью метрик CloudWatch",
    "* How-to guide": "* Практическое руководство",
    "* 6-min read": "* Чтение: 6 мин",
    "* Published Sep 08, 2020": "* Обновлено 08 сентября 2020 г.",
    "Dynatrace ingests metrics for multiple preselected namespaces, including AWS Elastic Beanstalk. You can view metrics for each service instance, split metrics into multiple dimensions, and create custom charts that you can pin to your dashboards.": "Dynatrace получает метрики для множества предварительно выбранных пространств имён, включая AWS Elastic Beanstalk. Можно просматривать метрики для каждого экземпляра сервиса, разделять метрики по нескольким измерениям и создавать пользовательские графики, которые можно закрепить на панелях мониторинга.",
    "## Prerequisites": "## Предварительные требования",
    "To enable monitoring for this service, you need": "Для включения мониторинга этого сервиса вам необходимо",
    "* ActiveGate version 1.197+": "* ActiveGate версии 1.197+",
    "* For Dynatrace Managed deployments, you can use any kind of ActiveGate.": "* Для развёртываний Dynatrace Managed можно использовать любой тип ActiveGate.",
    "For role-based access in a [Managed](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#role-based-access \"Connect your Amazon account with Dynatrace Managed and start monitoring.\") deployment, you need an [Environment ActiveGate](/managed/ingest-from/dynatrace-activegate/installation \"Learn how to configure ActiveGate\") installed on an Amazon EC2 host.": "Для доступа на основе ролей в развёртывании [Managed](/managed/ingest-from/amazon-web-services/set-up-aws-monitoring-with-managed#role-based-access \"Подключите учётную запись Amazon к Dynatrace Managed и начните мониторинг.\") требуется [Environment ActiveGate](/managed/ingest-from/dynatrace-activegate/installation \"Настройте ActiveGate\"), установленный на хосте Amazon EC2.",
    "* Dynatrace version 1.201+": "* Dynatrace версии 1.201+",
    "* An updated [AWS monitoring policy](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics#monitoring-policy \"Integrate metrics from Amazon CloudWatch.\") to include the additional AWS services.": "* Обновлённая [AWS monitoring policy](/managed/ingest-from/amazon-web-services/integrate-with-aws/cloudwatch-metrics#monitoring-policy \"Интеграция метрик из Amazon CloudWatch.\") для включения дополнительных сервисов AWS.",
    "To [update the AWS IAM policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-edit.html#edit-managed-policy-console), use the JSON below, containing the monitoring policy (permissions) for all supporting services.": "Чтобы [обновить AWS IAM policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-edit.html#edit-managed-policy-console), используйте приведённый ниже JSON, содержащий политику мониторинга (разрешения) для всех поддерживаемых сервисов.",
    "JSON predefined policy for all supporting services": "Предопределённая JSON-политика для всех поддерживаемых сервисов",
    "If you don't want to add permissions to all services, and just select permissions for certain services, consult the table below. The table contains a set of permissions that are required for [All AWS cloud services](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Monitor all AWS cloud services with Dynatrace and view available metrics.\") and, for each supporting service, a list of optional permissions specific to that service.": "Если вы не хотите добавлять разрешения для всех сервисов и хотите выбрать разрешения только для определённых сервисов, обратитесь к таблице ниже. Таблица содержит набор разрешений, необходимых для [All AWS cloud services](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-all-services \"Мониторинг всех облачных сервисов AWS с помощью Dynatrace и просмотр доступных метрик.\"), а также для каждого поддерживаемого сервиса список необязательных разрешений, специфичных для этого сервиса.",
    "Permissions required for AWS monitoring integration:": "Разрешения, необходимые для интеграции мониторинга AWS:",
    "* `\"cloudwatch:GetMetricData\"`": "* `\"cloudwatch:GetMetricData\"`",
    "* `\"cloudwatch:GetMetricStatistics\"`": "* `\"cloudwatch:GetMetricStatistics\"`",
    "* `\"cloudwatch:ListMetrics\"`": "* `\"cloudwatch:ListMetrics\"`",
    "* `\"sts:GetCallerIdentity\"`": "* `\"sts:GetCallerIdentity\"`",
    "* `\"tag:GetResources\"`": "* `\"tag:GetResources\"`",
    "* `\"tag:GetTagKeys\"`": "* `\"tag:GetTagKeys\"`",
    "* `\"ec2:DescribeAvailabilityZones\"`": "* `\"ec2:DescribeAvailabilityZones\"`",
    "### Complete list of permissions for cloud services": "### Полный список разрешений для облачных сервисов",
    "| Name | Permissions |": "| Название | Разрешения |",
    "| --- | --- |": "| --- | --- |",
    "| All monitored Amazon services Required | `cloudwatch:GetMetricData`, `cloudwatch:GetMetricStatistics`, `cloudwatch:ListMetrics`, `sts:GetCallerIdentity`, `tag:GetResources`, `tag:GetTagKeys`, `ec2:DescribeAvailabilityZones` |": "| Все отслеживаемые сервисы Amazon (обязательно) | `cloudwatch:GetMetricData`, `cloudwatch:GetMetricStatistics`, `cloudwatch:ListMetrics`, `sts:GetCallerIdentity`, `tag:GetResources`, `tag:GetTagKeys`, `ec2:DescribeAvailabilityZones` |",
    "| AWS Certificate Manager Private Certificate Authority | `acm-pca:ListCertificateAuthorities` |": "| AWS Certificate Manager Private Certificate Authority | `acm-pca:ListCertificateAuthorities` |",
    "| Amazon MQ |  |": "| Amazon MQ |  |",
    "| Amazon API Gateway | `apigateway:GET` |": "| Amazon API Gateway | `apigateway:GET` |",
    "| AWS App Runner | `apprunner:ListServices` |": "| AWS App Runner | `apprunner:ListServices` |",
    "| Amazon AppStream | `appstream:DescribeFleets` |": "| Amazon AppStream | `appstream:DescribeFleets` |",
    "| AWS AppSync | `appsync:ListGraphqlApis` |": "| AWS AppSync | `appsync:ListGraphqlApis` |",
    "| Amazon Athena | `athena:ListWorkGroups` |": "| Amazon Athena | `athena:ListWorkGroups` |",
    "| Amazon Aurora | `rds:DescribeDBClusters` |": "| Amazon Aurora | `rds:DescribeDBClusters` |",
    "| Amazon EC2 Auto Scaling | `autoscaling:DescribeAutoScalingGroups` |": "| Amazon EC2 Auto Scaling | `autoscaling:DescribeAutoScalingGroups` |",
    "| Amazon EC2 Auto Scaling (built-in) | `autoscaling:DescribeAutoScalingGroups` |": "| Amazon EC2 Auto Scaling (built-in) | `autoscaling:DescribeAutoScalingGroups` |",
    "| AWS Billing |  |": "| AWS Billing |  |",
    "| Amazon Keyspaces |  |": "| Amazon Keyspaces |  |",
    "| AWS Chatbot |  |": "| AWS Chatbot |  |",
    "| Amazon CloudFront | `cloudfront:ListDistributions` |": "| Amazon CloudFront | `cloudfront:ListDistributions` |",
    "| AWS CloudHSM | `cloudhsm:DescribeClusters` |": "| AWS CloudHSM | `cloudhsm:DescribeClusters` |",
    "| Amazon CloudSearch | `cloudsearch:DescribeDomains` |": "| Amazon CloudSearch | `cloudsearch:DescribeDomains` |",
    "| AWS CodeBuild | `codebuild:ListProjects` |": "| AWS CodeBuild | `codebuild:ListProjects` |",
    "| Amazon Cognito |  |": "| Amazon Cognito |  |",
    "| Amazon Connect |  |": "| Amazon Connect |  |",
    "| Amazon Elastic Kubernetes Service (EKS) | `eks:ListClusters` |": "| Amazon Elastic Kubernetes Service (EKS) | `eks:ListClusters` |",
    "| AWS DataSync | `datasync:ListTasks` |": "| AWS DataSync | `datasync:ListTasks` |",
    "| Amazon DynamoDB Accelerator (DAX) | `dax:DescribeClusters` |": "| Amazon DynamoDB Accelerator (DAX) | `dax:DescribeClusters` |",
    "| AWS Database Migration Service (AWS DMS) | `dms:DescribeReplicationInstances` |": "| AWS Database Migration Service (AWS DMS) | `dms:DescribeReplicationInstances` |",
    "| Amazon DocumentDB | `rds:DescribeDBClusters` |": "| Amazon DocumentDB | `rds:DescribeDBClusters` |",
    "| AWS Direct Connect | `directconnect:DescribeConnections` |": "| AWS Direct Connect | `directconnect:DescribeConnections` |",
    "| Amazon DynamoDB | `dynamodb:ListTables` |": "| Amazon DynamoDB | `dynamodb:ListTables` |",
    "| Amazon DynamoDB (built-in) | `dynamodb:ListTables`, `dynamodb:ListTagsOfResource` |": "| Amazon DynamoDB (built-in) | `dynamodb:ListTables`, `dynamodb:ListTagsOfResource` |",
    "| Amazon EBS | `ec2:DescribeVolumes` |": "| Amazon EBS | `ec2:DescribeVolumes` |",
    "| Amazon EBS (built-in) | `ec2:DescribeVolumes` |": "| Amazon EBS (built-in) | `ec2:DescribeVolumes` |",
    "| Amazon EC2 API |  |": "| Amazon EC2 API |  |",
    "| Amazon EC2 (built-in) | `ec2:DescribeInstances` |": "| Amazon EC2 (built-in) | `ec2:DescribeInstances` |",
    "| Amazon EC2 Spot Fleet | `ec2:DescribeSpotFleetRequests` |": "| Amazon EC2 Spot Fleet | `ec2:DescribeSpotFleetRequests` |",
    "| Amazon Elastic Container Service (ECS) | `ecs:ListClusters` |": "| Amazon Elastic Container Service (ECS) | `ecs:ListClusters` |",
    "| Amazon ECS Container Insights | `ecs:ListClusters` |": "| Amazon ECS Container Insights | `ecs:ListClusters` |",
    "| Amazon ElastiCache (EC) | `elasticache:DescribeCacheClusters` |": "| Amazon ElastiCache (EC) | `elasticache:DescribeCacheClusters` |",
    "| AWS Elastic Beanstalk | `elasticbeanstalk:DescribeEnvironments` |": "| AWS Elastic Beanstalk | `elasticbeanstalk:DescribeEnvironments` |",
    "| Amazon Elastic File System (EFS) | `elasticfilesystem:DescribeFileSystems` |": "| Amazon Elastic File System (EFS) | `elasticfilesystem:DescribeFileSystems` |",
    "| Amazon Elastic Inference |  |": "| Amazon Elastic Inference |  |",
    "| Amazon Elastic Map Reduce (EMR) | `elasticmapreduce:ListClusters` |": "| Amazon Elastic Map Reduce (EMR) | `elasticmapreduce:ListClusters` |",
    "| Amazon Elasticsearch Service (ES) | `es:ListDomainNames` |": "| Amazon Elasticsearch Service (ES) | `es:ListDomainNames` |",
    "| Amazon Elastic Transcoder | `elastictranscoder:ListPipelines` |": "| Amazon Elastic Transcoder | `elastictranscoder:ListPipelines` |",
    "| Amazon Elastic Load Balancer (ELB) (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |": "| Amazon Elastic Load Balancer (ELB) (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |",
    "| Amazon EventBridge | `events:ListEventBuses` |": "| Amazon EventBridge | `events:ListEventBuses` |",
    "| Amazon FSx | `fsx:DescribeFileSystems` |": "| Amazon FSx | `fsx:DescribeFileSystems` |",
    "| Amazon GameLift | `gamelift:ListFleets` |": "| Amazon GameLift | `gamelift:ListFleets` |",
    "| AWS Glue | `glue:GetJobs` |": "| AWS Glue | `glue:GetJobs` |",
    "| Amazon Inspector | `inspector:ListAssessmentTemplates` |": "| Amazon Inspector | `inspector:ListAssessmentTemplates` |",
    "| AWS Internet of Things (IoT) |  |": "| AWS Internet of Things (IoT) |  |",
    "| AWS IoT Analytics |  |": "| AWS IoT Analytics |  |",
    "| Amazon Managed Streaming for Kafka | `kafka:ListClusters` |": "| Amazon Managed Streaming for Kafka | `kafka:ListClusters` |",
    "| Amazon Kinesis Data Analytics | `kinesisanalytics:ListApplications` |": "| Amazon Kinesis Data Analytics | `kinesisanalytics:ListApplications` |",
    "| Amazon Data Firehose | `firehose:ListDeliveryStreams` |": "| Amazon Data Firehose | `firehose:ListDeliveryStreams` |",
    "| Amazon Kinesis Data Streams | `kinesis:ListStreams` |": "| Amazon Kinesis Data Streams | `kinesis:ListStreams` |",
    "| Amazon Kinesis Video Streams | `kinesisvideo:ListStreams` |": "| Amazon Kinesis Video Streams | `kinesisvideo:ListStreams` |",
    "| AWS Lambda | `lambda:ListFunctions` |": "| AWS Lambda | `lambda:ListFunctions` |",
    "| AWS Lambda (built-in) | `lambda:ListFunctions`, `lambda:ListTags` |": "| AWS Lambda (built-in) | `lambda:ListFunctions`, `lambda:ListTags` |",
    "| Amazon Lex | `lex:GetBots` |": "| Amazon Lex | `lex:GetBots` |",
    "| Amazon Application and Network Load Balancer (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |": "| Amazon Application and Network Load Balancer (built-in) | `elasticloadbalancing:DescribeInstanceHealth`, `elasticloadbalancing:DescribeListeners`, `elasticloadbalancing:DescribeLoadBalancers`, `elasticloadbalancing:DescribeRules`, `elasticloadbalancing:DescribeTags`, `elasticloadbalancing:DescribeTargetHealth` |",
    "| Amazon CloudWatch Logs | `logs:DescribeLogGroups` |": "| Amazon CloudWatch Logs | `logs:DescribeLogGroups` |",
    "| AWS Elemental MediaConnect | `mediaconnect:ListFlows` |": "| AWS Elemental MediaConnect | `mediaconnect:ListFlows` |",
    "| AWS Elemental MediaConvert | `mediaconvert:DescribeEndpoints` |": "| AWS Elemental MediaConvert | `mediaconvert:DescribeEndpoints` |",
    "| AWS Elemental MediaPackage Live | `mediapackage:ListChannels` |": "| AWS Elemental MediaPackage Live | `mediapackage:ListChannels` |",
    "| AWS Elemental MediaPackage Video on Demand | `mediapackage-vod:ListPackagingConfigurations` |": "| AWS Elemental MediaPackage Video on Demand | `mediapackage-vod:ListPackagingConfigurations` |",
    "| AWS Elemental MediaTailor | `mediatailor:ListPlaybackConfigurations` |": "| AWS Elemental MediaTailor | `mediatailor:ListPlaybackConfigurations` |",
    "| Amazon VPC NAT Gateways | `ec2:DescribeNatGateways` |": "| Amazon VPC NAT Gateways | `ec2:DescribeNatGateways` |",
    "| Amazon Neptune | `rds:DescribeDBClusters` |": "| Amazon Neptune | `rds:DescribeDBClusters` |",
    "| AWS OpsWorks | `opsworks:DescribeStacks` |": "| AWS OpsWorks | `opsworks:DescribeStacks` |",
    "| Amazon Polly |  |": "| Amazon Polly |  |",
    "| Amazon QLDB | `qldb:ListLedgers` |": "| Amazon QLDB | `qldb:ListLedgers` |",
    "| Amazon RDS | `rds:DescribeDBInstances` |": "| Amazon RDS | `rds:DescribeDBInstances` |",
    "| Amazon RDS (built-in) | `rds:DescribeDBInstances`, `rds:DescribeEvents`, `rds:ListTagsForResource` |": "| Amazon RDS (built-in) | `rds:DescribeDBInstances`, `rds:DescribeEvents`, `rds:ListTagsForResource` |",
    "| Amazon Redshift | `redshift:DescribeClusters` |": "| Amazon Redshift | `redshift:DescribeClusters` |",
    "| Amazon Rekognition |  |": "| Amazon Rekognition |  |",
    "| AWS RoboMaker | `robomaker:ListSimulationJobs` |": "| AWS RoboMaker | `robomaker:ListSimulationJobs` |",
    "| Amazon Route 53 | `route53:ListHostedZones` |": "| Amazon Route 53 | `route53:ListHostedZones` |",
    "| Amazon Route 53 Resolver | `route53resolver:ListResolverEndpoints` |": "| Amazon Route 53 Resolver | `route53resolver:ListResolverEndpoints` |",
    "| Amazon S3 | `s3:ListAllMyBuckets` |": "| Amazon S3 | `s3:ListAllMyBuckets` |",
    "| Amazon S3 (built-in) | `s3:ListAllMyBuckets` |": "| Amazon S3 (built-in) | `s3:ListAllMyBuckets` |",
    "| Amazon SageMaker Batch Transform Jobs |  |": "| Amazon SageMaker Batch Transform Jobs |  |",
    "| Amazon SageMaker Endpoint Instances | `sagemaker:ListEndpoints` |": "| Amazon SageMaker Endpoint Instances | `sagemaker:ListEndpoints` |",
    "| Amazon SageMaker Endpoints | `sagemaker:ListEndpoints` |": "| Amazon SageMaker Endpoints | `sagemaker:ListEndpoints` |",
    "| Amazon SageMaker Ground Truth |  |": "| Amazon SageMaker Ground Truth |  |",
    "| Amazon SageMaker Processing Jobs |  |": "| Amazon SageMaker Processing Jobs |  |",
    "| Amazon SageMaker Training Jobs |  |": "| Amazon SageMaker Training Jobs |  |",
    "| AWS Service Catalog |  |": "| AWS Service Catalog |  |",
    "| Amazon Simple Email Service (SES) |  |": "| Amazon Simple Email Service (SES) |  |",
    "| Amazon Simple Notification Service (SNS) | `sns:ListTopics` |": "| Amazon Simple Notification Service (SNS) | `sns:ListTopics` |",
    "| Amazon Simple Queue Service (SQS) | `sqs:ListQueues` |": "| Amazon Simple Queue Service (SQS) | `sqs:ListQueues` |",
    "| AWS Systems Manager - Run Command |  |": "| AWS Systems Manager - Run Command |  |",
    "| AWS Step Functions |  |": "| AWS Step Functions |  |",
    "| AWS Storage Gateway | `storagegateway:ListGateways` |": "| AWS Storage Gateway | `storagegateway:ListGateways` |",
    "| Amazon SWF | `swf:ListDomains` |": "| Amazon SWF | `swf:ListDomains` |",
    "| Amazon Textract |  |": "| Amazon Textract |  |",
    "| AWS IoT Things Graph |  |": "| AWS IoT Things Graph |  |",
    "| AWS Transfer Family | `transfer:ListServers` |": "| AWS Transfer Family | `transfer:ListServers` |",
    "| AWS Transit Gateway | `ec2:DescribeTransitGateways` |": "| AWS Transit Gateway | `ec2:DescribeTransitGateways` |",
    "| Amazon Translate |  |": "| Amazon Translate |  |",
    "| AWS Trusted Advisor |  |": "| AWS Trusted Advisor |  |",
    "| AWS API Usage |  |": "| AWS API Usage |  |",
    "| AWS Site-to-Site VPN | `ec2:DescribeVpnConnections` |": "| AWS Site-to-Site VPN | `ec2:DescribeVpnConnections` |",
    "| AWS WAF Classic |  |": "| AWS WAF Classic |  |",
    "| AWS WAF |  |": "| AWS WAF |  |",
    "| Amazon WorkMail | `workmail:ListOrganizations` |": "| Amazon WorkMail | `workmail:ListOrganizations` |",
    "| Amazon WorkSpaces | `workspaces:DescribeWorkspaces` |": "| Amazon WorkSpaces | `workspaces:DescribeWorkspaces` |",
    "Example of JSON policy for one single service.": "Пример JSON-политики для одного сервиса.",
    "JSON policy for Amazon API Gateway": "JSON-политика для Amazon API Gateway",
    "In this example, from the complete list of permissions you need to select": "В этом примере из полного списка разрешений вам необходимо выбрать",
    "* `\"apigateway:GET\"` for **Amazon API Gateway**": "* `\"apigateway:GET\"` для **Amazon API Gateway**",
    "* `\"cloudwatch:GetMetricData\"`, `\"cloudwatch:GetMetricStatistics\"`, `\"cloudwatch:ListMetrics\"`, `\"sts:GetCallerIdentity\"`, `\"tag:GetResources\"`, `\"tag:GetTagKeys\"`, and `\"ec2:DescribeAvailabilityZones\"` for **All AWS cloud services**.": "* `\"cloudwatch:GetMetricData\"`, `\"cloudwatch:GetMetricStatistics\"`, `\"cloudwatch:ListMetrics\"`, `\"sts:GetCallerIdentity\"`, `\"tag:GetResources\"`, `\"tag:GetTagKeys\"` и `\"ec2:DescribeAvailabilityZones\"` для **всех облачных сервисов AWS**.",
    "## Install OneAgent Optional": "## Установка OneAgent (необязательно)",
    "To install and customize OneAgent, see [Deploy OneAgent on AWS Elastic Beanstalk](/managed/ingest-from/amazon-web-services/integrate-into-aws/aws-beanstalk \"Install OneAgent on AWS Elastic Beanstalk.\").": "Для установки и настройки OneAgent см. [Развёртывание OneAgent на AWS Elastic Beanstalk](/managed/ingest-from/amazon-web-services/integrate-into-aws/aws-beanstalk \"Установка OneAgent на AWS Elastic Beanstalk.\").",
    "### AWS endpoints that need to be reachable from ActiveGate with corresponding AWS services": "### Эндпоинты AWS, которые должны быть доступны из ActiveGate, с соответствующими сервисами AWS",
    "| Endpoint | Service |": "| Эндпоинт | Сервис |",
    "| `autoscaling.<REGION>.amazonaws.com` | Amazon EC2 Auto Scaling (built-in), Amazon EC2 Auto Scaling |": "| `autoscaling.<REGION>.amazonaws.com` | Amazon EC2 Auto Scaling (built-in), Amazon EC2 Auto Scaling |",
    "| `lambda.<REGION>.amazonaws.com` | AWS Lambda (built-in), AWS Lambda |": "| `lambda.<REGION>.amazonaws.com` | AWS Lambda (built-in), AWS Lambda |",
    "| `elasticloadbalancing.<REGION>.amazonaws.com` | Amazon Application and Network Load Balancer (built-in), Amazon Elastic Load Balancer (ELB) (built-in) |": "| `elasticloadbalancing.<REGION>.amazonaws.com` | Amazon Application and Network Load Balancer (built-in), Amazon Elastic Load Balancer (ELB) (built-in) |",
    "| `dynamodb.<REGION>.amazonaws.com` | Amazon DynamoDB (built-in), Amazon DynamoDB |": "| `dynamodb.<REGION>.amazonaws.com` | Amazon DynamoDB (built-in), Amazon DynamoDB |",
    "| `ec2.<REGION>.amazonaws.com` | Amazon EBS (built-in), Amazon EC2 (built-in), Amazon EBS, Amazon EC2 Spot Fleet, Amazon VPC NAT Gateways, AWS Transit Gateway, AWS Site-to-Site VPN |": "| `ec2.<REGION>.amazonaws.com` | Amazon EBS (built-in), Amazon EC2 (built-in), Amazon EBS, Amazon EC2 Spot Fleet, Amazon VPC NAT Gateways, AWS Transit Gateway, AWS Site-to-Site VPN |",
    "| `rds.<REGION>.amazonaws.com` | Amazon RDS (built-in), Amazon Aurora, Amazon DocumentDB, Amazon Neptune, Amazon RDS |": "| `rds.<REGION>.amazonaws.com` | Amazon RDS (built-in), Amazon Aurora, Amazon DocumentDB, Amazon Neptune, Amazon RDS |",
    "| `s3.<REGION>.amazonaws.com` | Amazon S3 (built-in) |": "| `s3.<REGION>.amazonaws.com` | Amazon S3 (built-in) |",
    "| `acm-pca.<REGION>.amazonaws.com` | AWS Certificate Manager Private Certificate Authority |": "| `acm-pca.<REGION>.amazonaws.com` | AWS Certificate Manager Private Certificate Authority |",
    "| `apigateway.<REGION>.amazonaws.com` | Amazon API Gateway |": "| `apigateway.<REGION>.amazonaws.com` | Amazon API Gateway |",
    "| `apprunner.<REGION>.amazonaws.com` | AWS App Runner |": "| `apprunner.<REGION>.amazonaws.com` | AWS App Runner |",
    "| `appstream2.<REGION>.amazonaws.com` | Amazon AppStream |": "| `appstream2.<REGION>.amazonaws.com` | Amazon AppStream |",
    "| `appsync.<REGION>.amazonaws.com` | AWS AppSync |": "| `appsync.<REGION>.amazonaws.com` | AWS AppSync |",
    "| `athena.<REGION>.amazonaws.com` | Amazon Athena |": "| `athena.<REGION>.amazonaws.com` | Amazon Athena |",
    "| `cloudfront.amazonaws.com` | Amazon CloudFront |": "| `cloudfront.amazonaws.com` | Amazon CloudFront |",
    "| `cloudhsmv2.<REGION>.amazonaws.com` | AWS CloudHSM |": "| `cloudhsmv2.<REGION>.amazonaws.com` | AWS CloudHSM |",
    "| `cloudsearch.<REGION>.amazonaws.com` | Amazon CloudSearch |": "| `cloudsearch.<REGION>.amazonaws.com` | Amazon CloudSearch |",
    "| `codebuild.<REGION>.amazonaws.com` | AWS CodeBuild |": "| `codebuild.<REGION>.amazonaws.com` | AWS CodeBuild |",
    "| `datasync.<REGION>.amazonaws.com` | AWS DataSync |": "| `datasync.<REGION>.amazonaws.com` | AWS DataSync |",
    "| `dax.<REGION>.amazonaws.com` | Amazon DynamoDB Accelerator (DAX) |": "| `dax.<REGION>.amazonaws.com` | Amazon DynamoDB Accelerator (DAX) |",
    "| `dms.<REGION>.amazonaws.com` | AWS Database Migration Service (AWS DMS) |": "| `dms.<REGION>.amazonaws.com` | AWS Database Migration Service (AWS DMS) |",
    "| `directconnect.<REGION>.amazonaws.com` | AWS Direct Connect |": "| `directconnect.<REGION>.amazonaws.com` | AWS Direct Connect |",
    "| `ecs.<REGION>.amazonaws.com` | Amazon Elastic Container Service (ECS), Amazon ECS Container Insights |": "| `ecs.<REGION>.amazonaws.com` | Amazon Elastic Container Service (ECS), Amazon ECS Container Insights |",
    "| `elasticfilesystem.<REGION>.amazonaws.com` | Amazon Elastic File System (EFS) |": "| `elasticfilesystem.<REGION>.amazonaws.com` | Amazon Elastic File System (EFS) |",
    "| `eks.<REGION>.amazonaws.com` | Amazon Elastic Kubernetes Service (EKS) |": "| `eks.<REGION>.amazonaws.com` | Amazon Elastic Kubernetes Service (EKS) |",
    "| `elasticache.<REGION>.amazonaws.com` | Amazon ElastiCache (EC) |": "| `elasticache.<REGION>.amazonaws.com` | Amazon ElastiCache (EC) |",
    "| `elasticbeanstalk.<REGION>.amazonaws.com` | AWS Elastic Beanstalk |": "| `elasticbeanstalk.<REGION>.amazonaws.com` | AWS Elastic Beanstalk |",
    "| `elastictranscoder.<REGION>.amazonaws.com` | Amazon Elastic Transcoder |": "| `elastictranscoder.<REGION>.amazonaws.com` | Amazon Elastic Transcoder |",
    "| `es.<REGION>.amazonaws.com` | Amazon Elasticsearch Service (ES) |": "| `es.<REGION>.amazonaws.com` | Amazon Elasticsearch Service (ES) |",
    "| `events.<REGION>.amazonaws.com` | Amazon EventBridge |": "| `events.<REGION>.amazonaws.com` | Amazon EventBridge |",
    "| `fsx.<REGION>.amazonaws.com` | Amazon FSx |": "| `fsx.<REGION>.amazonaws.com` | Amazon FSx |",
    "| `gamelift.<REGION>.amazonaws.com` | Amazon GameLift |": "| `gamelift.<REGION>.amazonaws.com` | Amazon GameLift |",
    "| `glue.<REGION>.amazonaws.com` | AWS Glue |": "| `glue.<REGION>.amazonaws.com` | AWS Glue |",
    "| `inspector.<REGION>.amazonaws.com` | Amazon Inspector |": "| `inspector.<REGION>.amazonaws.com` | Amazon Inspector |",
    "| `kafka.<REGION>.amazonaws.com` | Amazon Managed Streaming for Kafka |": "| `kafka.<REGION>.amazonaws.com` | Amazon Managed Streaming for Kafka |",
    "| `models.lex.<REGION>.amazonaws.com` | Amazon Lex |": "| `models.lex.<REGION>.amazonaws.com` | Amazon Lex |",
    "| `logs.<REGION>.amazonaws.com` | Amazon CloudWatch Logs |": "| `logs.<REGION>.amazonaws.com` | Amazon CloudWatch Logs |",
    "| `api.mediatailor.<REGION>.amazonaws.com` | AWS Elemental MediaTailor |": "| `api.mediatailor.<REGION>.amazonaws.com` | AWS Elemental MediaTailor |",
    "| `mediaconnect.<REGION>.amazonaws.com` | AWS Elemental MediaConnect |": "| `mediaconnect.<REGION>.amazonaws.com` | AWS Elemental MediaConnect |",
    "| `mediapackage.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Live |": "| `mediapackage.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Live |",
    "| `mediapackage-vod.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Video on Demand |": "| `mediapackage-vod.<REGION>.amazonaws.com` | AWS Elemental MediaPackage Video on Demand |",
    "| `opsworks.<REGION>.amazonaws.com` | AWS OpsWorks |": "| `opsworks.<REGION>.amazonaws.com` | AWS OpsWorks |",
    "| `qldb.<REGION>.amazonaws.com` | Amazon QLDB |": "| `qldb.<REGION>.amazonaws.com` | Amazon QLDB |",
    "| `redshift.<REGION>.amazonaws.com` | Amazon Redshift |": "| `redshift.<REGION>.amazonaws.com` | Amazon Redshift |",
    "| `robomaker.<REGION>.amazonaws.com` | AWS RoboMaker |": "| `robomaker.<REGION>.amazonaws.com` | AWS RoboMaker |",
    "| `route53.amazonaws.com` | Amazon Route 53 |": "| `route53.amazonaws.com` | Amazon Route 53 |",
    "| `route53resolver.<REGION>.amazonaws.com` | Amazon Route 53 Resolver |": "| `route53resolver.<REGION>.amazonaws.com` | Amazon Route 53 Resolver |",
    "| `api.sagemaker.<REGION>.amazonaws.com` | Amazon SageMaker Endpoints, Amazon SageMaker Endpoint Instances |": "| `api.sagemaker.<REGION>.amazonaws.com` | Amazon SageMaker Endpoints, Amazon SageMaker Endpoint Instances |",
    "| `sns.<REGION>.amazonaws.com` | Amazon Simple Notification Service (SNS) |": "| `sns.<REGION>.amazonaws.com` | Amazon Simple Notification Service (SNS) |",
    "| `sqs.<REGION>.amazonaws.com` | Amazon Simple Queue Service (SQS) |": "| `sqs.<REGION>.amazonaws.com` | Amazon Simple Queue Service (SQS) |",
    "| `storagegateway.<REGION>.amazonaws.com` | AWS Storage Gateway |": "| `storagegateway.<REGION>.amazonaws.com` | AWS Storage Gateway |",
    "| `swf.<REGION>.amazonaws.com` | Amazon SWF |": "| `swf.<REGION>.amazonaws.com` | Amazon SWF |",
    "| `transfer.<REGION>.amazonaws.com` | AWS Transfer Family |": "| `transfer.<REGION>.amazonaws.com` | AWS Transfer Family |",
    "| `workmail.<REGION>.amazonaws.com` | Amazon WorkMail |": "| `workmail.<REGION>.amazonaws.com` | Amazon WorkMail |",
    "| `workspaces.<REGION>.amazonaws.com` | Amazon WorkSpaces |": "| `workspaces.<REGION>.amazonaws.com` | Amazon WorkSpaces |",
    "## Enable monitoring": "## Включение мониторинга",
    "To learn how to enable service monitoring, see [Enable service monitoring](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-metrics-ingest/aws-enable-service-monitoring \"Enable AWS monitoring in Dynatrace.\").": "Чтобы узнать, как включить мониторинг сервиса, см. [Enable service monitoring](/managed/ingest-from/amazon-web-services/integrate-with-aws/aws-metrics-ingest/aws-enable-service-monitoring \"Включение мониторинга AWS в Dynatrace.\").",
    "## View service metrics": "## Просмотр метрик сервиса",
    "You can view the service metrics in your Dynatrace environment either on the **custom device overview page** or on your **Dashboards** page.": "Метрики сервиса можно просматривать в окружении Dynatrace на странице **обзора пользовательского устройства** или на странице **Панели мониторинга**.",
    "### View metrics on the custom device overview page": "### Просмотр метрик на странице обзора пользовательского устройства",
    "To access the custom device overview page": "Для доступа к странице обзора пользовательского устройства",
    "1. Go to **Technologies & Processes**.": "1. Перейдите в **Technologies & Processes**.",
    "2. Filter by service name and select the relevant custom device group.": "2. Отфильтруйте по имени сервиса и выберите соответствующую группу пользовательских устройств.",
    "3. Once you select the custom device group, you're on the **custom device group overview page**.": "3. После выбора группы пользовательских устройств вы окажетесь на странице **обзора группы пользовательских устройств**.",
    "4. The **custom device group overview page** lists all instances (custom devices) belonging to the group. Select an instance to view the **custom device overview page**.": "4. На странице **обзора группы пользовательских устройств** перечислены все экземпляры (пользовательские устройства), принадлежащие группе. Выберите экземпляр, чтобы перейти на страницу **обзора пользовательского устройства**.",
    "### View metrics on your dashboard": "### Просмотр метрик на панели мониторинга",
    "After you add the service to monitoring, a preset dashboard containing all recommended metrics is automatically listed on your **Dashboards** page. To look for specific dashboards, filter by **Preset** and then by **Name**.": "После добавления сервиса в мониторинг предустановленная панель мониторинга со всеми рекомендуемыми метриками автоматически отображается на странице **Панели мониторинга**. Для поиска конкретных панелей используйте фильтр **Preset**, затем **Name**.",
    "![AWS presets](https://dt-cdn.net/images/image-26-1645-389f58aa89.png)": "![AWS presets](https://dt-cdn.net/images/image-26-1645-389f58aa89.png)",
    "AWS presets": "AWS presets",
    "For existing monitored services, you might need to resave your credentials for the preset dashboard to appear on the **Dashboards** page. To resave your credentials, go to **Settings** > **Cloud and virtualization** > **AWS**, select the desired AWS instance, and then select **Save**.": "Для уже отслеживаемых сервисов может потребоваться повторно сохранить учётные данные, чтобы предустановленная панель отобразилась на странице **Панели мониторинга**. Для этого перейдите в **Settings** > **Cloud and virtualization** > **AWS**, выберите нужный экземпляр AWS и нажмите **Save**.",
    "You can't make changes on a preset dashboard directly, but you can clone and edit it. To clone a dashboard, open the browse menu (**…**) and select **Clone**.": "Вносить изменения в предустановленную панель напрямую нельзя, но её можно клонировать и редактировать. Для клонирования откройте меню просмотра (**...**) и выберите **Clone**.",
    "To remove a dashboard from the dashboards page, you can hide it. To hide a dashboard, open the browse menu (**…**) and select **Hide**.": "Чтобы убрать панель мониторинга со страницы, её можно скрыть. Для этого откройте меню просмотра (**...**) и выберите **Hide**.",
    "Hiding a dashboard doesn't affect other users.": "Скрытие панели мониторинга не влияет на других пользователей.",
    "![Clone hide AWS](https://dt-cdn.net/images/2020-12-10-15-04-09-1502-b899a29d73.png)": "![Clone hide AWS](https://dt-cdn.net/images/2020-12-10-15-04-09-1502-b899a29d73.png)",
    "Clone hide AWS": "Clone hide AWS",
    "To check the availability of preset dashboards for each AWS service, see the list below.": "Чтобы проверить доступность предустановленных панелей мониторинга для каждого сервиса AWS, см. список ниже.",
    "### Preset dashboard availability list": "### Список доступности предустановленных панелей мониторинга",
    "| AWS service | Preset dashboard |": "| Сервис AWS | Предустановленная панель |",
    "| Amazon EC2 Auto Scaling (built-in) | Not applicable |": "| Amazon EC2 Auto Scaling (built-in) | Недоступна |",
    "| AWS Lambda (built-in) | Not applicable |": "| AWS Lambda (built-in) | Недоступна |",
    "| Amazon Application and Network Load Balancer (built-in) | Not applicable |": "| Amazon Application and Network Load Balancer (built-in) | Недоступна |",
    "| Amazon DynamoDB (built-in) | Not applicable |": "| Amazon DynamoDB (built-in) | Недоступна |",
    "| Amazon EBS (built-in) | Not applicable |": "| Amazon EBS (built-in) | Недоступна |",
    "| Amazon EC2 (built-in) | Not applicable |": "| Amazon EC2 (built-in) | Недоступна |",
    "| Amazon Elastic Load Balancer (ELB) (built-in) | Not applicable |": "| Amazon Elastic Load Balancer (ELB) (built-in) | Недоступна |",
    "| Amazon RDS (built-in) | Not applicable |": "| Amazon RDS (built-in) | Недоступна |",
    "| Amazon S3 (built-in) | Not applicable |": "| Amazon S3 (built-in) | Недоступна |",
    "| AWS Certificate Manager Private Certificate Authority | Not applicable |": "| AWS Certificate Manager Private Certificate Authority | Недоступна |",
    "| All monitored Amazon services | Not applicable |": "| All monitored Amazon services | Недоступна |",
    "| Amazon API Gateway | Not applicable |": "| Amazon API Gateway | Недоступна |",
    "| AWS App Runner | Not applicable |": "| AWS App Runner | Недоступна |",
    "| Amazon AppStream | Applicable |": "| Amazon AppStream | Доступна |",
    "| AWS AppSync | Applicable |": "| AWS AppSync | Доступна |",
    "| Amazon Athena | Applicable |": "| Amazon Athena | Доступна |",
    "| Amazon Aurora | Not applicable |": "| Amazon Aurora | Недоступна |",
    "| Amazon EC2 Auto Scaling | Applicable |": "| Amazon EC2 Auto Scaling | Доступна |",
    "| AWS Billing | Applicable |": "| AWS Billing | Доступна |",
    "| Amazon Keyspaces | Applicable |": "| Amazon Keyspaces | Доступна |",
    "| AWS Chatbot | Applicable |": "| AWS Chatbot | Доступна |",
    "| Amazon CloudFront | Not applicable |": "| Amazon CloudFront | Недоступна |",
    "| AWS CloudHSM | Applicable |": "| AWS CloudHSM | Доступна |",
    "| Amazon CloudSearch | Applicable |": "| Amazon CloudSearch | Доступна |",
    "| AWS CodeBuild | Applicable |": "| AWS CodeBuild | Доступна |",
    "| Amazon Cognito | Not applicable |": "| Amazon Cognito | Недоступна |",
    "| Amazon Connect | Applicable |": "| Amazon Connect | Доступна |",
    "| AWS DataSync | Applicable |": "| AWS DataSync | Доступна |",
    "| Amazon DynamoDB Accelerator (DAX) | Applicable |": "| Amazon DynamoDB Accelerator (DAX) | Доступна |",
    "| AWS Database Migration Service (AWS DMS) | Applicable |": "| AWS Database Migration Service (AWS DMS) | Доступна |",
    "| Amazon DocumentDB | Applicable |": "| Amazon DocumentDB | Доступна |",
    "| AWS Direct Connect | Applicable |": "| AWS Direct Connect | Доступна |",
    "| Amazon DynamoDB | Not applicable |": "| Amazon DynamoDB | Недоступна |",
    "| Amazon EBS | Not applicable |": "| Amazon EBS | Недоступна |",
    "| Amazon EC2 Spot Fleet | Not applicable |": "| Amazon EC2 Spot Fleet | Недоступна |",
    "| Amazon EC2 API | Applicable |": "| Amazon EC2 API | Доступна |",
    "| Amazon Elastic Container Service (ECS) | Not applicable |": "| Amazon Elastic Container Service (ECS) | Недоступна |",
    "| Amazon ECS Container Insights | Applicable |": "| Amazon ECS Container Insights | Доступна |",
    "| Amazon Elastic File System (EFS) | Not applicable |": "| Amazon Elastic File System (EFS) | Недоступна |",
    "| Amazon Elastic Kubernetes Service (EKS) | Applicable |": "| Amazon Elastic Kubernetes Service (EKS) | Доступна |",
    "| Amazon ElastiCache (EC) | Not applicable |": "| Amazon ElastiCache (EC) | Недоступна |",
    "| AWS Elastic Beanstalk | Applicable |": "| AWS Elastic Beanstalk | Доступна |",
    "| Amazon Elastic Inference | Applicable |": "| Amazon Elastic Inference | Доступна |",
    "| Amazon Elastic Transcoder | Applicable |": "| Amazon Elastic Transcoder | Доступна |",
    "| Amazon Elastic Map Reduce (EMR) | Not applicable |": "| Amazon Elastic Map Reduce (EMR) | Недоступна |",
    "| Amazon Elasticsearch Service (ES) | Not applicable |": "| Amazon Elasticsearch Service (ES) | Недоступна |",
    "| Amazon EventBridge | Applicable |": "| Amazon EventBridge | Доступна |",
    "| Amazon FSx | Applicable |": "| Amazon FSx | Доступна |",
    "| Amazon GameLift | Applicable |": "| Amazon GameLift | Доступна |",
    "| AWS Glue | Not applicable |": "| AWS Glue | Недоступна |",
    "| Amazon Inspector | Applicable |": "| Amazon Inspector | Доступна |",
    "| AWS Internet of Things (IoT) | Not applicable |": "| AWS Internet of Things (IoT) | Недоступна |",
    "| AWS IoT Things Graph | Applicable |": "| AWS IoT Things Graph | Доступна |",
    "| AWS IoT Analytics | Applicable |": "| AWS IoT Analytics | Доступна |",
    "| Amazon Managed Streaming for Kafka | Applicable |": "| Amazon Managed Streaming for Kafka | Доступна |",
    "| Amazon Kinesis Data Analytics | Not applicable |": "| Amazon Kinesis Data Analytics | Недоступна |",
    "| Amazon Data Firehose | Not applicable |": "| Amazon Data Firehose | Недоступна |",
    "| Amazon Kinesis Data Streams | Not applicable |": "| Amazon Kinesis Data Streams | Недоступна |",
    "| Amazon Kinesis Video Streams | Not applicable |": "| Amazon Kinesis Video Streams | Недоступна |",
    "| AWS Lambda | Not applicable |": "| AWS Lambda | Недоступна |",
    "| Amazon Lex | Applicable |": "| Amazon Lex | Доступна |",
    "| Amazon CloudWatch Logs | Applicable |": "| Amazon CloudWatch Logs | Доступна |",
    "| AWS Elemental MediaTailor | Applicable |": "| AWS Elemental MediaTailor | Доступна |",
    "| AWS Elemental MediaConnect | Applicable |": "| AWS Elemental MediaConnect | Доступна |",
    "| AWS Elemental MediaConvert | Applicable |": "| AWS Elemental MediaConvert | Доступна |",
    "| AWS Elemental MediaPackage Live | Applicable |": "| AWS Elemental MediaPackage Live | Доступна |",
    "| AWS Elemental MediaPackage Video on Demand | Applicable |": "| AWS Elemental MediaPackage Video on Demand | Доступна |",
    "| Amazon MQ | Applicable |": "| Amazon MQ | Доступна |",
    "| Amazon VPC NAT Gateways | Not applicable |": "| Amazon VPC NAT Gateways | Недоступна |",
    "| Amazon Neptune | Applicable |": "| Amazon Neptune | Доступна |",
    "| AWS OpsWorks | Applicable |": "| AWS OpsWorks | Доступна |",
    "| Amazon Polly | Applicable |": "| Amazon Polly | Доступна |",
    "| Amazon QLDB | Applicable |": "| Amazon QLDB | Доступна |",
    "| Amazon RDS | Not applicable |": "| Amazon RDS | Недоступна |",
    "| Amazon Redshift | Not applicable |": "| Amazon Redshift | Недоступна |",
    "| Amazon Rekognition | Applicable |": "| Amazon Rekognition | Доступна |",
    "| AWS RoboMaker | Applicable |": "| AWS RoboMaker | Доступна |",
    "| Amazon Route 53 | Applicable |": "| Amazon Route 53 | Доступна |",
    "| Amazon Route 53 Resolver | Applicable |": "| Amazon Route 53 Resolver | Доступна |",
    "| Amazon S3 | Not applicable |": "| Amazon S3 | Недоступна |",
    "| Amazon SageMaker Batch Transform Jobs | Not applicable |": "| Amazon SageMaker Batch Transform Jobs | Недоступна |",
    "| Amazon SageMaker Endpoints | Not applicable |": "| Amazon SageMaker Endpoints | Недоступна |",
    "| Amazon SageMaker Endpoint Instances | Not applicable |": "| Amazon SageMaker Endpoint Instances | Недоступна |",
    "| Amazon SageMaker Ground Truth | Not applicable |": "| Amazon SageMaker Ground Truth | Недоступна |",
    "| Amazon SageMaker Processing Jobs | Not applicable |": "| Amazon SageMaker Processing Jobs | Недоступна |",
    "| Amazon SageMaker Training Jobs | Not applicable |": "| Amazon SageMaker Training Jobs | Недоступна |",
    "| AWS Service Catalog | Applicable |": "| AWS Service Catalog | Доступна |",
    "| Amazon Simple Email Service (SES) | Not applicable |": "| Amazon Simple Email Service (SES) | Недоступна |",
    "| Amazon Simple Notification Service (SNS) | Not applicable |": "| Amazon Simple Notification Service (SNS) | Недоступна |",
    "| Amazon Simple Queue Service (SQS) | Not applicable |": "| Amazon Simple Queue Service (SQS) | Недоступна |",
    "| AWS Systems Manager - Run Command | Applicable |": "| AWS Systems Manager - Run Command | Доступна |",
    "| AWS Step Functions | Applicable |": "| AWS Step Functions | Доступна |",
    "| AWS Storage Gateway | Applicable |": "| AWS Storage Gateway | Доступна |",
    "| Amazon SWF | Applicable |": "| Amazon SWF | Доступна |",
    "| Amazon Textract | Applicable |": "| Amazon Textract | Доступна |",
    "| AWS Transfer Family | Applicable |": "| AWS Transfer Family | Доступна |",
    "| AWS Transit Gateway | Applicable |": "| AWS Transit Gateway | Доступна |",
    "| Amazon Translate | Applicable |": "| Amazon Translate | Доступна |",
    "| AWS Trusted Advisor | Applicable |": "| AWS Trusted Advisor | Доступна |",
    "| AWS API Usage | Applicable |": "| AWS API Usage | Доступна |",
    "| AWS Site-to-Site VPN | Applicable |": "| AWS Site-to-Site VPN | Доступна |",
    "| AWS WAF Classic | Applicable |": "| AWS WAF Classic | Доступна |",
    "| AWS WAF | Applicable |": "| AWS WAF | Доступна |",
    "| Amazon WorkMail | Applicable |": "| Amazon WorkMail | Доступна |",
    "| Amazon WorkSpaces | Applicable |": "| Amazon WorkSpaces | Доступна |",
    "![Elastic beanstalk](https://dt-cdn.net/images/dashboard-48-1016-8c1715cd7e.png)": "![Elastic beanstalk](https://dt-cdn.net/images/dashboard-48-1016-8c1715cd7e.png)",
    "Elastic beanstalk": "Elastic beanstalk",
    "## Available metrics": "## Доступные метрики",
    "| Name | Description | Unit | Statistics | Dimensions | Recommended |": "| Название | Описание | Единица | Статистика | Измерения | Рекомендуемая |",
    "| --- | --- | --- | --- | --- | --- |": "| --- | --- | --- | --- | --- | --- |",
    "| ApplicationLatencyP10 | The average amount of time, in seconds, it takes to complete the fastest 10% of requests (instance and environment) | Seconds | Multi | EnvironmentName, InstanceId |  |": "| ApplicationLatencyP10 | Среднее время, в секундах, необходимое для обработки самых быстрых 10% запросов (экземпляр и окружение) | Seconds | Multi | EnvironmentName, InstanceId |  |",
    "| ApplicationLatencyP10 |  | Seconds | Multi | EnvironmentName |  |": "| ApplicationLatencyP10 |  | Seconds | Multi | EnvironmentName |  |",
    "| ApplicationLatencyP50 | The average amount of time, in seconds, it takes to complete the fastest 50% of requests (instance and environment) | Seconds | Multi | EnvironmentName, InstanceId |  |": "| ApplicationLatencyP50 | Среднее время, в секундах, необходимое для обработки самых быстрых 50% запросов (экземпляр и окружение) | Seconds | Multi | EnvironmentName, InstanceId |  |",
    "| ApplicationLatencyP50 |  | Seconds | Multi | EnvironmentName |  |": "| ApplicationLatencyP50 |  | Seconds | Multi | EnvironmentName |  |",
    "| ApplicationLatencyP75 | The average amount of time, in seconds, it takes to complete the fastest 75% of requests (instance and environment) | Seconds | Multi | EnvironmentName, InstanceId |  |": "| ApplicationLatencyP75 | Среднее время, в секундах, необходимое для обработки самых быстрых 75% запросов (экземпляр и окружение) | Seconds | Multi | EnvironmentName, InstanceId |  |",
    "| ApplicationLatencyP75 |  | Seconds | Multi | EnvironmentName |  |": "| ApplicationLatencyP75 |  | Seconds | Multi | EnvironmentName |  |",
    "| ApplicationLatencyP85 | The average amount of time, in seconds, it takes to complete the fastest 85% of requests (instance and environment) | Seconds | Multi | EnvironmentName, InstanceId |  |": "| ApplicationLatencyP85 | Среднее время, в секундах, необходимое для обработки самых быстрых 85% запросов (экземпляр и окружение) | Seconds | Multi | EnvironmentName, InstanceId |  |",
    "| ApplicationLatencyP85 |  | Seconds | Multi | EnvironmentName |  |": "| ApplicationLatencyP85 |  | Seconds | Multi | EnvironmentName |  |",
    "| ApplicationLatencyP90 | The average amount of time, in seconds, it takes to complete the fastest 90% of requests (instance and environment) | Seconds | Multi | EnvironmentName, InstanceId |  |": "| ApplicationLatencyP90 | Среднее время, в секундах, необходимое для обработки самых быстрых 90% запросов (экземпляр и окружение) | Seconds | Multi | EnvironmentName, InstanceId |  |",
    "| ApplicationLatencyP90 |  | Seconds | Multi | EnvironmentName | Applicable |": "| ApplicationLatencyP90 |  | Seconds | Multi | EnvironmentName | Доступна |",
    "| ApplicationLatencyP95 | The average amount of time, in seconds, it takes to complete the fastest 95% of requests (instance and environment) | Seconds | Multi | EnvironmentName, InstanceId |  |": "| ApplicationLatencyP95 | Среднее время, в секундах, необходимое для обработки самых быстрых 95% запросов (экземпляр и окружение) | Seconds | Multi | EnvironmentName, InstanceId |  |",
    "| ApplicationLatencyP95 |  | Seconds | Multi | EnvironmentName |  |": "| ApplicationLatencyP95 |  | Seconds | Multi | EnvironmentName |  |",
    "| ApplicationLatencyP99 | The average amount of time, in seconds, it takes to complete the fastest 99% of requests (instance and environment) | Seconds | Multi | EnvironmentName, InstanceId |  |": "| ApplicationLatencyP99 | Среднее время, в секундах, необходимое для обработки самых быстрых 99% запросов (экземпляр и окружение) | Seconds | Multi | EnvironmentName, InstanceId |  |",
    "| ApplicationLatencyP99 |  | Seconds | Multi | EnvironmentName |  |": "| ApplicationLatencyP99 |  | Seconds | Multi | EnvironmentName |  |",
    "| ApplicationLatencyP99.9 | The average amount of time, in seconds, it takes to complete the fastest 99.9% of requests (instance and environment) | Seconds | Multi | EnvironmentName, InstanceId |  |": "| ApplicationLatencyP99.9 | Среднее время, в секундах, необходимое для обработки самых быстрых 99.9% запросов (экземпляр и окружение) | Seconds | Multi | EnvironmentName, InstanceId |  |",
    "| ApplicationLatencyP99.9 |  | Seconds | Multi | EnvironmentName |  |": "| ApplicationLatencyP99.9 |  | Seconds | Multi | EnvironmentName |  |",
    "| ApplicationRequestsTotal | The total number of requests completed by the instance or environment | Count | Sum | EnvironmentName, InstanceId |  |": "| ApplicationRequestsTotal | Общее количество запросов, обработанных экземпляром или окружением | Count | Sum | EnvironmentName, InstanceId |  |",
    "| ApplicationRequestsTotal |  | Count | Sum | EnvironmentName | Applicable |": "| ApplicationRequestsTotal |  | Count | Sum | EnvironmentName | Доступна |",
    "| ApplicationRequests2xx | The number of requests that completed with a `2XX` status code (instance and environment) | Count | Sum | EnvironmentName, InstanceId |  |": "| ApplicationRequests2xx | Количество запросов, завершённых с кодом состояния `2XX` (экземпляр и окружение) | Count | Sum | EnvironmentName, InstanceId |  |",
    "| ApplicationRequests2xx |  | Count | Sum | EnvironmentName |  |": "| ApplicationRequests2xx |  | Count | Sum | EnvironmentName |  |",
    "| ApplicationRequests3xx | The number of requests that completed with a `3XX` status code (instance and environment) | Count | Sum | EnvironmentName, InstanceId |  |": "| ApplicationRequests3xx | Количество запросов, завершённых с кодом состояния `3XX` (экземпляр и окружение) | Count | Sum | EnvironmentName, InstanceId |  |",
    "| ApplicationRequests3xx |  | Count | Sum | EnvironmentName |  |": "| ApplicationRequests3xx |  | Count | Sum | EnvironmentName |  |",
    "| ApplicationRequests4xx | The number of requests that completed with a `4XX` status code (instance and environment) | Count | Sum | EnvironmentName, InstanceId |  |": "| ApplicationRequests4xx | Количество запросов, завершённых с кодом состояния `4XX` (экземпляр и окружение) | Count | Sum | EnvironmentName, InstanceId |  |",
    "| ApplicationRequests4xx |  | Count | Sum | EnvironmentName | Applicable |": "| ApplicationRequests4xx |  | Count | Sum | EnvironmentName | Доступна |",
    "| ApplicationRequests5xx | The number of requests that completed with a `5XX` status code (instance and environment) | Count | Sum | EnvironmentName, InstanceId |  |": "| ApplicationRequests5xx | Количество запросов, завершённых с кодом состояния `5XX` (экземпляр и окружение) | Count | Sum | EnvironmentName, InstanceId |  |",
    "| ApplicationRequests5xx |  | Count | Sum | EnvironmentName | Applicable |": "| ApplicationRequests5xx |  | Count | Sum | EnvironmentName | Доступна |",
    "| CPUIdle | The percentage of time the CPU was in idle state in the last minute (instance only) | Percent | Multi | EnvironmentName, InstanceId |  |": "| CPUIdle | Процент времени, в течение которого ЦП находился в состоянии простоя за последнюю минуту (только экземпляр) | Percent | Multi | EnvironmentName, InstanceId |  |",
    "| CPUIowait | The percentage of time the CPU was in `iowait` state in the last minute (instance only) | Percent | Multi | EnvironmentName, InstanceId |  |": "| CPUIowait | Процент времени, в течение которого ЦП находился в состоянии `iowait` за последнюю минуту (только экземпляр) | Percent | Multi | EnvironmentName, InstanceId |  |",
    "| CPUIrq | The percentage of time the CPU was in `irq` state in the last minute (instance only) | Percent | Multi | EnvironmentName, InstanceId |  |": "| CPUIrq | Процент времени, в течение которого ЦП находился в состоянии `irq` за последнюю минуту (только экземпляр) | Percent | Multi | EnvironmentName, InstanceId |  |",
    "| CPUNice | The percentage of time the CPU was in `nice` state in the last minute (instance only) | Percent | Multi | EnvironmentName, InstanceId |  |": "| CPUNice | Процент времени, в течение которого ЦП находился в состоянии `nice` за последнюю минуту (только экземпляр) | Percent | Multi | EnvironmentName, InstanceId |  |",
    "| CPUPrivileged | The percentage of time the CPU was in `privileged` state in the last minute (instance only) | Percent | Multi | EnvironmentName, InstanceId |  |": "| CPUPrivileged | Процент времени, в течение которого ЦП находился в привилегированном (`privileged`) состоянии за последнюю минуту (только экземпляр) | Percent | Multi | EnvironmentName, InstanceId |  |",
    "| CPUSoftirq | The percentage of time the CPU was in `softirq` state in the last minute (instance only) | Percent | Multi | EnvironmentName, InstanceId |  |": "| CPUSoftirq | Процент времени, в течение которого ЦП находился в состоянии `softirq` за последнюю минуту (только экземпляр) | Percent | Multi | EnvironmentName, InstanceId |  |",
    "| CPUSystem | The percentage of time the CPU was in `system` state in the last minute (instance only) | Percent | Multi | EnvironmentName, InstanceId |  |": "| CPUSystem | Процент времени, в течение которого ЦП находился в системном (`system`) состоянии за последнюю минуту (только экземпляр) | Percent | Multi | EnvironmentName, InstanceId |  |",
    "| CPUUser | The percentage of time the CPU was in `user` state in the last minute (instance only) | Percent | Multi | EnvironmentName, InstanceId |  |": "| CPUUser | Процент времени, в течение которого ЦП находился в пользовательском (`user`) состоянии за последнюю минуту (только экземпляр) | Percent | Multi | EnvironmentName, InstanceId |  |",
    "| EnvironmentHealth | The current health status of the environment, with seven possible values: 0 - `OK`, 1 - `Info`, 5 - `Unknown`, 10 - `No data`, 15 - `Warning`, 20 - `Degraded`, and 25 - `Severe` | None | Multi | EnvironmentName | Applicable |": "| EnvironmentHealth | Текущий статус работоспособности окружения; возможные значения: 0 - `OK`, 1 - `Info`, 5 - `Unknown`, 10 - `No data`, 15 - `Warning`, 20 - `Degraded`, 25 - `Severe` | None | Multi | EnvironmentName | Доступна |",
    "| InstanceHealth | The current health status of the instance, with seven possible values: 0 - `OK`, 1 - `Info`, 5 - `Unknown`, 10 - `No data`, 15 - `Warning`, 20 - `Degraded`, and 25 - `Severe` | None | Multi | EnvironmentName, InstanceId | Applicable |": "| InstanceHealth | Текущий статус работоспособности экземпляра; возможные значения: 0 - `OK`, 1 - `Info`, 5 - `Unknown`, 10 - `No data`, 15 - `Warning`, 20 - `Degraded`, 25 - `Severe` | None | Multi | EnvironmentName, InstanceId | Доступна |",
    "| InstancesDegraded | The number of instances in the environment with `degraded` health status (environment only) | Count | Multi | EnvironmentName |  |": "| InstancesDegraded | Количество экземпляров в окружении со статусом работоспособности `degraded` (только окружение) | Count | Multi | EnvironmentName |  |",
    "| InstancesInfo | The number of instances in the environment with `info` health status (environment only) | Count | Multi | EnvironmentName |  |": "| InstancesInfo | Количество экземпляров в окружении со статусом работоспособности `info` (только окружение) | Count | Multi | EnvironmentName |  |",
    "| InstancesNoData | The number of instances for which no data is being received (environment only) | Count | Multi | EnvironmentName |  |": "| InstancesNoData | Количество экземпляров, данные по которым не поступают (только окружение) | Count | Multi | EnvironmentName |  |",
    "| InstancesOk | The number of instances in the environment with `OK` health status (environment only) | Count | Multi | EnvironmentName |  |": "| InstancesOk | Количество экземпляров в окружении со статусом работоспособности `OK` (только окружение) | Count | Multi | EnvironmentName |  |",
    "| InstancesPending | The number of instances in the environment with `pending` health status (environment only) | Count | Multi | EnvironmentName |  |": "| InstancesPending | Количество экземпляров в окружении со статусом работоспособности `pending` (только окружение) | Count | Multi | EnvironmentName |  |",
    "| InstancesSevere | The number of instances in the environment with `severe` health status (environment only) | Count | Multi | EnvironmentName |  |": "| InstancesSevere | Количество экземпляров в окружении со статусом работоспособности `severe` (только окружение) | Count | Multi | EnvironmentName |  |",
    "| InstancesUnknown | The number of instances in the environment with `unknown` health status (environment only) | Count | Multi | EnvironmentName |  |": "| InstancesUnknown | Количество экземпляров в окружении со статусом работоспособности `unknown` (только окружение) | Count | Multi | EnvironmentName |  |",
    "| InstancesWarning | The number of instances in the environment with `warning` health status (environment only) | Count | Multi | EnvironmentName |  |": "| InstancesWarning | Количество экземпляров в окружении со статусом работоспособности `warning` (только окружение) | Count | Multi | EnvironmentName |  |",
    "| LoadAverage1min | The average CPU load of the instance over the last minute (instance only) | Percent | Multi | EnvironmentName, InstanceId |  |": "| LoadAverage1min | Средняя нагрузка на ЦП экземпляра за последнюю минуту (только экземпляр) | Percent | Multi | EnvironmentName, InstanceId |  |",
    "| LoadAverage5min | The average CPU load of the instance over the last five minutes (instance only) | Percent | Multi | EnvironmentName, InstanceId |  |": "| LoadAverage5min | Средняя нагрузка на ЦП экземпляра за последние пять минут (только экземпляр) | Percent | Multi | EnvironmentName, InstanceId |  |",
    "| RootFilesystemUtil | The percentage of disk space that's in use (instance only) | Percent | Multi | EnvironmentName, InstanceId |  |": "| RootFilesystemUtil | Процент используемого дискового пространства (только экземпляр) | Percent | Multi | EnvironmentName, InstanceId |  |",
    "| RootFilesystemUtil |  | Percent | Multi | EnvironmentName |  |": "| RootFilesystemUtil |  | Percent | Multi | EnvironmentName |  |",
}

PASS = set()

build_one(REL, "cloudwatch-elastic-beanstalk.md", TRANS, PASS)
qa_one(REL, "cloudwatch-elastic-beanstalk.md")
